### ISSUE TITLE
migration command text differs from 3.1 and 2.2.6

### ISSUE THREAD

**Issue by xiaotupansy** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1001]
### Steps to reproduce
When creating a new table, here's the command text generated:

2.2.6:
```sql
CREATE TABLE `t_Order1` (
    `Id` varchar(20) NOT NULL,
    `IsDeleted` tinyint(1) NOT NULL,
    `TenantId` varchar(20)  NULL,
    `Remark` longtext NULL,
    CONSTRAINT `PK_t_Order1` PRIMARY KEY (`Id`),
    CONSTRAINT `FK_t_Order1_t_Tenant_TenantId` FOREIGN KEY (`TenantId`) REFERENCES `t_Tenant` (`Id`) ON DELETE RESTRICT
);
```

3.1:
```sql
CREATE TABLE `t_Order1` (
    `Id` varchar(20) CHARACTER SET utf8mb4 NOT NULL,
    `IsDeleted` tinyint(1) NOT NULL,
    `TenantId` varchar(20) CHARACTER SET utf8mb4 NULL,
    `Remark` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_t_Order1` PRIMARY KEY (`Id`),
    CONSTRAINT `FK_t_Order1_t_Tenant_TenantId` FOREIGN KEY (`TenantId`) REFERENCES `t_Tenant` (`Id`) ON DELETE RESTRICT
);
```

### The issue
Referencing column `TenantId` and referenced column `Id` in foreign key constraint `FK_t_Order1_t_Tenant_TenantId` are incompatible.

### Further technical details

I've set default character set `utf8mb4` and collation `utf8mb4_unicode_ci` for this database.
For column `TenantId`, if character set is set, then the collation will be `utf8mb4_0900_ai_ci`,
if not, the collation will be `utf8mb4_unicode_ci`.

MySQL version: 8.0.17
Operating system: centos 7
Pomelo.EntityFrameworkCore.MySql version:3.1
Microsoft.AspNetCore.App version:3.1

### Expection

Can you give me the option to close character set in generated sql?

**Comment by lauxjpn** [comment]
There are multiple options (here are just a few):

### Use `CharSetBehavior(behavior)`

```c#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder
        .UseMySql(connectionString, b => b.CharSetBehavior(CharSetBehavior.NeverAppend));
}
```
Use `MySqlDbContextOptionsBuilder.CharSetBehavior(CharSetBehavior))` to specify, for which columns to output a charset in general. Use `CharSetBehavior.NeverAppend`, if you do not want to output charsets at all.

In case you explicitly set a charset or collation for a column (see next section), than that charset or collation will take precedence over the `CharSetBehavior`.

### Use `HasCharSet(string)` or `HasCollation(string)`

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<t_Order1>(entity =>
    {
        entity.Property(e => e.TenantId)
            .HasCharSet('utf8mb4') // set the charset for the column
            .HasCollation('utf8mb4_unicode_ci') // set the collation for the column
    });
}
```

You can use either `HasCharSet(string)` to explicitly specify as charset for a column, or `HasCollation(string)` to explicitly specify the collation, or both.

**Comment by xiaotupansy** [comment]
Works.

Thank you @lauxjpn !
