### ISSUE TITLE
Is there an example how to use Pomelo.EntityFrameworkCore.MySql with .NET 4.7.2?

### ISSUE THREAD

**Issue by Michael-Schmid-ST** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1003]
### Steps to reproduce
Visual Studio 2017
Pomelo.EntityFrameworkCore.MySql 3.1.0

My DbContext looks like:
```
using Microsoft.EntityFrameworkCore;


class TestDbContext : DbContext
    {
        public DbSet<Product> Products { get; set; }
        public DbSet<Item> Items { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.UseMySql("server=ip;port=3306;database=TEST;uid=user;password=password;persistsecurityinfo=True;");

    }
```

### The issue
I have tried to use Pomelo.EntityFrameworkCore.MySql with .NET 4.7.2 without success. I get the following error when enabling migrations with Enable-Migrations on the Packet-Manager-Console:

Error: System.ArgumentException: The type 'TestDbContext' does not inherit from DbContext. The DbMigrationsConfiguration.ContextType property must be set to a type that inherits from DbContext.

I am not sure how to implement TestDbContext with .NET 4.7.2.

### Further technical details
Database: MariaDB 10.4.11

**Comment by lauxjpn** [comment]
The implementation should look the same for .NET Framework 4.7.2 and .NET Core 3.1:

### Working sample code

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Pomelo.EntityFrameworkCore.MySql.Storage;
using System.Diagnostics;
using System.Linq;

namespace IssueConsoleTemplateNet472
{
    public class IceCream
    {
        public int IceCreamId { get; set; }
        public string Name { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql("server=127.0.0.1;port=3306;user=root;password=;database=Issue1003",
                    b => b.ServerVersion(new ServerVersion("10.4.11-mariadb")))
                .UseLoggerFactory(LoggerFactory.Create(b => b
                    .AddConsole()
                    .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream>(entity =>
            {
                entity.Property(e => e.Name)
                    .HasMaxLength(512)
                    .IsRequired();
            });
        }
    }

    internal class Program
    {
        private static void Main()
        {
            using (var context = new Context())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.IceCreams.AddRange(
                    new IceCream { Name = "Vanilla" },
                    new IceCream { Name = "Chocolate" },
                    new IceCream { Name = "Strawberry" }
                );

                context.SaveChanges();

                var iceCreams = context.IceCreams
                    .OrderBy(i => i.IceCreamId)
                    .ToList();

                Debug.Assert(iceCreams.Count == 3);
                Debug.Assert(iceCreams[0].Name == "Vanilla");
                Debug.Assert(iceCreams[0].IceCreamId == 1);
            }
        }
    }
}
```

I uploaded the full .NET Framework 4.7.2 [sample solution](https://github.com/lauxjpn/Issue1003). The first two commits do not use migrations, while the last one does (see next section).

### Using EF Core tools

> I get the following error when enabling migrations with Enable-Migrations on the Packet-Manager-Console:
>
> Error: System.ArgumentException: The type 'TestDbContext' does not inherit from DbContext. The DbMigrationsConfiguration.ContextType property must be set to a type that inherits from DbContext.

Pomelo is a EF Core based provider, so you should make sure to use the EF Core tools when adding migrations, scaffolding databases etc.

#### Using the Package Manager Console in Visual Studio

When using the Package Manager Console in Visual Studio, run the following command in there to install the tools (see the [EF Core docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#other-versions-and-project-types) for further details):

```
Install-Package Microsoft.EntityFrameworkCore.Tools
```

You can then start to add migrations right away (there is no `Enable-Migrations` command anymore like previously in Entity Framework):

```
Add-Migration MyFirstMigration
```

#### Using Windows PowerShell or any other Command Line (including on Linux or macOS):

To install the EF Core command line tools (.NET CLI), run the following command (for further details, see the [EF Core docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)). You might need to run the command elevated, when using the `--global` option:

```
dotnet tool install --global dotnet-ef
```

To add your first migration, just run the following command:

```
dotnet ef migrations add MyFirstMigration
```

**Comment by Michael-Schmid-ST** [comment]
Thank you so much. It was of great help to me.

My issue resulted that Microsoft.EntityFrameworkCore.Tools was not installed properly.
