### ISSUE TITLE
Adding a migration is not taking collation into account

### ISSUE THREAD

**Issue by CyberBotX** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1004]
### Steps to reproduce
I'm not sure if this is an error on my part or on the library's part. I'm attempting to force a collation of `utf8mb4_unicode_ci` on a string column. I'm doing something similar to this:
```
builder.Property(p => p.Value).HasCollation("utf8mb4_unicode_ci");
```
However, when I make a migration from the Package Manager Console using `Add-Migration`, like so:
```
Add-Migration MigrationName -Project NetStandardProject -StartupProject NetCoreProject
```
The generated `Migration` class does not contain an annotation on the field. I'll see only the following in the migration under the table's columns:
```
Value = table.Column<string>(nullable: true)
```
Also, when I look at the debugging of the create table command for one of the above when I use the `Migrate()` command from a .NET Core project, I'll see:
```
`Value` longtext CHARACTER SET utf8mb4 NULL
```
It doesn't seem to matter if the column in question is a key or not, the result is the same. Because of the lack of collation, I end up getting all my string-based columns as `utf8mb4_general_ci` instead. I've also tried to turn off character set appending in the configuration using:
```
optionsBuilder.UseMySql(connection, b => b.CharSetBehavior(CharSetBehavior.NeverAppend));
```
This also seems to be having no effect as I am still getting the character set appended.

### The issue
I expected that doing the above would set the collation of the column properly, but instead it is being ignored completely.

### Further technical details
MySQL version: MariaDB 10.4.11
Operating system: Windows 10 64-bit 1909 (client) / FreeBSD 12.1-RELEASE-p1 (server)
Pomelo.EntityFrameworkCore.MySql version: 3.1.0
Microsoft.AspNetCore.App version: (Not ASP.NET) .NET Standard 2.1 / .NET Core 3.1

Other details about my project setup:
I've got my DbContext and entities in a .NET Standard 2.1 project and I create the migration by using a separate .NET Core 3.1 project that stores the connection details. The migration is saved to the .NET Standard project.

As far as on the server end, I've got the following in my `my.cnf` file:
```
[client]
default_character_set=utf8mb4

[server]
collation_server=utf8mb4_unicode_ci
init_connect='SET CHARACTER SET utf8mb4'
character_set_server=utf8mb4
character_set_client_handshake=OFF
innodb_compression_default=ON
innodb_compression_level=9
```

**Comment by lauxjpn** [comment]
I will take a look at this tomorrow. But this is going to be a bug that we need to fix.

**Comment by lauxjpn** [comment]
@CyberBotX Thank you for reporting this issue!

The [fix](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1009) will be part of an upcoming service release (`3.1.1`).
