### ISSUE TITLE
Entity framework core and MySql.Data in the same project

### ISSUE THREAD

**Issue by lebartha** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1006]
### Steps to reproduce
MySql.Data + Pomelo.EntityFrameworkCore.MySql in the same solution but different projects.
### The issue
If we have a visual studio solution, where one project uses MySQL.Data nuget package for legacy code that creates MySqlConnection objects, and another project that uses EF Core with Pomelo nuget package, we are getting ambiguous errors in VS when creating these legacy MySqlConnection objects, because both projects use the same namespace (MySql.Data.MySqlClient). Is it possible somehow to fix this?

### Further technical details

MySQL version: 5.7.29
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.1

**Comment by mguinness** [comment]
See [Use a different namespace](https://github.com/mysql-net/MySqlConnector/issues/189) for MySqlConnector.

**Comment by lauxjpn** [comment]
Especially the last comment looks good: https://github.com/mysql-net/MySqlConnector/issues/189#issuecomment-543583735
The same principal can also be found on [StackOverflow](https://stackoverflow.com/a/50504273/2618319).

**Comment by lebartha** [comment]
Thanks for the help, now i feel super dumb :)
