### ISSUE TITLE
Error in BytesToDateTimeConverter with Blazor 

### ISSUE THREAD

**Issue by mathragoso** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1013]
The error occur on select with:
```
public List<Onu> GetLast(int n){
            return DbContext.Onu.Include(x => x.User).Include(x => x.Type).Include(x => x.Olt).Skip(Math.Max(0, DbContext.Onu.Count() - n)).ToList();
        }
```
```
WASM: System.TypeInitializationException: The type initializer for 'Pomelo.EntityFrameworkCore.MySql.Storage.Internal.BytesToDateTimeConverter' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
```

### Further technical details

MySQL version: 8.0.17 
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.1.0
Microsoft.AspNetCore.Blazor version: 3.1.0-preview4.19579.2

Other details about my project setup:

Contexts, Models and Repositories projects: netstandard2.1

**Comment by mguinness** [comment]
See [Can EF Core work on Blazor WASM?](https://github.com/dotnet/efcore/issues/18908)
