### ISSUE TITLE
Auto Increment (int) not working Ver. 3.1

### ISSUE THREAD

**Issue by cetubig** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1015]
Auto increment is not working on version 3.1 even I removed [Key] and [DatabaseGenerated(DatabaseGeneratedOption.Identity)] 

I also tried setting in Fluent API but no luck.

            modelBuilder.Entity<UserActionLog>()
               .Property<int>("Id")
               .ValueGeneratedOnAdd(); // Autogenerated

            modelBuilder.Entity<UserActionLog>()
                .HasKey("Id"); // Unique

**Comment by cetubig** [comment]
I have resolved it by setting in fluent API.

modelBuilder.Entity<UserActionLog>(entity =>
{
	entity.HasKey(e => e.Id)
		 .HasName("PRIMARY");
	entity.Property(e => e.Id).HasColumnType("int(11) auto_increment")
		  .ValueGeneratedOnAdd();
});

**Comment by lauxjpn** [comment]
> `entity.Property(e => e.Id).HasColumnType("int(11) auto_increment")`

This should not be necessary. If you post the SQL of the `CREATE TABLE` statement for the `UserActionLog` table, the model (the `UserActionLog` class) and the full model definition for the class (the `modelBuilder.Entity<UserActionLog>` code) we can take a look at why this is not working for you.

**Comment by lasse16** [comment]
@lauxjpn 
I ran into the same problem and @cetubig 's workaround worked for me.

These are the relevant lines from my `DbContext`:
``` csharp
modelBuilder.Entity<Demo>(entity =>
            {
                entity.HasKey(e => e.MatchId);
                entity.ToTable("Demo");

                entity.Property(e => e.MatchId).HasColumnType("bigint(20) auto_increment")
                .ValueGeneratedOnAdd();
```

This is the generated SQL for the migration:
``` sql
ALTER TABLE `Demo` MODIFY COLUMN `MatchId` bigint(20) auto_increment NOT NULL AUTO_INCREMENT;
```

Here is the original `CREATE TABLE`-SQL: 
(There's been a few migrations in between but none affecting the `MatchId` column.)
``` sql
CREATE TABLE `Demo` (
    `MatchId` int(11) NOT NULL,
    
    //[...] more columns in between
    
    CONSTRAINT `PK_Demo` PRIMARY KEY (`MatchId`)
);
``` 

I tested removing the `.HasColumnType()` call and generated a new migration for that.
Resulting in the proper SQL-statement :
``` sql
ALTER TABLE `Demo` MODIFY COLUMN `MatchId` bigint NOT NULL AUTO_INCREMENT;
```

This is the proper statement which should have been generated in the first place, however , for whatever reason, it was not. 

Feel free to ask if you need any more information from me.

**PS.**

It took me a while to find the `Generate`-Policies for Pomelo. 
I found these lines in `Pomelo.EntityFrameworkCore.MySql.Migrations.MySqlMigrationsSqlGenerator`.  
Maybe add them into a documentation somewhere.

```csharp
switch (matchType)
                {
                    case "tinyint":
                    case "smallint":
                    case "mediumint":
                    case "int":
                    case "bigint":
                        autoIncrement = true;
                        break;
                    case "datetime":
                        if (!_options.ServerVersion.SupportsDateTimeCurrentTimestamp)
                        {
                            throw new InvalidOperationException(
                                $"Error in {table}.{name}: DATETIME does not support values generated " +
                                $"on Add or Update in versions lower than {ServerVersion.GetSupport(ServerVersion.DateTimeCurrentTimestampSupportKey)}. Try explicitly setting the column type to TIMESTAMP.");
                        }

                        goto case "timestamp";
                    case "timestamp":
                        operation.DefaultValueSql = $"CURRENT_TIMESTAMP({matchLen})";
                        break;
                }
```

**Comment by lauxjpn** [comment]
@lasse16 An `auto_increment` attribute should never be part of the FluentAPI's column type in the first place. I am pretty sure, that the current versions of Pomelo don't do that.

The code that you referenced is responsible for generating the actual SQL code for the migration (not the C# files). I has nothing to do with the issue you are having.

So the question is: How did the `auto_increment` end up in the column type in the first place?

It could be possible (I haven't checked), that some older version of Pomelo's migration or scaffolding code did generate a model definition (scaffolding) or snapshot (migration) with column types that could include a `auto_increment` attribute.
It is however very possible, that the initial model definition was not generated by Pomelo at all, and was manually written.
Maybe you can elaborate on that. In case you _did_ generate the original model definition, please specify how (e.g. scaffolding) and which version of Pomelo was used at the time.

Also, please post the actual model class of the `Demo` entity (C# class) and tell us, whether the excerpt of the model definition code you posted is the actual model definition, or generated code of a migration snapshot.
