### ISSUE TITLE
.Where( r=>r.Name.StartsWith( "W" ) produces this where clause that does not work.

### ISSUE THREAD

**Issue by kampilan** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1026]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

### The issue
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Further technical details

MySQL version: 
Operating system: 
Pomelo.EntityFrameworkCore.MySql version:
Microsoft.AspNetCore.App version:

Other details about my project setup:

**Comment by kampilan** [comment]
.Where( r=>r.Name.StartsWith( "W" )) produces this where clause that does not work.

WHERE `s`.`Name` IS NOT NULL AND ((`s`.`Name` LIKE CONCAT('W', '%')) AND (LEFT(`s`.`Name`, CHAR_LENGTH(CONVERT('W' USING utf8mb4) COLLATE utf8mb4_bin)) = CONVERT('W' USING utf8mb4) COLLATE utf8mb4_bin))

It works fine when everything after ((`s`.`Name` LIKE CONCAT('W', '%')) is removed

Any ideas?
Thanks
Jim

**Comment by lauxjpn** [comment]
We will need more information than that. Please post the model of the entity (class) this about, the model definition (FluentAPI), the SQL of the `CREATE TABLE` statement of the table in question and the full error message or exception (if you get one).
Also, if you expect the query to return something specific, we might also need to take a look at the row you expect the query to return from the table.

The issue *could* be related to #996, but with so little context information, we cannot say yet.

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/495 and resolution using [EF.Functions.Like()](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-entity-framework-core-2-0/#like-query-operator) method.

**Comment by kampilan** [comment]
Same issue (non-issue). I just didn't put 2 and 2 together when I was reading the other issues.
Thanks

**Comment by lauxjpn** [comment]
@kampilan Can you elaborate a bit more, what the actual issue was? Thanks!

**Comment by kampilan** [comment]
As you pointed out, my issue was the same as #996

**Comment by lauxjpn** [comment]
@kampilan I see. I am probably fixing this one over the weekend.
