### ISSUE TITLE
Cannot Mapping Point to MySql

### ISSUE THREAD

**Issue by maian1891** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1033]
### Steps to reproduce
![image](https://user-images.githubusercontent.com/18574898/75242583-fd387e80-57fa-11ea-8e3b-a0f85c0393a1.png)

![image](https://user-images.githubusercontent.com/18574898/75242724-37a21b80-57fb-11ea-909f-eb3f42a29dc2.png)

### The issue
I cannot map 'Point' from Model entity framework to 'Point' in MySQL.
Can you pls give me some ideas?

Thanks!!!

**Comment by lauxjpn** [comment]
Pomelo does not support spatial types yet. But We have planned support for this for one of the next releases. See #488

**Comment by maian1891** [comment]
> Pomelo does not support spatial types yet. But we have planned support for this feature for one of the next releases. See #488

Thank you so much!!!
