### ISSUE TITLE
lower case tables names required, had to run the migration to create tables names in lower case

### ISSUE THREAD

**Issue by Parbil** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1035]
### Steps to reproduce
Mac OS, XAMPP My SQL my tables got created with actual names Such Users while running migration scripts.But When I run system cannot find table is it looking for a table name in lowercase users.

After changing table to lower in migration script it worked 

### The issue
Somehow the system looks table name in lowercase

### Further technical details
MAC Os
XAMPP MY SQL
Other details about my project setup:

**Comment by lauxjpn** [comment]
If I understand you correctly, you manually create a table first using SQL. This table name uses both, uppercase and lowercase characters, like `User`.

But when you run a migration command like `dotnet ef migrations add MyMigration --verbose`, the migration script uses lowercase-only names, like `user`.

Is that what happens?

**Comment by Parbil** [comment]
Yes, Now it is working. I deleted all scripts also removed and added pomelo packages and recreated the migration scripts . It is working without changing any MySQL server settings.
Thanks
