### ISSUE TITLE
Issue with custom TagHelper and InvalidOperationException: Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first. MySql.Data.MySqlClient.MySqlCommand.set_CommandText(string value) in MySqlCommand.cs, line 147

### ISSUE THREAD

**Issue by Nerdtek** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1041]
### Steps to reproduce
Here is the TagHelper code:
```c#
       [HtmlAttributeName("identity-role")]
        public string Role { get; set; }
        public override async Task ProcessAsync(TagHelperContext context,
        TagHelperOutput output)
        {
            List<string> names = new List<string>();
 
            IdentityRole role = await roleManager.FindByIdAsync(Role).ConfigureAwait(true);
            if (role != null)
            {
                foreach (var user in userManager.Users)
                {
                    if (user != null
                    && await userManager.IsInRoleAsync(user, role.Name).ConfigureAwait(true))
                    {
                        names.Add(user.UserName);
                    }
                }
            }
            _ = output.Content.SetContent(names.Count == 0 ? "No Users" : string.Join(", ", names));
        }
```

The line mentioned in the exception is:
IdentityRole role = await roleManager.FindByIdAsync(Role).ConfigureAwait(true);

I can't seem to get the Razor view code to paste properly here, but the line mentioned in the exception is here:

```html
<td identity-role="@role.Id"></td>
```

### The issue
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
`An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.
MySql.Data.MySqlClient.MySqlCommand.set_CommandText(string value) in MySqlCommand.cs, line 147`
Stack trace:
`InvalidOperationException: Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.
MySql.Data.MySqlClient.MySqlCommand.set_CommandText(string value) in MySqlCommand.cs
Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+AsyncEnumerator.InitializeReaderAsync(DbContext _, bool result, CancellationToken cancellationToken)
Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync<TState, TResult>(TState state, Func<DbContext, TState, CancellationToken, Task<TResult>> operation, Func<DbContext, TState, CancellationToken, Task<ExecutionResult<TResult>>> verifySucceeded, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+AsyncEnumerator.MoveNextAsync()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<TSource>(IAsyncEnumerable<TSource> asyncEnumerable, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<TSource>(IAsyncEnumerable<TSource> asyncEnumerable, CancellationToken cancellationToken)
MSLIS.Infrastructure.RoleUsersTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output) in RoleUsersTagHelper.cs
+
            IdentityRole role = await roleManager.FindByIdAsync(Role).ConfigureAwait(true);
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)
AspNetCore.Views_RoleAdmin_Index.ExecuteAsync() in Index.cshtml
+
                <td identity-role="@role.Id"></td>
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Further technical details

MySQL version: MariaDb 10.4
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.1.1
Microsoft.AspNetCore.App version: 3.1

Other details about my project setup:
Running this from Visual Studio 2019 Version 16.4.6
This runs perfectly when setup with MSSQL, it seems only when the mysql handler is used that the exception fires.

**Comment by mguinness** [comment]
See https://github.com/dotnet/efcore/issues/20041

**Comment by Nerdtek** [comment]
Tried using the recommended method from the issue mentioned, and still getting an exception this time it's code I used to move the list of users to a list as recommended in the issue you referred to.

`

        public override async Task ProcessAsync(TagHelperContext context,
        TagHelperOutput output)
        {
            List<string> names = new List<string>();
            List<AppUser> users = userManager.Users.ToList();
 
            IdentityRole role = await roleManager.FindByIdAsync(Role).ConfigureAwait(true);
            if (role != null)
            {                
                foreach (var user in users)
                {
                    if (user != null
                    && await userManager.IsInRoleAsync(user, role.Name).ConfigureAwait(true))
                    {
                        names.Add(user.UserName);
                    }
                }
            }
            _ = output.Content.SetContent(names.Count == 0 ? "No Users" : string.Join(", ", names));
        }

`

So now the exception trips on the List<AppUser> users = userManger.Users.ToList(); line.

It appears that MySqlCommand.cs is still exceptioning on line 147 so it seems to be the same issue.  

What do I need to do to get around this, or is it even the same problem?

**Comment by Nerdtek** [comment]
I tried this 
`

foreach (var user in userManager.Users.ToList())

`
and now the exception happens on userManager.IsInRoleAsync(user, role.Name).ConfigureAwait(true))

**Comment by lauxjpn** [comment]
The code in both of your previous posts looks good. It's therefore likely, that while you fixed the issue the method you posted, there is still a similar issue up the call stack.

**Comment by Nerdtek** [comment]
There isn't anything other than a constructor in the TagHelper.  I'm really confused in how to fix this.

**Comment by Nerdtek** [comment]
Also when I looked again at the line that is throwing the original exception it is not even in the foreach loop.  So this is a different issue than what is mentioned in the issue you mentioned.  It's my RoleManager that's being complained about which is before the for loop.

**Comment by Nerdtek** [comment]
Here is the complete code: (The insert code function is messed on this site)

`

{
    [HtmlTargetElement("td", Attributes = "identity-role")]
    public class RoleUsersTagHelper : TagHelper
    {
        private UserManager<AppUser> userManager;
        private RoleManager<IdentityRole> roleManager;
        
        public RoleUsersTagHelper(UserManager<AppUser> usermgr,
        RoleManager<IdentityRole> rolemgr)
        {
            userManager = usermgr;
            roleManager = rolemgr;
        }

        [HtmlAttributeName("identity-role")]
        public string Role { get; set; }

        public override async Task ProcessAsync(TagHelperContext context,
        TagHelperOutput output)
        {
            List<string> names = new List<string>();            
 
            IdentityRole role = await roleManager.FindByIdAsync(Role).ConfigureAwait(true);

            if (role != null)
            {                
                foreach (var user in userManager.Users)
                {
                    if (user != null && await userManager.IsInRoleAsync(user, role.Name).ConfigureAwait(true))
                    {
                        names.Add(user.UserName);
                    }
                }
            }
            _ = output.Content.SetContent(names.Count == 0 ? "No Users" : string.Join(", ", names));
        }
    }
}
`

**Comment by lauxjpn** [comment]
> The insert code function is messed on this site

I edited all you posts to use correct code syntax (edit them again to take a look at the syntax). Basically, use `` `code` `` for inline code and

<pre>
```c#
my
multiline
c#
code
```
</pre>

for multiline code.
GitHub uses [Markdown](https://guides.github.com/features/mastering-markdown/).

---

As for the actual issue, it is very likely that your issue is still the one that @mguinness referenced.

So you need to trace, why the underlying connection already has a data read open, or to be more specific, where the data reader has been opened.

Looking at your stacktrace, this might happen in your `Index.cshtml` file. I could imagine a scenario, where a loop over some `DbSet<>` property from your `DbContext` is used in the file, either in form of tags or in form of actual C# code and your `RoleUsersTagHelper.ProcessAsync` method is called inside this loop.

So please post the `Index.cshtml` code and also a [logging](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging) output (with either `LogLevel.Debug` or `LogLevel.Trace`; remove your connection string, if it contains sensitive data).

**Comment by Nerdtek** [comment]
Ok thanks, that's brilliant.  I will get the logging, but probably won't post until Monday Mar 16th as I am pretty much done at work.

**Comment by Nerdtek** [comment]
Here is the `index.cshtml` file
```html
@model IEnumerable<IdentityRole>

<div class="bg-primary m-1 p-1"><h4>Roles</h4></div>

<div class="text-danger" asp-validation-summary="ModelOnly"></div>

<table class="table table-sm table-bordered table-bordered">
    <tr><th>Id</th><th>Name</th><th>Users</th></tr>
    @if(Model.Count() == 0)
    {
        <tr><td colspan="4" class="text-center">No Roles</td></tr>
    } else
    {
        foreach (var role in Model)
        {
            <tr>
                <td>@role.Id</td>
                <td>@role.Name</td>
                <td identity-role="@role.Id"></td>
                <td>
                    <form asp-action="Delete" asp-route-id="@role.Id" method="post">
                        <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@role.Id">Edit</a>
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    }
</table>
<a class="btn btn-primary" asp-action="Create">Create</a>
```

**Comment by lauxjpn** [comment]
There is the `foreach` loop. It is iterating over `Model`. Take a look at the code, that sets/initializes the `Model` property. It's probably constructing an `IQueryable<IdentityRole>` (meaning, its missing a `ToList()` call at the end of the query). So the query gets executed not when setting the `Model` property (or before), but when iterating over the `foreach` loop.

This would be the exact issue @mguinness referenced. The foreach loop executes the query and iterates over the returned records from the data reader, one by one (which means, it is open as long as your code is in the `foreach` loop).

**Comment by Nerdtek** [comment]
I went into my controller that sends the model to the view and changed the two places where the roles are sent and which indeed was an `IQueryable`, and added the `.ToList()` method to them and am still getting an exception.

This time on the line that checks to see if a given user is in the role, which is in a loop so I will check once again to see if I have to make changes there.

`if (user != null && await userManager.IsInRoleAsync(user, role.Name).ConfigureAwait(true))`

**Comment by Nerdtek** [comment]
I moved the users return from the UserManager to a list outside the foreach loop and problem solved.

Thank you so much everyone!!!
