### ISSUE TITLE
Doesn't support keepalive parameter

### ISSUE THREAD

**Issue by xxlagr** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#105]
My app`s connection string looks like:

`Data Source=something.net; Initial Catalog=database; Character Set=utf8; User Id=user; Password=password; convertzerodatetime=true;Keepalive=90`

My app crached with error "keepalive parameter is not support".

If I remove this parameter from connection string, local app works, but app, hosted in azure servise doesn't works and return the same error.

**Comment by caleblloyd** [comment]
Opened upstream to MySqlConnector at https://github.com/mysql-net/MySqlConnector/issues/132

**Comment by Kagamine** [comment]
Keep this open until MySqlConnector support this feature.

**Comment by caleblloyd** [comment]
Shipped in [1.1.1-prerelease-10000](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.1.1-prerelease-10000)

**Comment by Kagamine** [comment]
@caleblloyd, I dont suggest reset the build number to 10000, could we keep the build number growing?

**Comment by caleblloyd** [comment]
@Kagamine yes I will follow that from now on
