### ISSUE TITLE
Upgrade to 3.1.1，IQueryable.ToListAsync() has been changed

### ISSUE THREAD

**Issue by hzicong** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1051]
i upgrade my program from .NET Core 2.2 to .NET Core 3.1

before upgrade， my code:

await _productSkuRepository.GetAll().Where(s => s.ProductId == productId).ToListAsync();

sql text:
SELECT `p`.`Id`, `p`.`CreationTime`,
FROM `Product_Sku` AS `p`
WHERE `p`.`ProductId`  = @__productId_0

after :

SELECT `p`.`Id`, `p`.`CreationTime`
FROM `Product_Sku` AS `p`
WHERE CAST(`p`.`ProductId` AS signed) = @__productId_0

**Comment by hzicong** [comment]
i found the problem
mysql datatype is bigint , but in entity type is int.

**Comment by lauxjpn** [comment]
> mysql datatype is bigint , but in entity type is int.

Thanks for sharing. This is the correct SQL translation then.
