### ISSUE TITLE
Calling ShapedQueryExpression.VisitChildren is not allowed

### ISSUE THREAD

**Issue by git37** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1052]
getting this exception after select on .Any() call:

```System.InvalidOperationException: 'Calling ShapedQueryExpression.VisitChildren is not allowed. Visit expression manually for relevant part.'```

from this code:

```C#
var ar = from r in db.AuthRoles
    where r.Name == "accountowner"
    select r;

if (ar.Any()) { <==  EXCEPTION HAPPENS HERE....
    ur.RoleId = ar.FirstOrDefault().RoleId;
}
```

Works OK on MSSQL.
Any idea?

**Comment by mguinness** [comment]
Please provide the information requested in the new issue template such as EF Core version & Pomelo version.  This exception appears to have been added recently in the following PR:

[Query: Remove public setters from custom expression properties](https://github.com/dotnet/efcore/pull/19346/files#diff-454641f61cf0438568546a282a68ee0dR41-R43)

> ShapedQueryExpression.VisitChildren throws now. Since ShapedQuery contains query expression (server side) and shaper expression (client side), it is unlikely that a visitor needs to visit both components. Hence we force visitor to decide which component to visit. This improves perf as we wouldn't go into client side shaper when updating something in sql tree

**Comment by git37** [comment]
Hi,
Core Framework 3.1.200
EF Core 3.1.0
Pomelo 3.1.1
Thanks

**Comment by git37** [comment]
Sorry, my bad.
The EF core used was a preview.
changing back to stable solved it.
