### ISSUE TITLE
SELECT Take "The LINQ expression '(OUTER APPLY (Projection Mapping"

### ISSUE THREAD

**Issue by 491134648** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1053]
### Steps to reproduce
 `
  var result = await query.ToStandardTableResult(param,
                c => new CustomerOrderQueryResult
                {
                    Id = c.Id,
                    Items = c.OrderItems.Select(x => new CustomerOrderItemQueryResult
                    {
                        OrderId = x.OrderId,
                        DiscountAmount = x.DiscountAmount,
                        ItemAmount = x.ItemAmount,
                    }).Take(2), 
                    ItemsTotal = c.OrderItems.Sum(x => x.Quantity),
                });
`
### The issue
When I upgrade from 2.2 to 3.1.1, the SELECT  TAKE (2) statement under the execution of the Time Error, when I remove Take (2) is normal

```


Exception message:
Stack trace:
The LINQ expression '(OUTER APPLY (Projection Mapping:
↵(
↵    SELECT TOP((2)) ((o2.OrderId)), ((o2.DiscountAmount)), ((o2.ItemAmount)), ((o2.ItemWeight)), ((o2.Note)), ((o2.Id)), ((o2.ProductId)), ((o2.ProductMediaUrl)), ((o2.ProductName)), ((o2.ProductPrice)), ((o2.Quantity)), ((o2.ShippedQuantity))
↵    FROM (Orders_OrderItem AS o2)
↵    WHERE ((Not((o2.IsDeleted))) && (((t.Id) == (o2.OrderId))))
↵) AS t1))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information
```

### Further technical details

MySQL version: 5.7.20
Operating system: windows10
Pomelo.EntityFrameworkCore.MySql version:3.1.1
Microsoft.AspNetCore.App version:

Other details about my project setup:

**Comment by lauxjpn** [comment]
EF Core translated your query in a way, that uses an EF Core `OUTER APPLY` clause. This clause would be translated to a MySQL `LEFT JOIN LATERAL` clause. However, the `LATERAL` clauses are only supported by MySQL since version 8.0.14.

So if you want to execute the whole query on the database server-side, you need to use a MySQL 8.0.14+.

**Comment by 491134648** [comment]
Ok thanks! EF core 3.1, Mysql 5.7.20 I changed to separate query, is normal! , 2.X environment is used by Mysql Version 8.0+
