### ISSUE TITLE
OfType() + Include(string)

### ISSUE THREAD

**Issue by Mats391** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#106]
Imagine following set up:

```
public class MyDbContext : DbContext{
        public DbSet<Person> Persons { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
}

public abstract class Person
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
    }

public class Student : Person
    {
        public int Grade { get; set; }
    }

public class Teacher : Person
    {
        public ICollection<Student> Students { get; set; }
    }
```

Now trying to eager load the students along the teachers

```
using (var db = MyDbContextFactory.Create(connectionstring))
            {
                db.Persons.OfType<Teacher>().Include("Students").Load();
            }
```
This causes following error
```
Exception message: 
The property 'Students' is not a navigation property of entity type 'Person'. The 'Include(string)' method can only be used with a '.' separated list of navigation property names.
```
I also tried to change it to "Teacher.Students", but then it complains that Teacher is no navigation property.
I highly suspect this to be an error with EF core, but since I am using your connector wanted to post it here first to be 100% sure.
### Further technical details

EF Core version:  1.1.0-preview1-final
Pomelo.EntityFrameworkCore.MySql version: "1.1.0-preview1-*"
Operating system:  Win7
Visual Studio version: VS 2015

**Comment by caleblloyd** [comment]
I just added a pretty in-depth example of how to properly use inheritance based off your model:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/107/files

**Comment by Mats391** [comment]
@caleblloyd Your example does not use the new Include("Property") function from EF 1.1. Is that working for you too?

**Comment by caleblloyd** [comment]
I prefer to use `.Include(m => m.relationship)` because it's strongly typed.  But you could do it with `.Include("relationship")` and get the exact same result.

```csharp
// this statement is strongly typed and should not hit runtime errors
var teachers = await db.People.OfType<PersonTeacher>()
	.Where(m => m.Id >= _fixture.LowestTeacherId && m.Id <= _fixture.HighestTeacherId)
	.OrderBy(m => m.Id)
	.Include(m => m.Family)
		.ThenInclude(m => m.Members)
	.Include(m => m.Students)
		.ThenInclude(m => m.Family)
		.ThenInclude(m => m.Members)
	.ToListAsync();

// this statement is identical, but uses strings so could hit runtime errors
var teachers = await db.People.OfType<PersonTeacher>()
	.Where(m => m.Id >= _fixture.LowestTeacherId && m.Id <= _fixture.HighestTeacherId)
	.OrderBy(m => m.Id)
	.Include("Family.Members")
	.Include("Students.Family.Members")
	.ToListAsync();
```

**Comment by Mats391** [comment]
I also prefer strongly typed includes, but the string variant is very nice for generic functions. 
I tried your example and it worked to my surprise. After testing more I tried I found that it only works with the Where() or OrderBy(). If you use the Include right after OfType it will throw error I mentioned above.

This errors:
```
var teachers = await db.People.OfType<PersonTeacher>()
    .Include("Family.Members")
    .Include("Students.Family.Members")
    .ToListAsync();
```

This works:
```
var teachers = await db.People.OfType<PersonTeacher>()
    .Where(x => true)
    .Include("Family.Members")
    .Include("Students.Family.Members")
    .ToListAsync();
```

**Comment by caleblloyd** [comment]
Ah, excellent observation.  Opened upstream at https://github.com/aspnet/EntityFramework/issues/6969

**Comment by Mats391** [comment]
Thanks. Seems to be fixed already. Closing this.
