### ISSUE TITLE
Add new MySQL 8.0.19+ time zone support

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1064]
MySQL 8.0.19 added time zone support for `DATETIME` and `TIMESTAMP` values.

From [11.2.2 The DATE, DATETIME, and TIMESTAMP Types](https://dev.mysql.com/doc/refman/8.0/en/datetime.html):

> As of MySQL 8.0.19, you can specify a time zone offset when inserting `TIMESTAMP` and `DATETIME` values into a table. The offset is appended to the date part of a datetime literal, with no intravening spaces, and uses the same format used for setting the [time_zone](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_time_zone) system variable, with the following exceptions:
>
> * For hour values less than than 10, a leading zero is required.
> * The value `'-00:00'` is rejected.
> * Time zone names such as `'EET'` and `'Asia/Shanghai'` cannot be used; `'SYSTEM'` also cannot be used in this context.

**Comment by mguinness** [comment]
Do you think this will have any practical benefit since the offset isn't stored?

> The offset is not displayed when selecting a datetime value, even if one was used when inserting it.

**Comment by lauxjpn** [comment]
Probably not. I think we can close this for now. I did not follow up on the details regarding the introduced time zone handling. Just stumbled across it while doing the work on the `datetime` precision issue and dumped it in here, so I don't forget about it.
