### ISSUE TITLE
How do I remove from IServiceCollection the types added by AddDbContextPool()?

### ISSUE THREAD

**Issue by lnaie** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1068]
### Steps to reproduce
NA

### The issue
For my asp.net core integration testing, I need to replace the types added by the services.AddDbContextPool<AppDbContext>() with in-memory types created by:
```
                services.AddDbContext<AppDbContext>(options =>
                {
                    options.UseInMemoryDatabase("InMemoryDbForTesting");
                });
```
What are the signature of these types in the IServiceCollection container? 
Or how would you suggest to do it?

### Further technical details

MySQL version: MariaDb 10.4.12
Operating system: MacOS Catalina 10.15.3
Pomelo.EntityFrameworkCore.MySql version: 3.1.1
Microsoft.AspNetCore.App version: 3.1.3

Thanks

**Comment by mguinness** [comment]
This question would be better suited for https://stackoverflow.com/questions/tagged/ef-core or the https://github.com/dotnet/efcore repo since it's not provider specific.

**Comment by lauxjpn** [comment]
Take a closer look as [Testing with InMemory: Avoid configuring two database providers](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory#avoid-configuring-two-database-providers). It shows how to accomplish what you want without having to replace anything.

**Comment by lnaie** [comment]
:)
The thing is AddDbContextPool() doesn't work with this example:
https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#customize-webapplicationfactory

That made me think that maybe it's not them. 
And that's how I came here to ask.

**Comment by lauxjpn** [comment]
@lnaie Where you able to solve your problem?

**Comment by lnaie** [comment]
Hi,
I did sorted it out, google-ing it of course. :) Oh man, too often OS is shadowed by the time wasted in fixing edge cases.
Anyways for my aspnet core integration tests, that are documented at [Customize WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#customize-webapplicationfactory), and that I'm using for a signalr backend with mariadb, into a VS for mac, my fix was to replace the code block suggested in the official sample:
```
            services.AddDbContext<AppDbContext>(options =>
            {
                options.UseInMemoryDatabase("InMemoryDbForTesting");
            });
```
with:
```
                services.AddTransient(x => new DbContextOptionsBuilder<AppDbContext>()
                    .UseInMemoryDatabase(databaseName: "InMemoryDbForTesting")
                    .ConfigureWarnings(w => w.Ignore(InMemoryEventId.TransactionIgnoredWarning))
                    .Options);
```

In my case, the exception was that the ```DbContextOptions<AppDbContext>```,  that's being used by the only constructor of ```AppDbContext```,  could not be resolved from the root of the DI container.

Again, this workaround was not needed for using a MS SQL or SQLite DB provider.

That's all I could say about.
Thanks

**Comment by lauxjpn** [comment]
Thanks for sharing your solution!
