### ISSUE TITLE
MSB3030	Could not copy the file "config.json" because it was not found

### ISSUE THREAD

**Issue by connywesth** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1073]
### Steps to reproduce
I just cloned the project "PomeloFoundation\Pomelo.EntityFrameworkCore.MySql" run restore packages and the run "all tests". Then I got the error message "Error	MSB3030	Could not copy the file "config.json" because it was not found".

I did not expect any file be missing.

### The issue
I expected the tests to run flawlessly without error or maybe to tell me that the database setting was not set up properly. Or Database not created.

This is the details of the error message I get:

Exception message:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3030	Could not copy the file "config.json" because it was not found.	EFCore.MySql.IntegrationTests	F:\Projects\GitHub\PomeloFoundation\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.IntegrationTests\EFCore.MySql.IntegrationTests.csproj	77	
```

### Further technical details

MySQL version: 8.0.19, port 3306
Operating system: Windows 10 Pro (64 bit)
Processor: intel(R) Core(TM) i5-6200U @ 2.30GHz 2.40 GHz
Pomelo.EntityFrameworkCore.MySql version: Latest as of 2020-04-25.
Microsoft.AspNetCore.App version: 3.1

Other details about my project setup:

Microsoft Visual Studio Community 2019
Version 16.5.4

**Comment by connywesth** [comment]
I found the file config.json.example and made a copy manually of this file to config.json and changed the property to "Copy always", and changed password to what i use in my database.

I think this file should always exist from start. It is self evident to change password, maybe username, and databasename, but not the existance of a configuration file.

**Comment by lauxjpn** [comment]
I don't think that is something we want to change. The `config.json` files should not be part of the repo, to make sure that nobody commits their own file by accident (and other git related reasons).

**Comment by connywesth** [comment]
After some thinking I agree this default is acceptaable, and pretty good actually. I withdraw my issue.

**Comment by lauxjpn** [comment]
The could be two alternatives to the current approach, which I have not looked deeper into:

1. Adding a default `config.json` file, committing it to the github repo, but changing the `.gitignore` file afterwards to exclude the `config.json`. This might make sure, that the default file is part of the repo, but any changes to it would note make it into the repo.
2. Letting VS create a `config.json` file as a copy of the sample file, if the `config.json` file does not exist.

**Comment by connywesth** [comment]
Yes any of those solutions shold be acceptable  i think, i whould prefer the first alternative.

**Comment by lauxjpn** [comment]
The question is however, if this is actually an improvement to the current solution. The exception is very explicit and the steps needed are described in the `README.md` file after all.

A disadvantage could also be, that already existing `config.json` files might result in a conflict now, because developers have already created their own and a default one would now be shipped.

If you think this is necessary after all, feel free to do the testing to make sure, that it does not break existing environments, and push a PR if everything works as expected.

**Comment by connywesth** [comment]
I dont think an existiing config.json ever should be overwritten at all. but only when the file is missing in the locan project folder should it be copied.

**Comment by lauxjpn** [comment]
I agree, this is how it would need to be if an approach like this is being used. Not sure though, if this is the behavior we would actually get.

With the current approach, the compile time error is very expressive. I don't see at the moment, that other approaches have any advantage over the current one.

But I think, the current approach could be improved by making it event more explicit. We could use an [error task](https://docs.microsoft.com/en-us/visualstudio/msbuild/error-task?view=vs-2019) to stop compiling with a custom error message like the following, in case the `config.json` file is missing:

> The `"config.json"` file could not be found. This file is mandatory to run the `"$(ProjectName)"` tests and needs to be created and configured after cloning the repository. The necessary setup steps are described in the `"README.md"` file, that is located in the base directory of the project.

**Comment by connywesth** [comment]
I agree with you that it could be a nice aproach.
