### ISSUE TITLE
Table 'pomelo_test.blogs' doesn't exist

### ISSUE THREAD

**Issue by connywesth** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1074]
### Steps to reproduce
When running "all tests" out of the box I encouter error "Table 'pomelo_test.blogs' doesn't exist".

### The issue
I expected the table 'pomelo_test.blogs' to be automatically created, when running tests.

Exception message:
Stack trace:

```
Pomelo.EntityFrameworkCore.MySql.IntegrationTests.Tests.Connection.ConnectionTest.AffectedRowsFalse(reuseConnection: False)
   Source: ConnectionTest.cs line 20
   Duration: 2,6 sec

  Message: 
    Microsoft.EntityFrameworkCore.DbUpdateException : An error occurred while updating the entries. See the inner exception for details.
    ---- MySql.Data.MySqlClient.MySqlException : Table 'pomelo_test.blogs' doesn't exist
    -------- MySql.Data.MySqlClient.MySqlException : Table 'pomelo_test.blogs' doesn't exist
  Stack Trace: 
    ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
    BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
    BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
    StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
    StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
    MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken) line 68
    DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
    ConnectionTest.AffectedRowsFalse(Boolean reuseConnection) line 28
    --- End of stack trace from previous location where exception was thrown ---
    ----- Inner Stack Trace -----
    MySqlDataReader.ActivateResultSet() line 130
    MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) line 391
    CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) line 62
    RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
    ----- Inner Stack Trace -----
    ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) line 774
    ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) line 49
```

### Further technical details

MySQL version: 8.0.19
Operating system: Windows 10 Pro
Pomelo.EntityFrameworkCore.MySql version: current version as of 2020-04-25 (ISO 8601 dateformat)
Microsoft.AspNetCore.App version: 3.1

Other details about my project setup:
Microsoft Visual Studio Community 2019, Version 16.5.4
newly cloned, right out of the box, have setup database connection and it works.

**Comment by connywesth** [comment]
I have manually created the empty database "pomelo_test". before running tests.

**Comment by lauxjpn** [comment]
Take a look at the [README.md](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/EFCore.MySql.IntegrationTests/README.md) file under `.\test\EFCore.MySql.IntegrationTests\README.md`:

> **Configuring the Database**
> 
> You first must configure your MySql Database.  Open the `config.json.example` file, configure the connection string, and save it as `config.json`.
> 
> Next, you must rebuild migrations.  Run the `scripts/rebuild.sh` script on Linux or the `scripts/rebuild.ps1` script on Windows.  Any time you make changes to database models, run the rebuild script.
> 
> **Running Integration Tests**
> 
> 1. Configure the Database
> 2. Run `dotnet test`
> 3. This will run through all of the tests in the Test/ directory.

If you further take a look inside the `scripts/rebuild.ps1` or `scripts/rebuild.sh` files, you can see that these scripts should create the database (if you created the `config.json` before as instructed).

**Comment by lauxjpn** [comment]
@connywesth Since we haven't heard back from you, I will assume that you missed running the mentioned script. We will close this issue.
