### ISSUE TITLE
Support the new savepoint API

### ISSUE THREAD

**Issue by roji** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1076]
Support for savepoints has been merged into EF Core via https://github.com/dotnet/efcore/issues/20176, this tracks adding support on the Pomelo provider side.

This is super simple to do - simply subclass from RelationalTransaction and implement the relevant methods, following what was done for Sqlite in https://github.com/dotnet/efcore/pull/20710 (SQL Server is lacking support for Release).

**Comment by bgrainger** [comment]
The Savepoint API was added to MySqlConnector in https://github.com/mysql-net/MySqlConnector/issues/775.

**Comment by roji** [comment]
Thanks @bgrainger.

Note that since I opened this issue, I improved the default relational support so that the Pomelo provider probably doesn't need to do anything - any provider using RelationalTransaction will automatically attempt to use the standard savepoint management SQL (`SAVEPOINT x`, `ROLLBACK TO x`, `RELEASE SAVEPOINT x`). IIRC MySQL supports this, so apart from possibly enabling testing this should just work.

**Comment by roji** [comment]
To expand on the above, the savepoint support in EF Core 5.0 does not rely on the new System.Data APIs being introduced to .NET 5.0 (https://github.com/dotnet/runtime/issues/33397). In the future, if EF Core drops support for pre-.NET 5.0 (or cross-targets) we can have RelationalTransaction rely on the System.Data API instead of doing its own thing.

**Comment by lauxjpn** [comment]
I'll close this one, since EF Core does all the magic for us here.
