### ISSUE TITLE
Timestamp attribute in  RowVersion Field Not Support

### ISSUE THREAD

**Issue by mycsj** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#108]

**Comment by mycsj** [comment]
Field Define 

```csharp
    [Timestamp]
    public DateTime RowVersion { get; set; }
```

Database 

RowVersion     DateTime[6]

expect

RowVersion     DateTime         CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

**Comment by caleblloyd** [comment]
Our default DateTime mapping is to `DATETIME(6)`

This is what you want:

```csharp
    [Column(TypeName = "DATETIME")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime RowVersion { get; set; }
```

Please refer to the EF Docs for usage-related questions: https://docs.efproject.net/en/latest/modeling/generated-properties.html
