### ISSUE TITLE
Unable to find migrations and update database.

### ISSUE THREAD

**Issue by orassr** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1082]
I am trying to publish self contained .Net Core 3.1 application on a Ubuntu 18.04-x64
.NET Core SDKs installed: 3.1.201
Host (useful for support): Version: 3.1.3
.NET Core SDKs installed: 3.1.201
.NET Core runtimes installed: Microsoft.AspNetCore.App 3.1.3
Microsoft.NETCore.App 3.1.3

MYSQL server is up and running on same machine, `mysql. V 14.14 Distrib 5.7.29, for Linux (x86_64)`

my connection strings looks like this :
` "ConnectionStrings": { "MyDbContext": "Server=localhost;Database=DbProd;User Id=user;Password=MyPass" `

`dotnet ef database update` I am getting the following output:

`No migrations were applied. the database is already up to date.`

`dotnet ef migrations list` will show:

`Microsoft.EntityFrameworkCore.Infrastructure[10403]
 Entity Framework Core 3.1.0 initialized 'MyDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: none.`
`No migrations were found`

I am able to create new migrations and see them inside the `Migrations` folder, however, when updating the database the only file available is __EFMigrationsHistory`

I have already added to my Configure method @ Startup.cs to try run migrations on runtime. 
`dbContext.GetInfrastructure().GetService<IMigrator>();`
`dbContext.Database.Migrate();`

On debugging I am able to see my tables that supposed to be created at the `.dbContext`.

**Comment by mguinness** [comment]
Take a look at [No migrations were applied. The database is already up to date.](https://stackoverflow.com/questions/56702683) for a similar issue.

**Comment by orassr** [comment]
@mguinness I do have the .Designer.cs file, this is not my case..

**Comment by lauxjpn** [comment]
Please post your `Program.cs` and `Startup.cs` code and either the full `DbContext` class or at least the constructors.

Also, please run the `dotnet ef database update` and `dotnet ef migrations list` commands with the `--verbose` parameter and post the output.

Make sure to replace all sensitive information before your post anything.

**Comment by orassr** [comment]
@lauxjpn 
Program.cs 
 `public class Program`
`    {`
    `    public static void Main(string[] args)`
    `    {`
  `          CreateWebHostBuilder(args).Build().Run();`
`        }`
`        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>`
 `           WebHost.CreateDefaultBuilder(args)`
 `               .UseStartup<Startup>();`
  ` }`

DbContext ctor:
`        public StationsDbContext(DbContextOptions options)
            : base(options) {}`
Not too complicated, has few `<DbSet>`'s

`        protected override void OnModelCreating(ModelBuilder modelBuilder)`
     `   {`
       `     modelBuilder.ApplyConfiguration(new AlbumConfigurations());`
      `      modelBuilder.ApplyConfiguration(new ArtistConfigurations());`
  `       .`
     `    .`
      `   .`
Also few seeds:
`            modelBuilder`
            `    .Entity<Station>()`
         `       .HasData(`
            `        new Station`
          `          {`
                     `   Id = 1,`
                 `       StationName = "Namr",`
       `                 StationTitle = "Title",`
              `          StationDescription = "Description",`
             `           // URL's`
               `         StationThumbnailUrl = "http://.......",`
             `           StationInfoUrl = "http://.....",`
             `           StationBaseStreamUrlAac = "http://......",`
              `          StationBaseStreamUrlMp3 = "http://.....",`
                `        IsStationActive = true,`
               `         IsFavorite = false,`
             `       },`
     .
     .
     .        `

My Startup.cs:
`
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.KnownProxies.Add(IPAddress.Parse("10.0.0.100"));
            });

            services.AddDbContext<StationsDbContext>(options =>
                options.UseMySql(
                    Configuration.GetConnectionString(nameof(StationsDbContext)),options => options.EnableRetryOnFailure()));

            services.AddScoped
                <IStationRepository, StationRepository>();

            services.AddScoped
                <ISort, Sort>();

            services.AddScoped
                <IScrapServices, Ten>();

            services.AddScoped
                <ISearchForRecord, SearchForRecord>();

            services.AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_3_0);

            services.AddCors();

            services.AddAuthentication("cookies")
                .AddCookie("cookies", option => option.LoginPath = "/Or/Login");

            services.AddHttpClient();

            // Had to disable UseMvc after updating from 2.2 => 3.1
            services.AddMvc(options => options.EnableEndpointRouting = false);


            services.AddIdentity<ApplicationUsers, IdentityRole>
                ().AddEntityFrameworkStores<StationsDbContext>()
                //added bekow
                .AddDefaultTokenProviders();

                };
            });

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        [System.Obsolete]
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, StationsDbContext dbContext)
        {
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });

            dbContext.GetInfrastructure().GetService<IMigrator>();
            dbContext.Database.Migrate();

        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
            app.UseHsts();
        }

            // Shows UseCors with CorsPolicyBuilder.
            app.UseCors(builder =>
               builder.WithOrigins("http://localhost:4200"));

        //app.UseHttpsRedirection();
        app.UseAuthentication();
        app.UseMvc();  
        }
    }
}
`

**Comment by lauxjpn** [comment]
I edited you post to correctly display the code. When you post the requested `--verbose` output, please use correct multi-line code markdown. You can edit your previous post to take a look at the syntax I used. Thanks!

**Comment by orassr** [comment]
Thank you for the correction,

`dotnet ef migrations list --verbose`
```
orassr@prod:~/Desktop/server/PsServer.Data$ dotnet ef migrations list --verbose --project PsServer.Data               Using project 'PsServer.Data/PsServer.Data.csproj'.
Using startup project 'PsServer.Data/PsServer.Data.csproj'.
Writing 'PsServer.Data/obj/PsServer.Data.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpl9DBtE.tmp /verbosity:quiet /nologo PsServer.Data/PsServer.Data.csproj
Writing 'PsServer.Data/obj/PsServer.Data.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpAjIhPi.tmp /verbosity:quiet /nologo PsServer.Data/PsServer.Data.csproj
Build started...
dotnet build PsServer.Data/PsServer.Data.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.17
Build succeeded.
dotnet exec --depsfile /home/orassr/Desktop/server/PsServer.Data/PsServer.Data/bin/Debug/netcoreapp3.1/PsServer.Data.deps.json --additionalprobingpath /home/orassr/.nuget/packages --runtimeconfig /home/orassr/Desktop/server/PsServer.Data/PsServer.Data/bin/Debug/netcoreapp3.1/PsServer.Data.runtimeconfig.json /home/orassr/.dotnet/tools/.store/dotnet-ef/3.1.3/dotnet-ef/3.1.3/tools/netcoreapp3.1/any/tools/netcoreapp2.0/any/ef.dll migrations list --assembly /home/orassr/Desktop/server/PsServer.Data/PsServer.Data/bin/Debug/netcoreapp3.1/PsServer.Data.dll --startup-assembly /home/orassr/Desktop/server/PsServer.Data/PsServer.Data/bin/Debug/netcoreapp3.1/PsServer.Data.dll --project-dir /home/orassr/Desktop/server/PsServer.Data/PsServer.Data/ --language C# --working-dir /home/orassr/Desktop/server/PsServer.Data --verbose --root-namespace PsServer.Data
Using assembly 'PsServer.Data'.
Using startup assembly 'PsServer.Data'.
Using application base '/home/orassr/Desktop/server/PsServer.Data/PsServer.Data/bin/Debug/netcoreapp3.1'.
Using working directory '/home/orassr/Desktop/server/PsServer.Data/PsServer.Data'.
Using root namespace 'PsServer.Data'.
Using project directory '/home/orassr/Desktop/server/PsServer.Data/PsServer.Data/'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'StationsContextFactory'.
Found DbContext 'StationsDbContext'.
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'StationsContextFactory'.
Using context 'StationsDbContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'PsServer.Data'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'PsServer.Data'...
No design-time services were found.
'StationsDbContext' disposed.
20200501222928_One
```
For the first time I am able to see the migration => 20200501222928_One
I haven't made any changes in my code, and used --verbose in the past, also, my machine has been restarted several times.

`orassr@prod:~/Desktop/server/PsServer.Data/PsServer$ dotnet ef database update --verbose`
```
Using project '/home/orassr/Desktop/server/PsServer.Data/PsServer/PsServer.csproj'.
Using startup project '/home/orassr/Desktop/server/PsServer.Data/PsServer/PsServer.csproj'.
Writing '/home/orassr/Desktop/server/PsServer.Data/PsServer/obj/PsServer.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpeyAlUE.tmp /verbosity:quiet /nologo /home/orassr/Desktop/server/PsServer.Data/PsServer/PsServer.csproj
Writing '/home/orassr/Desktop/server/PsServer.Data/PsServer/obj/PsServer.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpyh678I.tmp /verbosity:quiet /nologo /home/orassr/Desktop/server/PsServer.Data/PsServer/PsServer.csproj
Build started...
dotnet build /home/orassr/Desktop/server/PsServer.Data/PsServer/PsServer.csproj /verbosity:quiet /nologo
/usr/share/dotnet/sdk/3.1.201/Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3277: Found conflicts between different versions of "RestSharp" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/home/orassr/Desktop/server/PsServer.Data/PsServer.Make/PsServer.Make.csproj]
/usr/share/dotnet/sdk/3.1.201/Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3277: Found conflicts between different versions of "RestSharp" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/home/orassr/Desktop/server/PsServer.Data/PsServer/PsServer.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets(404,5): warning RAZORSDK1006: Detected Razor language version downgrade. This is typically caused by a reference to the Microsoft.AspNetCore.Razor.Design package. Consider removing this package reference. [/home/orassr/Desktop/server/PsServer.Data/PsServer/PsServer.csproj]
Controllers/OrController.cs(229,28): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/home/orassr/Desktop/server/PsServer.Data/PsServer/PsServer.csproj]

Build succeeded.

/usr/share/dotnet/sdk/3.1.201/Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3277: Found conflicts between different versions of "RestSharp" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/home/orassr/Desktop/server/PsServer.Data/PsServer.Make/PsServer.Make.csproj]
/usr/share/dotnet/sdk/3.1.201/Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3277: Found conflicts between different versions of "RestSharp" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/home/orassr/Desktop/server/PsServer.Data/PsServer/PsServer.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets(404,5): warning RAZORSDK1006: Detected Razor language version downgrade. This is typically caused by a reference to the Microsoft.AspNetCore.Razor.Design package. Consider removing this package reference. [/home/orassr/Desktop/server/PsServer.Data/PsServer/PsServer.csproj]
Controllers/OrController.cs(229,28): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/home/orassr/Desktop/server/PsServer.Data/PsServer/PsServer.csproj]
    4 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.15
Build succeeded.
dotnet exec --depsfile /home/orassr/Desktop/server/PsServer.Data/PsServer/bin/Debug/netcoreapp3.1/PsServer.deps.json --additionalprobingpath /home/orassr/.nuget/packages --runtimeconfig /home/orassr/Desktop/server/PsServer.Data/PsServer/bin/Debug/netcoreapp3.1/PsServer.runtimeconfig.json /home/orassr/.dotnet/tools/.store/dotnet-ef/3.1.3/dotnet-ef/3.1.3/tools/netcoreapp3.1/any/tools/netcoreapp2.0/any/ef.dll database update --assembly /home/orassr/Desktop/server/PsServer.Data/PsServer/bin/Debug/netcoreapp3.1/PsServer.dll --startup-assembly /home/orassr/Desktop/server/PsServer.Data/PsServer/bin/Debug/netcoreapp3.1/PsServer.dll --project-dir /home/orassr/Desktop/server/PsServer.Data/PsServer/ --language C# --working-dir /home/orassr/Desktop/server/PsServer.Data/PsServer --verbose --root-namespace PsServer
Using assembly 'PsServer'.
Using startup assembly 'PsServer'.
Using application base '/home/orassr/Desktop/server/PsServer.Data/PsServer/bin/Debug/netcoreapp3.1'.
Using working directory '/home/orassr/Desktop/server/PsServer.Data/PsServer'.
Using root namespace 'PsServer'.
Using project directory '/home/orassr/Desktop/server/PsServer.Data/PsServer/'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Found DbContext 'StationsDbContext'.
Finding DbContext classes in the project...
Using context 'StationsDbContext'.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.0 initialized 'StationsDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: None
Finding design-time services for provider 'Pomelo.EntityFrameworkCore.MySql'...
Using design-time services from provider 'Pomelo.EntityFrameworkCore.MySql'.
Finding design-time services referenced by assembly 'PsServer'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'PsServer'...
No design-time services were found.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (14ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='StationsDbProd' AND TABLE_NAME='__EFMigrationsHistory';
Executed DbCommand (14ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='StationsDbProd' AND TABLE_NAME='__EFMigrationsHistory';
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='StationsDbProd' AND TABLE_NAME='__EFMigrationsHistory';
Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='StationsDbProd' AND TABLE_NAME='__EFMigrationsHistory';
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `MigrationId`, `ProductVersion`
      FROM `__EFMigrationsHistory`
      ORDER BY `MigrationId`;
Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT `MigrationId`, `ProductVersion`
FROM `__EFMigrationsHistory`
ORDER BY `MigrationId`;
info: Microsoft.EntityFrameworkCore.Migrations[20405]
      No migrations were applied. The database is already up to date.
No migrations were applied. The database is already up to date.
Done.
```

**Comment by lauxjpn** [comment]
> No migrations were applied. The database is already up to date.

It says your migration has already been applied. Please verify this.

**Comment by orassr** [comment]
mysql> SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| Statio             |
| StationDbProd      |
| StationsDbProd     |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
7 rows in set (0.01 sec)

mysql> USE StationsDbProd;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> SELECT * FROM `__EFMigrationsHistory` ORDER BY `MigrationId`;
Empty set (0.01 sec)

No file was generated with that input.

**Comment by lauxjpn** [comment]
> Then, post the files (the one containing the Up() and Down() methods and the corresponding .Design.cs file) of the migration that has not been applied but should have.

After you have posted the file contents, you might want to insert some `Debugger.Launch();` statements in the constructor or `OnConfiguring()` method of your `DbContext` class to trigger your debugger when the `dotnet ef database update` command is running. From the debugger, check the connection string and everything else against what you expect.

**Comment by orassr** [comment]
File hasn't been produced, all values are null.

**Comment by mguinness** [comment]
> I do have the .Designer.cs file

> File hasn't been produced

Are you saying that file doesn't exist now?

**Comment by lauxjpn** [comment]
> File hasn't been produced, all values are null.

You need to be more specific than that, so we can understand, what happened.

It is unclear, what file you are talking about and unclear what values you are talking about. It is also unclear, what you did, that let to your current results.

Please always provide as much detailed information as possible.
