### ISSUE TITLE
Scaffold-DbContext issue

### ISSUE THREAD

**Issue by JoSaint13** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#109]
### Steps to reproduce
I am trying to make reverse engineering and create classes from existing database by using Scaffold
command:
Scaffold-DbContext "connection string" Pomelo.EntityFrameworkCore.MySql -Verbose

This is working for Microsft.EntityFrameworkCore.
![verbose log](https://cloud.githubusercontent.com/assets/14937013/20078265/8019c8b8-a548-11e6-9093-347044d6ddc3.png)

**Comment by Kagamine** [comment]
Dupe of #55

**Comment by Kagamine** [comment]
@JoSaint13 We have supported DbContext Scaffolding in 1.1.0-rtm-10003.
