### ISSUE TITLE
Raw SQL query empty when using inner join and spatial function

### ISSUE THREAD

**Issue by jrmeland** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1109]
### Steps to reproduce
I am using `FromSql` on `DbSet` to execute a query that uses the Geometry type, specifically the `ST_CONTAINS` function:
```
SET @g = POINTFROMTEXT('POINT({0} {1})');
select z.* from zone z 
inner join zone_area za on za.ZoneId = z.ZoneId
WHERE z.CodeEntryComplete and ST_CONTAINS(za.Geometry, @g);
```
I believe it has something to do with the `ST_CONTAINS` and inner join since the following two queries work as expected:
```
SET @g = POINTFROMTEXT('POINT({0} {1})');
SELECT * FROM zone_area za 
WHERE ST_CONTAINS(za.Geometry, @g);
```
and 
```
SET @g = POINTFROMTEXT('POINT({0} {1})');
SELECTz.* FROM zone z 
INNER JOIN zone_area za on za.ZoneId = z.ZoneId 
WHERE za.ZoneAreaId > 0 AND  z.CodeEntryComplete
```
### The issue
The issue is that the results come back empty, but when I take the query as written above or logged by `Microsoft.EntityFrameworkCore.Database.Command` and run it directly against the database, it will return results. 

No exception is thrown in the application, nor any indication of problems, just an empty response.

### Further technical details

MySQL version: 10.3.13-MariaDB
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.1.4
Microsoft.AspNetCore.App version: 2.1.1

Any help is appreciated, thanks!

**Comment by mguinness** [comment]
If you are able, upgrade to 3.1 and use built-in [Support for spatial data with MySQL](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/488).  Otherwise enable the general query log on MySQL and confirm the actual SQL getting executed.  You could also try to upgrade to the latest version of [MySqlConnector](https://www.nuget.org/packages/MySqlConnector/) in your project file.

**Comment by jrmeland** [comment]
Hmm yeah okay I will try that. Was wondering if 3.1 would do the trick... I'll get back to you. Thanks!

**Comment by jrmeland** [comment]
All is good now, no issue.
