### ISSUE TITLE
How to use HEX from EFCore?

### ISSUE THREAD

**Issue by mc0re** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1111]
### Steps to reproduce
I can write an SQL query like this to search in a byte array as if it was a string.
```
select HEX(SystemId) from Table where HEX(SystemId) like '%8b%'
```
Here `SystemId` is a non-nullable `longblob` (`byte[]` in *C#*).

### The issue
Is there a way to generate this query using EFCore?

### Further technical details

MySQL version: mysql  Ver 15.1 Distrib 10.4.12-MariaDB
Operating system: Linux
Pomelo.EntityFrameworkCore.MySql version: 3.1.1
Microsoft.AspNetCore.App version: 3.1.3

**Comment by mguinness** [comment]
I don't think there's a translator for `HEX()`, but you should be able to use [Raw SQL Queries](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql).

Based on below from [The BLOB and TEXT Types](https://dev.mysql.com/doc/refman/8.0/en/blob.html) you might be able to use [EF.Functions.Like](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbfunctionsextensions.like)

> BLOB values are treated as binary strings (byte strings). They have the binary character set and collation, and comparison and sorting are based on the numeric values of the bytes in column values.

**Comment by mc0re** [comment]
Thanks a lot. I guess I will convert the binary to a hex-string and store it as text.

**Comment by lauxjpn** [comment]
We can add a translation for this. We could translate `BitConverter.ToString()`, but it usually separates the individual bytes with hyphens (bad design decision, but that's how it is). So its probably best to just add an `EF.Functions.Hex()` function, that gets translated.
