### ISSUE TITLE
Microsoft.EntityFrameworkCore.Database.Command  Failed executing DbCommand (rename)

### ISSUE THREAD

**Issue by rafaeldoria** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1116]
### Steps to reproduce
when creating a migration to rename a column you get an exception

### The issue
The command to rename the column is not that of mysql

migrationBuilder.RenameColumn(
                name: "Name",
                table: "User",
                newName: "Username");

````
Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE `User` RENAME COLUMN `Name` TO `Username`;
Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `User` RENAME COLUMN `Name` TO `Username`;
````

### Further technical details

MySQL version: 5.7.30-log MySQL Community Server
Operating system: Windows 10 Pro
Pomelo.EntityFrameworkCore.MySql version: 3.1.1
Microsoft.AspNetCore.App version: 3.1

Other details about my project setup:
All other migrations went smoothly, including AlterColumn and AddColumn

**Comment by mguinness** [comment]
Have you set [ServerVersion](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/wiki/Configuration-Options#serverversion)?  In your case `ServerVersion(new Version(5, 7, 30), ServerType.MySql)`

**Comment by rafaeldoria** [comment]
Check mysql config
![image](https://user-images.githubusercontent.com/14793540/86655244-f4339700-bfbc-11ea-88a1-f2701705d428.png)

**Comment by crozone** [comment]
You Startup.cs requires `ServerVersion(new Version(5, 7, 30), ServerType.MySql)` so that Pomelo knows which dialect of MySql to use.

For example:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<ApplicationDbContext>(options =>
                options.UseMySql(connectionString,
                    o => o.ServerVersion(new Version(5, 7, 30), ServerType.MySql)
    );

    // ...
}
```

Does the issue persist after adding this?

**Comment by rafaeldoria** [comment]
great!
it worked, thanks!!!
