### ISSUE TITLE
Why Choose This?

### ISSUE THREAD

**Issue by ronnieoverby** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#112]
Apologies if there's a better channel in which to ask this. I think it would be useful if you included a comparison of this provider to some of the others. Microsoft's EFCore documentation mentions 4 different MySql providers:

-Official MySql,
-Pomelo
-Sapient Guardian Fork
-DevArt

I'm interested in knowing the differences, but I haven't found any resource that gets into that.

**Comment by caleblloyd** [comment]
I have structured the performance tests to work with other providers. Our strongest feature is that we are (as of 1.0.1) backed by [MySqlConnector](https://github.com/mysql-net/MySqlConnector), which is truly asynchronous.

- Official MySql: this hits bugs in the performance tests, not sure why
- Sapient Guardian: I tried this month's ago and couldn't get migrations to work. I'll try again soon, I see there have been changes
- DevArt: Pay for and closed source, I can't test it

I would love to post comparisons, but Pomelo is the only one that has worked reliably for me out of the box. Maybe once the others catch up we can post comparisons

**Comment by Kagamine** [comment]
In another hand, we are following the Microsoft milestones, We have released our libs which based on ef core 1.0.0/1.0.1/1.1.0-preview1, but the other providers did not.

**Comment by Kagamine** [comment]
Devart is not a .net standard lib, so it does not cross plat.

**Comment by Mats391** [comment]
Licenses are also different for each, in case that is relevant to you.
Official is GPL2
Pomelo is MIT
Sapient is GPL2 I think
DevArt isnt free

**Comment by VaclavElias** [comment]
Thanks, this is very helpful! :)

**Comment by mguinness** [comment]
I haven't used Pomelo yet, but I may try it due to issues with the others listed below:

**Official MySql** - no Take() support (https://bugs.mysql.com/bug.php?id=82991) and not compatible with 1.1.0 yet.
**SapientGuardian** - DateTimeOffset bug (https://github.com/SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql/issues/32) and migrations issues.

Overall, no MySql provider gives full EF7 support yet (none support database scaffolding at this time) so the situation is rather confusing.  Hopefully this will improve over time, but it's unfortunate that Oracle hasn't created a repo for MySql.Data.EntityFrameworkCore in GitHub.

**Comment by caleblloyd** [comment]
> it's unfortunate that Oracle hasn't created a repo for MySql.Data.EntityFrameworkCore in GitHub.

It's part of their Connector/NET project.  They [have it on GitHub](https://github.com/mysql/mysql-connector-net/tree/7.0/Source/MySql.Data.EntityFrameworkCore), but I don't think that it's fully up-to-date.  The best place to get their source code is [on their website](https://dev.mysql.com/downloads/connector/net/6.9.html) and choose "Development Releases"

Oracle's connector works off a closed development roadmap, fairly restrictive license, and I'm not even sure if they accept Pull Requests from outside developers for features.

Pomelo is full MIT License and we accept Pull Requests!  We plan to add scaffolding support eventually, but if someone wants to step in and contribute scaffolding support it could get done even sooner!

**Comment by Kagamine** [comment]
@mguinness I am implementing design-time layer, I believe I will release a version which support scaffolding

**Comment by Kagamine** [comment]
![image](https://cloud.githubusercontent.com/assets/2216750/20509984/f0cd01d2-b0a7-11e6-9136-5ed589e2ccdc.png)

**Comment by Kagamine** [comment]
Close this since it was out of date.
