### ISSUE TITLE
How to change isolation level?

### ISSUE THREAD

**Issue by chester89** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1129]
Is there a way to change isolation level for all queries either on provider level or in mysql-connector?
I'm considering changing this on database-level using `SET TRANSACTION ISOLATION LEVEL READ COMMITTED;`, not sure if the EF/underlying driver will pick it up.
The only other way I know of is issuing explicit command (like suggested here https://github.com/dotnet/efcore/issues/4809#issuecomment-222945564) - not sure if that would be good idea performance-wise.
Any suggestions?

### Further technical details

MySQL version: 5.7.29
Operating system: Linux
Pomelo.EntityFrameworkCore.MySql version:
Microsoft.AspNetCore.App version:

Other details about my project setup:

**Comment by lauxjpn** [comment]
You can find anything officially supported by EF Core about transactions and isolation levels in [Using Transactions](https://docs.microsoft.com/en-us/ef/core/saving/transactions).

**Comment by lauxjpn** [comment]
@chester89 How is it going? Can we close this one?

**Comment by chester89** [comment]
@lauxjpn yep, it seems to work ok. Thanks
