### ISSUE TITLE
Public Jetbrains.Annotation definitions collide with other code

### ISSUE THREAD

**Issue by joepb** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#113]
### Steps to reproduce
Consume the module in a project that also includes the Jetbrains.Annotations nuget.

### The issue
Because both Pomelo.EntityFrameworkCore.MySql and Jetbrains.Annotations expose the same public members, the compiler is unable to determine the correct one, resulting in errors.

```
Error CS0433
The type '...' exists in both 'JetBrains.Annotations.NetStandard, Version=10.2.1.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' and 'Pomelo.EntityFrameworkCore.MySql, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null'	SampleImporter..NETCoreApp,Version=v1.0
```

### Further technical details
Marking the Resharper code hints as internal should fix all collisions. The analysis engine of Resharper supports this out of the box.

**Comment by caleblloyd** [comment]
Thanks for the contribution!  Shipped in [1.0.2-prerelease-10002](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.0.2-prerelease-10002) and [1.1.0-preview1-10002](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.1.0-preview1-10002)
