### ISSUE TITLE
NettopologySuite support

### ISSUE THREAD

**Issue by dalton5** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1132]
Hi,

I migrate from Sql Server to MySql with entity framework core.

I installed Pomelo but when I want to set my DbContext I can't find the option Use 

SQL Server:

builder.UseSqlServer(connectionString, x=> x.UseNetTopologySuite());

MySql:

![image](https://user-images.githubusercontent.com/8339768/88459435-d65ba280-ce95-11ea-82f8-3d82602bf9dd.png)

Can you help?

Thanks,

**Comment by dalton5** [comment]
Ok I sorted it out.

I went into package source of nugget options. I added the url and I found below:

https://pkgs.dev.azure.com/pomelo-efcore/Pomelo.EntityFrameworkCore.MySql/_packaging/pomelo-efcore-public/nuget/v3/index.json

**Comment by lauxjpn** [comment]
Yeah, NTS support is pretty new in Pomelo, so it has not been publicly released yet. But it is in our [nightly builds](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds).

**Comment by mustafaomar** [comment]
hi , 
just started to use UseNetTopologySuite()
and  i am having the same problem

![image](https://user-images.githubusercontent.com/23484701/158056311-8690532d-fd91-4942-a571-9ac3d317f786.png)

ps: i am  using the latest stable version  " Pomelo.EntityFrameworkCore.MySql.NetTopologySuite -Version 6.0.1 "

**Comment by enkodellc** [comment]
Here is what I used for EF 6, .Net Core 6:

                services.AddDbContext<AWSMariaSQLDbContext>(options => options.UseMySql(configuration.GetConnectionString("AWSMariaSQLDataConnection"), Microsoft.EntityFrameworkCore.ServerVersion.Parse("10.6.10-mariadb"), 
                    options => options.UseNetTopologySuite())
                );


Then in my model builder:

            entity.Property(e => e.Location)
                   .HasColumnName("Location")
                   .HasColumnType("point");

My Model:

    public Point Location { get; set; }
