### ISSUE TITLE
Is Except() supported?

### ISSUE THREAD

**Issue by mc0re** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1141]
### Steps to reproduce
I have a *LINQ* query, that uses `Except()`. It produces a "SQL could not be translated" exception.
Looking at the source code, in `SimpleQueryMySqlTest.cs` I found a line, that `EXCEPT` is not supported by *MySQL*.
Trying out a query with `EXCEPT` directly on *MySQL* (actually, *MariaDB*) produces the correct result, so it is supported.

### The issue
So the question is basically, whether *Pomelo* supports `Except()`, or is the exception generated by something else. And if does not, what can I replace it with.

### Further technical details

MySQL version: mariadb  Ver 15.1 Distrib 10.4.14-MariaDB
Pomelo.EntityFrameworkCore.MySql version: 3.2.0-preview.20372.3
Microsoft.AspNetCore.App version: 3.1.6

**Comment by lauxjpn** [comment]
Looks like MariaDB introduced `EXCEPT` and `INTERSECT` support in `10.3.0`, and then extended it in `10.4.0` (precedence) and again in `10.5.0` (supporting `EXCEPT ALL` and `INTERSECT ALL`). So we can support those operations for MariaDB. There is still no support for them for MySQL.

**Comment by mc0re** [comment]
Thanks for clarification. I'm still not clear about the differences between *MySQL* and *MariaDB* :-/

By a lengthy try-and-err process I found the culprit.
I had the following code in the end of the query:
```
            return await query
                .Where(pl => times.Contains(pl.EventTime))
                .ProjectTo<UsageModel>(mMapper.ConfigurationProvider)
                .OrderBy(u => u.Student.UserName)
                .ToListAsync();
```

Removing the `OrderBy` eliminated the exception. Go figure :-)

**Comment by lauxjpn** [comment]
Glad you could fix the issue on your end. Let's keep this issue open though, because we should support `EXCEPT` and `INTERCEPT` for MariaDB.

**Comment by mc0re** [comment]
Oh, I thought you said you do - but it was only *can*, not *does* :-)
What can I replace the `EXCEPT` with for the time being?

**Comment by lauxjpn** [comment]
Sorry, my Ride IDE was acting up after their new so called "release". Anyway, I just pushed the PR. Will be part of the nightly builds as soon as it has been merged (in about 24h).

**Comment by mc0re** [comment]
That was fast! :-)
