### ISSUE TITLE
Exception happen when ThenInclude

### ISSUE THREAD

**Issue by iamchamith** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1145]
### Steps to reproduce

1. Create a project using .net core
2. Add Pomelo
3. Add migration
4. Deployed Project on Linux docker container.
5. Run the Application.

### The issue
The application will Crash. No exception generated. Down the Docker container.  

Example:
```C#
var x = await _unitOfWorkRoute.RouteRepository.TableAsNoTracking
        .Include(p => p.RouteFareDefinitionTravelClasses)
        .Where(p => p.Id == 1462)
        .ToListAsync();
```

This code is working fine.but following code will brake the application
```C#
var x = await _unitOfWorkRoute.RouteRepository.TableAsNoTracking
        .Include(p => p.RouteFareDefinitionTravelClasses)
        **.ThenInclude(p => p.RouteFares)**
        .Where(p => p.Id == 1462)
        .ToListAsync();
```

### Further technical details

MySQL version: 5.7
Operating system: linux
Pomelo.EntityFrameworkCore.MySql version: 2.0.1
Microsoft.AspNetCore.App version:2.0.0

**Comment by lauxjpn** [comment]
@iamchamith Besides your actual issue, what is your reasoning for using Pomelo `2.0.1` nowadays? This version is not officially supported anymore. I don't even have a setup ready here to test issues for that version.

**Comment by lauxjpn** [comment]
@iamchamith Since we haven't heard back from you, we will close this issue. Once you provided us with the requested information, we will reopen it.
