### ISSUE TITLE
Remove migration does not remove unapplied migration files and throws error stating last migration has already been applied

### ISSUE THREAD

**Issue by eric10k93** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1155]
### Steps to reproduce
In Visual Studio NuGet Package Manager Console:
```
Add-Migration JustATest -Project <project_name> -Context <context_name>
```
The Migration file gets added (though containing extraneous stuff I didn't add)
```
Remove-Migration -Project <project_name> -Context <context_name>
```

### The issue
I am at present unable to successfully add or remove migrations from my project running Pomelo 3.1.2.

The following error is thrown when attempting to remove an unapplied migration:

```
The migration '<previous_migration_name>' has already been applied to the database. Revert it and try again. If the migration has been applied to other databases, consider reverting its changes using a new migration.
```

### Further technical details

MySQL version: 5.7.17
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.1.2

Other details about my project setup:
I'm using a .NET Standard 2.0 library project that's been working fine with EF Core 2.x and previous versions of Pomelo.  The DbContext and models were scaffolded from an existing database, and all changes since have been code-first approach.

Solution uses a startup project with EF Core Tools libraries and a target project with the DbContext and Migrations (hence needing the flags above).

Recently upgraded all relevant libraries to EF Core 3.1.7 and Pomelo 3.1.2.  Managed to successfully apply some minor migrations to confirm everything appeared to be working.

Today, attempting to make minor model changes and the model changes are not recognized when performing Add-Migration command (they're not scaffolded by the model builder on the new migration .cs file).  This is simply attempting to add a field to the model/table in the database.

Strangely, I attempted just deleting the Migrations folder, wondering if the DbContextModelSnapshot was out of sync... but when running Add-Migration after deleting the entire Migrations folder it creates the exact same migration (with some extraneous stuff I didn't add) as mentioned above when running Add-Migration before clearing all the migrations.  It's in some state where it doesn't acknowledge I have deleted all previous migrations.

My main concern at this point would likely be getting to a state where I can just recreate a new (clean) DbContextModelSnapshot file that is in sync with the existing database, but I appear to be unable to do anything at the moment.

**Comment by lauxjpn** [comment]
Adding and removing migrations should generally work fine with EF Core and Pomelo 3.1.2. As a general advice when unexpected errors are popping up when executing an EF Core tool, use the `-Verbose` (when using the Package Manager Console in VS, or `--verbose` when using the .NET Core CLI).

For a general solution to you problem, see [StackOverflow: How to unapply a migration in ASP.NET Core with EF Core](https://stackoverflow.com/questions/38192450/how-to-unapply-a-migration-in-asp-net-core-with-ef-core), which seems to discuss the same issue.

If you just want to start over with a single migration, take a look at [Managing Migrations: Resetting all migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#resetting-all-migrations).

**Comment by eric10k93** [comment]
Apologies for not being clear enough... my issue actually doesn't relate to that StackOverflow issue at all.  The problem I am seeing is I get that error with a migration I haven't even applied.  "Remove-Migration" command does not remove the unapplied migration... I just get an error that it can't remove the PREVIOUS migration (which is NOT what I am trying to do).

I also already performed the steps in the "Managing Migrations: Resetting all migrations" link you listed.  BUT despite clearing all my previous migrations, something appears to be stuck because when I perform "Add-Migration" to generate a new one, it doesn't contain my entire schema as I'd expect... it doesn't seem to recognize that I've deleted my Migrations folder at all.  I just don't quite understand where it's even getting the data from since I have deleted my DbContextModelSnapshot.cs file.

This looks like a major bug to me, but maybe it's an EF Core Tools bug rather than Pomelo?  I'm just not quite sure where to point the finger.

Lastly, I get nothing useful from using the -Verbose option when adding or removing migrations.  It simply gives me the errors I have already mentioned.

**Comment by lauxjpn** [comment]
> This looks like a major bug to me, but maybe it's an EF Core Tools bug rather than Pomelo? I'm just not quite sure where to point the finger.

Its probably impossible to dive deeper into this and find out what the actual issue is, without having access to the project, since you already worked through multiple steps and are stuck somewhere in between.
Please either share the project itself or something similar that reproduces the issue.

**Comment by eric10k93** [comment]
Understandable, might take me a bit to clean it up so it's shareable as it's a corporate project at the moment.... give me a few days

**Comment by lauxjpn** [comment]
Taking a closer look at the EF Core migration removal code, I am not full convinced yet, that you went through _all_ the steps outlined in [Managing Migrations: Resetting all migrations](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#resetting-all-migrations):

> ...
> * In your database, delete all rows from the migrations history table
> * Insert a single row into the migrations history, to record that the first migration has already been applied, since your tables are already there. The insert SQL is the last operation in the SQL script generated above.

---

Also, if you revert your project to the state, where the `Migrations` folder existed and the original error message appeared when trying to remove the last migration, your should be able to use the `-Force` parameter, that will ignore the fact that this migration has already been applied to _some_ database (see [Remove-Migration](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#remove-migration)).

---

From https://github.com/dotnet/efcore/blob/68941673e27be80b95fe1b8645da3f1f927e2d6d/src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs#L251-L277:

```c#
var applied = false;
try
{
    applied = Dependencies.HistoryRepository.GetAppliedMigrations().Any(
        e => e.MigrationId.Equals(migration.GetId(), StringComparison.OrdinalIgnoreCase));
}
catch (Exception ex) when (force)
{
    Dependencies.OperationReporter.WriteVerbose(ex.ToString());
    Dependencies.OperationReporter.WriteWarning(
        DesignStrings.ForceRemoveMigration(migration.GetId(), ex.Message));
}

if (applied)
{
    if (force)
    {
        Dependencies.Migrator.Migrate(
            migrations.Count > 1
                ? migrations[migrations.Count - 2].GetId()
                : Migration.InitialDatabase);
    }
    else
    {
        throw new OperationException(DesignStrings.RevertMigration(migration.GetId()));
    }
}
```

The `Dependencies.HistoryRepository.GetAppliedMigrations()` call will check the history table in the configured database, if the migration has already been applied to the configured database.

The line `throw new OperationException(DesignStrings.RevertMigration(migration.GetId()));` is the one, that will output the error message you posted. It you provide the force parameter, it will ignore that the migration has already been applied.

If you delete the history table from the configured database and delete the `Migrations` folder, you will have a clean slate.

**Comment by eric10k93** [comment]
Correct, there are four steps referenced:

1. Delete your Migrations folder
2. Create a new migration and generate a SQL script for it
3. In your database, delete all rows from the migrations history table
4. Insert a single row into the migrations history, to record that the first migration has already been applied, since your tables are already there. The insert SEQL is the last operation in the SQL script generated above.

I can't make it past step 2 because generating the SQL script does not recreate my entire database as I'd expect it to.  So there is no point in continuing to steps 3 and 4 until I figure out why step 2 does not work.

After deleting the Migrations folder, performing "Add-Migration" as in step 2 SHOULD create a migration containing my entire database schema, but it's currently creating a migration with code to add a keyless entity that I already added to the database 3 migrations ago.  So I don't understand why "Add-Migration" is even picking this up when I already applied that change to the database weeks ago (I have not made any changes since)... I also deleted the Migrations folder, so it shouldn't even have any way to recognize that I made changes...

My understanding is that at this point, after deleting the Migrations folder, I should basically be working with a clean slate since there is no model to compare to when I then run "Add-Migration"

I understand that I still need to finish cleaning everything up afterwards with steps 3 and 4, but I can't properly get past step 2... as EF appears to still have some idea about the state of Migrations even after I have deleted the folder

**Comment by lauxjpn** [comment]
The steps as stated in the referenced article are not necessarily in order.

This is what you need to do:

> So, if you revert to the state where you still have your Migrations folder, then using the -Force parameter should work, even if you already applied the migration to the configured database (maybe a local development database).
>
> If you don't, deleting the history table from the configured database and the Migrations folder will return you to a clean slate.

Either do the first or the second approach. If you do the second one, it will not be enough to only delete the history table (as the EF Core article correctly points out), because all the other tables already exist. Therefor, you will need to delete all tables (or drop the database itself).

This _is_ the solution to your problem. There _must_ be a database configured, which _has_ the migration applied (or at least it has an entry in its history table).

**Comment by eric10k93** [comment]
There's definitely a misunderstanding here.  I will make further attempts at what you have outlined above.

BUT, a distinction needs to be made, as I have tried to explain...

I have created a migration, which we'll call "MigrationB" using "Add-Migration"

I HAVE NOT ever applied MigrationB to ANY database (the updates are not applied to the database, and there are NO records in the __efmigrationshistory table)... so my intent was to delete the migration, WHICH IS UNAPPLIED, using "Remove-Migration".

This is supposed to delete UNAPPLIED migrations from the current list of migrations on the project.

Instead, I am getting an error that MigrationA (a previously applied migration) has already been applied and cannot be removed.  Thus, the files for MigrationB never get deleted (cleaned up) from the migrations list.

I AM NOT trying to remove MigrationA or ANY MIGRATIONS WHICH HAVE BEEN APPLIED TO THE DATABASE.  The migration I am attempting to remove is UNAPPLIED.  AND the error message I am getting is referencing a previously APPLIED migration name... Remove-Migration should be removing MigrationB from my current project since it is UNAPPLIED.

**Comment by lauxjpn** [comment]
I understand what your issue is, and also, what you believe to be the case. However, the official EF Core 3.1.7 code I have posted above clearly proves, that the error message appears only if you have applied the migration to a database. We can even dive deeper into the `GetAppliedMigrations()` method if you don't believe me:

From https://github.com/dotnet/efcore/blob/68941673e27be80b95fe1b8645da3f1f927e2d6d/src/EFCore.Relational/Migrations/HistoryRepository.cs#L210-L234:

```c#
public virtual IReadOnlyList<HistoryRow> GetAppliedMigrations()
{
    var rows = new List<HistoryRow>();

    if (Exists())
    {
        var command = Dependencies.RawSqlCommandBuilder.Build(GetAppliedMigrationsSql);

        using (var reader = command.ExecuteReader(
            new RelationalCommandParameterObject(
                Dependencies.Connection,
                null,
                null,
                Dependencies.CurrentContext.Context,
                Dependencies.CommandLogger)))
        {
            while (reader.Read())
            {
                rows.Add(new HistoryRow(reader.DbDataReader.GetString(0), reader.DbDataReader.GetString(1)));
            }
        }
    }

    return rows;
}

// ...

/// <summary>
///     Generates SQL to query for the migrations that have been applied.
/// </summary>
protected virtual string GetAppliedMigrationsSql
    => new StringBuilder()
        .Append("SELECT ")
        .Append(SqlGenerationHelper.DelimitIdentifier(MigrationIdColumnName))
        .Append(", ")
        .AppendLine(SqlGenerationHelper.DelimitIdentifier(ProductVersionColumnName))
        .Append("FROM ")
        .AppendLine(SqlGenerationHelper.DelimitIdentifier(TableName, TableSchema))
        .Append("ORDER BY ")
        .Append(SqlGenerationHelper.DelimitIdentifier(MigrationIdColumnName))
        .Append(SqlGenerationHelper.StatementTerminator)
        .ToString();
```

If you think my assessment is not correct, then prove it with code. Otherwise, we must agree at this point, that EF Core only throws the exception, if it finds an applied migration in the `__EFMigrationsHistory` table.

So at this point, there is no arguing anymore, that you have not applied the migration, because the exception is prove that you have.

Instead, the actual question here is, to which database? Because if you say that the `__EFMigrationsHistory` table is empty, then you must be looking in a different database than EF Core does.

Therefore, you need to find out which database EF Core is querying when looking for the applied migrations.

**Comment by eric10k93** [comment]
I still can't resolve the issue I have reported, but I have no way of sharing my code that I can see.  I can't share the whole project... is there some part of the code that would help you better understand what I'm seeing?

**Comment by mguinness** [comment]
You haven't addressed the question of whether the `__EFMigrationsHistory` table is empty in the database the migration is using.

**Comment by eric10k93** [comment]
Yes, I have confirmed my DbContext is targeting my development database, and I have deleted both the Migrations folder and the __efmigrationshistory table.  I still have the same issue where when creating a new migration EF Core seems to still be comparing against something as if it's looking somewhere else for the model snapshot.  I closed this issue and opened a new one on the main EF Core page with more details including screenshots since the issue itself seems to fit much better there:
https://github.com/dotnet/efcore/issues/22466
