### ISSUE TITLE
System.InvalidCastException: 'Unable to cast object of type 'System.SByte' to type 'System.Boolean'

### ISSUE THREAD

**Issue by MKI-Miro** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1164]
### Steps to reproduce
Connection string includes TreatTinyAsBoolean=false
Get one row from DB and save it without any change

### The issue

`
var product = context.PtbfzVirtuemartProducts.FirstOrDefault(p => p.VirtuemartProductId == productId);
 context.SaveChanges();`

```
Exception message: 
System.InvalidCastException: 'Unable to cast object of type 'System.SByte' to type 'System.Boolean'.'

Stack trace:
`   at Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer`1.Equals(Object left, Object right)``

### Further technical details

MySQL version: 8
Operating system: 
Pomelo.EntityFrameworkCore.MySql version: 3.1.2
Microsoft.AspNetCore.App version: 3.1

Other details about my project setup:

**Comment by lauxjpn** [comment]
Please post your `PtbfzVirtuemartProduct` model class (and model definition if any) and the corresponding table (`CREATE TABLE` statement), so we can reproduce this issue.

**Comment by lauxjpn** [comment]
@MKI-Miro Since we haven't heard back from you, we will close this issue. Feel free to provide the requested information, to reopen the issue.
