### ISSUE TITLE
`ValueGeneratedNever()` is not generated by scaffold for primary key

### ISSUE THREAD

**Issue by yyjdelete** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1170]
### Steps to reproduce
dotnet ef dbcontext scaffold "server=***;port=***;user id=***;password=***;database=***" Pomelo.EntityFrameworkCore.MySql --force
```sql
CREATE TABLE `yyy` (
  `id` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;


-- test.xxx definition

CREATE TABLE `xxx` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fk_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `xxx_FK` (`fk_id`),
  CONSTRAINT `xxx_FK` FOREIGN KEY (`fk_id`) REFERENCES `yyy` (`id`)
) ENGINE=InnoDB;
```

### The issue
The column `yyy.id` should not be treated as auto_increment.
Tested `Microsoft.EntityFrameworkCore.SqlServer` 3.1.8 and `Npgsql.EntityFrameworkCore.PostgreSQL` 3.1.4 will add `.ValueGeneratedNever()` for this case.

#### Expected
```cs
            modelBuilder.Entity<Yyy>(entity =>
            {
                entity.ToTable("yyy");

                entity.Property(e => e.Id).HasColumnName("id").ValueGeneratedNever();
            });
```

#### Actual
```cs
            modelBuilder.Entity<Yyy>(entity =>
            {
                entity.ToTable("yyy");

                entity.Property(e => e.Id).HasColumnName("id");
            });
```
with `ValueGeneratedNever()`: Added, not throw;
without `ValueGeneratedNever()`: Modified, throw(fk conflict);
```cs
                //init data
                ctx.Xxx.Add(new Xxx());
                ctx.SaveChanges();

                var xxx = ctx.Xxx.FirstOrDefault();
                xxx.Fk = new Yyy { Id = 1 };
                ctx.ChangeTracker.DetectChanges();
                Console.WriteLine(ctx.Entry(xxx.Fk).State);
                ctx.SaveChanges();
```

### Further technical details

MySQL version: `8.0.21`
Operating system: `win10-x64`
Pomelo.EntityFrameworkCore.MySql version: `3.2.0`
Microsoft.EntityFrameworkCore.Design: `3.1.8`
Microsoft.AspNetCore.App version: `none`

Other details about my project setup:

**Comment by lauxjpn** [comment]
It is an interesting issue, that I will take a closer look at later today. Just as a heads-up however, it is likely that this is an issue in EF Core and not in Pomelo (though we probably would be able to fix it in this case too).
