### ISSUE TITLE
Include doesnt work. Sometimes... 

### ISSUE THREAD

**Issue by zamecnik** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1173]
I have a very simple query that uses Include to load reference:

`var model = _dbContext.ModelInfos
.Include(m=>m.Model)
.Single(m => m.Key == infoKey);
`

It correctly loads the reference in one repository, but in another repo it doesnt and create an SQL query without JOIN statement. Same code, same item key...

And it happens across my app on multiple models. Sometimes Include works, sometimes it doesnt. 

In case it doesnt work and references are not loaded, I use explicit loading like:

`var entry = _dbContext.Entry(model);
entry.Reference(e => e.Model).Load();`

as it loads the reference always correctly. 

I would like to include better description and steps to reproduce, but I do not know what is the cause and why it act like this...

Doesnt anyone have an idea what could be the problem?

### Further technical details

MySQL version: Win64 8.0.19 Community
Operating system: Win10
Pomelo.EntityFrameworkCore.MySql version: 3.2.0
Microsoft.AspNetCore.App version: 3.1

**Comment by lauxjpn** [comment]
Please post the model classes involved for the case where the include does not what you expect. If there is any Fluent API used to configure any of the involved model classes, post that too.

(Of course if your repo is public, you can just link to it with some instructions for us which query does not work as expected.)

**Comment by zamecnik** [comment]
I cannot post full classes, but looks like this:

```
public class ModelInfo
    {
        public int Id { get; set; }

        [MaxLength(5)]
        public string Key { get; set; }

        [MaxLength(50)]
        public string Title { get; set; }
 
        public Model Model { get; set; }

      	....
    }

 public class Model
    {
        public int Id { get; set; }

        [MaxLength(5)]
        public string Key { get; set; }

 	public List<ModelInfo> ModelInfos { get; set; }

	....

	 public Model()
        {
           ...
           ModelInfos = new List<ModelInfo>();
           .... 
        }

}
```

Fluent API is used only to create indexes on some fields:

```
modelBuilder.Entity<Model>().HasIndex(b => b.Key);

modelBuilder.Entity<ModelInfo>().HasIndex(b => b.Key);
```

**Comment by lauxjpn** [comment]
I don't see a foreign key defined on `ModelInfo` for `Model` (e.g. `ModelInfo.ModelId`).

**Comment by zamecnik** [comment]
I dont think its necessary. When I look at migration script, the reference is there correctly:

```
migrationBuilder.CreateTable(
                name: "ModelInfos",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Key = table.Column<string>(maxLength: 5, nullable: true),
                    Title = table.Column<string>(maxLength: 50, nullable: true),
                    Description = table.Column<string>(maxLength: 1000, nullable: true),
                 	...
                
                    ModelId = table.Column<int>(nullable: true),
                    ...
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ModelInfos", x => x.Id);
                    ...
                    table.ForeignKey(
                        name: "FK_ModelInfos_Models_ModelId",
                        column: x => x.ModelId,
                        principalTable: "Models",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });
```

**Comment by lauxjpn** [comment]
Please setup EF Core logging (at least to the `Information` level) and post as much of the output till (and including) the unexpected query as you can.

> I dont think its necessary. When I look at migration script, the reference is there correctly:

While it is technically true that EF Core should use a shadow property for cases where you don't explicitly setup a foreign key, you are already experiencing navigation related issues.
Therefore being as explicit as possible (including to specify the relationship using the Fluent API) should be one of the first steps to narrow down the actual issue.

**Comment by lauxjpn** [comment]
@zamecnik Since we haven't heard back from you, we are closing this one for now.
