### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by L60008028** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1175]
### Steps to reproduce
.netCore3.1,
paket add Pomelo.EntityFrameworkCore.MySql --version 3.2.1

### The issue
System.TypeLoadException:“Method 'Create' in type 'Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlSqlTranslatingExpressionVisitorFactory' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=3.2.1.0, Culture=neutral, 

```
Exception message:
Stack trace:
```

### Further technical details

MySQL version: 
Operating system: 
Pomelo.EntityFrameworkCore.MySql version:
Microsoft.AspNetCore.App version:

Other details about my project setup:

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1138#issuecomment-670049509
