### ISSUE TITLE
Incompatible with IdentityServer4.Models (&& invalid code provided in docs)

### ISSUE THREAD

**Issue by zaneclaes** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1178]
### Steps to reproduce
Create a new `dotnetcore3.1` project using `IdentityServer4.Models` and attempt to run any migration.

### The issue
`IdentityServer4.Models` provide a variety of classes that handle huge chunks of user authentication and authorization. However, many of these models are incompatible with any sort of `UTF` character encoding. Moreover, I cannot seem to get Pomelo to respect my desires to use a `latin1` default...

Simply adding the IdentityServer4 and creating a migration gives the following migration code (example):
```
b.Property<string>("DeviceCode")
    .IsRequired()
    .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
    .HasMaxLength(200);
```

```
2020-09-29T11:09:18.7639670-06:00 [ERR] (/zbookpro/1) Failed executing DbCommand ("4"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"\n""CREATE TABLE `DeviceCodes` (\n    `UserCode` varchar(200) CHARACTER SET utf8mb4 NOT NULL,\n    `DeviceCode` varchar(200) CHARACTER SET utf8mb4 NOT NULL,\n    `SubjectId` varchar(200) CHARACTER SET utf8mb4 NULL,\n    `ClientId` varchar(200) CHARACTER SET utf8mb4 NOT NULL,\n    `CreationTime` datetime(6) NOT NULL,\n    `Expiration` datetime(6) NOT NULL,\n    `Data` longtext CHARACTER SET utf8mb4 NOT NULL,\n    CONSTRAINT `PK_DeviceCodes` PRIMARY KEY (`UserCode`)\n);"
```

I tried to follow the [config docs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/wiki/Configuration-Options), but the code provided there is invalid:
![Screen Shot 2020-09-29 at 11 42 55 AM](https://user-images.githubusercontent.com/2084821/94596227-17cb4e00-0249-11eb-955a-23bdc089e80f.png)

At this point, I tried to just manually set my entire database to `Latin1`, so I could choose to manually override the columns I want to be UTF:

```
mySqlOptions.
                      .CharSet(CharSet.Latin1)
                      .CharSetBehavior(CharSetBehavior.AppendToAllUnicodeColumns);
```

However, this had no effect. The columns still all have `CHARACTER SET utf8mb4` in the migration. I can use `CharSetBehavior.NeverAppend` to get around the immediate problem, but that isn't what I want. Moreover, it doesn't fix the indexes which get added later.

Next, I tried manually telling EFCore that these columns are actually `latin1`:
```
    protected override void OnModelCreating(ModelBuilder modelBuilder) {
      modelBuilder.Entity<DeviceFlowCodes>(e => {
        e.Property(p => p.UserCode).HasCharSet("latin1");
      });
    }
```

But the generated migration seems to conflict with itself:
```
                    b.Property<string>("UserCode")
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200)
                        .HasAnnotation("MySql:CharSet", "latin1");
```

This does end up working, though. The resulting `UserCode` is `latin1` and the `DeviceCodes` table is created successfully. 

Eventually I got the migration to work by forcibly applying `latin1` to all the relevant fields (everything except email, which can be UTF8).
```
modelBuilder.Entity<UserProfile>(e => {
        e.Property(p => p.Id).HasCharSet("latin1");
        e.Property(p => p.NormalizedUserName).HasCharSet("latin1");
        e.Property(p => p.UserName).HasCharSet("latin1");
        e.Property(p => p.PasswordHash).HasCharSet("latin1");
        e.Property(p => p.SecurityStamp).HasCharSet("latin1");
        e.Property(p => p.ConcurrencyStamp).HasCharSet("latin1");
        e.Property(p => p.PhoneNumber).HasCharSet("latin1");
      });
      modelBuilder.Entity<IdentityRole>(e => {
        e.Property(p => p.Id).HasCharSet("latin1");
        e.Property(p => p.ConcurrencyStamp).HasCharSet("latin1");
        e.Property(p => p.Name).HasCharSet("latin1");
        e.Property(p => p.NormalizedName).HasCharSet("latin1");
      });
      modelBuilder.Entity<IdentityRoleClaim<string>>(e => {
        e.Property(p => p.RoleId).HasCharSet("latin1");
        e.Property(p => p.ClaimType).HasCharSet("latin1");
        e.Property(p => p.ClaimValue).HasCharSet("latin1");
      });
      modelBuilder.Entity<IdentityUserClaim<string>>(e => {
        e.Property(p => p.UserId).HasCharSet("latin1");
        e.Property(p => p.ClaimType).HasCharSet("latin1");
        e.Property(p => p.ClaimValue).HasCharSet("latin1");
      });
      modelBuilder.Entity<IdentityUserLogin<string>>(e => {
        e.Property(p => p.UserId).HasCharSet("latin1");
        e.Property(p => p.LoginProvider).HasCharSet("latin1");
        e.Property(p => p.ProviderKey).HasCharSet("latin1");
        e.Property(p => p.ProviderDisplayName).HasCharSet("latin1");
      });
      modelBuilder.Entity<IdentityUserRole<string>>(e => {
        e.Property(p => p.UserId).HasCharSet("latin1");
        e.Property(p => p.RoleId).HasCharSet("latin1");
      });
      modelBuilder.Entity<IdentityUserToken<string>>(e => {
        e.Property(p => p.UserId).HasCharSet("latin1");
        e.Property(p => p.LoginProvider).HasCharSet("latin1");
        e.Property(p => p.Name).HasCharSet("latin1");
        e.Property(p => p.Value).HasCharSet("latin1");
      });
      modelBuilder.Entity<DeviceFlowCodes>(e => {
        e.Property(p => p.UserCode).HasCharSet("latin1");
        e.Property(p => p.DeviceCode).HasCharSet("latin1");
        e.Property(p => p.SubjectId).HasCharSet("latin1");
        e.Property(p => p.ClientId).HasCharSet("latin1");
        e.Property(p => p.Data).HasCharSet("latin1");
      });
      modelBuilder.Entity<IdentityServer4.EntityFramework.Entities.PersistedGrant>(e => {
        e.Property(p => p.Key).HasCharSet("latin1");
        e.Property(p => p.Type).HasCharSet("latin1");
        e.Property(p => p.Data).HasCharSet("latin1");
        e.Property(p => p.SubjectId).HasCharSet("latin1");
        e.Property(p => p.ClientId).HasCharSet("latin1");
      });
```

### Further technical details

MySQL version: 5.7
Operating system: Ubuntu
Pomelo.EntityFrameworkCore.MySql version: 3.2.1
Microsoft.AspNetCore.App version: 3.1.8

**Comment by lauxjpn** [comment]
We need to update the wiki. Since we introduced `HasCharSet()` in 3.1, `CharSetBehavior()` is basically obsolete and will probably be dropped (or at least marked as obsolete) for 5.0.

Typical setup code would look like the following for 3.2.1:

```c#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder
        .UseMySql(
            "server=127.0.0.1;port=3308;user=root;password=;database=Issue1086",
            b => b
                .ServerVersion("8.0.20-mysql")
                .CharSetBehavior(CharSetBehavior.NeverAppend))
        .UseLoggerFactory(
            LoggerFactory.Create(
                b => b
                    .AddConsole()
                    .AddFilter(level => level >= LogLevel.Information)))
        .EnableSensitiveDataLogging()
        .EnableDetailedErrors();
}
```

So setting `CharSetBehavior(CharSetBehavior.NeverAppend)` should currently be the default. This will not output the charset together with the type, unless specified explicitly by `HasCharSet()`, and even there only if actually needed.

Therefore setting the whole database to `latin1`, using `CharSetBehavior(CharSetBehavior.NeverAppend)` and then using `HasCharSet('utf8mb4')` on the email property, should be the simplest way to go here for you.

---

> `IdentityServer4.Models` provide a variety of classes that handle huge chunks of user authentication and authorization. However, many of these models are incompatible with any sort of UTF character encoding.

That should not be the case. In what format strings are stored in the database is an implementation detail. Once queried, any .NET string in memory is a 16 bit Unicode string. For database-side string storage, UTF-8 ist the defacto standard nowadays. So I would be quite surprised, if for some strange reason, IdentityServer would depend on ASCII/ANSI. If you can, please post some links to reported issues on that, so we can take a look at that.

**Comment by zaneclaes** [comment]
Thanks for the quick reply!

> That should not be the case. In what format strings are stored in the database is an implementation detail.

If changing the format changes the function of the application, then it is (by definition) not an implementation detail. 

Implementation details are those things which are inconsequential toward the ability of the library to fulfill its contract. For example, if the library decided to store everything as binary, that would be an implementation detail... but _only as long as it still fulfilled its contract_ (i.e., the successful storage and retrieval of the well-formed data model). If it suddenly started returning binary to me (instead of strings), or not working at all, then it is no longer an "implementation detail."

>  if for some strange reason, IdentityServer would depend on ASCII/ANSI

That dependency comes implicit with the use of MySQL.

- IdentityServer depends on 200-character-long codes.
- MySQL cannot store these columns in UTF.

**Comment by lauxjpn** [comment]
> That dependency comes implicit with the use of MySQL.
> 
> * IdentityServer depends on 200-character-long codes.
> * MySQL cannot store these columns in UTF.

No sure what you mean by that. Both MySQL and Pomelo are fully capable of storing 200 character long strings in columns with any charset you wish, including `utf8mb3` and `utf8mb4`.

I am actively using IdentityServer with MySQL and Pomelo and so are many others. If you post your project, we should be able to configure it in a way that just works.

(If you can't post the project for some reason, I can also offer you to post a general sample implementation, but since IdentityServer allows for many ways to customize the configuration/implementation, it is usually better to take a look at the actual project (or a trimmed-down version)).

---

> If changing the format changes the behavior of the application, then it is (by definition) not an implementation detail.

IdentityServer is specifically designed in a way, that it does not rely on database specific features, so it works the same way with all major database servers. It should not depend on charsets at all (which makes sense, because charset support in EF Core is only just being introduced with 5.0, so it is not GA yet; Pomelo implemented charsets on its own for 3.1).

**Comment by zaneclaes** [comment]
> Both MySQL and Pomelo are fully capable of storing 200 character long strings in columns with any charset you wish,

I should have been more explicit. I'm referring to the migration error I included in the original post, having to do with the key length, not the column. Lots of people have run in to this, or similar: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/298 https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/136 https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/81

> I am actively using IdentityServer with MySQL and Pomelo with utf8mb4 (the default charset in MySQL 8) and so are many others. If you post your project, we should be able to configure it in a way that just works.

Thanks :) The code I pasted in my OP is actually working well for me. Gripes aside, I do actually prefer to stick with convention and use a default=utf8mb4... even if that means overriding so many properties for IdentityServer.

>  The contract does not specifies anything about how it is stored or what exactly can be stored.

Yes, I agree. But if the database cannot store the model in its default form (without the modifications described in these threads), then the database provider is not compatible with the model. As you said, the goal of IS4 is to:

> [...] work the same way with all major database servers

But, _it doesn't work the same with this database provider_. Patching the model to support the database is not the same thing as "compatibility" with the database.

But perhaps my expectations are unreasonable ;)

Hopefully this will all just go away if dotnetcore5 and IS5 both just move to charset annotations in the code.

**Comment by lauxjpn** [comment]
> I should have been more explicit. I'm referring to the migration error I included in the original post, having to do with the **key length**, not the column. Lots of people have run in to this, or similar: #298 #136 #81

Ah, now we are talking. I think the actual error is missing from the OP. The only thing in there is the general error, that the `CREATE TABLE` statement failed.

Key length restrictions are usually a result of using InnoDB (which we recommend) and are not Pomelo specific. However, we added support in 3.2.0 to configure the prefix length in the model using the Fluent API, so you don't feel pressured to shorten your column length to avoid key length errors.

See #1069 for the `HasKeyLength()` introducing PR and sample code.
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/936#issuecomment-553024052 for a general discussion.

**Comment by mguinness** [comment]
It should be noted that since MySQL 5.7 `innodb_large_prefix` is enabled by default allowing key length up to 3072 bytes for InnoDB tables.

**Comment by zaneclaes** [comment]
> It should be noted that since MySQL 5.7 innodb_large_prefix is enabled by default allowing key length up to 3072 bytes for InnoDB tables.

Ah, I may have been bitten by the fact my database was upgraded from 5.6!

> I think the actual error is missing from the OP.

Whoops!

> See #1069 for the HasPrefixLength() introducing PR and sample code.

Ohh, nice!

**Comment by lauxjpn** [comment]
> Ah, I may have been bitten by the fact my database was upgraded from 5.6!

Definitely possible. It can also depend on what row format is used for the table (from [15.22 InnoDB Limits](https://dev.mysql.com/doc/refman/8.0/en/innodb-limits.html)):

> The index key prefix length limit is `3072` bytes for InnoDB tables that use `DYNAMIC` or `COMPRESSED` row format.
>
>The index key prefix length limit is `767` bytes for InnoDB tables that use the `REDUNDANT` or `COMPACT` row format. For example, you might hit this limit with a column prefix index of more than `191` characters on a `TEXT` or `VARCHAR` column, assuming a `utf8mb4` character set and the maximum of `4` bytes for each character.
>
>Attempting to use an index key prefix length that exceeds the limit returns an error.
>
>If you reduce the InnoDB page size to 8KB or 4KB by specifying the `innodb_page_size` option when creating the MySQL instance, the maximum length of the index key is lowered proportionally, based on the limit of `3072` bytes for a 16KB page size. That is, the maximum index key length is `1536` bytes when the page size is 8KB, and `768` bytes when the page size is 4KB.
>
>The limits that apply to index key prefixes also apply to full-column index keys.

If the `REDUNDANT` or `COMPACT` row format is used, you get `767 bytes / 4 bytes = 191 characters` that can be indexed when using `utf8mb4`.
