### ISSUE TITLE
Log Pomelo version in info output

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1184]
The following log output should also contain the Pomelo version:

```
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.8 initialized 'Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: ServerVersion 5.7.0 MySql SensitiveDataLoggingEnabled DetailedErrorsEnabled
```

Either we can implement this for Pomelo, or the EF Core team can implement this for providers in general.

**Comment by ajcvickers** [comment]
@lauxjpn Seems like a good idea for providers in general. Would you mind filing an issue on efcore?

**Comment by lauxjpn** [comment]
@ajcvickers Done!
