### ISSUE TITLE
scaffolding bug: bit(1) mapped to ulong

### ISSUE THREAD

**Issue by alex-dubatov** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1187]
### Steps to reproduce
``` sql
CREATE DATABASE IF NOT EXISTS `db1`;
USE `db1`;
DROP TABLE IF EXISTS `t1`;

CREATE TABLE `t1` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Gender` bit(1) NOT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

```
dotnet ef dbcontext scaffold "Server=localhost;Database=mydb;User=root;Password=1111;TreatTinyAsBoolean=true;" Pomelo.EntityFrameworkCore.MySql -c MyDB -f -d --no-build -p
```
With TreatTinyAsBoolean=false; same result.

### The issue
Using scaffold command I expect to get mapped c# boolean property from bit(1) mysql column 'Gender'. As was with .net core 2.2.
But i got
```c#
...
[Column(TypeName = "bit(1)")]
public ulong Gender { get; set; }
...
```

### Further technical details

.net core 3.1.8
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.2.2" />

**Comment by mguinness** [comment]
Please update to the latest version 3.2.2 and see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/917#issuecomment-565340084.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/ff1b02fbe0ca912830c4b801163584d8933d6af4/src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs#L256-L263

**Comment by alex-dubatov** [comment]
Ok. I got this problem in 3.2.2.

**Comment by lauxjpn** [comment]
> Please update to the latest version 3.2.2 and see #917 (comment) and #577 (comment) along w/ PR #909.

> Ok. I got this problem in 3.2.2.

@alex-dubatov Just give us a short feedback, that https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/917#issuecomment-565340084 mentined by @mguinness solves your issue (which it should), so we can close this one as a duplicate.

**Comment by alex-dubatov** [comment]
#917 doesn't solve my issue because with ```TreatTinyAsBoolean=false;```. I still don't get bit{1} as bool.

**Comment by lauxjpn** [comment]
> #917 doesn't solve my issue because with TreatTinyAsBoolean=false;. I still don't get bit(1) as bool.

@alex-dubatov Thanks for reporting this issue! It is a regression bug introduced with #1066. We will release a fix (see #1188) shortly.

**Comment by alex-dubatov** [comment]
@lauxjpn  Thanks for you!
I will close the issue after checking the release.

**Comment by lauxjpn** [comment]
@alex-dubatov The fix is now part of the [nightly build feed](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds), in case you want to start using it.

**Comment by alex-dubatov** [comment]
@lauxjpn nuget doesn't find version 3.2.3 in nightly build feed.
Also command below doesn't show version 3.2.3.
```
nuget list -AllVersions -Source "https://pkgs.dev.azure.com/pomelo-efcore/Pomelo.EntityFrameworkCore.MySql/_packaging/pomelo-efcore-public/nuget/v3/index.json"
```

**Comment by lauxjpn** [comment]
> nuget doesn't find version 3.2.3 in nightly build feed.

@alex-dubatov The release is [3.2.3-servicing.20511.3](https://dev.azure.com/pomelo-efcore/Pomelo.EntityFrameworkCore.MySql/_packaging?_a=package&feed=pomelo-efcore-public&package=Pomelo.EntityFrameworkCore.MySql&version=3.2.3-servicing.20511.3&protocolType=NuGet&view=overview) and was added to the feed yesterday.
You need to enable prereleases (use either the checkbox in VS or the `-Prerelease` option for `nuget.exe`).

**Comment by alex-dubatov** [comment]
@lauxjpn Thank you very much for the info!!

**Comment by thulyatech** [comment]
Hi, seems this issue recurred recently. We are facing this issue in the 6.0.2 too. How do we fix the bit flag being produced into ulong rather than boolean? Is there any config that can fix this? Your inputs will be much appreciated

**Comment by thulyatech** [comment]
Hi, Has this issue been regressed in any recent versions? We are using 6.0.2. When we use the config TreatTinyAsBoolean=true, then the tinyint (1) gets produced into bool flag correctly. However, the bit(1) gets produced into ulong rather than bool.

Could you please suggest any fix for this? Thank you.

**Comment by DoomerDGR8** [comment]
I'm in thale latest non preview version of Efcore v8x and am facing this same big. All my bit columns with default set to 1 are read as ulong in the scaffolding process.

**Comment by Flithor** [comment]
It regression again!
