### ISSUE TITLE
Can't connect .net core 3.1 with MySQL 5. 5. 41

### ISSUE THREAD

**Issue by DariaIT** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1196]
### The issue

Hello,
I have .net core 3.1 web application with MSSQL Local Db with migrations and everything work fine.
I have another MySQL Db 5. 5. 41 online where I need to get some data. (just reading)

### Steps to reproduce

1. I install Pomelo.EntityFrameworkCore.MySql 3.2.3 via Nuget

2. Add new DbContext and new DbSet (not sure if I need this, because I have db first aproach):

```C#
namespace Test.Data
{
    public class ReadOnlyDbContext: DbContext
    {
        public ReadOnlyDbContext(DbContextOptions<ReadOnlyDbContext> options)
           : base(options)
        {
        }
        
        public DbSet<contactosTaxas> ContactsTax { get; }

        //for define Db as ReadOnly
        public override int SaveChanges()
        {
            // Throw if they try to call this
            throw new InvalidOperationException("This context is read-only.");
        }
    }
}
```

3. Add new class in Models:

```C#
namespace Test.Models
{
    public class contactsTax
    {
        public int ID { get; }
        public int contactID { get; }
        public int taskKindID { get; }
        public double tax { get; }
    }
}
```

4. Add in Startup.cs

```C#
services.AddDbContextPool<ReadOnlyDbContext>(
    dbContextOptions => 
    dbContextOptions.UseMySql(
        // Replace with your connection string.
        Configuration.GetConnectionString("MySQLConnection"),
        // Replace with your server version and type.
        mySqlOptions => mySqlOptions
            .ServerVersion(new Version(5, 5, 41), ServerType.MySql)
            .CharSetBehavior(CharSetBehavior.NeverAppend)));
```

5. Add connection string in appsettings.json:

```
"ConnectionStrings": {
    "MySQLConnection": "server=000.00.00.00;Database=test_common_ps;user=xxx;password=xxx;"
}
```

6. Add to Controller constructor:

```C#
public class BaseController : Controller
{
    protected readonly ReadOnlyDbContext _context;

    public BaseController(ReadOnlyDbContext context)
    {
        _context = context;
    }
}
```

7. Finally call it in Index function:

```C#
public async Task<IActionResult> Index()
{
    ...
    var testQuery = _context.ContactsTax;
    ...
}
```

Issue: Value is always empty. What am I missing? Is it because of incompatibility? Ou something with my code? I do not get any error. Tryed to connect to MySql Server with WorkBench with success.

### Further technical details

MySQL version: 5. 5. 41
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 3.2.3
Microsoft.AspNetCore.App version: 3.1

**Comment by mguinness** [comment]
As it stands your test query just references the DBSet, what happens when you append `.ToList()` to query?

**Comment by DariaIT** [comment]
It throw exception ArgumentNullException, because it is impossible to create List from null. I debug application with various breakpoints and it is null there ...

**Comment by mguinness** [comment]
Try adding a setter back to your DBSet.

**Comment by DariaIT** [comment]
Hello,
thank you, it did the trick, I add setters everywhere and start to see errors, after modified DbSet line:
public DbSet<contactosTaxas> contactsTax { get; set; } // has to match exact column name
and add  var testQuery = _context.contactsTax.ToList();
it start working.
