### ISSUE TITLE
MySqlConnector 1.0.0 support

### ISSUE THREAD

**Issue by sukhdev22** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1198]
### When will it support MySqlConnector 1.0.0

**Comment by lauxjpn** [comment]
This is a duplicate of #1161.
Everything of interest to you should be in there.

TLDR: The prereleases of Pomelo 5.0 already supports MySqlConnector >= 1.0.0. There will not be added support in Pomelo < 5.0.
