### ISSUE TITLE
Revamp collation (and charset) support to be in line with EF Core 5

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1199]
Since EF Core 5 brings its own collation support to the table, we need to do some spring cleaning on our own support that we introduced in 3.0.

Afterwards, implementing #618 and #913 can be considered.

**Comment by mguinness** [comment]
For reference, see [Configuring Character Sets and Collations in EF Core](https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core-charset.html) with MySQL Connector.

**Comment by lauxjpn** [comment]
@mguinness Thanks, I wasn't even aware, that Oracle had implemented its own support in the past. We could consider supporting their old mechanisms in a compatibility package (or namespace) or something similar, to make it easier for users to migrate to Pomelo. This support would likely introduce a set of extension methods (and attributes) of the same namespace they use, that would be marked as obsolete, but would forward their calls to ne new EF Core 5 implementations.
