### ISSUE TITLE
Contrain Migration Names too long

### ISSUE THREAD

**Issue by matthewjcooper** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#12]
If the model and field names of a relationship are long, the generated contraint is too long for MYSQL:

Pomelo.Data.MySql.MySqlException: Identifier name 'AK_OrganizationPatientInsurances_OrganizationPatientId_InsurancePriority' is too long

**Comment by Kagamine** [comment]
What name did you used?

**Comment by matthewjcooper** [comment]
Ah, my bad i didn't use HasName, I Just did:
```
builder.Entity<OrganizationPatientInsurance>()
              .HasAlternateKey(i => new { i.OrganizationPatientId, i.InsurancePriority })
```

However this works:
```
builder.Entity<OrganizationPatientInsurance>()
              .HasAlternateKey(i => new { i.OrganizationPatientId, i.InsurancePriority })
              .HasName("AK_OrgPat_InsPri");


```

**Comment by Kagamine** [comment]
But I will still make something to modify the long alternate key name which generated by ef. Thanks for your report. :smile:
