### ISSUE TITLE
PARTITION BY being generated for MySQL < 8.0

### ISSUE THREAD

**Issue by zhangqx1** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1204]
### Steps to reproduce
Use MySQL 5.7 ,EF Core 3.1
```
var sourceQuery = _detailRepository
                .WithDetails(x => x.SalesContract)
                .Select(x => new { Key = new { x.SalesContractId, x.ProductId }, Entry = x });

            var query = sourceQuery
                .Select(x => x.Key).Distinct()
                .SelectMany(key => 
                    sourceQuery.Where(e => e.Key.SalesContractId == key.SalesContractId && e.Key.ProductId == key.ProductId)
                    .Select(e => e.Entry)
                    .OrderByDescending(e => e.ProvideStartDate)
                    .Take(1));
```

### The issue
```
Exception message:
Stack trace:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `c1`.`SalesContractId`, `c1`.`ProductVasId` ORDER 
```

### Further technical details

MySQL version: 5.7.31
Operating system: 
Pomelo.EntityFrameworkCore.MySql version:3.1.1
Microsoft.AspNetCore.App version:3.1.6

how to disable the OVER(PARTITION ..) entirely for version< 8.0 ?

**Comment by lauxjpn** [comment]
The query you are building requires [window function](https://en.wikipedia.org/wiki/SQL_window_function) support, which is available only for MySQL 8.0.0+ or MariaDB 10.2.0+.

For your query to work with MySQL 5.7, you will need to split-up the query. You can also first query the data you need, and then switch to client evaluation by calling `.AsEnumerable()` and then perform the rest of the query client-side.
