### ISSUE TITLE
Conflict with dependencies

### ISSUE THREAD

**Issue by kristx300** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1206]
Pomelo.EntityFrameworkCore.MySql - require - MySqlConnector <1.0
HealthCheck.MySql - require - MySqlConnctor >1.0
![image](https://user-images.githubusercontent.com/11241838/96820400-81a9d280-1458-11eb-86eb-d6910aafc3d4.png)
Or write issue to HealthCheck repo?

**Comment by mguinness** [comment]
See [Support for MySqlConnector >1.0](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1161) and [Incompatible with MySqlConnector v. 1.x](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/612)

**Comment by kristx300** [comment]
Checked.
[Issue](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/612) closed, but not solved.
![image](https://user-images.githubusercontent.com/11241838/96823853-fb918a00-145f-11eb-98a4-76a1c68e1606.png)

**Comment by mguinness** [comment]
Also see [Update MySqlConnector to 1.0](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/561) which is still open, but now redundant.

**Comment by kristx300** [comment]
In any case, I think we need to wait for the new release from HealthCheck.
Or PomeloFoundation will develop full support health check provider. That's sounds good.

**Comment by lauxjpn** [comment]
> In any case, I think we need to wait for the new release from HealthCheck.

@kristx300 What is `HealthCheck`? Chan you provide us with a link?

There is an alpha prerelease of Pomelo available that is compatible with EF Core 5, which uses MySqlConnector >= 1.0.0.
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088#issuecomment-707776730 for further details.

**Comment by kristx300** [comment]
One simple class and code.
[MySqlHealthCheck.cs](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.MySql/MySqlHealthCheck.cs)

**Comment by lauxjpn** [comment]
@kristx300 I see, so I am assuming you are using the [MySqlHealthCheck.cs](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.MySql/MySqlHealthCheck.cs) class, but also Pomelo 3.2.3 with EF Core 3.1.x.

So as mentioned above, you could just use EF Core 5 and the Pomelo 5.0 alpha prerelease.

If you want to keep using EF Core 3.1.x you could just use a HealthChecks release before https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/612. Their MySql package version `3.1.1` should be the last one that supports MySqlConnector < 1.0.0.

You could also move the HealthCheck to a different project (can be in the same solution). Different projects can reference the same package in different versions.

**Comment by kristx300** [comment]
@lauxjpn I think, better way is to copy one class to ext lib in solution
And when HC fixes it, I can easily replace the code with lib

//I am wait full release .Net 5 and base depends libs
