### ISSUE TITLE
LINQ warning for Contains, EndsWith and StartsWith

### ISSUE THREAD

**Issue by mguinness** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#122]
I'm getting the following warning when using the Pomelo provider:

```Linq translation for method 'Contains' used by this database provider can return incorrect results when the value argument contains wildcard characters (e.g. '%' or '_').```

It appears there is a warning for providers that mentions this issue at https://github.com/aspnet/EntityFramework/issues/474

**Comment by Kagamine** [comment]
Fixed in 1.1.0-rtm-10007
