### ISSUE TITLE
password not suppose char

### ISSUE THREAD

**Issue by hantsukinosora** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1263]
```
Exception message:Access denied for user 'root'@'localhost' (using password: YES)
Stack trace:
```

### Further technical details

MariaDB version:10.4 
Operating system: windows 10 pro
Pomelo.EntityFrameworkCore.MySql version:3.2.4
Microsoft.AspNetCore.App version:3.1

Other details about my project setup:
My command wtih
dotnet ef dbcontext scaffold "Server=localhost;Database=DB;User=root;Password=Pwd;TreatTinyAsBoolean=true;persistsecurityinfo=True" "Pomelo.EntityFrameworkCore.MySql"

if Password contains !@#$%^&*,then print message Access denied for user 'root'@'localhost' (using password: YES)
so I remove these Char,then the command success

**Comment by lauxjpn** [comment]
@hantsukinosora I cannot reproduce the issue that you are describing.

I executed the following script on my MariaDB 10.4.14 database:

```sql
drop database if exists `Issue1263`;
create database `Issue1263`;
use `Issue1263`;

CREATE TABLE `IceCreams` (
    `IceCreamId` int NOT NULL AUTO_INCREMENT,
    `Name` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
);

DROP USER IF EXISTS 'issue1263user'@'localhost';
CREATE USER 'issue1263user'@'localhost' IDENTIFIED BY '!@#$%^&*';
grant all privileges on `Issue1263`.* to 'issue1263user'@'localhost';
```

I then created a new .NET Core 3.1 console project, added the necessary package references, and finally ran the following line in Powershell:

```console
dotnet ef dbcontext scaffold "Server=localhost;Port=3306;User=issue1263user;Password=!@#$%^&*;Database=Issue1263;TreatTinyAsBoolean=true;persistsecurityinfo=True" "Pomelo.EntityFrameworkCore.MySql"
```

It ran successfully and create the following files:

```console
26.11.2020  08:52               230 IceCreams.cs
26.11.2020  08:52             1.772 Issue1263Context.cs
```

**Comment by lauxjpn** [comment]
@hantsukinosora Since we haven't heard back from you, we are closing this one.
