### ISSUE TITLE
[Question] EF.Functions.Match - set multiple columns in MATCH

### ISSUE THREAD

**Issue by maratoss** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1267]
Hi!
Is it possible to set multiple columns in EF.Functions.Match API?
I went throught integrated tests and did not find the answer.
like a
```sql
SELECT * FROM articles WHERE MATCH (title,body)
    AGAINST ('+MySQL -YourSQL' IN BOOLEAN MODE);
```
using Pomelo.EntityFrameworkCore.MySql v3.2.4

**Comment by maratoss** [comment]
I read that thread and now i understand that this is not implemented yet
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1056

**Comment by lauxjpn** [comment]
@maratoss A simple immediate solution to the issue should be to just use multiple `Match()` calls:

```c#
var criteria = "+MySQL -YourSQL";
var multiColumnMatchResult = context.Articles
    .Where(a => EF.Functions.Match(a.Title, criteria, MySqlMatchSearchMode.Boolean) ||
                EF.Functions.Match(a.Body, criteria, MySqlMatchSearchMode.Boolean))
    .ToList();
```
