### ISSUE TITLE
Migrations: computed column with STORED option

### ISSUE THREAD

**Issue by maratoss** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1269]
### Steps to reproduce
I would like to create a computed value and make it stored
```cs
    public class FooMap : IEntityTypeConfiguration<Foo>
    {
        public void Configure(EntityTypeBuilder<Foo> builder)
        {
            builder.HasNoKey();
            builder.Property(x => x.C).HasComputedColumnSql("CONCAT(`A`, `B`)", stored: true);
        }
    }

    public class Foo
    {
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
    }
```

### The issue
but i've got in db this computed column as VIRTUAL instead of STORED:

```sql
CREATE TABLE `Foo` (
	`A` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`B` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`C` LONGTEXT DEFAULT NULL AS (concat(`A`,`B`)) virtual COLLATE 'utf8mb4_0900_ai_ci'
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
```

### Further technical details

MySQL version: 8.0.21
Operating system: db OS: Debian GNU/Linux 10 (buster) (docker), client: win10
Pomelo.EntityFrameworkCore.MySql version: 3.2.4

**Comment by lauxjpn** [comment]
@maratoss Thanks for reporting! Will be part of `5.0.0-alpha.4` and in your [nightly build feed](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) once #1270 has been merged.
