### ISSUE TITLE
Ef Core 5 scaffold flags doesn't work

### ISSUE THREAD

**Issue by barnuri** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1276]
### The issue
When you use ef core 5 scaffold flags dosent work 
1) --no-onconfiguring
2) --namespace 
3) --context-namespace

docs:
https://docs.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-dbcontext-scaffold

![image](https://user-images.githubusercontent.com/13019522/102643053-5517eb80-4167-11eb-80ac-812be30458af.png)

### Further technical details

Operating system: windows
Pomelo.EntityFrameworkCore.MySql version:   5.0.0-alpha.2
Microsoft.AspNetCore.App version:   net5.0

**Comment by Ghostbxz** [comment]
I have this issue too please fix it.

**Comment by lauxjpn** [comment]
This is likely to have the same cause as your other reported issue #1277, which is likely to be that you are using an older version of the `dotnet-ef` tool.

**Comment by barnuri** [comment]
i had version 5.0.0 now i update it to 5.0.1 and its work ty
