### ISSUE TITLE
Use MySqlException.IsTransient

### ISSUE THREAD

**Issue by bgrainger** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1285]
https://github.com/mysql-net/MySqlConnector/issues/849 called for `DbException.IsTransient` to be implemented in MySqlConnector.

I ended up using the same list of error codes as Pomelo does:

* https://github.com/mysql-net/MySqlConnector/blob/396ad9d8d9aed29c6dc74e64e4678109ca306e51/src/MySqlConnector/MySqlException.cs#L130-L135
* https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/33b8d595a9e69f0a67301ed64dbf04220f39f002/src/EFCore.MySql/Storage/Internal/MySqlTransientExceptionDetector.cs#L25-L38

Once MySqlConnector > 1.3.0-beta.1 ships (with this change), Pomelo could update its method to simply delegate to `MySqlException.IsTransient`. This would let Pomelo benefit from any additional errors MySqlConnector considers to be transient in future versions.

OTOH, if you want to remain in control of this logic and not be affected by unexpected changes in MySqlConnector's implementation, then I understand that and you can close this issue. 😀

**Comment by lauxjpn** [comment]
Thanks, we are using it from now on.

Not considering `MySqlErrorCode.CommandTimeoutExpired` as transient as described in https://github.com/mysql-net/MySqlConnector/issues/940 makes sense.
