### ISSUE TITLE
Linq Union

### ISSUE THREAD

**Issue by sexysat** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#129]
Im trying to do a UNION ALL query in MySQL using LINQ Concat but the queries are run separately using Local evaluation 

    var epg = EPG.Data.Where(e => e.ChannelId == 100).Select(c => c.ChannelId)
                    .Concat(EPG.Data.Where(e => e.ChannelId == 972).Select(c => c.ChannelId));

In the console this message is shown

 warn: Microsoft.EntityFrameworkCore.Query.Internal.MySqlQueryCompilationContextFactory[8]
      The LINQ expression 'Concat({from EPGItem e in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[WebApplication.Models.EPGItem]) where ([e].ChannelId == 972) select [e].ChannelId})' could not be translated and will be evaluated locally.

MySQL version: 5.7.16-0ubuntu0.16.04.1-log
Operating system: Ubuntu 16.04 
Pomelo.EntityFrameworkCore.MySql version: 1.1.0

**Comment by Kagamine** [comment]
https://github.com/aspnet/EntityFramework/issues/6812
