### ISSUE TITLE
Invalid sql statement is generated by the library when integrated with odata / MySQL 5.7+ returns NULL for constant values in LEFT JOINs if statement contains ORDER BY

### ISSUE THREAD

**Issue by OlehGaras** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1293]
### Steps to reproduce
Steps to reproduce were completely described in the separate issue created for OData/WebApi here: https://github.com/OData/WebApi/issues/2124

Please find the example where the error can be reproduced here: https://github.com/huiali/odata-sample

### The issue
```
OData URL-->GET
https://localhost:5002/oq/A?$expand=B($expand=C)-->
ERROR --> Value cannot be null. (Parameter 'key')
```

Using OData, expand inside another expand, or filter inside expand the error appears.

Investigations in the separate thread (https://github.com/OData/WebApi/issues/2124) showed that the issue is with the sql statement that is generated by the Pomelo.EntityFrameworkCore.MySql lib when OData is executing expand inside another expand

### Further technical details
Pomelo.EntityFrameworkCore.MySql version: 3.2.4
Microsoft.AspNetCore.App version: 3.1
Microsoft.AspNetCore.OData version: 7.5.0

**Comment by mguinness** [comment]
>  Investigations in the separate thread (OData/WebApi#2124) showed that the issue is with the sql statement that is generated by the Pomelo.EntityFrameworkCore.MySql lib when OData is executing expand inside another expand

That is contrary to https://github.com/OData/WebApi/issues/2124#issuecomment-690886665 which states the problem is with MySQL engine and not the Pomelo provider (same issue w/ Oracle provider).

Also from same thread, this is only an issue with MySQL 8.0 and not MariaDB 10.  You didn't state what engine and version you are using so please add that above (as requested in new issue template).

I would suggest looking at [MySQL 8.0 Release Notes](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/) for fixes to known issues and also search [MySQL Bug System](https://bugs.mysql.com/) for reported issues.  MySQL 8.0.22 has some serious regression bugs (see #1207, #1210 and #1216) so you may need to revert to 8.0.21 until Oracle fixes these bugs.

**Comment by lauxjpn** [comment]
@OlehGaras I posted [my answer](https://github.com/OData/WebApi/issues/2124#issuecomment-760641600) over on the original https://github.com/OData/WebApi/issues/2124 issue:

> I can confirm that this is a MySQL database engine bug, that I reported as [[REGRESSION] Order by and constant from left joined table result in NULL value](https://bugs.mysql.com/bug.php?id=96947) to Oracle over a year ago.
> 
> In my personal experience, the MySQL dev team works very slow when it comes to bugs, even critical ones like this. So I would not get my hopes up, that this will be fixed anytime soon. Of course it might help to post a comment on the bug-tracker issue, so they are aware that this is still a huge and critical issue.
> 
> > Maybe MySql team fixed it in the higher versions.
> 
> @woojunfeng Unfortunately, they did not.
> 
> > But what about thousands of people using mysql (buggy version ) who wants to use oData ?
> 
> @BinduShreeU You have currently 3 options:
> 
> * Use MariaDB instead of MySQL.
> * Use MySQL 6, which will reach its [end-of-life](https://endoflife.software/applications/databases/mysql) in about two weeks on 2021-02-05.
> * Do not order the result server side. Instead, query the result unordered and order it client side.

**Comment by OlehGaras** [comment]
@mguinness , @lauxjpn 
thanks for your help,
I use MySQL 5.7.12, so I hope the workaround will fix my issue.

**Comment by lauxjpn** [comment]
We implemented a workaround for this MySQL bug in Pomelo `5.0.0` with #1294 and in Pomelo `3.2.5` with 30295d1.
Both are already available in our [nightly builds](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/tree/3.2-maint#nightly-builds) as _prereleases_.

**Comment by OlehGaras** [comment]
@lauxjpn , I used the package 3.2.5-servicing.21065.4 as you suggested and checked the fix you applied.
I found out that it helps but not completely, I got the same error as previously: 
ERROR --> Value cannot be null. (Parameter 'key').

Except constantExpression the same problem exists with the parameterExpression in that case, I think they have to be explicitly casted too. 
I cloned your repo, extended your fix, build the package locally and used it inside my solution and it started to work perfectly.

Here is the PR with my changes
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1295/commits

Please take a look. 

Thanks

**Comment by lauxjpn** [comment]
Looks like Oracle fixed the issue in a recent version.

**Comment by mguinness** [comment]
Out of interest, due to regression bugs (see #1207, #1210 and #1216) are you still using MySQL 8.0.21 or have you updated?

**Comment by lauxjpn** [comment]
For the #1457, I just upgraded all versions to the latest release.
For my own projects, I have been running MySQL 8.0.25 for 2 or 3 weeks without issues (even though not all of the critical bugs have been fixed yet).

**Comment by mguinness** [comment]
Thanks for sharing, good to know these bugs are being addressed by Oracle.  And kudos to you for all the work that you do on this project.
