### ISSUE TITLE
The behavior of canceling the MySqlConnection.OpenAsnyc does not match expectations.

### ISSUE THREAD

**Issue by Flithor** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1308]
Related to:
https://github.com/mysql-net/MySqlConnector/issues/931
(Wait for fix and release)

**Comment by Flithor** [comment]
@lauxjpn it has fixed, I think it's time to fix in this library.

**Comment by lauxjpn** [comment]
@Flithor This seems to be only released in the latest _beta_ upstream. We usually only reference the official releases from MySqlConnector.

There is nothing stopping you to just reference a newer version of MySqlConnector. You don't have to use the exact version, that is referenced by Pomelo.
You can see that on [nuget.org](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/5.0.0-alpha.2) under _Dependencies_:

> .NETStandard 2.1
> Microsoft.EntityFrameworkCore.Relational (>= 5.0.0)
> MySqlConnector (**>= 1.1.0**)

It says `>= 1.1.0`, so feel free to use MySqlConnector `1.3.0-beta.4`.

**Comment by lauxjpn** [comment]
Current versions of Pomelo use versions of MySqlConnector that contain the fix.
