### ISSUE TITLE
How to GROUP BY over years and COUNT(*)?

### ISSUE THREAD

**Issue by fanjunfengxx** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1310]
How to use EF architecture, to achieve statistics, the following SQL statement， SELECT DATE_FORMAT(INFORMTIME,'%Y') date, COUNT(*) count FROM INFORMTBL WHERE INFORMTYPE = '1'

**Comment by lauxjpn** [comment]
@fanjunfengxx Here is some full sample code, returning the count of non-alcoholic expiring ice creams per year:

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
using Pomelo.EntityFrameworkCore.MySql.Storage;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int IceCreamId { get; set; }
        public string Name { get; set; }
        public DateTime ExpirationDate { get; set; }
        public bool ContainsAlcohol { get; set; }
    }
    
    public class Context : DbContext
    {
        public virtual DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var connectionString = "server=127.0.0.1;port=3308;user=root;password=;database=Issue1310";

            optionsBuilder.UseMySql(
                    connectionString,
                    options => options.CharSetBehavior(CharSetBehavior.NeverAppend)
                        .ServerVersion(ServerVersion.AutoDetect(connectionString)))
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        configure => configure
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream>(
                entity =>
                {
                    entity.HasData(
                        new IceCream {IceCreamId = 1, Name = "Vanilla", ExpirationDate = new DateTime(2022, 6, 30)},
                        new IceCream {IceCreamId = 2, Name = "Chocolate", ExpirationDate = new DateTime(2022, 6, 30)},
                        new IceCream {IceCreamId = 3, Name = "Matcha", ExpirationDate = new DateTime(2021, 12, 31)},
                        new IceCream {IceCreamId = 4, Name = "Vanilla Bean Bourbon", ExpirationDate = new DateTime(2022, 6, 30), ContainsAlcohol = true});
                });
        }
    }

    internal static class Program
    {
        private static void Main(string[] args)
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var nonAlcoholicIceCreamExpirationCountPerYear = context.IceCreams
                .Where(i => !i.ContainsAlcohol)
                .GroupBy(i => i.ExpirationDate.Year)
                .Select(g => new {Year = g.Key, Count = g.Count()})
                .OrderBy(n => n.Year)
                .ToList();

            Trace.Assert(nonAlcoholicIceCreamExpirationCountPerYear.Count == 2);
            Trace.Assert(nonAlcoholicIceCreamExpirationCountPerYear[0].Year == 2021);
            Trace.Assert(nonAlcoholicIceCreamExpirationCountPerYear[0].Count == 1);
            Trace.Assert(nonAlcoholicIceCreamExpirationCountPerYear[1].Year == 2022);
            Trace.Assert(nonAlcoholicIceCreamExpirationCountPerYear[1].Count == 2);
        }
    }
}
```

</details>

This is the query used:

```c#
var nonAlcoholicIceCreamExpirationCountPerYear = context.IceCreams
    .Where(i => !i.ContainsAlcohol)
    .GroupBy(i => i.ExpirationDate.Year)
    .Select(g => new {Year = g.Key, Count = g.Count()})
    .OrderBy(n => n.Year)
    .ToList();
```

It generates the following SQL:

```sql
SELECT EXTRACT(year FROM `i`.`ExpirationDate`) AS `Year`, COUNT(*) AS `Count`
      FROM `IceCreams` AS `i`
      WHERE NOT (`i`.`ContainsAlcohol`)
      GROUP BY EXTRACT(year FROM `i`.`ExpirationDate`)
      ORDER BY EXTRACT(year FROM `i`.`ExpirationDate`)
```

For more information, see [Complex Query Operators: GroupBy](https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#groupby).

**Comment by fanjunfengxx** [comment]
I have received your email, which has solved my problem perfectly.
 thank you













At 2021-01-26 20:32:09, "Laurents Meyer" <notifications@github.com> wrote:

@fanjunfengxx Here is some full sample code, returning the count of non-alcoholic expiring ice creams per year:

Program.cs
usingSystem;
usingSystem.Diagnostics;
usingSystem.Linq;
usingMicrosoft.EntityFrameworkCore;
usingMicrosoft.Extensions.Logging;
usingPomelo.EntityFrameworkCore.MySql.Infrastructure;
usingPomelo.EntityFrameworkCore.MySql.Storage;

namespaceIssueConsoleTemplate
{
    publicclassIceCream
    {
        publicintIceCreamId { get; set; }
        publicstringName { get; set; }
        publicDateTimeExpirationDate { get; set; }
        publicboolContainsAlcohol { get; set; }
    }
    
    publicclassContext : DbContext
    {
        publicvirtualDbSet<IceCream> IceCreams { get; set; }

        protectedoverridevoidOnConfiguring(DbContextOptionsBuilderoptionsBuilder)
        {
            varconnectionString="server=127.0.0.1;port=3308;user=root;password=;database=Issue1310";

            optionsBuilder.UseMySql(
                    connectionString,
                    options=>options.CharSetBehavior(CharSetBehavior.NeverAppend)
                        .ServerVersion(ServerVersion.AutoDetect(connectionString)))
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        configure=>configure
                            .AddConsole()
                            .AddFilter(level=>level>=LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protectedoverridevoidOnModelCreating(ModelBuildermodelBuilder)
        {
            modelBuilder.Entity<IceCream>(
                entity=>
                {
                    entity.HasData(
                        newIceCream {IceCreamId=1, Name="Vanilla", ExpirationDate=newDateTime(2022, 6, 30)},
                        newIceCream {IceCreamId=2, Name="Chocolate", ExpirationDate=newDateTime(2022, 6, 30)},
                        newIceCream {IceCreamId=3, Name="Matcha", ExpirationDate=newDateTime(2021, 12, 31)},
                        newIceCream {IceCreamId=4, Name="Vanilla Bean Bourbon", ExpirationDate=newDateTime(2022, 6, 30), ContainsAlcohol=true});
                });
        }
    }

    internalstaticclassProgram
    {
        privatestaticvoidMain(string[] args)
        {
            usingvarcontext=newContext();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            varnonAlcoholicIceCreamExpirationCountPerYear=context.IceCreams
                .Where(i=>!i.ContainsAlcohol)
                .GroupBy(i=>i.ExpirationDate.Year)
                .Select(g=>new {Year=g.Key, Count=g.Count()})
                .OrderBy(n=>n.Year)
                .ToList();

            Trace.Assert(nonAlcoholicIceCreamExpirationCountPerYear.Count==2);
            Trace.Assert(nonAlcoholicIceCreamExpirationCountPerYear[0].Year==2021);
            Trace.Assert(nonAlcoholicIceCreamExpirationCountPerYear[0].Count==1);
            Trace.Assert(nonAlcoholicIceCreamExpirationCountPerYear[1].Year==2022);
            Trace.Assert(nonAlcoholicIceCreamExpirationCountPerYear[1].Count==2);
        }
    }
}

This is the query used:

varnonAlcoholicIceCreamExpirationCountPerYear=context.IceCreams
    .Where(i=>!i.ContainsAlcohol)
    .GroupBy(i=>i.ExpirationDate.Year)
    .Select(g=>new {Year=g.Key, Count=g.Count()})
    .OrderBy(n=>n.Year)
    .ToList();

It generates the following SQL:

SELECT EXTRACT(year FROM`i`.`ExpirationDate`) AS`Year`, COUNT(*) AS`Count`FROM`IceCreams`AS`i`WHERE NOT (`i`.`ContainsAlcohol`)
      GROUP BY EXTRACT(year FROM`i`.`ExpirationDate`)
      ORDER BY EXTRACT(year FROM`i`.`ExpirationDate`)

For more information, see Complex Query Operators: GroupBy.
