### ISSUE TITLE
Json Converter not working

### ISSUE THREAD

**Issue by agmorpheus** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1318]
### Steps to reproduce
```C#
modelBuilder
    .Entity<Feedback>()
    .Property(e => e.JsonResponse).HasConversion(
        v => JsonConvert.SerializeObject(v, settings),
        v => JsonConvert.DeserializeObject<object>(v, settings));
```

### The issue
I moved from MSSQL to MySQL. After the move the Json convertor is not working anymore. The object is serialized to the db field but it is not deserialized back to the object. 
In the MSSQL field the object was stored like this: `{"hardtofind":true,...`
Now in MySQL it is stored like this: `"{\"hardtofind\":true,...`
Looks like all " are escaped. I am not sure if this is the problem.

How can I get this back as object like before?
Thanks for your help.

### Further technical details

MySQL version: 8.0.22
Operating system: Windows Server 2019
Pomelo.EntityFrameworkCore.MySql version: 5.0 alpha 2
Microsoft.AspNetCore.App version: 5.02

**Comment by mguinness** [comment]
What is the data type of the field in the db, [text](https://dev.mysql.com/doc/refman/8.0/en/blob.html) or [json](https://dev.mysql.com/doc/refman/8.0/en/json.html)?

For example using value conversions see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1039#issuecomment-599140036.

For full JSON support see the example at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/14#issuecomment-725257107.

**Comment by agmorpheus** [comment]
Perfect, I got it working with the Json example. Thanks!
