### ISSUE TITLE
.OrderBy(x => Guid.NewGuid())  Cannot take effect

### ISSUE THREAD

**Issue by AlightChen** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1320]
Mysql's function to return a random piece of data is order by RAND(), not order by UUID(),as the picture shows

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/bd1f8369e73a2555eef989e0c4503d84a5180fa0/src/EFCore.MySql/Query/Internal/MySqlNewGuidTranslator.cs#L30-L35

**Comment by mguinness** [comment]
Duplicate of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/265

**Comment by AlightChen** [comment]
> Duplicate of #265, also see [dotnet/efcore#23145](https://github.com/dotnet/efcore/pull/23145).

Thanks
