### ISSUE TITLE
Pomelo.EntityFrameworkCore.MySql

### ISSUE THREAD

**Issue by JoannaCatts** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1324]
Hello,
can anybody support me in the ECCN classification for Pomelo.EntityFrameworkCore.MySql?

**Comment by mguinness** [comment]
[Export Administration Regulations](https://en.wikipedia.org/wiki/Export_Administration_Regulations) is beyond the scope of issues related to this repo.

See [US Export Administration Regulations (EAR)](https://docs.microsoft.com/en-us/compliance/regulatory/offering-ear#frequently-asked-questions) in relation to Microsoft products.
