### ISSUE TITLE
Error mssage "An error occurred using the connection to database '' on server '127.0.0.1'" using 5.0.0-alpha.2

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1328]
I am using the alpha2. Maybe this is a general problem, but I have the problem, that the API Server takes long to connect to the MYSQL Server (installed on the same server). The API returns a result after 15 sec. Further requests return results within 6 ms. After some minutes again a request takes 15 sec. In the log I find this:
`An error occurred using the connection to database '' on server '127.0.0.1'.` or sometimes this
`An error occurred using the connection to database 'feedback' on server '127.0.0.1'.` 

Can someone help me with this?

_Originally posted by @agmorpheus in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088#issuecomment-776056664_

**Comment by agmorpheus** [comment]
Even with 'localhost' the same problem.
Right now i am using .EnableRetryOnFailure() not to get a the response code 500.
Before always 500 was returned.

**Comment by lauxjpn** [comment]
@agmorpheus There should be no connection issues with Pomelo win _any_ version.

This is likely some kind of configuration issue on your end (either database server, network or software based).

I would start by retrieving the number of currently opened connections to the database server and compare that value against the `max_connection` MySQL value:

```sql
select @@max_connections;
show status where `variable_name` = 'Threads_connected';
show processlist;
```

**Comment by agmorpheus** [comment]
I moved from MySQL to MariaDB. It looks like, the problem is solved for me. Thanks.

**Comment by lauxjpn** [comment]
> I moved from MySQL to MariaDB. It looks like, the problem is solved for me. Thanks.

Thanks for letting us know.
If this should arise with MariaDB as well (which it might), we can open this again.
