### ISSUE TITLE
Configuring a console app

### ISSUE THREAD

**Issue by KevinBurton** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1333]
I am unclear in the instructions as to how I should properly configure the provider in a console application. For using MS SQL I have 

```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder.UseSqlServer();
}
```
But I cannot get it work. I currently am stuck with

```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    // https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/README.md
    optionsBuilder.UseMySql(
    // Replace with your connection string.
    "server=localhost;user=root;password=1234;database=ef",
    // Replace with your server version and type.
    // For common usages, see pull request #1233.
    new MySqlServerVersion(new Version(8, 0, 21)), // use MariaDbServerVersion for MariaDB
    mySqlOptions => mySqlOptions
        .CharSetBehavior(CharSetBehavior.NeverAppend))
        // Everything from this point on is optional but helps with debugging.
        .EnableSensitiveDataLogging()
        .EnableDetailedErrors();
    ));
}
```

The main problems seem to be the 'MySqlServerVersion' and 'CharSetBehavior' is not defined.

MySQL version: MariaDB (from the connection I am not sure how to tell what version the server is)
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.2.4
Microsoft.AspNetCore.App version: .NET Core 3.1 (but this is a Console app)

**Comment by mguinness** [comment]
> The main problems seem to be the 'MySqlServerVersion' and 'CharSetBehavior' is not defined.

I think those are new to EF Core 5.0 so you probably need to use the following for 3.x provider:

```C#
optionsBuilder.UseMySql("server=localhost;user=root;password=1234;database=ef", 
    opts => opts.ServerVersion(new Version(8, 0, 21), ServerType.MySql));
```

> from the connection I am not sure how to tell what version the server is

Use `SELECT VERSION();` to get the version number.

**Comment by KevinBurton** [comment]
I am sorry I must just need another set of eyes to look at it. I have:

```
        protected override void OnConfiguring(
            DbContextOptionsBuilder optionsBuilder)
        {
            // https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/README.md
            optionsBuilder.UseMySql(
            // Replace with your connection string.
            "server=localhost;user=root;password=1234;database=ef",
            opts => opts.ServerVersion(new Version(8, 0, 21), ServerType.MySql)
            );
        }
```
I still see errors at 'ServerVersion' and at the semicolon end.  For some reason the code still thinks that I am trying to access 'MySqlServerVersion'?
![image](https://user-images.githubusercontent.com/2643566/108657092-c178d900-748f-11eb-988e-0dda11869d58.png)
and
![image](https://user-images.githubusercontent.com/2643566/108655641-65ae5000-748f-11eb-8a1f-31c12751fafb.png)
The MariaDB server version show up as 10.4.14-8-MariaDB-enterprise-log

**Comment by mguinness** [comment]
Share your `.csproj` file so we can help further.  Based on your server version use below:

```C#
optionsBuilder.UseMySql("server=localhost;user=root;password=1234;database=ef", 
    opts => opts.ServerVersion(new Version(10, 4, 14), ServerType.MariaDb));
```

**Comment by KevinBurton** [comment]
Thank you. It works now.
