### ISSUE TITLE
TinnyInt(1)--> Boolean  and TinnyInt --> sbyte [feature?  or becoming a bug?]

### ISSUE THREAD

**Issue by ruirodrigues1971** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1337]
The standard in MySQL world is to consider TinyInt as Boolean  ([link](https://www.javatpoint.com/mysql-boolean#:~:text=MySQL%20does%20not%20contain%20built,to%200%20and%201%20value))

It appears that in the library is a feature to do

TinyInt(1) --> Boolean
TinyInt --> sbyte 

The problem is that mysql-warning-1681-integer-display-width-is-deprecated
Is starting to be a problem. Because some applications (like workbench) sees TinyInt and TinyInt(1) as the same.
If by "mistake" you create a column using TinyInt and then you try to change to TinyInt(1) the workbench don't changed
because is deprecated (Are the same)
**To solve this issue** you have to drop-create again the table using TinyInt(1)

https://dev.mysql.com/doc/refman/8.0/en/integer-types.html
https://stackoverflow.com/questions/58938358/mysql-warning-1681-integer-display-width-is-deprecated

I see that because of backwards compatibility is difficult to decide for
TinyInt(1) --> Boolean
TinyInt(N) --> Boolean
TinyInt --> Boolean

But seems the correct step (as **default**) because of mysql-warning-1681-integer-display-width-is-deprecated

In the past I used BIT(1) to use as Boolean in my previous C#/Java applications with MySQL (the libraries use this feature)

Maybe consider in the future **also as default**

BIT(1) --> Boolean

### Further technical details

MySQL version: 8.0.22
Operating system: windows 10 Pro
Pomelo.EntityFrameworkCore.MySql version: 5.0.0-alpha.2
Microsoft.AspNetCore.App version: .NET 5.0 (run application), the model/context in .NET standard 2.1

**Comment by mguinness** [comment]
See discussion starting at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/811#issuecomment-549179788 regarding display width.

**Comment by ruirodrigues1971** [comment]
you are right... 
The standard is the MySQL connector... And the library is following.
