### ISSUE TITLE
Please bring REGEXP functions to DbFunctions

### ISSUE THREAD

**Issue by mc0re** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1338]
`LIKE` is not sufficient for some search scenarios, so a `REGEXP` function(s) would be nice to have.

**Comment by mguinness** [comment]
See [Regex.IsMatch](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/wiki/Translations#string-functions) translation.

**Comment by mc0re** [comment]
Ah, great, thanks!
