### ISSUE TITLE
Using JsonObject to write to a MySQL JSON field without using a template class

### ISSUE THREAD

**Issue by RaviDesai** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#134]
### Steps to reproduce
None, really, just a question.

### The issue
I would really like to just store a JSON blob in a JsonObject field.  With the following code (defining a class Def, and using that as the template parameter to the JsonObject) I can store items of type Def to my Definition field.  It works great.  But if I remove the <Def> class below, and just try to use a straight up JsonObject, it doesn't work - entity framework complains about not knowing what a JsonObject is.   I have a lot of different possible JSON blobs I want to store in the Definition field below.  How can I use JsonObject without a template class?

```
public class Def
{
        public string test { get; set; }
}

public class ContentItem
{
    [Key]
    public Guid Id { get; set; }

    public string Name { get; set; }
    public string Type { get; set; }

    public JsonObject<Def> Definition { get; set; }

    [NotMapped]
    public string Def { get { return Definition.Json; } set { Definition = new JsonObject<Def>(value); }}
}
```

### Further technical details

MySQL version: 5.17.15
Operating system: macOS Sierra 10.12.1
Pomelo.EntityFrameworkCore.MySql version: 1.0.0

Other details about my project setup:

**Comment by Kagamine** [comment]
JsonObj accepts class type argument only. Does not support string.
