### ISSUE TITLE
Is it safe to use version 5.0.0-alpha.2 for new projects?

### ISSUE THREAD

**Issue by Josrph** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1341]
am starting a new project of mine and i need to use Many-to-Many relationship which exists only in EF Core 5.0 . 

so is it safe to use **Pomelo.EntityFrameworkCore.MySql 5.0.0-alpha.2** for new projects???

**Comment by Zwergenpunk** [comment]
We use in production (upgraded from 3 to 5) for nearly half a year, and had no problems.

There are probably some features missing which exists in 5.0.0 but for me it was not relevant.

**Comment by Gun-Killer** [comment]
using ,had no problems

**Comment by lauxjpn** [comment]
The releases are stable, though I recommend using the latest [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds), as there are a couple of bugfixes in there.

**Comment by mguinness** [comment]
Maybe we should change the nomenclature to either beta or [release candidate](https://en.wikipedia.org/wiki/Software_release_life_cycle#Release_candidate) for the next NuGet package?

**Comment by lauxjpn** [comment]
I think making the upcoming release a beta is fine. The one after that can either be an RC or the GA release, depending on how well the beta release worked.

**Comment by Josrph** [comment]
When do we expect an official release of version 5.0!? Is it soon or there is more work to do?

**Comment by lauxjpn** [comment]
> When do we expect an official release of version 5.0!? Is it soon or there is more work to do?

I just updated #1088 about 30 minutes ago :)

**Comment by patil-vaibhav** [comment]
> Specified key was too long; max key length is 767 bytes

Had to manually change 256 to 128 to work. Is there any way around this ?

`services.AddDbContext<ApplicationDbContext>(options =>
                options.UseMySql(Configuration.GetConnectionString("DefaultConnection"),
                    new MariaDbServerVersion(new Version(10, 1, 44)),
                   mySqlOptions => mySqlOptions
                            .CharSetBehavior(CharSetBehavior.NeverAppend)));`

MariaDB 10.1.44
utf8mb4_unicode_ci

**Comment by mguinness** [comment]
@patil-vaibhav Your problem is unrelated to this issue, try https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1347 instead.
