### ISSUE TITLE
Method 'Create' does not have an implementation

### ISSUE THREAD

**Issue by gongzhx1998** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1345]
`Method 'Create' in type 'Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlSqlTranslatingExpressionVisitorFactory' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=3.2.4.0, Culture=neutral, PublicKeyToken=2cc498582444921b' does not have an implementation.`

### Further technical details

Operating system: linux
Pomelo.EntityFrameworkCore.MySql version: 3.2.4
Microsoft.AspNetCore.App version: 5.0

**Comment by mguinness** [comment]
Closing as duplicate, see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1138#issuecomment-670049509.
