### ISSUE TITLE
Each time blank constructor after DBFirst - scaffold crash the flow

### ISSUE THREAD

**Issue by kingsanu-production** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1351]
I want to know why this blank constructor made each time i scaffold from dbfirst. Please give me sollution

![image](https://user-images.githubusercontent.com/65809324/111627766-6e3b4180-8815-11eb-9e50-6b4ccd9ca0a1.png)
Note i'm using DBFirst approach & AddDBPool.

**Comment by mguinness** [comment]
There's really not enough information to help you.  One possibility is that your tables don't have any primary keys.

Closing issue for now, but will reopen once you provide additional details requested from the new issues template.

**Comment by lauxjpn** [comment]
@kingsanu-production This is just default behavior of EF Core.

The default constructor (without parameters) might be useful, if you configure your `DbContext` by overriding `OnConfiguring()`. In that case, there is no need to specify any options from outside of the class.

If the empty default constructor would be missing, the following statement would not compile:

```c#
var context = new Context();
```

The reason this would not work is, that the class explicitly implements a constructor, but not one without any arguments. In this case, no default constructor is created for the class.

If no explicit constructor would be specified at all in the code, then the compiler would generate an implicit default constructor, event though is has not been defined in the code.
