### ISSUE TITLE
issue with scaffolding tables without including Foreign tables

### ISSUE THREAD

**Issue by Fadi-MAMB** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1352]
Hi .. i was trying to scaffold-dbcontext 

first i added a simple table (no relations with other tables and no constraints ) and everything worked fine .. but when i tried the same with another table that has foreign key constraints with many tables but those tables  were not included in the proces i got an error 

the solution was to include all my DB tables (which is not logic here and makes the project size bigger)

Further technical details

Database engine: MySQL

Visual Studio version: Visual Studio 2019 16.9.2

.Net Core Version : .Net 5

Microsoft.EntityFrameworkCore Version="5.0.4"
Microsoft.EntityFrameworkCore.SqlServer Version="5.0.4"
Microsoft.EntityFrameworkCore.SqlServer.Design Version="1.1.6"
Microsoft.EntityFrameworkCore.Tools Version="5.0.4"

Pomelo.EntityFrameworkCore.MySql Version "5.0.0-alpha.2"

**Comment by mguinness** [comment]
> i got an error

What was the exception?  Please include stack trace as requested in the new issue template.

If the referenced table is not included in the scaffold then you should get a warning instead.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/e2cd0e97ec9d5bca02dfef4d645eaa780c3fb96e/src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs#L673

Also a little confused why you have references to `Microsoft.EntityFrameworkCore.SqlServer`.

**Comment by mguinness** [comment]
Thank you for investigating and finding the solution.  If you can create a PR that will be included in the [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) after merging.

**Comment by V1nzi** [comment]
Created pull request #1364
