### ISSUE TITLE
Odata queries generated use the LOCATE SQL Function

### ISSUE THREAD

**Issue by wayneforrest** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1353]
My **OData** queries being generated use the *LOCATE* SQL Function, which run slower
than when using *LIKE*. e.g. see https://jira.mariadb.org/browse/MDEV-25196

Can this be improved by not using "LOCATE" when Indexes are available and use "LIKE"?
Would PostgreSQL or Microsoft SQL perform any better?

**Comment by mguinness** [comment]
Are you using [EF.Functions.Like()](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-entity-framework-core-2-0/#like-query-operator) when you have an index?

**Comment by wayneforrest** [comment]
I had a closer look but still not clear what precisely is being executed... Odata doing it's magic...

What I do see is the `queryOptions` received is similar to this:

`// queryOptions.Filter.RawValue = "(contains(tolower(UserEmail),'joe')) or (contains(tolower(Status),'joe')) or ....`

`// and the SQL = WHERE ((((((LOCATE('joe', LOWER(`e`.`UserEmail`)) > 0) OR (LOCATE('joe', LOWER(`e`.`Status`)) > 0)) OR`


 ```
       [Route("api/QryModel")]
        public PageResult<MoModel> ListOData([FromQuery]ODataQueryOptions queryOptions)
        {
            var result = queryOptions.ApplyTo(dataContext.QryModel) as IEnumerable<MyModel>;
            var pageResult = new PageResult< MyModel >(
                result,
                null,
                count: Request.ODataFeature().TotalCount);

            return pageResult;
     }
```

**Comment by mguinness** [comment]
Oh so the query is being generated in a library?  If that's the case you'll need to open an issue in the [OData Web API](https://github.com/OData/WebApi) repo and request them to use `EF.Functions.Like()` instead of `Contains()`.

**Comment by wayneforrest** [comment]
Thanks #mguinness.

**Comment by lauxjpn** [comment]
@wayneforrest As far as I can see, this query should be translated by Pomelo to a `LIKE` statement, because the pattern `joe` is constant. We only use `LOCATE()`, if the pattern is not a constant string (e.g. if it uses a column or so).

If you provide us with a small project to replicate the behavior, we can reopen this issue and I will investigate it further.
