### ISSUE TITLE
OrderBy relevance at EF.Functions.Match? 

### ISSUE THREAD

**Issue by ilsubyeega** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1356]
Seems that ordering by relevance does not exist at pomelo's MySQL.
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/29dcac9398249c4bb3510423db294d4e927f966f/test/EFCore.MySql.FunctionalTests/Query/MatchQueryMySqlTest.cs 
(the test code, latest commit before creating this issue) hasn't mentioned the order by one.

I think this feature isn't implemented yet.

### Tried Via _(Match was boolean typed so it wont work i think)_
```cs
q = q.OrderBy(a => EF.Functions.Match( new[] { a.Table1, a.Table2 }. fulltextquery, MySqlMatchSearchMode.Boolean));
```

### Further technical details

MySQL version: MariaDB 10.5.8
Operating system: Windows 10 (x64)
Pomelo.EntityFrameworkCore.MySql version: nightly 5.0.0-alpha.3.ci.20210223004403
Microsoft.AspNetCore.App version: 5.0.0

Other details about my project setup: its web api project made by own / [repo](https://github.com/ilsubyeega/Sakamoto)

**Comment by mguinness** [comment]
@neonVoice As you added support for `MATCH` in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1056 can you offer any insight?

**Comment by neonVoice** [comment]
> 
> 
> @neonVoice As you added support for `MATCH` in #1056 can you offer any insight?

At the time I was implementing it, **OrderBy** wasn't taken into account, so it's probably not implemented. Later it was extended by @lauxjpn — maybe he knows more.

**Comment by lauxjpn** [comment]
@ilsubyeega What is the SQL equivalent of the LINQ expression you are looking for?

**Comment by ilsubyeega** [comment]
> @ilsubyeega What is the SQL equivalent of the LINQ expression you are looking for? The expression in the OP looks a bit weird.

I'm looking for this example, [url](https://stackoverflow.com/a/13494588) is here.

**Comment by lauxjpn** [comment]
@ilsubyeega The following sample program works fine for me:

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int IceCreamId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; } 
    }

    public class Context : DbContext
    {
        public virtual DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                const string connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1356";
                var serverVersion = ServerVersion.AutoDetect(connectionString);
                
                optionsBuilder.UseMySql(
                        connectionString,
                        serverVersion,
                        options => options
                            .CharSetBehavior(CharSetBehavior.NeverAppend)) 
                    .UseLoggerFactory(
                        LoggerFactory.Create(
                            configure => configure
                                .AddConsole()
                                .AddFilter(level => level >= LogLevel.Information)))
                    .EnableSensitiveDataLogging()
                    .EnableDetailedErrors();
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream>(
                entity =>
                {
                    entity.HasIndex(e => e.Description)
                        .IsFullText();
                    
                    entity.HasData(
                        new IceCream
                        {
                            IceCreamId = 1,
                            Name = "Vanilla",
                            Description = "Smooth and creamy vanilla ice cream."
                        },
                        new IceCream
                        {
                            IceCreamId = 2,
                            Name = "Chocolate & Cream",
                            Description = "With nougat and cream."
                        },
                        new IceCream
                        {
                            IceCreamId = 3,
                            Name = "Matcha",
                            Description = "Green tee blend from Hoshino."
                        });
                });
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var matches = context.IceCreams
                .Where(i => EF.Functions.Match(i.Description, "+cream", MySqlMatchSearchMode.Boolean))
                .OrderBy(i => EF.Functions.Match(i.Description, "+cream", MySqlMatchSearchMode.Boolean))
                .ToList();
            
            Trace.Assert(matches.Count == 2);
            Trace.Assert(matches[0].IceCreamId == 1);
            Trace.Assert(matches[1].IceCreamId == 2);
        }
    }
}
```

</details>

**Comment by ilsubyeega** [comment]
> @ilsubyeega The following sample program works fine for me:
> 
> <details>
> <summary>Program.cs</summary>
> 
> ```c#
> using System;
> using System.Diagnostics;
> using System.Linq;
> using Microsoft.EntityFrameworkCore;
> using Microsoft.Extensions.Logging;
> using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
> 
> namespace IssueConsoleTemplate
> {
>     public class IceCream
>     {
>         public int IceCreamId { get; set; }
>         public string Name { get; set; }
>         public string Description { get; set; } 
>     }
> 
>     public class Context : DbContext
>     {
>         public virtual DbSet<IceCream> IceCreams { get; set; }
> 
>         protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
>         {
>             if (!optionsBuilder.IsConfigured)
>             {
>                 const string connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1356";
>                 var serverVersion = ServerVersion.AutoDetect(connectionString);
>                 
>                 optionsBuilder.UseMySql(
>                         connectionString,
>                         serverVersion,
>                         options => options
>                             .CharSetBehavior(CharSetBehavior.NeverAppend)) 
>                     .UseLoggerFactory(
>                         LoggerFactory.Create(
>                             configure => configure
>                                 .AddConsole()
>                                 .AddFilter(level => level >= LogLevel.Information)))
>                     .EnableSensitiveDataLogging()
>                     .EnableDetailedErrors();
>             }
>         }
> 
>         protected override void OnModelCreating(ModelBuilder modelBuilder)
>         {
>             modelBuilder.Entity<IceCream>(
>                 entity =>
>                 {
>                     entity.HasIndex(e => e.Description)
>                         .IsFullText();
>                     
>                     entity.HasData(
>                         new IceCream
>                         {
>                             IceCreamId = 1,
>                             Name = "Vanilla",
>                             Description = "Smooth and creamy vanilla ice cream."
>                         },
>                         new IceCream
>                         {
>                             IceCreamId = 2,
>                             Name = "Chocolate & Cream",
>                             Description = "With nougat and cream."
>                         },
>                         new IceCream
>                         {
>                             IceCreamId = 3,
>                             Name = "Matcha",
>                             Description = "Green tee blend from Hoshino."
>                         });
>                 });
>         }
>     }
> 
>     internal static class Program
>     {
>         private static void Main()
>         {
>             using var context = new Context();
> 
>             context.Database.EnsureDeleted();
>             context.Database.EnsureCreated();
> 
>             var matches = context.IceCreams
>                 .Where(i => EF.Functions.Match(i.Description, "+cream", MySqlMatchSearchMode.Boolean))
>                 .OrderBy(i => EF.Functions.Match(i.Description, "+cream", MySqlMatchSearchMode.Boolean))
>                 .ToList();
>             
>             Trace.Assert(matches.Count == 2);
>             Trace.Assert(matches[0].IceCreamId == 1);
>             Trace.Assert(matches[1].IceCreamId == 2);
>         }
>     }
> }
> ```
> 
> </details>

i will re-try it when i got home, thanks for investigation

**Comment by ilsubyeega** [comment]
> @ilsubyeega The following sample program works fine for me:
> 
> Program.cs

Hello, I just found that I misunderstand* the pattern (Fulltext querying pattern) at Match. Thank you again for writing the code and using time on it as must have been useful for me
