### ISSUE TITLE
Please publish a tag with MySqlConnector 1.1.0，Thank you

### ISSUE THREAD

**Issue by woshilangdanger** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1357]
i got a problem with this lab, so i need a lab on using  MySqlConnector 1.1.0

**Comment by mguinness** [comment]
Dependencies for [Pomelo.EntityFrameworkCore.MySql](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql) in NuGet:

Version 3.2.4 requires MySqlConnector (>= 0.69.9 && < 1.0.0)
Version 5.0.0-alpha.2 requires MySqlConnector (>= 1.1.0)



Closing issue as the version information from new issue template was not provided.
