### ISSUE TITLE
idempotent script generated with `POMELO_BEFORE_DROP_PRIMARY_KEY` and `POMELO_AFTER_ADD_PRIMARY_KEY` store procedures missing delimiter calls

### ISSUE THREAD

**Issue by Sean-LM** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1359]
### Steps to reproduce
I re-named a table from `EmailTemplate` to `EmailTemplates` andgenerated sql from the command:

`dotnet ef migrations script -o data/migrations/snapshot.sql --idempotent`

### The issue
The sql includes the two mentioned procedures at the top of the script:
`POMELO_BEFORE_DROP_PRIMARY_KEY` and `POMELO_AFTER_ADD_PRIMARY_KEY`

However, the script will not run, because these two procedures are missing the wrapping `DELIMITER //` and `END //`.

When I add the top `DELIMITER //` and update the `END;` to `END //`, it works fine.

### Further technical details

MySQL version: 5.7.21

Operating system: windows 10
Pomelo.EntityFrameworkCore.MySql version: 5.0.0-alpha.2

**Comment by lauxjpn** [comment]
@Sean-LM Please try the latest [nighty build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) and see if it works for you.
We did change the code responsible for those procedures in #1282 a couple of months ago.

**Comment by lauxjpn** [comment]
> Please try the latest [nighty build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) and see if it works for you.
> We did change the code responsible for those procedures in #1282 a couple of months ago.

@Sean-LM Does recent nightly builds or `5.0.0-beta.1` work for you in that regard?
