### ISSUE TITLE
Query Builder using LAST_INSERT_ID() on tables where key is Guid

### ISSUE THREAD

**Issue by VictorCodesseira** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1360]
### Steps to reproduce
**SQL table**
Basic structure, there are more fields but they don't interfere

```sql
CREATE TABLE `test_student` (
  `id` char(36) NOT NULL DEFAULT (uuid()),
  `created_at` datetime(6) NOT NULL DEFAULT (now(3)),
  `updated_at` datetime(6) NOT NULL DEFAULT (now(3)),
  `test_id` char(36) NOT NULL,
  `student_id` char(36) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `test_student_student_id` (`student_id`),
  KEY `test_student_test_id` (`test_id`),
  CONSTRAINT `fk_student_id_test_student` FOREIGN KEY (`student_id`) REFERENCES `Aluno` (`id`),
  CONSTRAINT `test_student_test_id_fk` FOREIGN KEY (`test_id`) REFERENCES `test` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

**Scaffolding command**
```shell
dotnet ef dbcontext scaffold --no-onconfiguring \
 "Server=****;Database=data;Uid=****;Pwd=****;" \
	Pomelo.EntityFrameworkCore.MySql \
	-o Models -c "DbContext" -d -f -v
```

**DbContext.cs**
```c#
modelBuilder.Entity<TestStudent>(entity =>
{
    entity.Property(e => e.Id)
        .HasDefaultValueSql("'uuid()'")
        .HasCharSet("utf8mb4")
        .HasCollation("utf8mb4_0900_ai_ci");

    entity.Property(e => e.CreatedAt).HasDefaultValueSql("'now(3)'");

    entity.Property(e => e.StudentId)
        .HasCharSet("utf8mb4")
        .HasCollation("utf8mb4_0900_ai_ci");

    entity.Property(e => e.TestId)
        .HasCharSet("utf8mb4")
        .HasCollation("utf8mb4_0900_ai_ci");

    entity.Property(e => e.UpdatedAt).HasDefaultValueSql("'now(3)'");

    entity.HasOne(d => d.Student)
        .WithMany(p => p.TestStudents)
        .HasPrincipalKey(p => p.Id)
        .HasForeignKey(d => d.StudentId)
        .OnDelete(DeleteBehavior.ClientSetNull)
        .HasConstraintName("fk_student_id_test_student");

    entity.HasOne(d => d.Test)
        .WithMany(p => p.TestStudents)
        .HasForeignKey(d => d.TestId)
        .OnDelete(DeleteBehavior.ClientSetNull)
        .HasConstraintName("test_student_test_id_fk");
});
```

**Model**
```c#
[Table("test_student")]
[Index(nameof(StudentId), Name = "test_student_student_id")]
[Index(nameof(TestId), Name = "test_student_test_id")]
public partial class TestStudent
{
    public TestStudent()
    {
    }

    [Key]
    [Column("id")]
    public Guid Id { get; set; }
    [Column("created_at")]
    [MaxLength(6)]
    public DateTime CreatedAt { get; set; }
    [Column("updated_at")]
    [MaxLength(6)]
    public DateTime UpdatedAt { get; set; }
    [Column("test_id")]
    public Guid TestId { get; set; }
    [Column("student_id")]
    public Guid StudentId { get; set; }
   
    public virtual Aluno Student { get; set; }
    [ForeignKey(nameof(TestId))]
    [InverseProperty("TestStudents")]
    public virtual Test Test { get; set; }
}
```

### The issue
```c#
var newTestStudent = new TestStudent
{
    Test = test,
    Student = student,
};

Db.TestStudents.Add(newTestStudent);
Db.SaveChanges();
```

Whenever I insert a new value on this table, using Add(), and then execute SaveChanges(), the values that should be updated by Db generated values (CreatedAt, UpdatedAt and Id) are wrong. I've done some digging, and found that the generated SQL in this case is

```sql
INSERT INTO `test_student` (`student_id`, `test_id`)                                                    
VALUES (@p0, @p1);                                            
SELECT `id`, `created_at`, `updated_at`                                                                         
FROM `test_student`                                                                                                     
WHERE ROW_COUNT() = 1 AND `id` = LAST_INSERT_ID();    
```

So, the problem is that, to find the inserted row, the SQL is using `LAST_INSERT_ID()`, which returns an int. In this case, the int is always 0, so the select always returns the first row in the table in which the `id` starts with 0 (the uuid is truncated). I have found a workaround, that is explicitly setting the id, like so
```c#
var newTestStudent = new TestStudent
{
    Id = new Guid(),
    Test = test,
    Student = student,
};
```

However, this system is reasonably large, and theses problems appeared after a migration from SQL Server to MySql. So it would be really nice to have a lower level fix, so that we wouldn't miss any of the instances where this bug is happening. 
Also, it clearly is a bug, since it is inserting data from a different row into the inserted entity.

So I would like any help you can provide in fixing this, either by a bugfix or a workaround I can implement myself into the query builder. Thank you.

### Further technical details
MySQL version: 8.0.21
Operating system: Win10x64
Pomelo.EntityFrameworkCore.MySql version: 5.0.0-alpha2
Microsoft.AspNetCore.App version:  3.1

**Comment by lauxjpn** [comment]
@VictorCodesseira Using the latest [nightly build](TODO), I do not get the `LAST_INSERT_ID()` part generated anymore. However, that generated statement looks now similar to the following, which will not work as well:

```sql
SELECT `id`, `created_at`, `updated_at`                                                                         
FROM `test_student`                                                                                                     
WHERE ROW_COUNT() = 1;
```

Your code cannot work, because there is no way for EF Core (or Pomelo) to read-back the just inserted value. The reason is, that the primary key is generated by the server via `DEFAULT (uuid())`, and there is no equivalent to `LAST_INSERT_ID()` for Guids, so EF Core (or Pomelo) cannot find out, what Guid was generated by MySQL for your new row.

The solution is simple: Because Guids are globally unique, you can just generate one client-side, and supply the value to the server with your `INSERT` statement. Pomelo already contains an index optimized `Guid` generator, that it will use if you let it. All you need to do, is to remove the `.HasDefaultValueSql("'uuid()'")` line.

This will work by convention, because you named your PK property `Id`, which EF Core recognizes as a primary key. And for primary keys that are of type `Guid`, Pomelo uses its `Guid` generator.

You can also instruct Pomelo to use the `Guid` generator explicitly, by adding a `.ValueGeneratedOnAdd()` call to your PK property.

The following to model definition will work:

```sql
entity.Property(e => e.Id)
    // .HasDefaultValueSql("'uuid()'") <-- this does not work
    // .ValueGeneratedOnAdd() <-- optional, but not necessary in your case
    .HasCharSet("utf8mb4")
    .HasCollation("utf8mb4_0900_ai_ci");
```

**Comment by VictorCodesseira** [comment]
Yeah, the workaround we found was explicitly creating Ids everywhere we save changes. I didn't want to change the model definition because it is part of an older system, in which we use a DB-First approach. So changing model definitions would mean we would need to remember overwriting it everytime we scaffolded the db.

I imagined I couldn't solve it with the library, because of limitations from MySql, that are not present in SQLServer. But I still think the current behavior is not ideal, and should error out(or at least warn) on model definition, or maybe on query execution. As it is, it took quite a bit of debugging to realize what was happening, and worse, it left a few "scars" on the database because of the SaveChanges putting a seemingly "random" value in this Id. So, in places where we saved an entity, and then used it's Id as a foreign key in another table, we ended up associating the wrong objects. Luckily, it was nothing too bad, but I would rather it error out on query execution than risk potential data corruption.

Anyway, thanks for the help you gave me with this!

**Comment by lauxjpn** [comment]
Warning users when scaffolding a default value that contains a `uuid()` call, sounds like a good idea.

As for altering the model without changing the definition, you can just run some code e.g. in `DbContext.OnConfiguring()` (e.g. triggered by some kind of flag, or by overriding the method in a derived class) after the regular model definition has been set, and alter it like you want/need to:

```c#
public class LegacyContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<IceCream>(
            entity =>
            {
                entity.Property(e => e.IceCreamId)
                    .HasDefaultValueSql("'uuid()'")
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                // ...
            });
        
        // ...
    }
}

public class ModernContext : LegacyContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        var uuidProperties = modelBuilder.Model
            .GetEntityTypes()
            .SelectMany(e => e.GetProperties())
            .Where(
                p => p.GetDefaultValueSql()
                        ?.Contains("uuid()", StringComparison.OrdinalIgnoreCase) ?? false);

        foreach (var uuidProperty in uuidProperties)
        {
            uuidProperty.SetDefaultValueSql(null);
            uuidProperty.ValueGenerated = ValueGenerated.OnAdd;
        }
    }
}
```

**Comment by VictorCodesseira** [comment]
I thought about extending the DbContext Class, which would not work, bit didn't think of inheriting it. That should work perfectly, thank you again!
