### ISSUE TITLE
Support the new BCL DateOnly and TimeOnly structs

### ISSUE THREAD

**Issue by roji** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1361]
New DateOnly and TimeOnly structs are being introduced to .NET 6 as alternatives to DateTime (https://github.com/dotnet/runtime/issues/49036). MySqlConnector issue: https://github.com/mysql-net/MySqlConnector/issues/963.

**Comment by mattjohnsonpint** [comment]
Please note that the final names for these types are `DateOnly` and `TimeOnly` and that they are now merged into the main branch for the next version of .NET 6 (preview 4 likely).  Please rename the title of this issue accordingly.  Thanks.

**Comment by lauxjpn** [comment]
They are [coming](https://github.com/dotnet/core/issues/6098#issuecomment-840815510) in .NET 6 Preview 4.

**Comment by roji** [comment]
@lauxjpn yes.

Note that it may be a good idea to hold off here (and in Npgsql) until support is added in EF Core itself (https://github.com/dotnet/efcore/issues/24506, https://github.com/dotnet/efcore/issues/24507), this way the specification tests will already be added upstream. I hope to make that happen pretty quickly after the preview4 release.

**Comment by uzairali001** [comment]
Any news?

**Comment by roji** [comment]
FYI support in EF Core has been added for Sqlite, including functional tests.

**Comment by lauxjpn** [comment]
> Any news?

We will implement it in the near future.

**Comment by BrokenShoeLace** [comment]
Using EF 6.05 and the same error as @uzairali001 on VS2022 for Microsoft SQL 2019

**Comment by mguinness** [comment]
@BrokenShoeLace If you're using MS SQL then please look at https://github.com/dotnet/efcore/issues/24507.

**Comment by BrokenShoeLace** [comment]
Thanks for the link but ut doesnt address my issue:

TimeOnly is not DateOnly

**Comment by lauxjpn** [comment]
@BrokenShoeLace Please clarify: Are you using `Pomelo.EntityFrameworkCore.MySql` or `Microsoft.EntityFrameworkCore.SqlServer`?

**Comment by BrokenShoeLace** [comment]
Microsoft.EntityFrameworkCore.SqlServer
