### ISSUE TITLE
Feature request: FULLTEXT using ngram parser

### ISSUE THREAD

**Issue by ahnseunghae** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1367]
While FULLTEXT Index is supported now, [Full-Text Parser](https://dev.mysql.com/doc/refman/8.0/en/fulltext-search-ngram.html) is also required to search text in Chinese, Japanese, and Korean. Is it possible to add the feature to create FULLTEXT Index with `WITH PARSER ngram`

**Comment by lauxjpn** [comment]
@ahnseunghae I've got the code ready, except the scaffolding part. Can you research, how we can find-out, if a full-text index has a parser set? We normally use the `information_schema` tables (for indexes the `information_schema.statistics` table).

**Comment by ahnseunghae** [comment]
@lauxjpn 
I coube be wrong, but as far as I researched, `SHOW CREATE TABLE` statement is the only way.
As you can see [here](https://github.com/mysql/mysql-server/blob/f8cdce86448a211511e8a039c62580ae16cb96f5/mysql-test/suite/innodb_fts/r/ngram_2.result#L38), I think MySQL itself also using `SHOW CREATE TABLE` statement to testing `WITH PARSER`statement.

**Comment by lauxjpn** [comment]
@ahnseunghae Thanks, we will use it then until a better way opens up.
