### ISSUE TITLE
Scaffold mysql boolean to sbyte?

### ISSUE THREAD

**Issue by joevchs** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#137]
### Steps to reproduce
After runnning the scaffold command, the boolean type column was defined as sbyte instead of boolean on the entity model.

### The issue
The result is:
public **sbyte** tableColumn { get; set; }

### Further technical details

MySQL version: 5.7.12
Operating system: Windows 7
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Pomelo.EntityFrameworkCore.MySql": "1.1.0",
    "Pomelo.EntityFrameworkCore.MySql.Design": "1.1.0"

**Comment by mguinness** [comment]
Please provide your table schema and confirm you're using bit datatype and not tinyint.

**Comment by Kagamine** [comment]
@joevchs We will not treat DB type tinyint(1) to CLR type bool, because not all tinyint(1) are boolean. You can modify the field type after scaffolding manually.

**Comment by joevchs** [comment]
Using bit(1) works as expected. Thanks!!
