### ISSUE TITLE
Unknown column 'X' in 'field list'

### ISSUE THREAD

**Issue by amyndhupelia** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1375]
### Steps to reproduce
Setup a .net core project with
1. https://github.com/openiddict/openiddict-core 3.0 or later
2. Add Pomelo mySQL: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql  3.0.1 or later
3. Add EF Core Dependencies 3.1.*
4. connect to a mysql DB and let openiddict connect initialize the DB using Worker : IHostedService 

### The issue
When it tries to initialize i get the following error: `MySqlException: Unknown column 'o.DisplayNames' in 'field list'`

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```
![image](https://user-images.githubusercontent.com/42614908/113738609-4b85a580-96bc-11eb-8af1-d391ee1ac067.png)

### Further technical details

Pomelo.EntityFrameworkCore.MySql version: 3.0.1 or later
Microsoft.AspNetCore.App version: 3.1*

**Comment by mguinness** [comment]
Screenshots of stack traces are discouraged as they are both hard to read and also prevent searching.  Also you appear to be using an old version of Pomelo, you should be using [version 3.2.4](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/3.2.4).  

As far as I can tell `DisplayNames` is part of [OpenIddictEntityFrameworkCoreApplication](https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.EntityFrameworkCore.Models/OpenIddictEntityFrameworkCoreApplication.cs#L79) model, does that field exist in your database table?

**Comment by lauxjpn** [comment]
@amyndhupelia This is very likely just a configuration/setup issue with the technologies you are using. If you want us to look into it any, please provide us with a project/solution, that reproduces the issue, so we can just run it and get the same error.

**Comment by amyndhupelia** [comment]
Thanks you. You are right, there was a issue on my side. I made it work on SQL Server and then changed to mySQL and it worked fine. Sorry about it. Please delete the issue , as its irrelevant.
