### ISSUE TITLE
Just a question How can I use Migration using DBFirst 

### ISSUE THREAD

**Issue by stherrienaspnet** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1379]
### Steps to reproduce
I'm using your version 5 alpha 2 and EntityFramework 5.0.5 and I can access my MariaDB database. As soon I add [EntityFrameworkCore.Tools 5.0.5](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Tools/5.0.5) I'm getting error and cannot access the database anymore. I try to migrate my changes that is why I would like to use EntityFrameworkCore.Tools.

### The issue
`System.AggregateException: 'One or more errors occurred. (Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.)'`

Any help will be really appreciated

**Comment by stherrienaspnet** [comment]
I have downgraded both EntityFrameworkCore version to 5.0.0 and it is working

**Comment by mguinness** [comment]
Mixing versions from different releases are not supported and may not always work.

**Comment by lauxjpn** [comment]
@stherrienaspnet Pomelo 5.x should work with any EF Core 5.0.y version. Please paste the package references from your `.csproj` file, so we can take a look at it. Also make sure, that the `Microsoft.EntityFrameworkCore.Relational` in version `5.0.5` is indeed in your output directory, when you are using the EF Core tools.

**Comment by stherrienaspnet** [comment]
I will do it since now I exchanged package Pomelo for MySQL package. Now it
is working but would prefer use your package.

**Comment by stherrienaspnet** [comment]
Here is the content of my Inspect360.EntityFramework.csproj

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="5.0.0-alpha.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inspect360.Domain\Inspect360.Domain.csproj" />
  </ItemGroup>

</Project>

I have a login form in my application and it is hanging forever as show below.  Same code by with Mysql package from Oracle is working without any issue.

        private void btnLogin_Click(object sender, EventArgs e)
        {
            try {
                if (!ValidateChildren(ValidationConstraints.Enabled)) return;
                var userService = new GenericDataService<User>(new EntityFramework.Inspect360DbContextFactory());
                var user = userService.GetAll().Result.FirstOrDefault(x => x.Email == txtEmail.Text); (CAN TAKE FOREVER HERE...)
                if (user != null){

                }

Best regards,
Stephane

**Comment by stherrienaspnet** [comment]
Microsoft.EntityFrameworkCore.Relational.dll is not present into my Inspect360.EntityFramework.csproj bin/debug directory
Do I need to install also Microsoft.EntityFrameworkCore.Relational package?

**Comment by stherrienaspnet** [comment]
I would like to make one clarification. When I said that when I downgraded it worked, it was not true, one warning disappear but I was not event able to login into my application.

**Comment by lauxjpn** [comment]
> Microsoft.EntityFrameworkCore.Relational.dll is not present into my Inspect360.EntityFramework.csproj bin/debug directory
Do I need to install also Microsoft.EntityFrameworkCore.Relational package?

Yes, take a look at the `Dependencies` section on nuget.org for [Pomelo.EntityFrameworkCore.MySql](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/5.0.0-alpha.2):

> .NETStandard 2.1
> ---
> **Microsoft.EntityFrameworkCore.Relational (>= 5.0.0)**
> MySqlConnector (>= 1.1.0)

Now take a look at the [Microsoft.EntityFrameworkCore](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/5.0.5) package, to see whether it references `Microsoft.EntityFrameworkCore.Relational` or not:

> .NETStandard 2.1
> ---
> Microsoft.EntityFrameworkCore.Abstractions (>= 5.0.5)
> Microsoft.EntityFrameworkCore.Analyzers (>= 5.0.5)
> Microsoft.Extensions.Caching.Memory (>= 5.0.0)
> Microsoft.Extensions.DependencyInjection (>= 5.0.1)
> Microsoft.Extensions.Logging (>= 5.0.0)
> System.Collections.Immutable (>= 5.0.0)
> System.ComponentModel.Annotations (>= 5.0.0)
> System.Diagnostics.DiagnosticSource (>= 5.0.1)

As you can see, it doesn't.

So, if you don't want to use the EF Core version that is being referenced by Pomelo, but instead want to use a newer one (which is perfectly fine), you need to explicitly reference all the required EF Core package versions to ensure they are all of the same version.

That means, if you are referencing `Microsoft.EntityFrameworkCore` and `Microsoft.EntityFrameworkCore.Tools` in version `5.0.5`, you now also need to explicitly reference `Microsoft.EntityFrameworkCore.Relational` in version `5.0.5` (and also use the `dotnet-ef` tool in version `5.0.5`).

So you project file should look like this:

```xml
<PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="5.0.0-alpha.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inspect360.Domain\Inspect360.Domain.csproj" />
  </ItemGroup>

</Project>
```

**Comment by stherrienaspnet** [comment]
I just tried and same result, Hanging forever. Here is my current configuration. I could possibly send you my application so you can try it by yourself. 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="5.0.0-alpha.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inspect360.Domain\Inspect360.Domain.csproj" />
  </ItemGroup>

</Project>
```

**Comment by lauxjpn** [comment]
> I just tried and same result, Hanging forever.

The solution I provided is not about hanging/freezing, it is about the issue you described in the OP:

> `System.AggregateException: 'One or more errors occurred. (Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.)'`

---

> Here is my current configuration. I could possibly send you my application so you can try it by yourself.

If you want me to take a look at why your app freezes, please do so.

**Comment by stherrienaspnet** [comment]
Thanks for your time

**Comment by lauxjpn** [comment]
> If you want me to take a look at why your app freezes, please do so. (Preferably, put it on GitHub, either publicly or privately.)

@stherrienaspnet Do you still need help with the freezing issue, or can we close this issue?

**Comment by stherrienaspnet** [comment]
You can close it thanks
