### ISSUE TITLE
How to realize fuzzy query of full text index in MySQL?

### ISSUE THREAD

**Issue by bbhxwl** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1384]
How to realize fuzzy query of full text index in MySQL?

`select *  from DouYinVideo where match(nickname) AGAINST ('mysql');`

**Comment by mguinness** [comment]
See tests in [MatchQueryMySqlTest](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/EFCore.MySql.FunctionalTests/Query/MatchQueryMySqlTest.cs) for examples.
