### ISSUE TITLE
Scaffolder generates slightly incorrect HasCharSet() and HasCollation() calls in 5.0.0-beta.1

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1393]
When scaffolding from an existing database using `5.0.0-beta.1`, incorrect code similar to the following might be generated:

```c#
modelBuilder.HasCharSet(new object[] {"utf8mb4"})
    .UseCollation(new object[] {"utf8mb4_0900_ai_ci"});
```

However, correct would be the following instead:

```c#
modelBuilder.HasCharSet("utf8mb4")
    .UseCollation("utf8mb4_0900_ai_ci");
```

The same issue can also happen at the table level and with delegations.

**Comment by capegreg** [comment]
There is no 5.0.0-beta.2 package on nuget.org.

https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/5.0.0-beta.1

**Comment by mguinness** [comment]
Beta 2 is still a WIP, use the [nighty build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) in the interim.

**Comment by lauxjpn** [comment]
We be release any minute now.
