### ISSUE TITLE
Pomelo.EntityFrameworkCore.MySql.Infrastructure in Startup.cs

### ISSUE THREAD

**Issue by yasserss** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1417]
In the [documentation](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#3-services-configuration): 

> Add `Pomelo.EntityFrameworkCore.MySql` to the services configuration in your the `Startup.cs` file.

Why is that and why do we need it?

**Comment by mguinness** [comment]
Are you why `using Pomelo.EntityFrameworkCore.MySql.Infrastructure;` is shown instead of `using Pomelo.EntityFrameworkCore.MySql;` in the example code?

**Comment by lauxjpn** [comment]
@yasserss If use use ASP.NET Core, you need/should to register your `DbContext` derived class using `services.AddDbContextPool<YourDbContext>(/* ... */)`, so you can inject it e.g. into the constructor of your controllers.

Feel free to ask a more specific question if you like, or post some code to clarify, where you have questions or where you see issues.

**Comment by yasserss** [comment]
@lauxjpn @mguinness  alrighty thank you guys  and amazing work BTW keep it up: 👍

**Comment by lauxjpn** [comment]
> We could still keep it in there though, to help users discovering the location of the `MySqlDbContextOptionsBuilder` and its options.

I am not sure if it helps to keep it in the file. I am developing exclusively with Rider, which is very strong in discovering types and adding `using` statements. I don't know how VS and VS Code handle this case, but I guess they would add the `using` statement as well, so it might make sense to remove it from the sample code after all. We could then simplify the code by letting it just start with the `Startup` class or its `ConfigureServices` method.

**Comment by lauxjpn** [comment]
Type discovery seems to be strong enough over the board. I think we can remove the `using` statement from the readme sample code.

**Comment by lauxjpn** [comment]
I cleaned up the sample code. I also replaced the `AddDbContextPool` call with `AddDbContext`, because the former one is an optimization that should not be part of the general sample.
