### ISSUE TITLE
Exception when TreatTinyAsBoolean option is true (default)

### ISSUE THREAD

**Issue by mguinness** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#142]
When you have a table column as `tinyint(1)` (which is scaffolded as sbyte), a LINQ query that references that will fail with InvalidCastException.

### Steps to reproduce
```SQL
CREATE TABLE TestTable (
  TestColumn tinyint(1) NOT NULL
);
```

```C#
public partial class TestTable
{
    public sbyte TestColumn { get; set; }
}
```

### The issue
`var test = context.TestTable.ToList();` will generate exception message "There is already an open DataReader associated with this Connection which must be closed first".

That exception is misleading as it's an artifact of the handled exception trying to close the transaction when the reader was still open.

The underlying exception message is "Unable to Cast Object of type 'System.Boolean' to type 'System.Byte'" which is in the GetByte override in the SynchronizedMySqlDataReader class.

### Workarounds
Changing the column from tinyint(1) to tinyint(3) will mean that the ADO.NET data provider will treat this a byte instead of a boolean.

There is an open issue https://github.com/mysql-net/MySqlConnector/issues/141 for the ADO.NET data provider.  If that is implemented, then setting `TreatTinyAsBoolean=false` in the connection string should work.

### Further technical details

MySQL version: 5.6.27-log
Operating system: Linux
Pomelo.EntityFrameworkCore.MySql version: 1.1.0

**Comment by caleblloyd** [comment]
There is an open discussion in MySqlConnector at https://github.com/mysql-net/MySqlConnector/issues/141 on whether to default to `TreatTinyAsBoolean=true` or `TreatTinyAsBoolean=false`

Should we force `TreatTinyAsBoolean=false` in this library, since we store bools as `BIT(1)`?

**Comment by mguinness** [comment]
It's a hard one to call.  My gut feeling is that this library should default to `TreatTinyAsBoolean=false` and also `ConvertZeroDateTime=true` (since .NET has no zero datetime).

However, if settings are overridden from the [documented](https://dev.mysql.com/doc/connector-net/en/connector-net-connection-options.html) defaults it could get confusing for end users.

Also should we see which defaults are used in Official MySql, Sapient Guardian & DevArt?  Switching providers should be transparent ideally.

**Comment by caleblloyd** [comment]
> should we see which defaults are used in Official MySql, Sapient Guardian & DevArt

I don't think so.  We should decide what works best in this library and document differences from the official library.

**Comment by caleblloyd** [comment]
As an alternative to forcing these options, we could create a Connection String Parser and set our own defaults.  That way users have the options of switching back from our defaults if they want

**Comment by mguinness** [comment]
Connection string option `TreatTinyAsBoolean` is was implemented in https://github.com/mysql-net/MySqlConnector/issues/141 so this library can now reference latest [MySqlConnector](https://www.nuget.org/packages/MySqlConnector/0.9.0) to close this issue.

**Comment by caleblloyd** [comment]
Shipped in updated MySqlConnector with this option in [1.1.1-prerelease-10002](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.1.1-prerelease-10002)

**Comment by mguinness** [comment]
@caleblloyd Thank you, can confirm that this now works.
