### ISSUE TITLE
Confusion Around MariaDB and NetTopologySuite

### ISSUE THREAD

**Issue by amura11** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1425]
### The issue
I'm having trouble creating a `Polygon`, saving it my MariaDB database, then query the database to see if the `Polygon` contains a certain `Point`. I get a Latitude and Longitude from Google Maps then I create a `Point` and find the first entity in my database that has a `Polygon` that contains that `Point`.

This is my code:

**Polygon Creation Code**
This is the code that I use when I'm seeding my database. I feed the function an array of data I got from OSM in a GeoJson file.
```
double[,] source =  new double[,] { {longitude1, latitude1}, {longitude2, latitude2}, ... }; //Taken from a GeoJson file 
int length = source.Length / 2;
Coordinate[] coordinates = new Coordinate[length];

for (int i = 0; i < length; i++)
{
    coordinates[i] = new Coordinate(source[i, 0], source[i, 1]);
}

GeometryFactory _factory = NetTopologySuite.NtsGeometryServices.Instance.CreateGeometryFactory(4326);

return factory.CreatePolygon(coordinates);
```

**Query**
This is the code that I'm using to query my database.`latitude` and `longitude` are returned from Google Maps API.

```
GeometryFactory factory = NetTopologySuite.NtsGeometryServices.Instance.CreateGeometryFactory(4326);
Point p = factory.CreatePoint(new Coordinate(longitude, latitude));

MyEntity entity = await dbContext.Set<MyEntity>.Where(entity => entity.Polygon.Contains(p)).FirstOrDefaultAsync();
```

When I run the query with a know `latitude` and `longitude` that should be within the `Polgyon` I get a null result. After some fiddling about I decided to swap the `latitude` and `longitude` when I create the `Point` and that works. However, everything I've seen online previously said that I should be creating the `Point` using `longitude` as the first parameter and `latitude` as the second parameter.

Any help on what I'm doing wrong here would really be appreciated, I'm pretty new to all this geopositioning stuff and it's a little overwhelming.

### Further technical details

MySQL version: MariaDB 10.5.10
Operating system: Windows 10 Professional
Pomelo.EntityFrameworkCore.MySql version: 5.0.0
Microsoft.AspNetCore.App version: 3.1.10

**Comment by lauxjpn** [comment]
We recently had #1350, which is similar. Start by taking a look at it and the referenced issue in there. I will take another look at the tests.

**Comment by amura11** [comment]
@lauxjpn thanks for getting back to me so quickly.

I did come across that case and I read the linked comment of yours but to be honest I don't fully understand everything going on there. I decided to create a quick test to see if I take the database out of the question if my code (or a close approximation of it) would work as I expected and it seems like it does: [Fiddle](https://dotnetfiddle.net/R5fduM). I tried running my code again and manually swapping the latitude and longitude when I create the `Point` and that gets me the expected result.

I highly doubt it's an issue with the library, I'd put my money on me doing something stupid in the code 😅

**Comment by lauxjpn** [comment]
I am rechecking this again at the moment. Should only take a couple of minutes. MySQL has added ` ST_Longitude()` and ` ST_Latitude()` in MySQL 8, so I am currently checking, whether we pass the coordinates on to MySQL (and also MariaDB) in the correct order.

Because MySQL expects the coordinates swapped in contrast to other databases, it can become confusing if you try to populate a database manually.

**Comment by lauxjpn** [comment]
Okay, it works as expected. Got worried there for a moment, since this is the second post within two month with the same issue.

Here is same sample code to prove that everything works as expected (you it can only by run against MySQL, as MariaDB has no `ST_Longitude()` and `ST_Latitude()` functions to prove, that the coordinates are in the order the database expect them to be):

<details>
<summary>Program.cs</summary>

```c#
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NetTopologySuite;
using NetTopologySuite.Geometries;

namespace IssueConsoleTemplate
{
    public class IceCreamShop
    {
        public int IceCreamShopId { get; set; }
        public string Name { get; set; }
        public Point Location { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<IceCreamShop> IceCreamShops { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1425";
                var serverVersion = ServerVersion.AutoDetect(connectionString);
                
                optionsBuilder.UseMySql(
                        connectionString,
                        serverVersion,
                        options => options.UseNetTopologySuite())
                    .UseLoggerFactory(
                        LoggerFactory.Create(
                            configure => configure
                                .AddConsole()
                                .AddFilter(level => level >= LogLevel.Information)))
                    .EnableSensitiveDataLogging()
                    .EnableDetailedErrors();
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCreamShop>(
                entity =>
                {
                    entity.Property(e => e.Location)
                        .HasSpatialReferenceSystem(4326);
                });
        }
    }

    internal static class Program
    {
        private static void Main(string[] args)
        {
            using (var context = new Context())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var factory = NtsGeometryServices.Instance.CreateGeometryFactory(4326);

                context.Add(
                    new IceCreamShop
                    {
                        IceCreamShopId = 1,
                        Name = "Cold & Sweet",
                        
                        // Brandenburg Gate, Berlin, Germany:
                        // lon=13.3777041, lat=52.5162746; or @52.516377,13.3776013 as Google Maps outputs them in @lat,lon order)
                        Location = factory.CreatePoint(new Coordinate(/* lon */ x: 13.3777041, /* lat */ y: 52.5162746))
                    });

                context.SaveChanges();
            }

            using (var context = new Context())
            {
                // Get the entity through EF Core/Pomelo.
                var iceCreamShop = context.IceCreamShops.Single();

                //
                // Get the location data directly from MySQL:
                //
                
                context.Database.OpenConnection();

                var connection = context.Database.GetDbConnection();

                using var command = connection.CreateCommand();
                command.CommandText = @"SELECT ST_Longitude(`Location`) as Lon, ST_Latitude(`Location`) as Lat, ST_X(`Location`) as X, ST_Y(`Location`) as Y
FROM `IceCreamShops`
WHERE `IceCreamShopId` = 1";

                using var dataReader = command.ExecuteReader();
                dataReader.Read();
                        
                var lon = (double)dataReader["Lon"];
                var lat = (double)dataReader["Lat"];
                var x = (double)dataReader["X"];
                var y = (double)dataReader["Y"];

                //
                // Validate:
                //
                
                // Longitude and latitude should be exactly as specified by us. 
                Trace.Assert(lon == 13.3777041);
                Trace.Assert(lat == 52.5162746);
                        
                // X and Y coordinates should be swapped in the database, because MySQL expects X to be latitude
                // and Y to longitude for no good reason.
                Trace.Assert(x == 52.5162746);
                Trace.Assert(y == 13.3777041);
                
                // NTS uses X as longitude and Y as latitude, as anyone sane would do.
                Trace.Assert(iceCreamShop.Location.X == 13.3777041);
                Trace.Assert(iceCreamShop.Location.Y == 52.5162746);
            }
        }
    }
}
```

</details>

If you manually input/load data into your table (by not using Pomelo), make sure to use latitude as the first coordinate and longitude as the second coordinate (Google Maps order).

That is the opposite of the NTS order, which uses x as longitude and y as latitude.

**Comment by amura11** [comment]
@lauxjpn thanks for going through all that. It turns out that I'm just dense. I copied the code you wrote with some modifications to see what might be wrong. As expected your code worked flawlessly and after much more confusion and questioning my sanity I managed to figure out what happened.

When I originally wrote the code to seed the database I had the longitude and latitude reversed. I fixed that pretty quickly and updated my database. I'm using migrations and didn't think to check my `DatabaseContextModelSnapshot`, it had the original reversed data. So even though I fixed it and ran the migration I was getting the reverse data and my code didn't work. Removing the migration and creating a new one fixed the issue

**Comment by lauxjpn** [comment]
@amura11 Thanks for keeping us updated! I agree, that the whole longitude/latitude coordinate position ambiguity between different database systems, platforms like Google Maps and libraries like NTS, adds a lot of unnecessary complexity. With additional complexity like migrations, its pretty hard to get right. Glad you figured out what the issue was in your case!

**Comment by amura11** [comment]
In the event someone in the future comes across this and can't figure out their issue try dumping your data using `ST_AsGeoJson()`, for example: 

```
SELECT ST_AsGeoJson(Boundary) FROM region;
```

GeoJson seems to have a fairly strict standard so it can be useful for identifying issues with your data. In my case when I did this I noticed that the `Polygon` data was in the wrong order and that helped me narrow down my issue.

**Comment by lauxjpn** [comment]
I updated the previous comments of mine and made them accurate in terms of database versions and SRID.

PR #1433 makes this all explicit and demonstrates what construct in what coordinate order is being interpreted by MySQL and NTS in what way.
