### ISSUE TITLE
Translate "DateTime.AddHours" error and got MySqlException

### ISSUE THREAD

**Issue by Flithor** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1434]
If try to select the hour time of a date:
```
myData.Select(d => d.dateTime.Date.AddHours(d.dateTime.Hour));
```
will get this exception:
```
MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'double) AS signed) hour)
FROM `myData` AS `m`' at line 1
```

This is the translated SQL:
```
SELECT DATE_ADD(CONVERT(`m`.`dateTime`, date), INTERVAL CAST(CAST(EXTRACT(hour FROM `m`.`dateTime`) AS double) AS signed) hour)
FROM `myData` AS `m`
```
The right SQL:
```
SELECT DATE_ADD(CONVERT(`m`.`dateTime`, date), INTERVAL EXTRACT(hour FROM `m`.`dateTime`) hour) -- remove two cast
FROM `myData` AS `m`
```

There are the same bug on all of `DateTime.AddXXX` methods.
### Further technical details

MySQL version: 5.6.26
Operating system: Win 10
Pomelo.EntityFrameworkCore.MySql version: 3.2.4
Microsoft.AspNetCore.App version: 3.1.8

PS: This bug hinders my work. At present, I have not found any other way besides using raw sql query - but raw sql is not what I want.

**Comment by lauxjpn** [comment]
The issue in your case is not the castings. It is very likely that you did not specify to Pomelo, what version of MySQL you are using.
It should look like this for Pomelo 3.2.5:

```c#
var connectionString = "server=localhost;user=root;password=1234;database=ef";

optionsBuilder.UseMySql(
    connectionString
    mySqlOptions => mySqlOptions
        .ServerVersion(new Version(5, 6, 26), ServerType.MySql) // <-- your server version and type
        .CharSetBehavior(CharSetBehavior.NeverAppend))
```

If you do not specify your server version explicitly, Pomelo 3.x will assume, that you have the _latest_ version of MySQL installed (8.0.21+).

The following should work as well:

```c#
var connectionString = "server=localhost;user=root;password=1234;database=ef";
var serverVersion = ServerVersion.AutoDetect(connectionString);

optionsBuilder.UseMySql(
    connectionString
    mySqlOptions => mySqlOptions
        .ServerVersion(serverVersion)
        .CharSetBehavior(CharSetBehavior.NeverAppend))
```

MySQL 8.0.17+ allows directly casting to double, while MySQL versions below that don't, so we are using a workaround to make it happen anyway (as long as you specify the correct version).

---

While the following is not the reason for your issue, be aware that MySQL 5.6 has reached its end-of-life as of February this year. So you might want to consider upgrading.
