### ISSUE TITLE
Pomelo.EntityFrameworkCore.MySql causing a CoreClr Event was not raised error when building ASP.NET Core 3.1 with Angular solution if MysqlConnector and Pomelo.JsonObject packages are not referenced in the solution.

### ISSUE THREAD

**Issue by rafiksamman1982** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1440]
### Steps to reproduce
Create a ASP.NET Core 3.1 solution and add Angular 11 and Pomelo.EntityFrameworkCore.MySql only without adding the below packages.
MySqlConnector and Pomelo.JsonObject are dependencies listed in Nuget.

Build and debug the solution, the build/debug process will crash sometimes with the coreclr event was not raised error.

### The issue
I've got a ASP.NET Core 3.1 + Angular 11 app that depends on Pomelo.EntityFrameworkCore.MySql.
I am not using MySqlConnector or Pomelo.JsonObject in my code, but it seems these dependencies are needed.

The solution does not always build reliably, and there's no dependency errors associated with the crash of the build/Debug process.

I'm not sure what you guys can do here... maybe this is just a documentation item.

**Comment by lauxjpn** [comment]
>### Further technical details
>
>MySQL version: 
>Operating system: 
>Pomelo.EntityFrameworkCore.MySql version:
>Microsoft.AspNetCore.App version:

Please fill-out the requested information.

> Build and debug the solution, the build/debug process will crash sometimes with the coreclr event was not raised error.

Please post the exact exception being thrown.

**Comment by rafiksamman1982** [comment]
Mysql 8.0.17
Windows 10 Pro 20H2
Pomelo.EntityFrameworkCore.MySql version: 3.2.5
Microsoft.AspNetCore.App version: 3.1.12

Exception: Unable to attach to CoreCLR

There are no Exception details being shown other than that message in the output window.

.NET Core SDK Version 3.1.409

![image](https://user-images.githubusercontent.com/7150531/120875494-1db4c400-c57a-11eb-94dc-c0b50153e01a.png)

**Comment by lauxjpn** [comment]
I can do some testing, but I am pretty sure that this is not a Pomelo (or MySqlConnector) related error.

It should also not be related in any way to you explicitly specifying the MySqlConnector package or not. Pomelo depends on MySqlConnector, so if you don't specify it explicitly, it will be used implicitly anyway.

The `JsonObject` package is obsolete. Don't use it anymore.

---

@rafiksamman1982 What happens, when you build your project/solution via the `dotnet build` using PowerShell/Command line? Do you get the same error message at build time?

Also, are there any build warnings when the build process does successfully complete?

**Comment by mguinness** [comment]
Make sure you have the correct .NET Core runtime installed

[The target process exited without raising CoreCLR started event](https://stackoverflow.com/questions/55757793/the-target-process-exited-without-raising-coreclr-started-event-error-with-net)

**Comment by lauxjpn** [comment]
@rafiksamman1982 We haven't heard back from you. Do you still need help with this issue?

**Comment by lauxjpn** [comment]
@rafiksamman1982 Since we haven't heard back from you, we are closing this one for now.
