### ISSUE TITLE
Solution to JsonObject is deprecated

### ISSUE THREAD

**Issue by tsq** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1442]
I upgraded Pomelo.EntityFrameworkCore.MySql from **3.2.2** to **5.0.0**.  Because `JsonObject` is deprecated in **5.0.0**, so some error is happened on code using `JsonObject`.

I speed a lot time to find a demo about how to write a JSON type on a entity class, but... it's so difficult to find a good demo.

Thank God, I solved this problem in the end, so I want to record it here and share it with those who need it.

#### 1. install two packages

```sh
dotnet add package Pomelo.EntityFrameworkCore.MySql
dotnet add package Pomelo.EntityFrameworkCore.MySql.Json.Microsoft
```
**Pomelo.EntityFrameworkCore.MySql.Json.Microsoft** is required for supporting JSON type.

ps.: you can also use the package: `Pomelo.EntityFrameworkCore.MySql.Json.Newtonsoft`,  [here](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1232) is the doc.

####  2.  config Mysql on Startup.cs

```c#
        public void ConfigureServices(IServiceCollection services)
        {
            string mysqlConnectionString = Configuration.GetConnectionString("DefaultConnection");
            var mysqlVersion = new MySqlServerVersion(new Version(8, 0, 19));
            services.AddDbContextPool<DataContext>(options => options.UseMySql(mysqlConnectionString, mysqlVersion, mysqlOptions =>
            {
                mysqlOptions.UseMicrosoftJson();
            }));

            services.AddControllers();
        }
```

`mysqlOptions.UseMicrosoftJson();` is required, don't miss it. ps. I got some tips from [here](https://stackoverflow.com/questions/62301095/how-to-use-jsonobject-of-pomelo-entityframework)

Actually, if you don't use mysql JSON type, the third parameter of `options.UseMySql` is not required.

####  3. config entity class

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Demo.Models
{
    public class Progress
    {
        public int ID { get; set; }
        public List<ProgressItem> Content { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
    public class ProgressItem
    {
        public string LectureID { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}
```

about `public List<ProgressItem> Content { get; set; }`, if we use **JsonObject** before, it should be:

```c#
 public JsonObject<ProgressItem[]> Content { get; set; }
```

But now we can just apply a common data type to our property, here I use `List<ProgressItem> ` to represent a JSON array in Mysql, like so:

```
[{
    "LectureID": 1,
    "CreatedAt": null,
    "UpdatedAt": null
}]
```

####  4. add some code in **OnModelCreating** of DataContext

```c#
using Microsoft.EntityFrameworkCore;
using Demo.Models;

namespace Demo.Data
{
    public class DataContext : DbContext
    {
        public DataContext(DbContextOptions<DataContext> options) : base(options)
        {
        }
        public DbSet<Progress> Progresses { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Progress>(entity =>
            {
                entity.Property(e => e.Content).HasColumnType("json");
            });
        }
    }
}
```

Yes, it's required to specify the json type for our table column manually(ps. when we use JsonObject, it's not required), here is it: 

```c#
            modelBuilder.Entity<Progress>(entity =>
            {
                entity.Property(e => e.Content).HasColumnType("json");
            });
```

By 4 steps above, it's work for me, I hope it's also work for you!

**Comment by lauxjpn** [comment]
@tsq Thanks for sharing!

The most comprehensive demo code we currently have is probably the one from https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/14#issuecomment-725294202.

It demonstrates all three types of JSON support: POCOs, the DOM and strings.

**Comment by alexeygritsenko** [comment]
Thanks for the informative post! It helped me, but instead of **OnModelCreating** it's easier to use an attribute
```
[Column(TypeName = "json")]
public List<ProgressItem> Content { get; set; }
```

**Comment by lauxjpn** [comment]
@alexeygritsenko Please open a new issue and post some sample code. Thanks!
