### ISSUE TITLE
Charset Ignored

### ISSUE THREAD

**Issue by twsl** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1470]
### Steps to reproduce
I created a MySql table in MariaDB docker container, db first using the following sql dump.
```SQL
CREATE TABLE `defects` (
  `DefectId` int(10) UNSIGNED NOT NULL,
  `Name` text COLLATE latin1_german2_ci,
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_german2_ci;
```
and from that the models and dbcontext are creating using ef tools.

### The issue
Despite having the following code in my `OnModelCreating`:

```C#
modelBuilder
        .HasCharSet("latin1", DelegationModes.ApplyToDatabases)
        .UseCollation("latin1_swedish_ci");

    modelBuilder.Entity<Defect>(entity =>
    {
        entity.ToTable("defects");

        entity.UseCollation("latin1_german2_ci");

        entity.Property(e => e.DefectId).HasColumnType("int(10) unsigned");

        entity.Property(e => e.Name)
            .HasColumnType("text");
    });
```

the name property show umlauts like `ü` as `Ã¼`.

I validated that the columns have the proper collation_name, but the whole database is in utf8mb4, maybe that is causing the issue? Via mysql cmd utility, everything looks correct.

### Further technical details

MySQL version: 10.5.10-mariadb, Docker
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 5.0.1

Other details about my project setup: .NET 5

**Comment by lauxjpn** [comment]
How was the data inserted to the table? Via app or via some outside data import?
How does the data look when you use mysqldump to export it to a file? Are the special characters/Umlaute correctly dumped to the file, or are they already mangled?

**Comment by twsl** [comment]
The data is inserted into the db by mounting the sql dump file into the `/docker-entrypoint-initdb.d` folder. That triggers mariadb import. When opening the import sql file with VS Code, it shows UTF-8 encoding. Everything looks good so far.

Dumping the data with mysqldump again from the docker container already mangels the umlaute. Encoding in VS Code is again shown as UTF-8.

**Comment by lauxjpn** [comment]
> Dumping the data with mysqldump again from the docker container already mangels the umlaute. 

Then I think it is likely an issue with the import process. The reason it might be shown correctly using the `mysql` command line tool might be, that the encoding the shell/command line/PowerShell is using is compatible (or the same) as the one actually being used for the import.

What does the actual SQL import statement (probably a shell command) of the container look like?
If it is just using the `mysql` command line tool, does it use the [--default-character-set=](https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html#option_mysql_default-character-set) parameter? If so, I think it should be set to the encoding of the source file (or of the system/shell that imports the file; it's not entirely clear) and not the target database.

Quick references:
*  [utf8 garbled when importing into mysql](https://stackoverflow.com/questions/13234433/utf8-garbled-when-importing-into-mysql/35157493)
* [Dumping and importing from/to MySQL in an UTF-8 safe way](https://makandracards.com/makandra/595-dumping-and-importing-from-to-mysql-in-an-utf-8-safe-way#note-section-importing-a-dump-safely)
* [Bad encoding import SQL file into MySQL](https://stackoverflow.com/a/36584300/2618319)

**Comment by twsl** [comment]
Below is the docker-compose i used to start the db container:
```
version: "3.9"

services:
  mariadb-test:
    restart: always
    image: mariadb:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 13306:3306
    volumes:
      - ./MariaDb:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: **********
      MARIADB_DATABASE: **********
```

Selecting from the tables still shows the correctly, mysqldump will mangle the string.

**Comment by twsl** [comment]
Current Workaround:
- Adding reference to nuget package `System.Text.Encoding.CodePages`
- Adding `System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);`
- Calling the following code, whenever I need to access those properties:
 ```
Encoding iso = Encoding.GetEncoding("Windows-1252");// "ISO-8859-1");
byte[] encBytes = iso.GetBytes(defect.Name);
string name = Encoding.UTF8.GetString(encBytes); 
  ```

**Comment by mguinness** [comment]
Not sure if this is related, but take a look at [UTF8 Encoded SQL Scripts in initdb](https://github.com/docker-library/mysql/issues/131).

**Comment by lauxjpn** [comment]
> Seems like both mysqldump and this repo fail to properly convert latin1 to utf8 when exporting and just take the raw bytes.

@twsl I don't think so. I think you are importing it using the wrong encoding (likely because the shell encoding is used, which is not utf-8, while the SQL file you use for your import is utf-8).

Try the steps I outlined above to verify this:

> A simple way to verify that this is indeed an import encoding issue could be to just connect to your database via MySQL Workbench, load the file with the correct encoding (e.g. use vscode to load it and then copy & paste the content to a MySQL Workbench query tab) and then execute it directly from MySQL Workbench.

---

> Not sure if this is related, but take a look at [UTF8 Encoded SQL Scripts in initdb](https://github.com/docker-library/mysql/issues/131).

@mguinness Yeah, if the shell encoding is the issue, which is likely, then setting the shell encoding to utf-8 is likely to solve this issue as well.
Or just add the `--default-character-set=utf8mb4` parameter to the `mysql` import shell command, so the file is read as utf-8 and not as the native shell encoding, as outlined in the references I linked in my previous comment.

**Comment by twsl** [comment]
You were completly right, @lauxjpn !
Using `--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci` is simply used too late, only after initializing the database. Could definitely be improved on site of mariadb.
Setting `default-character-set` as command argument directly was not possible (missing additional args [here](https://github.com/MariaDB/mariadb-docker/blob/master/docker-entrypoint.sh#L220) where files are piped directly into mysql), but simply using eigher MySql Workbench or the solution from the thread posted by @mguinness using `-e LANG=C.UTF-8` solved the issue.

Big thanks for helping me investigate this.
