### ISSUE TITLE
MysqlException invalid syntax for sql in HasComputedColumnSql

### ISSUE THREAD

**Issue by Francis6543** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1472]
### Steps to reproduce
I have a table like this:

```SQL
CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(150) NOT NULL,
  `lastname` varchar(150) NOT NULL,
  `fullname` varchar(301) GENERATED ALWAYS AS (concat(`firstname`,_utf8mb4' ',`lastname`)) VIRTUAL,
  PRIMARY KEY (`id`),
)
```

I run the dbcontext scaffold using Pomelo.EntityFrameworkCore.MySql:

`dotnet ef dbcontext scaffold "myconnectionstring" Pomelo.EntityFrameworkCore.MySql -o "Models/Database" --context "myDbContext" --no-pluralize --no-onconfiguring -f`

In the generated DbContext, I have:

```C#
entity.Property(e => e.Fullname)
      .HasMaxLength(301)
      .HasColumnName("fullname")
      .HasComputedColumnSql("concat(`firstname`,_utf8mb4\\' \\',`lastname`)", false);
```

Now, if I create a database using the dbContext:

`myDbContext.Database.EnsureCreated();`

I get an error for an invalid syntax.

### The issue
``.HasComputedColumnSql("concat(`firstname`,_utf8mb4\\' \\',`lastname`)", false);``

The single quote for specifing a space must not be escaped. If I remove the double backslash before single quote, it runs fine.
I fixed it this way:

``.HasComputedColumnSql("concat(`firstname`,_utf8mb4' ',`lastname`)", false);``

### Further technical details

MySQL version: 8.0.15
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 5.0.1
Microsoft.AspNetCore.App version: 3.1
dotnet ef tools version: 5.0.7

**Comment by lauxjpn** [comment]
This seems to be a MySQL 8 specific bug.
I filed [[REGRESSION] Unexpected escaped string returned in GENERATION_EXPRESSION](https://bugs.mysql.com/bug.php?id=104294) on Oracle's official bug tracker.

We will implement a workaround though.

**Comment by lauxjpn** [comment]
This will be part of the `5.0.2` release.
Use the latest [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) until then.
