### ISSUE TITLE
HasCharSet and UseCollation are not delegated to child columns of type Guid

### ISSUE THREAD

**Issue by TrobinsonCincom** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1477]
### Steps to reproduce
1) Create the following class.

```C#
[Table("Test")]
public class Test
{
    public Guid TestId { get; set; }

    public string Name { get; set; }
}
```

2) Call `HasCharset` and `UseCollation` on the ModelBuilder in OnModelCreating as shown below.

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.HasCharSet(CharSet.Utf8Mb4, true)
        .UseCollation("utf8mb4_general_ci");

    modelBuilder.Entity<Test>().HasKey(e => e.TestId);
}
```

3) Generate a migration.

### The issue
The migration assigns the `utf8mb4_general_ci` collation to the Name column as expected. However, ascii_general_ci is assigned to the TestId column. The charset and collation I set for the database was ignored on the Guid column.

```C#
migrationBuilder.CreateTable(
    name: "Test",
    columns: table => new
    {
        TestId = table.Column<Guid>(type: "char(36)", nullable: false, collation: "ascii_general_ci"),
        Name = table.Column<string>(type: "longtext", nullable: true, collation: "utf8mb4_general_ci")
            .Annotation("MySql:CharSet", "utf8mb4")
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Test", x => x.TestId);
    })
    .Annotation("MySql:CharSet", "utf8mb4")
    .Annotation("Relational:Collation", "utf8mb4_general_ci");
```

### Further technical details

MySQL version:  10.3.23-MariaDB-log
Operating system: 
Pomelo.EntityFrameworkCore.MySql version: 5.0.1
Microsoft.AspNetCore.App version: 5.0

**Comment by mguinness** [comment]
See `DefaultGuidCollation` setting:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/b9195dee266404da569b9681856a95acc7a5bfb3/src/EFCore.MySql/Internal/MySqlOptions.cs#L36

**Comment by lauxjpn** [comment]
The default collation for `Guid` text columns is `ascii_general_ci`, because it performs the best.

To change the collation for `Guid` text columns, call the `modelBuilder.UseGuidCollation(string)` Fluent API extension method (e.g. from your `DbContext.OnModelCreating()` method).

_From the XML docs/IntelliSense:_
> [...] An _empty string_ means that no explicit collation will be applied, while `null` means that the default collation `ascii_general_ci` will be applied.

So if you want to use the default collation of your database for your `Guid` text columns as well, call `modelBuilder.UseGuidCollation(string.Empty)`.
