### ISSUE TITLE
LEFT JOIN is generated with LATERAL which breaks the query on MySQL 8.0.18

### ISSUE THREAD

**Issue by OldrichDlouhy** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1479]
### Steps to reproduce

Having tables `Customers`, `SystemFeatures` and m:n relation table `CustomerFeatures`, and corresponding entities, the following code 

``` CSharp
dbContext.Customers
    .AsNoTracking()
    .Select(c => new {
        Customer = new { Id = c.Id, Name = c.Name },
        Features = dbContext.SystemFeatures
            .AsNoTracking()
            .Select(s => new {
                Id = s.Id,
                Name = s.Name,
                Enabled = c.Features.Any(f => f.Enabled && f.FeatureId == s.Id)
            })
            .ToList()
    }
)
```
generates SQL 
``` SQL
SELECT `c0`.`Id`, `c0`.`Name`, `s`.`Id`, `s`.`Name`, EXISTS (
    SELECT 1
    FROM `CustomerFeature` AS `c`
    WHERE (`c0`.`Id` = `c`.`CustomerId`) AND (`c`.`Enabled` AND (`c`.`FeatureId` = `s`.`Id`)))
FROM `Customers` AS `c0`
LEFT JOIN LATERAL `SystemFeatures` AS `s` ON TRUE
ORDER BY `c0`.`Id`, `s`.`Id`
```
for which the MySQL 8.0.18 throws `MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`SystemFeatures` AS `s` ON TRUE
ORDER BY `c0`.`Id`, `s`.`Id`' at line 6`

Removing the `LATERAL` from the query runs it perfectly fine, returning expected results.

### Further technical details

MySQL version: 8.0.18 
Operating system: Windows 10, 1909
Pomelo.EntityFrameworkCore.MySql version: 5.0.1
Microsoft.EntityFrameworkCore version: 5.0.8
Microsoft.AspNetCore.App version: 5.0.0

**Comment by lauxjpn** [comment]
@OldrichDlouhy Thanks for the report. We already fixed the issue with #1457 (the `Fix LATERAL usage for split queries that don't need it.` commit ae7bc17).

You can test/use it by referencing Pomelo `6.0.0-preview.5`.
