### ISSUE TITLE
The length of the migrationid field generated by MySQL historyrepository is incorrect

### ISSUE THREAD

**Issue by yilezhu** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1480]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

### The issue
The length of the MigrationId field generated by `MysqlHistoryRepository` is incorrect.Normally, the defined length of `MigrationId ` is 150 ,but `MysqlHistoryRepository` generated length is 95
Here is efcore code
```
protected virtual void ConfigureTable(EntityTypeBuilder<HistoryRow> history)
        {
            history.ToTable(DefaultTableName);
            history.HasKey(h => h.MigrationId);
            history.Property(h => h.MigrationId).HasMaxLength(150);
            history.Property(h => h.ProductVersion).HasMaxLength(32).IsRequired();
        }
```
Here is MysqlHistoryRepository'code

```
protected override void ConfigureTable([NotNull] EntityTypeBuilder<HistoryRow> history)
        {
            base.ConfigureTable(history);

            history.HasCharSet(CharSet.Utf8Mb4);
        }
```
![image](https://user-images.githubusercontent.com/18655233/127492200-778c946a-7359-4696-8556-9d21ffd8926b.png)

### Further technical details

MySQL version:  5.7.33
Operating system: windows server 2012R2
Pomelo.EntityFrameworkCore.MySql version:5.0.0-alpha.2
Microsoft.AspNetCore.App version:net5.0

Other details about my project setup:

**Comment by mguinness** [comment]
Please include your `HistoryRow` model and also see PR https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1326.

**Comment by yilezhu** [comment]
This is defined by default in HistoryRepository by efcore. I don't have any settings

**Comment by mguinness** [comment]
@yilezhu Are you using version 3.2 or 5.0 of Pomelo?  You left that blank in the new issue template.

**Comment by yilezhu** [comment]
> @yilezhu Are you using version 3.2 or 5.0 of Pomelo? You left that blank in the new issue template.

Sorry, I have put the corresponding version information in the problem template.

**Comment by mguinness** [comment]
You need to upgrade from prerelease [5.0.0-alpha.2](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/5.0.0-alpha.2) to latest [5.0.1](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/5.0.1) and try again as it should include PR https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1326.

**Comment by yilezhu** [comment]
Very good. It's working good
