### ISSUE TITLE
Method HasAlternateKey not found

### ISSUE THREAD

**Issue by ng-designs** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1488]
When i update to latest version library for this [project](https://github.com/broderickhyman/albiondata-sql-dotNet), it will crash with next error:

Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Builders.KeyBuilder Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasAlternateKey(System.Linq.Expressions.Expression`1<System.Func`2<!

With old versions up to 3.2.6, all works fine.

How can i resolve this problem?

**Comment by mguinness** [comment]
Not enough information provided.  Typically these exceptions occur when you have mismatched library versions.  Check that you're using the latest 5.0.1 release and 5.0.8 of `Microsoft.EntityFrameworkCore`.

**Comment by ng-designs** [comment]
> Not enough information provided. Typically these exceptions occur when you have mismatched library versions. Check that you're using the latest 5.0.1 release and 5.0.8 of `Microsoft.EntityFrameworkCore`.

all libraries is updated to latest stable version 

IDE marks to this code:

      modelBuilder.Entity<MarketOrderExpiredDB>(entity =>
      {
        entity.ToTable("market_orders_expired");
        entity.HasKey(e => e.Id);
        entity.HasAlternateKey(e => e.AlbionId)
              .HasName("AlbionId");

        entity.Property(e => e.AlbionId)
              .IsRequired();
        entity.Property(e => e.Amount)
              .HasColumnName("amount");
        entity.Property(e => e.AuctionType)
              .HasColumnName("auction_type")
              .HasMaxLength(32);
        entity.Property(e => e.EnchantmentLevel)
              .HasColumnName("enchantment_level");
        entity.Property(e => e.Expires)
              .HasColumnName("expires");
        entity.Property(e => e.Id)
              .HasColumnName("id");
        entity.Property(e => e.ItemTypeId)
              .HasColumnName("item_id")
              .HasMaxLength(128);
        entity.Property(e => e.LocationId)
              .HasColumnName("location")
              .IsRequired();
        entity.Property(e => e.QualityLevel)
              .HasColumnName("quality_level");
        entity.Property(e => e.UnitPriceSilver)
              .HasColumnName("price");
      });

i think problem is in Microsoft.EntityFrameworkCore lib

**Comment by lauxjpn** [comment]
Works fine for me:

```
PS E:\Sources\PomeloIssues\Issue1488\albiondata-sql-dotNet> dotnet build
Microsoft (R) Build Engine version 17.0.0-preview-21302-02+018bed83d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  albiondata-sql-dotNet -> E:\Sources\PomeloIssues\Issue1488\albiondata-sql-dotNet\albiondata-sql-dotNet\bin\Debug\netcoreapp3.1\albiondata-sql-dotNet.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.43
```

The changes I made:

```diff
--- a/albiondata-sql-dotNet/ConfiguredContext.cs
+++ b/albiondata-sql-dotNet/ConfiguredContext.cs
@@ -16,6 +16,7 @@ namespace albiondata_sql_dotNet

       // Use a large timeout since we have deletes that must do table scans
       optionsBuilder.UseMySql(Program.SqlConnectionUrl,
+        ServerVersion.AutoDetect(Program.SqlConnectionUrl),
         opts => opts.CommandTimeout((int)TimeSpan.FromMinutes(5).TotalSeconds));
 #if DEBUG
       if (Program.Debug)
diff --git a/albiondata-sql-dotNet/albiondata-sql-dotNet.csproj b/albiondata-sql-dotNet/albiondata-sql-dotNet.csproj
index 4a6cde7..1ce312e 100644
--- a/albiondata-sql-dotNet/albiondata-sql-dotNet.csproj
+++ b/albiondata-sql-dotNet/albiondata-sql-dotNet.csproj
@@ -9,11 +9,11 @@
   <ItemGroup>
     <PackageReference Include="AlbionData.Models" Version="0.1.11" />
     <PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="2.5.1" />
-    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.1" />
-    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="3.1.1" />
+    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
+    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
     <PackageReference Include="NATS.Client" Version="0.10.0" />
     <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
-    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.1.1" />
+    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="5.0.1" />
   </ItemGroup>

 </Project>
```

**Comment by ng-designs** [comment]
I don't know why, but on to another computers i've got one result:
![image](https://user-images.githubusercontent.com/4186146/128851214-3dda6471-45f2-43fe-bb79-b446b3740d7a.png)

**Comment by mguinness** [comment]
Assuming you've made the appropriate changes to the csproj file, try clean solution option from build menu in VS.

**Comment by lauxjpn** [comment]
> Assuming you've made the appropriate changes to the csproj file, try clean solution option from build menu in VS.

@ng-designs If that doesn't help, manually remove the `bin` and `obj` folders and rebuild again.

If that still does not help, double check from what folder your application runs. Check that the libraries (especially Pomelo and EF Core DLLs) are present and have the expected versions.

**Comment by ng-designs** [comment]
> > Assuming you've made the appropriate changes to the csproj file, try clean solution option from build menu in VS.
> 
> @ng-designs If that doesn't help, manually remove the `bin` and `obj` folders and rebuild again.
> 
> If that still does not help, double check from what folder your application runs. Check that the libraries (especially Pomelo and EF Core DLLs) are present and have the expected versions.

I did it, but there is no result. I'm downloading a clean, working project from github. I update your library to the latest stable version, add ServerVersion.AutoDetect(Program.SqlConnectionUrl) to optionsBuilder, build the project and when I run it I get this error.

I do not understand why my friend and I have the same error on two different computers, but everything works fine on yours.

**Comment by ng-designs** [comment]
> > I update only your library to the latest stable version with NuGet package manager, add ServerVersion.AutoDetect(Program.SqlConnectionUrl) to optionsBuilder, build the project and when I run it I get this error.
> 
> In addition to updating `Pomelo.EntityFrameworkCore.MySql` to 5.0.1 you also need to update both `Microsoft.Extensions.Logging` and `Microsoft.Extensions.Logging.Console` to 5.0.0 as detailed earlier.

There is no difference between updating this libraries and not. I've already tried few different variants about updating libs and replace them with another libs. I think it is problems with EF Core, becouse when i replace your lib with MySql.EntityFrameworkCore and Microsoft.EntityFrameworkCore libs, i have the same error. I didn't change anything else in project, only update libs and add ServerVersion option. I have no idea

**Comment by mguinness** [comment]
> Check that the libraries (especially Pomelo and EF Core DLLs) are present and have the expected versions.

What do you see in the debug or release folder?  Are you using .NET 5 or .NET 6 preview?

**Comment by lauxjpn** [comment]
@ng-designs Ah, sorry, I did not run the app, I just compiled it.

Your project uses the `AlbionData.Models` NuGet package, which has the following dependencies:

```
.NETStandard 2.1

Microsoft.EntityFrameworkCore (>= 3.1.1)
Microsoft.EntityFrameworkCore.Relational (>= 3.1.1)
Newtonsoft.Json (>= 12.0.3)
System.ComponentModel.Annotations (>= 4.7.0)
```

While it technically says `Microsoft.EntityFrameworkCore (>= 3.1.1)`, that is actually not correct, because major EF Core versions are not compatible with each other.

So if a component officially depends on EF Core >= 3.1.1, it really means EF Core >= 3.1.1 && EF Core < 5.0.0.

---

You either need to use EF Core 3.1 with the `AlbionData.Models` package, or you need a version of it that is actually compatible with EF Core 5.0.

Since its [repository](https://github.com/broderickhyman/albiondata-models-dotnet) is public, you can just clone it, update its package references to use EF Core 5.0 and then recompile it. That should fix it.

**Comment by ng-designs** [comment]
> @ng-designs Ah, sorry, I did not run the app, I just compiled it.
> 
> Your project uses the `AlbionData.Models` NuGet package, which has the following dependencies:
> 
> ```
> .NETStandard 2.1
> 
> Microsoft.EntityFrameworkCore (>= 3.1.1)
> Microsoft.EntityFrameworkCore.Relational (>= 3.1.1)
> Newtonsoft.Json (>= 12.0.3)
> System.ComponentModel.Annotations (>= 4.7.0)
> ```
> 
> While it technically says `Microsoft.EntityFrameworkCore (>= 3.1.1)`, that is actually not correct, because major EF Core versions are not compatible with each other.
> 
> So if a component officially depends on EF Core >= 3.1.1, it really means EF Core >= 3.1.1 && EF Core < 5.0.0.
> 
> You either need to use EF Core 3.1 with the `AlbionData.Models` package, or you need a version of it that is actually compatible with EF Core 5.0.
> 
> Since its [repository](https://github.com/broderickhyman/albiondata-models-dotnet) is public, you can just clone it, update its package references to use EF Core 5.0 and then recompile it. That should fix it.

Thanks you very match! I was too tired to understand that on that day. I've added models to project as classes and now all works fine! 

Your are the best!
