### ISSUE TITLE
Scaffold-DbContext Seems to be running, but no output

### ISSUE THREAD

**Issue by tsfinley** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#149]
### Steps to reproduce
From the Package Manager Console:
Scaffold-DbContext "server=10.1.1.1;port=3306;database=magento;uid=thomas;password=password" "Pomelo.EntityFrameworkCore.MySql" -o "Models/Magento" -verbose

*The IP, Username and Password have been changed to protect the innocent. ;)

Output so far:
Build started...
Build succeeded.
Setting app base path C:\Users\thomas\Documents\Visual Studio 2015\Projects\MyProject\src\MyProject.Web\.\bin\Debug\netcoreapp1.0

### The issue
Seems to be running as my CPU is hovering at 20%, but nothing is happening. This is a Magento database I'm hitting against so it has a quite a few tables.

MySQL version: 5.6
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 1.1.0

Other details about my project setup:

Part of my project.json:
{
  "dependencies": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "BundlerMinifier.Core": "2.2.306",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Pomelo.EntityFrameworkCore.MySql": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Pomelo.EntityFrameworkCore.MySql.Design": "1.1.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

**Comment by mguinness** [comment]
No kidding, the [magneto database](http://anna.voelkl.at/uploads/magento/ce1922.png) has over 300 tables :)  Unfortunately, I don't believe the verbose flag works at this time.  If you wanted to build a debug version you could make this [alteration](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql.Design/Internal/MySqlDatabaseModelFactory.cs#L30) to help find issues.

Short of that you could try `--table <schema.table>` option to see if it works.  Bear in mind that a table won't get scaffolded unless it has a PK.  FWIW, I've been able to scaffold about 150 tables (with no FK's used).

**Comment by mguinness** [comment]
@tsfinley I found an old Magneto 1.7 schema and ran a migration against it.  Worked fine w/ the following warnings:

      Unable to identify the primary key for table 'api_session'.
      Unable to identify the primary key for table 'catalog_category_anc_categs_index_idx'.
      Unable to identify the primary key for table 'catalog_category_anc_categs_index_tmp'.
      Unable to identify the primary key for table 'catalog_category_anc_products_index_idx'.
      Unable to identify the primary key for table 'catalog_category_anc_products_index_tmp'.
      Unable to identify the primary key for table 'catalog_category_product_index_enbl_idx'.
      Unable to identify the primary key for table 'catalog_category_product_index_enbl_tmp'.
      Unable to identify the primary key for table 'catalog_category_product_index_idx'.
      Unable to identify the primary key for table 'catalog_category_product_index_tmp'.
      Could not find type mapping for column 'paypal_payment_transaction.additional_information' with data type 'blob'. Skipping column.
      Could not find type mapping for column 'sales_payment_transaction.additional_information' with data type 'blob'. Skipping column.
      Unable to identify the primary key for table 'weee_discount'.
      Could not find type mapping for column 'xmlconnect_history.params' with data type 'blob'. Skipping column.

It output models for the remaining 326 tables and also the DbContext class.

**Comment by Kagamine** [comment]
In EF, a table must contains a key. if not, it cannot be scaffolded. Since @mguinness tried successfully, we could not repro your issue now. You can try to wait a bit more. 

@mguinness good catch, I will fix the blob type mapping issue (#150)

**Comment by tsfinley** [comment]
I think it was a bandwidth issue on my end. I was connecting to a remote MySQL box. I copied the schema to a local instance of MySQL and it worked like a charm. Thank you for the help.

**Comment by JanBN** [comment]
I have the same problem. What is strange that on another computer (at work) it works. But on my home pc it does nothing. On Monday I will try it at work again.

However I run this:
`C:\.Net Core\EFTest MySql\EFTest>dotnet ef dbcontext scaffold "Server=localhost;User Id=root;Password=;Database=bcd" "Pomelo.EntityFrameworkCore.MySql"  -o
 Mode2 --verbose` with verbose option

and this is the output:

> c:\.Net Core\EFTest MySql\EFTest>dotnet ef dbcontext scaffold "Server=localhost;User Id=root;Password=;Database=bcd" "Pomelo.EntityFrameworkCore.MySql"  -o Mode2 --verbose
> Using project 'c:\.Net Core\EFTest MySql\EFTest\EFTest.csproj'.
> Using startup project 'c:\.Net Core\EFTest MySql\EFTest\EFTest.csproj'.
> dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\jp\AppData\Local\Temp\tmp9E9.tmp /verbosity:quiet /nologo "c:\.Net Core\EFTest MySql\EFTest\EFTest.csproj"
> dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\jp\AppData\Local\Temp\tmpC7A.tmp /verbosity:quiet /nologo "c:\.Net Core\EFTest MySql\EFTest\EFTest.csproj"
> dotnet build "c:\.Net Core\EFTest MySql\EFTest\EFTest.csproj" /verbosity:quiet /nologo
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:02.42
> dotnet exec --depsfile "c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\EFTest.deps.json" --additionalprobingpath C:\Users\jp\.nuget\packages --runtimeconfig "c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\EFTest.runtimeconfig.json" C:\Users\jp\.nuget\packages\microsoft.entityframeworkcore.tools.dotnet\1.0.0\tools\netcoreapp1.0\ef.dll dbcontext scaffold "Server=localhost;User Id=root;Password=;Database=bcd" Pomelo.EntityFrameworkCore.MySql -o Mode2 --assembly "c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\EFTest.dll" --startup-assembly "c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\EFTest.dll" --project-dir "c:\.Net Core\EFTest MySql\EFTest\\" --content-root "c:\.Net Core\EFTest MySql\EFTest\\" --data-dir "c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\\" --verbose --root-namespace EFTest
> Using assembly 'EFTest'.
> Using startup assembly 'EFTest'.
> Using application base 'c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0'.
> Using content root 'c:\.Net Core\EFTest MySql\EFTest\'.
> Using root namespace 'EFTest'.
> Using project directory 'c:\.Net Core\EFTest MySql\EFTest\'.
> Using data directory 'c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\'.

It won't continue after **Using data directory 'c:\.Net Core\EFTest MySql\EFTest\bin\Debug\netcoreapp1.0\'**
