### ISSUE TITLE
Wrong boolean type on scaffold

### ISSUE THREAD

**Issue by Jennal** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1490]
Hi, I am try to use pomelo scaffold mysql table into csharp code.

The table is 

```SQL
CREATE TABLE `employee` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` char(10) NOT NULL,
  `password` char(32) NOT NULL,
  `session_id` char(40) NOT NULL,
  `session_data` text NOT NULL,
  `activated` tinyint(1) NOT NULL DEFAULT '1',
  `show_in_select` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

and the scaffold script is 

`dotnet ef dbcontext scaffold "server=localhost;database=zoe;user=root;password=;treattinyasboolean=true;charset=utf8;" "Pomelo.EntityFrameworkCore.MySql" --project proj.csproj -o Generated/ -f`

result is 

```C#
public partial class Employee
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Password { get; set; }
    public string SessionId { get; set; }
    public string SessionData { get; set; }
    public bool? Activated { get; set; }
    public bool? ShowInSelect { get; set; }
}
```

I am confused that why `bool?` not `bool`. `bool?` is nullable `bool` but I set the column type as `NOT NULL`.   Is this a bug?

### Further technical details

MySQL version: 8.0.22
Operating system: Windows10
Pomelo.EntityFrameworkCore.MySql version: 5.0.2
Microsoft.AspNetCore.App version: 5.0.302

**Comment by lauxjpn** [comment]
I think this is the classic _doomsday machine issue_ I outlined in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/989#issuecomment-564860672.
Feel encouraged to take a closer look at the sample code I posted there.

There should be a related warning shown to you in the console, when scaffolding.

This is not a bug.
Using `bool?` in this case is the only way for EF Core to distinguish between an unset value, that then gets the SQL default value applied, and .NET's default value (which is `false`).

If you would change `bool?` to `bool` and then add a new `Employee`, you would always end up having `Activated = true` and `ShowInSelect = true` in your database, regardless of what you set those properties to:
* If you set `Activated = false` than EF Core recognizes `false` as the .NET default value for `bool` and will therefore assume that you did not explicitly set `Activated` to any value at all. It will therefore apply the default value that you configured, which is `1`/`true`.
* If you set `Actived = true` than EF Core recognizes `true` as something different from the .NET default value for `bool` and will therefore use this value. So it will apply `true` again.

**Comment by lauxjpn** [comment]
@ajcvickers We are getting this question from time to time. It might make sense to add a bit more context to [Generated Values: Default values](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#default-values) that explains how EF Core decides to apply configured default values (when EF Core thinks a value has not been set, which it assumes when it encounters `value = .NET default value for that type`) and that this means e.g. that a `bool` property with a configured default value of `true` can only ever be `true`.

**Comment by ajcvickers** [comment]
@lauxjpn We have [change-tracking docs for this](https://docs.microsoft.com/en-us/ef/core/change-tracking/miscellaneous#working-with-default-values). I'll file a docs issue to cross-link these topics.

**Comment by Jennal** [comment]
I am wonderring if it is possible to generate code like this:

```csharp
public bool Activated { get; set; }=true;
```

**Comment by lauxjpn** [comment]
> We have [change-tracking docs](https://docs.microsoft.com/en-us/ef/core/change-tracking/miscellaneous#working-with-default-values) for this. I'll file a docs issue to cross-link these topics.

@Jennal Take a look at [Nullable backing fields for bool properties](https://docs.microsoft.com/en-us/ef/core/change-tracking/miscellaneous#nullable-backing-fields-for-bool-properties), that is part of the docs that @ajcvickers referenced above. It is likely the solution you are looking for.
