### ISSUE TITLE
Added JSON, like the original JSON content, but the indentation or layout is not the same, resulting in Assert is not equal

### ISSUE THREAD

**Issue by applenele** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#15]
Added JSON, like the original JSON content, but the indentation or layout is not the same, resulting in Assert is not equal

![4e kg4z477r a7mx2pse](https://cloud.githubusercontent.com/assets/2216750/16860689/e0f56908-4a6c-11e6-98f8-4bfceeed68fd.png)

**Comment by Kagamine** [comment]
@TiriSane What is the process about this issue?
