### ISSUE TITLE
Concatenating string and number in EF.Functions.LIKE match expression makes the search case-sensitive

### ISSUE THREAD

**Issue by OldrichDlouhy** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1511]
### Steps to reproduce

Have entity like this:

```CSharp
public class Container {
  public int Id { get ; set; }
  public string Name { get ; set; }
  public int Number { get; set; }
}
```

`Name` field collation is `utf8mb4_0900_ai_ci` (default).

The following query
```CSharp
context.Containers
  .Where(e => EF.Functions.Like(e.Name + e.Number.ToString(), "%Metal%"))
  .ToList()
```

translates to 

```SQL
SELECT `c`.`Id`, `c`.`Name`, `c`.`Number`
FROM `Containers` AS `c`
WHERE CONCAT(COALESCE(`c0`.`Name`, ''), COALESCE(CAST(`c0`.`Number` AS char) COLLATE utf8mb4_bin, '')) LIKE '%Metal%'
```

The `COLLATE` statement on the `Number` column forces the search to be case-sensitive.

### The issue

The search is expected to be case insensitive but is not.

### Further technical details

MySQL version: 8.0.18
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 5.0.1
Microsoft.AspNetCore.App version: 5.0.9

**Comment by lauxjpn** [comment]
This is a current limitation of the provider, that we are aware of:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/ebed280097d498ad1b999c32501cd53849d7897d/src/EFCore.MySql/Query/ExpressionVisitors/Internal/MySqlQuerySqlGenerator.cs#L377-L383

I'll take another look, whether we can make it work reliably without the forced `COLLATE` clause or not.

**Comment by lauxjpn** [comment]
We added this in #1057 as part of the #996 fix.
However, no tests seem to fail (anymore) when I remove this piece of code.

We will therefore remove the clause, as the original issue might have been fixed in the meantime, by how it is being translated.
