### ISSUE TITLE
Question: Perform MySQL translation /only/, for testing & in-memory db

### ISSUE THREAD

**Issue by LordMike** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1514]
Hi,

Purely a question I couldn't find the answer to, which you might know.

We have a project that uses Pomelo to do MySQL for our EF database. When we run queries locally, we will use an in-memory database. The obvious issue is that the in-memory database supports a different set of expressions than Pomelo (everything, because,... C#).. 

I had a thought, that I could add a translation step for our in-memory db, such that it translates to SQL using Pomelo.. and _then_ it does whatever it does.. This way, we can catch invalid queries before we deploy to our staging environment.

Is this possible? Feasible? -- where would I start (is there a `PomeloExpression.Translate()` I can use)?

Additionally - it would be really cool, if this works, to have an extension for the in-memory database to add ".ValidateQueriesInPomelo()" to get this validation I mention, so that it's available for all :)

Mike.

**Comment by lauxjpn** [comment]
> I had a thought, that I could add a translation step for our in-memory db, such that it translates to SQL using Pomelo.. and _then_ it does whatever it does.. This way, we can catch invalid queries before we deploy to our staging environment.

I'm not sure I fully understand what you are trying to accomplish. Please elaborate in more detail.

---

> When we run queries locally, we will use an in-memory database.

Do you mean the [EF Core In-Memory Database Provider](https://docs.microsoft.com/en-us/ef/core/providers/in-memory/) or something else?

---

Generally, your CI environment (or your local machines) should run tests against an actual MySQL instance, to ensure that everything (including the generated SQL) works as expected.

**Comment by LordMike** [comment]
Sure, if I had a query like the following:

```csharp
var someDict = new Dictionary<int, string>{ { 1, "Some string" } };
myContext.Blogs.First(s => someDict.ContainsKey(s.Id));
```

.. this works in the In Memory database (yes, from Microsoft), which we, and I assume many others, use for local executions of our codebase (with mocked data) in addition to the few unit tests we do have. The issue is that, the query works - because it's C# code. 

It won't work in Pomelo however, as the `ContainsKey()` can't be translated. (For the curious, `someDict.Keys.Contains(s.Id)` works fine). 

My hope was, that I could replace some service within EF, in our local use case, that operates on the expression before it's being translated. In this replacement, I wanted to run something like:

```csharp
// The expression we had before
Expression<Func<Blog, bool>> expression = s => someDict.ContainsKey(s.Id);

// Call in Pomelo translation
// If this throws, the expression _could not_ be performed in Pomelo
// The result is _not interesting_ ... we just need to know that it _can_ be translated
var translated = PomeloTranslator.Translate(expression);

// Pass on the expression to the in-memory database
// I suppose this will call some `base`, as I'll likely inherit from whatever class is actually handling the expression - so when I know the expression is ok, I can pass it on.
actualDatabase.Perform(expression) ....;
```

The goal is, that in our local executions of our code, we can know that the expressions _can be translated to SQL_. 

Thanks in advance :).

**Comment by LordMike** [comment]
So the question is really two-fold:

1. Is there an entrypoint, like my example `PomeloTranslator`, that I can call to translate an expression to an SQL string? -- can I call it without getting too involved (lots of supporting services), or should I get it from the DI system?
2. My next task is to intercept the query execution at an appropriate point in order to insert this translation step, when using the in memory database - do you know where this might be? ... Else I'll just go digging in EF to find relevant services :).

**Comment by LordMike** [comment]
Hot damn. I'll have to try this out.

Thanks a lot ! :)

Do you think this feature would have a wider audience? If so, I can try to package it down, when I get time to work on it for our use case, so that it may work for any db context. I'm hoping the API in the end can be:

```
optionsBuilder
	.UseInternalServiceProvider(serviceProvider)
	.UseInMemoryDatabase("Issue1514")
        .UseQueryTranslationFrom<>(x => ConfigurePomelo())
        .UseQueryTranslationFrom<>(x => ConfigureMsSQL())
        .UseQueryTranslationFrom<>(x => ConfigureSqlite());
```

.. somehow make (small) adapters as needed to allow for this translation to be plugged in.

**Comment by lauxjpn** [comment]
> Do you think this feature would have a wider audience?

Could be. It is definitely more useful then just using the in-memory provider alone.

However, the usual way is to just run tests against a real instance, which might take a bit more time, but ensures that everything works exactly as expected.

**Comment by LordMike** [comment]
That's entirely true - but that's integration testing.. I don't think developers should be expected to do integration testing while developing locally :)

I'll see if I can get around to it - this is definitely a great start! 👍

**Comment by LordMike** [comment]
@lauxjpn hey again. I found some time and [created this](https://github.com/LordMike/MBW.EF.ExpressionValidator). It wouldn't have been possible without your contribution, so I'm very grateful :)

It works in my limited test scenarios, and I hope to be able to test it more thoroughly later. 

I ended up doing a replacement of the `IQueryCompiler` via the DI system, where my custom compiler wraps the existing compiler. It then does translation to one or more other database query systems, failing if any one of them fails.

**Comment by lauxjpn** [comment]
@LordMike Thanks for sharing, nice work!

For the Pomelo implementation, you probably want the user to pass the `ServerVersion` along to the `UseMySql()` method, because query building can differ over database server types (MySQL/MariaDB) and versions.

(And you might want to change the dummy connection string to something less weird, like `database=dummy` or `server=localhost` or so 😁.)
