### ISSUE TITLE
Need help with character set related migration inconsistencies

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1521]
@lauxjpn sorry for ping back, I should have tried it earlier, but was looking for `5.0.2` release...

Now I have the following issue - here is the SQL generated for one of the tables:
```SQL
CREATE TABLE `Downloads` (
    `Id` varchar(255) NOT NULL,
    `CreationDate` datetime(6) NOT NULL,
    `ExpirationDate` datetime(6) NOT NULL,
    `IsUsed` tinyint(1) NOT NULL,
    `UserId` varchar(255) NOT NULL,
    CONSTRAINT `PK_Downloads` PRIMARY KEY (`Id`),
    CONSTRAINT `FK_Downloads_AspNetUsers_UserId` FOREIGN KEY (`UserId`) REFERENCES `AspNetUsers` (`Id`) ON DELETE CASCADE
);
```

And I'm having the following error `errno: 150 "Foreign key constraint is incorrectly formed"`.

In order to fix the SQL I need to add `CHARACTER SET utf8mb4` to `Id` and `UserId` columns, so this way it works:
* `Id varchar(255) NOT NULL` -> `Id varchar(255) CHARACTER SET utf8mb4 NOT NULL`
* `UserId varchar(255) NOT NULL` -> `UserId varchar(255) CHARACTER SET utf8mb4 NOT NULL`

And I added the following line to `OnModelCreating` `builder.HasCharSet("utf8mb4")`:
```C#
protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);
    builder.HasCharSet("utf8mb4");
}
```

But it doesn't seem to help...

Sorry in case I'm missing something...

Thanks

_Originally posted by @imalkevich in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1493#issuecomment-922478412_

**Comment by lauxjpn** [comment]
Edit: found the following question that was answer some time ago - https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1437 - but unfortunately `modelBuilder.HasCharSet("utf8mb4")` has no effect in my case...

_Originally posted by @imalkevich in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1493#issuecomment-922482960_

**Comment by lauxjpn** [comment]
If you want _all_ your tables and columns using `utf8mb4`, then `builder.HasCharSet("utf8mb4");` should work, but not specifying it at all should be the same (as it is the default anyway).
It should result in all text based columns getting a `CHARACTER SET utf8mb4` clause added to them.

What is the generated SQL for the `AspNetUsers` table?

It might be necessary to post us the actual migration code (or the project if you can). Otherwise, this will be difficult to analyze.
Also, please open another issue for this one, as it seems to be unrelated to the one we fixed.

_Originally posted by @lauxjpn in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1493#issuecomment-924905274_

**Comment by lauxjpn** [comment]
@lauxjpn thanks for looking... I've added you to the repository with the project https://github.com/imalkevich/iotics/tree/iotics/pomelo, maybe this will be helpful?

There are two places you might be interested in :
![image](https://user-images.githubusercontent.com/7044304/134581338-e0f324d0-cc74-44f4-98ab-0212c21bfca2.png)

I will try to output the SQl generated over the weekend and will send you the details.

Thanks

_Originally posted by @imalkevich in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1493#issuecomment-926141430_

**Comment by lauxjpn** [comment]
@imalkevich There are some issues with the already existing migrations.
Is it alright to discuss the migration code and SQL in public (you repo is private after all)?

**Comment by imalkevich** [comment]
@lauxjpn Thanks, sure, we can discuss the issue in public. I'm 99% sure the owner of the project won't agree to give public access to the repository, but maybe I can do something to help the investigation? (I will be thinking on it in the meantime, so maybe I will have some idea how this can be reproduced easier, maybe moving parts into separate application... I will update)

**Comment by lauxjpn** [comment]
I have already looked at it and just wanted to make sure, that discussing it here is fine.

I should mention, that the folling applies to the `origin/iotics/pomelo` branch, but with the `builder.HasCharSet("utf8mb4");` line removed from `ApplicationDbContext.OnModelCreating()`.

---

The first issue is, that the migrations don't work in the way they have been created. The migration `20201205084841_AddClientConnections` cannot drop the `IX_Settings_LocationId` index, because it is used in another FK relationship:

<details>
<summary>20201205084841_AddClientConnections.cs</summary>

```diff
diff --git a/Iotics.Admin/Iotics.Api/Migrations/20201205084841_AddClientConnections.cs b/Iotics.Admin/Iotics.Api/Migrations/20201205084841_AddClientConnections.cs
--- a/Iotics.Admin/Iotics.Api/Migrations/20201205084841_AddClientConnections.cs	(revision 8ffdef6cea5b3d9b21cbca0ccf4c746e6cea6a38)
+++ b/Iotics.Admin/Iotics.Api/Migrations/20201205084841_AddClientConnections.cs	(date 1632484601137)
@@ -7,10 +7,6 @@
     {
         protected override void Up(MigrationBuilder migrationBuilder)
         {
-            migrationBuilder.DropIndex(
-                name: "IX_Settings_LocationId",
-                table: "Settings");
-
             migrationBuilder.DropIndex(
                 name: "IX_IpValues_IpString_IpValueSource_DeviceId",
                 table: "IpValues");
@@ -158,11 +154,6 @@
                 oldMaxLength: 128,
                 oldNullable: true);
 
-            migrationBuilder.CreateIndex(
-                name: "IX_Settings_LocationId",
-                table: "Settings",
-                column: "LocationId");
-
             migrationBuilder.CreateIndex(
                 name: "IX_Settings_Name",
                 table: "Settings",
```

</details>

Next, I am getting the same error you described above, but already for the `20210702211637_AddUserAutomationNotifications` migration, because the migration tries to setup an FK between `` `ApplicationUserAutomationNotifications`.`AutomationId` varchar(255) CHARACTER SET utf8mb4 NULL `` and `` `Automations`.`Id` varchar(255) NOT NULL `` (which is `latin1` by default), and also between `` `ApplicationUserAutomationNotifications`.`UserId` varchar(255) CHARACTER SET utf8mb4 NULL `` and `` `AspNetUsers`.`Id` varchar(255) NOT NULL `` (which is `latin1` by default).

So the error you describe even appears in the already existing migrations. To fix it for the `ApplicationUserAutomationNotifications` table, the simplest way is to make the `UserId` and `AutomationId` columns of the `ApplicationUserAutomationNotifications` table use the database default character set (which should be `latin1` by default):

<details>
<summary>20210702211637_AddUserAutomationNotifications.cs</summary>

```diff
diff --git a/Iotics.Admin/Iotics.Api/Migrations/20210702211637_AddUserAutomationNotifications.cs b/Iotics.Admin/Iotics.Api/Migrations/20210702211637_AddUserAutomationNotifications.cs
--- a/Iotics.Admin/Iotics.Api/Migrations/20210702211637_AddUserAutomationNotifications.cs	(revision 8ffdef6cea5b3d9b21cbca0ccf4c746e6cea6a38)
+++ b/Iotics.Admin/Iotics.Api/Migrations/20210702211637_AddUserAutomationNotifications.cs	(date 1632507154778)
@@ -12,10 +12,8 @@
                 {
                     Id = table.Column<string>(type: "varchar(255)", nullable: false)
                         .Annotation("MySql:CharSet", "utf8mb4"),
-                    UserId = table.Column<string>(type: "varchar(255)", nullable: true)
-                        .Annotation("MySql:CharSet", "utf8mb4"),
+                    UserId = table.Column<string>(type: "varchar(255)", nullable: true),
                     AutomationId = table.Column<string>(type: "varchar(255)", nullable: true)
-                        .Annotation("MySql:CharSet", "utf8mb4")
                 },
                 constraints: table =>
                 {
@@ -32,8 +30,7 @@
                         principalTable: "Automations",
                         principalColumn: "Id",
                         onDelete: ReferentialAction.Cascade);
-                })
-                .Annotation("MySql:CharSet", "utf8mb4");
+                });
 
             migrationBuilder.CreateIndex(
                 name: "IX_ApplicationUserAutomationNotifications_AutomationId",
```

</details>

I am then getting this error for later migrations as well, so the same fix needs to be applied there too:

<details>
<summary>20210722135203_AddUserDevicesAndDeviceNotifications.cs</summary>

```diff
diff --git a/Iotics.Admin/Iotics.Api/Migrations/20210722135203_AddUserDevicesAndDeviceNotifications.cs b/Iotics.Admin/Iotics.Api/Migrations/20210722135203_AddUserDevicesAndDeviceNotifications.cs
--- a/Iotics.Admin/Iotics.Api/Migrations/20210722135203_AddUserDevicesAndDeviceNotifications.cs	(revision 8ffdef6cea5b3d9b21cbca0ccf4c746e6cea6a38)
+++ b/Iotics.Admin/Iotics.Api/Migrations/20210722135203_AddUserDevicesAndDeviceNotifications.cs	(date 1632508640299)
@@ -31,7 +31,6 @@
                     CreationDate = table.Column<DateTime>(type: "datetime(6)", nullable: false),
                     UpdatedDate = table.Column<DateTime>(type: "datetime(6)", nullable: true),
                     UserId = table.Column<string>(type: "varchar(255)", nullable: false)
-                        .Annotation("MySql:CharSet", "utf8mb4")
                 },
                 constraints: table =>
                 {
@@ -42,8 +41,7 @@
                         principalTable: "AspNetUsers",
                         principalColumn: "Id",
                         onDelete: ReferentialAction.Cascade);
-                })
-                .Annotation("MySql:CharSet", "utf8mb4");
+                });
 
             migrationBuilder.CreateTable(
                 name: "DeviceNotifications",
@@ -55,8 +53,7 @@
                         .Annotation("MySql:CharSet", "utf8mb4"),
                     EventFiredDate = table.Column<DateTimeOffset>(type: "datetime(6)", nullable: false),
                     CreatedDate = table.Column<DateTime>(type: "datetime(6)", nullable: false),
-                    UserId = table.Column<string>(type: "varchar(255)", nullable: true)
-                        .Annotation("MySql:CharSet", "utf8mb4"),
+                    UserId = table.Column<string>(type: "varchar(255)", nullable: true),
                     DeviceId = table.Column<string>(type: "varchar(255)", nullable: true)
                         .Annotation("MySql:CharSet", "utf8mb4")
                 },
@@ -75,9 +72,8 @@
                         principalTable: "UserDevices",
                         principalColumn: "Id",
                         onDelete: ReferentialAction.Cascade);
-                })
-                .Annotation("MySql:CharSet", "utf8mb4");
-
+                });
+            
             migrationBuilder.CreateIndex(
                 name: "IX_DeviceNotifications_DeviceId",
                 table: "DeviceNotifications",
```

</details>

<details>
<summary>20210724084231_RenameDeviceNotificationsToUserNotifications.cs</summary>

```diff
diff --git a/Iotics.Admin/Iotics.Api/Migrations/20210724084231_RenameDeviceNotificationsToUserNotifications.cs b/Iotics.Admin/Iotics.Api/Migrations/20210724084231_RenameDeviceNotificationsToUserNotifications.cs
--- a/Iotics.Admin/Iotics.Api/Migrations/20210724084231_RenameDeviceNotificationsToUserNotifications.cs	(revision 8ffdef6cea5b3d9b21cbca0ccf4c746e6cea6a38)
+++ b/Iotics.Admin/Iotics.Api/Migrations/20210724084231_RenameDeviceNotificationsToUserNotifications.cs	(date 1632508751250)
@@ -20,8 +20,7 @@
                         .Annotation("MySql:CharSet", "utf8mb4"),
                     EventFiredDate = table.Column<DateTimeOffset>(type: "datetime(6)", nullable: false),
                     CreatedDate = table.Column<DateTime>(type: "datetime(6)", nullable: false),
-                    UserId = table.Column<string>(type: "varchar(255)", nullable: true)
-                        .Annotation("MySql:CharSet", "utf8mb4"),
+                    UserId = table.Column<string>(type: "varchar(255)", nullable: true),
                 },
                 constraints: table =>
                 {
@@ -32,8 +31,7 @@
                         principalTable: "AspNetUsers",
                         principalColumn: "Id",
                         onDelete: ReferentialAction.Cascade);
-                })
-                .Annotation("MySql:CharSet", "utf8mb4");
+                });
 
             migrationBuilder.CreateIndex(
                 name: "IX_UserNotifications_UserId",
```

</details>

Now, the migrations can finally be applied.

---

The main issue with the state of the model is, that the charsets that are actually used in the database, are not the ones that the Pomelo model definition thinks should be there.
For example, you model makes Pomelo believe, that all text based columns are currently `utf8mb4`, all tables as well and even the database default character set too.
It appears, that migration operations where manually removed from `Up()` / `Down()` methods of some previous migrations, but the model itself was not manually updated accordingly, and therefore, what is now in the database is not what Pomelo thinks is there.

The charset inconsistency situation looks like this:

charset | columns
--- | ---
latin1 | 115
utf8mb4 | 38

The simplest way to fix this, is probably to reset the character set of all columns, tables and even the database itself, to the same charset. I would suggest to use `utf8mb4` for that.
The process to do this would be like the following:

### 1. Resetting the model to another charset

Since the EF Core model definition currently thinks, that everything is already `utf8mb4` (because it is the Pomelo default and nothing was explicitly setup otherwise), we first need to convince the model that we are actually using another charset for everything:

<details>
<summary>ApplicationDbContext.cs</summary>

```diff
diff --git a/Iotics.Admin/Iotics.Api/Data/ApplicationDbContext.cs b/Iotics.Admin/Iotics.Api/Data/ApplicationDbContext.cs
--- a/Iotics.Admin/Iotics.Api/Data/ApplicationDbContext.cs	(revision 7a29ac346b968b9f2a919986e3a5b22d4ecf1479)
+++ b/Iotics.Admin/Iotics.Api/Data/ApplicationDbContext.cs	(date 1632510203173)
@@ -87,7 +87,7 @@
         {
             base.OnModelCreating(builder);
 
+            builder.HasCharSet("latin1");
 
             // ApplicationUser
             builder.Entity<ApplicationUser>(user => {
```

</details>

The actual charset we are using here does not matter, as long as it is not `utf8mb4`.

We then add a migration for this change: `dotnet ef migrations add InternallyResetCharSetToLatin1`.

This will result in a lot of migration operations, that we don't need to apply (because we don't really want to change the database objects to this temporary charset) and therefore, we can just delete all statements from the `Up()` and `Down()` methods. The result is an empty migration, but a model that now thinks that everything is `latin1`.

Now, we would like to do the same again for `utf8mb4`, and actually keep all those migration operations this time, so they get applied to the database. The problem is, that we cannot change the charset of columns, that are referenced in a foreign key relationship.
Therefore, we first need to drop all FKs, then alter the column's charsets, and finally create all FKs again.

### 2. Temporarily remove all FKs

The simplest way to temporarily remove all foreign keys should have been to just manually remove them in a loop at the end of the `ApplicationDbContext.OnModelCreating()` method like this:

<details>
<summary>ApplicationDbContext.cs</summary>

```diff
diff --git a/Iotics.Admin/Iotics.Api/Data/ApplicationDbContext.cs b/Iotics.Admin/Iotics.Api/Data/ApplicationDbContext.cs
--- a/Iotics.Admin/Iotics.Api/Data/ApplicationDbContext.cs	(revision 77e97e90ff32d6fd235d76082bf4627ba63c2a24)
+++ b/Iotics.Admin/Iotics.Api/Data/ApplicationDbContext.cs	(date 1632511583739)
@@ -1,4 +1,5 @@
 using System;
+using System.Linq;
 using Iotics.Api.Models;
 using Microsoft.AspNetCore.Identity;
 using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
@@ -395,6 +396,15 @@
             builder.Entity<RoomViewStatistic>().ToView(nameof(RoomViewStatistic));
             builder.Entity<UserConnection>().ToView(nameof(UserConnection));
             builder.Entity<UserUptimeStatistic>().ToView(nameof(UserUptimeStatistic));
+            
+            // Temporarily remove all FKs.
+            foreach (var entityType in builder.Model.GetEntityTypes())
+            {
+                foreach (var foreignKey in entityType.GetForeignKeys().ToList())
+                {
+                    entityType.RemoveForeignKey(foreignKey);
+                }
+            }
         }
     }
 }
```

</details>

We then add a migration for this change: `dotnet ef migrations add TemporarilyRemoveAllForeignKeys`.
The generated `Up()` method now contains `DropForeignKey` operations. However, for some reason it also contains other operations and not all the `DropForeignKey` operations we expected...weird. Probably some convention issue.

Of course it is always possible to manually add the missing `DropForeignKey` operations and remove any non-`DropForeignKey` operations from then `Up()` method.

Do the same in the `Down()` method, just for the `AddForeignKey` operations this time.

When we apply this migration to a database, we should now have a database without foreign keys.

### 3. Setting the model to `utf8mb4`

Now we can set the model character set again, but this time to `utf8mb4`. Since this is the default anyway, we can either just remove the `builder.HasCharSet("latin1");` call, or change it to `builder.HasCharSet("utf8mb4");`. Both does the same.
We then add a migration for this change: `dotnet ef migrations add ResetCharSetToUtf8Mb4`.

The result is an `Up()` methods with a single `AlterDatabase` operation, a `AlterTable` operation for each table and a `AlterColumn` operation for each column.

### 2. Recreate the temporarily removed FKs

Just by removing the loop we created earlier, we should have been able to recreate all FKs.

We then add a migration for this change: `dotnet ef migrations add RecreateTemporarilyRemovedForeignKeys`.

If this doesn't work, we can manually add the necessary operations to the `Up()`/`Down()` methods.

The database should now be back in a consistent state with the model and all text based columns should be `utf8mb4`.

(I'll take a closer look at the `entityType.RemoveForeignKey(foreignKey);` weirdness tomorrow. But it is probably an EF Core bug.)

**Comment by imalkevich** [comment]
@lauxjpn Thanks a lot! Following the steps fixed the issue! My sincerest appreciation of your time and efforts!

**Comment by lauxjpn** [comment]
No worries, I'm glad it worked.
