### ISSUE TITLE
Scaffolding boolean values not working ...

### ISSUE THREAD

**Issue by lpghartz** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#153]
There appears to be an incompatibility between EF7 and the Pomelo scaffolding code, or perhaps a bug entirely in the Pomelo code. (Its unclear which, as the error comes from deep in EF).

The issue is a scaffolded set of classes created against a table that has tinyint(1) columns used as Boolean flags is created as an sbyte? type in the entity class, but something else in the system is treating it as a Boolean. As a result, entities can't be retrieved from the database without an exception.  While, in this case, the tinyint(1) column *is* Boolean data, a tinyint(1) is a full byte, so the conversion the scaffolding did may be "right", its just incompatible with what something else is doing. 

The exception:

Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler:Error: An exception occurred in the database while iterating the results of a query.

System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'System.SByte'.
   at Microsoft.EntityFrameworkCore.Storage.SynchronizedMySqlDataReader.ConvertWithReflection[T](Int32 ordinal, InvalidCastException e)
   at Microsoft.EntityFrameworkCore.Storage.SynchronizedMySqlDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.MySqlQueryingEnumerable`1.MySqlEnumerator.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass20_0`1.<CompileQueryCore>b__0(QueryContext qc)

This problem happens on all of the classes with a tinyint(1) column, so its easy to reproduce.

**Comment by lpghartz** [comment]
Actually, there's more problems than that one...  char(n) columns are being scaffolded as "char?" types, which causes a similar casting error from String to char. And its not just char(1) fields being scaffolded as char, its any char column... so a char(2) and a char(10), at a minimum, in my database both ended up as "char?" types. 

With both sets of errors, a bulk replace of "char" with "string" and "sbyte" with "bool" resolved the runtime errors, so there's a work-around...

**Comment by Kagamine** [comment]
@lpghartz Not all tinyint(1) are boolean. So we won't treat tinyint(1) as boolean.

**Comment by lpghartz** [comment]
Yes, I'm aware. I even said that above. 

The issue is that something -- either in your code, or in EF -- *is* treating it as a Boolean. 

From the stacktrace, Microsoft.EntityFrameworkCore.Storage.SynchronizedMySqlDataReader.GetFieldValue is clearly has an instance of a Boolean that its trying to set into the sbyte in ConvertWithReflection[T]... which won't work. 

From my standpoint, I can change the code that the scaffolding created. I can't change what GetFieldValue is doing. So the "fix" (temporary or otherwise) of changing the sbyte to bool works, for me, even if the correct fix is for the code to not treat the tinyint(1) as a Boolean. If that's actually your code doing that, then the fix is to change the code incorrectly treating it as a Boolean. If its not your code, but rather Microsoft's, then right or wrong, your code needs to treat it as a Boolean because you simply can't use the Pomolo code currently with a database that uses tinyint(1). 

The char issue is pretty cut and dry wrong though -- char and varchar should both always be strings, and never should be a char datatype.

**Comment by Kagamine** [comment]
So, I wanna know which pomelo version were you using. There was an upstream issue: https://github.com/mysql-net/MySqlConnector/issues/141. I think it was already shipped in 1.1.1-prerelease-*

**Comment by lpghartz** [comment]
"Pomelo.EntityFrameworkCore.MySql": "1.1.1-prerelease-10001",

Pulled yesterday. 

Its an interesting discussion, but it looks like the issue isn't quite that. It'd be fine if the system entirely treated tinyint(1) as a bool, or as an sbyte. The problem is, it seems the code that populates the entity is treating it one way, and the code retrieving it from the database is treating it the other. 

From our standpoint, it'd be great to just tell the system to treat them as bool, because we have hundreds of them across a hundred tables, and every single one *is* a Boolean. But I can live with them being sbytes, as long as I can read them from the database. It just means a lot of if (foo == 1) instead of if (foo) in the code. Not a big deal.

**Comment by mguinness** [comment]
@lpghartz Please create another issue for the char to string problem.  With regards to tinyint(1) to bool issue, you can now use `TreatTinyAsBoolean=false` option in the connection string to override the default behavior of MySqlConnector.

However, tinyint will still be scaffolded as sbyte not bool - you can use bit type in MySQL to get that behavior if you prefer.   As you correctly surmised you can always change the types after scaffolding to suit your preferences.

**Comment by lpghartz** [comment]
I'll do that with the char issue. I suggest rethinking the scaffolding strategy, as well. If TreatTinyAsBoolean is being considered default, now, than the default for scaffolding should match. The scaffold code gets the connection string, it should be able to default the same way the underlying DB code is defaulting.

**Comment by Kagamine** [comment]
@lpghartz we already discussed tinyint(1) => sbyte or boolean, and the result is sbyte.

**Comment by lpghartz** [comment]
I think you need to call this out more explicitly, then -- if you're saying you're going to knowingly and deliberately create scaffolds that do not work out of the box for every single database that uses a tinyint(1), that's something people need to know when choosing to waste time on looking at your particular option for connecting to MySQL. Because the fact is, the default you have chosen and the default the upstream has chosen are mutually incompatible. At a minimum, you should patch, in your version, to have the default be false, not true, for TreatTinyAsBoolean. Then things would be inconsistent with other providers, but would at least work.

**Comment by caleblloyd** [comment]
Can we detect `TreatTinyAsBoolean` option in the connector, and scaffold according to the setting?  So if `TreatTinyAsBoolean=true` then we scaffold `TINYINT(1)` as `bool`, but if `TreatTinyAsBoolean=false` then we scaffold `TINYINT(1)` as `sbyte/byte`?

**Comment by Kagamine** [comment]
It is hard to implement, because we cannot inject MySqlConnection in MySqlTypeMapper.cs

**Comment by caleblloyd** [comment]
Moved to #163

**Comment by bluee** [comment]
Can we have an option when running scaffolding that will treat it as either sbyte or boolean instead of the one size fits all approach?

**Comment by darkguy2008** [comment]
I'm having the same issue right now with 2.1.0-rc1-final. My MySQL table has a tinyint(1) in place of a boolean as it was made with FluentMigrator (which makes sense as it seems it should be used instead of BIT -> https://www.xaprb.com/blog/2006/04/11/bit-values-in-mysql/ ) and there's no way to fix this other than manually editing the generated models. Any ideas?
