### ISSUE TITLE
Additional information: Translation of method 'string.Contains' failed

### ISSUE THREAD

**Issue by CwjXFH** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1536]
### Steps to reproduce
When I upgrade Pomelo.EntityFrameworkCore.MySql from **3.2.0** to **5.0.1**, execute query will throw exception.
linq query like this: 
```c#
.Where(e=>e.No.Contains(request.No, StringComparison.OrdinalIgnoreCase)
```

### The issue

```
System.InvalidOperationException: The LINQ expression 'DbSet<SalesOrderEntity>()
.Where(s => __ef_filter__IgnoreDeleted_0 || s.IsDeleted == __ef_filter__Deleted_1)
.Where(s => s.CustomerOrderNo.Contains(value: "4200001599", comparisonType: OrdinalIgnoreCase))' could not be translated. Additional information: Translation of method 'string.Contains' failed.

Translation of the 'String.Contains' overload with a 'StringComparison' parameter is not supported by default. To opt-in to translations of methods with a 'StringComparison' parameter, call `EnableStringComparisonTranslations` on your MySQL specific 'DbContext' options.
```

And I can't found EnableStringComparisonTranslations on google.

### Further technical details

MySQL version: **8.0.12**
Operating system: **win10**
Pomelo.EntityFrameworkCore.MySql version: **5.0.1**
Microsoft.AspNetCore.App version: **netcoreapp3.1**

Other details about my project setup:

**Comment by mguinness** [comment]
> Translation of the 'String.Contains' overload with a 'StringComparison' parameter is not supported by default. To opt-in to translations of methods with a 'StringComparison' parameter, call `EnableStringComparisonTranslations` on your MySQL specific 'DbContext' options.

See [EnableStringComparisonTranslations](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/wiki/Configuration-Options#enablestringcomparisontranslations) option.
