### ISSUE TITLE
Scaffolding char database columns incorrectly creates char properties

### ISSUE THREAD

**Issue by lpghartz** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#154]
Database columns with "char" datatypes as opposed to "varchar" are being created as "char" types in the resulting scaffold code. They should always be created as string types. 

(This is true of both char(1) and char(n) -- they all get created as char or char? depending on the nullability of the column.)

**Comment by Kagamine** [comment]
Fixed in 8b48c03
