### ISSUE TITLE
Incorrect string value: '\x99\xBDhM\xA0N...'

### ISSUE THREAD

**Issue by ClementeGao** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1547]
```
An exception occurred in the database while saving changes for context type 'PurchaseReceiving.Infrastructure.Nxin_Qlw_BusinessContext'
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> MySqlConnector.MySqlException (0x80004005): Incorrect string value: '\\x99\\xBDhM\\xA0N...' for column 'Guid' at row 1
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 890
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 314
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 307
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> MySqlConnector.MySqlException (0x80004005): Incorrect string value: '\x99\xBDhM\xA0N...' for column 'Guid' at row 1
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 890
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition
```

please help see this question, i am really don't know why

**Comment by mguinness** [comment]
With the limited information that you have provided it appears that you have an issue with your charsets, see https://dba.stackexchange.com/questions/161460 for more information.

**Comment by ClementeGao** [comment]
@mguinness 
![image](https://user-images.githubusercontent.com/16145998/140599355-54fa9ee4-fc43-41fb-a60f-3fbf981fdd60.png)
now the domain layer have a Pomelo.EntityFrameworkCore.MySql package  and the Infrastructure layer have a Pomelo.EntityFrameworkCore.MySql, when i remove Pomelo.EntityFrameworkCore.MySql from domain layer it work well, i don't know why 
![image](https://user-images.githubusercontent.com/16145998/140599429-7438f6d9-60f4-491d-aee9-787312fea5a6.png)
![image](https://user-images.githubusercontent.com/16145998/140599441-10ffb6de-5886-428f-b04b-eb1599296fae.png)

**Comment by mguinness** [comment]
Really there's not enough information to go on, what is the DDL for the table you're inserting into?

**Comment by lauxjpn** [comment]
@ClementeGao First, fill-out the issue template (containing the version that you are using). We are not able to help you otherwise.
In addition to that, please post the connection string options and `DbContext` options you are using.

I came across the same exception while upgrading Pomelo for EF Core 6 RC2.

**Comment by ClementeGao** [comment]
@mguinness  yes i am adding  a data this is my code
```
var appid = "111111111";
                string numericalOrder = await _numericalOrderCreator.CreateAsync();
                Biz_Review review = new Biz_Review(long.Parse(numericalOrder), long.Parse(appid), long.Parse(_identityService.UserId)).SetMaking();
                _businessContext.Set<Biz_Review>().Add(review);
                await _businessContext.SaveChangesAsync();
                _logger.LogError("插入成功，准备删除");
```


@lauxjpn sorry let me provide you some info 

- Pomelo.EntityFrameworkCore.MySql version is 5.0.1
- the connectionstring is 
```
Server=xxxx;port=1337;database=xxx;user=xxx;pwd=xxxx;Pooling=True;Max Pool Size=2000;Min Pool Size=5;Connect Timeout=45;Connection Lifetime=3600;charset=utf8mb4;
```
- the dbcontext is
```
public partial class MyDbContext : EFContext
    {
        public DbSet<Review> Reviews { get; set; }

        public MyDbContext (DbContextOptions options, IMediator mediator) : base(options, mediator)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // the ReviewEntityConfigurations is empty  ignore it
            modelBuilder.ApplyConfiguration(new ReviewEntityConfigurations());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
```

**Comment by lauxjpn** [comment]
@ClementeGao I cannot replicate the issue. The following code runs fine (using EF Core 5.0.12, Pomelo 5.0.1/5.0.2, MySqlConnector 1.3.13):

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class Review
    {
        [Key]
        public int RecordID { get; set; }
        public Guid Guid { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<Review> Reviews { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1547";
            var serverVersion = ServerVersion.AutoDetect(connectionString);

            optionsBuilder
                .UseMySql(connectionString, serverVersion)
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var review = new Review { Guid = Guid.NewGuid() };
            context.Set<Review>().Add(review);
            
            context.SaveChanges();
        }
    }
}
```

</details>

<details>
<summary>Output</summary>

```sql
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.

info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 5.0.10 initialized 'Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: ServerVersion 8.0.25-mysql SensitiveDataLoggingEnabled DetailedErrorsEnabled

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (41ms) [Parameters=[], CommandType='Text', CommandTimeout='30']

      DROP DATABASE `Issue1547`;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']

      CREATE DATABASE `Issue1547`;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (28ms) [Parameters=[], CommandType='Text', CommandTimeout='30']

      ALTER DATABASE CHARACTER SET utf8mb4;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (60ms) [Parameters=[], CommandType='Text', CommandTimeout='30']

      CREATE TABLE `Reviews` (
          `RecordID` int NOT NULL AUTO_INCREMENT,
          `Guid` char(36) COLLATE ascii_general_ci NOT NULL,
          CONSTRAINT `PK_Reviews` PRIMARY KEY (`RecordID`)
      ) CHARACTER SET utf8mb4;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (14ms) [Parameters=[@p0='811d8726-e986-48b3-bbce-3c15b5c7f831'], CommandType='Text', CommandTimeout='30']

      INSERT INTO `Reviews` (`Guid`)
      VALUES (@p0);
      SELECT `RecordID`
      FROM `Reviews`
      WHERE ROW_COUNT() = 1 AND `RecordID` = LAST_INSERT_ID();
```

</details>

Please provide us with the following information, so we can investigate this further:

* What version of **MySqlConnector** are you using?
* Is there any Fluent API in regards to the `Review` entity or the model/`DbContext` in general? If so, please post it.
* Post the `CREATE TABLE` statement for the table of the `Review` entity in the database you are using (by executing `SHOW CREATE TABLE yourTableName;`).
* Log the failing SQL query generated by EF Core and post it.

**Comment by ClementeGao** [comment]
@lauxjpn the following is create table info 
CREATE TABLE `reviwe` (
  `RecordID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `NumericalOrder` bigint(20) NOT NULL,
  `Guid` char(36) NOT NULL ,
  `ReviweType` bigint(20) NOT NULL ,
  `Level` bigint(20) NOT NULL,
  `CheckMark` int(3) DEFAULT '0' ,
  `CheckedByID` bigint(20) NOT NULL ,
  `CreatedDate` datetime NOT NULL ,
  `ModifiedDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `AppID` bigint(20) DEFAULT NULL ,
  PRIMARY KEY (`RecordID`),
  KEY `NumericalOrder` (`NumericalOrder`),
  KEY `idx_ReviweType` (`ReviweType`),
  KEY `idx_CheckedByID` (`CheckedByID`),
  KEY `biz_reviwe_CheckMark_index` (`CheckMark`)
) ENGINE=InnoDB AUTO_INCREMENT=119091803 DEFAULT CHARSET=utf8

**Comment by lauxjpn** [comment]
The `` `Guid` char(36) NOT NULL `` statement looks similar to mine: `` `Guid` char(36) COLLATE ascii_general_ci NOT NULL ``.

---

@ClementeGao Some requested information is still missing.

Please provide us with the following information, so we can investigate this further:

- [ ] What version of **MySqlConnector** are you using?
- [ ] Is there any Fluent API in regards to the `Review` entity or the model/`DbContext` in general? If so, please post it.
- [x] Post the `CREATE TABLE` statement for the table of the `Review` entity in the database you are using (by executing `SHOW CREATE TABLE yourTableName;`).
- [ ] Log the failing SQL query generated by EF Core and post it.

**Comment by ClementeGao** [comment]
@lauxjpn  the MySqlConnector is 1.3.10       
![image](https://user-images.githubusercontent.com/16145998/140939728-9a561334-6212-44f0-ba87-18a312820a9f.png)

the configuration is     
![image](https://user-images.githubusercontent.com/16145998/140939944-48b4f8d4-3ecd-44cd-b805-8758b2f4a3e2.png)

**Comment by lauxjpn** [comment]
>```sql
>@p2='?' (Size = 16) (DbType = Binary)
>INSERT INTO `Review` (`Guid`) values (p2)
>```

So it looks like that Pomelo thinks your `Review.Guid` column is a `binary`/`byte[]` column, when in fact it is a `char(36)`/`string` column.

However, with the information provided so far, we cannot figure-out why that is the case.

---

You could try to add the following connection string option to your existing connection string and see whether it makes a difference or not:

```
GuidFormat=Char36
```

---

@ClementeGao Can you change the sample code that posted above, so that it reproduces the issue?

**Comment by ClementeGao** [comment]
@lauxjpn  i try  add GuidFormat=Char36 to connectionstring but it don't work, i don't know why is binary type 
 @p2='0xB396A9596B3367468
E10A5F984BE4AD5' (Nullable = false) (Size = 16), INSERT INTO `Review` (`Guid`) values (p2)

**Comment by lauxjpn** [comment]
As i said above, we cannot investigate this much further without more information (or code).

Please post the code that creates your `DbContext` (e.g. calling `AddDbContext()`).

Of course you can also try to just use the latest version `6.0.0` or `5.0.3`.

**Comment by ClementeGao** [comment]
@lauxjpn let me tell you my test result for a few days .
i have two projects  their class library version is the same
but  when i post them to production env. A project not work .but B project is ok .  I checked the version of the version and the character set of the table with the field type field  they are same next week i will continue to troubleshoot the question and thank you for your reply

**Comment by mguinness** [comment]
Are the projects on the same server or different servers?  I did notice that code posted above has both `reviwe` and `review`, is it possible multiple objects exists in the database?

**Comment by ClementeGao** [comment]
@mguinness sorry, i was wrong,  is review, it is really a object which is review  they are  on the same  server, now i find solution, but i still don't understand why   thank your reply! the following is my way
1、remove the configuration for entiy to table
2、the connectionstring add Old Guids=true
![image](https://user-images.githubusercontent.com/16145998/141726609-0fea7212-fa68-45e7-9401-f0f630c41c43.png)
