### ISSUE TITLE
[MariaDB] Timestamp columns are using expressions without it being implicitly said so

### ISSUE THREAD

**Issue by JamesParkDev** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1559]
### Steps to reproduce

Create a simple base entity

```cs
    public class BaseEntity
    {
        [Key]
        [Column("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid Id { get; set; }
        
        [Column("date_created", TypeName = "TIMESTAMP")]
        [Required]
        public DateTime DateCreated { get; set; }
        
        [Required]
        [Column("last_update", TypeName = "TIMESTAMP")]
        public DateTime LastUpdate { get; set; }
    }
```

inherit this with any class you want ex user

### The issue
It keeps setting `last_update` and `date_created` columns with default expression value: (while using dotnet-ef tool)

![image](https://user-images.githubusercontent.com/36516118/141650485-5fdb002c-0a76-4193-b84c-cbceeda40621.png)

There should be way to overwrite this and set these columns to some other date like `0000-00-00 00:00:00` (default) or nothing at all.

Is there any way to remove those default expressions ?

### Further technical details

MySQL version: 10.5 (MARIA DB)
Operating system: Win 10 21H1
Pomelo.EntityFrameworkCore.MySql version: 5.0.3
Microsoft.AspNetCore.App version: 5.0.11

Other details about my project setup:

- Just using docker

**Comment by mguinness** [comment]
See [Generated Values](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties).

**Comment by lauxjpn** [comment]
@JamesParkDev If you are using `TIMESTAMP`, Pomelo will setup the column to use `CURRENT_TIMESTAMP()` by default, as long as you don't explicitly set it up to something else (as @mguinness referenced).

If you don't want this default behavior for a `DateTime` property, don't use `timestamp`. Use `datetime(6)` or `datetime` (or no explicit SQL type at all, which defaults to `datetime(6)`);

**Comment by JamesParkDev** [comment]
> @JamesParkDev If you are using `TIMESTAMP`, Pomelo will setup the column to use `CURRENT_TIMESTAMP()` by default, as long as you don't explicitly set it up to something else (as @mguinness referenced).
> 
> If you don't want this default behavior for a `DateTime` property, don't use `timestamp`. Use `datetime(6)` or `datetime` (or no explicit SQL type at all, which defaults to `datetime(6)`);

I see, thank you.
