### ISSUE TITLE
Explicitly using NVARCHAR (UPPERCASE) should not emit CHARACTER SET utf8mb4 clause

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1565]
@lauxjpn  This issue seems to not be fully resolved, if I set the TypeName to NVARCHAR in my entity's column attribute, the migration will add CHARACTER SET utf8mb4 and that will cause an error!
Here is my entity:

```c#
    public class Country
    {
        [Required, Key, Column("Id")]
        public uint CountryId { get; set; }

        [Required, Column(TypeName = "NVARCHAR"), StringLength(45)]
        public string Code { get; set; }

        public ICollection<Author> Authors { get; set; }
    }
```

The migration will genreate this SQL query:

```sql
     CREATE TABLE `Countries` (
          `Id` int unsigned NOT NULL AUTO_INCREMENT,
          `Code` NVARCHAR(45) CHARACTER SET utf8mb4 NOT NULL, /* When the type is NVARCHAR we can't use 'CHARACTER SET utf8mb4'*/
          CONSTRAINT `PK_Countries` PRIMARY KEY (`Id`)
      ) CHARACTER SET utf8mb4;
```

If we define the column's type explicitly to NVARCHAR, the CHARACTER SET utf8mb4 should not be added.

_Note: I'm using Pomelo 5.0.3 on a new project._

_Originally posted by @gitown in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1493#issuecomment-968116460_

**Comment by lauxjpn** [comment]
@gitown Independent of the actual issue here, it should be mentioned that `nvarchar` is basically deprecated, because it uses the `utf8` charset, which is not proper UTF-8 but a proprietary implementation by MySQL that is not standard conform.
MySQL has been slowly moving away from that implementation over the course of the last 15 years or so.

Unless there is a specific reason to do otherwise, `utf8` (now called `utf8mb3`) should not be used anymore. Use `utf8mb4` instead.

**Comment by mguinness** [comment]
To corroborate the earlier post, when creating a table with `nvarchar` MySQL 8.0.20 will output the following warning:

`Warning (code 3720): NATIONAL/NCHAR/NVARCHAR implies the character set UTF8MB3, which will be replaced by UTF8MB4 in a future release. Please consider using CHAR(x) CHARACTER SET UTF8MB4 in order to be unambiguous.`

**Comment by lauxjpn** [comment]
Looks like this is just a casing issue. If you use `nvarchar` instead of `NVARCHAR` it works fine.
