### ISSUE TITLE
DefaultValue attribute isn't taken into account during the migration

### ISSUE THREAD

**Issue by gitown** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1566]
If I apply the DefaultValue attribute to my property it's not taken into account during the migration
```c#
        [Column(Order = 2), DefaultValue(1)]
        public bool Enabled { get; set; }
```
The current workaround is to use Fluent Api to set the default value!

Hope we'll see this issue fixed in the coming Pomelo releases.

### Further technical details

MySQL version: 8.0.27
Pomelo.EntityFrameworkCore.MySql version: 5.0.3
Microsoft.AspNetCore.App version: 5.0

**Comment by mguinness** [comment]
EF Core only interprets attributes defined in the `System.ComponentModel.DataAnnotations.Schema` and `System.ComponentModel.DataAnnotations` namespaces.

Also see https://github.com/dotnet/efcore/issues/17103.  The team have no plans to add additional functionality to data annotations.

Some workarounds are discussed in [What is the Entity Framework Core attribute equivalent to modelBuilder's HasDefaultValueSql?](https://stackoverflow.com/questions/55033666)

**Comment by lauxjpn** [comment]
@gitown It is theoretically possible to implement your own data annotation attribute (or use the `System.ComponentModel.DefaultValueAttribute` one) and hook it up with some class overwrites to the equivalent Fluent API calls, but depending on your scenario, this might be overkill.

As an alternative, in your `OnModelCreating()` method, you could also just iterate over the properties of the entity classes, check for their custom attributes, and setup the default value if they have been annotated with the `System.ComponentModel.DefaultValueAttribute`.
