### ISSUE TITLE
Inefficient query building when using BIT(1) -> bool mappings

### ISSUE THREAD

**Issue by bbepis** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1574]
### Steps to reproduce
Using a model similar to this:
```cs
public class TS4Household
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public ulong ID { get; set; }
    
    public uint? UploaderID { get; set; }
    
    public uint GalleryDownloadCount { get; set; }
    
    [Column(TypeName = "BIT(1)")]
    public bool IsFeatured { get; set; }
    
    [Column(TypeName = "BIT(1)")]
    public bool IsHidden { get; set; }
}
```

And a table schema similar to the following:
```sql
CREATE TABLE IF NOT EXISTS `ts4households` (
  `ID` bigint unsigned NOT NULL AUTO_INCREMENT,
  `UploaderID` int unsigned DEFAULT NULL,
  `GalleryDownloadCount` int unsigned NOT NULL DEFAULT '0',
  `IsFeatured` bit(1) NOT NULL DEFAULT b'0',
  `IsHidden` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`ID`),
  KEY `IDX_IsFeatured` (`IsFeatured`) USING BTREE,
  KEY `IDX_IsHidden` (`IsHidden`) USING BTREE,
  KEY `IDX_GalleryDownloadCount` (`GalleryDownloadCount`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

```

If relevant, the table has about 250,000 entries.

----

### The issue

Performing a `.Where` on any of the `BIT(1)` columns impacts MySQL's query performance as it doesn't use an equality comparison. This might only apply when doing a join + explicit orderby, however I didn't do extensive testing.

Example generated query for `.Where(x => !x.IsHidden && x.IsFeatured)`:

```sql
SELECT `t`.`ID`, `t`.`IsHidden`, `t`.`IsFeatured`, `t`.`GalleryDownloadCount`, `u`.`Username`
FROM `ts4households` AS `t`
LEFT JOIN `users` AS `u` ON `t`.`UploaderID` = `u`.`ID`
WHERE NOT (`t`.`IsHidden`) AND `t`.`IsFeatured`
ORDER BY `t`.`GalleryDownloadCount` DESC
LIMIT 24 OFFSET 0;
```

![image](https://user-images.githubusercontent.com/36346617/143739648-4441d5be-f4bf-4f69-9573-e58559acb095.png)

Execution time: 00m 16.1779s

Now changing the model to use a byte instead of a bool (and wrapping bool logic with a non-mapped property):

```cs
[Column(TypeName = "BIT(1)")]
public byte IsFeatured { get; set; }

[NotMapped]
public bool IsFeaturedBool
{
    get => IsFeatured == 1;
    set => IsFeatured = value ? (byte)1 : (byte)0;
}

[Column(TypeName = "BIT(1)")]
public byte IsHidden { get; set; }

[NotMapped]
public bool IsHiddenBool
{
    get => IsHidden == 1;
    set => IsHidden = value ? (byte)1 : (byte)0;
}
```

Example generated query now for `.Where(x => x.IsHidden == 0 && x.IsFeatured == 1)`:

```sql
SELECT `t`.`ID`, `t`.`IsHidden`, `t`.`IsFeatured`, `t`.`GalleryDownloadCount`, `u`.`Username`
FROM `ts4households` AS `t`
LEFT JOIN `users` AS `u` ON `t`.`UploaderID` = `u`.`ID`
WHERE `t`.`IsHidden` = 0 AND `t`.`IsFeatured` = 1
ORDER BY `t`.`GalleryDownloadCount` DESC
LIMIT 24 OFFSET 0;
```

![image](https://user-images.githubusercontent.com/36346617/143742223-3391d717-36f3-4bcd-b524-090cf158186a.png)

Execution time: 00m 0.0036s (!!!)

------

Making the wrapper properties feels like a hack rather than a proper solution.

While I understand that explicitly adding the `= 0` and `= 1` would not be appropriate when using `TINYINT` or even a `BIT(1) NULL`, for `BIT(1) NOT NULL` the only possible values in the column are either 0 or 1.

### Further technical details

MySQL version: MySQL 8.0.26
Operating system: Windows 10 x64
Pomelo.EntityFrameworkCore.MySql version: 6.0.0
Microsoft.AspNetCore.App version: 6.0.0

**Comment by CheloXL** [comment]
Not sure if this solves the main issue, but btrees are not good for small sets of highly repeating data. Have you tried changing the index type to HASH?

I'm not sure if connector uses it, but for bool/enum types is the recommended index type.

**Comment by mguinness** [comment]
I think the issue is that your model doesn't properly represent your table.  As you already stated "the only possible values in the column are either 0 or 1"  so the obvious mapping would be `bool` not `byte`.  If you wish to keep `byte` then the LINQ query should be `.Where(x => x.IsHidden == 0x0 && x.IsFeatured == 0x1)` instead.

**Comment by bbepis** [comment]
> Not sure if this solves the main issue, but btrees are not good for small sets of highly repeating data. Have you tried changing the index type to HASH?
> 
> I'm not sure if connector uses it, but for bool/enum types is the recommended index type.

@CheloXL If I could I would, however MySQL does not support HASH indexes for anything that isn't a MEMORY database

Postgres fares a bit better but not by much. No RDBMS properly supports HASH indices, which is unfortunate

----

@mguinness I had a look at my question again and realized I had mistakenly copied the same model twice. The original model was in fact using `bool` properties, and the generated SQL as such is when using `bool` in my model.

I did some more testing and used `TINYINT(1)` instead of `BIT(1)` in my database and got the same result.

But I did get a weird result; if I changed one of the properties (in this case IsFeatured) to TINYINT(1), IsHidden suddenly started to use the correct equality check for some reason:

```sql
SELECT `t`.`ID`, `t`.`IsHidden`, `t`.`IsFeatured`, `t`.`GalleryDownloadCount`, `u`.`Username`
     FROM `ts4households` AS `t`
     LEFT JOIN `users` AS `u` ON `t`.`UploaderID` = `u`.`ID`
     WHERE (`t`.`IsHidden` = 0) AND `t`.`IsFeatured`
     LIMIT @__p_1 OFFSET @__p_0
```

**Comment by mguinness** [comment]
As you're probably already aware MySQL doesn't have a native boolean type like Postgres/MSSQL but both `BOOL` and `BOOLEAN` are synonyms of `TINYINT(1)`.  As discussed in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1010#issuecomment-576042516 it's recommended to use `TINYINT(1)` rather than `BIT(1)` for storing boolean values.  Also note that the connection string property `TreatTinyAsBoolean` defaults to true for this purpose.

> When set to `true`, `TINYINT(1)` values are returned as booleans. Setting this to `false` causes `TINYINT(1)` to be returned as sbyte/byte.

**Comment by bbepis** [comment]
That option was what I needed. Hero

Thanks for the information re: `TINYINT(1)` as well
