### ISSUE TITLE
JsonElementComparer is CC BY-SA 4.0 which is incompatible with MIT license

### ISSUE THREAD

**Issue by murillo128** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1586]
The code in:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/00bfeecd11eeda988d5d934706ff6af6c0a7c13b/src/EFCore.MySql.Json.Microsoft/Storage/ValueComparison/Internal/MySqlJsonMicrosoftValueComparer.cs#L260

Is taken from 
https://stackoverflow.com/a/60592310/2618319

which as stated by the author in his comments:
https://stackoverflow.com/questions/60580743/what-is-equivalent-in-jtoken-deepequals-in-system-text-json/60592310#comment117292494_60592310

is CC BY-SA 4.0,  which is incompatible with the MIT license the project is currently using.

Is there a way we could reimplement that class implementation without reusing the stackoverflow code to keep the MIT licensing for the project?

**Comment by mguinness** [comment]
> is CC BY-SA 4.0, which is incompatible with the MIT license the project is currently using.

The SO post is [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) as described in [licensing](https://stackoverflow.com/help/licensing).  The code is attributed per the license in the comment.

See [Are permissive licenses (MIT/BSD/zlib) compatible with CC-BY?](https://opensource.stackexchange.com/questions/324/are-permissive-licenses-mit-bsd-zlib-compatible-with-cc-by).  If you need clarification, perhaps post a question on [Open Source Stack Exchange](https://opensource.stackexchange.com/) and copy the response here.

>  But the license of part A doesn't impose any restrictions on part B and vice versa

**Comment by murillo128** [comment]
That doesn't seem to be compliant with the CC BY SA 4.0 license:

https://creativecommons.org/licenses/by-sa/4.0/

```
ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
```

Note that MIT license is NOT compatible with CC BY SA 4.0 (GPL is):
https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses

https://opensource.stackexchange.com/questions/7435/mit-licensed-project-with-cc-by-sa-dependency

**Comment by lauxjpn** [comment]
_dbc_ the author of the code has also made the code available on [.NET Fiddle](https://dotnetfiddle.net/ijrDBZ).
According to their [Terms & Conditions](https://dotnetfiddle.net/Terms):

> **2.** When submitting to dotnetfiddle.net service the user grants all other users of dotnetfiddle.net and dotnetfiddle.net the right to view, modify, download, clone and republish the original code.

So technically, we could just remove the attribution comment (or change it to reference .NET Fiddle) and are fine.

---

That being said, it is unlikely that skilled users that publish code on SO have issues with their code being incorporated into community driven open source projects like ours, as long as we link back to their original SO answer.

I'll post a comment on SO and ask _dbc_, whether this is fine.

We can than just reference both postings (.NET Fiddle & SO) in the code.

**Comment by murillo128** [comment]
Indeed the dotnetfiddle terms & conditions looks promising and could allow reusing the code under MIT license. I will double check with our lawyers and get back to you asap.
