### ISSUE TITLE
I just wanted to thank you and I didn't know how

### ISSUE THREAD

**Issue by Nefcanto** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1588]
I was trying to use SQL Server docker container on Debian for 6 months and no matter what I did, it was slow. And I was stuck in the technology.

But you saved me today. Today I could migrate my code to your EF Core adapter, and use MariaDB as my database engine.

I had to thank you all for this amazing, valuable repo. You saved me, and you save many other developers from the slow technologies of Microsoft.

God bless you all. Thank you.

**Comment by lauxjpn** [comment]
@Nefcanto Thanks, we are glad that the Pomelo project helped you in making your work life easier!

/cc @bgrainger, @mguinness
