### ISSUE TITLE
Navigation Properties are null - EF Core 6.0 / .Net Core 6.0

### ISSUE THREAD

**Issue by yanivamrami** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1589]
### Steps to reproduce
Models definition (simplified):
public class Store : BaseEntity
{
     public virtual User? Owner { get; set; }
     public int? OwnerId { get; set; }
}
public class User : BaseEntity
{
     public virtual Store? Store { get; set; }
}
For both models, primary key is defined in BaseEntity as follows:
[Key]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
public int Id { get; set; }

Lazy loading is enabled here:
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder.UseLazyLoadingProxies();
}

and in Program.cs:
builder.Services.AddDbContext<AppDbContext>(opt => opt
    .UseLazyLoadingProxies()
    .ConfigureWarnings(warning => warning.Ignore(CoreEventId.DetachedLazyLoadingWarning))
    .EnableSensitiveDataLogging()
    .UseMySql(
        Globals.DB_CONNECTION_STRING, new MySqlServerVersion(Globals.MYSQL_SERVER_VERSION),
        o => o.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)
            ));

### The issue
Trying to retrieve Store data with the following code:
Store? store = await dbContext.Stores
    .Include(x => x.Owner)
    .FirstOrDefaultAsync(x => x.Owner.Id == ownerId && x.Id == storeId);

I get the Store data but the Owner and OwnerId are null, though I can clearly see OwnerId is defined in the database, for that Store record.

I have also tried to explicitly set the One to One relationship between the two models as follows:
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<User>()
    .HasOne(x => x.Store)
     .WithOne(x => x.Owner) ;
}

But it doesn't help. I also tried to set the foreign key explicitly. Also, didn't help...
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<User>()
    .HasOne(x => x.Store)
     .WithOne(x => x.Owner) 
    .HasForeignKey<Store>(x => x.OwnerId);
}

It looks like the only time it worked is when I changed property names - Owner to User and OwnerId to UserId, but that is not an expected behavior, at least not according to EF Core Relationship docs at https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#fully-defined-relationships

If you are seeing an exception, include the full exceptions details (message and stack trace).
N/A
```
Exception message:
Stack trace:
```

### Further technical details

MySQL version: 8.0.27
Operating system: Mac Big Sur 11.6
Pomelo.EntityFrameworkCore.MySql version: 6.0.0
Microsoft.AspNetCore.App version: 6.0.0

Other details about my project setup:

**Comment by yanivamrami** [comment]
Looks like issue can be closed.
Apparently, I was using AutoMapper which set those specific objects (Owner and OwnerId) to null.

Sorry for the trouble.

**Comment by lauxjpn** [comment]
@yanivamrami Glad you figured it out and thanks for letting us know what the issue was!
