### ISSUE TITLE
Do you plan to support querying JSON arrays in the future?

### ISSUE THREAD

**Issue by 15192095633** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1599]
for example `select * from log2 where JSON_CONTAINS(data,JSON_OBJECT('id', "142"))`

**Comment by mguinness** [comment]
While waiting for upstream work on [JSON columns](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/plan#json-columns), this provider has implemented support for both Microsoft and Newtonsoft stacks - see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/14#issuecomment-725257107 for examples.  Also see the test cases in [JsonPocoQueryTestBase](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/EFCore.MySql.FunctionalTests/Query/JsonPocoQueryTestBase.cs) for help.

**Comment by 15192095633** [comment]
Let me close this problem.thank you.
