### ISSUE TITLE
is System.ComponentModel.DataAnnotations.Schema supported for Database-First?

### ISSUE THREAD

**Issue by JayMoorhouse** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1605]
I apologize if this isn't the place for this question; I've been reading the docs and haven't found any reference.

Basically I have
```
[Table("viewOfTable")]
public class Table
{
...
```

Yet it still is mapping to "Table" instead of the view "viewOfTable". This something I do with regular EF Core all the time, just curious if this is supported and if so what the syntax may be?

Thanks so much

**Comment by lauxjpn** [comment]
@JayMoorhouse According to [Entity Types: Table name](https://docs.microsoft.com/en-us/ef/core/modeling/entity-types?tabs=data-annotations#table-name), this should work. Let me check...

There is also [Entity Types: View mapping](Entity Types), which currently has only Fluent API support.

**Comment by JayMoorhouse** [comment]
@lauxjpn thanks so much for your hastey response. I apologize, the previous developer did it in View mapping so it was bypassing my annotation. You can mark this as solved and again I apologize for the inconvenience.

**Comment by lauxjpn** [comment]
@JayMoorhouse Thanks for the prompt response! We are glad you figured out what the issue was.
