### ISSUE TITLE
Exception on commit transaction

### ISSUE THREAD

**Issue by elvysmarcos** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1608]
### Steps to reproduce
i just configured de transaction filter this way :

```c#
public class Transaction : ITransaction
{
    private readonly ApplicationDbContext _applicationDbContext;
    public Transaction(ApplicationDbContext applicationDbContext)
    {
        _applicationDbContext = applicationDbContext;
    }

    public void BeginTransaction()
    {
        _applicationDbContext.Database.BeginTransaction();
    }

    public async Task CommitTransactionAsync()
    {
        await _applicationDbContext.Database.CommitTransactionAsync();
    }

    public async Task RollbackTransactionAsync()
    {
        await _applicationDbContext.Database.RollbackTransactionAsync();
    }
}
```

### The issue
But sometimes, the application throws a transaction exception when it is trying commit the transaction, but the same transaction generally works, the issue happens in alternating.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: 
Object reference not set to an instance of an object.
Stack trace:

   at MySqlConnector.MySqlTransaction.<CommitAsync>d__2.MoveNext() in /_/src/MySqlConnector/MySqlTransaction.cs:line 37
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.<CommitAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.<CommitAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

### Further technical details

MySQL version: 5.7.24 (Or any version) 
Operating system: Window 10 ou Linux Ubuntu
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: 6.0.1

Other details about my project setup:

**Comment by lauxjpn** [comment]
This `NullReferenceException` seems to be thrown from line 37 in the following code:

_From https://github.com/mysql-net/MySqlConnector/blob/7773a756cc305238026146e06d48deaff7e0f604/src/MySqlConnector/MySqlTransaction.cs#L37_

```c#
private async Task CommitAsync(IOBehavior ioBehavior, CancellationToken cancellationToken)
{
    VerifyValid();

    using var activity = Connection!.Session.StartActivity("Commit");
    try
    {
        using (var cmd = new MySqlCommand("commit", Connection, this) { NoActivity = true })
            await cmd.ExecuteNonQueryAsync(ioBehavior, cancellationToken).ConfigureAwait(false);
        Connection!.CurrentTransaction = null; // <-- Line 37
        Connection = null;
        activity?.SetSuccess();
    }
    catch (Exception ex) when (activity is { IsAllDataRequested: true })
    {
        activity.SetException(ex);
        throw;
    }
}
```

So it means, that the `Connection` property is already null at the time of the commit.

---

@elvysmarcos This is very likely an issue in your applications code.

Please post the actual transaction code that fails.

Is this code being run inside a `Task.Run()` block or are you maybe missing an `await` keyword for an `async` call somewhere along the call stack (look for `CS4014` compile time warning)?

**Comment by elvysmarcos** [comment]
follow 

Executed DbCommand (30ms) [Parameters=[@__subjectId_0='' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SELECT `s`.`AttachmentId`, `s`.`Email`, `s`.`Id`, `s`.`Name`, `s`.`UId`, `f`.`Id`, `f`.`Bucket`, `f`.`ContentType`, `f`.`FileName`, `f`.`Guid`
FROM `settings.vw_users` AS `s`
LEFT JOIN `files.Attachments` AS `f` ON `s`.`AttachmentId` = `f`.`Id`
WHERE `s`.`UId` = @__subjectId_0
vw_users is a view.

**Comment by elvysmarcos** [comment]
The error happens sometimes, and put a breakpoint before call CommitTransactionAsync, and look like ok, but when the exceptions was throw , some thing clear the connection.
I tested the same code in sql server, but nothing happens.

**Comment by lauxjpn** [comment]
> Please post the actual transaction code that fails.

Sorry, I meant the C# code, like:

```c#
using var transaction = context.Database.BeginTransaction();

try
{
    // ...

    transaction.Commit();
}
catch (Exception)
{
    // ..
}
```

---

> The error happens sometimes, and put a breakpoint before call CommitTransactionAsync, and look like ok, but when the exceptions was throw , some thing clear the connection.

How often does this happen? Does it happen reliably or is it non-deterministic?

---

> Is this code being run inside a `Task.Run()` block or are you maybe missing an `await` keyword for an `async` call somewhere along the call stack (look for `CS4014` compile time warning)?

Have you checked that?

**Comment by elvysmarcos** [comment]
I can't determine, It happens amy moment.

First I have a filter :
`public class TransactionFilter : ActionFilterAttribute
    {
        private readonly ITransaction _transaction;
        public TransactionFilter(ITransaction transaction)
        {
            _transaction = transaction;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            _transaction.BeginTransaction();
        }

        public override async void OnActionExecuted(ActionExecutedContext context)
        {
            if (context.Exception == null && context.ModelState.IsValid)
            {
                await _transaction.CommitTransactionAsync();
            }
            else
            {
                await _transaction.RollbackTransactionAsync();
            }
        }
    }`

and than the transaction class 

` public class Transaction : ITransaction
    {
        private readonly ApplicationDbContext _applicationDbContext;
        public Transaction(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        public void BeginTransaction()
        {
            _applicationDbContext.Database.BeginTransaction();
        }

        public async Task CommitTransactionAsync()
        {
            await _applicationDbContext.Database.CommitTransactionAsync();
        }

        public async Task RollbackTransactionAsync()
        {
            await _applicationDbContext.Database.RollbackTransactionAsync();
        }
    }`

Configured in the program.cs 
`builder.Services.AddMvcCore(c =>
{
    c.Filters.Add<ExceptionFilter>();
    c.Filters.Add<TransactionFilter>();
}`

**Comment by lauxjpn** [comment]
@elvysmarcos This is likely to be an issue with how you implemented the `TransactionFilter`. There are 2 interfaces for action filters: [IActionFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iactionfilter?view=aspnetcore-6.0) and [IAsyncActionFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iasyncactionfilter?view=aspnetcore-6.0).

_From [Filters in ASP.NET Core: Multiple filter stages](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-6.0#multiple-filter-stages)_

> Interfaces for multiple filter stages can be implemented in a single class. For example, the [ActionFilterAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.actionfilterattribute) class implements:
> 
> * Synchronous: [IActionFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iactionfilter?view=aspnetcore-6.0) and [IResultFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iresultfilter)
> * Asynchronous: [IAsyncActionFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iasyncactionfilter?view=aspnetcore-6.0) and [IAsyncResultFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iasyncresultfilter)
> * [IOrderedFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iorderedfilter)

> **Implement either the synchronous or the async version of a filter interface, not both.** The runtime checks first to see if the filter implements the async interface, and if so, it calls that. If not, it calls the synchronous interface's method(s). If both asynchronous and synchronous interfaces are implemented in one class, only the async method is called. When using abstract classes like ActionFilterAttribute, override only the synchronous methods or the asynchronous methods for each filter type.

So the issue seems to be, that you are using `async` calls from within the synchronous [IActionFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iactionfilter?view=aspnetcore-6.0) implementation of [ActionFilterAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.actionfilterattribute).

Instead, you either want to use non-`async` calls in the [IActionFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iactionfilter?view=aspnetcore-6.0) methods or use the [IAsyncActionFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iasyncactionfilter?view=aspnetcore-6.0) methods.

---

For some sample code and more information about action filters see [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-6.0).

**Comment by lauxjpn** [comment]
@elvysmarcos Since you did not respond to us, we will assume that my previous answer solved the issue for you and are closing this one.
