### ISSUE TITLE
Initialising Entity Framework

### ISSUE THREAD

**Issue by stuartbloom** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#161]
Hi, and sorry if this is the wrong place or a silly question.

I have created a project on ubuntu 16.04 and all sems to compile of, however, when I call `dotnet ef migrations add Initial` I get a long list of errors with the following in red.

`Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory..ctor(Microsoft.EntityFrameworkCore.Infrastructure.ISensitiveDataLogger``1<Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory>, System.Diagnostics.DiagnosticSource, Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.
`
Can anyone give me any pointers?

Thanks in advance

Stuart

**Comment by Kagamine** [comment]
Maybe you mixed different ef versions in one project. We need more information, Could you post your project.json here?

**Comment by stuartbloom** [comment]
Sure, here it is :) renamed to txt to help upload :)
[project.json.txt](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/666035/project.json.txt)

**Comment by Kagamine** [comment]
You mixed ef core 1.1.0 and pomelo mysql 1.0.1. Please keep them same version will solve your issue.

**Comment by stuartbloom** [comment]
Thank you so much, now onto the next issue :(
