### ISSUE TITLE
Expected to read 4 header bytes but only received 0.

### ISSUE THREAD

**Issue by SavoInfostream** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1610]
### The issue
This error is thrown on `SaveChanges` in one Web Api Action, every time. Other Actions don't have this issue.
I am updating about 20 entries in this SaveChanges, more than in others. After getting this error in this one place a few times, other actions also starts throwing it. After a few seconds they go back to normal.

I am using the latest MySQL on Google Cloud, and I am using **SSL** for connections.
I am surprised at how little info on this issue is on the web, and this seems to be a completely generic error.

**connect_timeout** 10
**delayed_insert_timeout** 300
**have_statement_timeout** YES
**innodb_flush_log_at_timeout** 1
**innodb_lock_wait_timeout** 50
**innodb_rollback_on_timeout** OFF
**interactive_timeout** 28800
**lock_wait_timeout** 31536000
**net_read_timeout** 30
**net_write_timeout** 600
**rpl_stop_slave_timeout** 31536000
**slave_net_timeout** 30
**wait_timeout** 28800

Exception message:
Stack trace:

```
System.IO.EndOfStreamException: Expected to read 4 header bytes but only received 0.
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 476
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 943
```

### Further technical details

MySQL version: 8.0.18-google
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: 6.0

**Comment by lauxjpn** [comment]
@SavoInfostream Are you using the version of `MySqlConnector` that is referenced by Pomelo `6.0.1` (which is `2.1.2`), or are you using a newer version?

What OS is your app running on (or is it executed serverless)?

**Comment by mguinness** [comment]
See https://github.com/mysql-net/MySqlConnector/issues/571#issuecomment-437407245 for some background.  Are you using something like [ProxySQL](https://github.com/sysown/proxysql)?

> 0 bytes read is the indication that server closed the TCP connection (in an ordinary fashion, with closesocket, and linger). This is how APIs handle received FIN. Sockets are closed by server (i.e without client's COM_QUIT) in 2 main cases
>
> - KILL CONNECTION for this connection
>
> - One of the timeouts has expired. This usually will be either the inactivity timeout (_wait_timeout_ server variable) or the _write_timeout_ . _write_timeout_ happens when server sends a lot of result set rows quickly, but client is much slower processing rows, than server sends them.
> What happens is that TCP send buffer on the server side gets full, server gets stuck trying to write some data to socket. If server gets stuck for more than _write_timeout_ seconds, connection is closed.

**Comment by SavoInfostream** [comment]
@lauxjpn I tries with 2.0.0, 2.1.4 (latest currently) and 2.1.2. Same things happens.
Client app is running on Windows 10. It is a local dev environment.

**Comment by lauxjpn** [comment]
> Client app is running on Windows 10. It is a local dev environment.

@SavoInfostream Okay, so the app is running on your local Windows 10 machine, and is directly connected to a Google Cloud hosted MySQL instance, correct?

I would suggest to log the SQL statements generated by the failing `SaveChanges()` call. Then replay those statements (in a transaction) in one go from your local dev machine to the Google Cloud hosted MySQL instance using the `mysql.exe` command line tool to see, whether this issue is potentially a Pomelo/MySqlConnector issue or an issue with the setup of the MySQL instance.

Also, check the MySQL error log for additional information.

**Comment by mguinness** [comment]
Also see [MySql Long Running Query Fails on Docker .NET Core](https://stackoverflow.com/questions/63698209) for a possible solution.

**Comment by SavoInfostream** [comment]
Well, I have found a bug in MySQL. 
One of my commands was a DELETE command which was causing the error. Google Cloud MySql log was showing:
"The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains information that should help you find out what is causing the crash."

Anyways, this DELETE statement would try to delete a row from a table, and do a CASCADE delete from another table (foreign key). Besides cascade delete, another interesting thing is that the child table has a [multi-valued index](https://dev.mysql.com/doc/refman/8.0/en/create-index.html#create-index-multi-valued) on one of its json columns. These two things combined, with or without transaction, crash the MySql. 

If I delete the child row manually, it works. If I drop the index and delete the parent row, it deletes the parent and the child row.

Thanks for the help, everyone.
I will try and report this to MySql people.

**Comment by lauxjpn** [comment]
@SavoInfostream Nice detective work! Thanks for letting us know and for reporting it to the MySQL team.
