### ISSUE TITLE
SHOW VIEW permission required for querying a view.

### ISSUE THREAD

**Issue by kampilan** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1614]
Does querying a view in  MySql 8.0 now require the SHOW VIEW permission to be granted? This was the only way I was able to resolve my issue and I just wanted to confirm this is in fact a requirement. 

Thanks

**Comment by mguinness** [comment]
This question is better suited to Stack Exchange [Database Administrators](https://dba.stackexchange.com/questions/tagged/mysql) where you'll get a quicker and more detailed response.

As a hint you might want to check the `SQL SECURITY` setting on your view definition.
