### ISSUE TITLE
EF.Functions.Match translates to faulty sql

### ISSUE THREAD

**Issue by RSBlek** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1616]
### Steps to reproduce
Standard asp.net core mvc application.

**Entity Class**
```C#
public class DocumentFileEntity : BaseEntity
{
    ...
    public String? Text { get; set; }
    ...
}
```

### The issue
Using the Function `EF.Functions.Match` in a Linq-Where Statement leads to non executable SQL.

The used **Linq-Query** is:

```C#
List<DocumentEntity> documentEntities = await this.dbContext.DocumentFiles
   .Where(documentFile => EF.Functions.Match("Text", searchTerm, MySqlMatchSearchMode.NaturalLanguage))
   .Select(documentFile => documentFile.Document)
   .ToListAsync();
```

**Generated SQL and Exception**
```
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (5ms) [Parameters=[@__searchTerm_1='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
      SELECT `d0`.`Id`, `d0`.`FolderId`, `d0`.`Name`, `d0`.`Type`
      FROM `DocumentFiles` AS `d`
      INNER JOIN `Documents` AS `d0` ON `d`.`DocumentId` = `d0`.`Id`
      WHERE MATCH ('Text') AGAINST (@__searchTerm_1)
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Flek.Data.ApplicationDbContext'.
      MySqlConnector.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''Text') AGAINST ('a')' at line 4
```

It looks to me like the single quotes around the column name 'Text' name are the problem. A related PR that i found is #1268.

### Further technical details

Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: .NET 6

**Comment by lauxjpn** [comment]
@RSBlek The first parameter of `EF.Functions.Match(strin property, ...)` is supposed to be set to a _property_ of your entity, _not_ to the _name of the property_ of the entity:

```c#
// The following call should be translated as you would expect:
var documentEntities = await this.dbContext.DocumentFiles
   .Where(documentFile => EF.Functions.Match(/* --> */ documentFile.Text /* <-- */, searchTerm, MySqlMatchSearchMode.NaturalLanguage))
// ...
```

**Comment by RSBlek** [comment]
@lauxjpn 
Oh yes sorry, that was absolutely my bad. I should have looked at the functional tests first.
With `.Where(documentFile => EF.Functions.Match(documentFile.Text, searchTerm, MySqlMatchSearchMode.NaturalLanguage))` everything works as intended.

I've never seen this notation before.
I would have expected that when passing object.Property on a string parameter, the value of the property would be passed, and then that the string value of the property would have been used as column name.

**Comment by lauxjpn** [comment]
> I've never seen this notation before.
> I would have expected that when passing object.Property on a string parameter, the value of the property would be passed, and then that the string value of the property would have been used as column name.

@RSBlek No problem. Your EF Core LINQ queries are actually not C# code that is being executed. Instead, they are _expression trees_ that describe the operations that you have typed.

If e.g. you have a `documentFile.Size + 42` operation in you LINQ query (for whatever reason), then EF Core and Pomelo will receive an `Expression` object that has a `Left` property that is set to another expression representing your `documentFile.Size` property, a `Right` property that is set to another expression representing the constant value `42`, and a `NodeType` property that is set to `Add` (which is the operation that should be applied to the two properties/operands).

So what EF Core and Pomelo do, is basically just to parse this expression tree and convert all the expressions to SQL in a way that does make sense.

See [Expression Trees (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/) for more general information.

**Comment by klemmchr** [comment]
I've ran into the same problem and would suggest to change the syntax to a proper linq expression. This is super counter intuitive and error prone.

**Comment by lauxjpn** [comment]
> I've ran into the same problem and would suggest to **change the syntax to a proper linq expression**. This is super counter intuitive and error prone.

@klemmchr What do you means/suggest (post us some sample code)?

The current syntax should be the same as for any other LINQ expression for EF Core. Using a _property name string_ would be very unusual, since this is not being done in any common LINQ expression I am aware of.

**Comment by klemmchr** [comment]
I see that the behavior aligns with EF Core itself but this should at least be documented somehow or added to the xml docs.

**Comment by mguinness** [comment]
This is a community project, you can propose a change to the wiki or code.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/e1a1d8acb996efb19b07c6b7ff38a8367cb62daf/src/EFCore.MySql/Extensions/MySqlDbFunctionsExtensions.cs#L653-L667

**Comment by lauxjpn** [comment]
> @klemmchr What do you mean/suggest (post us some sample code)?
> 
> The current syntax should be the same as for any other LINQ expression for EF Core. Using a _property name string_ would be very unusual, since this is not being done in any common LINQ expression I am aware of.

@klemmchr Please just post us some sample code of what you would suggest the call should look like instead, or suggest to us a concrete change in the docs of that method, so we get an idea of where the actual pitfall is and can make the correct use as clear as possible for other users in the future. Thanks!

**Comment by klemmchr** [comment]
My use case is building a dynamic search function that performs a fulltext search over some entity. At this state I'm forced to write LINQ expressions from scratch to get this done because there is no overload that just accepts the property name(s). 
This is the code I need right now to fill the use case:

```c#
internal static class QueryableExtensions
{
    private static readonly MethodInfo DbFunctionsMatchMethod;
    private static readonly char[] MatchIllegalChars = { '+', '-', '@', '>', '<', '{', '}', '~', '*', '"' };
    private static readonly ConcurrentDictionary<Type, IReadOnlyCollection<string>> FulltextIndexProperties = new();
    private static readonly Expression EfFunctionsExpression = Expression.Constant(EF.Functions);
    private static readonly Expression SearchModeExpression = Expression.Constant(MySqlMatchSearchMode.Boolean);

    static QueryableExtensions()
    {
        DbFunctionsMatchMethod = typeof(MySqlDbFunctionsExtensions)
            .GetMethods(BindingFlags.Static | BindingFlags.Public)
            .FirstOrDefault(x =>
                x.Name == nameof(MySqlDbFunctionsExtensions.Match) &&
                x.GetParameters().Length == 4 &&
                x.GetParameters()[0].ParameterType == typeof(DbFunctions) &&
                x.GetParameters()[1].ParameterType == typeof(string[]) &&
                x.GetParameters()[2].ParameterType == typeof(string) &&
                x.GetParameters()[3].ParameterType == typeof(MySqlMatchSearchMode))!;
    }

    public static IQueryable<T> Search<T>(
        this IQueryable<T> query,
        IModel model,
        string searchString
        )
    {
        var expressionParameter = Expression.Parameter(typeof(T), "x");
        var searchProperties = GetIndexPropertyNames<T>(model);
        var body = GetPropertyFilterExpression(expressionParameter, searchProperties, searchString);

        var lambda = Expression.Lambda<Func<T, bool>>(body, expressionParameter);
        return query.Where(lambda);
    }

    private static MethodCallExpression GetPropertyFilterExpression(
        Expression parameter,
        IEnumerable<string> propertyNames,
        string searchString)
    {
        var matchPattern = GetMatchPattern(searchString);

        var propertiesExpression = propertyNames.Select(x => Expression.PropertyOrField(parameter, x));
        var propertyExpression = Expression.NewArrayInit(typeof(string), propertiesExpression);
        var patternExpression = Expression.Constant(matchPattern);
        return Expression.Call(DbFunctionsMatchMethod, EfFunctionsExpression, propertyExpression, patternExpression, SearchModeExpression);
    }

    private static string GetMatchPattern(string searchString)
    {
        var sanitizedSearchString = string.Join(
            "",
            searchString.Split(MatchIllegalChars, StringSplitOptions.RemoveEmptyEntries)
        );

        return sanitizedSearchString + "*";
    }

    private static IEnumerable<string> GetIndexPropertyNames<T>(IModel model)
    {
        if (FulltextIndexProperties.TryGetValue(typeof(T), out var indexProperties))
        {
            return indexProperties;
        }

        var entityType = model.FindEntityType(typeof(T));
        if (entityType is null)
        {
            throw new InvalidOperationException($"Entity type {typeof(T).FullName} is not configured in EF Core");
        }

        var indexes = entityType.GetIndexes().Where(x => x.IsFullText() is true).ToList();
        if (indexes.Count == 0)
        {
            throw new InvalidOperationException($"Found no fulltext index on entity type {typeof(T).FullName}");
        }

        if (indexes.Count > 1)
        {
            throw new InvalidOperationException(
                $"Found more than one full text index of entity type {typeof(T).FullName}"
            );
        }

        var index = indexes.First();
        indexProperties = index.Properties.Select(x => x.Name).ToList();
        FulltextIndexProperties.TryAdd(typeof(T), indexProperties);

        return indexProperties;
    }
}
```

Having such an overload would simplify that a lot. In terms of docs I could find something like that useful:

```c#
/// <example>
/// <code>
/// IQueryable<Foo> query;
/// query.Where(f => EF.Functions.Match(f.Bar, "filter", MySqlMatchSearchMode.Boolean))
/// </code>
/// </example>
```

**Comment by federicofz85** [comment]
Hi guys is there a way to match with 2 or more properties? I noticed that there's a overload that asks for string[] properties but I can't make it work
