### ISSUE TITLE
SQL Syntax

### ISSUE THREAD

**Issue by stuartbloom** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#162]
I am getting this error 

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL,
    `level` int NOT NULL,
    CONSTRAINT `PK_TankLevels` PRIMARY K' at line 4`

Is there anyway to see the full SQL so I can debug this? Attached is the contents of my models folder.

Thanks in advance

Stuart
[Models.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/666392/Models.zip)

**Comment by Kagamine** [comment]
Please upgrade your mysql to 5.6 or 5.7. The lower versions dosn not support datetime(6)

**Comment by deinok** [comment]
@Kagamine I'm having the same problem with the latest MySQL version (5.7.18)

**Comment by Kagamine** [comment]
@deinok We have already fixed this issue, if you still occur this, please open a new issue and provide us more information about your issue.

**Comment by deinok** [comment]
ref #332
