### ISSUE TITLE
Using ef dbcontext optimize

### ISSUE THREAD

**Issue by jasonterando** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1624]
Hi, I'm trying to run `ef dbcontext optimize` and have included Pomelo.EntityFrameworkCore.MySql and Pomelo.EntityFrameworkCore.MySql.Design in my project.  When running `ef dbcontext optimize` I'm getting the following error:

System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Design.Internal.ICSharpRuntimeAnnotationCodeGenerator' while attempting to activate 'Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGenerator'.

Do you guys support ef dbcontext optimize?  If so, are there any steps I need to take in ConfigureServices to enable support ?

Here are the packages I've included:

* Microsoft.EntityFrameworkCore (6.0.3)
* Microsoft.EntityFrameworkCore.Design (6.0.3)
* Microsoft.EntityFrameworkCore.Relational (6.0.3)
* Microsoft.EntityFrameworkCore.Relational.Design (6.0.3)
* Pomelo.EntityFrameworkCore.MySql (6.01)
* Pomelo.EntityFrameworkCore.MySql.Design (1.1.2)

I'm using 6.03 of the EF command line tools.

Thanks!

**Comment by mguinness** [comment]
[Pomelo.EntityFrameworkCore.MySql.Design](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql.Design) is deprecated and is nearly five years old, the functionality is now included within [Pomelo.EntityFrameworkCore.MySql](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql).  If you've already installed the EF Core tools using `dotnet tool install --global dotnet-ef` you shouldn't need to include any of the other packages.

**Comment by lauxjpn** [comment]
@jasonterando I tried a compiled model for the following code, which worked as expected:

<details>
<summary>.csproj File</summary>

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>disable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.5" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.1" />
    </ItemGroup>
    
</Project>
```

</details>

<details>
<summary>Program.cs</summary>

```c#
using System.Diagnostics;
using System.Linq;
using IssueConsoleTemplate.CompiledModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate;

public class IceCream
{
    public int IceCreamId { get; set; }
    public string Name { get; set; }
}
    
public class Context : DbContext
{
    public DbSet<IceCream> IceCreams { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var connectionString = "server=127.0.0.1;port=3308;user=root;password=;database=Issue1624";
            var serverVersion = ServerVersion.AutoDetect(connectionString);

            optionsBuilder
                .UseMySql(
                    connectionString,
                    serverVersion)
                .UseModel(ContextModel.Instance)
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<IceCream>(
            entity =>
            {
                entity.HasData(
                    new IceCream { IceCreamId = 1, Name = "Vanilla" },
                    new IceCream { IceCreamId = 2, Name = "Chocolate" });
            });
    }
}

internal static class Program
{
    private static void Main()
    {
        using var context = new Context();
            
        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        var iceCreams = context.IceCreams
            .OrderBy(i => i.IceCreamId)
            .ToList();
            
        Trace.Assert(iceCreams.Count == 2);
        Trace.Assert(iceCreams[0].IceCreamId == 1);
    }
}
```

</details>

**Comment by jasonterando** [comment]
Thanks.  I think we're good here!
