### ISSUE TITLE
Rename field error

### ISSUE THREAD

**Issue by jerateep** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1627]
### The issue
1. rename IsActive to is_active
2. use command dotnet ef migrations add rename_is_active is OK
3. use command dotnet ef database update => 
    error : You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `Is_Active` TO `is_active`' at line 1

![image](https://user-images.githubusercontent.com/18267454/160749030-49f42a86-f92f-4dc8-bdb3-a8678322276e.png)

my class
![image](https://user-images.githubusercontent.com/18267454/160749109-545936df-2c4a-45ac-b089-a96804609400.png)

```
Exception message:
Stack trace:
```

### Further technical details

mariadb version:  10.3.34
Operating system: windows 10
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.EntityFrameworkCore: 6.0.3
Microsoft.EntityFrameworkCore.Design: 6.0.3
Microsoft.EntityFrameworkCore.Proxies: 6.0.3
Microsoft.EntityFrameworkCore.Tools: 6.0.3
Other details about my project setup:
![image](https://user-images.githubusercontent.com/18267454/160748922-d0117e2d-d766-4c41-a609-83765e404e94.png)

**Comment by yukozh** [comment]
Can you post the migration script?

**Comment by jerateep** [comment]
@yukozh 
![image](https://user-images.githubusercontent.com/18267454/160775382-e04590d1-63c1-47f5-84e2-40ef98e01b06.png)

**Comment by yukozh** [comment]
I think maria db doesn't support RENAME COLUMN syntax, so did you specify the DB type and version when you add the Pomelo into service collection?
