### ISSUE TITLE
MySQL 8 hours time out problem with `DbContextPool`

### ISSUE THREAD

**Issue by LeaFrock** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1628]
### The issue

When using `DbContextPool`, EF Core will maintain a pool of connection. But if sometimes the connections are idle for above 8 hours and MySql will close them automatically. And then the first several requests to MySQL will throw exceptions : `... Connection Reset by Peer ...`. It becomes a fairly normal problem in our test environment.

I know some solutions like changing the settings of MySQL, or adding a `BackGroudService` which executes `Select 1;` per hour. I just wonder whether the side of application/configs related to EF Core can do something about it.

### Further technical details

MySQL version: 5.7
Operating system: Linux
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: 6.0.3

**Comment by mguinness** [comment]
Set `ConnectionLifeTime` in [Connection Pooling Options](https://mysqlconnector.net/connection-options/#connection-pooling-options) to a value below your [wait_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout).

Also you could look into using [Connection Resiliency](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency) via the [EnableRetryOnFailure](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/wiki/Configuration-Options#enableretryonfailure) option.

**Comment by LeaFrock** [comment]
Thanks @mguinness ! I'll do a test and close this issue if it works.
