### ISSUE TITLE
Translation of method 'System.DateTimeOffset.Add' failed

### ISSUE THREAD

**Issue by Kation** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1631]
It will throw exception show `Translation of method 'System.DateTimeOffset.Add' failed.` when use Add method.

```C#
DateTimeOffset today = new DateTimeOffset(DateTime.SpecifyKind(DateTimeOffset.Now.ToOffset(TimeSpan.FromHours(8)).Date, DateTimeKind.Unspecified), TimeSpan.FromHours(8));
query.Where(t => today.Add(t.Time) < t.StartTime || today.Add(t.Time) > t.EndTime);
```

It seems it is not support?
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/f17aa00102f5198f5d0d49c1a029cfe4c29e3a59/src/EFCore.MySql/Query/Internal/MySqlDateTimeMethodTranslator.cs#L18-L36

MySQL version: 
Operating system: 
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: 6.0

**Comment by mguinness** [comment]
Yes, [DateTimeOffset.Add](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.add) isn't translated.  You may be able to use other [supported translations](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/wiki/Translations) to achieve what you need.

**Comment by mguinness** [comment]
It might be possible to achieve what you need by using a combination of other methods.  Show us your table schema and some sample data.

**Comment by Kation** [comment]
I use dbfunction to workaround.

**Comment by mguinness** [comment]
Would you be able to share your code for others that encounter the same issue?
