### ISSUE TITLE
Found conflicts between EF Core 6.0.4 and Pomelo.EntityFrameworkCore.MySql 6.0.1

### ISSUE THREAD

**Issue by artur-siwiak** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1633]
### Steps to reproduce
Upgrade EF core nuget packages to 6.0.4 and use Pomelo.EntityFrameworkCore.MySql 6.0.1

### The issue
Experiencing warnings related to nuget packages version conflicts.

`Warning	MSB3277	Found conflicts between different versions of "Microsoft.EntityFrameworkCore.Relational" that could not be resolved.
There was a conflict between "Microsoft.EntityFrameworkCore.Relational, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" and "Microsoft.EntityFrameworkCore.Relational, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".
    "Microsoft.EntityFrameworkCore.Relational, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was chosen because it was primary and "Microsoft.EntityFrameworkCore.Relational, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was not.
    References which depend on "Microsoft.EntityFrameworkCore.Relational, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [C:\Users\[username]\.nuget\packages\microsoft.entityframeworkcore.relational\6.0.1\lib\net6.0\Microsoft.EntityFrameworkCore.Relational.dll].
        C:\Users\[username]\.nuget\packages\microsoft.entityframeworkcore.relational\6.0.1\lib\net6.0\Microsoft.EntityFrameworkCore.Relational.dll
          Project file item includes which caused reference "C:\Users\[username]\.nuget\packages\microsoft.entityframeworkcore.relational\6.0.1\lib\net6.0\Microsoft.EntityFrameworkCore.Relational.dll".
            C:\Users\[username]\.nuget\packages\microsoft.entityframeworkcore.relational\6.0.1\lib\net6.0\Microsoft.EntityFrameworkCore.Relational.dll
    References which depend on "Microsoft.EntityFrameworkCore.Relational, Version=6.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [].
        C:\Code\...\bin\Debug\net6.0\Storage.dll
          Project file item includes which caused reference "C:\Code\...\bin\Debug\net6.0\bbb.dll".
            C:\Code\...\bin\Debug\net6.0\bbb.dll
            C:\Code\...\bin\aaan\bin\Debug\net6.0\aaa.dll	UnitTests	C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	2302	`

### Further technical details
EF Core: 6.0.4
Pomelo.EntityFrameworkCore.MySql version: 6.0.1

### Workaround
Downgrade all ef core packages to version 6.0.1

**Comment by mguinness** [comment]
If you look at the dependencies for [Pomelo.EntityFrameworkCore.MySql](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/6.0.1#dependencies-tab) you'll see it can use any version >= 6.0.1 && < 7.0.0 of that library.   Double check all your project files in your solution, i.e. unit tests.  You've stripped out some text from the warning message above which should help you track down the problem.

**Comment by artur-siwiak** [comment]
> If you look at the dependencies for [Pomelo.EntityFrameworkCore.MySql](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/6.0.1#dependencies-tab) you'll see it can use any version >= 6.0.1 && < 7.0.0 of that library. Double check all your project files in your solution, i.e. unit tests. You've stripped out some text from the warning message above which should help you track down the problem.

That's correct. You have a right. Sorry for creating useless issue :/
