### ISSUE TITLE
Regression on 6.0.1 from 6.0.0 - hanging queries

### ISSUE THREAD

**Issue by jtheisen** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1634]
I have a situation where since updating to 6.0.1 on even the most simple test program any second query done through EF 6.0.1 hangs and ultimately fails on timeout, whereas Pomelo 6.0.0 is working just fine.

There are, however, some special network circumstances but I can't tell if they are relevant:

This only happens when connecting to a MySQL managed service on AWS which I get access to through a convoluted routing that involves an Azure NAT and an AWS load balancer.

I don't have direct access to that database, so I can't test if the regression manifests itself there too.

The AWS MySQL identifies itself as "5.7.12-log".

A MySQL that I connect directly to that is working with the new 6.0.1 identifies as "8.0.20-3".

I'm using .NET 6 here.

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1617

**Comment by jtheisen** [comment]
Right, that's the one, thanks.

That issue is closed for two months though and 6.0.1 still up as the latest version.

**Comment by mguinness** [comment]
> That issue is closed for two months though and 6.0.1 still up as the latest version.

Closing issue as not related to Pomelo provider, rather the underlying MySqlConnector library.
