### ISSUE TITLE
Can not project int values from json column

### ISSUE THREAD

**Issue by denisenko93** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1638]
### Steps to reproduce

1. Create ef core model
```cs
public class SampleJson
{
    [JsonProperty("int_value")]
    public int IntValue { get; set; }
}

public class EntityWithJson
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("json", TypeName = "json")]
    public SampleJson Json { get; set; }
}
```
2. Configure DBContext
```cs
optionsBuilder.UseMySql(
    "{connection_string}",
    new MySqlServerVersion(new Version(5, 7, 26)),
    x => x.UseNewtonsoftJson(MySqlCommonJsonChangeTrackingOptions.FullHierarchyOptimizedSemantically));
```
3. Create projection and try get value from json column
```cs
class Projection
{
    public int Value { get; set; }

    public int JsonValue { get; set; }
}

var query = _dbContext.Entities
    .Select(x => new Projection
    {
        Value = x.Id,
        JsonValue = x.Json.IntValue
    });
await query.ToArrayAsync();
```

### The issue
I see exception if i try get value from json

```
Exception message: Can't convert JSON to Int32
Stack trace:
at MySqlConnector.Core.Row.GetInt32(Int32 ordinal) in /_/src/MySqlConnector/Core/Row.cs:line 218
   at MySqlConnector.MySqlDataReader.GetInt32(Int32 ordinal) in /_/src/MySqlConnector/MySqlDataReader.cs:line 234
   at lambda_method62(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at MySqlJsonTest.Tests.Test1() in D:\source\MySqlJsonTest\MySqlJsonTest\UnitTest1.cs:line 39
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

### Further technical details

MySQL version: 8.0
Operating system: Windows 10 x64
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: 6.0.4

**Comment by mguinness** [comment]
We don't currently have documentation for JSON, but take a look at the code in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1296#issuecomment-835426559 to help get you started.

**Comment by denisenko93** [comment]
@mguinness I looked at examples in unit test projects. If json model contains only string properties, it works fine.

**Comment by mguinness** [comment]
What is the SQL that is being generated?  Is the source JSON like `{"IntValue":"123"}` or `{"IntValue":123}`?  Does this only occur when using a projection, if so have you tried casting?  What happens if you project to an anonymous type?

**Comment by denisenko93** [comment]
Generated SQL: 
```sql
SELECT `e`.`id` AS `Value`, JSON_EXTRACT(`e`.`json`, '$.int_value') AS `JsonValue`
FROM `Entities` AS `e`
```
I am created value in database from entity. In database json column contains `{"int_value": 34546}`
Reprodusion project in my [repository](https://github.com/denisenko93/PomeloJsonColumnTest)

**Comment by denisenko93** [comment]
This is the only way to avoid the error
```cs
new
{
    Value = x.Id,
    JsonValue = int.Parse(x.Json.IntValue.ToString())
}
```
Generated SQL:
```sql
SELECT `e`.`id`, CAST(JSON_EXTRACT(`e`.`json`, '$.int_value') AS char)
FROM `Entities` AS `e`
```

**Comment by mguinness** [comment]
Thanks for answering those questions.  I think you'll need to use `EF.Functions.JsonExtract()` to extract values from JSON when not a string value.

```C#
new
{
    Value = x.Id,
    JsonValue = EF.Functions.JsonExtract<int>(x.Json, "$.int_value")
}
```

@bgrainger Would there be anyway for the ADO.NET library to automagically cast the return value for a field using `JSON_EXTRACT()` to the receiving .NET type?  I'm guessing not, but I wanted to get your thoughts.

**Comment by bgrainger** [comment]
> Would there be anyway for the ADO.NET library to automagically cast the return value for a field using JSON_EXTRACT() to the receiving .NET type?

I suppose? The [JSON spec](https://www.json.org/json-en.html) has unambiguous forms for the various "value" types, which could be determined based on the leading character:

* `"` - string
* `0`-`9`, `-` - integer unless it contains `.` or `E` or `e`, in which case double
* `[` - array; ignore
* `{` - object; ignore
* `t`, `f` - check for `true` or `false`; Boolean
* `n` - check for `null`; could be mapped to `null`

I'm not sure if we'd want `GetValue` to automatically perform this conversion, or just allow `GetInt32`, `GetString`, `GetBoolean`, etc. to perform an implicit conversion from `JSON` if the field contents could be converted to the requested type? (I think the former creates a "polymorphic" return type, which would probably cause more problems than it solves; the latter would fix the exception in the OP.)

**Comment by bgrainger** [comment]
This might create ambiguous behaviour for `GetString`: does it return the original JSON as a string, or decode a JSON string into a C# string? If it already does the former, it would be a breaking change to change it to the latter.

**Comment by bgrainger** [comment]
According to a comment above, Pomelo generates this SQL:

```sql
SELECT `e`.`id` AS `Value`, JSON_EXTRACT(`e`.`json`, '$.int_value') AS `JsonValue`
FROM `Entities` AS `e`
```

I wonder if it should generate a conversion if it knows it's producing an integral value?

```sql
SELECT `e`.`id` AS `Value`, CONVERT(JSON_EXTRACT(`e`.`json`, '$.int_value'), SIGNED) AS `JsonValue`
FROM `Entities` AS `e`
```

Similarly, if Pomelo is extracting a string, I would expect this SQL:

```sql
SELECT `e`.`id` AS `Value`, JSON_UNQUOTE(JSON_EXTRACT(`e`.`json`, '$.string_value')) AS `JsonValue`
FROM `Entities` AS `e`
```

**Comment by denisenko93** [comment]
I think we should convert json value to c# value in background. Because if I execute this SQL script using Dapper it works fine

**Comment by mguinness** [comment]
Will wait for Laurents to opine on this subject when he has availability.

**Comment by lauxjpn** [comment]
@denisenko93 I'll test this shorty, but your model should just work, so if it doesn't in this case, it might be a bug that needs to be fixed.

**Comment by lauxjpn** [comment]
@denisenko93 Thanks for reporting! You can find the fix in our [nightly builds](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds).
