### ISSUE TITLE
Guidance for moving from MySQL.EntityFrameworkCore

### ISSUE THREAD

**Issue by marknadig** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1639]
I've got a production system that I'd like to migrate from using MySQL.EntityframeworkCore to Pomelo.EntityFrameworkCore. I wanted to do some due diligence before I just upgraded the nuget packages and give it a spin. I appreciate any insight. Currently I'm on EF5, also planning on upping to EF6.

One area of concern is existing migrations. Will they be compatible? Early in the project I switched from MSSQL provider to MySQL and had to delete and regenerate the migrations from scratch.

(cross posting from SO [question](https://stackoverflow.com/questions/72003180/))

**Comment by mguinness** [comment]
If you want to preserve existing migrations then upgrading the official provider to [6.0.0](https://www.nuget.org/packages/MySql.EntityFrameworkCore/6.0.0) is the easiest path.  Whenever you change a EF Core provider it probably makes sense to regenerate migrations to avoid any issues.

**Comment by marknadig** [comment]
Thanks @mguinness . I agree, path of least resistance is to stay w/ 'official'. But, I've got a nagging feeling I'd regret that into perpetuity. The opaqueness of the official bits drives me crazy. 

Are you aware of any guidance for swapping providers for a production system? Easy peasy to delete the existing migrations and regen the initial create. I didn't know if I needed to do anything w/ the existing __efmigrationshistory table or not.

**Comment by mguinness** [comment]
A lot of people have moved from Oracle to Pomelo provider for various reasons like bug fixes and we also have additional functionality like JSON and spatial support which the official version doesn't yet have.

With regards to a guide for swapping providers, take a look at [Re-Generate the Migrations](https://docs.abp.io/en/abp/4.4/Entity-Framework-Core-Other-DBMS#re-generate-the-migrations) for the steps.
