### ISSUE TITLE
Support for EntityFramework 6.4 (not EF Core) in .Net 6

### ISSUE THREAD

**Issue by vcrobe** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1642]
Hi there,

Is the Pomelo foundation supporting the EntityFramework 6.4 in .Net 6 (not EF Core)?

Thank you.

**Comment by mguinness** [comment]
No plans to create a provider for EF6.  Your best bet would be to see if Oracle or Devart have a provider.

**Comment by vcrobe** [comment]
OK, thank you for your quick response.

Oracle Connector.Net 8 provider work well as far as I can tell with _Entity Framework 6.4.4_ but it seems they don't allow migrations.

Thank you once again.
