### ISSUE TITLE
Support setting MySqlConnection.ProvidePasswordCallback through MySqlDbContextOptionsBuilder

### ISSUE THREAD

**Issue by ArtemKorchunov** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1643]
### The issue
I am trying to use ProvidePasswordCallback in order to retain the benefits of connection pooling for Aurora RDS with IAM Authentication. Exactly in the way that is described in MySqlConnection doc https://mysqlconnector.net/connection-options/
![image](https://user-images.githubusercontent.com/28545836/167264109-3ba23bc1-ec3d-4226-8651-93a393436697.png)

The problem is that it seems like [Pomelo.EntityFrameworkCore.MySql] does not support this. I have tried to look through other providers.

### Further technical details
 I have found this functionality for example in npgsql provider https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG/Infrastructure/NpgsqlDbContextOptionsBuilder.cs#L127
But nothing in Pomelo

MySQL version:  8.0.28
Operating system: Linux
Pomelo.EntityFrameworkCore.MySql version: 6.0.0
Microsoft.AspNetCore.App version: 6.0

**Comment by mguinness** [comment]
You should be able to set [ProvidePasswordCallback](https://mysqlconnector.net/api/mysqlconnector/mysqlconnection/providepasswordcallback/) by [Registering interceptors](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors), specifically [ConnectionOpening](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.idbconnectioninterceptor.connectionopening).

See [Example: Connection interception for SQL Azure authentication using AAD](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#example-connection-interception-for-sql-azure-authentication-using-aad) that manipulates the connection.

**Comment by ArtemKorchunov** [comment]
Thanks, it worked out for me.

**Comment by lauxjpn** [comment]
Lets keep this issue open to remind us to implement this feature.

**Comment by lauxjpn** [comment]
> You should be able to set [ProvidePasswordCallback](https://mysqlconnector.net/api/mysqlconnector/mysqlconnection/providepasswordcallback/) by [Registering interceptors](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors), specifically [ConnectionOpening](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.diagnostics.idbconnectioninterceptor.connectionopening).

I think connection interceptors are the right approach here. I currently see no need to explicitly expose the same behavior with a dedicated `DbContext` option method.
