### ISSUE TITLE
Null Reference Exception When Using Unix Socket

### ISSUE THREAD

**Issue by caseymarquis** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#165]
In the file: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/6844ed7007a68700affe84cf954a9f17e22e6975/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlRelationalConnection.cs

DoOpen/DoOpenAsync/DoClose all reference _connection.DataSource when creating logs. Unfortunately, if you're using a unix socket, this causes a null reference exception.

I'd think the solution would just be to replace it with  _connection.UnixSocket ?? _connection.DataSource, or something along those lines.

Not sure if this is a problem anywhere else in the code base? I'll end up looking through it (could be a bit though as I'm using this as part of a hobby project), but does anyone else have any thoughts?

**Comment by caleblloyd** [comment]
Thanks for the bug report.  Opened upstream at: https://github.com/mysql-net/MySqlConnector/issues/152

**Comment by caleblloyd** [comment]
Fixed in [1.1.1-prerelease-10004](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.1.1-prerelease-10004)
