### ISSUE TITLE
Duplicate logging

### ISSUE THREAD

**Issue by mandar1jn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1653]
### Steps to reproduce
configure the db context options with logging
```
.LogTo(Console.WriteLine, LogLevel.Information)
```

### The issue
Every message is logged to the console twice. Once in color, once in black and white

![image](https://user-images.githubusercontent.com/49076509/168868039-6814e084-7988-4b46-8c5d-d3192279bb25.png)

### Further technical details

MySQL version: 5.7.19
Operating system: windows 10
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: 6.0.5

**Comment by mandar1jn** [comment]
```
using DotNetWebsite.Data;
using Microsoft.EntityFrameworkCore;

namespace DotNetWebsite
{
    class Program {

        static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            // Add services to the container.
            builder.Services.AddRazorPages()
                //TODO: just make this 2 seperate statements. Readability over less repetition in this case
#if DEBUG
                //This would only take up resources in production without any use
                .AddRazorRuntimeCompilation();
#else
                //terminate if not in release
                ;
#endif

            string connectionString = builder.Configuration.GetConnectionString("HomeConnection");
            builder.Services.AddDbContext<DatabaseContext>(
            dbContextOptions => dbContextOptions
                .UseMySql(connectionString, ServerVersion.AutoDetect(connectionString))
                .LogTo(Console.WriteLine, LogLevel.Warning)

#if DEBUG
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors()
#endif
        );

            WebApplication app = builder.Build();

            // Configure the HTTP request pipeline.
            if (!app.Environment.IsDevelopment())
            {
                app.UseExceptionHandler("/Error");
            }

            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.MapRazorPages();

            app.Run();

        }

    }
}
```

note that the double log to does not seem to be the cause. I tried it in release mode and got the same result.

**Comment by mguinness** [comment]
Just created a simple fiddle at https://dotnetfiddle.net/nkC0yZ and there were no duplicates.  If you can expand this example to show duplicate messages or provide a sample project then we can investigate further.

Alternatively you can switch to the Oracle provider [MySql.EntityFrameworkCore](https://www.nuget.org/packages/MySql.EntityFrameworkCore/) and see if the duplicates still show.

**Comment by lauxjpn** [comment]
@mandar1jn This is going to be an issue somewhere in your app configuration code.

Have you tried it without the `LogTo()` shortcut? ASP.NET Core might just already have setup the logging for you and `LogTo()` is then issuing a second logging call. For example, you might already have setup the logging via your `appsettings.json` file.

(In case you want me to, I can try to replicate this in an ASP.NET app.)

**Comment by mandar1jn** [comment]
yup. Even without the logto there is already an instance logged to the console. It's my configuration. Thank you for your time
