### ISSUE TITLE
Unknown Database Error When Attempting To Create DB Via Code-First Migrations

### ISSUE THREAD

**Issue by thall90** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1670]
### Steps to reproduce

Program.cs:
```C# 
var host = CreateHostBuilder(arguments).Build();
using var scope = host.Services
    .GetRequiredService<IServiceScopeFactory>()
    .CreateScope();

var context1 = scope.ServiceProvider.GetRequiredService<ITestContext>();

context1.Database.Migrate();
host.Run();
```

```C#
public static class DbContextRegistrationExtensions
{
    public static void AddDbContexts(
        this IServiceCollection services,
        IConfigurationRoot configuration)
    {
        RegisterDbContext<ITestContext, TestContext>(
            services,
            configuration,
            "TestConnection",
           "Test");
    }

    private static void RegisterDbContext<TInterface, TContext>(
        this IServiceCollection services,
        IConfiguration configuration,
        string connectionStringName,
        string? schemaName = null,
        ServiceLifetime serviceLifetime = ServiceLifetime.Scoped)
        where TContext : DbContext, TInterface, IDbContext
    {
        var connectionString = configuration.GetConnectionString(connectionStringName);

        services.AddDbContext<TInterface, TContext>((_, options) =>
        {
            options.ConfigureWarnings(x => x.Ignore(CoreEventId.ManyServiceProvidersCreatedWarning));
            options.UseSnakeCaseNamingConvention();
            options.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString), x =>
            {
                x.MigrationsAssembly(AssemblyConstants.MigrationsAssembly);
                x.SchemaBehavior(MySqlSchemaBehavior.Translate, (schema, entity) =>
                {
                    return $"{schema.ToLowerInvariant() ?? "dbo"}_{entity.ToLower()}";
                });

                if (!string.IsNullOrWhiteSpace(schemaName))
                {
                    x.MigrationsHistoryTable($"__{schemaName}MigrationsHistory");
                }
            });

            options.EnableSensitiveDataLogging();
            options.ReplaceService<IMigrationsAssembly, CustomMigrationAssembly>();
        }, serviceLifetime);
    }
}
```

```C#
public class TestContext : DbContext, ITestContext
{
    public TestContext(DbContextOptions<TestContext> options)
        : base(options)
    {
    }

    public DbSet<TestReadModel> Tests { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.HasDefaultSchema(DatabaseBoundedContextConstants.Test);
        modelBuilder.ApplyConfiguration(new TestReadModelConfiguration());
    }
}
```

```C#
public class TestReadModelConfiguration : IEntityTypeConfiguration<TestReadModel>
{
    public void Configure(EntityTypeBuilder<TestReadModel> builder)
    {
        builder.HasKey(x => new { x.CustomerId, x.Id })
            .HasName("PK_Test");

        builder.Property(x => x.CustomerId)
            .IsRequired()
            .ValueGeneratedNever();

        builder.Property(x => x.Id)
            .IsRequired()
            .ValueGeneratedNever();

        builder.Property(x => x.Derp)
            .IsRequired(false)
            .IsUnicode(false)
            .HasMaxLength(50);
    }
}
```

appsettings.json
```JSON
{
  "ConnectionStrings": {
    "TestConnection": "server=127.0.0.1;port=3306;user=admin;password=Password123!;database=test_database"
  }
}
```

docker-compose.yml
```YAML
services:
  some-mariadb:
    image: mariadb:10.7
    container_name: mariadb2
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Password123!
      - MYSQL_PASSWORD=Password123!
      - MYSQL_USER=admin
      - MYSQL_DATABASE=master
```

### The issue
Attempting to create a MariaDB schema / database via code-first migrations yields an `Unknown database` exception. 

```
MySqlConnector.MySqlException (0x80004005): Unknown database 'test_database'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
```

### Further technical details

MariaDB version: 10.7 (Docker Container)
Operating system: MacOS 
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: .NET 6

**Comment by mguinness** [comment]
Shouldn't the `MYSQL_DATABASE` environment variable be test_database instead of master?

**Comment by thall90** [comment]
I used master as the initial database to ensure that the test_database was created by the migration, rather than by the Docker setup. I have a multi-database environment, so I needed to ensure that the migrations can create databases.

**Comment by mguinness** [comment]
Don't you then need to use [EnsureCreated](https://docs.microsoft.com/en-us/ef/core/managing-schemas/ensure-created#ensurecreated)?

**Comment by thall90** [comment]
Per that article, EnsureCreated shouldn't be used with migrations:

![image](https://user-images.githubusercontent.com/35042176/174193084-8a39db1b-d903-48b5-a68d-be29a099495f.jpeg)

**Comment by mguinness** [comment]
Then add a script to `/docker-entrypoint-initdb.d` to create the database.  The issue you're having isn't related to this provider.

**Comment by thall90** [comment]
This provider creates databases via migrations in other .NET Web APIs. Why wouldn't it in this case?

**Comment by lauxjpn** [comment]
@thall90 Please share with us the full stack trace of the exception.

Also make sure, that the sample code you provided does actually run. While I have not tried it yet, it appears that no context is currently created or registered (i.e. your `DbContextRegistrationExtensions.AddDbContexts()` method is not being called anywhere and your `CustomMigrationAssembly` class is missing (or should be stripped from the sample code if not needed)).

**Comment by thall90** [comment]
@mguinness @lauxjpn I was actually about to figure out the root cause of this issue. The exception that I was receiving was actually being thrown within the MySqlConnector code (see the call stack below), so once I set Rider to break for user exceptions only, it created the databases with no issues 🤦‍♂️

I apologize for the waste of time, and am very grateful for your help. 

![Screen Shot 2022-06-17 at 2 46 23 PM](https://user-images.githubusercontent.com/35042176/174374013-b23ba7cf-585a-487a-80fc-632cac696dc3.png)

**Comment by lauxjpn** [comment]
@thall90 Thanks for letting us know! Yeah, the exception is just part of the check, whether the database already exists or not and is caught and processed internally.

**Comment by Eternal21** [comment]
> @mguinness @lauxjpn I was actually able to figure out the root cause of this issue. The exception that I was receiving was actually being thrown within the MySqlConnector code (see the call stack below), so once I set Rider to break for user exceptions only, it created the databases with no issues 🤦‍♂️
> 
> I apologize for the waste of time, and am very grateful for your help.
> 

I've just wasted one hour trying to figure this out.  I thought I was going crazy, because database was being crated fine just yesterday and now is stopped.  Thanks for sharing your solution.
