### ISSUE TITLE
Support for new net 6.0 linq feature like DistinctBy

### ISSUE THREAD

**Issue by uzairali001** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1689]
.NET 6.0 introduce new features for LINQ and it would be really great if they translate to SQL query especially `DistinctBy`

Currently it's giving this error
```
.DistinctBy(ts => ts.TutorId)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'
```

https://dev.to/satish/net-6-linq-new-features-opb

**Comment by mguinness** [comment]
See https://github.com/dotnet/efcore/issues/27470
