### ISSUE TITLE
How to specify `lower_case_table_names` during database creation?

### ISSUE THREAD

**Issue by nicholasyin** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1695]
### Steps to reproduce
My database is in cloud and I can't modify the server configuration so can only resort to making this change during database creation via EF Core code first.

### The issue
Can't find how to specify this configuration using Pomelo provider.

### Further technical details

MySQL version: 5.7
Operating system: Ubuntu 20.04
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: 6.0

Other details about my project setup:

**Comment by mguinness** [comment]
Based on [Identifier Case Sensitivity](https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html) this value cannot be changed on the fly.

> [lower_case_table_names](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_lower_case_table_names) can only be configured when initializing the server. Changing the [lower_case_table_names](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_lower_case_table_names) setting after the server is initialized is prohibited.

**Comment by nicholasyin** [comment]
AFAIK, the database has its own setting of this.
