### ISSUE TITLE
Migrations: Is there any way to change the AUTO_INCREMENT constraint?

### ISSUE THREAD

**Issue by buzzers** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1702]
We are using [TiDB](https://en.wikipedia.org/wiki/TiDB) which provides a way of generating primary key data similar to `AUTO_INCREMENT` called `AUTO_RANDOM`.  `AUTO_RANDOM` and EF Core work just fine until we want to use the migration feature.

I didn't find a way to change the `AUTO_INCREMENT` constraint of the generated primary key to `AUTO_RANDOM`, which prevented us from taking advantage of the migration feature.  Is there any way to do this now?

MySQL version: TiDB 6.0
Operating system: Debian 11
Pomelo.EntityFrameworkCore.MySql version: 6.0.2
Microsoft.AspNetCore.App version: 6.0

**Comment by mguinness** [comment]
You could override the migration process, see [How to customize migration generation in EF Core Code First](https://stackoverflow.com/a/63793227/310601) for an example.

**Comment by buzzers** [comment]
I override `MySqlMigrationsSqlGenerator.ColumnDefinition` and this works. 
But since `MySqlMigrationsSqlGenerator` has some private methods that cannot be accessed 
this leads me to not be able to restore the logic 100% and just modify the `auto_increment` to `auto_random`.
Is there any other better way?
