### ISSUE TITLE
didn't use 'LogTo' method, but the sql statement log still printed

### ISSUE THREAD

**Issue by Fingerbb** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1706]
### Steps to reproduce
In my 'Startup.cs', I didn't use 'LogTo' method

```C#
var serverVersion = new MySqlServerVersion(new Version(8, 0, 28));
builder.Services.AddDbContextPool<XYCMDbContext>((options) =>
{
    options.UseMySql(builder.Configuration.GetConnectionString("DefaultConnection"), serverVersion);
    //.LogTo(Console.WriteLine, LogLevel);
});

```

### The issue
I didn't use 'LogTo' method, but the sql statement log still printed in window,I just want it not print，no matter debug or release

### Further technical details

MySQL version: 8, 0, 28
Operating system: linux
Pomelo.EntityFrameworkCore.MySql version: 6.0.2
Microsoft.AspNetCore.App version: 6.0.7

**Comment by mguinness** [comment]
See [Logging in .NET Core and ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/) and [Suppress SQL Queries logging in Entity Framework core](https://stackoverflow.com/questions/42079956/).
