### ISSUE TITLE
Currently skipping async tests, that depend on the Disposed event not raised by MySqlConnection.DisposeAsync

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1718]
The following _async_ tests depend on the `MySqlConnection.Disposed` event, that is currently not raised:

* ConnectionInterceptionMySqlTest
  * Intercept_connection_creation_with_multiple_interceptors
  * Intercept_connection_creation_passively
  * Intercept_connection_to_override_creation
  * Intercept_connection_to_override_connection_after_creation
* ConnectionInterceptionWithDiagnosticsMySqlTest
  * Intercept_connection_creation_with_multiple_interceptors
  * Intercept_connection_creation_passively
  * Intercept_connection_to_override_creation
  * Intercept_connection_to_override_connection_after_creation

@bgrainger The `Disposed` event is automatically raised by `Compontent.Dispose(bool disposing)`, but since it is not called by `MySqlConnection.DisposeAsync()`, the event is not raised.

**Comment by bgrainger** [comment]
Opened https://github.com/mysql-net/MySqlConnector/issues/1235 for MySqlConnector.

See also https://github.com/dotnet/efcore/pull/27920#pullrequestreview-974459202 and https://github.com/npgsql/efcore.pg/issues/2368.

I agree with @roji that this seems like a "legacy" event that the (test) code shouldn't be depending on. Thoughts about skipping these tests, as npgsql does, while the EF team decides if it's the right idea?

**Comment by lauxjpn** [comment]
Yeah, I think this event is suspicious as well. We will continue to skip the tests, until there is more consensus about what to do about it.

**Comment by lauxjpn** [comment]
Thanks, the tests work now!
