### ISSUE TITLE
EF Core 7 is not supported

### ISSUE THREAD

**Issue by alexyakunin** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1720]
IMO this requires an urgent update / fix.

### Steps to reproduce

- Reference EF Core 7 (e.g. Microsoft.EntityFrameworkCore.Relational 7.0.0 or any other EF Core provider targeting EF Core 7)
- Reference Pomelo.EntityFrameworkCore.MySQL 6.0.2
- Build the project.

### The issue
Describe what is not working as expected.

```
Stl.Fusion.Tests.csproj: [NU1107] Version conflict detected for Microsoft.EntityFrameworkCore.Relational. Install/reference Microsoft.EntityFrameworkCore.Relational 7.0.0 directly to project Stl.Fusion.Tests to resolve this issue. 
 Stl.Fusion.Tests -> Microsoft.EntityFrameworkCore.Sqlite 7.0.0 -> Microsoft.EntityFrameworkCore.Sqlite.Core 7.0.0 -> Microsoft.EntityFrameworkCore.Relational (>= 7.0.0) 
 Stl.Fusion.Tests -> Pomelo.EntityFrameworkCore.MySql 6.0.2 -> Microsoft.EntityFrameworkCore.Relational (>= 6.0.7 && < 7.0.0).
```

As you can see, https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql specifies it supports `Microsoft.EntityFrameworkCore.Relational` with version range (>= 6.0.7 && < 7.0.0), and `< 7.0.0` is a fit for RC builds, **but not a fit for release** (i.e. exactly v7.0.0).

### Further technical details

MySQL version: doesn't matter
Operating system: doesn't matter 
Pomelo.EntityFrameworkCore.MySql version: 6.0.2

**Comment by SeriaWei** [comment]
Is there any plan to upgrade to EF Core 7.0?

**Comment by mguinness** [comment]
This is to be expected, you cannot use `6.0.2` with EF Core 7 as stated in the dependencies.  The effort to support that is being tracked in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1557.  Suggest you subscribe to that issue to get updates and closing this as a duplicate.
