### ISSUE TITLE
Database is created but tables are not created (7.0.0-alpha.1)

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1726]
Database is created but tables are not created

_Originally posted by @areltasarim in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1557#issuecomment-1319867907_

**Comment by lauxjpn** [comment]
> Database is created but tables are not created

Check if all your tables(your model) have Primary key as i had an issue related to EF Core 7.0 forcing to have Primary Keys

_Originally posted by @alexandrecastro-bib in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1557#issuecomment-1319897667_

**Comment by lauxjpn** [comment]
I have 2 complex business applications each with fairly complex databases and comprehensive integration test suites, all work well with 7.0.0-alpha.1. As always, even with ORM, having the code first model design conforming to database normalization is good for many things. 
I was not aware of EF Core 7.0 forcing to have Primary Keys, however, I do think this is a good move. Google "entity framework normalization database" you can find many good posts.

_Originally posted by @zijianhuang in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1557#issuecomment-1320502523_

**Comment by lauxjpn** [comment]
all my id fields are like this anyway

`[Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]`

```
Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
19.11.2022 00:29:38.840 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure) 
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
19.11.2022 00:29:39.871 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (14ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='paros' AND TABLE_NAME='__EFMigrationsHistory';
19.11.2022 00:29:39.883 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='paros' AND TABLE_NAME='__EFMigrationsHistory';
19.11.2022 00:29:39.935 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `MigrationId`, `ProductVersion`
      FROM `__EFMigrationsHistory`
      ORDER BY `MigrationId`;
19.11.2022 00:29:39.952 RelationalEventId.MigrationsNotApplied[20405] (Microsoft.EntityFrameworkCore.Migrations) 
      No migrations were applied. The database is already up to date.
Done.
```

tables are not created

_Originally posted by @areltasarim in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1557#issuecomment-1320541747_

**Comment by lauxjpn** [comment]
@areltasarim Create a new issue w/ an example project so it can be looked into.

_Originally posted by @mguinness in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1557#issuecomment-1320805416_

**Comment by lauxjpn** [comment]
You can download the project from the link below

https://github.com/areltasarim/Pomelo

the default project as in the picture below EticaretWebCoreMigrationMysql Let's make an update database by selecting

![Başlıksız-1](https://user-images.githubusercontent.com/101069343/202844574-74c6181b-3f41-4e38-812c-0ccce37ce36f.png)

_Originally posted by @areltasarim in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1557#issuecomment-1320845561_

**Comment by lauxjpn** [comment]
> You can download the project from the link below
> 
> https://github.com/areltasarim/Pomelo
> 
> the default project as in the picture below EticaretWebCoreMigrationMysql Let's make an update database by selecting
> 
> ![Başlıksız-1](https://user-images.githubusercontent.com/101069343/202844574-74c6181b-3f41-4e38-812c-0ccce37ce36f.png)

I can't access your project but did you generate your first migration ? 
If not, this is why you don't have tables.

_Originally posted by @alexandrecastro-bib in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1557#issuecomment-1320846427_

**Comment by lauxjpn** [comment]
you can access the project now

https://github.com/areltasarim/Pomelo

_Originally posted by @areltasarim in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1557#issuecomment-1320847903_

**Comment by lauxjpn** [comment]
normally I did add-migration in my project, but I forgot this in the project I sent you, you add-migration first

_Originally posted by @areltasarim in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1557#issuecomment-1320853422_

**Comment by lauxjpn** [comment]
re-updated the project can you download again

_Originally posted by @areltasarim in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1557#issuecomment-1320853725_

**Comment by areltasarim** [comment]
now tables are created, my problem is solved :))) Thanks for your help

**Comment by lauxjpn** [comment]
@areltasarim Thank you for letting us know! What was the root of the issue and the solution that solved it?

**Comment by areltasarim** [comment]
I thought I did add-migration, then when I looked I realized that I didn't do it, it was my problem.
