### ISSUE TITLE
UseMySql( DbConnection ) extension fails with Exception about having both a Connection and a connection string

### ISSUE THREAD

**Issue by kampilan** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#175]
I posted this to the closed previous issues #169 a few days ago. Not sure you saw so I am opening a new issue.

Got a chance to try this (fix for #169).
An exception was thrown in MySqlRelationConnection:

            if (!string.IsNullOrWhiteSpace(relationalOptions.ConnectionString))
            {
                throw new InvalidOperationException(RelationalStrings.ConnectionAndConnectionString);
            }
It appears that setting the connection string on the option builder even though a live connection was supplied is the culprit:

        var extension = GetOrCreateExtension(optionsBuilder);
        extension.Connection = connection;
        extension.ConnectionString = csb.ConnectionString;
        ((IDbContextOptionsBuilderInfrastructure)optionsBuilder).AddOrUpdateExtension(extension);

        mySqlOptionsAction?.Invoke(new MySqlDbContextOptionsBuilder(optionsBuilder));

Thanks
Jim

**Comment by caleblloyd** [comment]
Shipped in [1.1.1-prerelease-10011](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.1.1-prerelease-10011)

I added a test this time so it should work now!

**Comment by kampilan** [comment]
Works great!  Thanks.
