### ISSUE TITLE
Using 3.x versions with latest MySqlConnector library (2.2.25+)

### ISSUE THREAD

**Issue by jsholzer** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1762]
I have a legacy ASP.NET app that we're in the process of porting from .NET Framework and MySQL Connector/Net to .NET/.NET Core and MySqlConnector + Pomelo. For the time being, we need to utilize Entity Framework Core 3.1, so we'll need to utilize the 3.x versions of this library.

Would you accept a pull request for refactoring the latest 3.2-maint version of this library to work with MySqlConnector 2.2.25? I was able to successfully refactor the code, and the tests, to work with MySqlConnector 2.2.25, and can certainly submit a PR. Could this be a 3.3.0 version?

However, if you would be unwilling to merge in a PR with the changes, I can certainly publish them as a separate NuGet package for now

We would much prefer to use the latest and greatest version of MySqlConnector as opposed to the 0.69.10 version that the latest 3.2-maint release requires.

**Comment by yukozh** [comment]
.NET 3.1 LTS was end of support. We don't have any plan to do that. Feel free to create your own package but please follow the MIT license.
