### ISSUE TITLE
How to use Stored procedure in this library?

### ISSUE THREAD

**Issue by IkhyeonJo** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1765]
Hi, I'm trying to use stored procedure by using this library.

I can't find out how to use it.

Can you tell me how to use it?

**Comment by IkhyeonJo** [comment]
I'm using version 7.0

**Comment by lauxjpn** [comment]
In case you are still looking for it, https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/953#issuecomment-555964869 has some older code that demonstrates how to use stored procedures.

There are also a couple of [stored procedure related answers](https://stackoverflow.com/search?q=user%3A2618319+stored+procedures+%5Bpomelo-entityframeworkcore-mysql%5D) I gave on StackOverflow.
