### ISSUE TITLE
Schemas don't work

### ISSUE THREAD

**Issue by GuilhermeBley** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1769]
### The issue
I know that entity framework don't supports mysql schemas, but is there a way to do a query including several schemas?

### Further technical details

MySQL version: 5.6.51
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 6.0.2

**Comment by JohannSig** [comment]
You might be able to run a raw SQL query.

https://learn.microsoft.com/en-us/ef/core/querying/sql-queries

But you may be better off just creating a view in one of the DB schemas targeting the other one.

**Comment by GuilhermeBley** [comment]
Thanks for the alternative solution, I will try it.
