### ISSUE TITLE
Exception when connect to MySQL

### ISSUE THREAD

**Issue by phuocminh6464** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1771]
### Steps to reproduce

The issue can't not to reproduce because it only occurs in my client side and but not in my dev environment. The only difference between 2 environments is that I use Windows 10 and my client uses Windows 11. 
**Step:**
1.  Create a class library for DAL has HQPCDbContext, MainUserConfiguration and entity file
2.  Create another class library has Program.cs file (main project)
3. Reference the DAL project in main project

Here is my code:

**DAL.csproj** file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.17" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="5.0.4" />
  </ItemGroup>

</Project>
```

**Program.cs** file:
```
string dbConnection = "server=localhost;port=3306;Uid=root;Pwd=mysql;database=test;"
var optionsBuilder = new DbContextOptionsBuilder<HQPCDbContext>();
optionsBuilder.UseMySql(dbConnection, MySqlServerVersion.LatestSupportedServerVersion);
var _context = new HQPCDbContext(optionsBuilder.Options);
var user = _context.MainUsers.FirstOrDefault(x => x.UserName == "abc");
```
**HQPCDbContext** file:
```
public class HQPCDbContext : DbContext
{
    public HQPCDbContext(DbContextOptions options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new MainUserConfiguration());       
        base.OnModelCreating(modelBuilder);
    }

    public DbSet<MainUser> MainUsers { get; set; }
}
```
**MainUserConfiguration** file:
```
public class MainUserConfiguration : IEntityTypeConfiguration<MainUser>
{
    public void Configure(EntityTypeBuilder<MainUser> builder)
    {
        builder.ToTable("MainUser");
        builder.HasKey(x => x.Id);            
    }
}
```

### The issue
It gets exception as below when call 'UseMySql' and because it occurs in client side so I only have the Exception message

```
Exception message: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
```

### Further technical details

MySQL version:  8.0.30
Operating system: Windows 11
Pomelo.EntityFrameworkCore.MySql version: 5.0.4
Class Library TargetFramework: .Net 5

**Comment by JohannSig** [comment]
Can you put your code into a Git repo and provide a link to it?
Also, .NET 5 went out of support 7 months ago, you might have better luck with .NET 6 or 7 versions of Pomelo.

**Comment by phuocminh6464** [comment]
> Can you put your code into a Git repo and provide a link to it? Also, .NET 5 went out of support 7 months ago, you might have better luck with .NET 6 or 7 versions of Pomelo.

@JohannSig thanks, I've found that adding 'EnableRetryOnFailure() mehtod when call UseMySql() is solved
