### ISSUE TITLE
Exception when connect to MariaDb 10.3  Unable to create a 'DbContext' of type ''

### ISSUE THREAD

**Issue by YongPengDing** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1773]
TestContext.cs
`public class TestContext: DbContext{public  FatTigerContext(DbContextOptions options) : base(options) {}}`

Program.cs
`builder.Services.AddDbContext<FatTigerContext>(options =>{  options.UseMySql(builder.Configuration.GetConnectionString("maraidb"), new MariaDbServerVersion(new Version(10,3,32)));});`

### The issue

Add-Migration test

```
Exception message:
Unable to create a 'DbContext' of type ''. The exception 'Method not found: 'Void CoreTypeMappingParameters..ctor(System.Type, Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, System.Func`3<Microsoft.EntityFrameworkCore.Metadata.IProperty,Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.ValueGeneration.ValueGenerator>)'.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

### Further technical details

MariaDb version:  10.3.32
Operating system:  win10 vs2022
Pomelo.EntityFrameworkCore.MySql version: 7.0.0
Microsoft.AspNetCore.App version: 6

Other details about my project setup:
Same configuration
conn SqlServer 
Success

**Comment by imran-uk** [comment]
What was the fix for this please? I have a similar issue.

**Comment by imran-uk** [comment]
I got this to work by downgrading my app to net6 (sdk 6.0.201)

Seems like the Pomelo.EntityFrameworkCore.MySql packages do not fully work with net8 (sdk 8.0.100).

**Comment by epatrick** [comment]
I found downgrading to .net7.0 (from .net8.0) addressed the The exception 'Method not found: 'Void CoreTypeMappingParameters...' issue. Oddly, the Microsoft.EntityFramework* assemblies are 8.0.0.

**Comment by imran-uk** [comment]
I got it working with net8 by using the beta package

https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/8.0.0-beta.1
