### ISSUE TITLE
an exception was  throw when i  used  linq method "Where" to get  a list

### ISSUE THREAD

**Issue by yinanrong** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#178]
### the parameter that  i gave was  a ulong number ,and the exception was:

> The call is ambiguous between the following methods or properties: 'Microsoft.EntityFrameworkCore.Storage.RelationalSqlGenerationHelper.GenerateLiteralValue(float)' and 'Microsoft.EntityFrameworkCore.Storage.RelationalSqlGenerationHelper.GenerateLiteralValue(decimal)'

### it looks like that it can't find a matched overload method 
my code is just like:
```c#
  var list =
                  _dbContext.Notices.Where(m => ids.Contains(m.Id) && m.State == NoticeStates.NotSent);
            foreach (var model in list)
            {
                model.State = NoticeStates.Canceled;
            }
            return await _dbContext.SaveChangesAsync();
```

## what can i do to  solve id,thanks

**Comment by Kagamine** [comment]
@yinanrong Could do you show me your `project.json`

**Comment by Jamesxql** [comment]
@Kagamine the `project.json` like this:

```json
{
  "version": "2.0.2",
  "buildOptions": {
    "debugType": "portable",
    "warningsAsErrors": true
  },
  "dependencies": {
    "FeiniuBus.Puid": "2.0.0",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Pomelo.EntityFrameworkCore.MySql": "1.1.0"
  },
  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by mclucario** [comment]
Any idea whats wrong?

**Comment by Novatide** [comment]
I had this same problem. It was only being thrown when I tried to use a specific property in my Where call. I believe this is a bug in EntityFramework, and has something to do with the way async is being used.

In my case, I was able to work around it by moving my context work into its own Task, and then async calling that.
