### ISSUE TITLE
[enum] Problem of storing ISO 5218 values in database

### ISSUE THREAD

**Issue by alexeygritsenko** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1783]
### Steps to reproduce
1. Make sure you have the following user table
```
CREATE TABLE `Users` (
  `Id` int NOT NULL,
  `Name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Sex` tinyint(1) NOT NULL DEFAULT '0',
  `BirthDate` date DEFAULT NULL,
  `Avatar` varchar(255) DEFAULT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
2. According to the ISO 5218, we have an enumeration
```
    public enum Sex
    {
        Unknown,
        Male,
        Female,
        NotApplicable = 9
    }
```
with entity model
```
    public class User
    {
        public int? Id { get; set; }
        public string Name { get; set; }
        public Sex Sex { get; set; }
        public DateTime? BirthDate { get; set; }
        public string Avatar { get; set; }
    }
```

we read or write changes like this
```
var user = await _mysql.Users.FirstOrDefaultAsync(x => x.Id == 1);
user.Sex = Sex.Male;
await _mysql.SaveChangesAsync();
```

### The issue
The problem is that after a time the value is not saved to the database or is read incorrectly. Sometimes it works, but more often it doesn't. That being said, I don't get any errors.

### Further technical details

MySQL version: 8.0.30
Operating system:  Windows 10
Pomelo.EntityFrameworkCore.MySql version: 6.0.2
Microsoft.AspNetCore.App version: net6.0

Link to ISO 5218 https://en.wikipedia.org/wiki/ISO/IEC_5218

**Comment by yukozh** [comment]
I think we are storing enums in integer. did u checked the value in db？

**Comment by alexeygritsenko** [comment]
> I think we are storing enums in integer. did u checked the value in db？
Yes. as you can see in my schema i use tinyint(1). It also is int only more economical. It supports my range from enum 0,1,2,9. I successfully set values to it through the phpMyAdmin and Workbench. But when I work through the EF it gives an unexpected result.

**Comment by yukozh** [comment]
Do you mean you have created table by the SQL command, not code first, right?

**Comment by alexeygritsenko** [comment]
Yes, my database is designed manually. this allows you to specify types more efficiently. However, you are right! The library considered this type to be boolean, so I just removed the dimension like this:  `tinyint(1)` -> `tinyint` now the conversion works as it should) thank you very much
