### ISSUE TITLE
How do you get a random entity or a random entity set with LINQ?

### ISSUE THREAD

**Issue by Nefcanto** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1789]
In EF Core, we could use `OrderBy(i => Guid.NewGuid())` to get a random entity or a random entity set.

I know in MySql this does not work and we should use `order by rand()`. But how do you do that using LINQ?

I mean let's consider this query:

```
Students.Where(i => i.Age > 24).Take(5);
```

How can I make it return a random entity set?

**Comment by sigeer** [comment]
`.OrderBy(x => EF.Functions.Random())`

**Comment by Nefcanto** [comment]
@sigeer , perfect. You literally saved me. Thank you so much.
