### ISSUE TITLE
Cannot use MethodCallTranslatorProvider in v8

### ISSUE THREAD

**Issue by MaceWindu** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1801]
Following code stops to work in v8
```cs
var dependencies = context.GetService<RelationalSqlTranslatingExpressionVisitorDependencies>();
// fails due to MySqlMethodCallTranslatorProvider.QueryCompilationContext being null
dependencies.MethodCallTranslatorProvider.Translate(...);
```

**Comment by lauxjpn** [comment]
@MaceWindu Please post the full exception, including the stack trace.

**Comment by MaceWindu** [comment]
It fails on this line https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Query/Internal/MySqlMethodCallTranslatorProvider.cs#L56

**Comment by lauxjpn** [comment]
Yes, we new require the `QueryCompilationContext` property to be set to the current query compilation context, before `MySqlMethodCallTranslatorProvider.Translate()` can be called.

**Comment by MaceWindu** [comment]
How it could be done from generic code?

**Comment by MaceWindu** [comment]
We need to translate provider specific extensions and currently it stopped to work for mysql provider as it returns uninitialized object from DI container

**Comment by lauxjpn** [comment]
Drop me a link to the line in the code, so I can see the context.

**Comment by MaceWindu** [comment]
https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/master/Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs#L523

here we convert efcore extension to linq2db extension format

**Comment by lauxjpn** [comment]
> here we convert efcore extension to linq2db extension format

While this is not enough context for me to understand what you are trying to do, here is how you can fix it in general:

You somehow need to provide a `QueryCompilationContext` instance to `MySqlMethodCallTranslatorProvider.QueryCompilationContext`, before calling `MySqlMethodCallTranslatorProvider.Translate()`.

EF Core creates one [before compiling a query](https://github.com/dotnet/efcore/blob/5ff7e9fc758d5792df5615350ed31f7c93134f40/src/EFCore/Storage/Database.cs#L67) by calling `QueryCompilationContextFactory.Create()`.

So you could retrieve the `IQueryCompilationContextFactory` service and call `Create()` to get a `QueryCompilationContext` instance. Than you can later use that object to set the `MySqlMethodCallTranslatorProvider.QueryCompilationContext` property to it, if `ctx.this_._dependencies!.MethodCallTranslatorProvider` has a public `QueryCompilationContext` property (check via reflection if you do not reference Pomelo, or if it `is MySqlMethodCallTranslatorProvider` if you do reference Pomelo).

**Comment by MaceWindu** [comment]
Fixed using reflection
