### ISSUE TITLE
Implement `DbDataSource` support

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1817]
> I really hope to get to building DbDataSource support into EF itself for 9.0; I've added DbDataSource specifically to EFCore.PG in the meantime, so you could copy that, but ideally this would all be managed in the core.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1813#issuecomment-1821372201

**Comment by bgrainger** [comment]
Related issue in Npgsql: https://github.com/npgsql/efcore.pg/issues/2400

In https://github.com/dotnet/aspire/pull/1161 (which you may want to review @lauxjpn), I'm having to work around the inability to use `MySqlDataSource` from DI.
