### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1818]
To stay aligned with common practices, we should name the default branch `main`.

**Comment by alexeygritsenko** [comment]
Is this really important? It seems to me that you can do a lot of really useful things instead

**Comment by lauxjpn** [comment]
To update your local environment, your can use commands similar to the following:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
