### ISSUE TITLE
Error EF update cascading

### ISSUE THREAD

**Issue by douglassimaodev** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1824]
```
dbug: 28/12/2023 00:09:14.545 RelationalEventId.CommandExecuting[20100] (Microsoft.EntityFrameworkCore.Database.Command)
      Executing DbCommand [Parameters=[@p0='?' (DbType = Guid), @p1='?' (DbType = DateTime), @p2='?' (DbType = Int64), @p3='?' (DbType = Guid), @p4='?' (DbType = Guid), @p5='?' (Size = 250), @p6='?' (Size = 250), @p7='?' (DbType = Guid), @p8='?' (DbType = DateTime), @p9='?' (DbType = Guid), @p10='?' (DbType = DateTime), @p11='?' (Size = 250), @p12='?' (Size = 250)], CommandType='Text', CommandTimeout='30']
      INSERT INTO `InfluencerMedia` (`CreatedBy`, `CreatedOn`, `Followers`, `InfluencerId`, `MediaId`, `MediaUserId`, `Name`, `RemovedBy`, `RemovedOn`, `UpdatedBy`, `UpdatedOn`, `Url`, `Username`)
      VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12);
      SELECT `Id`
      FROM `InfluencerMedia`
      WHERE ROW_COUNT() = 1 AND ;
```

I am trying to update a table with a list of new items in another table linked by foreign key 

<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0-beta.2" />

with .net 8.. the problem seems to be in that "AND ;"

**Comment by lauxjpn** [comment]
@douglassimaodev Please check if this issue still occurs using Pomelo `8.0.1`. We did some fixes in this area for that release.

If you still encounter this issue with Pomelo `8.0.1`, please post the involved model classes, their Fluent API configuration and the code that leads to the generation of the insert query, so we can reproduce the issue. Thanks!

**Comment by lauxjpn** [comment]
> @douglassimaodev Please check if this issue still occurs using Pomelo `8.0.1`. We did some fixes in this area for that release.
> 
> If you still encounter this issue with Pomelo `8.0.1`, please post the involved model classes, their Fluent API configuration and the code that leads to the generation of the insert query, so we can reproduce the issue. Thanks!

@douglassimaodev Any update on this?

**Comment by lauxjpn** [comment]
@douglassimaodev We will close this issue for now. Once you provide the requested information, we will reopen this issue.
