### ISSUE TITLE
EF Core 8.0.1 with Pomelo.EntityFrameworkCore.MySql 7.0.0 fails to create migration

### ISSUE THREAD

**Issue by MarcosNasc** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1831]
### Steps to reproduce

Create a new ASP.NET Core project using .NET 8.0.
Install the following packages:
Microsoft.EntityFrameworkCore (version 8.0.1)
Microsoft.EntityFrameworkCore.Tools (version 8.0.1)
Pomelo.EntityFrameworkCore.MySql (version 7.0.0)
Create a DbContext class that inherits from IdentityDbContext.
Register the DbContext in the program.cs file.
Configure the DbContext with a connection string to a MySQL database.
Attempt to create a migration using the command Add-Migration AuthIdentity.
### The issue

The command Add-Migration AuthIdentity fails with the following error:

Unable to create a 'DbContext' of type ''. The exception 'Method not found: 'Void CoreTypeMappingParameters..ctor(System.Type, Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, System.Func`3<Microsoft.EntityFrameworkCore.Metadata.IProperty,Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.ValueGeneration.ValueGenerator>)'.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

### Further technical details

MySQL version: 8.0.36
Operating system: Windows 10 (please specify your specific version)
Pomelo.EntityFrameworkCore.MySql version: 7.0.0
Microsoft.AspNetCore.App version: 8.0.1
Visual Studio version: (please specify your specific version)
.NET Core SDK version: (please specify your specific version)
### Other details about my project setup

No other relevant details to share at this time.
### Additional notes from troubleshooting attempts:

The issue persists even after installing the Microsoft.EntityFrameworkCore.Design package.
It is unlikely to be a compatibility issue between EF Core and Pomelo.EntityFrameworkCore.MySql versions, as the versions used are compatible.
The issue might be related to the configuration of the DbContext or other factors in the project setup.

**Comment by iKingNinja** [comment]
Can you share how you solved this issue?

**Comment by Previatti** [comment]
I updated the Pomelo version and it worked...
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0-beta.2" />

**Comment by iKingNinja** [comment]
I thought there wasn't a higher version because visual studio's nuget package manager doesn't show beta versions.
