### ISSUE TITLE
MySql Renaming Column Exception

### ISSUE THREAD

**Issue by ElsevarAsadov** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1842]
### The issue
Just i tried to rename column name

```
Exception message:
Stack trace:

fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER TABLE `UnverifiedUsers` RENAME COLUMN `Username` TO `UserName`;
Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `UnverifiedUsers` RENAME COLUMN `Username` TO `UserName`;

```

I solved this problem simply custom sql statement but anyway i hope this will help you to improve system.

```cs
public partial class UnverifiedUsersTableUpdated : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            /*migrationBuilder.RenameColumn(
                name: "Username",                     // Not works
                table: "UnverifiedUsers", 
                newName: "UserName");*/     

            migrationBuilder.Sql("ALTER TABLE `unverifiedusers` CHANGE `UserName` `Username` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;", true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            /*migrationBuilder.RenameColumn(
                name: "UserName",                        // Not works
                table: "UnverifiedUsers",
                newName: "Username");*/
            
            
            migrationBuilder.Sql("ALTER TABLE `unverifiedusers` CHANGE `UserName` `Username` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;", true);
        }
    }
```

### Further technical details

MySQL version: Server version: 10.4.32-MariaDB - mariadb.org binary distribution
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 8.0.0-beta.2
Microsoft.AspNetCore.App version: .NET 8

**Comment by lauxjpn** [comment]
The `RENAME COLUMN` syntax is support since MariaDB `10.5.2`. You are using MariaDB `10.4.32`, so the syntax is not supported in your case.

Pomelo should not use this unsupported syntax in your case, unless you have configured it for a version of MariaDB (or MySQL) that supports that syntax.

@ElsevarAsadov So the question is: How does your `UseMySql()` call look like? (Especially the `serverVersion` parameter, which Pomelo depends on for choosing a syntax that your database server is compatible with.)

**Comment by ElsevarAsadov** [comment]
> The `RENAME COLUMN` syntax is supported since MariaDB `10.5.2`:
> 
> https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/126df6e22003cf8f334322bc08f5446f7000f9fd/src/EFCore.MySql/Infrastructure/MariaDbServerVersion.cs#L56
> 
> You are using MariaDB `10.4.32`, so the syntax is not supported in your case.
> 
> Pomelo should not use this unsupported syntax, unless you have configured it for a version of MariaDB (or MySQL) that supports that syntax.
> 
> @ElsevarAsadov So the question is: How does your `UseMySql()` call look like? (Especially the `serverVersion` parameter, which Pomelo depends on for choosing a syntax that your database server is compatible with.)

Hi, This is my configuration.

```cs
        // Database Contexts
        services.AddDbContext<MainDbContext>(options =>
        {
            int major = int.Parse(configuration["MySql:Major"] ?? throw new ConfigurationMissingException("Mysql:Major configuration missing"));
            int minor = int.Parse(configuration["MySql:Minor"] ?? throw new ConfigurationMissingException("Mysql:Minor configuration missing"));
            int build = int.Parse(configuration["MySql:Build"] ?? throw new ConfigurationMissingException("Mysql:Build configuration missing"));
            options.UseMySql(configuration["ConnectionStrings:Default"], new MySqlServerVersion(new Version(major, minor, build)));
        });
       

```

```json
...
 
"MySql": {
    "Major": "10",
    "Minor": "4",
    "Build": "24"
  }

...


````

**Comment by ElsevarAsadov** [comment]
@lauxjpn Thanks.I the problem obvious is my configuration :))

```cs

  // Database Contexts
        services.AddDbContext<MainDbContext>(options =>
        {
            int major = int.Parse(configuration["MySql:Major"] ?? throw new ConfigurationMissingException("Mysql:Major configuration missing"));
            int minor = int.Parse(configuration["MySql:Minor"] ?? throw new ConfigurationMissingException("Mysql:Minor configuration missing"));
            int build = int.Parse(configuration["MySql:Build"] ?? throw new ConfigurationMissingException("Mysql:Build configuration missing"));
            
            options.UseMySql(configuration["ConnectionStrings:Default"], new MariaDbServerVersion(new Version(major, minor, build)));
        });
        
        ```
        
        now works fine.but anyway i think pomelo should validate someway that i configured badly so doesnt continue to transaction.I literally use that horrible configuration a long time and worked fine except some cases weird errors.

**Comment by lauxjpn** [comment]
Yes, using `MariaDbServerVersion` instead of `MySqlServerVersion` is correct.

If you want to simplify your configuration, you can pass a string to `ServerVersion.Parse()`:

```c#
// [...]
// "MySql": "10.4.24-mariadb",
// [...]

services.AddDbContext<MainDbContext>(options =>
{
    var serverVersion = ServerVersion.Parse(configuration["MySql"] ?? throw new ConfigurationMissingException("Mysql configuration missing"));
    options.UseMySql(configuration["ConnectionStrings:Default"], serverVersion);
});
```

---

> [...] i think pomelo should validate someway that i configured badly so doesnt continue to transaction [...]

Pomelo works across different MySQL implementations and versions. It is your responsibility to tell it the correct database version and type it should expect.

(It is also possible to detect the current `ServerVersion` by calling `ServerVersion.AutoDetect(connectionString)`. But specifying the `ServerVersion` manually is our recommended best practice.)
