### ISSUE TITLE
ServerVersion.AutoDetect vs manual MySqlServerVersion set

### ISSUE THREAD

**Issue by alexeygritsenko** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1845]
Hi, I'd like to clarify why such difficulties, while other EF providers detect the version automatically.
1. How accurate/reliable is AutoDetect?
2. Is the version obtained via AutoDetect cached or is it requested on every scoped connection?
3. Is there any reason not to make AutoDetect the default without explicitly setting it by developer?

**Comment by roji** [comment]
Other EF providers do not detect versions automatically - other providers have similar explicit APIs for specifying versions (PG has SetPostgresVersion(), SQL Server has SetCompatibilityMode()). The difference is that with those other providers, specifying the version is optional (some default is assumed), whereas with the Pomelo provider speicfying the default is mandatory.

For background, there are various places where EF needs to e.g. generate SQL without having any connection to the database (e.g. when generating migration scripts, when compiling/precompiling queries). As a result, EF relies on the user configuring explicitly which database version/type is being targeted.

**Comment by bgrainger** [comment]
Related: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1603

**Comment by alexeygritsenko** [comment]
Thanks. But so far this information does not answer all questions.
>when generating migration scripts

I don't use migrations
>when compiling/precompiling queries

That is, if I use AutoDetect will they not compile for me?

>Is the version obtained via AutoDetect cached?

?

**Comment by lauxjpn** [comment]
@alexeygritsenko Thanks for letting us know! If you have any suggestions about how to make the usage clearer, please go ahead. Otherwise, feel free to close this issues.
