### ISSUE TITLE
Using `SELECT ... ORDER BY (SELECT 1)` can lead to the return of unexpected data using Oracle MySQL releases

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1849]
Using a `SELECT ... ORDER BY (SELECT 1)` expression can return completely wrong data using Oracle MySQL releases.
We came across this issue in our test suite, when tests are executed in a specific order.

The issue can be reproduced by executing a no-op (or any existing) test of the `ProxyGraphUpdatesMySqlTest.LazyLoading` class (e.g. our own `DummyTest`), immediately followed by `NorthwindSplitIncludeNoTrackingQueryMySqlTest.Include_collection_OrderBy_empty_list_contains(async: False)`.

We should implement a workaround, that outputs `1` instead of `(SELECT 1)`.

### Further technical details

MySQL version: 8.0.0+ (tested e.g. with 8.0.36)

**Comment by Santehnikua** [comment]
I used the technique of converting IQueryable to IOrderedQueryable var orderedData = data.OrderBy(x => true); to dynamically generate a list of parameters for sorting in the future.
After this change, the MySQL code ORDER BY 1 is generated, but the server interprets it as sorting by the first parameter and now my records are sorted incorrectly, because the first parameter is Id.
Is it possible to make this change optional, or ignore .OrderBy(x => true) when building queries?
So far I have found a solution var orderedData = data.OrderBy(x => x.Id == 0); but in my opinion it is not optimal.

**Comment by lauxjpn** [comment]
@Santehnikua Please post some sample code, so we can reproduce the issue you are having with this change.

**Comment by Santehnikua** [comment]
Here is a minimal reproducible example.

The problem occurs when sorting by true is combined with skip + take. Without skip + take a 1 is not added to the ORDER BY query.

`using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace PomeloEntityFrameworkCoreMySqlChangeTest
{
	internal class Program
	{
		static void Main(string[] args)
		{
			using var db = new BloggingContext();

			db.Database.EnsureDeleted();
			db.Database.EnsureCreated();

			var users = new List<User>
			{
				new User
				{
					FirstName = "Jane",
					LastName = "Barton"
				},
				new User
				{
					FirstName = "Rey",
					LastName = "Morgan"
				},
				new User
				{
					FirstName = "Ann",
					LastName = "Knight"
				},
				new User
				{
					FirstName = "Bob",
					LastName = "Martin"
				},
				new User
				{
					FirstName = "Adam",
					LastName = "Alpine"
				}
			};

			db.AddRange(users);
			db.SaveChanges();

			var orderedUsersWithTrue = db.TestUsers.OrderBy(x => true);
			orderedUsersWithTrue = orderedUsersWithTrue.ThenBy(x => x.FirstName);
			orderedUsersWithTrue = orderedUsersWithTrue.ThenBy(x => x.LastName);

			Console.WriteLine("Here is broken results. They are ordered by UserId, due to ORDER BY 1");

			foreach (var user in orderedUsersWithTrue.Skip(0).Take(3))
			{
				Console.WriteLine(user.UserId + " - " + user.FirstName + " - " + user.LastName);
			}

			Console.WriteLine("Here is working results. They are ordered by First Name");

			var orderedUsersWithoutTrue = db.TestUsers.OrderBy(x => x.FirstName);
			orderedUsersWithoutTrue = orderedUsersWithoutTrue.ThenBy(x => x.LastName);

			foreach (var user in orderedUsersWithoutTrue.Skip(0).Take(3))
			{
				Console.WriteLine(user.UserId + " - " + user.FirstName + " - " + user.LastName);
			}


		}
	}

	public class BloggingContext : DbContext
	{
		public DbSet<User> TestUsers { get; set; }

		protected override void OnConfiguring(DbContextOptionsBuilder options)
			=> options
				.UseMySql("Server=localhost;Database=test;user=test;password=qwerty", new MySqlServerVersion(new Version(8, 0, 27)))
				.LogTo(Console.WriteLine, LogLevel.Information)
				.EnableSensitiveDataLogging();
	}
	
	public class User
	{
		public int UserId { get; set; }
		public string FirstName { get; set; }
		public string LastName { get; set; }

	}
}`

**Comment by lauxjpn** [comment]
> After this change, the MySQL code ORDER BY 1 is generated, but the server interprets it as sorting by the first parameter and now my records are sorted incorrectly, because the first parameter is Id.

Interesting. I have been using SQL for around 25 years and I did not know that `ORDER BY 1` sorts the result by the first selected expression, but it is indeed SQL-92 standard.

That means that `ORDER BY (SELECT 1)` is _not_ equivalent to `ORDER BY 1`.

We have to revert this PR.

@Santehnikua Thanks for making us aware of this!
