### ISSUE TITLE
Method Not Found - Metadata.IMutableEntityType.GetProperties()

### ISSUE THREAD

**Issue by codexBA** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1854]
### Steps to reproduce
Any query/request I try throws an exception of 'Method not found'.

for instance:
`await _dbContext.Products.FirstOrDefaultAsync(p => p.Id == "here is the id");`

### The issue
Exception is thrown on each query, looking for the method IMutableEntityType.GetProperties which is present in EF Core 7 [LINK HERE](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.imutableentitytype.getproperties?view=efcore-7.0) and seems not to be part of EF Core 8 [LINK HERE](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.imutableentitytype.adddata?view=efcore-8.0) 

Exception message:
```
Method not found: 'System.Collections.Generic.IEnumerable`1<Microsoft.EntityFrameworkCore.Metadata.IMutableProperty> Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.GetProperties()'`
```

### Further technical details

MySQL version: 8.0.29-1.el8 (using docker)
Operating system: win 11
Pomelo.EntityFrameworkCore.MySql version: 8.0.0
EF Core version: 8.0.x
Microsoft.AspNetCore.App version: 

Other details about my project setup:
Im trying to update from .NET 6 to .NET 8. 
The persistence layer is implemented with an abstract approach using a BaseRepository<T> and other repositories inherit from it with required customizations where necessary. 
Same setup works fine with .NET 8, EF Core 7 and Pomelo.EntityFrameworkCore.MySql version: 7.0.0

**Comment by lauxjpn** [comment]
@codexBA Please post a full call stack, so we know where the exception is thrown.

Generally, those kind of exceptions are thrown when the used versions of Pomelo and EF Core are incompatible with each other. So you want to ensure that Pomelo `8.0.x` is used only with EF Core `8.0.x` packages (and not older ones).

For general Pomelo compatibility, see our [compatibility matrix](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql?tab=readme-ov-file#compatibility).

**Comment by codexBA** [comment]
Thanks for the quick reply and my apologies - it was my bad.

After deeper analysis of the exception figured out that another nuget-package for applying the encryption was causing the issue. 

For anyone interested in more details, `OnModelCreating` method used some nuget package for applying encryption by implementing an extension method to `ModelBuilder.`

Thanks again

**Comment by lauxjpn** [comment]
@codexBA Thanks for sharing the cause of the issue!
