### ISSUE TITLE
Any plans for a 1.1.1 release?

### ISSUE THREAD

**Issue by kampilan** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#186]
Thanks

**Comment by caleblloyd** [comment]
For official releases we try to follow [upstream Microsoft.EntityFrameworkCore.Relational](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Relational/) releases, which coincide with .NET Core releases

1.1.1-prerelease-* releases are fairly stable and have passed all of our test cases, so should be safe to use.
