### ISSUE TITLE
Just a quick question: does it support JSON data type?

### ISSUE THREAD

**Issue by nicholasyin** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1877]
including saving and querying?

**Comment by lauxjpn** [comment]
Yes. Pomelo has extensive support for working with Json.

Choose one of our two [Json packages](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql?tab=readme-ov-file#packages):

- `Pomelo.EntityFrameworkCore.MySql.Json.Microsoft`
- `Pomelo.EntityFrameworkCore.MySql.Json.Newtonsoft`

For some sample code that demonstrates different ways of querying, see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/14#issuecomment-632536008.
