### ISSUE TITLE
.Net Core 1.1 cannot use .ToListAsync with MySQL?

### ISSUE THREAD

**Issue by KenDRhyD** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#188]
### Steps to reproduce
Have 1.1.0 of all elements installed.

### The issue
There does not seem to be a ToListAsync() method available, even though all of the documentation indicates that it should be. Am I missing something?

```
Exception message:
Stack trace:
```

### Further technical details

MySQL version: 5.7.15
Operating system: MacOS 10.11.6
Pomelo.EntityFrameworkCore.MySql version: 1.1.0

Other details about my project setup:

**Comment by caleblloyd** [comment]
What is the call that you are trying to make that includes `ToListAsync()`?

**Comment by KenDRhyD** [comment]
I am experimenting and have built the scaffold for an existing database and schema (District2).

services.AddDbContext<District2Context>(options => options.UseMySql(Configuration.GetConnectionString("District2-Dev")));

In my HomeController I inject the District2Context and save it in a class variable (District2Context _context;).

In the Index() method I enter code to initially retrieve all news items (which is a table for which scaffolding was built): var news = _context.NewsEvents.ToListAsync();

I had tried the ToList() call, but it also indicates that the method is not available -- even though the auto-completion does acknowledge that NewEvents is a DbSet object!

**Comment by caleblloyd** [comment]
What if you use an Order By statement or a limit such as `Take(10)`? [example](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Controllers/AsyncController.cs)

**Comment by KenDRhyD** [comment]
For some reason none of the expected methods (Where, OrderBy, etc) appear in the intellisense list and report the same error if I attempt to use them. Truly confusing as the injection is accepted and seems to work. There is an AddAsync and FIndAsync method available, but no others seem related to database activity.

**Comment by caleblloyd** [comment]
Are you `using Microsoft.EntityFrameworkCore;` in your controller?

**Comment by KenDRhyD** [comment]
Argh! That was missing!!! How frustrating that nothing provided a clue, or at least none that I understood!

I am making progress now. Thank you!
