### ISSUE TITLE
Include() raises "There is already an open DataReader (...)" exception

### ISSUE THREAD

**Issue by GrzegorzSojka** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#189]
### Steps to reproduce
I'm stuck on really simple piece:
`      var x = kp.MatchEvents.Include (m => m.Match).ToList ();`
This fails with exception (details below). What I can't understant that almost the same code works with different two tables in the very same 1:N configuration.
It looks very similar to #18 .

Related code:

    namespace KP.Model
    {
      [Table("matches")]
      public partial class Match
      {
        [Column("MatchID", TypeName = "int(10) unsigned")]
        [Key]
        public int MatchID { get; set; }

        (...)

        public virtual ICollection<MatchEvent> Events { get; set; } = new List<MatchEvent> ();
      }
     
      [Table ("mevents")]
      public partial class MatchEvent
      {
        [Column ("EventID", TypeName = "int(11)")]
        [Key]
        public int EventId { get; set; }

        [Column ("MatchID", TypeName = "int(10) unsigned")]
        public int MatchID { get; set; }

        (...)

        [ForeignKey("MatchID")]
        public virtual Match Match { get; set; }
      }
    }
and

      modelBuilder.Entity<MatchEvent>(entity =>
      {
        entity.HasIndex(e => e.MatchID)
          .HasName("MatchID")
          .IsUnique();

        entity.HasOne (e => e.Match)
          .WithMany (m => m.Events)
          .HasForeignKey (e => e.MatchID);
      });
### The issue
When I try to 
`      var x = kp.MatchEvents.Include (m => m.Match).ToList ();`
I get:
```
MySqlException: There is already an open DataReader associated with this Connection which must be closed first.

MySql.Data.MySqlClient.MySqlCommand.VerifyValid()
MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor+<ExecuteReaderAsync>d__3.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor+<ExecuteNonQueryAsync>d__1.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MySql.Data.MySqlClient.MySqlCommand+<ExecuteNonQueryAsync>d__46.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
MySql.Data.MySqlClient.MySqlTransaction.Dispose(bool disposing)
Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalTransaction.Dispose()
Microsoft.EntityFrameworkCore.Query.QueryMethodProvider+<_Include>d__30.System.IDisposable.Dispose()
Microsoft.EntityFrameworkCore.Query.QueryMethodProvider+<_Include>d__30.MoveNext()
Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider+<_TrackEntities>d__15.MoveNext()
Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider+ExceptionInterceptor+EnumeratorExceptionInterceptor.MoveNext()
System.Collections.Generic.List..ctor(IEnumerable<T> collection)
System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
```

### Further technical details

MySQL version: 5.7.11
Operating system: Win10
Pomelo.EntityFrameworkCore.MySql version: 1.1.0
DB first (legacy data).

**Comment by GrzegorzSojka** [comment]
...and today everything work correctly without changing anything. Probably unexplainable, probably closable.

**Comment by caleblloyd** [comment]
Keep the issue open, this exception is masking an inner exception. Probably an issue connecting to MySQL or something in your case, but I need to look at why the inner exception is being masked.

**Comment by pawepaw** [comment]
I'm facing the same problem and i can't update to newest version because i have to run .NetCoreApp 1.0. Any chance to deploy fix for 1.0 version? Or any possible fixes to apply?

**Comment by caleblloyd** [comment]
1.1.2 works work .NET core 1.0

**Comment by pawepaw** [comment]
> Error: Project is referencing NETStandard.Library version 1.6.1. Max version supported by netcoreapp1.0 is 1.6.0.

>  Error: NETStandard.Library 1.6.1 is used for target framework netcoreapp1.1.

**Comment by Kagamine** [comment]
Please bump up your target, set netcoreapp1.1 as your build target please.

**Comment by pawepaw** [comment]
Can't use 1.1 has to be 1.0.

**Comment by caleblloyd** [comment]
It works fine for me:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" Version="3.4.156" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.2" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="1.1.2" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>
  
</Project>
```

Build:

```
dotnet build
Microsoft (R) Build Engine version 15.3.117.23532
Copyright (C) Microsoft Corporation. All rights reserved.

  App -> /home/caleb/Projects/caleb/dotnet-core-boilerplate/dotnet/src/App/bin/Debug/netcoreapp1.0/App.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.17
```

Nothing more we can do.  I imagine you have some conflicts in your project.json / csproj.  Try upgrading your tooling and using the new csproj with `netcoreapp1.0`

**Comment by pawepaw** [comment]
ok so it might be connected with aws and their support. Thanks anyway!
