### ISSUE TITLE
`Math.Log` number and base are in the wrong order in mysql `LOG` function

### ISSUE THREAD

**Issue by MSDev201** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1890]
### Steps to reproduce

```cs
await _db.Clicks
            .GroupBy(x => x.Search)
            .Select(x => Math.Log(x.Count(), 10))
            .ToListAsync();
```
resulting sql:
```sql
SELECT LOG(CAST(COUNT(*) AS double), 10.0)
FROM `Clicks` AS `p`
GROUP BY `p`.`Search`
```

### The issue

The calculated result is wrong since the count is used as base and the base is used as count.
C# is `Math.Log(number, base)`
MySQL is `LOG(base, number)` https://dev.mysql.com/doc/refman/8.3/en/mathematical-functions.html#function_log

My workaround for now is to just flip the parameters.
From what I see, this issue is also present in newer versions but please correct me if im wrong.

### Further technical details

MySQL version: 10.9.8-MariaDB
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 7.0.0
Microsoft.AspNetCore.App version: 7.0.7

**Comment by lauxjpn** [comment]
@MSDev201 Thanks! The fix will be available in `9.0.0-preview.2`, `8.0.3`, `7.0.1` and `6.0.4`. It is now available via our [nightly build feeds](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql?tab=readme-ov-file#nightly-builds).
