### ISSUE TITLE
All primary keys altered in migration after upgrading efcore to 8.0.1

### ISSUE THREAD

**Issue by benjaminoerskov** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1898]
After upgrading to 8.0.1, my migrations wants to update all my primary keys like so:

```tsql
ALTER TABLE `UserPerformanceSettings` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT;
``` 

The same is true for version 8.0.2. However if I downgrade to version 8.0.0, I no longer get these extra Alters.

Note: I have not changed anything other than the version, and my primary keys are already set like the migration target.

Maybe related to this?
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1844

EF Core version: 8.0.1
Database provider: Pomelo.EntityFrameworkCore.MySql Version=8.0.1
Target framework: NET8.0
Operating system:
IDE: Visual Studio 2022 17.8.7

**Comment by lauxjpn** [comment]
> Maybe related to this?
> https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1844

@benjaminoerskov That is correct. As part of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1844, we update the metadata (in the snapshot and `<Migration>.Designer.cs` file) for all `auto_increment` columns and for the model itself.

The `ALTER TABLE` statement should be a noop and not change anything, so you could remove them manually from your `Up()`/`Down()` methods if you want to.

**Comment by lauxjpn** [comment]
> So does that mean, if I only have these changes in my migration, I can completely remove the migration, and only commit a changed snapshot?

Yes, that should usually work.
