### ISSUE TITLE
Remove STJ dependency as it is provided by the framework

### ISSUE THREAD

**Issue by thompson-tomo** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1905]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Text.Json as it can be provided by the framework. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by lauxjpn** [comment]
I don't think we are explicitly referencing the `System.Text.Json` package in `Pomelo.EntityFrameworkCore.MySql` (see [EFCore.MySql.csproj](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/main/src/EFCore.MySql/EFCore.MySql.csproj)).

We only reference it in the optional `Pomelo.EntityFrameworkCore.MySql.Json.Microsoft` package, but that is expected.

---

@thompson-tomo You are used an issue template that is not ours. Are you sure you posted this issue on the right repository?

**Comment by thompson-tomo** [comment]
@lauxjpn yes I am talking about Pomelo.EntityFrameworkCore.MySql.Json.Microsoft hence correct project. Starting with net core app 3 I think, STJ has been available as part of the framework hence you don't need an explicit dependency on it.

**Comment by lauxjpn** [comment]
In that case, yes, we are explicitly referencing `System.Text.Json` in `Pomelo.EntityFrameworkCore.MySql.Json.Microsoft`, so that we can specify the exact version that we use.

@bricelam Is there any other reason why `EFCore.SqlServer.Abstractions` is explicitly referencing `System.Text.Json`?

**Comment by roji** [comment]
FYI @bricelam left Microsoft.

> If EFCore.SqlServer.Abstractions would not be .NET Standard [...]

Which exact package are you referring to here?

In any case, various parts of EF already use System.Text.Json types, and since latest versions target net80 which already has this in the box, we don't reference it; the System.Text.Json is only useful when targeting an older TFM which doesn't yet have it. System.Text.Json can be thought of as similar to System.Net or System.IO at this point.
