### ISSUE TITLE
Support for Schemas

### ISSUE THREAD

**Issue by sherloqholmes** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#191]
In the DbContext class you are able to map en entity to a table. In this mapping you can specify the table name and optionally a schema.

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
      base.OnModelCreating(modelBuilder);

      modelBuilder.Entity<Employee>(e => { e.ToTable("employees", "hrm"); });
      modelBuilder.Entity<Job>(e => { e.ToTable("jobs", "jobs"); });
}
```

The schema parameter is being ignored.
In some MySQL Clusters databases are being used as a schema, where - within one connection - you are able to switch between databases.

Would it be possible to use the schema to switch between databases within one SQL connection?
So you are able to create queries like this:

```
select job.title from hrm.employees
inner join jobs.jobs as job on job.id = employee.jobId
limit 1

```

**Comment by caleblloyd** [comment]
Initial support was added in #236.  Fully tested support will come in #246, and this will be in `1.1.1`
