### ISSUE TITLE
Unnecessary migration is generated after update to 8.0.2

### ISSUE THREAD

**Issue by karuakun** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1920]
### Steps to reproduce
After upgrading from PomeloMySQL 7.0.0 to 8.0.2, an unwanted migration script is generating scripts even though there is no change in Entity.

### The issue
NET 7.0 created tables in the database with the following Entity and DbContext.

```
public class Blog
{
    public int Id { get; set; }
    [StringLength(100)]
    public string Name { get; set; } = null!;
}

public class AppDbContext: DbContext
{
    public DbSet<Blog> Blogs => Set<Blog>();
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }
}
```

```Program.cs
builder.Services.AddDbContext<AppDbContext>(context =>
{
    context.UseMySql(
        "server=localhost; port=3306; database=db; user=root; password=password",
        new MySqlServerVersion("8.0.0"));
});
```

We then upgraded to .NET 8.0 with the following changes and updated the Pomelo version to 8.0.2.

```diff
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
-    <TargetFramework>net6.0</TargetFramework>
+    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
-    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.18">
+    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
-    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="7.0.0" />
+    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />

    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

</Project>
```

```diff
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-ef": {
-      "version": "7.0.18",
+      "version": "8.0.4",
      "commands": [
        "dotnet-ef"
      ]
    }
  }
}
```

No changes were made to Entity or DbContext, and the following commands were executed.

```
dotnet ef migrations add net8
```

Unexpected changes have been added to the Migration Script

```
    /// <inheritdoc />
    public partial class Net8 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Blogs",
                type: "int",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Blogs",
                type: "int",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .OldAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
        }
    }
```

### Further technical details

MySQL version: 8.0.0
Operating system: Windows 11
Pomelo.EntityFrameworkCore.MySql version: 8.0.2
Microsoft.AspNetCore.App version: 8.0.0

Other details about my project setup:

**Comment by karuakun** [comment]
The snapshot has the following differences

```diff
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
+using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
-                .HasAnnotation("ProductVersion", "7.0.18")
+                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

+            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);
+
            modelBuilder.Entity("Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

+                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
+
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
```

**Comment by karuakun** [comment]
I'm sorry. It was a duplicate, so I'll Close it.
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1895

**Comment by Todilo** [comment]
I am sorry but what exactly was the solution? What rows did you delete, the 
MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);
?
And then the altercolumns ?

I am having the same issue and I have made 0 code change except migrating to new version of dotnet.

**Comment by karuakun** [comment]
@Todilo 

The following procedure was used to update the software.

This work assumes that there are no changes involving intentional migration to Entity before and after the Pomello version upgrade; do not include any work other than the Pomello version upgrade.

- 1. upgrade to Pomello 8.0.2
- 2. create a new empty migration (this will add unnecessary migration scripts for the Id column and update the current snapshot)
- 3. delete all of Up and Down, since Entity does not contain any intentional migrations and the migration scripts added in 2 are not needed. Leave the Snapshot as it is important.
- 4. update the database locally just to be sure and verify that no DDLs of any kind are issued.

**Comment by Todilo** [comment]
> @Todilo
> 
> The following procedure was used to update the software.
> 
> This work assumes that there are no changes involving intentional migration to Entity before and after the Pomello version upgrade; do not include any work other than the Pomello version upgrade.
> 
> * 1. upgrade to Pomello 8.0.2
> * 2. create a new empty migration (this will add unnecessary migration scripts for the Id column and update the current snapshot)
> * 3. delete all of Up and Down, since Entity does not contain any intentional migrations and the migration scripts added in 2 are not needed. Leave the Snapshot as it is important.
> * 4. update the database locally just to be sure and verify that no DDLs of any kind are issued.

Thank you @karuakun ! Works great!
