### ISSUE TITLE
One to many relation generates a 1+n query

### ISSUE THREAD

**Issue by pkiers** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#193]
### Steps to reproduce
I am created the following models
```
public class Account
{
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    public string Name { get; set; }

    public List<Site> Sites { get; set; }
}

public class Site
{
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    public string Name { get; set; }

    public Account Account { get; set; }

    [Column("accountId")]
    public int? AccountId { get; set; }
}
```

Then creating DbContext:
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Account>(e => 
    {
        e.ToTable("accounts")
        .HasKey(x => x.Id);
    });

    modelBuilder.Entity<Site>(e =>
    {
        e.ToTable("sites")
        .HasKey(x => x.Id);
    });
            
    modelBuilder.Entity<Site>()
        .HasOne(sites => sites.Account)
        .WithMany(account => account.Sites)
        .HasForeignKey(c => c.AccountId);

    modelBuilder.Entity<Account>()
        .HasMany(c => c.Sites)
        .WithOne(a => a.Account)
        .HasForeignKey(a => a.AccountId);

    base.OnModelCreating(modelBuilder);
}

```
### The issue
When I execute the following linq statement:
`var accounts = context.Accounts.Include(x => x.Sites).Take(10).ToList();`
Then I am generating and 1+n query, one time:
```
SELECT `x`.`id`, `x`.`name`
FROM `accounts`.`accounts` AS `x`
ORDER BY `x`.`id`
LIMIT @__p_0
```
And then 10 times the following query.:
```
SELECT `s`.`id`, `s`.`accountId`, `s`.`name`
FROM `sites`.`sites` AS `s`
INNER JOIN (
    SELECT DISTINCT `x`.`id`
    FROM `accounts`.`accounts` AS `x`
    ORDER BY `x`.`id`
    LIMIT @__p_0
) AS `x0` ON `s`.`accountId` = `x0`.`id`
ORDER BY `x0`.`id`
```

I would have expected a clean LEFT JOIN instead of that. The other way I goes correctly.
`var sites = context.Sites.Include(x => x.Account).Take(10).ToList()`
Generated the correct query
```
SELECT `x`.`id`, `x`.`accountId`, `x`.`name`, `a`.`id`, `a`.`name`
FROM `sites`.`sites` AS `x`
LEFT JOIN `accounts`.`accounts` AS `a` ON `x`.`accountId` = `a`.`id`
LIMIT @__p_0
```

Is this an issue or am I just doing something wrong with my model / context configuration?

Thanks in advanced,
Peter Kiers

**Comment by caleblloyd** [comment]
Which version is this?

**Comment by pkiers** [comment]
@caleblloyd This is with a pull from master branch.

**Comment by caleblloyd** [comment]
A couple things you could try:

You should only need to define the relationship once, Entity Framework should automatically understand the inverse.  I prefer do define relationships on the higher-level model, so I'd use just this definition:

```
modelBuilder.Entity<Account>()
        .HasMany(c => c.Sites)
        .WithOne(a => a.Account)
        .HasForeignKey(a => a.AccountId);
```

Off the top of my head, I think that the position of `Take(n)` may matter.  Maybe try:

`var accounts = context.Accounts.Take(10).Include(x => x.Sites).ToList();`

I would not expect `(n+1)` queries like this from eager loading, so if you still hit the issue after trying these couple things then I can look into this.

**Comment by pkiers** [comment]
@caleblloyd The `Take(n)` position doesn't change the query, even without the `Take(n)` it still generates (n+1) queries. Also when removing the redundant mapping.

**Comment by pkiers** [comment]
@caleblloyd Just an update, the situation is bit diffrent. It does not generate a LEFT JOIN but splits this up into two queries. So not n+1

First query to fetch all accounts.
```
SELECT `x`.`id`, `x`.`name`
FROM `accounts`.`accounts` AS `x`
ORDER BY `x`.`id`
LIMIT @__p_0
```

Second query to fetch all sites for those accounts.
```
SELECT `s`.`id`, `s`.`accountId`, `s`.`name`
FROM `sites`.`sites` AS `s`
INNER JOIN (
    SELECT DISTINCT `x`.`id`
    FROM `accounts`.`accounts` AS `x`
    ORDER BY `x`.`id`
    LIMIT @__p_0
) AS `x0` ON `s`.`accountId` = `x0`.`id`
ORDER BY `x0`.`id`
```

But still feel this would have been faster in a single join query. Or is this the correct behaviour?

**Comment by caleblloyd** [comment]
Ah, 2 queries here is correct. It's how EF is designed by Microsoft.

For ORMs in general, combining everything into a single big query is tough (overlapping column names, repeated rows in HasMany queries) and is not necessarily faster.

**Comment by pkiers** [comment]
Then this can be closed, sorry for the inconvenience.
