### ISSUE TITLE
Syntax error when I try to call stored procedure

### ISSUE THREAD

**Issue by dotWasim** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#194]
I receive this error when I try to execute stored procedure
 

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'getComanies' at line 1

**Controller Code**
```
        public IActionResult GetPorc()
        {
            using (var context = new MyContext())
            {
                return Ok(context.Companies.FromSql("getComanies").ToList());
            }
        }
```

**project.json**
```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Pomelo.EntityFrameworkCore.MySql": "1.1.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

```

**Comment by mguinness** [comment]
You're missing CALL, see [Working with Stored Procedures](https://dev.mysql.com/doc/connector-net/en/connector-net-tutorials-stored-procedures.html).

**Comment by caleblloyd** [comment]
I'd recommend working with Stored Procedure at the Database Driver level, not Entity Framework level.

Here's the reference for MySqlConnector: https://mysql-net.github.io/MySqlConnector/

We don't have documentation on Stored Procedures yet, but the [test cases](https://github.com/mysql-net/MySqlConnector/blob/master/tests/SideBySide.New/StoredProcedureTests.cs) have good examples.

**Comment by mguinness** [comment]
@caleblloyd It should be no problem to use stored procs from EF, with ExecuteSqlCommand for no resultset and FromSql if the resultset matches your model.  For more complicated use cases, then ADO.NET would be your best bet.

**Comment by caleblloyd** [comment]
Correct, it will work.  But it will be executed as `CommandType.Text`

MySqlConnector does a lot of Stored Procedure specific stuff when using `CommandType.StoredProcedure`.  It has procedure caching, automatically assigns parameter direction, and converts return parameters to the proper type.  I'd recommend working with all Stored Procedures using ADO.NET for that reason.

**Comment by dotWasim** [comment]
@mguinness it matches the model, but I don't know what's the problem!

@caleblloyd I already have old DB and stored procedures, but I was planing to use EF to add unavailable queries. I have never used MySqlConnector, so I check it

**Comment by mguinness** [comment]
@dotWasim Have you tried pre-pending CALL?  Also look at your query logs to see what is being executed, the parser is giving a syntax error.
