### ISSUE TITLE
Incorrect migration generated SQL when changing data type to LONGTEXT

### ISSUE THREAD

**Issue by huww98** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#196]
### Steps to reproduce
1. same as #195 
2. delete `[MaxLength(16777215)]` from `Program.cs`
3. run `dotnet ef migrations add RemoveMaxLength`
4. run `dotnet ef migrations script Init`

### The issue

The generated SQL is:
```
ALTER TABLE `Blogs` MODIFY COLUMN `Content` longtext NULL;
ALTER TABLE `Blogs` ALTER COLUMN `Content` DROP DEFAULT;
INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20170220080526_RemoveMaxLength', '1.1.0-rtm-22752');
```
The 2nd line will cause an error `Error Code: 1101. BLOB, TEXT, GEOMETRY or JSON column 'Content' can't have a default value`

### Further technical details

MySQL version: 5.7
Operating system: Windows 10 1607
Pomelo.EntityFrameworkCore.MySql version: 1.1.1-prerelease-10018

**Comment by caleblloyd** [comment]
Shipped in [1.1.1-prerelease-10024](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.1.1-prerelease-10024), please verify the fix in your app
