### ISSUE TITLE
HasMaxLength does not affect generated migration code for classes that derive Identity

### ISSUE THREAD

**Issue by NickThissen** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#200]
### The issue

In the `OnModelCreating` method, the `HasMaxLength` call on the `ModelBuilder` seems to have no effect on the generated migrations if it is applied on a property that inherits an ASP.NET Identity Core class, such as IdentityUser or IdentityRole.

However, it seems to apply the length correctly when used directly on Identity classes that are not derived from, e.g. `IdentityUserLogin<int>` and `IdentityUserToken<int>`.

For example, I extended my IdentityUser class in a class `User` and IdentityRole in a class `IntRole`:

	public class User : IdentityUser<int>
	{
	    public string FullName { get; set; }
	}

    public class IntRole : IdentityRole<int>
    {
        public IntRole() : base() { }
        public IntRole(string name) : base(name) { }
    }

I use the model builder to set some max lengths to make sure the key size remains below 767 bytes.

    private const int MAX_KEY_LENGTH = 127;

    protected override void OnModelCreating(ModelBuilder builder)
    {
        // Make sure keys and indices are not too long
        builder.Entity<User>(e =>
        {
            e.Property(m => m.UserName).HasMaxLength(MAX_KEY_LENGTH);
            e.Property(m => m.NormalizedUserName).HasMaxLength(MAX_KEY_LENGTH);
            e.Property(m => m.Email).HasMaxLength(MAX_KEY_LENGTH);
            e.Property(m => m.NormalizedEmail).HasMaxLength(MAX_KEY_LENGTH);
        });

        builder.Entity<IntRole>(e =>
        {
            e.Property(m => m.Name).HasMaxLength(MAX_KEY_LENGTH);
            e.Property(m => m.NormalizedName).HasMaxLength(MAX_KEY_LENGTH);
        });

        builder.Entity<IdentityUserLogin<int>>(entity =>
        {
            entity.Property(m => m.LoginProvider).HasMaxLength(MAX_KEY_LENGTH);
            entity.Property(m => m.ProviderKey).HasMaxLength(MAX_KEY_LENGTH);
        });
        builder.Entity<IdentityUserToken<int>>(entity =>
        {
            entity.Property(m => m.LoginProvider).HasMaxLength(MAX_KEY_LENGTH);
            entity.Property(m => m.Name).HasMaxLength(MAX_KEY_LENGTH);

        });
    }

After generating a migration, the length of the relevant columns is **incorrect** for the AspNetUser and AspNetRoles tables. However, it is **correctly modified** for the AspNetUserLogin and AspNetUserToken tables:

    dotnet ef migrations add Test

Generated migration code (pieces);

    // Roles: NOT CHANGED!
    migrationBuilder.CreateTable(
        name: "AspNetRoles",
        columns: table => new
        {
            Id = table.Column<int>(nullable: false)
                .Annotation("MySql:ValueGeneratedOnAdd", true),
            ConcurrencyStamp = table.Column<string>(nullable: true),
            Name = table.Column<string>(maxLength: 256, nullable: true),
            NormalizedName = table.Column<string>(maxLength: 256, nullable: true)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_AspNetRoles", x => x.Id);
        });
        
    // Users: NOT CHANGED!
    migrationBuilder.CreateTable(
        name: "AspNetUsers",
        columns: table => new
        {
            Id = table.Column<int>(nullable: false)
                .Annotation("MySql:ValueGeneratedOnAdd", true),
            AccessFailedCount = table.Column<int>(nullable: false),
            ConcurrencyStamp = table.Column<string>(nullable: true),
            CreatedTime = table.Column<DateTime>(nullable: false),
            Email = table.Column<string>(maxLength: 256, nullable: true),
            EmailConfirmed = table.Column<bool>(nullable: false),
            FullName = table.Column<string>(nullable: true),
            LockoutEnabled = table.Column<bool>(nullable: false),
            NormalizedEmail = table.Column<string>(maxLength: 256, nullable: true),
            NormalizedUserName = table.Column<string>(maxLength: 256, nullable: true),
            PasswordHash = table.Column<string>(nullable: true),
            PhoneNumber = table.Column<string>(nullable: true),
            PhoneNumberConfirmed = table.Column<bool>(nullable: false),
            SecurityStamp = table.Column<string>(nullable: true),
            TwoFactorEnabled = table.Column<bool>(nullable: false),
            UserName = table.Column<string>(maxLength: 256, nullable: true)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_AspNetUsers", x => x.Id);
        });
        
    // User Tokens: changed ok!
    migrationBuilder.CreateTable(
        name: "AspNetUserTokens",
        columns: table => new
        {
            UserId = table.Column<int>(nullable: false),
            LoginProvider = table.Column<string>(maxLength: 127, nullable: false),
            Name = table.Column<string>(maxLength: 127, nullable: false),
            Value = table.Column<string>(nullable: true)
        },
        constraints: table =>
        {
            table.PrimaryKey("PK_AspNetUserTokens", x => new { x.UserId, x.LoginProvider, x.Name });
    });

To be clear, the issue is the length of for example the `AspNetUser.Email` and `AspNetRole.Name` columns.

Is this an issue with your provider, with Identity, or just something wrong on my end?

### Further technical details

MySQL version: 5.7
Operating system: Windows 7
Pomelo.EntityFrameworkCore.MySql version: 1.1.0

**Comment by mguinness** [comment]
> Is this an issue with your provider, with Identity, or just something wrong on my end?

It's easy to test against another provider, try to see if you can repro using the following:

`Install-Package SapientGuardian.EntityFrameworkCore.MySql`

**Comment by NickThissen** [comment]
Probably should have mentioned this, but I have the same issue with SapientGuardian. That might point to it being my mistake but I dont see it. Could be just an oversight in both providers?

**Comment by mguinness** [comment]
Try posting this issue at [ASP.NET Core Identity](https://github.com/aspnet/Identity)?
