### ISSUE TITLE
Optimistic concurrency

### ISSUE THREAD

**Issue by flipchart** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#205]
With SQL Server, I can use the following mapping to get an optimistic concurrency column that is updated on every insert/update:

``` C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder
        .Entity(typeof(Foo))
        .Property<byte[]>("Timestamp")
        .ValueGeneratedOnAddOrUpdate()
        .IsConcurrencyToken()
        .IsRequired();
}
```

When I insert, the `Timestamp` value on my entity can be null and SQL Server will generate a value. 

I don't have much experience in MySQL, but [people][1] [recommend][2] using the `TIMESTAMP` data type for this purpose. I've tried mapping this with a `byte[]` (just like above) but the value doesn't get generated on insert. How should I map this, and will I even get the same functionality as what I'm used to in SQL Server?

[1]:http://stackoverflow.com/questions/1920796/row-versioning-for-mysql
[2]:http://stackoverflow.com/questions/33224923/does-mysql-have-an-equivalent-of-sql-server-rowversion

**Comment by caleblloyd** [comment]
I'd recommend a MySQL type of `DATETIME(6)`, which is the default mapping for the CLR Type `DateTime` [example](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Models/GeneratedTypes.cs#L84-L85)

`ValueGeneratedOnAddOrUpdate` will work correctly with a `DateTime`
