### ISSUE TITLE
Release 1.1.1

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#208]
- [x] Switch to `msbuild` #206 
- [x] Update Documentation #207 
- [x] Get community feedback on [Pomelo.EntityFrameworkCore.MySql/1.1.1-prerelease-10020](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.1.1-prerelease-10020) and higher to ensure no regressions
- [x] Set a target release date.  Friday March 17th
- [x] Fix #195

**Comment by Kagamine** [comment]
How about 17th？

**Comment by caleblloyd** [comment]
> How about 17th？

Good idea - that's St Patrick's Day in the US.  I'll drink a green beer to celebrate!

**Comment by Kagamine** [comment]
I will fix #195 before 17th.

**Comment by Kagamine** [comment]
Please put off the date, due to there was a important issue https://github.com/mysql-net/MySqlConnector/issues/196

**Comment by huww98** [comment]
@Kagamine Will you fix #196 ? This problem prevents me from building database tables automatically when deploying

**Comment by caleblloyd** [comment]
1.1.1 Milestone is cleared!  I've published [1.1.1-prerelease-10029](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.1.1-prerelease-10029), it is a Release Candidate.

@Kagamine what date should we release?

**Comment by Kagamine** [comment]
just now？

**Comment by caleblloyd** [comment]
I've run some more tests against 1.1.1-prerelease-10029 on another project and I'm happy with it.  I'll let you push the release in myget.  Thanks!

**Comment by mguinness** [comment]
Awesome work guys, thanks for the release!
