### ISSUE TITLE
There is no ForSqlServerIsClustered extend method

### ISSUE THREAD

**Issue by zfkingth** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#222]
code as bellow:
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AppCollection>().HasKey(e => e.Id).ForSqlServerIsClustered(false);
        }
ForSqlServerIsClustered would not be recognized.

![image](https://cloud.githubusercontent.com/assets/4738319/24159755/ed6a866c-0e9a-11e7-9219-faf900de764c.png)

**Comment by mguinness** [comment]
That is implemented for SQL Server provider, not for this provider see [SqlServerIndexBuilderExtensions](https://github.com/aspnet/EntityFramework/blob/f386095005e46ea3aa4d677e4439cdac113dbfb1/src/EFCore.SqlServer/Extensions/SqlServerIndexBuilderExtensions.cs).

It's unclear what version of MySQL you're using, but this article on [clustered indexes](https://dev.mysql.com/doc/refman/5.7/en/innodb-index-types.html) may offer you some guidance.

**Comment by zfkingth** [comment]
@mguinness I'am using MariaDB, does your lib has similiar method controlling the clustered indexes?

**Comment by Kagamine** [comment]
No, we don't have. If you want to make partition, please use Pomelo.EntityFrameworkCore.MyCat.
