### ISSUE TITLE
Access denied for user 'myuser'@'172.17.0.1' (using password: NO)

### ISSUE THREAD

**Issue by SergioRius** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#224]
Executing `dotnet ef database drop -f` from command line returns `Access denied for user 'myuser'@'172.17.0.1' (using password: NO)` while all other migrations statements execute without issue.

The testing solution uses a docker container for a MySql database. It has the model in a separate assembly as per [this](http://www.michael-whelan.net/ef-core-101-migrations-in-separate-assembly/) article.

This is the DbContext configuration class:

    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;

    namespace S3.DAL.Data
    {
        public class ApplicationDbContextFactory : IDbContextFactory<ApplicationDbContext>
        {
            public ApplicationDbContext Create(DbContextFactoryOptions options)
            {
                var builder = new DbContextOptionsBuilder<ApplicationDbContext>();
                builder.UseMySql("server=localhost;database=mydatabase;uid=myuser;pwd=mypassword;");
                return new ApplicationDbContext(builder.Options);
            }
        }
    }

Changing "myuser" for any non-existent user changes the error message for "Access denied for user 'nouser'@'172.17.0.1' (using password: YES)" (Notice using password)

This is the output:

> >dotnet ef database drop -f
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:00.75
> Dropping database 'mydatabase'.
> MySql.Data.MySqlClient.MySqlException: Access denied for user 'myuser'@'172.17.0.1' (using password: NO)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
>    at MySql.Data.Serialization.MySqlSession.<ConnectAsync>d__22.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__57.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__11.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.Open()
>    at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalConnection.DoOpen()
>    at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalConnection.Open()
>    at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlDatabaseCreator.Delete()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureDeleted()
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.DropDatabase(String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.DropDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> Access denied for user 'myuser'@'172.17.0.1' (using password: NO)

This is the output for example for an update:

> >dotnet ef database update
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:00.75
> Applying migration '20170322101829_Initial'.
> Done.

This is very strange. there's something more that I can make for diagnosing?

### Further technical details

MySQL version:  5.7
Operating system: Windows / .NET Core / docker for windows
Pomelo.EntityFrameworkCore.MySql version: 1.1.1-prerelease-10021

**Comment by Kagamine** [comment]
Are you using mysql on azure？

**Comment by SergioRius** [comment]
No. I'm executing docker for windows locally.

 This is the docker compose file:
  version: '2'

  services:
    s3_db:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: mypassword
        MYSQL_DATABASE: mydatabase
        MYSQL_USER: myuser
        MYSQL_USER_PASSWORD: mypassword
      ports:
        - "3306:3306"

    s3.core:
      depends_on:
      - s3_db
      image: s3.core
      build:
        context: ./S3.Core
        dockerfile: Dockerfile
      ports:
        - "5000:80"
      links:
      - s3_db

I'm having this issue using both myuser and root. But it's only failing at dropping the database. In packege manager migrations commands they all work.

**Comment by AlfonzAlfonz** [comment]
It seems when I edit database manually with:
```sql
alter table db.SelectValue modify Id int(11) AUTO_INCREMENT;
alter table db.Selects modify Id int(11) AUTO_INCREMENT;
```
It works fine.

**Comment by xepher** [comment]
I have same issue.
Notice the server ip.

> dotnet ef database drop -v

Part of log:

> Are you sure you want to drop the database 'xxx' on server '**_127.0.0.1_**'? (y/N)
> y
> Finding DbContext classes...
> Using context 'XXXContext'.
> Dropping database 'xxx'.
> Opening connection to database 'mysql' on server '**_127.0.0.1_**'.
> Opening connection to database 'mysql' on server '**_127.0.0.1_**'.
> MySql.Data.MySqlClient.MySqlException: Access denied for user 'root'@'**_172.17.0.1_**' (using password: NO)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
>    at MySql.Data.Serialization.MySqlSession.<ConnectAsync>d__22.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__55.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__11.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MySql.Data.MySqlClient.MySqlConnection.Open()
>    at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalConnection.DoOpen()
>    at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalConnection.Open()
>    at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migration
> Commands, IRelationalConnection connection)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlDatabaseCreator.Delete()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureDeleted()
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.DropDatabase(String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.DropDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> Access denied for user 'root'@'**_172.17.0.1_**' (using password: NO)
>

**Comment by SergioRius** [comment]
For the while, I've done the following batch file in the project root folder that does the same job:

    dotnet ef database update 0
    dotnet ef migrations remove
    dotnet ef migrations add "Initial"
    dotnet ef database update
    @pause

Rollback to 0 or to a known named migration.
Recreate initial or your named migration.
The mysql container and database is created by the docker compose file every time the project is run.

**Comment by caleblloyd** [comment]
I just tested this through docker and it works with the correct permissions in mysql.  You need to give your mysql user permissions:

```
GRANT ALL ON *.* TO 'your_user'@'172.17.0.1';
```

**Comment by hidayatulfakhri** [comment]
> I just tested this through docker and it works with the correct permissions in mysql. You need to give your mysql user permissions:
> 
> ```
> GRANT ALL ON *.* TO 'your_user'@'172.17.0.1';
> ```

so where i can put that command sir?

**Comment by Elio-Shyti** [comment]
> > I just tested this through docker and it works with the correct permissions in mysql. You need to give your mysql user permissions:
> > ```
> > GRANT ALL ON *.* TO 'your_user'@'172.17.0.1';
> > ```
> 
> so where i can put that command sir?

you run it inside the mysql terminal.
But that didn't worked for me!

**Comment by lauxjpn** [comment]
@Elio-Shyti Do you have any connection issues?

**Comment by Elio-Shyti** [comment]
> 
> 
> @Elio-Shyti Do you have any connection issues?

@lauxjp I don't have connection issues. I tried create again the the 'root'@'172.17.0.1' user and gave him all privileges again. Then it worked for me. Maybe I had done something wrong before.
Thank you!
