### ISSUE TITLE
AlterDatabase().Annotation not effect

### ISSUE THREAD

**Issue by zfkingth** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#225]
### Steps to reproduce
add a migration as follow:

    public partial class second : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            //migrationBuilder.AlterDatabase().Annotation("COLLATE", "'utf8_general_ci'");
             migrationBuilder.Sql(@"ALTER DATABASE smims COLLATE = 'utf8_general_ci';");
        }
    }

### The issue
migrationBuilder.AlterDatabase().Annotation("COLLATE", "'utf8_general_ci'");
the above code doesn't have effect。

But if I use sql directly then have effect，as follow:
migrationBuilder.Sql(@"ALTER DATABASE smims COLLATE = 'utf8_general_ci';");

How to use "AlterDatabase().Annotation" to alter database or get the database name in "Up(MigrationBuilder migrationBuilder)" function, and then alter database by SQL statement directly?

 
MySQL version:  mariaDB  	10.1.22-MariaDB-1~xenial mariadb.org binary distribution
Operating system: ubuntu server 16.04 LTS
Pomelo.EntityFrameworkCore.MySql version: 1.1.1-prerelease-10021

**Comment by Kagamine** [comment]
Close this since it was related to #84
