### ISSUE TITLE
Issues in migrations when using entities inheritance

### ISSUE THREAD

**Issue by SergioRius** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#229]
When using a base class for some entities that share several fields, the resulting migration has the following problems:

Only the base class with all the fields is created instead of the child entities.
You can force the entities creation by using `builder.Entity<myEntity>(e => { e.ToTable("MyEntity"); });` for every entity.

Then, if the Id key field is included on the base class, it isn't marked as a key.
Child table:
![image](https://cloud.githubusercontent.com/assets/1693727/24293655/1eb40e42-1093-11e7-97a8-657fca5c95f8.png)

Independant table example:
![image](https://cloud.githubusercontent.com/assets/1693727/24293834/f753e61e-1093-11e7-9ba6-1dd29e353471.png)

Also, I just noticed that common fields between child tables are ommited. This is the table definition for the first capture. Notice the lack of several fields on the table in DB:

    public class Customer : EntityBase
    {
        public Customer()
        {
            CustomerContacts = new HashSet<CustomerContact>();
        }

        //Commented fields on EntityBase
        //[Key]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        //public Guid Id { get; set; }

        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        //public DateTimeOffset CreationDate { get; set; }

        [Required]
        public string Code { get; set; }

        [MaxLength(50)]
        [Display(Name = "Nombre")]
        public string Name { get; set; }

        [MaxLength(50)]
        public string Brand { get; set; }

        public byte[] Avatar { get; set; }

        [MaxLength(15)]
        public string IC { get; set; }

        [MaxLength(100)]
        public string Address { get; set; }

        [MaxLength(30)]
        public string City { get; set; }

        [MaxLength(11)]
        public string PostalCode { get; set; }

        [MaxLength(30)]
        public string State { get; set; }

        [MaxLength(30)]
        public string Country { get; set; }

        public virtual ICollection<CustomerContact> CustomerContacts { get; set; }

        public virtual ICollection<Attachment> Attachments { get; set; }
    }

### Further technical details

MySQL version: 5.7
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 1.1.1-prerelease-10024

**Comment by SergioRius** [comment]
The generated migration has the missing fields and pk definition but still isn't created:

            migrationBuilder.CreateTable(
                name: "Customers",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false)
                        .Annotation("MySql:ValueGeneratedOnAdd", true),
                    Address = table.Column<string>(maxLength: 100, nullable: true),
                    Avatar = table.Column<byte[]>(nullable: true),
                    Brand = table.Column<string>(maxLength: 50, nullable: true),
                    City = table.Column<string>(maxLength: 30, nullable: true),
                    Code = table.Column<string>(nullable: false),
                    Country = table.Column<string>(maxLength: 30, nullable: true),
                    CreationDate = table.Column<DateTimeOffset>(nullable: false)
                        .Annotation("MySql:ValueGeneratedOnAddOrUpdate", true),
                    IC = table.Column<string>(maxLength: 15, nullable: true),
                    Name = table.Column<string>(maxLength: 50, nullable: true),
                    PostalCode = table.Column<string>(maxLength: 11, nullable: true),
                    State = table.Column<string>(maxLength: 30, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Customers", x => x.Id);
                });

Note: After reverting the base class usage, still doesn't create those fields.

**Comment by caleblloyd** [comment]
Relational Inheritance in Entity Framework Core uses Table Per Hierarchy, see here: https://docs.microsoft.com/en-us/ef/core/modeling/relational/inheritance

As far as I know, all of the inheritance specific code is at https://github.com/aspnet/EntityFramework and it just makes calls to our library for the MySQL syntax

**Comment by SergioRius** [comment]
Very interesting. So I guess for some time being I will not be able to save some code.
What do you think about the missing columns. I've reverted it all and still there are not created. Do you think there may be something cached there?
Migrations are deleted and even the DB and mysql server are also dropped.
