### ISSUE TITLE
How to use Pomelo.EntityFrameworkCore.MySql

### ISSUE THREAD

**Issue by HeikoZhang** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#23]
I download the zip file, but I don't know how to use it to connect to mysql using ef core, Anyone could give me a full sample that I could directly run?

**Comment by Kagamine** [comment]
@HeikoZhang You needn't download the source, just do the following instructions will make you connect to mysql by using ef core.

1. Create a NuGet.config file in your project root directory.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="Pomelo" value="https://www.myget.org/F/pomelo/api/v3/index.json" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2" />
  </packageSources>
</configuration>
```

2. Add `Pomelo.EntityFrameworkCore.MySql` into your project.json file.

```json
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    },
    "Pomelo.EntityFrameworkCore.MySql": "1.0.0" 
    ...
  },
```

3. Execute `dotnet restore`

4. Configure startup class:

ConfigureServices:

``` c#
services.AddDbContext<YourContext>(x => x.UseMySql("server=localhost;database=yourdb;uid=root;pwd=123456"));
```

5. Inject YourContext in a controller:

```c#
public IActionResult Index([FromServices] YourContext DB)
{
    return View(DB.Articles.ToList());
}
```

**Comment by HeikoZhang** [comment]
thanks for your help!

**Comment by HeikoZhang** [comment]
still don't know how to use it, thanks

**Comment by Kagamine** [comment]
Are you using this in ASP.NET Core 1.0.0 rtm?

**Comment by vitoryugulis** [comment]
I'm having issues using your code, @yukozh .

> System.InvalidOperationException: 'Cannot resolve scoped service 'Repository.EF.simysatContext' from root provider.'

It gives me this error on this part of the code:

```
public async void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.AddConsole();

    ...

    var DB = app.ApplicationServices.GetRequiredService<YourContext>();
    DB.Database.EnsureCreated();
}
```

**Comment by vitoryugulis** [comment]
For anyone who stumbles in this issue, i found the following solution...

This were my default BuildWebHost() in Program.cs:

```
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
```

I changed to this and it worked.
```
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseDefaultServiceProvider(options =>
                    options.ValidateScopes = false)
                .Build();
```

Heres is where i found the solution: [dotnet core github issue](https://github.com/dotnet/corefx/issues/23604)

**Comment by thangchung** [comment]
@vitoryugulis Thank you for this trick. You're saving my day 👍

**Comment by EKkoGGG** [comment]
@vitoryugulis Thank you

**Comment by EKkoGGG** [comment]
I ues .net core 3.1 to build a web api project

I changed this method and it worked
> public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>()
                    .UseDefaultServiceProvider(options =>options.ValidateScopes = false);
                });
