### ISSUE TITLE
UseMySQL extension method is missing in DbContextOptionsBuilder

### ISSUE THREAD

**Issue by adnan-kamili** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#231]
### Steps to reproduce
In ConfigureServices when I try following:
```
 // Add database Context
            services.AddDbContext<ApplicationDbContext>(options =>
            {
                options.UseMySQL(Configuration.Get<AppOptions>().ConnectionStrings.MySqlProvider);
                options.UseOpenIddict();
            });
```
It doesn't work. Due to DateTimeOffset issue in Sapient I am moving to Pomelo, but UseMySQL extension method is missing. In Sapient 
`using MySQL.Data.Entity.Extensions; `
provided the needed extension.
### The issue
UseMySQL extension method is missing.
```
Exception message:
error CS1061: 'DbContextOptionsBuilder' does not contain a definition for 'UseMySQL' and no extension method 'UseMy
SQL' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly ref
erence?)
```

### Further technical details

MySQL version: 5.7.17
Operating system: macOS
Pomelo.EntityFrameworkCore.MySql version: 1.1.1

Other details about my project setup:

**Comment by caleblloyd** [comment]
You must import:

```
using Microsoft.EntityFrameworkCore;
```

**Comment by adnan-kamili** [comment]
@caleblloyd  I tried but still the same error

**Comment by caleblloyd** [comment]
It's case-sensitive, `UseMySql`

Here's an [example](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Startup.cs#L48-L52)

**Comment by adnan-kamili** [comment]
Thanks, it worked

**Comment by humanusdeus** [comment]
The link doesn't seem to work anymore and I am having the same issue, can you specify how did you solve it?

**Comment by mguinness** [comment]
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/302ff5db432373ee2091b3f471f9f64bf4ddb4fb/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Startup.cs#L56-L60
