### ISSUE TITLE
Namespace of this library?

### ISSUE THREAD

**Issue by Daniel15** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#234]
It's very confusing that this library has classes in the `Microsoft.EntityFrameworkCore` namespace, as it conflates Entity Framework classes with this library's classes. Is there a reason for this? Could the classes be moved into a `Pomelo.EntityFrameworkCore.MySql` namespace instead?

**Comment by Kagamine** [comment]
Following the postgres, sqlserver and sqlite

**Comment by Daniel15** [comment]
@Kagamine  - Are those third-party as well, or are they supported by Microsoft? I think that's the primary difference.

**Comment by Kagamine** [comment]
postgres is not. In another hand, UseMySql is extending DbContextOptionBuilder which defined in Ms.EfCore.

**Comment by Kagamine** [comment]
I think this project will join .net foundation soon.

**Comment by Daniel15** [comment]
Thanks for the explanation :)
