### ISSUE TITLE
How to use non-password authentication in the connection string?

### ISSUE THREAD

**Issue by LiangZugeng** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#235]
### Steps to reproduce
This is a question really instead of a bug or issue report.

### The issue
In the connection string it needs the username and password to authenticate against MySQL, I wonder if there is anyway to use non-password authentication? In Windows there may be possible to use the integrated authentication, however our production server is on Linux. We intended to increase the security and pre-configure an encrypted file with the username and password and save it on the server for the connection string to use so the clear-text username and password won't be saved in the appsettings.json on the disk. Hope someone could give me a hint.

### Further technical details

MySQL version: 5.7.17
Operating system: Ubuntu Server 16.04 LTS
Pomelo.EntityFrameworkCore.MySql version: 1.1.1-prerelease-10026
.NET Core Version: 1.1.1

**Comment by caleblloyd** [comment]
This is a common issue, typically it's solved by using environment variables or secrets.

You can build the connection string problematically by reading environment variables or files.  For example, one of my projects uses Kubernetes for deployment, which has [secrets](https://kubernetes.io/docs/user-guide/secrets/) as part of the deployment specification.  I store the credentials in these secrets and keep them out of the main repository.

The secrets get mounted as files, and I have a [JSON configuration](https://github.com/caleblloyd/dotnet-core-boilerplate/blob/develop/dotnet/src/App/Common/Config/config.alpha.json) with configuration keys that end in `_file`, denoting that the value should be read from a file.  Finally, I [problematically build the connection string](https://github.com/caleblloyd/dotnet-core-boilerplate/blob/develop/dotnet/src/App/Common/Config/AppConfig.cs#L47-L64) by reading files.

The same thing could be achieved with environment variables.

**Comment by LiangZugeng** [comment]
Thanks @caleblloyd for the answer. I went through the source code you provided, and in the configuration json file there is "password_file": "/etc/secrets/dotvue-blog-db/pass" which points the appconfig.js to read password from the file, so the password doesn't need to be stored in the source repository, however the password is still clear text on the server disk.

We are using Visual Studio Team Services for CI/CD and we are able to tokenize the variables in the configuration files and replace them with actual value during the release process, that's not an issue for us, what we are trying to avoid here is the clear text password saved on server (call us super cautious :)). On Windows we can use Windows Integrated Authentication in the connection string and authorize the service account running the app to access the database with it's own identity so no password will be stored in the app's configuration files, but on Linux for MySQL we are still looking for something like Integrated Authentication or file based authentication like ID_RSA for SSH, specifically for .NET Core apps. Actually mysql cli tool on Linux can use --login-path parameter to use a pre-configured and encrypted password to access the database, I wonder if there is a similar way in the .NET Core app database connection string.

**Comment by caleblloyd** [comment]
Here's a good article on [mysql_config_editor](http://mysqlblog.fivefarmers.com/2012/08/16/understanding-mysql_config_editors-security-aspects/) security.  It makes a very good point:

> This enhancement really isn’t about securing passwords at a file-system level.  Don’t assume that the encryption used will prevent attackers from getting passwords stored in the .mylogin.cnf file if they have read access to it – it absolutely will not.  There are multiple ways to extract the password out of this file, some more complex than others.  Don’t make the mistake of believing that the password storage is safe just because the contents are encrypted.

Encrypting the file will obfuscate it's contents, but if somebody has access to the decryption key, either in the repository or if it's also readable by the same unix user, then it is still not safe.

I'm not aware of any native options that [MySqlConnector](https://github.com/mysql-net/MySqlConnector) (our ADO.NET) implements to interact with integrated authentication on Linux.  You could use a Keyring such as [Seahorse](https://wiki.gnome.org/Apps/Seahorse) to manage your keys on the production machine, and implement some application logic to decrypt a password with a Public Key though.

**Comment by caleblloyd** [comment]
Another option is to limit your MySQL user to the host that you are connecting from.  For example if you connect from `172.17.0.1`:

```
CREATE USER 'your_user'@'172.17.0.1' IDENTIFIED BY 'your_password';
GRANT ALL ON *.* TO 'your_user'@'172.17.0.1';
```

This way even if somebody gets the password, they still can't connect without access to a production machine.  You can use partial wildcards to allow subnets if you have multiple app servers.

**Comment by mguinness** [comment]
> Linux can use --login-path parameter to use a pre-configured and encrypted password to access the database

Be aware that .mylogin.cnf [isn't a secure password store](http://serge.frezefond.com/2013/02/mysql-5-6-credentials-securely-stored/).

You should also be using [SSL](https://dev.mysql.com/doc/refman/5.7/en/secure-connections.html) to encrypt the connection between MySQL client and the server if you want to increase security.

Anyway these security issues are beyond the scope of this library, perhaps visit the [MySQL Forums](http://forums.mysql.com/) for further guidance.

**Comment by LiangZugeng** [comment]
Thanks for the replies and suggestions, after doing some more researching, we are going to implement our own secret user store and provide it as a service for our applications to use, this hopefully will help us deal with such kind of issues once and for all. This issue can be closed and thanks again.

**Comment by tggoo** [comment]
Hello I would be glad to read your opinions to this [question](https://stackoverflow.com/questions/71742985/connection-string-works-with-net-mysqlconnector-but-not-with-usemysql-configura): My goal is to get also credential less connection string but using unix_socket authentication.

Thanks in advance for any replies.
