### ISSUE TITLE
char(16) to GUID - Special Condition

### ISSUE THREAD

**Issue by iChaosren** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#237]
By default, scaffolding of the column type char(16) should convert to Guid.
This is a special condition met in the old default MySql Connector.

Could you please add it as a special condition in the next version of the connector?

**Comment by Kagamine** [comment]
Not all char(16) is GUID. This issue should be discussed.

**Comment by iChaosren** [comment]
Ok,

Here's what I know, feel free to state your case/say why not:

When using the scaffolding tool on pre-Core systems, using the database-first approach, I created a table that contained a **char(16)** and the ADO.NET Code Generator would automatically assume **char(16)** was a **Guid**.

The reason I used **char(16)** in the first place was due to a post on stackoverflow, regarding the best data-type to use for storing a Guid: [http://stackoverflow.com/questions/412341/how-should-i-store-guid-in-mysql-tables](http://stackoverflow.com/questions/412341/how-should-i-store-guid-in-mysql-tables)

I doesn't matter either way. You can change the type to **Guid** and it works the same.
It was more of a convenience change. At the moment it automatically saves anything using the **char** data-type as a **char** C# type. Which is wrong... **char(16)** is an array of 16 chars. (Which a **Guid** will always fill perfectly.)

**Comment by iChaosren** [comment]
Wrong website -_- They're all suppose to be char(36).
[http://stackoverflow.com/questions/968175/what-is-the-string-length-of-a-guid](http://stackoverflow.com/questions/968175/what-is-the-string-length-of-a-guid)
