### ISSUE TITLE
dotnet ef dbcontext scaffold stops executing

### ISSUE THREAD

**Issue by chrisNom** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#238]
### Steps to reproduce
Trying to do a DB first project the command to scaffold db just hangs as seen in the picture:

![pomelo](https://cloud.githubusercontent.com/assets/21661957/24463984/1e55fbc8-14b1-11e7-81cc-a1c329a08bd5.png)

### Further technical details

MySQL version: 5.6
Operating system:  Win 8.1
Pomelo.EntityFrameworkCore.MySql version: 1.1.0

**Comment by mguinness** [comment]
@chrisNom Can you look at issue https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/149?  Let us know if that doesn't help.

**Comment by mguinness** [comment]
Can you share the schema of the artifacts table?  FWIW, tables must have a PK for scaffolding to work.

**Comment by chrisNom** [comment]
CREATE TABLE `artifacts` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Details` text,
  `TypeID` int(11) NOT NULL,
  `ParentType` varchar(50) DEFAULT NULL,
  `ParentID` int(11) DEFAULT NULL,
  `ByUser` varchar(50) DEFAULT NULL,
  `Filename` varchar(255) DEFAULT NULL,
  `filedata` longblob,
  `filesize` int(11) DEFAULT NULL,
  `CreatedOn` datetime NOT NULL,
  `LastUpdatedOn` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ArtifactType_idx` (`TypeID`),
  CONSTRAINT `FK_ArtifactType` FOREIGN KEY (`TypeID`) REFERENCES `artifacttypes` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=221 DEFAULT CHARSET=utf8;

**Comment by chrisNom** [comment]
But I tried even a more simple one:

```
CREATE TABLE `offenseorigins` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `Description` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
```

The result is the same

**Comment by mguinness** [comment]
I was able to scaffold those two tables w/o issue using Pomelo 1.1.0 against MySQL 5.1 on Windows 10:

`C:\Projects\ConsoleApp3>dotnet ef dbcontext scaffold "server=XXX" Pomelo.EntityFrameworkCore.MySql -o Models`

The tool output generated three files (the two tables and the context), see attached [Models.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/886566/Models.zip) file.

**Comment by chrisNom** [comment]
Ok, so I guess my problem cannot be reproduced.
Yet, mysql 5.1?? is nt it too old??

Thank you for your efforts anyway!
