### ISSUE TITLE
Substring in Select returns empty value

### ISSUE THREAD

**Issue by adnan-kamili** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#239]
### Steps to reproduce
Following is my Select projection:
```
        public static Expression<Func<ApplicationRole, ApplicationRoleDto>> SelectProperties = (role) => new ApplicationRoleDto
        {
            Id = role.Id,
            Name = role.Name.Substring(0, role.Name.Length - role.TenantId.Length),
            Description = role.Description,
            Claims = role.Claims.Select(claim => claim.ClaimValue).ToList(),
            CreatedAt = role.CreatedAt,
            ModifiedAt = role.ModifiedAt
        };
```
### The issue
In the Sapient it was working fine, but after I switched to Pomelo it always returns the **Name** property empty.

When I checked the generated query it is trying to do the **Substring** operation using SQL and returns incorrect result.

```
SELECT `t`.`Id`, SUBSTRING(`t`.`Name`, 0, CHAR_LENGTH(`t`.`Name`) - CHAR_LENGTH(`t`.`TenantId`)), `t`.`Description`, `t`.`Create
dAt`, `t`.`ModifiedAt` ...
```

### Further technical details

MySQL version: 5.6
Operating system: macOS
Pomelo.EntityFrameworkCore.MySql version:1.1.1

**Comment by mguinness** [comment]
@adnan-kamili What SQL does Sapient generate?

**Comment by adnan-kamili** [comment]
It does it simple:

```
SELECT `t`.`Id`, `t`.`Name`, `t`.`TenantId`, `t`.`Description`, `t`.`CreatedAt`, `t`.`ModifiedAt`
      FROM ...
```

and leaves Substring operation to C# which works as expected.

**Comment by mguinness** [comment]
OK, but that isn't performant when dealing with large tables.  Without seeing data it's hard to determine the issue, but what does the following SQL give?

```SQL
SUBSTRING(`t`.`Name`, 1, CHAR_LENGTH(`t`.`Name`) - CHAR_LENGTH(`t`.`TenantId`))
```

**Comment by adnan-kamili** [comment]
Even following returns an empty string, if I hardcode the values in Substring(0,5)

`SELECT `t`.`Id`, SUBSTRING(`t`.`Name`, 0, 5), `t`.`Description`, `t`.`CreatedAt`, `t`.`ModifiedAt``

**Comment by adnan-kamili** [comment]
I fixed my issue temporarily by using Replace instead of Substring, but you should consider fixing it.

Name = role.Name.Replace(role.TenantId,string.Empty),

**Comment by mguinness** [comment]
Try hardcoding the Substring(1,5) instead and see what you get

**Comment by adnan-kamili** [comment]
Worked fine but that is a bug, the semantics of C# Substring and SQL Substring are not aligned, you need to add an offset in your code.

**Comment by mguinness** [comment]
Yes, that was why I asked and what I wanted to confirm.
