### ISSUE TITLE
Adding data with romanian diacritics aren't saved properly

### ISSUE THREAD

**Issue by florinciubotariu** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#243]
### Steps to reproduce
Execute dbContext.Database.ExecuteSqlCommand(@"INSERT INTO Table VALUES("ț')");
### The issue
When I update a row with data that contains romanian [diacritics](http://collation-charts.org/mysql60/mysql604.utf8_romanian_ci.html) that specific character is replaced with 
Äƒ, È›, Åž, etc.
I'm using MySQL Workbench to see the results.
When retrieving the data, even though it is saved as I said above, correct characters are returned (romanian diacritics).
Adding manually INSERT INTO Table VALUES("ț') with MySQL Workbench works good.

`show variables like 'character_set_database';` returns utf8
The table  and the column has utf8- utf8_romanian_ci collation.

### Further technical details

MySQL version: version 14.14 distrib 5.1.73
Operating system: Windows 10 ASP.NET Core project, MySQL on CentOS 6.8
Pomelo.EntityFrameworkCore.MySql version: 1.1.0

**Comment by florinciubotariu** [comment]
Update:
dbContext.Database.ExecuteSqlCommand(@"INSERT INTO Table VALUES(**N**"ț')"); works.
I've tried to set IsUnicode() on the entity but it still doesn't work.

**Comment by florinciubotariu** [comment]
[MySqlMaxLengthMapping](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/854e79dca7d33b4c333972ed4a903822432071a6/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlMaxLengthMapping.cs) has a constructor that accepts a _boolean unicode_ value.
In [MySqlTypeMapper](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/2db9a1a9d748a268a451d162080ccf3089a537b3/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlTypeMapper.cs) we never instantiate a MySqlTypeMapper using the constructor that accepts unicode boolean.
Should that help us to solve the issue? I didn't found where the **N** prefix is added when creating the query.

**Comment by Kagamine** [comment]
I've tested the char with utf8 -- UTF-8 Unicode it works fine.
