### ISSUE TITLE
How to code-first with explicitly defined DB table fields sequence?

### ISSUE THREAD

**Issue by chrisNom** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#248]
### Steps to reproduce
I tried to add Column Order annotation like this:
```     
        public class ApplicationRole
	{
                [Column(Order = 0)]
                public int ID { get; set; }

		[StringLength(45)]
                [Column(Order = 1)]
		public string Name { get; set; }

		[StringLength(500)]
                [Column(Order = 2)]
		public string Description { get; set; }
	}
```
But it was not succesfull, it created a table like this:

> CREATE TABLE `applicationroles` (
>   `ID` int(11) NOT NULL AUTO_INCREMENT,
>   `Description` varchar(500) DEFAULT NULL,
>   `Name` varchar(45) DEFAULT NULL,
>   PRIMARY KEY (`ID`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

### Further technical details

MySQL version: 5.6
Operating system: win8.1
Pomelo.EntityFrameworkCore.MySql version: "1.1.0"

Other details about my project setup:
"Microsoft.EntityFrameworkCore": "1.1.0",

**Comment by Kagamine** [comment]
MySQL does not support sequence.

**Comment by lauxjpn** [comment]
@chrisNom If I understand correctly, this issue is not about "sequences" (e.g. `CREATE SEQUENCE`), but about the order the columns are being generated (e.g. in a `CREATE TABLE` statement) in. It my assessment correct?
