### ISSUE TITLE
Relationships doesn't load any data

### ISSUE THREAD

**Issue by SergioRius** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#250]
### Steps to reproduce
I have the following models on a project set-up for code-first:

    public class Customer
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        public string FirstName { get; set; }

        public virtual ICollection<CustomerContact> Contacts { get; set; } = new List<CustomerContact>();
    }

    public class CustomerContact
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        public string FirstName { get; set; }

        //[ForeignKey("Customer")]
        public Guid CustomerId { get; set; }

        public virtual Customer Customer { get; set; }
    }

I don't configure anything in OnModelCreating.

### The issue
Getting the data in controller like:

            var customer = await _context.Customers
                //.Include(x => x.Contacts)
                //.Include(x => x.Records)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            ViewBag.Contacts = customer.Contacts.Count; //Always null or zero depending on implementation.

I can't get anything from customer.Contacts (or any other relation setup on the project). I've tried with the same implementation than in the Yuuko blog example (commented code) without success.
I would bet that I'm doing anything wrong but I've already tried anything from right to left and upsidedown without result.

_If there's a forum or someplace else to ask for questions, please let me know. Thanks._

### Further technical details

MySQL version: 5.7
Operating system: Docker for windows
Pomelo.EntityFrameworkCore.MySql version: 1.1.1-prerelease-10028

Other details about my project setup: 

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0" PrivateAssets="All" />
    <PackageReference Include="Pomelo.AspNetCore.Extensions" Version="1.1.0-rtm-10031" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="1.1.1-prerelease-10028" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.1-prerelease-10028" />

    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />

**Comment by Kagamine** [comment]
why annotate .Include & [ForeignKey()]? Eager Load depends on them.

**Comment by SergioRius** [comment]
Kagamine, I also tried with those lines uncommented but doesn't work. I commented them as EFCore documentation doesn't use them.
I will try again with them right now. I understand that all of them should be used.

Relations are created:

    CONSTRAINT `FK_CustomerContacts_Customers_CustomerId` FOREIGN KEY (`CustomerId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE

**Comment by SergioRius** [comment]
This last time it worked. I don't know what it is but it can't be a code problem, because all other relations also started working. This may be a dependencies issue. I had a warning on nuget deps that now doesn't appear.

So it doesn't load linked data for default? Should I always add ".include" (I never used it before)? It's something changed in lazy loading?

**Comment by caleblloyd** [comment]
> So it doesn't load linked data for default? Should I always add ".include" (I never used it before)? It's something changed in lazy loading?

Correct, you either need to Eager Load or Explicit Load.  Lazy loading is not yet implemented in EF Core.  Here's the docs: https://docs.microsoft.com/en-us/ef/core/querying/related-data

**Comment by SergioRius** [comment]
Gotcha. Thanks very much.

**Comment by eldarj** [comment]
Update on this or any other issues, after Lazy loading was implemented in EF Core?

**Comment by Kurtz1993** [comment]
> Lazy loading is now implemented in EF Core.
> Any new update or issue on this?
You need to install `Microsoft.EntityFrameworkCore.Proxies` NuGet, and then enable it by adding

```csharp
services.AddDbContextPool<TrascenderDbContext>(options => options
    .UseLazyLoadingProxies() // <-- This is the important part
    // replace with your connection string
    .UseMySql(Configuration.GetConnectionString("MySQLConneciton"), mySqlOptions => mySqlOptions
        // replace with your Server Version and Type
        .ServerVersion(new ServerVersion(new Version(8, 0, 18), ServerType.MySql))
));
```
