### ISSUE TITLE
MySQL 8.0.1

### ISSUE THREAD

**Issue by Kagamine** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#257]

**Comment by bgrainger** [comment]
@Kagamine Is there a concrete objective you have in mind for this issue?

I've tested MySqlConnector against MySQL Server 8.0.1 and found one bug in the connector: mysql-net/MySqlConnector#242.

**Comment by Kagamine** [comment]
Shipped in 1.1.2-preview-10032

**Comment by bgrainger** [comment]
@Kagamine MySqlConnector 0.18.0 (the latest version on NuGet) doesn't include the MySQL 8.0.1 fixes; I'll update this case when a fixed version is available.

**Comment by bgrainger** [comment]
[MySqlConnector 0.18.1](https://www.nuget.org/packages/MySqlConnector/0.18.1) includes the fixes for MySQL Server 8.0.1.

**Comment by Kagamine** [comment]
@bgrainger Thanks
