### ISSUE TITLE
MySQL Exception Handling

### ISSUE THREAD

**Issue by dansiegel** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#259]
# Issue

This was previously brought up in issue #200. When using AspNetCore.Identity, the entities start throwing an exception for the "Specified key was too long". The error thrown though is quite useless as it provides no context for debugging or fixing the entities.

# Expected Behavior

The exception thrown should include information at least for the Table and/or Property that caused the exception to be thrown. While I may have encountered this in a context that only contained the base Identity Context, it could very quickly become almost impossible to diagnose for a larger schema when you don't even know which model caused the exception to be thrown.

**Comment by caleblloyd** [comment]
The solution here is to use Logging to see which statements are getting executed.

Change `Microsoft` log level to `Information` ([example](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/appsettings.json#L7))

If you don't already have this somewhere, here's some examples:

- [Read a JSON object into a configuration object](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/AppConfig.cs#L17-L31).
- [Add logging to MVC app in Startup.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Startup.cs#L59)
- [Add logging to DBContext if using simple console app with no Startup.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/AppDb.cs#L63)

This will print all SQL statements that are getting executed, and the last one printed will be the one where the exception occurred.
