### ISSUE TITLE
Pomelo doesn't update entities with concurrency tokens

### ISSUE THREAD

**Issue by vaneapp** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#261]
# POCO
``` C#
public class Rate
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public byte Frequency { get; set; }
        public DateTimeOffset RowVersion { get; set; }
    }
```
# Fluent API
``` C#
var rateEntity = modelBuilder.Entity<Rate>();
            rateEntity.HasKey(p => p.Id);
            rateEntity.Property(p => p.Amount);
            rateEntity.Property(p => p.Frequency);
            rateEntity.Property(p => p.RowVersion)
                .ValueGeneratedOnAddOrUpdate()
                .IsConcurrencyToken();
``` 
# Generated Script
``` SQL
CREATE TABLE `Rates` (
    `Id` int NOT NULL AUTO_INCREMENT,
    `Amount` decimal(65, 30) NOT NULL,
    `Frequency` tinyint unsigned NOT NULL,
    `RowVersion` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT `PK_Rates` PRIMARY KEY (`Id`)
);
```

# Update Query generated by POMELO
``` SQL
Executed DbCommand (76ms) [Parameters=[@p0='?', @p2='?', @p4='?', @p6='?'], CommandType='Text', CommandTimeout='0']
UPDATE `Rates` SET `Amount` = @p2, `Frequency` = @p4
WHERE `Id` = @p0 AND `RowVersion` = @p6;
```

# Pomelo version
Pomelo.EntityFrameworkCore.MySql(1.1.1) 

All appears well by the entity isn't update in database.

**Comment by mguinness** [comment]
See discussion on [row versioning](http://stackoverflow.com/questions/40394577/better-way-to-implement-a-row-version-with-ef-core-and-mysql) in SO.

**Comment by vaneapp** [comment]
Hi mguinness,
I saw the discusion on stackoverflow about row versioning. That´s is a trick a patch.
When the Pomelo provider thinks solve this feature transparently how the SQLServer provider solves it?
I mean without extra work.

**Comment by mguinness** [comment]
Please provide some further information for your issue.  The update query you provided only shows parameter placeholders, what is the actual SQL (with values) being run against MySQL?  Also provide the RowVersion field value before you call SaveChanges.  You also didn't mention what version of MySQL you're using and on what OS.
