### ISSUE TITLE
Translation of NewGuid()

### ISSUE THREAD

**Issue by Kazinix** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#265]
### Steps to reproduce
I'm using it for getting random records.
```
_dbContext.Stories
    .Where(s => s.IsPublished)
    .OrderBy(s => Guid.NewGuid())
```
### The issue
Cannot translate to NewGuid() to UUID()

```
warn: Microsoft.EntityFrameworkCore.Query.Internal.MySqlQueryCompilationContextFactory[8]
      The LINQ expression 'orderby NewGuid() asc' could not be translated and will be evaluated locally.
```

### Further technical details

MySQL version: MariaDB 10.1
Operating system: Windows 8
Pomelo.EntityFrameworkCore.MySql version: 1.1.1

**Comment by Kagamine** [comment]
In MySQL order by uuid() will not make your result in a random order. You have to use order by rand()

**Comment by Kazinix** [comment]
@Kagamine  Figured that out just now. BTW, don't you think it's still necessary to add NewGuid for other use?

**Comment by sphildreth** [comment]
> In MySQL order by uuid() will not make your result in a random order. You have to use order by rand()

How does do this in code? ".OrderBy(x => rand())" ?
