### ISSUE TITLE
Welcome to join the discussion email group

### ISSUE THREAD

**Issue by Kagamine** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#266]
Now, everyone of the Pomelo.EntityFrameworkCore.MySql users can join this email group by the following link. 

https://outlook-sdf.office.com/owa/pomeloentityframeworkcoremysql@service.microsoft.com/groupsubscription.ashx?action=join&guid=06050988-4493-4768-241e-7229e9470481

And also, if you have any questions, please feel free to send an email to pomeloentityframeworkcoremysql@service.microsoft.com.

**Comment by pkiers** [comment]
Somehow after the login the page just ends up in some refresh loop.
