### ISSUE TITLE
Bulk inserts don't use INSERT INTO VALUES (...) format

### ISSUE THREAD

**Issue by ErikSchierboom** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#268]
### Steps to reproduce

Create a simple DbContext and add three records in a single SaveChanges call:

```csharp
public class Program
{
	public class MySqlContext : DbContext
	{
		public DbSet<Person> Persons { get; set; }

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseMySql(@"Server=localhost;Database=PerformanceTest;Uid=test;Pwd=test;");
		}
	}

	public class Person
	{
		[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
		public int Id { get; set; }
		public string Name { get; set; }
	}

	public static void Main(string[] args)
	{
		var persons = new[]
		{
			new Person { Id = 1, Name = "Erik" },
			new Person { Id = 2, Name = "Jens" },
			new Person { Id = 3, Name = "Elmar" },
		};

		using (var mySqlContext = new MySqlContext())
		{
			foreach (var person in persons)
				mySqlContext.Add(person);

			mySqlContext.SaveChanges();
		}
	}
}
```

I have created a Gist [here](https://gist.github.com/ErikSchierboom/cf3f73740b6e088f2fb6e35fef32675f).

### The issue

As the SaveChanges call only has to deal with inserting values, I would expect the values to be inserted using the INSERT INTO .. VALUES (...) syntax. However, the records are inserted one by one, with one query being executed for each record:

```
info: Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (14ms) [Parameters=[@p0='?', @p2='?' (Size = 8000)], CommandType='Text', CommandTimeout='0']
      INSERT INTO `Persons` (`Id`, `Name`)
      VALUES (@p0, @p2);
      SELECT ROW_COUNT();
info: Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (0ms) [Parameters=[@p0='?', @p2='?' (Size = 8000)], CommandType='Text', CommandTimeout='0']
      INSERT INTO `Persons` (`Id`, `Name`)
      VALUES (@p0, @p2);
      SELECT ROW_COUNT();
info: Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (0ms) [Parameters=[@p0='?', @p2='?' (Size = 8000)], CommandType='Text', CommandTimeout='0']
      INSERT INTO `Persons` (`Id`, `Name`)
      VALUES (@p0, @p2);
      SELECT ROW_COUNT();
```

If I use the exact same code but with a SqlServer backend, only one INSERT INTO .. VALUES (...) query is executed:

```
info: Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory[1]
      Executed DbCommand (56ms) [Parameters=[@p0='?', @p1='?' (Size = 4000), @p2='?', @p3='?' (Size = 4000), @p4='?', @p5='?' (Size = 4000)]
, CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Persons] ([Id], [Name])
      VALUES (@p0, @p1),
      (@p2, @p3),
      (@p4, @p5);
```

Needless to say, the single INSERT INTO .. VALUES (...) query performs a lot better than the individual INSERT queries. I would love the MySQL provider to use the INSERT INTO .. VALUES (...) syntax for multiple INSERT statements.

### Further technical details

MySQL version: 10.1 (MariaDB)
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 1.1.2-preview-10038

**Comment by caleblloyd** [comment]
You need to specify MaxBatchSize when you configure the provider. Example:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/AppDb.cs#L61

You are correct to not include an auto increment ID. Auto increment​ IDs will not use batching because each ID must be queried as it is inserted.

**Comment by ErikSchierboom** [comment]
Thanks for the heads-up! Works perfectly.
