### ISSUE TITLE
if (dto.JsonObject == null) throws NullReferenceException when dto is not null

### ISSUE THREAD

**Issue by HongyanShen** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#278]
And there are values stored in the jsonobject.the jsonobject is of type JsonObject<Dictionary<string, object>>

**Comment by caleblloyd** [comment]
Please post a model and controller at the least so we can recreate

**Comment by Kagamine** [comment]
Please use JsonObject.Equals instead of `==`, because we cannot reload the == operation with a null value.

**Comment by HongyanShen** [comment]
@Kagamine Both dto and dto.JsonObject are not null.

**Comment by Kagamine** [comment]
You should not use `==` with a JsonObject. You have to use `.Equals(null)` instead of `==`
