### ISSUE TITLE
Enum Types

### ISSUE THREAD

**Issue by arzzzae** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#283]
What is the best way to use MySql enum data type? I am currently rewriting my old app into dotnet core and i am currently having issue scaffolding tables with enums.

### Further technical details

MySQL version: 5.7
Operating system: Win10
Pomelo.EntityFrameworkCore.MySql version: 1.1.1

**Comment by mguinness** [comment]
Before creating a new issue, please search existing issues.  A quick search revealed issue https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/36.
