### ISSUE TITLE
dbcontext scaffold 无法处理枚举类型

### ISSUE THREAD

**Issue by Cherrs** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#284]
Could not find type mapping for column 'test' with data type 'enum('pending','failed','verified','destroyed')'. Skipping column.

MySQL version: 5.7
Operating system: ubuntu16.04
Pomelo.EntityFrameworkCore.MySql version:1.1.2

**Comment by Kagamine** [comment]
Pomelo treat enum(CLR type) as a integer(DB type). Please modify your column into integer before scaffolding.

**Comment by Cherrs** [comment]
数据库是设计好的，不能改。。
现在是使用string来解决这个问题的
