### ISSUE TITLE
UseMySQL instead of UseMySql

### ISSUE THREAD

**Issue by mguinness** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#286]
This is a minor niggle, but something I encountered early on when switching providers.  Was there a reason why the extension method was defined as UseMySql instead of UseMySQL?

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Extensions/MySqlDbContextOptionsExtensions.cs

I think it should be consistent with the other providers.  Maybe we could make this change in the 2.0.0 release?

**Comment by caleblloyd** [comment]
The entire project uses the case scheme for `MySql`.  I don't think the spelling `MySQL` appears anywhere in our source (except for dependencies)

The proper way to use it is documented for our library.  There's already >260 stars on GitHub and changing it in V2 would be confusing to our users.

We could add an alias but I also think that would be confusing.  My vote is to leave it.

**Comment by mguinness** [comment]
The UseMySql extension method for option builder is currently in [seven files](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/search?utf8=✓&q=UseMySql), but I understand reluctance to change it for the aforementioned reasons.  As you said, an alias is another option.

The only reason I bring this up is that I'm using a third party model designer tool that generates a context file which emits UseMySQL for the options builder.  Each time it does this I have to manually change it.  Not a showstopper, but an irritation nonetheless.

**Comment by caleblloyd** [comment]
The refactor isn't what concerns me, it's the BC break.

Is it a popular tool?  An alias wouldn't be bad, it just might make people think "which one do I use?" when in reality they're the same thing

**Comment by mguinness** [comment]
The tool is [Entity Developer](https://www.devart.com/entitydeveloper/), but I don't know how widespread it's use is.  An alias could be confusing, but I guess you could mark the other as deprecated using System.Obsolete attribute.

**Comment by Kagamine** [comment]
I dont agree change UseMySql into UseMySQL, maybe you should open an issue on the tool repo.

**Comment by mguinness** [comment]
@Kagamine Fair enough.  A workaround is for me to alias those extension methods myself which achieves the same result.

```C#
namespace Microsoft.EntityFrameworkCore
{
    public static class MySqlDbContextOptionsExtensions
    {
        public static DbContextOptionsBuilder UseMySQL(
            this DbContextOptionsBuilder optionsBuilder,
            string connectionString,
            Action<MySqlDbContextOptionsBuilder> mySqlOptionsAction = null)
        {
            return optionsBuilder.UseMySql(connectionString, mySqlOptionsAction);
        }

        public static DbContextOptionsBuilder UseMySQL(
            this DbContextOptionsBuilder optionsBuilder,
            DbConnection connection,
            Action<MySqlDbContextOptionsBuilder> mySqlOptionsAction = null)
        {
            return optionsBuilder.UseMySql(connection, mySqlOptionsAction);
        }

        public static DbContextOptionsBuilder<TContext> UseMySQL<TContext>(
            this DbContextOptionsBuilder<TContext> optionsBuilder,
            string connectionString,
            Action<MySqlDbContextOptionsBuilder> mySqlOptionsAction = null)
            where TContext : DbContext
        {
            return optionsBuilder.UseMySql(connectionString, mySqlOptionsAction);
        }

        public static DbContextOptionsBuilder<TContext> UseMySQL<TContext>(
            this DbContextOptionsBuilder<TContext> optionsBuilder,
            DbConnection connection,
            Action<MySqlDbContextOptionsBuilder> mySqlOptionsAction = null)
            where TContext : DbContext
        {
            return optionsBuilder.UseMySql(connection, mySqlOptionsAction);
        }
    }
}
```
