### ISSUE TITLE
2.0.0 Unit Tests update

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#287]
Lots has changed in upstream 2.0.0.  The `dev` branch now tracks `2.0.0-preview3-*` from aspnet/EntityFramework's MyGet feed.

I have updated the Unit Test code, but there is some failures that need to be investigated and fixed:

```
Total tests: 57. Passed: 43. Failed: 13. Skipped: 1.
```

Specifically one thing that has changed is the way to mark properties for value generated on add/update, so I had to comment out all lines in the test that look like this:

```
//[MySqlAnnotationNames.Prefix + MySqlAnnotationNames.ValueGeneratedOnAdd] = true
```

Need to figure out new way that this is handled in 2.0.0 and source of other Unit test failures.

**Comment by Kagamine** [comment]
@caleblloyd why removed annotations from Metadata/Internal/MySqlAnnotationNames.cs?

**Comment by caleblloyd** [comment]
@Kagamine I don't remember, it may have been a mistake. If they were needed feel free to add them back

**Comment by Kagamine** [comment]
@caleblloyd Does ef core 2.0.0 support value generate on update? I've viewed npgsql and sqlserver source, and not found anything about `ON UPDATE`

**Comment by caleblloyd** [comment]
I'm pretty sure that it does somehow, although it looked to me like they changed the way it was done.

Maybe just comment out the ON UPDATE tests for now until we can get 2.0.0 working and then we can add them back
