### ISSUE TITLE
2.0.0  Functional Tests update

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#288]
Lots has changed in upstream 2.0.0.  The `dev` branch now tracks `2.0.0-preview3-*` from aspnet/EntityFramework's MyGet feed.

Functional tests have stopped working because migrations do not work.

Investigate cause of migration failures and get all functional tests working.

**Comment by caleblloyd** [comment]
`dotnet ef migrations add initial` is failing to map `JsonObject<>` properties.  Opened upstream https://github.com/aspnet/EntityFramework/issues/8814

**Comment by smitpatel** [comment]
This call is bit ambiguous

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlTypeMapper.cs#L251

It is possible that it worked in previous versions of netstandard but not allowed in netstandard2.0 anymore.

The `PropertyMappingValidationConvention` comes through this path only. Make sure that `FindMapping` function given a generic `JsonObject` returns the type correctly. When TypeMapper doesn't return a type, the convention will fail.

**Comment by caleblloyd** [comment]
@smitpatel thanks for pointing that line out,  I had erroneously removed it in the 2.0.0 migration.  Adding it back fixed the issue

**Comment by caleblloyd** [comment]
Running into a problem with DI Resolving `IDBContextOptions`.  Asked for help upstream at https://github.com/aspnet/EntityFramework/issues/8818

**Comment by Kagamine** [comment]
Could you add EFCore, EFCore.Relational into dev branch for debugging, I've tried to add them but cannot hit the break point.

**Comment by caleblloyd** [comment]
Let me try the suggestions in https://github.com/aspnet/EntityFramework/issues/8818 first and see if I can get it working.  I need a few days before I can dig into it

**Comment by Kagamine** [comment]
Hi @caleblloyd, could you give me the myget owner permission. Now we have another project `RedisConnector` with full async implements and based on libuv.

**Comment by caleblloyd** [comment]
@Kagamine I'm not sure how to do that, I don't know if I have owner permission on MyGet.  Don't you already have owner permissions on there?

**Comment by Kagamine** [comment]
I have transfered the ownership by mistake prrvious

**Comment by caleblloyd** [comment]
Ah MyGet only allows 1 owner.  I transferred it back to you.

**Comment by Kagamine** [comment]
thx

**Comment by caleblloyd** [comment]
The `IDBContextOptions` is cleared up now.  Now I am hitting an issue with migration commands to MySql hanging.  I will need to step-through debug this.

**Comment by smitpatel** [comment]
Few pointers to debug that:
- Run `dotnet ef migrations script` and verify that generated SQL is correct.
- Run context.Database.EnsureCreated to know if it is solely about tools issue or internal script execution issue.
- Run Migrate from code to mimic database update behavior.

Turn on logging to debug level and you will be able to at which point exactly it is getting stuck.

**Comment by Kagamine** [comment]
Does EnsureCreated() work now?

**Comment by smitpatel** [comment]
umm. It worked always from 1.0 release.

**Comment by Kagamine** [comment]
@smitpatel Sorry, I should say does EnsureCreated work with pomelo 2.0

**Comment by smitpatel** [comment]
I am not sure about that. Though `EnsureCreated()` has much simpler implementation compared to Migrations. It would be good first step to make that work rather than migration.
A working set of runtime components makes it easier to get design time components working.

**Comment by caleblloyd** [comment]
Worked through the issue with migration commands hanging.  Now hitting a bunch of cast errors because EF Core 2.0 is calling It looks like EF 2.0.0 is calling `dbReader.GetValues` now instead of `dbReader.GetFieldValue<T>`

Upstream issue: https://github.com/aspnet/EntityFramework/issues/9013

**Comment by Kagamine** [comment]
Which vs version are you using, why I cannot get it compilable.

**Comment by Kagamine** [comment]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102: Unable to find package System.Compone
.Annotations with version (>= 4.4.0-preview3-25428-02)\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 19 version(s) in nuget.org
st version: 4.4.0-preview2-25405-01 ]\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 16 version(s) in aspnetcore
Nearest version: 4.4.0-preview3-25428-01 ]\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 3 version(s) in Microsoft V
tudio Offline Packages [ Nearest version: 4.3.0 ]\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 2 version(s) in CliFallback
[ Nearest version: 4.4.0-preview2-25405-01 ]\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 0 version(s) in Pomelo [C:\
uko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102: Unable to find package Microsoft.CSha
 version (>= 4.4.0-preview3-25428-02)\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 17 version(s) in nuget.org
st version: 4.4.0-preview2-25405-01 ]\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 16 version(s) in aspnetcore
Nearest version: 4.4.0-preview3-25428-01 ]\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 3 version(s) in Microsoft V
tudio Offline Packages [ Nearest version: 4.3.0 ]\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 3 version(s) in CliFallback
[ Nearest version: 4.4.0-preview2-25405-01 ]\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 0 version(s) in Pomelo [C:\
uko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102: Unable to find package System.Runtime
erServices.Unsafe with version (>= 4.4.0-preview3-25428-02)\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 23 version(s) in aspnetcore
Nearest version: 4.4.0-preview3-25428-01 ]\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 6 version(s) in nuget.org [
t version: 4.4.0-preview2-25405-01 ]\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 2 version(s) in CliFallback
[ Nearest version: 4.4.0-preview2-25405-01 ]\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 1 version(s) in Microsoft V
tudio Offline Packages [ Nearest version: 4.3.0 ]\r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1102:   - Found 0 version(s) in Pomelo [C:\
uko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1605: Detected package downgrade: xunit fro
-beta3-build3705 to 2.2.0. Reference the package directly from the project to select a different version. \r [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore
Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1605:  Pomelo.EntityFrameworkCore.MySql.Tes
1.0.0) -> Microsoft.EntityFrameworkCore.Specification.Tests (>= 2.0.0-preview3-25986) -> xunit (>= 2.3.0-beta3-build3705) \r [C:\Users\Yuko\Documents\GitHub\Pomelo.Ent
eworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]
C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\test\EFCore.MySql.Tests\EFCore.MySql.Tests.csproj : error NU1605:  Pomelo.EntityFrameworkCore.MySql.Tes
1.0.0) -> xunit (>= 2.2.0) [C:\Users\Yuko\Documents\GitHub\Pomelo.EntityFrameworkCore.MySql\Pomelo.EntityFrameworkCore.MySql.sln]

**Comment by caleblloyd** [comment]
@Kagamine https://www.microsoft.com/net/core/preview

**Comment by Kagamine** [comment]
I have already installed vs2017 preview and .net core sdk 2.0.0-prev2

**Comment by smitpatel** [comment]
@Kagamine - It is package restore error. Perhaps due to corrupted local nuget cache.
run this command to clear all local caches
`dotnet nuget locals all --clear` & then run `dotnet restore`

**Comment by caleblloyd** [comment]
Also I just updated all of the dependencies to `2.0.0-preview2-final` from nuget and removed the aspnet-dev MyGet repo.  This way we are building on a more stable set of packages, and can eventually release our own `2.0.0-preview2` once we get things working

**Comment by caleblloyd** [comment]
OK everything works except for 2 `NullReferenceExceptions` I can't figure out.  Upstream issues are https://github.com/aspnet/EntityFramework/issues/9037 and https://github.com/aspnet/EntityFramework/issues/9038
