### ISSUE TITLE
2.0.0 Scaffolding updates

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#289]
Lots has changed in upstream 2.0.0. The `dev` branch now tracks 2.0.0-preview3-* from aspnet/EntityFramework's MyGet feed.

The `Pomelo.EntityFrameworkCore.MySql.Design` project has been dissolved into `Pomelo.EntityFrameworkCore.MySql` as part of the 2.0.0 upgrade.

Scaffolding related files have been moved to these directories:

```
src/EFCore.MySql/Design
src/EFCore.MySql/Scaffolding
```

All scaffolding related code has been commented-out in order to get the rest of the project to compile.  Go through the files, uncomment them, and compare changes from the upstream project.

A good reference is to look at how things are implemented in [EFCore.SqlServer](https://github.com/aspnet/EntityFramework/tree/dev/src/EFCore.SqlServer)

**Comment by Kagamine** [comment]
@caleblloyd What is the change around `MySqlScopedTypeMapper`?

**Comment by caleblloyd** [comment]
Nothing it's just a Singleton now and leverages `MySqlOptions` to get server info

**Comment by Kagamine** [comment]
I cannot find the class `MySqlScopedTypeMapper` in the whole sln

**Comment by Kagamine** [comment]
Did you renamed the class?

**Comment by caleblloyd** [comment]
Oh yes I renamed it to `MySqlSmartTypeMapper` since it is no longer scoped

**Comment by Kagamine** [comment]
Since MySqlDesignTimeSmartTypeMapper inherit from MySqlSmartTypeMapper, how to invoke the base constructor now?

**Comment by Kagamine** [comment]
Besides I cannot read the property `ConnectionSettings` anymore. How to process the TreatTinyIntAsBool behavior?

**Comment by caleblloyd** [comment]
You must inject Singleton `MySqlOptions` and save it as a prop. Then do `_mySqlOptions.ConnectionSettings`
