### ISSUE TITLE
Migration failure cause some of the change remains

### ISSUE THREAD

**Issue by 303248153** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#292]
### Steps to reproduce
[EFCORETEST.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/1079541/EFCORETEST.zip)

**create first migration**
dotnet ef migrations add firstMigration

**apply first migration**
dotnet ef database update

**add field 'Test' in table 'blogs' manually**

**uncomment field 'Test' under 'Blog' and 'Post' class**

**create second migration**
dotnet ef migrations add secondMigration

**apply second migration**
dotnet ef database update

Apply second migration will failed, then secondMigration wont insert to __efmigrationshistory,
but field 'Test' will remain in table 'posts'.
If you can't reproduce maybe the order is not right, try again and add field 'Test' in table 'posts' manually.

### The issue
The migration should be an atomic operation, it shouldn't cause some change remains after failure.
This problem won't happen with MSSQL driver.

### Further technical details

MySQL version: 5.5.5-10.1.14-MariaDB
Operating system: Windows 8.1
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

**Comment by Kagamine** [comment]
@caleblloyd Could you please investigate this issue?

**Comment by caleblloyd** [comment]
Unfortunately DDL statements in MySQL cannot be rolled back. I don't believe there's anything we can do. If somebody else knows of a way though please post here.

https://dev.mysql.com/doc/refman/5.7/en/cannot-roll-back.html

**Comment by tvardero** [comment]
~~@caleblloyd Coming back to this question, can Pomelo provider perform negating action automatically for DDL changes when migration fails?~~

nvm, answered here: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/812#issuecomment-725767625
