### ISSUE TITLE
Using "Unbundled" as a mapping property

### ISSUE THREAD

**Issue by maponce** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#299]
### Steps to reproduce
Add a property named "Unbundled" in a mapped entity

` 
....
`
` 
public Boolean? Unbundled { get; set; }
`
` 
....
`
### The issue
We are receiving a random mapping error trying to use this particular property name. if we change it, everything looks good.

Exception message: Count = error CS0103: The name 'InnerExceptionCount' does not exist in the current context

Inner exception message = "Unable to cast object of type 'System.Boolean' to type 'System.String'."

The weird part of the issue is that we can reproduce the scenario using multiple combinations like : IsUnbundled, Untest, Uninstall, etc

### Further technical details
Net core version: 1.1
MySQL version: 5.6.21
Operating system: Windows Server 2008
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

**Comment by mguinness** [comment]
What is the database schema for that mapped entity?

**Comment by maponce** [comment]
We are working with a legacy application schema, let me replicate the issue in a separate one to specifically address the problem.
