### ISSUE TITLE
照着sample，改了一下链接字符串报错

### ISSUE THREAD

**Issue by dhswg20077** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#30]
### Steps to reproduce
照着sample，改了一下链接字符串报错

Exception message:

An unhandled exception of type 'Pomelo.Data.MySql.MySqlException' occurred in Microsoft.EntityFrameworkCore.Relational.dll

Additional information: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json,

    `Title` varchar(32),

    `UserId` int NOT NULL,

    CONSTRAINT `PK_' at line 4

MySQL version: 5.6.28-log

**Comment by Kagamine** [comment]
MySQL 5.6 doesn't support JsonObject<T>, Don't use json in MySQL 5.6.
