### ISSUE TITLE
Auto increment does not work in mysql

### ISSUE THREAD

**Issue by fcin** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#300]
Setting auto increment field in entity framework does not work with mysql. I found this issue when I was trying to save a basic model with two properties:

```
public class User
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Key]
    public int Id { get; set; }
    [Required]
    public string Name { get; set; }
}
```

When I wanted to save a new user to mysql database I got an exception 

> Field 'Id' doesn't have a default value

```
private TetrominoContext _dbContext;

public HomeController(TetrominoContext dbContext)
{
    _dbContext = dbContext;
}
public IActionResult Index()
{
    var user = new User {
        Name = "Whatever"
    };

    _dbContext.Users.Add(user);
    _dbContext.SaveChanges(); // Throws exception
}
```

> InnerException  {MySql.Data.MySqlClient.MySqlException: Field 'Id' doesn't have a default value
>    at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
>    at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__62.MoveNext()

I tried different combinations of `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` and `[Key]`, but with no luck.

These are all of my packages:
```
 <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.NodeServices" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.2" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="1.1.2" />
  </ItemGroup>
```

And my migration:
```
    [DbContext(typeof(TetrominoContext))]
    [Migration("20170625090637_SixthMigration")]
    partial class SixthMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "1.1.2");

            modelBuilder.Entity("Tetromino.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
        }
    }
```

My `Startup.cs`:
```
public class Startup
    {

        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            
            //services.AddEntityFrameworkMySql().AddDbContext<TetrominoContext>(options => options.UseMySql(Configuration.GetConnectionString("MySqlConnection")));
            services.AddEntityFrameworkMySql().AddDbContext<TetrominoContext>(options => options.UseMySql(Configuration.GetConnectionString("LocalTestDbConnection")));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseDefaultFiles();
            app.UseStaticFiles();

            app.UseMvcWithDefaultRoute();
        }
    }
```

**Comment by caleblloyd** [comment]
Don't even put `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` on the property.  `[Key]` should be enough.  If you call the column `Id`, it doesn't even need any annotations.  It'll get `AUTO_INCREMENT` automatically.

Example:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/7aecbf6fdcd7e6b38c02e0f7dd3abb61feffac17/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Models/DataTypes.cs#L9

**Comment by caleblloyd** [comment]
If you already have rows in that table you can't just add an `AUTO_INCREMENT` column to it.  You have to add an `ID` column with a default value, then populate the values to be unique, then set the `AUTO_INCREMENT`.  I recommend you hand-code a migration to do that.

**Comment by fcin** [comment]
The thing is I first tried doing this without `[Key]` and `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]`. I later tried different combinations. I also recreated my database couple of times to see if it would help, but it didn't.

**Comment by caleblloyd** [comment]
If you can recreate your database, then remove all of your migrations and generate a single migration for your initial migration.

The problem in your log above is that you are hitting errors when changing the schema.  Creating a fresh migration ensures there is no issue creating a fresh schema.

**Comment by fcin** [comment]
Thank you. The problem was that recreated my database but I didn't remove my previous migrations.

**Comment by maxikape** [comment]
> Gracias. El problema fue que recreé mi base de datos pero no eliminé mis migraciones anteriores.

como te quedo el codigo?? tengo el mismo problema

**Comment by lauxjpn** [comment]
@maxikape If you post the SQL of the `CREATE TABLE` statement for the table, the model class and the full model definition for the model class (the `modelBuilder.Entity<>` code) we can take a look at why this is not working for you.
Also, which version of Pomelo are you using?
