### ISSUE TITLE
Add .NET 4.6.1 back

### ISSUE THREAD

**Issue by Kagamine** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#304]

**Comment by caleblloyd** [comment]
No need.  `netstandard2.0` is compatible with `net461` and up!

**Comment by Kagamine** [comment]
See the official package, it has added net461 additionally. Maybe netstandard 2.0 will use corefx but net461 will use netfx

**Comment by caleblloyd** [comment]
Some of their code has conditional compile `#if NET461` flags [code search](https://github.com/aspnet/EntityFramework/search?utf8=%E2%9C%93&q=%23if+NET461&type=)


[EFCore.csproj](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/EFCore.csproj), [EFCore.Relational.csproj](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.Relational/EFCore.Relational.csproj), [EFCore.SqlServer.csproj](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.SqlServer/EFCore.SqlServer.csproj) only targets `netstandard2.0` 

There is no need to target `net461` if we have no conditional compile flags for it

**Comment by Kagamine** [comment]
Got it
