### ISSUE TITLE
2.0.0 Add EF Upstream Functional Tests for Providers

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#305]
Porting [comment](https://github.com/aspnet/EntityFramework/issues/8818#issuecomment-309074878) from @ajcvickers

> Also, it doesn't seem like the github repo is making use of the functional tests that we publish for providers to use--unless you are doing it in some way that I missed. I would recommend that you look at how the SQL Compact provider (https://github.com/ErikEJ/EntityFramework.SqlServerCompact) and the Prostgres provider (https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL) are doing this. I'm sure either @ErikEJ or @roji would be happy to give some guidance on this.

We should add these tests at `test/EFCore.MySql.UpstreamFunctionalTests`

@ErikEJ and @roji do you have any recommendations or roadblocks that you encountered when putting these upstream tests in your project that would be helpful for us to know about?

**Comment by roji** [comment]
@caleblloyd nothing in particular to say... A good place to start might be QueryTestBase, which contains a ton of general SQL tests that should flush out any issues you have in the provider. There's a bit of infrastructure/utilities you'd have to write first (e.g. TestStore), simply follow the dependencies and compare what SqlServer/Sqlite/SqlServerCompact/Npgsql are doing.

Making the entire functional test suite run and pass is quite a big task, you should probably go incrementally, starting with the more important classes, working your way through. If you run into specific concrete problems don't hesitate to ask.

**Comment by caleblloyd** [comment]
Specification tests were merged to the branch [f_2.1.0-spec-tests](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/tree/f_2.1.0-spec-tests) in #534 by @AndriySvyryd however the current implementation does not pass most of those tests:

> Only made minimal code fixes required for the test infrastructure. Most of the tests are still failing.

The implementation should be fixed by further changes to `f_2.1.0-spec-tests` so that tests pass, then `f_2.1.0-spec-tests` could be merged into`2.1.0-preview` or `master` and a the 2.1 Release Candidate process can begin.
