### ISSUE TITLE
An error occurred applying migrations, try applying them from the command line

### ISSUE THREAD

**Issue by dhswg20077** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#31]
### Steps to reproduce
1.修改配置文件
    "MysqlDefaultConnection": "Data Source=******.com;port=8041;Database=Videos;uid=root;pwd=*****;charset=utf8",

2.services.AddDbContext<ApplicationDbContext>(options =>
                options.UseMySql(Configuration.GetConnectionString("MysqlDefaultConnection")));

3.注册用户

4.提示ef迁移

5.点击 Apply Migrations

6.报错 提示 “An error occurred applying migrations, try applying them from the command line”
查看数据库已经自动创建成功，但是表只有__EFMigrationsHistory一个。

MySQL version:  MySQL 5.6

**Comment by Kagamine** [comment]
What's your DbContext and your models?

**Comment by dhswg20077** [comment]
public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }
    }

VS 自动生成的

**Comment by dhswg20077** [comment]
services.AddDbContext<ApplicationDbContext>(options =>
                options.UseMySql(Configuration.GetConnectionString("MysqlDefaultConnection")));

**Comment by Kagamine** [comment]
@ElderJames Can you help him to solve the question?

**Comment by Kagamine** [comment]
@dhswg20077 We need more information to solve your question. Which .NET Core version are you using?  Can you post your project.json here?

**Comment by dhswg20077** [comment]
`{
  "userSecretsId": "aspnet-WebApplication2-2392ac1d-1dae-4770-b5d3-03a75cf52afe",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.0.0",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Pomelo.EntityFrameworkCore.MySql": "1.0.0-prerelease-20160726"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`

**Comment by dhswg20077** [comment]
"MysqlDefaultConnection": "Data Source=579781ae36ef7.gz.cdb.myqcloud.com;port=8041;Database=Videos;uid=github;pwd=github123;charset=utf8",  

测试数据库

**Comment by Kagamine** [comment]
We still cannot reproduce your issue. You can have a try to remove your schema, and remove the Migrations folder.

Then execute `dotnet ef migrations Init` & `dotnet ef database update`.

**Comment by dhswg20077** [comment]
https://1drv.ms/u/s!Anl7_22uzWH_i59hO8Qt26HVY_uEjA   上传了测试源码。。

**Comment by Kagamine** [comment]
![image](https://cloud.githubusercontent.com/assets/2216750/17199689/536b265a-54b1-11e6-9eb8-be947a70838d.png)

It seems works well in my machine, I still cannot reproduce your issue.

**Comment by dhswg20077** [comment]
那是不支持 mysql5.6么?
579781ae36ef7.gz.cdb.myqcloud.com;port=8041;Database=Videos;uid=github;pwd=github123;charset=utf8

你用我这个数据库测试，上面的东西都可以删

**Comment by Kagamine** [comment]
Your database is gbk charset. change it into utf8 will solve this issue.

**Comment by dhswg20077** [comment]
it works，thank you very much  23333....
