### ISSUE TITLE
No distinguishing Utc time and local time when the DateTime type is stored in the database 

### ISSUE THREAD

**Issue by xyhuanglihua** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#312]
I puting the Local time and Utc time is stored the database, with DateTimeKind method can show these two time were Local and Utc, but through the query database to get these two time, and then using the DateTimeKind method to show these two time are Unspecified.

The code is as follows：
```
 public static void Main()
        {
            using (var db = new BloggingContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();
                var a = DateTime.Now;
                var b = DateTime.UtcNow;
                Console.WriteLine(" DateTime A - {0}, DateTime Kind - {1}", a, a.Kind);
                Console.WriteLine(" DateTime B - {0}, DateTime Kind - {1}", b, b.Kind);

                db.Blogs.Add(new Blog { String = "LocalTime", DateTime = DateTime.Now });
                db.Blogs.Add(new Blog { String = "UTCTime", DateTime = DateTime.UtcNow });
                db.SaveChanges();
            }

            using (var db = new BloggingContext())
            {
                foreach (var blog in db.Blogs)
                {
                    Console.WriteLine(" Title - {0}, DateTime - {1}, DateTime Kind: {2}", blog.String, blog.DateTime, blog.DateTime.Kind);
                }
            }
    }
```

Output results:

```
 DateTime A - 2017/7/6 17:47:21, DateTime Kind - Local
 DateTime B - 2017/7/6 9:47:21, DateTime Kind - Utc
 Title - LocalTime, DateTime - 2017/7/6 17:47:21, DateTime Kind: Unspecified
 Title - UTCTime, DateTime - 2017/7/6 9:47:21, DateTime Kind: Unspecified
```
The code is linked as follows:
https://github.com/xyhuanglihua/EF-Core-DateTime-Issues.git
### The issue
No distinguishing Utc time and local time when  Pomelo.EntityFrameworkCore.MySql put the DateTime type is stored in the database ,this is a design, or a bug？

**Comment by caleblloyd** [comment]
This is a limitation of MySQL, it does not store time zone info in `DateTime` or any other date object.

It is best to qualify your fields such as `UtcDateTime` and `LocalDateTime` or save time zone in a separate field and recreate the full object in C#
