### ISSUE TITLE
Schedule 2.0.0-preview2-final release date

### ISSUE THREAD

**Issue by Kagamine** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#316]

**Comment by 717009629** [comment]
支持女神

**Comment by caleblloyd** [comment]
How about Monday July 17

**Comment by caleblloyd** [comment]
Just published it: [https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.0.0-preview2-final](2.0.0-preview2-final)

We need community feedback, RTM is getting close.  Anyone successfully upgraded their project to `2.0.0-preview`?  Were there any problems upgrading?

**Comment by chikien276** [comment]
I upgraded my project to
```<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview2-final" />```
and 
```<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.0.0-preview2-final" />```
After that I tried to add 1 more migration (add-migration blabla) the operation **not finishing** but still generating some strange script. 
Say, I had a table called `Song` with Primary Key `Id` type `Int`. I had nothing to do with this table but the progress generated the code look like
```
migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Songs",
                type: "int",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
``` 
As a result, I got this error when update database
```
fail: Microsoft.EntityFrameworkCore.Database.Command[200102]
     Failed executing DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
     ALTER TABLE `Songs` MODIFY COLUMN `Id` int NOT NULL;
     ALTER TABLE `Songs` ALTER COLUMN `Id` DROP DEFAULT;
MySql.Data.MySqlClient.MySqlException (0x80004005): Cannot change column 'Id': used in a foreign key constraint ...
```

**Comment by Kagamine** [comment]
@chikien276 First, this issue is about preview2 release plan. Any issues about using, please open a new one.
Then, the exception told you if you want to change the column, must drop the FK first. I assume this is a user error.

**Comment by mguinness** [comment]
.NET Standard 2.0 is now [finalized](https://github.com/dotnet/announcements/issues/24) and the announcement of .NET Core 2.0 will be on September 18-19.
