### ISSUE TITLE
Upgrade to MySqlConnector that Supports netstandard2.0 Before 2.0.0-RTM

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#317]
MySqlConnector will publish a `netstandard2.0` build once 2.0.0 RTM is published

We need to wait for this to get published on NuGet, then switch our dependencies to use it before we publish our 2.0.0 package.

Here is the tracking issue: https://github.com/mysql-net/MySqlConnector/issues/270

**Comment by chikien276** [comment]
Sir, any update about this. I upgraded my application to 2.0.0 RTM now and get ` Could not load type Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'` error

I'm not sure this is error from EntityFramework or not but it was working when my project had Microsoft.AspNetCore.All in `2.0.0-preview1-final` and Pomelo.EntityFrameworkCore.MySql in `2.0.0-preview3-10054`

**Comment by caleblloyd** [comment]
@chikien276 your question is unrelated to this issue so I will remove it from this issues soon.  But to answer your question your dependencies in your `csproj` should target `2.0.0-preview2-final` with the latest preview.  Here are our working dependencies: [EFCore.MySql.FunctionalTests.csproj](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/EFCore.MySql.FunctionalTests/EFCore.MySql.FunctionalTests.csproj)

**Comment by Kagamine** [comment]
So, you are not using 2.0.0-RTM, you are using the 2.0.0-preview1-final. Unfortunately, pomelo has lost the support for 2.0.0-preview1, you must bump up your project to 2.0.0-preview2 and use Pomelo.EntityFrameworkCore.MySql 2.0.0-preview2-final or 2.0.0-preview3-*.

**Comment by chikien276** [comment]
I am so sorry about that and thank you for your answers. I though this is a issue about support EfCore 2.0.0 RTM cause it have been released  and I got this error from using it against our 2.0.0-preview3-10054. Again, I'll remove my comments and sorry for this inconvenience.
