### ISSUE TITLE
Issue with migrations on MariaDB 10.2

### ISSUE THREAD

**Issue by nover** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#320]
### Steps to reproduce
On an existing EF model with a foreign key to one table, change that foreign key to another table - this caused EF to create a "RENAME INDEX" in my case as the column name changes.

### The issue
When renaming indexes MySQL 5.7 introduced a new nice keyword `RENAME INDEX TO` - however, Mariadb 10.2 does _not_ support this, so the generated migration fail. 

I was hoping that the MySQL connector could see / guess that it's not talking to MySQL 5.7 and create a migration that would apply cleanly - something like `DROP` and `CREATE` index though it is a slower.

Doctrine - an ORM for PHP had a similar issue:
https://github.com/doctrine/migrations/issues/196

### Further technical details

MySQL version:  MariaDB 10.2.6
Operating system: Windows 10 with database via Docker Compose
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

Now I know that the driver says it is MySQL compatible, but given that MariaDB is so close to being binary compatible with MySQL I was hoping you would look into fixing this.

**Comment by Kagamine** [comment]
Yes, this was by design. rename operations only works with 5.7+. We do not want to drop and re-create.

**Comment by nover** [comment]
Okay, so the driver basically supports MYSQL 5.7, with no intention to support older versions of MYSQL nor mariadb?

**Comment by caleblloyd** [comment]
> Okay, so the driver basically supports MYSQL 5.7, with no intention to support older versions of MYSQL nor mariadb?

No

---

The migration operation is [here in MySqlMigrationsSqlGenerator.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/e53d8fe26c0e0bfbb184b595dcb2625e6a7d17e5/src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs#L154-L171)

A server version flag needs to be added [here in ServerVersion.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/e53d8fe26c0e0bfbb184b595dcb2625e6a7d17e5/src/EFCore.MySql/Storage/Internal/ServerVersion.cs) for `SupportsRenameIndex`

Then the migration option needs to check `_options.ConnectionSettings.ServerVersion.SupportsRenameIndex` and use it if available, otherwise fallback to drop and re-create.

---

Happy to accept it as a PR or we can fix it.

On a side note it'd be good to add MySql 5.6 and MariDB 10.3 to our TravisCI setup to catch stuff like this

**Comment by nover** [comment]
@caleblloyd thanks for clarifying, I'll try to look into it tomorrow if I get the time.
I also created an issue with MariaDB to see if we can get `RENAME INDEX` support added there.
https://jira.mariadb.org/browse/MDEV-13301

**Comment by nover** [comment]
@caleblloyd I see that you tagged it up for the 2.0 release - would it be possible to backport it to the 1.1 series? Because we kind of need the feature for a project running on 1.1 that can't be upgraded to the preview.

**Comment by Kagamine** [comment]
@nover Sorry, we don't have an LTS plan for 1.1, maintaining different versions is a huge program, and we only have 2 people maintaining this project.

**Comment by nover** [comment]
@Kagamine Fair enough - what if I make two PRs? One based off master for 2.0 and one based off the 1.1.2-rtm branch?

**Comment by Kagamine** [comment]
should push to 1.1.3 branch

**Comment by caleblloyd** [comment]
Sure we'll accept a PR and push a 1.1.3 prerelease for you!

**Comment by nover** [comment]
Okay PR ready for version 2.0:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/321

**Comment by nover** [comment]
Backport of changes for 1.1: 
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/322

**Comment by savissimo** [comment]
Excuse me, I have the issue with RENAME INDEX, and apparently this fix would solve that. But I can't understand how I should use it. Thanks for any help!

**Comment by mc0re** [comment]
My version string on the server is:
```
$ mysql -V
mysql  Ver 15.1 Distrib 10.4.12-MariaDB, for Linux (x86_64) using readline 5.1
```

But the index renaming is still not supported:
```
 MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to u
se near 'INDEX `IX_CourseFiles_Hash` TO `IX_Files_Hash`' at line 1
```

Can I force the server version somehow?

**Comment by mguinness** [comment]
See [ServerVersion](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/wiki/Configuration-Options#serverversion) in Configuration Options wiki.
