### ISSUE TITLE
Invalid SQL generated for default values

### ISSUE THREAD

**Issue by bandito22** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#325]
### Steps to reproduce

1. Create a database with a table that have a combination of default values eg.:

```
CREATE TABLE `testable` (
  `myDateTime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `myYN` varchar(1) NOT NULL DEFAULT 'N',
  `myChar` varchar(25) NOT NULL DEFAULT ' ',
  `id` varchar(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
    
2. Use scaffolding to create your entities from this DB.
Will give something like this:

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Testable>(entity =>
            {
                entity.ToTable("testable");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("varchar(45)");

                entity.Property(e => e.MyChar)
                    .IsRequired()
                    .HasColumnName("myChar")
                    .HasColumnType("varchar(25)")
                    .HasDefaultValueSql(" ");

                entity.Property(e => e.MyDateTime)
                    .HasColumnName("myDateTime")
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("0000-00-00 00:00:00");

                entity.Property(e => e.MyYn)
                    .IsRequired()
                    .HasColumnName("myYN")
                    .HasColumnType("varchar(1)")
                    .HasDefaultValueSql("N");
            });
```

3. Run 'add-migration' command.
4. Run 'script-migration' command. Will give you something like this:

```
CREATE TABLE `__EFMigrationsHistory` (
    `MigrationId` varchar(95) NOT NULL,
    `ProductVersion` varchar(32) NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
);

CREATE TABLE `testable` (
    `id` varchar(45) NOT NULL,
    `myChar` varchar(25) NOT NULL DEFAULT  ,
    `myDateTime` datetime NOT NULL DEFAULT 0000-00-00 00:00:00,
    `myYN` varchar(1) NOT NULL DEFAULT N,
    CONSTRAINT `PK_testable` PRIMARY KEY (`id`)
);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20170714104810_test', '1.1.2');

```
### The issue
The generated script is missing quotes from around the default values.

This in itself is not a major problem as it can be edited manually. But this invalid SQL prevents you from running any of the other database generation commands within your code eg. Database.Migrate() , EnsureCreated() etc.. 

### Further technical details

MySQL version: 5.7.18
Operating system: Win10
Pomelo.EntityFrameworkCore.MySql version: 1.1.2 

Other details about my project setup:

**Comment by caleblloyd** [comment]
It's because scaffolding is putting the default values in `HasDefaultValueSql`. It should be `HasDefaultValue`.

Scaffolding does not get everything right, scaffolded code should always be reviewed and corrected where necessary.

**Comment by bandito22** [comment]
Thanks.

Converting the scaffold code to .HasDefaultValue resolved the majority of issues.

However, in order to set a default `DateTime` value to zero I need to use `HasDefaultValueSql`. Adding in the additional quotes here seems to fix that issue: `.HasDefaultValueSql("'0000-00-00 00:00:00'");` 

Following these changes, `Datebase.Migrate & EnsureCreated` commands work fine.

Appreciate the help.
