### ISSUE TITLE
Add timestamp(6) as a supported data type

### ISSUE THREAD

**Issue by lundcm** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#326]
### Steps to reproduce
Scaffold a database with `timestamp(6)` datatypes similarly to:
`dotnet ef dbcontext scaffold 'server=server_name;userid=username;password=pw;database=db;' Pomelo.EntityFrameworkCore.MySql -o Models --data-annotations`

All columns that have timestamp(6) columns are ignored:
`Could not find type mapping for column 'table.column' with data type 'timestamp(6)'. Skipping column.`

### The issue
`timestamp(6)` isn't a supported data type. I believe it needs to be added here: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Storage/Internal/MySqlTypeMapper.cs#L49

```
Exception message: `Could not find type mapping for column 'table.column' with data type 'timestamp(6)'. Skipping column.`
```

### Further technical details

MySQL version: 5.7
Operating system: centos
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

**Comment by caleblloyd** [comment]
Please post the model that was scaffolded

**Comment by lundcm** [comment]
Here is the DDL
```sql
create table consumer_summary
(
	id bigint auto_increment primary key,
	consumer_id bigint not null,
	achieved_total double null,
	converted_total double null,
	delivered_total double null,
	paid_total double null,
	last_touched timestamp(6) null,
	date_created timestamp(6) default '1970-01-01 00:00:01.000000' not null,
	last_updated timestamp(6) default '1970-01-01 00:00:01.000000' not null,
	constraint idx_organizationId_consumerId
		unique (organization_id, consumer_id)
);
```

**Comment by Kagamine** [comment]
I don't think mysql support the type `timestamp(6)`

**Comment by lundcm** [comment]
Um, it is and we're using it. It's the most precise time-stamp I believe they offer which is why we're using it. The 6 signifies the number of ms to store.

https://dev.mysql.com/doc/refman/5.7/en/datetime.html

>A DATETIME or TIMESTAMP value can include a trailing fractional seconds part in up to microseconds (6 digits) precision.

**Comment by lundcm** [comment]
@Kagamine - Is this being covered by #345?
