### ISSUE TITLE
LINQPad - Has anyone tried using it with this?

### ISSUE THREAD

**Issue by gbfromhb** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#33]
Not sure if this is the right place, but I would give it a shot to see if this is of interest and if the issue might be here. I have posted this at LinqPad also. If this is not of interest, I understand. Thanks for the time you spent on this driver it is working great for me.

In LinqPad trying to add connection and telling it Path to Custom Assembly

It returns:
"Could not load Assembly. System.Runtime, Version=4.1.0.0, PublicKeyToken=b03f5f7f11d50a3a when adding connection

I am currently running
.NETCore.App: 1.0.0-rc2-3002702
.EntityFrameworkCore.Tools: 1.0.0-preview1-final
Pomelo.EntityFrameworkCore.MySql: 0.0-prerelease-20160730
LINQPad: 5.08.01
LinqPad EntityFramework V7 Driver: 1.0.1.0
Client Operating System: Windows 10 Version: 1607 (OS Build 14393.5)
Database Server Operating System: Raspberry PI  - Raspbian
MySql: Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (armv71)

**Comment by Kagamine** [comment]
Hi, @gbfromhb , Pomelo.EntityFrameworkCore.MySql is design for .NET Core 1.0.0 RTM, I saw you are using the old version `1.0.0-rc2`. Can you have a try to upgrade your .NET Core?
