### ISSUE TITLE
NullReferenceException in MySqlBatchExecutor

### ISSUE THREAD

**Issue by mguerrieri** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#340]
When building against the EF daily dev builds (2.1.0-preview1-26462, which I understand is not yet supported, but just to make you aware for the future),  if you commit multiple changes (thereby invoking MySqlBatchExecutor) EF Core will dispose the underlying connection (I believe during the disposing or RelationalDataReader) which causes a NullReferenceException during the subsequent transaction commit.

**Comment by Kagamine** [comment]
Force target to another ef core version will not work

**Comment by Kagamine** [comment]
Please follow the upstream ef core version which referenced by pomelo.

**Comment by mguerrieri** [comment]
I understand,  I just wanted to get this out there for future reference. If you can future-proof the library for the 2.0 release now, you can save headaches later when 2.1 is released.

**Comment by caleblloyd** [comment]
Upstream introduces changes that break the provider all the time in new versions. It's just part of the upgrade process.
