### ISSUE TITLE
Change recommendation from utf8 to utf8mb4

### ISSUE THREAD

**Issue by nvivo** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#344]
`utf8` in mysql is quite problematic as it is a proprietary 3-byte format that has been incorrectly named and maintained for compatibility purposes, and doesn't support real utf-8 strings, specially 4-byte strings like emoji.

Change the recommendation in the front page to `utf8mb4` which is the actual UTF-8 the rest of the world uses. It will match .NET UTF-8 encoding and it's also the default encoding used by connections in MySqlConnector.

**Comment by caleblloyd** [comment]
Thanks for the report, this is a great idea!

Here is more information: https://stackoverflow.com/questions/30074492/what-is-the-difference-between-utf8mb4-and-utf8-charsets-in-mysql

Will this affect the maximum key length? I think UTF8 max key length is 767, is UTF8MB4 less?

**Comment by Kagamine** [comment]
I agree this change

**Comment by nvivo** [comment]
As far as I understand, since mysql handles utf8 in bytes, limits remain the same but depends on what you put in the field.

**Comment by mguinness** [comment]
After reading https://mathiasbynens.be/notes/mysql-utf8mb4 I think key length is a factor, but that is somewhat mitigated by PR https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/139 to address issue https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/136.

> The InnoDB storage engine has a maximum index length of 767 bytes, so for utf8 or utf8mb4 columns, you can index a maximum of 255 or 191 characters, respectively. If you currently have utf8 columns with indexes longer than 191 characters, you will need to index a smaller number of characters when using utf8mb4. (Because of this, I had to change some indexed VARCHAR(255) columns to VARCHAR(191).)
