### ISSUE TITLE
How to correctly configure Default Value for CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by greghroberts** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#35]
### Steps To Reproduce
From the docs sample: https://ef.readthedocs.io/en/latest/modeling/relational/default-values.html
```c#
class MyContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>()
                .Property(b => b.Created)
                .HasDefaultValueSql("CURRENT_TIMESTAMP");
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
        public DateTime Created { get; set; }
    }
```
### The issue
The DB default in MySql is correct, but when saving this entity, without setting the Created property, it defaults to the DateTime Min of '0001-01-01 00:00:00'. If you do an insert directly in MySql it obviously works fine.  
I would assume the correct behavior would be to read back the value or use in the sql statment 'UTC_TIMESTAMP()'.

I can workaround by setting date in code, but would be good to understand if this is just bug or not.

### Further technical details

DotNet Core 1.0 RTM
MySQL version: 5.7
Pomelo.EntityFrameworkCore.MySql version: 1.0.0-prerelease-20160803

**Comment by Kagamine** [comment]
DateTime is a value type in .net. The default value is going to be default(DateTime) if you do not specify a default value.

**Comment by greghroberts** [comment]
I understand it's a value type. My question is more on if you plan on making DefaultValues work as per the EF docs.  The attached example and link do not work as designed.

**Comment by Kagamine** [comment]
Confirmed a bug, thanks for reporting this issue, we will fix it in some hours.

**Comment by Kagamine** [comment]
@greghroberts Thanks again. We have fixed this bug, and we will release this new version later.

**Comment by greghroberts** [comment]
Awesome thanks!

**Comment by Kagamine** [comment]
@greghroberts "Pomelo.EntityFrameworkCore.MySql": "1.0.0" is available on NuGet. :smile:
