### ISSUE TITLE
Publish 2.0.0 Package

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#353]
- [x] Begin to publish `2.0.0-rtm-*` packages
- [x] Fix or punt issues in the [2.0.0 Milestone](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/milestone/6)
- [x] Publish a 2.0.0 Package after the final RC is stable for a few days(18th Sep.)

**Comment by caleblloyd** [comment]
Published the first RTM targeting EF 2.0, [2.0.0-rtm-10056](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.0.0-rtm-10056)

**Comment by zhaopeiym** [comment]
very good

**Comment by lj666** [comment]
very good

**Comment by caianhua1986** [comment]
Very Happy，You did a Great job.

**Comment by shenniubuxing3** [comment]
。。。good

**Comment by ZeroX-V** [comment]
这么快就更新了，真的很感动。

**Comment by youdang227** [comment]
very good

**Comment by eyal7773** [comment]
Thanks!!

**Comment by caleblloyd** [comment]
I wrote a quick concurrency benchmark against MySQL, PostgreSQL, and SQL Server on Linux using EF 2.0: https://github.com/caleblloyd/EFCoreBench

Results look good, we are in-line with other providers.

**Comment by caleblloyd** [comment]
[2.0.0-rtm-10059](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.0.0-rtm-10059) has been published with a fix to work with migrations generated in 1.x.

I would like to target the 2.0.0 release on September 4th.  Thoughts @Kagamine or anyone else?

**Comment by mguinness** [comment]
I upgraded a project to target 2.0 and it worked fine, but it's mostly data retrieval.  Hopefully others can chime in with their success stories as well - it's good to hear those as well as failures!  Thanks for all your hard work in getting this up and running caleblloyd.

**Comment by Kagamine** [comment]
Sep. 18th will be better.

**Comment by caleblloyd** [comment]
> Sep. 18th will be better

Sounds good
