### ISSUE TITLE
Unable to use Scaffolding - 'using password: NO'

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#359]
### Steps to reproduce
Create a new console EF Core 2.0 project using VS 2017 15.3, install the following packages:
```<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.0.0-rtm-10056" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>
```

In the Package Manager Console in VS, run the following command:
```
Scaffold-DbContext "Server=localhost;database=db;uid=user;pwd=pwd;" "Pomelo.EntityFrameworkCore.MySql" -Verbose
```

Or navigate to the folder containing *.csproj, and run the following command:
``` 
dotnet ef dbcontext scaffold "Server=localhost;User Id=user;Password=pwd;Database=village_roadshow_main" "Pomelo.EntityFrameworkCore.MySql"
```

### The issue
I get the error like so: 
```Access denied for user 'user'@'localhost' (using password: NO)```

### Further technical details
Manually creating the model and dbcontext allows me to query the database.

MySQL version: 5.5.55-0ubuntu0.14.04.1
Operating system: Windows 10 15063 (MySql is running on Linux, Ubuntu 14.04)
Pomelo.EntityFrameworkCore.MySql version: 2.0

**Comment by Kagamine** [comment]
scaffolding requires root permission, at least your account must have the permissions to `information_schema`.

**Comment by alexzaytsev-newsroomly** [comment]
@Kagamine i have that access, in that i can run ```SELECT * FROM INFORMATION_SCHEMA.TABLES;``` when i connect to MySql.

**Comment by Kagamine** [comment]
Please confirm root user

**Comment by alexzaytsev-newsroomly** [comment]
@Kagamine 
Running 
``` SHOW GRANTS ```
returns

```
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' IDENTIFIED BY PASSWORD '*SOMEHASHHERE' WITH GRANT OPTION
```

**Comment by CAH-FlyChen** [comment]
me too

**Comment by mguinness** [comment]
@alexzaytsev-newsroomly Are you sure you're connecting to the right MySQL?  If your app is running on Win 10 and your database on Ubuntu, then why are you using the loopback address?

**Comment by alexzaytsev-newsroomly** [comment]
@mguinness This is because i am using SSH with local port forwarding?

**Comment by bgrainger** [comment]
I can't reproduce this problem following the steps as described. I also note that this project runs a [scaffolding test](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/EFCore.MySql.FunctionalTests/scripts/scaffold.sh#L11) on every build, which passes.

Thus I suspect it's a problem in the OP's environment; I could investigate further if someone can create a minimal project (on GitHub) that reproduces the issue.

**Comment by srikanthdasari** [comment]
i am having the same issue...is there any solution for this?

**Comment by leanbardelli** [comment]
idem for me, using root password, can confirm access from ip, user and pswd.

**Comment by mguinness** [comment]
@leanbardelli This is a 5 year old issue, please create a new issue and provide the details requested in the template.
