### ISSUE TITLE
Access Denied Issue on every second call - Azure MySql

### ISSUE THREAD

**Issue by Franklin89** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#360]
Not sure if this is related to Pomelo, but I thought I will ask if you guys have seen this issue.

I have a Azure MySql Instance. Connecting and creating the database works great. After that every second call fails with AccessDenied. Even with the `sa` user. This issue occurred after updating to .Net Core 2.0 and the latest preview of Pomelo.

Before writing this issues I create a local Docker instance of MySql and there everything seems to work great. So I am kinda in a situation where I have no idea where this error is coming from, since it worked with Azure Prior .Net Core 2.0 and now it only works with my local docker instance.

Thanks for any input

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/181 for more information.
