### ISSUE TITLE
auto_increment not set when running migrations created with 1.1.2

### ISSUE THREAD

**Issue by gabrielweyer** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#362]
### Steps to reproduce

- Create a migration with a `PK` using `Pomelo.EntityFrameworkCore.MySql` `1.1.2`. You will obtain code similar to this:

```
AppraisalValuerId = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGeneratedOnAdd", true),
```

- Create a migration with a `PK` using `Pomelo.EntityFrameworkCore.MySql` `2.0.0-rtm-10058`. You will obtain code similar to this:

```
DummyTableId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
```

### The issue

If you then execute the two migrations using `Pomelo.EntityFrameworkCore.MySql` `2.0.0-rtm-10058` you'll notice than the `PK` created with the first migration does not have `auto_increment`. The same migration executed with `Pomelo.EntityFrameworkCore.MySql` `1.1.2` used `auto_increment` as expected.

### Further technical details

MySQL version: `5.7.17`
Operating system: `Win 10 Pro 64 bit 1703`
`Pomelo.EntityFrameworkCore.MySql` version: from `1.1.2` to `2.0.0-rtm-10058`
`Pomelo.EntityFrameworkCore.MySql.Design` version: `1.1.2`

Other details about my project setup: not relevant

I think the issue is located in [Migrations/MySqlMigrationsSqlGenerator.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/3d8f483ce8171f7ffaf314e98910d6c5d2eba6c1/src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs#L405-L461)

**Comment by dls314** [comment]
I never worked through caleblloyd's recommendation over in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/423 about adding code manually to the migration, but I'm sure it's an answer.
