### ISSUE TITLE
System.TypeLoadException:“Method 'Clone' in type 'Microsoft.EntityFrameworkCore.Internal.MySqlOptionsExtension' from assembly 'Pomelo.EntityFrameworkCore.MySql, 

### ISSUE THREAD

**Issue by lixiaobai2** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#363]
System.TypeLoadException:“Method 'Clone' in type 'Microsoft.EntityFrameworkCore.Internal.MySqlOptionsExtension' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.”

Hello，How to solve this problem？？

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/295
