### ISSUE TITLE
Support for aspnet-codegenerator?

### ISSUE THREAD

**Issue by mrlife** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#367]
Does Pomelo support `aspnet-codegenerator`? I am following [this step of an official tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-mac/adding-model#scaffold-the-moviecontroller), but receive an error when running `aspnet-codegenerator`:

> Scaffolding failed to edit Startup class to register the new Context using Dependency Injection. Make sure there is a Startup class and a ConfigureServices method and Configuration property in it.

There is a Startup class and a ConfigureServices method and Configuration property in it.

MySQL version: 5.7.19
Operating system: macOS
Pomelo.EntityFrameworkCore.MySql version: 2.0.0-rtm-10057
ASP.NET Core version : 2.0.0
EF Core version: 2.0.0

**Comment by mguinness** [comment]
Please don't cross-post, you already have an open issue at https://github.com/aspnet/Scaffolding/issues/603.

**Comment by mrlife** [comment]
@mguinness There is some overlap here. Are you saying Pomelo supports `aspnet-codegenerator` or that `aspnet-codegenerator` isn't related to Pomelo?
