### ISSUE TITLE
mysqlconnector forces InteropServices.RuntimeInformation 4.0.0?

### ISSUE THREAD

**Issue by rebortec** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#377]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

I have a problem, my .net core 2.0 application, uses mysql pomelo, which in turn requires mysqlconnector. However the last version of mysqlconnector forces InteropServices.RuntimeInformation 4.0.0 but the pomelo requires a higher version and one does not work without the other.Has anyone had this problem yet?

http://prntscr.com/ggqc0l

What's strange is in visual studio everything works perfectly: 

My solution:https://drive.google.com/open?id=0BwRNzpc_I5ZlYy1KR0xhemUyR1E

Could you help me?

### The issue
Describe what is not working as expected.

mysqlconnector forces InteropServices.RuntimeInformation 4.0.0

```
Exception message:
Stack trace:
```

### Further technical details

MySQL version: 5.7
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version:2.0.0-rtm-10061

Other details about my project setup:

**Comment by Kagamine** [comment]
You should open the issue at https://github.com/mysql-net/mysqlconnector

**Comment by bgrainger** [comment]
When I built your code, I got (lots of!) warnings like the following:

```
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1987,5): warning MSB3243: No way to resolve conflict between "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.
4>  Consider app.config remapping of assembly "System.Runtime.InteropServices.RuntimeInformation, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "4.0.0.0" [C:\ERP\packages\System.Runtime.InteropServices.RuntimeInformation.4.0.0\lib\net45\System.Runtime.InteropServices.RuntimeInformation.dll] to Version "4.0.2.0" [C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\\net462\ref\System.Runtime.InteropServices.RuntimeInformation.dll] to solve conflict and get rid of warning.
```

I suggest adding an `app.config` remapping as suggested by the build warning to see if that resolves the assembly load issue. E.g., add:

```
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.InteropServices.RuntimeInformation" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.0.0" newVersion="4.3.0.0" />
      </dependentAssembly>
```

**Comment by bgrainger** [comment]
FWIW, `System.Runtime.InteropServices.RuntimeInformation` is not even a dependency of the `netstandard2.0` version of `MySqlConnector` so it's strange to me that it would even be referenced by a `netcoreapp2.0` project. It looks like UI.csproj and UInterface.csproj might only target .NET 4.6.2, so perhaps they're pulling in the `net46` version of the library even though .NET 4.6.2 supports `netstandard2.0`? Did you create the solution and add all the dependencies with Visual Studio 2017.3 (the first version that supported .NET Standard 2.0)? If not, perhaps some dependencies aren't configured correctly because they were added by a version of Visual Studio that didn't support .NET Standard 2.0. You could try uninstalling the packages then adding them again.
