### ISSUE TITLE
Zero Date conversion

### ISSUE THREAD

**Issue by bandito22** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#378]
### Steps to reproduce
create table table1 (column1 datetime not null default '0000-00-00 00:00:00');

### The issue
MySQL allows storing dates as "0000-00-00" which is not compatible with C#'s `MinDate`.
So, there is no 'automatic' way to explicitly set this date to zero from an Entity Framework POCO.

It would be useful if there could be an option that uses the MySQL fields 'DEFAULT' when C# entity property is set to `MinDate`:

Like:  MinDates = 'Default'

### Further technical details

MySQL version: 5.7.18
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

Other details about my project setup:

**Comment by caleblloyd** [comment]
See `ConvertZeroDateTime` connection string option: https://mysql-net.github.io/MySqlConnector/connection-options/

**Comment by bandito22** [comment]
I am already using this setting in my connection string but that is only a one-way fix when retrieving the date it converts zero date to `MinDate`

It does not allow me to persist a zero date back into the database.

Hence my suggestion that it would be useful to have a way of reversing this logic so that any `MinDate` could convert back to zero when persisting, if that is the desired behavior.

**Comment by caleblloyd** [comment]
I understand now, but it is just one of those things with C# that is not 1:1 with MySQL.  There really is no good fix for it.

Might I suggest that you use a `DateTime?` so that your zero DateTime could be `null`

**Comment by bandito22** [comment]
I agree with the 1:1 issue but the connection string setting is there to address that, but unfortunately only addresses it one way. I just wish it was an optional two-way setting.

I explored the `null `option but unfortunately I have over 200 legacy apps that I am tasked with converting to C# and they all rely on this explicit zero date. I may have to resort to triggers as I cannot see any other way around this.

**Comment by mguinness** [comment]
Iif you must have that default, then a trigger is another alternative.

**Comment by mguinness** [comment]
@bandito22 Maybe you could look at [Triggers Extension](https://github.com/NickStrupat/EntityFramework.Triggers/), but you'd have to use MySqlConnection to update the entity.

**Comment by bandito22** [comment]
@mguinness Thanks for that. I will give it a look. 👍
