### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by dknaack** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#38]
Ive tried Migrations. `Add-Migration` worked as expected. The code gets generated well. 
What i noticed is, that the `__EFMigrationsHistory` table does not get created. This makes it impossible to apply changes using `Update-Database`.

Any ideas?

Great work so far!

**Comment by Kagamine** [comment]
Which version are you using?

**Comment by dknaack** [comment]
Yes. I Use `"Pomelo.EntityFrameworkCore.MySql": "1.0.0"` from NuGet.
What else you want to know? I am currently watching the source so i would be happy if i could help.

**Comment by Kagamine** [comment]
I don't suppose Add-Migration will generate the table `__EFMigrationsHistory`, maybe you have to delete the existed database and execute  `Add-Migration` and `Update-Database`

**Comment by dknaack** [comment]
You'r right! 

I have create the Database using `EnsureCreated()` instead of `Update-Database`. 
Now, it works as expected.

Thanks for the repo and fast response!
