### ISSUE TITLE
Update MySqlConnector for Pomelo.EntityFrameworkCore.MySql 1.1

### ISSUE THREAD

**Issue by jp7677** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#381]
Hi there,

The MySqlConnector is currently at version 0.26.2, but the MySqlConnector for Pomelo.EntityFrameworkCore.MySql version 1.1.3 still has the dependency locked to version 0.19.

Would it be possible to release a 1.1.4 version with a newer MySqlConnector version? I can't yet move to net core 2.0, but would like to use the improvements made in MySqlConnector.

Best regards.

**Comment by Kagamine** [comment]
You can add MySqlConnector into your csproj file, and it will override the old version.

**Comment by jp7677** [comment]
That works, thanks a lo!
