### ISSUE TITLE
Infinite waiting(?) when connecting to ClearDB on Azure

### ISSUE THREAD

**Issue by ktos** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#384]
Hi, I have a problem when using Pomelo with ClearDB on Azure. Everything works for me locally and I've run out of ideas.

### Steps to reproduce
I have an ASP.NET Core 2.0 application. I've scaffolded dbcontext:

```csharp
public partial class TempdataDbContext : DbContext
{
    public virtual DbSet<Tempdata> Tempdata { get; set; }

    public TempdataDbContext(DbContextOptions<TempdataDbContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tempdata>(entity =>
        {
            entity.HasKey(e => e.Timestamp);

            entity.ToTable("tempdata");

            entity.Property(e => e.Timestamp)
                .HasColumnName("timestamp")
                .HasColumnType("int(11)")
                .ValueGeneratedNever();

            entity.Property(e => e.Sensor)
                .IsRequired()
                .HasColumnName("sensor")
                .HasMaxLength(50);

            entity.Property(e => e.Value).HasColumnName("value");
        });
    }
}
```

Simple Model:

```csharp
public partial class Tempdata
{
    public string Sensor { get; set; }
    public int Timestamp { get; set; }
    public float Value { get; set; }
}
```

And simple connection string:

```
Database=tempdata;Data Source=eu-cdbr-azure-north-e.cloudapp.net;User Id=REDACTED;Password=REDACTED
```

And I am trying to get some values from my database. Database has over 100,000 records, I am taking just 100 newest in my HomeController's Index action, immediately giving this list to my view.

```csharp
var data = _context.Tempdata.Where(x => x.Sensor == "outdoor").OrderByDescending(x => x.Timestamp).Take(100).ToList();
```

On my local MySQL server (5.7.18) the SQL seems to be generated properly:

```
SELECT `x`.`timestamp`, `x`.`sensor`, `x`.`value`
FROM `tempdata` AS `x`
WHERE `x`.`sensor` = 'outdoor'
ORDER BY `x`.`timestamp` DESC
LIMIT @__p_0
```

And it works immediately, as expected.

### The issue
The problem is, there is no result in my application at all when connecting to remote ClearDB on Azure.

```
Using launch settings from E:\Marcin\!Projekty\Temperature\TemperatureApp\TempHistory\Properties\launchSettings.json...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\Marcin\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: E:\Marcin\!Projekty\Temperature\TemperatureApp\TempHistory
Now listening on: http://localhost:51587
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:51587/
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method TempHistory.Controllers.HomeController.Index (TempHistory) with arguments ((null)) - ModelState is Valid
```

And it stays like this. I have waited over 4 minutes and nothing changed. When deployed to Azure Web App, it says after a time that CGI application was closed. Similar behaviour is on the IIS Express (error 502.3).

I can connect to the same ClearDB database using HeidiSQL and perform same query. It took 0,187 second.

I have also checked if it is a underlying MySqlConnector problem, creating small .NET Core 2.0 console app with MySqlConnector version 0.26.1 (same my Pomelo is dependent on) and everything works.

```csharp
static void Main(string[] args)
{
    using (var connection = new MySqlConnection(ConnectionString))
    {
        connection.Open();
        IDbCommand db = connection.CreateCommand();
        db.CommandText = "SELECT * FROM tempdata ORDER BY timestamp DESC LIMIT 10";
        var reader = db.ExecuteReader();

        while (reader.Read())
        {
            Console.WriteLine(reader.GetValue(0));
        }
        connection.Close();
    }

    Console.ReadKey();
}
```

I have tried and "scaled up" my ClearDB from the free tier (Mercury) to the cheapest one (Titan) and there is no change.

### Further technical details

MySQL version: ClearDB reports MySQL 5.5.56-log
Pomelo.EntityFrameworkCore.MySql version: 2.0.0-rtm-10062

I have no idea what can be wrong.

**Comment by mguinness** [comment]
Take at look at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/181 for issues with Azure.  It maybe the initial negotiation that's stalled, can you share the [MySQL logs](https://dev.mysql.com/doc/refman/5.7/en/query-log.html)?

**Comment by Kagamine** [comment]
@mguinness Nope, cleardb is diff from azure database for mysql

**Comment by ktos** [comment]
@mguinness I've browsed through that, but it's not the same problem. I cannot get MySQL logs, it's just hosted MySQL service, I have no access to the server itself, unfortunately.

But similarly to #181 I have used Wireshark to see how the underlying communication looks like. I've changed by ConnectionString not to use SSL - not sure if it's OK: `Database=tempdata;Data Source=eu-cdbr-azure-north-e.cloudapp.net;User Id=bef044c47f5218;Password=REDACTED;Ssl Mode=none`

And I got there is a request for quit command going from my computer?!

![image](https://user-images.githubusercontent.com/1633261/30513571-da205bde-9b05-11e7-829c-57041482fd63.png)

Wireshark PCAP file: [cleardb.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/1308423/cleardb.zip) and used the filter `(ip.dst == 137.135.138.88 ) || (ip.src == 137.135.138.88)`.

**Comment by mguinness** [comment]
That connection is probably the [server version interrogation](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Storage/Internal/MySqlConnectionSettings.cs#L48-L72).  Are there no subsequent connections?

**Comment by ktos** [comment]
There are no subsequent connections, only infinite waiting for something. Today I had a time for a serious debugging session and it seems:

Yes, that is the server version interrogation, but the version of the same method based only on connection string. The [infinite wait starts in line 42](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Storage/Internal/MySqlConnectionSettings.cs#L42), which is closing the using, which means there is a problem in closing the connection.

I have debugged it later into MySqlConnector itself and found the place in there where the wait starts -it's https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySqlClient/MySqlConnection.cs#L392. There is indeed waiting for something - and it seems it is waiting for a very long time :-)

I think I should bring this issue to MySqlConnector now.

**Comment by ktos** [comment]
Yes, found a fix in MySqlConnector itself. But thank you for assistance, anyway!

**Comment by mguinness** [comment]
@ktos Thanks for debugging and discovering the issue.  We also had an [issue](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/310) using MariaDB during scaffolding that may have the same problem.
