### ISSUE TITLE
Pomelo.EntityFrameworkCore.MySql.Design package's purpose

### ISSUE THREAD

**Issue by Mikaka27** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#388]
Hi,
Sorry for posting this here, but I cannot find any information about this.

I've been using Pomelo's version 1.xx before and recently upgraded to 2.0.
I still have a package Pomelo.EntityFrameworkCore.MySql.Design in version 1.1.2 and though it is required, but since it didn't get updated to 2.0, I'm starting to wonder.

What is this package used for in Pomelo 2.0 and can I remove it safely and still have everything working (including context scaffolding and migrations)?

**Comment by caleblloyd** [comment]
You may remove it, it is now included within Pomelo.EntityFrameworkCore.MySql
