### ISSUE TITLE
When adding a new value type or numeric field a default value is added to the migration

### ISSUE THREAD

**Issue by YandyZaldivar** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#39]
### Steps to reproduce

Add a new field to a mapped class without specifying a default value using the Fluent API and then generates a new migration. The corresponding column will be generated on the database correctly but with a default value which was not explicitly specified. 

### The issue

In EF Core by convention, a default value is not configured. However, in Pomelo, when you add a new field to a mapped class and generates a migration a default value is also generated, e.g:

```
            migrationBuilder.AddColumn<int>(
                name: "Attempts",
                table: "Players",
                nullable: false,
                defaultValue: 0);
```

The correct behavior should be not generating a default value unless explicitly specified it in the Fluent API.

### Further technical details

MySQL version: 5.7.14
Operating system: Win10
Pomelo.EntityFrameworkCore.MySql version: 1.0.1-prerelease-10000

### Other details

In the initial migration when creating the table the columns are mapped correctly without default values.

**Comment by caleblloyd** [comment]
A non-nullable `int` in the DBMS must have a default value.  If no default is specified, the default value is 0.

If you don't want a default value, you should define your property using the nullable `int?` type.

**Comment by YandyZaldivar** [comment]
In that case in my opinion there is an inconsistence. For example when the table is created the first time using non-nullable values the fields appears on the database with no default values. However if you add a migration with a new value (non-nullable) type, that field will be the only type with a default value. I think you must make this process homogenous at least. Or all value types gets the default value, even when creating the database or you remove the default values on migrations. I haven't taken a look to the behavior on SQL Server but in case of doubt you should follow that.
