### ISSUE TITLE
Creating a unique index on an existing key used in a relation fails

### ISSUE THREAD

**Issue by softlion** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#399]
Assume you have this schema
```
table User
   UserId
```

```
table UserDetail
   UserDetailId
   UserId <= set as foreign key to User.UserId
```

When adding a unique index on `UserDetail.UserId` in a migration, the scaffolded migration:
- drops the existing index on `UserDetail.UserId` 
- creates a new unique index on `UserDetail.UserId` 

This fails when executed on mysql, as mysql enforces the existence of an index on foreign keys columns.

The scaffolded migration should instead:
- rename the existing index to something else, Ex: `IX_UserDetail_UserId_ToDelete`
- create the new unique index
- drop the index `IX_UserDetail_UserId_ToDelete`

### Further technical details

MySQL version: 5.7.14
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

**Comment by caleblloyd** [comment]
Please upgrade to 2.0 and report back if you still hit the issue.
