### ISSUE TITLE
Generated Foreign Key Constraint name exceed max length of 64

### ISSUE THREAD

**Issue by OrihuelaConde** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#400]
Generated Foreign Key Constraint name exceed max length of 64 characters by InnoDB, this cause a lot of issues because it truncate the name in the DB and can incur in duplicated names.
For example: I have a constraint "FK_ProductoSucursalComboProductoSucursal_ProductosSucursal_ProductoSucursalId" and another "FK_ProductoSucursalComboProductoSucursal_ProductosSucursal_ProductoSucursalComboId", because of truncation both are called equal in the DB "FK_ProductoSucursalComboProductoSucursal_ProductosSucursal_Produ".

Is there a solution or I have to name manually every Foreign Key Constraint?

```
Failed executing DbCommand (30ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
ALTER TABLE `ProductoSucursalComboProductoSucursal` ADD CONSTRAINT `FK_ProductoSucursalComboProductoSucursal_ProductosSucursal_Produ` FOREIGN KEY (`ProductoSucursalComboId`) REFERENCES `ProductosSucursal` (`ProductoSucursalId`) ON DELETE CASCADE;
MySql.Data.MySqlClient.MySqlException (0x80004005): Can't write; duplicate key in table '#sql-8ac_19' ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Can't write; duplicate key in table '#sql-8ac_19'
```

### Further technical details

MySQL version: 5.7.17
Operating system: Windows 10 1703 (x64)
Pomelo.EntityFrameworkCore.MySql version: 2.0.0

Other details about my project setup: AspNetCore 2.0.0, Visual Studio 15.4.0

**Comment by caleblloyd** [comment]
I've seen this before too.  I'm not aware of a solution, to my knowledge Pomelo does not create the constraint names, upstream Entity Framework does.

There's probably a workaround that could be implemented.  I don't have the capacity to implement it though.  We could accept an improvement here as a PR.

**Comment by Kagamine** [comment]
You can use fluent api to decrease FK name length.
