### ISSUE TITLE
how to get inserted object id?

### ISSUE THREAD

**Issue by yeganaaa** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#401]
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Cryptography.X509Certificates;
using System.Threading;
using System.Threading.Tasks;
using cn.sarkar.pipeline.core;
using cn.sarkar.pipeline.core.Extensions;
using cn.sarkar.pipeline.test.DB.MySql;
using Newtonsoft.Json;
using Void = cn.sarkar.pipeline.Model.Void;

namespace cn.sarkar.pipeline.test
{
    class Program
    {

        static void Main(string[] args)
        {
            var user = new User
            {
                Name = "yeganaaa",
                Addr = "China",
                Age = 23
            };
            
            var context = new HelloContext();
            context.Add(user);
            context.SaveChanges();
            
            Console.WriteLine($"UserID::: {user.Id}"); //user.ID is zero
            Console.WriteLine("Insert Over");
            
        }
    }

}

### rider console:

/opt/dotnet/dotnet /home/yeganaaa/RiderProjects/cn.sarkar.pipeline.test/cn.sarkar.pipeline.test/bin/Debug/netcoreapp2.0/cn.sarkar.pipeline.test.dll
UserID::: 0
Insert Over

### Further technical details

MySQL version: mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper
Operating system: Linux ubuntu 17.10 beta 
DotNetCore version:  2.0
EntityFrameworkCore version: 2.0
Pomelo.EntityFrameworkCore.MySql version: 2.0.0

Other details about my project setup:

**Comment by yeganaaa** [comment]
###Data Context
`using Microsoft.EntityFrameworkCore;

namespace cn.sarkar.pipeline.test.DB.MySql
{
    public partial class HelloContext : DbContext
    {
        public virtual DbSet<User> User { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseMySql("Server=127.0.0.1;User Id=root;Password=653125;DataBase=Hello");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>(entity =>
            {
                entity.HasIndex(e => e.id)
                    .HasName("User_id_uindex")
                    .IsUnique();

                entity.Property(e => e.id)
                    .HasColumnName("id")
                    .HasColumnType("int(11)")
                    .ValueGeneratedNever();

                entity.Property(e => e.Addr)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Age).HasColumnType("tinyint(4)");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);
            });
        }
    }
}`

**Comment by yeganaaa** [comment]
mysql> select * from User;
+----+----------+-----+-------+
| id | Name     | Age | Addr  |
+----+----------+-----+-------+
|  1 | yeganaaa |  23 | China |
|  2 | yeganaaa |  23 | China |
|  3 | yeganaaa |  23 | China |
+----+----------+-----+-------+
3 rows in set (0.00 sec)

mysql>

**Comment by mguinness** [comment]
Can you share your MySQL schema and also the SQL logs when the inserts are made?
