### ISSUE TITLE
DbUpdateConcurrencyException not being thrown in rare circumstances

### ISSUE THREAD

**Issue by shaynevanasperen** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#403]
### Steps to reproduce
Can only seem to reproduce this in my solution. I've tried making a small reproduction of it without success.

### The issue
When marking an entity column as a concurrency token and then simulating a concurrency conflict the call to `SaveChangesAsync()` fails to throw a `DbUpdateConcurrencyException`.

### Further technical details

MySQL version: **5.7**
Operating system: **Windows 10 Pro**
Pomelo.EntityFrameworkCore.MySql version: **2.0.0**

Other details about my project setup:
Not using EF migrations, but rather creating database schema manually. The error occurs when I try to update an entity that has a composite primary key composed of two columns/properties. The entity in question has a collection of child entities and each one of those child entities has it's own collection of child entities. The scenario that I see this on is when the the update includes the addition of 3 child entities in the lowest level of the hierarchy as well as making a change to a string property on the root entity.

**Comment by caleblloyd** [comment]
This may already be fixed by #407 in the latest prerelease. It will ultimately be revisited in #411 for 2.0.1.

Please try the latest prerelease and report back, thanks.

**Comment by shaynevanasperen** [comment]
@caleblloyd I decided to skip testing the latest release and instead clone your branch for #411. Running against that works for me now. It also fixes another bug I had which was due to #405. I'd like you to publish 2.0.1 as soon as possible now so that I can start using it, thanks.

**Comment by caleblloyd** [comment]
2.0.1 won't be published until upstream EF releases their 2.0.1. We'll have a new 2.0.1-preview up on nuget by sometime tomorrow with this fix though.
