### ISSUE TITLE
DbUpdateException when adding entities with parent / child relationship and a many-many relationship

### ISSUE THREAD

**Issue by neoGeneva** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#405]
### Steps to reproduce
Example project included here: https://github.com/neoGeneva/PomeloDbUpdateException

Create a data model that has three entities:
1. One with a primary key (e.g. `Category`)
2. One with a parent / child relationship (e.g.`Product`)
3. One that creates a many to many relationship between the first two entities (e.g. `ProductCategory`)

### The issue
When adding multiple instances of `Product` and `ProductCategory` I'm getting a `DbUpdateException` complaining that an instance with that primary key already exists. I've executed the same code against SqlServer with Microsoft.EntityFrameworkCore.SqlServer@2.0.0 and the issues doesn't exist there.

I've done some debugging and it looks like the SQL that executes to insert the `ProductCategory` and executes `SELECT ROW_COUNT()` is assumed to be a `ProductId` by `Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch::Consume` because it doesn't move the `DbDataReader` to the next result when the mapping is `ResultSetMapping.NoResultSet`

### Exception
```
Exception message:  The instance of entity type 'Product' cannot be tracked because another instance with the key value 'ProductId:1' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
Stack trace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.UpdateIdentityMap(InternalEntityEntry entry, IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.PropertyChanged(InternalEntityEntry entry, IPropertyBase propertyBase, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.set_Item(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetCurrentValue(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.Update.ColumnModification.set_Value(Object value)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.PropagateResults(ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
```

### Further technical details

MySQL version: 5.7.14
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.0.0

Other details about my project setup:
Visual Studio 2017 v15.4.0
SQL Server 2014

**Comment by mguinness** [comment]
Please see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/397.

**Comment by neoGeneva** [comment]
Thanks! 

Yeah definitely a duplicate of #397 / #379, setting MaxBatchSize to 1 stopped the exception to me

**Comment by mguinness** [comment]
@Kagamine @caleblloyd Should the default be set to 1 instead of 1000?

**Comment by neoGeneva** [comment]
Looks like the SQL Server version just doesn't do a row count during batch operations, and the `Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch::Consume` assumes that's the case.

Perhaps this line needs to be changed to call a similar function that doesn't do a count, like : https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/7ef5845aee635011a2b0e8ec3f0d40258f846a2e/src/EFCore.MySql/Update/Internal/MySqlUpdateSqlGenerator.cs#L74

Which is what the SqlServer version does here:

https://github.com/aspnet/EntityFrameworkCore/blob/6c425d96f4553ae122d4ca784a75def379432679/src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs#L83

Just for reference here's a log for the same code executed against SqlServer vs MySql, and you can see for the `ProductCategory` rows it doesn't generate any result sets.

[mysql.log](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/1389743/mysql.log)
[sqlserver.log](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/1389744/sqlserver.log)

**Comment by caleblloyd** [comment]
@mguiness we should fix the bug and use the same default as SQL Server

**Comment by mguinness** [comment]
@caleblloyd My thinking was to simply change [MySqlModificationCommandBatch](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Update/Internal/MySqlModificationCommandBatch.cs#L44) to the following as an interim fix:

`_maxBatchSize = (maxBatchSize == null ? 1 : Math.Min(maxBatchSize, MaxRowCount));`

As for the bug itself, it's a little over my head and I have no idea of the work involved.

I noticed the parameter increment is still off, can we release a new version on nuget that includes PR https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/389?

**Comment by caleblloyd** [comment]
I can take a look at both issues sometime this week and I'll push an update through

**Comment by chazt3n** [comment]
FYI this came back in 3.1 release - exact duplicate of the aforementioned complaints

I had never seen it until upgrading a working 2.x example to 3.x

**Comment by lauxjpn** [comment]
@chazt3n I used the following code, based on the example project @neoGeneva posted 2 years ago, but was **unable to reproduce** the issue. It runs without any problems:

```c#
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Pomelo.EntityFrameworkCore.MySql.Storage;

namespace IssueConsoleTemplate
{
    public class Category
    {
        public int CategoryId { get; set; }
        public string Name { get; set; }

        public ICollection<ProductCategory> ProductCategories { get; set; } = new HashSet<ProductCategory>();
    }

    public class Product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public int? ParentProductId { get; set; }

        public Product ParentProduct { get; set; }
        public ICollection<Product> ChildProducts { get; set; } = new HashSet<Product>();
        public ICollection<ProductCategory> ProductCategories { get; set; } = new HashSet<ProductCategory>();
    }

    public class ProductCategory
    {
        public int ProductId { get; set; }
        public int CategoryId { get; set; }

        public Product Product { get; set; }
        public Category Category { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<Category> Categories { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql("server=127.0.0.1;port=3306;user=root;password=;database=Issue405",
                    b => b.ServerVersion(new ServerVersion("8.0.18-mysql")))
                .UseLoggerFactory(LoggerFactory.Create(b => b
                    .AddConsole()
                    .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Category>(entity =>
            {
                entity.Property(e => e.Name)
                    .HasMaxLength(255);

                entity.HasMany(e => e.ProductCategories)
                    .WithOne(e => e.Category)
                    .HasForeignKey(e => e.CategoryId);

                entity.HasData(
                    new Category {CategoryId = 1, Name = "Category 1"},
                    new Category {CategoryId = 2, Name = "Category 2"}
                );
            });

            modelBuilder.Entity<Product>(entity =>
            {
                entity.Property(e => e.Name)
                    .HasMaxLength(255);

                entity.HasOne(e => e.ParentProduct)
                    .WithMany(e => e.ChildProducts)
                    .HasForeignKey(e => e.ParentProductId);

                entity.HasMany(e => e.ChildProducts)
                    .WithOne(e => e.ParentProduct)
                    .HasForeignKey(e => e.ParentProductId);

                entity.HasMany(e => e.ProductCategories)
                    .WithOne(e => e.Product)
                    .HasForeignKey(e => e.ProductId);
            });

            modelBuilder.Entity<ProductCategory>(entity =>
            {
                entity.HasKey(e => new {e.ProductId, e.CategoryId});
                
                entity.HasOne(e => e.Category)
                    .WithMany(e => e.ProductCategories)
                    .HasForeignKey(e => e.CategoryId);

                entity.HasOne(e => e.Product)
                    .WithMany(e => e.ProductCategories)
                    .HasForeignKey(e => e.ProductId);
            });
        }
    }

    internal class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var categoryId = context.Categories
                .OrderBy(c => c.CategoryId)
                .Select(c => c.CategoryId)
                .First();

            var products = new List<Product>();

            for (var i = 0; i < 1000; ++i)
            {
                var product = new Product()
                {
                    Name = $"Product {i}",
                };

                product.ProductCategories.Add(new ProductCategory()
                {
                    CategoryId = categoryId
                });

                if (i % 2 == 1)
                {
                    product.ParentProduct = products[i - 1];
                }

                products.Add(product);
            }

            context.Products.AddRange(products);
            context.SaveChanges();
        }
    }
}
```

If you think, that this issue has returned again, please provide us with more information (model, model definition, `CREATE TABLE` statements and the code that throws the exception) or a sample project, that reproduces the issue.

**Comment by chazt3n** [comment]
@lauxjpn the exact prerequisites for this error to occur were in place when this error was seen

It's a parent with child entity involved in multiple many to many relationships within the same object graph - however the actual problem was a simple breaking change from EF Core 2.1 => 3.1 where the identifiers must be either explicitly created in code or explicitly created in the database.

We were previously allowing external consumers (in a distributed system) to pass in an ID, and if not the database would generate one for them. We caught this, changed it to where the code itself generates an Id if one is not provided, and it all works fine. 

Thank you for looking into this and responding - all is well and I was wrong

**Comment by lauxjpn** [comment]
@chazt3n Thanks for sharing the underlying cause!
