### ISSUE TITLE
Parent-Child table error

### ISSUE THREAD

**Issue by cycbluesky** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#406]
I use .net core 2.0 and Pomelo.EntityFrameworkCore.MySql 2.0.1-preview-10069.

When I create parent and it's children data, then save batchly, I'll cause error.

1. Table model
DROP TABLE IF EXISTS `order`;

CREATE TABLE `order` (
    `order_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(10) NOT NULL,    
    `created_on` DATETIME NOT NULL,
    `created_by` INT(11) UNSIGNED NOT NULL DEFAULT '0',
    `changed_on` DATETIME NOT NULL,
    `changed_by` INT(11) UNSIGNED NOT NULL DEFAULT '0',
    PRIMARY KEY (`order_id`)
);

/************************************************************************************/
DROP TABLE IF EXISTS `order_item`;

CREATE TABLE `order_item`(
	`item_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`order_id` INT(11) UNSIGNED NOT NULL,
	`name` VARCHAR(50) NOT NULL,	
	`count` int UNSIGNED NOT NULL NOT NULL,	
    `created_on` DATETIME NOT NULL,
    `created_by` INT(11) UNSIGNED NOT NULL DEFAULT '0',
    `changed_on` DATETIME NOT NULL,
    `changed_by` INT(11) UNSIGNED NOT NULL DEFAULT '0',
    PRIMARY KEY (`item_id`),
    FOREIGN KEY(order_id) REFERENCES `order`(order_id) ON DELETE CASCADE ON UPDATE CASCADE
 );  

2. Test code
var order = new Order()
            {                
                Code = "XF001",
                CreatedBy = 1,
                ChangedBy = 1,
                OrderItem = new List<OrderItem>()
                {
                    new OrderItem()
                    {
                        Name = "Child1",
                        Count = 100,
                        CreatedBy = 1,
                        ChangedBy = 1
                    },
                    new OrderItem()
                    {
                        Name = "Child2",
                        Count = 500,
                        CreatedBy = 1,
                        ChangedBy = 1
                    }
                }
            };

            _context.Order.Add(order);

            await _context.SaveChangesAsync();

3. The error detail
An unhandled exception occurred while processing the request.

InvalidOperationException: The instance of entity type 'OrderItem' cannot be tracked because another instance with the key value 'ItemId:0' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap.Add(TKey key, InternalEntityEntry entry)

I checked the auto-generated model code,  
                entity.ToTable("order");
                entity.Property(e => e.OrderId)
                    .HasColumnName("order_id")
                    .HasColumnType("int(11) unsigned")
                    .ValueGeneratedNever();

I found a new method **ValueGeneratedNever()** called,  if I comment it,  then no errors occurred.

so what's the meaning of  **ValueGeneratedNever()**, there's no this method in 1.x code.

**Comment by caleblloyd** [comment]
This code looks like it should work, may be related to #379 

We will fix for 2.0.1

**Comment by caleblloyd** [comment]
Can you verify if workaround in #379 fixes and close this if so?

**Comment by cycbluesky** [comment]
It will cause error even I use a single table with auto-increment primary key. Is it related to the **ValueGeneratedNever()** function? Once I comment it, the error disappeared.

      And I checked the SqlServer generator, It'll never generate **ValueGeneratedNever()** method for identity field. For example:
 -- SQL Server
modelBuilder.Entity<TestOrg>(entity =>
            {
                entity.HasKey(e => e.OrgId);

                entity.ToTable("test_org");

                **entity.Property(e => e.OrgId).HasColumnName("org_id");**

                entity.Property(e => e.ChangedBy).HasColumnName("changed_by");

                entity.Property(e => e.ChangedOn)
                    .HasColumnName("changed_on")
                    .HasColumnType("datetime");

                entity.Property(e => e.CreatedBy).HasColumnName("created_by");

                entity.Property(e => e.CreatedOn)
                    .HasColumnName("created_on")
                    .HasColumnType("datetime");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnName("name")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ParentId).HasColumnName("parent_id");

                entity.Property(e => e.TenantId).HasColumnName("tenant_id");
            });           

-- MySql
          modelBuilder.Entity<TestOrg>(entity =>
            {
                entity.HasKey(e => e.OrgId);

                entity.ToTable("test_org");

                entity.Property(e => e.OrgId)
                    .HasColumnName("org_id")
                    .HasColumnType("int(11) unsigned")
                    .ValueGeneratedNever();

                entity.Property(e => e.ChangedBy)
                    .HasColumnName("changed_by")
                    .HasColumnType("int(11) unsigned")
                    .HasDefaultValueSql("0");

                entity.Property(e => e.ChangedOn)
                    .HasColumnName("changed_on")
                    .HasColumnType("datetime");

                entity.Property(e => e.CreatedBy)
                    .HasColumnName("created_by")
                    .HasColumnType("int(11) unsigned")
                    .HasDefaultValueSql("0");

                entity.Property(e => e.CreatedOn)
                    .HasColumnName("created_on")
                    .HasColumnType("datetime");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnName("name")
                    .HasMaxLength(50);

                entity.Property(e => e.ParentId)
                    .HasColumnName("parent_id")
                    .HasColumnType("int(11) unsigned")
                    .HasDefaultValueSql("0");

                entity.Property(e => e.TenantId)
                    .HasColumnName("tenant_id")
                    .HasColumnType("int(11) unsigned");
            });

Next is the test code and error details.
`var newOrg = new TestOrg()
            {
                Name = "Name",
                TenantId = 1,
                CreatedBy = 1,
                ChangedBy = 1
            };
            
            _context.TestOrg.Add(newOrg);  

            await _context.SaveChangesAsync();`

DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(int commandIndex, int expectedRowsAffected, int rowsAffected)

Table definition:
CREATE TABLE `test_org`(
	`org_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`tenant_id` INT(11) UNSIGNED NOT NULL,
	`name` VARCHAR(50) NOT NULL,	
	`parent_id` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Parent org id',
    `created_on` DATETIME NOT NULL,
    `created_by` INT(11) UNSIGNED NOT NULL DEFAULT '0',
    `changed_on` DATETIME NOT NULL,
    `changed_by` INT(11) UNSIGNED NOT NULL DEFAULT '0',
    PRIMARY KEY (`org_id`)    
 );

**Comment by mds858** [comment]
I had an issue where context wouldn't update after multiple ef savechanges. My code looks like
`context.Users.Add(user)
context.SaveChanges();
...
context.Request.Add(request)
context.SaveChanges();
...
var base = new Base { userid = user.id, requestid = request.id}
context.Base.Add(base);
context.SaveChanges();`

This would always through ForeignKey constaint error since user.id and request.id were always 0.
Removing ValueGeneratedNever() worked.

**Comment by mguinness** [comment]
http://www.learnentityframeworkcore.com/configuration/fluent-api/valuegeneratednever-method

> Entity Framework Core does not implement a value generation strategy.
