### ISSUE TITLE
All conections keep in sleep state

### ISSUE THREAD

**Issue by demorales13** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#409]
Hi, 

I'm using pomelo.entityframework.core 2.0, the datacontext look like this:

```
    public class CavasContext : IdentityDbContext<CavasUser>
    {
        private readonly CavasCurrentUser _cavasCurrentUser;

        public CavasContext(DbContextOptions<CavasContext> options, CavasCurrentUser cavasCurrentUser)
        : base(options)
        {
            _cavasCurrentUser = cavasCurrentUser;
            Database.EnsureCreated();
        }
        ....
     }
```

Repository pattern base:

```
    public class Repository<TEntity> : IRepository<TEntity> where TEntity : class
    {
        protected readonly DbContext _context;
        protected readonly DbSet<TEntity> _dbSet;

        public Repository(DbContext context)
        {
            _context = context;
            _dbSet = context.Set<TEntity>();
        }

        public virtual void Add(TEntity entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException("entity");
            }

            _dbSet.Add(entity);
        }
....
```

The conections string:
`server=xxx.xxx.x.x;userid=admin;pwd=xxxxxxx;port=3306;database=db;sslmode=none;
`

### The issue
The connections remain in sleep state forever.

Is there anything I should do to avoid this behavior? (settings, changes version, etc)

### Further technical details

MySQL version:  5.7.20
Operating system:  Docker over ubuntu
Pomelo.EntityFrameworkCore.MySql version: 2.0.0

**Comment by caleblloyd** [comment]
Do you mean that you see connections sleeping after work has been done?  If so it's because of Connection Pooling.  You can tweak your connection pool settings by changing settings in your connection string, here's the docs:

https://mysql-net.github.io/MySqlConnector/connection-options/
