### ISSUE TITLE
JsonObject in 1.0.0?

### ISSUE THREAD

**Issue by matthewjcooper** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#41]
should this work in 1.0.0 ? 
public JsonObject<List<string>> Tags { get; set; } // Json storage (MySQL 5.7 only)

If so, what library/namespace does JsonObject come from?

**Comment by Kagamine** [comment]
System

**Comment by matthewjcooper** [comment]
Ah, yeah i can get it in my asp.net app, but my models are defined in a class library targeting netstandard1.6. I still don't get this standard vs coreapp stuff :).  Apparently System.JsonObject doesn't exist in netstandard1.6.

I
