### ISSUE TITLE
Publish a WIP release: 2.0.0.1

### ISSUE THREAD

**Issue by Kagamine** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#413]

**Comment by caleblloyd** [comment]
Let's see how [2.0.1-preview-10071](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.0.1-preview-10071) works, if it's stable for a week or so we should go ahead and promote it to `2.0.0.1`

**Comment by Kagamine** [comment]
I am pushing some fixes for scaffolding

**Comment by Kagamine** [comment]
Will 27th be better?

**Comment by caleblloyd** [comment]
Sure 27th should be fine

**Comment by Kagamine** [comment]
Released 10072, fixed two scaffolding bugs.

**Comment by caleblloyd** [comment]
10073 released, fixes #418 and uses EF's buffering
