### ISSUE TITLE
FirstChanceExceptionEventArgs Exception

### ISSUE THREAD

**Issue by ch19751116** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#420]
### Steps to reproduce
using System;
using System.Runtime.ExceptionServices;
using Microsoft.EntityFrameworkCore;
using MySqlTest;
namespace MySqlTest
{
      public class UserPassword 
    {
        public string Password { get; set; }
        public string Id { get; set; }
    }
    public class MyContext : DbContext
    {
        public DbSet<UserPassword> Users { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder
                .UseMySql(@"server=rm-XXXXXXXXXXXX.mysql.rds.aliyuncs.com;database=XXXXXXXXXXXX;uid=XXXXXXXXXXXX;pwd=XXXXXXXXXXXX;charset='gbk';SslMode=None");
    }
}
public static class Program
{
    public static void Main()
    {
        AppDomain.CurrentDomain.UnhandledException += UnhandledExceptionEventHandler;
        AppDomain.CurrentDomain.FirstChanceException += FirstChanceExceptionEventHandler;
        using (var context = new MyContext())
        {
            context.Database.EnsureCreated();
            var user = new UserPassword { Id = "Yuuko2" };
            context.Add(user);
            context.SaveChanges();
        }
        Console.Read();
    }
    static void UnhandledExceptionEventHandler(object sender, UnhandledExceptionEventArgs e)
    {
        Console.WriteLine(e.ExceptionObject.ToString());
    }
    static void FirstChanceExceptionEventHandler(object sender, FirstChanceExceptionEventArgs e)
    {
        Console.WriteLine(e.Exception.ToString());
    }
}
### The issue
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Further technical details
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Microsoft.EntityFrameworkCore.resources'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Microsoft.EntityFrameworkCore.resources'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Microsoft.EntityFrameworkCore.resources'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Microsoft.EntityFrameworkCore.Relational.resources'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Microsoft.EntityFrameworkCore.Relational.resources'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Microsoft.EntityFrameworkCore.Relational.resources'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)

MySQL version: 5.7
Operating system: windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.0.0

Other details about my project setup:

**Comment by Kagamine** [comment]
We could not repro your issue, please provide more information about this.

**Comment by ch19751116** [comment]
please config dbconectstring,and run this project,I had  commit the issue screenshot on this mail


------------------ 原始邮件 ------------------
发件人: "Yuko Zheng";<notifications@github.com>;
发送时间: 2017年10月29日(星期天) 下午4:57
收件人: "PomeloFoundation/Pomelo.EntityFrameworkCore.MySql"<Pomelo.EntityFrameworkCore.MySql@noreply.github.com>;
抄送: "无尽的任务"<253024649@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql]FirstChanceExceptionEventArgs Exception (#420)




We could not repro your issue, please provide more information about this.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
         
  


从QQ邮箱发来的超大附件

TIM截图20171030130021.png (21.8K, 2017年11月29日 13:04 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=77376663fccb9c9ab0ee726c1563514a0e055605565b075d14535157554e575d0d0e4b02510206480a0f560002015a015b055601337a6331707adbbbfedf51550800575300535256090754521d130d02390a&t=exs_ftn_download&code=97fc3cce




TIM截图20171030130353.png (43.9K, 2017年11月29日 13:04 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7834393048349999bfed2d3f1264544952565c07055350501b0201090c495253540714090d51554b55070f530251515705020900347d66327f7984e8f9d85456070308000754575506070c031a1408013609&t=exs_ftn_download&code=64904dff
