### ISSUE TITLE
MySqlValueGenerationStrategy does not exist in the current context

### ISSUE THREAD

**Issue by yusufys** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#427]
### The code

 
```
       migrationBuilder.CreateTable(
                name: "Favourites",
                columns: table => new
                {
                    FavId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    EventId = table.Column<int>(type: "int", nullable: false),
                    UserId = table.Column<string>(type: "varchar(127)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Favourites", x => x.FavId);
                    table.UniqueConstraint("AK_Favourites_EventId_UserId", x => new { x.EventId, x.UserId });
                    table.ForeignKey(
                        name: "FK_Favourites_Events_EventId",
                        column: x => x.EventId,
                        principalTable: "Events",
                        principalColumn: "EventId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Favourites_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });
```

### The issue
When I try to create a migration this error comes:
MySqlValueGenerationStrategy does not exist in the current context, the problem is getting solved by adding an enum similar to ( https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Metadata/MySqlValueGenerationStrategy.cs ) 
but I don't know if this solution is good or not, I need your help please?

```
Exception message: MySqlValueGenerationStrategy does not exist in the current context

```

### Further technical details

MySQL version: 5.7
Operating system: Win10
VS2017, ASP.net CORE 2.0
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

Other details about my project setup: the context is in another project.

**Comment by Kagamine** [comment]
Hi @yusufys, could you provide the full solution to us for investigating your issue? The info which you provided is not enough to repro that.

**Comment by yusufys** [comment]
Dear @Kagamine , I've created a Sample project which is having the same problem and I have uploaded it to my github acc.

[WebApplication2](https://github.com/yusufys/WebApplication2)

Please notice that when I add this code snippet to the migration class:
```
   public enum MySqlValueGenerationStrategy
    {
        IdentityColumn,
        ComputedColumn
    }

```
To emphasize only, that I was only asking if doing the thing I've done (adding that code snippet to the migration class) is it an OK solution or it'll produce troubles for me in the furure?
Thanks for your help!
Regards,
 Yusuf

**Comment by yusufys** [comment]
I'm very sorry, the problem was I didn't install the required nuget package to the DataLayer's project.
Sorry and thanks for your efforts!

**Comment by smithaitufe** [comment]
Why was this issue closed?

I am experiencing similar thing. 

What is the recommended solution?\

This is the error 
`The name 'MySqlValueGenerationStrategy' does not existin the current context `

**Comment by SistemasSouza** [comment]
I am same error

**Comment by SistemasSouza** [comment]
thanks @yusufys it work well

**Comment by alfreql** [comment]
I had to add this using: `using Microsoft.EntityFrameworkCore.Metadata;` and switch from uppercase to lowercase from: `MySQLValueGenerationStrategy.IdentityColumn` to `MySqlValueGenerationStrategy.IdentityColumn`

**Comment by dide0100** [comment]
This issue seems still to be or has come back on https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/8.0.0-beta.2 
Can anyone confirm this?
Thank you

**Comment by lauxjpn** [comment]
@dide0100 This should not be the case. If it is, please provide a model (class and Fluent API) and (if necessary) some instructions for us to reproduce the issue. Once you posted that, we can reopen the issue and check it again. Thanks!

**Comment by iSeeLittleMore** [comment]
> I had to add this using: `using Microsoft.EntityFrameworkCore.Metadata;` and switch from uppercase to lowercase from: `MySQLValueGenerationStrategy.IdentityColumn` to `MySqlValueGenerationStrategy.IdentityColumn`

It is work for me, thanks
