### ISSUE TITLE
scaffold生成Context类时，如何可以把ValueGeneratedNever()自动生成时换为ValueGeneratedOnAdd()

### ISSUE THREAD

**Issue by ajdwfnhaps** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#429]
### Steps to reproduce
dotnet ef dbcontext scaffold "Server=10.0.1.7;User Id=root;Password=a123456;Database=test_db" "Pomelo.EntityFrameworkCore.MySql" -o Models

### The issue
生成出来的Context类，如何可以把ValueGeneratedNever()自动生成时换为ValueGeneratedOnAdd() ?

 modelBuilder.Entity<ActivityTransfersMachines>(entity =>
            {
                entity.ToTable("activity_transfers_machines");

                entity.HasIndex(e => e.TransfersOrderId)
                    .HasName("transfers_order_id");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("int(11)")
                    .ValueGeneratedNever();

### Further technical details

MySQL version: 5.6
Operating system: win 7
Pomelo.EntityFrameworkCore.MySql version:2.0.0.1

**Comment by Kagamine** [comment]
Duplicated of #398
