### ISSUE TITLE
Problems connecting to MySQL with version 2.0

### ISSUE THREAD

**Issue by YandyZaldivar** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#434]
I use dependency injection to resolve DbContext objects and other services in non asp.net core environment. This works fine with the provider prior to version 2.0. After update to the latest 2.0 version the system turns unstable and I get randoms exceptions of 'Unable to connect to any of the specified MySQL hosts'.

The following construction that I used successfuly prior to 2.0 is working with problems after update.

`dbContext.Database.GetDbConnection()`

The first time I try to get a dbconnection this way it throws 'Unable to connect to any of the specified MySQL hosts' or it tries to connect inmediately and fails because the connection string is not properly configured. The workaround here is to catch the exception and retry the operation, the second time instead of return a null dbconnection it returns a valid connection that I can configure and properly use. Prior to 2.0 the same code worked flawlessly.

Some other normal usage of DbContext connections are also failing related of how I use the scope to get the services from dependency injection. The key here is that this doesn't  occur with previous version. In general I am just reporting this strange behavior with connections in my case.

OS: Win10
MySQL: 8.x
Pomelo MySQL: 2.0.0.1

**Comment by caleblloyd** [comment]
This is not enough info to recreate.  We need at least a stack trace, or better yet a Git project that we can clone that exhibits the behavior so that we can recreate and track down the bug.

**Comment by YandyZaldivar** [comment]
I know that is not enough information to solve the problem if it is related to a bug on your side. Yet I am sharing my problem to see if there are other coincidendes. For the moment I have reverted to 1.x, when I have more time I will try version 2.x again and give more information if the problem persist. Thanks.

**Comment by YandyZaldivar** [comment]
I have more information about this issue.

Instead of targeting the package I included your sources directly and I found the problem is related to the implementation of `Lazy<MySqlConnectionSettings> _lazyConnectionSettings` in the `MySqlOptions` class. The problem arise when you try to connect to a not running mysql server instance, because the MySqlOptions is pooled via dependency injection and the lazy connection settings can only be configured once because of the nature of the lazy implementation. After the MySql server start running a new connection try to the MySql server can succeed when a new `MySqlOptions` instance is used but new connections using the failed instance will fail with _Unable to connect to any of the specified MySQL hosts_ because the `_lazyConnectionSettings` was initially configured when the MySql server was down.

The correct behaviour should be to fail when the MySql server is down but suceed after the MySql server be properly started. For you to understand better the problem I have created a quick fix to solve the problem temporary by modifying your code from:

```
        public MySqlOptions()
        {
            _lazyConnectionSettings = new Lazy<MySqlConnectionSettings>(() =>
            {
                if (_relationalOptions.Connection != null)
                    return MySqlConnectionSettings.GetSettings(_relationalOptions.Connection);
                return MySqlConnectionSettings.GetSettings(_relationalOptions.ConnectionString);
            });
        }
```

to this:

```
        public MySqlOptions()
        {
            InitializeLazyConnectionSettings();
        }

        public void InitializeLazyConnectionSettings()
        {
            _lazyConnectionSettings = new Lazy<MySqlConnectionSettings>(() =>
            {
                try
                {
                    if (_relationalOptions.Connection != null)
                        return MySqlConnectionSettings.GetSettings(_relationalOptions.Connection);
                    return MySqlConnectionSettings.GetSettings(_relationalOptions.ConnectionString);
                }
                catch (Exception ex)
                {
                    InitializeLazyConnectionSettings();
                    throw ex;
                }
            });
        }
```

This way when the `_lazyConnectionSettings ` fails I give it the opportunity to reeinitialize on subsequent calls to:
`public virtual MySqlConnectionSettings ConnectionSettings => _lazyConnectionSettings.Value;`

Though the problem fix should be addressed in a more appropriate way.

**Comment by caleblloyd** [comment]
Thanks for finding the root cause.  I'll push an update for it

**Comment by caleblloyd** [comment]
It looks like the fix is simple, just set `LazyThreadSafetyMode.PublicationOnly` to avoid exception caching:

https://docs.microsoft.com/en-us/dotnet/framework/performance/lazy-initialization

**Comment by izaruba** [comment]
@caleblloyd The connection string if invalid is still cached in a `MySqlOptionsExtension` object. 
Thus, if specify the wrong CS for the first connection, there is no chance to override it in future.

**Comment by caleblloyd** [comment]
If the Connection String was invalid, the `Lazy<MySqlConnectionSettings>` method would throw an Exception and would not be cached.

Typically changing the Connection String would require restarting the process anyways, since Connection Strings are typically stored in a properties file and loaded into the program at startup time.

**Comment by izaruba** [comment]
@caleblloyd The problem is that the invalid connection string provided the very first time is cached within `MySqlOptionsExtension _relationalOptions` field and then no matter what changes `MySqlConnectionSettings.GetSettings(_relationalOptions.ConnectionString)` will always fail when `MySqlConnectionSettings` will make an attempt to get the server version since it uses the wrong connection string.

What do you think about adding an extra check to `MySqlOptions.Validate(IDbContextOptions options)`?

```
public virtual void Validate(IDbContextOptions options)
{
    if (_relationalOptions.ConnectionString == null && _relationalOptions.Connection == null)
    	throw new InvalidOperationException(RelationalStrings.NoConnectionOrConnectionString);
    
    var csb = new MySqlConnectionStringBuilder(_relationalOptions.ConnectionString)
    {
    	Database = "",
    	Pooling = false
    };
    
    using (var schemalessConnection = new MySqlConnection(csb.ConnectionString))
    {
    	schemalessConnection.Open();
    }
}
```
it doesn't help against caching the connection string, but at least it won't cache the wrong one.
