### ISSUE TITLE
Publish 2.0.1 release

### ISSUE THREAD

**Issue by yukozh** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#442]
The upstream ef core 2.0.1 is ready on NuGet.

**Comment by caleblloyd** [comment]
I am working on this, the 2.0.1 upgrade is seamless from to providers, which is nice!

I am having trouble with some of the Retry Related code that was added in #425 and #431 though, specifically getting a Null Reference Exception when no database is found.  Also having a hard time matching that code to the EF Upstream code to look for places where it may need upgrades.  I'm going to have to work on fixing that before I can get a PR open for 2.0.1.

**Comment by caleblloyd** [comment]
Should we publish a `2.0.1-preview1` to nuget to let people try next week, then tag the release at the end of the week?

**Comment by yukozh** [comment]
Yes

**Comment by caleblloyd** [comment]
[2.0.1-preview1-final](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.0.1-preview1-final), please provide feedback here or open an issue!

**Comment by yukozh** [comment]
I will publish on 24th Nov if there will be no serious issue.

**Comment by caleblloyd** [comment]
Sounds good, do we want to include #446 in a `2.0.1-preview2-final` today, and promote that one on the 24th if all is good?

**Comment by yukozh** [comment]
Yes, I will build 2.0.1 in myget with this change.
