### ISSUE TITLE
JSON Object Migrations Missing Using

### ISSUE THREAD

**Issue by matthewjcooper** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#45]
### Steps to reproduce
Add a field to a model for JSONObject:

`public JsonObject<List<string>> AlternateNames {get;set;}`

Generate a migration using:

`dotnet ef migrations add NewFieldTest`

### The issue
The migrations are created, but the Designer class and the Snapshot class do not include the required using statement:

`using System.Collections.Generic;`

This is required because the code for the field in the migrations contains LIst, which is in the System.Collections.Generic namespace:

`b.Property<JsonObject<List<string>>>("AlternateNames");`

### Workaround:

Manually add using statement to the code after each newly generated migration.

### Further technical details

MySQL version: 5.7
Operating system: mac osx el capitan
Pomelo.EntityFrameworkCore.MySql version: 1.0.0

**Comment by Kagamine** [comment]
Duplicated of aspnet/EntityFramework#6367

**Comment by caleblloyd** [comment]
@matthewjcooper there's an example of automating this using a script for [powershell](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/scripts/rebuild.ps1) and [bash](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/scripts/rebuild.sh)

You could adapt the scripts to work when generating a migration
