### ISSUE TITLE
MySql5.6 datetime scaffolding generate bug

### ISSUE THREAD

**Issue by ajdwfnhaps** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#451]
### Steps to reproduce
dotnet ef dbcontext scaffold "Server=10.0.1.7;User Id=xxx;Password=xxx;Database=aimei_finance" "Pomelo.EntityFrameworkCore.MySql" -o Finance

### The issue
  `acc_create_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',

```
entity.Property(e => e.AccCreateTime)
                    .HasColumnName("acc_create_time")
                    .HasColumnType("datetime")
                    .();
```

### Further technical details

MySQL version: 5.6
Operating system: win7 sp1
Pomelo.EntityFrameworkCore.MySql version:2.0.1

**Comment by caleblloyd** [comment]
Closing due to issue age; please open more detailed issue with recreate if problem persists
