### ISSUE TITLE
Not able to call stored Procedures or Custom SQLs

### ISSUE THREAD

**Issue by abhiquiet** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#452]
### Steps to reproduce
I have seen the examples for .net core entity framework, for calling stored procedures. 
One such example is under

dataContext.Database
           .ExecuteSqlCommand("usp_InsertCategory @p0", catName);

### The issue
I am not able to fine ExecuteSqlCommand under Database object in the dbcontext. 

How can the functionality be added?
Is the work on the above function is under development?
In case there is way out for calling custom sql / call stored procedure, kindly let everyone know. 

### Further technical details

MySQL version: 5.6
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1-preview1-final

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/194.
