### ISSUE TITLE
Decimal

### ISSUE THREAD

**Issue by xiaozhenli** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#459]
How Can use  Decimal  Like  this? 
  // modelBuilder.Entity<Product>().Property(x => x.Free).HasPrecision(18, 4)
the default  mapping format  is :  
 // new DecimalTypeMapping("decimal(65, 30)", DbType.Decimal);
How  Can I  Override  decimal  format   by myself ?

**Comment by yukozh** [comment]
[Column(Type = "decimal(123)")]

**Comment by caleblloyd** [comment]
https://docs.microsoft.com/en-us/ef/core/modeling/relational/data-types

**Comment by AlexLeung** [comment]
What `using` statement do I need so that Column is recognized?

**Comment by AlexLeung** [comment]
Found it. `using System.ComponentModel.DataAnnotations.Schema;`
