### ISSUE TITLE
Query: Invalid SQL generated when use .StartsWith

### ISSUE THREAD

**Issue by cycbluesky** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#463]
### Steps to reproduce
`var result = _context.Student.Where(p => p.Name.StartsWith(studentName)).ToList();`

### The issue
The Query generated by this is:

``` 
Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@__studentName_0='多语' (Size = 50) (DbType = AnsiString)], CommandType='Text', CommandTimeout='20']
      SELECT `p`.`student_id`, `p`.`address`, `p`.`alias_name`, `p`.`birthday`, `p`.`center_id`, `p`.`changed_by`, `p`.`changed_on`, `p`.`city`, `p`.`created_by`, `p`.`created_on`, `p`.`district`, `p`.`enroll_on`, `p`.`gender`, `p`.`grade`, `p`.`name`, `p`.`name_py`, `p`.`province`, `p`.`school`, `p`.`tenant_id`
      FROM `student` AS `p`
      WHERE (`p`.`name` LIKE CONCAT(@__studentName_0,'%') AND (LEFT(`p`.`name`, LENGTH(@__studentName_0)) = @__studentName_0)) OR (@__studentName_0 = '')
```
the LEFT(`p`.`name`, LENGTH(@__studentName_0)) is not valid.  LENGTH(@__studentName_0) will get 6,
If the stored value in p.name is '多语言',  the expression (LEFT(`p`.`name`, LENGTH(@__studentName_0)) will get '多语言'， so it's not equal to @__studentName_0.
       I think `p`.`name` LIKE CONCAT(@__studentName_0,'%')  is enough for StartWith method,  why it generated so many conditions?

### Further technical details

MySQL version: 5.1.73-community
Operating system: Windows 10 Pro 1709 (x64)
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

**Comment by yukozh** [comment]
We don't support MySQL < 5.5, please upgrade your mysql server

**Comment by cycbluesky** [comment]
I've upgrade to 5.7 although there is nothing to do with the MySQL version.

(((`p`.`name` LIKE CONCAT(@__studentName,'%') AND (LEFT(`p`.`name`, **LENGTH(@__studentName**)) = @__studentName)) OR (@__studentName = '')) 

The sql should use CHAR_LENGTH instead of LENGTH when translated from .StartWith,
Even though, I think it should only be translated to  (`p`.`name` LIKE CONCAT(@__studentName,'%')

**Comment by akinix** [comment]
@cycbluesky 
this should not be a problem of `Pomelo`.

**CHAR_LENGTH()** ：Return number of **characters** in **argument**
**LENGTH()** ： Return the length of a **string** in **bytes**

**Server : MariaDB 10.2.12**
**Client : CentOs 7**
1. Test 1:
```mysql
MariaDB [(none)]> set names utf8;
Query OK, 0 rows affected (0.00 sec)

MariaDB [(none)]> select char_length('多语言'),length('多语言');
+--------------------------+---------------------+
| char_length('多语言')    | length('多语言')    |
+--------------------------+---------------------+
|                        3 |                   9 |
+--------------------------+---------------------+
1 row in set (0.00 sec)
```
2. Test 2:
```mysql
MariaDB [(none)]> set names gbk;
Query OK, 0 rows affected (0.00 sec)

MariaDB [(none)]> select char_length('多语言'),length('多语言');
+-------------------------+--------------------+
| char_length('多?')     | length('多?')     |
+-------------------------+--------------------+
|                       5 |                  9 |
+-------------------------+--------------------+
1 row in set (0.00 sec)
```
3. Test 3:
```mysql
MariaDB [(none)]> set names latin1;
Query OK, 0 rows affected (0.00 sec)

MariaDB [(none)]> select char_length('多语言'),length('多语言');
+--------------------------+---------------------+
| char_length('多语言')    | length('多语言')    |
+--------------------------+---------------------+
|                        9 |                   9 |
+--------------------------+---------------------+
1 row in set (0.00 sec)
```
---

**Comment by cycbluesky** [comment]
@akinix 
Yes, You're right. char_length() return then number of the characters and the length() return the length of a string in bytes.

For example, let's search the keyword '多语', the value stored in column name is '多语言'.
So the p.Name.StartWith("多语") will be translated to  

WHERE (
            **`p`.`name` LIKE CONCAT('多语','%') 
                        AND (LEFT(`p`.`name`, LENGTH('多语')) = '多语'))** 
            OR ('多语'= '')
now what happened? You'll get empty result since the **LEFT(p.name, LENGTH('多语')) = '多语')** is false.
This's my point.

**Comment by cycbluesky** [comment]
@yukozh 
Could you kindly explain why the .StartsWith translated to 
`p.name LIKE CONCAT('多语','%') AND (LEFT(p.name, LENGTH('多语')) = '多语'))  OR ('多语'= '')`
rather than `p.name LIKE CONCAT('多语','%')`.
I think the latter is enough.

**Comment by caleblloyd** [comment]
It comes straight from [EF SQL Server](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStartsWithOptimizedTranslator.cs)

Here is their [test case with all of the edge cases](https://github.com/aspnet/EntityFrameworkCore/blob/69f870ab1f32b3185c3599887fbe020c0f70c445/src/EFCore.Specification.Tests/Query/FunkyDataQueryTestBase.cs#L148-L181) that makes the other condition checks necessary
