### ISSUE TITLE
System.InvalidOperationException was raised with message of 'Could not find column definition for table: XX column: XX'

### ISSUE THREAD

**Issue by LiangZugeng** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#464]
### Steps to reproduce
1. Get the source code from [https://github.com/LiangZugeng/DBMigrationRenamingException.git](https://github.com/LiangZugeng/DBMigrationRenamingException.git)
2. Run "dotnet restore"
3. Open "Models/Model.cs" and change the connection string in OnConfiguring method to a valid MySQL server.
4. Run "dotnet ef database update"

### The issue
Exception was raised on the line of renaming a column.

```
Applying migration '20180109020802_Init'.
Applying migration '20180109021020_ChangePriorityDataType'.
System.InvalidOperationException: Could not find column definition for table: '`Posts`' column: PriorityNew
   at Microsoft.EntityFrameworkCore.Migrations.MySqlMigrationsSqlGenerator.Generate(RenameColumnOperation operation, IModel model, MigrationCo
mmandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__63_20(MigrationsSqlGenerator g, MigrationOperation o, IMo
del m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandLis
tBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass13_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not find column definition for table: '`Posts`' column: PriorityNew
```

### Further technical details

MySQL version: 5.7.20
Operating system: MacOS 10.13.2
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

Other details about my project setup:

In the first migration, the "Priority" column in "Posts" table was longtext. Later in the second migration we intended to change it to a ushort and migrate the data from the old column into the new column, so in the migration we added a new column called "PriorityNew" of ushort, and then migrate the data, dropped the "Priority" column and then renamed "PriorityNew" to "Priority".

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/292#issuecomment-312758209.  You probably need to [manually add code](http://www.learnentityframeworkcore.com/migrations#executing-custom-sql) to your migration.

**Comment by LiangZugeng** [comment]
@mguinness I read #292 you mentioned and the article you referred.

Actually I manually wrote the Up method in the second migration (the original auto-generated Up method only use AlterColumn to change the data type), the issue here is RenameColumn couldn't find the PriorityNew column added by previous AddColumn method which I don't understand.

`migrationBuilder.AddColumn<ushort>(name: "PriorityNew", table: "Posts", type: "smallint unsigned", nullable: false, defaultValue: 1);`

`migrationBuilder.DropColumn("Priority", "Posts");`

`migrationBuilder.RenameColumn("PriorityNew", "Posts", "Priority");`

@mguinness care to elaborate more on this to help me understand it? Was that the first AddColumn call didn't get committed into the DB or AddColumn/RenameColumn are not in the same transaction?

**Comment by yukozh** [comment]
MySQL does not support DDL with tx.

**Comment by LiangZugeng** [comment]
@yukozh Thanks for the answer, please pardon me if my question was too basic.

Since MySQL doesn't support DDL with transaction, the DDL operations should be committed to DB individually which makes the exception non-sense at all.

In the first line AddColumn would add a new column and since it's not in a transaction this should be effective immediately, so in the 3rd line RenameColumn should have had the correct new column (named PriorityNew and created in the 1st line) to rename, instead it raised an exception saying PriorityNew cannot be found. This is the point bothered me and I'm trying to figure that out.

**Comment by mguinness** [comment]
Based on https://github.com/aspnet/EntityFrameworkCore/issues/6322 it seems that migrations are in an implicit transaction.

Have you tried using raw SQL instead?  If that fails you'll probably have to create another migration.

`` migrationBuilder.Sql("ALTER TABLE `Posts` CHANGE `PriorityNew` `Priority` smallint unsigned"); ``
