### ISSUE TITLE
Execute custom sql with parameters error

### ISSUE THREAD

**Issue by cycbluesky** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#467]
### Steps to reproduce
```
var changedOnParameter = new MySqlParameter("@changedOn", MySqlDbType.DateTime)
                               { Value = DateTime.Today };            
            await _context.Database.ExecuteSqlCommandAsync("update course set changed_on=@changedOn where tenant_id=1", changedOnParameter);
```

### The issue
Exception throw.
An unhandled exception occurred while processing the request.
InvalidOperationException: No value provided for required parameter '@changedOn'.
Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary<string, object> parameterValues)

----------------------------------
Does Pomelo.EntityFrameworkCore.MySql support custom sql with parameters? Or something is wrong?

### Further technical details

MySQL version: 5.7
Operating system: Windows 10 Pro 1709 (x64)
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

**Comment by yukozh** [comment]
See the comments in this page: https://docs.microsoft.com/en-us/ef/core/querying/raw-sql

**Comment by cycbluesky** [comment]
@yukozh  
It's OK in ef core.
using(var context = new SampleContext())
{
    var commandText = "INSERT Categories (CategoryName) VALUES (@CategoryName)";
    var name = new SqlParameter("@CategoryName", "Test");
    context.Database.ExecuteSqlCommand(commandText, name);
}

but error in Pomelo.

Do you have any sample. I did not find any test case about using custom sql with multi parameters  in Pomelo.EntityFrameworkCore.MySql.

**Comment by mguinness** [comment]
@cycbluesky Using parameter names works in 1.1, but not in 2.0 currently.  However, you can use the following format to reference parameters by ordinal position:

`context.Database.ExecuteSqlCommand("INSERT Categories (CategoryName) VALUES (@p0)", "Test");`

Not sure why named parameters don't work in 2.0, but you could take a look at [MySqlRelationalCommand.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Storage/Internal/MySqlRelationalCommand.cs#L172) to see what might be occurring.
