### ISSUE TITLE
Testing with JsonObject<T>

### ISSUE THREAD

**Issue by Azsael** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#470]
### The issue

I am trying to write some unit tests over code that utilises a DbContext. 

As per EntityFrameworkCore recommendations, I am mocking out the DbContext by using the InMemory Test databases.

i.e.
			var options = new DbContextOptionsBuilder<EventContext>()
				.UseInMemoryDatabase(Guid.NewGuid().ToString())
				.Options;

However I am using MySQL 5.7 and have several Json columns using JsonObject 

When I try to run the tests, I am getting the below exception.

I was wondering if this is a flaw in the MySql implementation that needs to be solved or if there is a current solution to this?

I am working around this by creating a Testing Context that Ignores the JsonObject properties explicitly but would prefer something that isn't so... hacky?

```
System.InvalidOperationException : The property 'JsonObject<IDictionary<string, int>>.Object' could not be mapped, because it is of type 'IDictionary<string, int>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

**Comment by yukozh** [comment]
JsonObject is MySQL only type. It has not been supported in InMem provider.

**Comment by rcollette** [comment]
If issues such as this are not related to this project, why are then not being closed out?
