### ISSUE TITLE
IQuerable methods are not accessible from class library

### ISSUE THREAD

**Issue by nrk6208** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#471]
Asp.net core 2.0 project structure:
1) BAL (class library) -References(DAL)
2) DAL (class library)
3) WEBAPI (dotnet core 2.0) -References(BAL,DAL)

when i am trying to get list of records from the table,
from WEBAPI i am getting fine by using
- DbContext.tablename.ToList();
- DbContext.tablename.Where(e=>e.Id==Id).ToList();

But i can't get these ToList and Where methods from a class library
![image](https://user-images.githubusercontent.com/27271479/35379227-6bf506c2-01db-11e8-9d42-b1d1646ed039.png)

**Comment by caleblloyd** [comment]
`using Microsoft.EntityFrameworkCore;`

See sample code in [our tests](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/EFCore.MySql.FunctionalTests/Controllers/AsyncController.cs)

Please don't use the issue tracker for usage-based questions, post those to StackOverflow.  The issue tracker is for reporting bugs.

**Comment by yukozh** [comment]
using System.Linq;
