### ISSUE TITLE
Connection to db is prematurely opened when using DbContext.Database.GetDbConnection()

### ISSUE THREAD

**Issue by YandyZaldivar** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#476]
### Steps to reproduce

Sometimes I need to change my database password.

Consider the following code:

```
var dbContext = scope.GetService<MasterDbContext>();
var connection = dbContext.Database.GetDbConnection();
connection.ConnectionString = "..."; // I need to conditionaly configure my connection string here.
await dbContext.Database.OpenConnectionAsync().ConfigureAwait(false);
```
You will get an exception in the second line because Pomelo is trying to connect to the db using a previously configured connection string in the DbContext class.

### The issue

In the second line when I am getting a connection object with a bad configured connection string Pomelo is forcing a connection to the DB to get the server version. The problem is that I want to properly configure my connection string before I explicitly open the connection in line 4.

##### Workaround
Because the first run of the second line configure the internal services a second run of the same code returns a valid connection that I can properly configure and use.

```
while (true)
{
    try
    {
        dbContext = scope.GetService<MasterDbContext>();
        connection = dbContext.Database.GetDbConnection();
        connection.ConnectionString = "...";
        await dbContext.Database.OpenConnectionAsync().ConfigureAwait(false);
        break;
    }
    catch ...
    {
        if (connection == null)
            continue;
        ...
    }
}
```

##### Possible solution?

The following code is from Pomelo MySqlConnectionSettings class. As you can see the connection is opened in line 39. Can you refactor your logic to not open the connection implicitly or at least fail gracefully with a proper DbConnection object that can be further configured?
```
        public static MySqlConnectionSettings GetSettings(string connectionString)
        {
            var csb = new MySqlConnectionStringBuilder(connectionString);
            var settingsCsb = _settingsCsb(csb);
            return Settings.GetOrAdd(settingsCsb.ConnectionString, key =>
            {
                csb.Database = "";
                csb.Pooling = false;
                string serverVersion;
                using (var schemalessConnection = new MySqlConnection(csb.ConnectionString))
                {
                    schemalessConnection.Open();
                    serverVersion = schemalessConnection.ServerVersion;
                }
                var version = new ServerVersion(serverVersion);
                return new MySqlConnectionSettings(settingsCsb, version);
            });
        }
```

### Further technical details

MySQL version: 8.x
Operating system: Win10
Pomelo.EntityFrameworkCore.MySql version: 2.x

**Comment by mguinness** [comment]
@YandyZaldivar What is your use case?  Is it multi tenancy?  Changing connection string at runtime is a little unusual.  This post on [SO](https://stackoverflow.com/questions/36816215/dynamically-change-connection-string-in-asp-net-core) might offer some pointers.

**Comment by YandyZaldivar** [comment]
One of my specific use case is that at the moment of application starting for the first time the MySQL database is unpopulated and I need to initialize the whole data structure, including my code first migrations. 

`Arguments = $"--defaults-file=\"{Master.Config.Database.Engine.ConfigFile}\" --initialize"`

Because of that, the first password I am going to use to connect to MySQL is different (randomly generated). After that I set the final password and connection string I use on my DbContext.

```
var cmdstr = $"alter user 'root'@'localhost' identified by '{Master.Config.Database.Engine.Password}'";
commandResult = await dbContext.Database.ExecuteSqlCommandAsync(cmdstr).ConfigureAwait(false);
```

Most of this code is executed in a library targeting .NET 451, NETSTANDARD1_3 and NETSTANDARD2_0. It has no knowledge of MySQL or any other specific provider, just a few configurable commands and SQL queries. So it is important for me to use the DbContext object which is previously configured in the main process.

The problem I have is simple, when I ask for a connection in:

`var connection = dbContext.Database.GetDbConnection();`

I expect to receive a DbConnection object, not a exception or a mandatory connected DbConnection. It is ok for me if you try to open the DbConnection first, but in case it fails please still give me the DbConnection instance instead of an exception.

**Comment by caleblloyd** [comment]
Closing issue due to age

**Comment by YandyZaldivar** [comment]
This issue was already fixed, I just forget to close this.
