### ISSUE TITLE
How using HiLo to generate keys with Pomelo.EntityFrameworkCore.MySql?

### ISSUE THREAD

**Issue by glazkovalex** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#477]
In microsoft.entityframeworkcore.sqlserver has ForSqlServerUseSequenceHiLo extend method that allows you to use HiLo to generate keys with Entity Framework Core. How using HiLo to generate keys with Pomelo.EntityFrameworkCore.MySql?

MySQL version: 5.7.9
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

**Comment by mguinness** [comment]
Sequences aren't available in MySQL, although [MariaDB](https://mariadb.com/kb/en/library/create-sequence/) is working to add them.

**Comment by glazkovalex** [comment]
Yes, Sequences aren't available in MySQL, but I did not write about support Sequences, but about support for the implementation of the HiLo algorithm. For example, [this nuget package](https://github.com/fabiogouw/NHilo) of the HiLo algorithm is supported on MySql without sequences.
However, I accept your answer: I don't know how using HiLo to generate keys with Pomelo.EntityFrameworkCore.MySql. Thanks for the reply.

**Comment by mguinness** [comment]
Yes, but sequences are how HiLo is implemented in both SQL Server and Postgres providers.  Could you not create your own high-low key table and use the [DatabaseGenerated](http://www.learnentityframeworkcore.com/configuration/data-annotation-attributes/databasegenerated-attribute) attribute?

**Comment by glazkovalex** [comment]
No, because this functionality is already implemented in the wonderful library [NHilo](https://github.com/fabiogouw/NHilo). For each data table created an additional table with Hi keys https://github.com/fabiogouw/NHilo/blob/master/src/NHiLo/HiLo/Repository/MySqlHiLoRepository.cs. Based on which clients generate unique HiLo keys https://github.com/fabiogouw/NHilo/blob/master/src/NHiLo/HiLo/HiLoGenerator.cs.
