### ISSUE TITLE
Query with filters to Json column

### ISSUE THREAD

**Issue by LiangZugeng** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#479]
### Steps to reproduce
It's not actually a bug or an issue, it's rather a question.

### The issue
There is a property of JsonObject type in the entity, when querying the entity with Where clause to match value in Json object, the query didn't get evaluated in MySQL server, it was evaluated locally, thus the performance is quite bad. My question is how I can construct the query for having the filter to be evaluated in MySQL.

```
    public class SalesOrder
    {
        public int Id { get; set; }
        public JsonObject<MaterialSpec> Specs { get; set; }
    }

    public class MaterialSpec
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    }
```

```
var orders = DbContext.SalesOrders.Where(so => so.Specs.Object.CategoryId == 1);
```

### Further technical details
MySQL version: 5.7.20
Operating system: Windows 10 Enterprise
Pomelo.EntityFrameworkCore.MySql version: 2.0.0

**Comment by yukozh** [comment]
We already discussed eval the json query. The anser is no. Althogh you can query json field with SQL , The perf is also bad.
