### ISSUE TITLE
Change the namespace of JsonObject

### ISSUE THREAD

**Issue by HB-2012** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#480]
Currently, the JsonObject class is part of the "System" namespace. When you look into the class using for example the Object Explorer, you can tell that this object is part of the Pomelo assemblies. Other than that, it looks like the object is part of .NET Core. Using the "System" namespace is bad practice imho, a different namespace that clearly identifies the object as a standalone addition would be preferred.

**Comment by caleblloyd** [comment]
That is a good point, but moving it would break backwards compatibility for consumers. The breaking change is just not worth it in this case.

**Comment by HB-2012** [comment]
I don't agree that the change is not worth it. Changing the namespace can be done without immediately breaking everything by using the [ObsoleteAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute?view=netcore-2.0).

The only downside I could think of is having to maintain both versions of the object while the deprecation notice is in effect, but that's only temporarily.
