### ISSUE TITLE
Can updates on JsonObject properties be done without materializing the entity?

### ISSUE THREAD

**Issue by AlphaGit** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#481]
Hi! I have a MySql database that is using the Pomelo EF MySql driver -- so far everything has been great.

I'm at a point where I need to perform update on a property of a JSON field, without explicitly materializing the entity.

In EF I would do this in an approach similar to this:

```csharp
var theClass = new MyClass()
{
    Id = 6,
    MyField = "new updated value"
};

var entity = dbContext.Attach(theClass);
entity.Property("MyField").IsModified = true;
context.SaveChanges();
```

This would make EF run a single update statement for that particular field with the new particular value. Something like `UPDATE MyClassTable SET MyField = 'new updated value' WHERE ID = 6`.

Is there any similar thing I can do with JSON objects? I want to update a particular property inside of a JSON object, but I found no documentation or reference to do that. Is is possible?

Thank you!

### Further technical details

MySQL version: 5.7.10
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

**Comment by caleblloyd** [comment]
It looks like partial updates on JSON fields are not supported until MySQL 8.0:

https://dev.mysql.com/doc/refman/8.0/en/json.html

You'd have to write SQL using something like [ExecuteSQLCommand](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced#call-an-update-query) to do the update; there is nothing built in to JsonObject that will do a partial update

**Comment by AlphaGit** [comment]
Hi @caleblloyd, thanks for the answer. However, aren't those instructions currently covered already in MySQL 5.7? I'm using `JSON_SET` which is available in it:

https://dev.mysql.com/doc/refman/5.7/en/json.html

It might internally be a full row replacement, but for most practical uses of consumers, it behaves as if it was a partial update, doesn't it?

For reference, this is the query I'm currently using:

```
UPDATE MyClassTable SET MyField = JSON_SET(MyField, '$."someProperty"', 'some value')
```

**Comment by caleblloyd** [comment]
Ah yes, `JSON_SET` is in 5.7: https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html#function_json-set

Building your own query to run `JSON_SET` is the right way to run an update without materializing the entity.  It is not currently supported by [Pomelo.JsonObject](https://github.com/PomeloFoundation/Pomelo.JsonObject)
