### ISSUE TITLE
MySql.Data.EntityFrameworkCore vs Pomelo.EntityFrameworkCore.MySql

### ISSUE THREAD

**Issue by SharmaHarsh7** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#484]
This is not an issue but a question??

Which database connector should I use in .Net Core 2 enterprise level web app which is going to handle large amount of data.

I have two choices:

    Pomelo.EntityFrameworkCore.MySql
    MySql.Data.EntityFrameworkCore

But still confuse which one to choose for the development.

I started with MySql.Data.EntityFrameworkCore, which is MySQL official provider but after facing several issues while code first migration I had to google again for some better alternative.

After some research I found Pomelo.EntityFrameworkCore.MySql bit more helpful for my application and it also covered the issues I was facing before.

But it still left me a bit confuse about which one to choose for long term.

Pomelo is workign fine currently but I am not sure if they (pomelo team) will keep always keep it updating and will keep it in sync with the latest .Net Core version available in the market??

MySql is not working as expected but the only plus point with this is : It is provided by MySQl itself.

Please help me to decide

**Comment by caleblloyd** [comment]
This was discussed a while back in #112 

Oracle's provider has never really worked.  That being said, they are a company and you could pay them for support.

This library is fully open source.  We try to stay up-to-date and performant.  That being said, we are all individual maintainers and do this in our free time. The nice thing is you can always jump in and contribute, too!

**Comment by SharmaHarsh7** [comment]
Thanks @caleblloyd for your instant response and yes this provider 🥇  is way more better than oracle.

I would definitely love to be a part of your team and would like to contribute once I am done with my current project   👍

**Comment by mason-chase** [comment]
I'm getting whole a lot  of errors that Pamelo doesn't support `boolean` or `enum`,  how can I help to support this?

**Comment by mguinness** [comment]
@mason-chase Try [StackOverflow](https://stackoverflow.com/questions/tagged/entity-framework-core) for peer support.

**Comment by mason-chase** [comment]
I was asking how can I help **Pomelo** support the `boolean` and `enum` and not to seek to receive help.

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/522 for discussion regarding contributing.
