### ISSUE TITLE
Connect Timeout expired

### ISSUE THREAD

**Issue by squalsoft** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#485]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.
Execute many selects from web application.
### The issue
Describe what is not working as expected.
We have a lot of connections to out webserver. Everything works very well. We have a enough free hardware resources. But sometimes all queries from web app somehow freezes to execute, connections count increases to max value (EF config)) and timeouts starts happen. When this happens we can connect to database from Mysql Workbench (for example) and execute any query very fast. 
Db: InnoDb.
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```
Error: MySql.Data.MySqlClient.MySqlException (0x80004005): Connect Timeout expired. ---> System.OperationCanceledException: The operation was canceled. at System.Threading.CancellationToken.ThrowOperationCanceledException() at System.Threading.SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__32.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__0.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 30 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__77.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 355 at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__77.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 370 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__19.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 160 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 137 at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected) at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer) at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult) at lambda_method(Closure , QueryContext ) at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc) at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate) at GuardPortal.Domain.Services.ApiSecurityService.CheckChopAccess(String key, String progId) in C:\TeamCity\buildAgent\work\GuardPortal\src\GuardPortal.Domain\Services\ApiSecurityService.cs:line 84 at GuardPortal.Domain.Services.ApiSecurityService.CheckAccessByFingerprint(String key, ProgrKindEnum programKind, String progId) in C:\TeamCity\buildAgent\work\GuardPortal\src\GuardPortal.Domain\Services\ApiSecurityService.cs:line 61 at GuardPortal.Web.Infrastructure.Middleware.AuthenticationMiddleware.<Invoke>d__2.MoveNext() in C:\TeamCity\buildAgent\work\GuardPortal\src\GuardPortal.Web\Infrastructure\Middleware\AuthenticationMiddleware.cs:line 42 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()

### Further technical details
Logs from .net
 Request starting HTTP/1.1 GET http://oxr-info.ru/api/Chop/GetUnreadedNotificationsByNum?chopNum=1227
Feb 09 09:56:59 web portal[11627]: info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
Feb 09 09:56:59 web portal[11627]:       Entity Framework Core 2.0.1-rtm-125 initialized 'ApplicationDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: SensitiveDataLoggingEnabled MigrationsAssembly=GuardPortal.DataAccess
Feb 09 09:56:59 web portal[11627]: info: Microsoft.EntityFrameworkCore.Database.Command[20101]
Feb 09 09:56:59 web portal[11627]:       Executed DbCommand (4ms) [Parameters=[@__key_0='2437-51A7-83CD-F798-E44D-433B-8A6A-2055' (Size = 60) (DbType = AnsiString), @__chopNum_1='1279'], CommandType='Text', CommandTimeout='80']
Feb 09 09:56:59 web portal[11627]:       SELECT CASE
Feb 09 09:56:59 web portal[11627]:           WHEN EXISTS (
Feb 09 09:56:59 web portal[11627]:               SELECT 1
Feb 09 09:56:59 web portal[11627]:               FROM `ChopMachines` AS `s`
Feb 09 09:56:59 web portal[11627]:               INNER JOIN `Chops` AS `s.Chop` ON `s`.`ChopId` = `s.Chop`.`ChopId`
Feb 09 09:56:59 web portal[11627]:               WHERE (`s`.`Fingerprint` = @__key_0) AND (`s.Chop`.`ChopNum` = @__chopNum_1))
Feb 09 09:56:59 web portal[11627]:           THEN TRUE ELSE FALSE
Feb 09 09:56:59 web portal[11627]:       END
Feb 09 09:56:59 web portal[11627]: info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
Feb 09 09:56:59 web portal[11627]:       Authorization was successful for user: (null).
Feb 09 09:56:59 web portal[11627]: info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Feb 09 09:56:59 web portal[11627]:       Executing action method TodoApi.ChopController.GetUnreadedNotificationsByNum (GuardPortal.Web) with arguments (1279) - ModelState is Valid
Feb 09 09:56:59 web portal[11627]: fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
Feb 09 09:56:59 web portal[11627]:       An exception was thrown attempting to execute the error handler.
Feb 09 09:56:59 web portal[11627]: MySql.Data.MySqlClient.MySqlException (0x80004005): Connect Timeout expired. ---> System.OperationCanceledException: The operation was canceled.

MySQL version: 
5.7.20-0ubuntu0.16.04.1
Operating system: 
Ubuntu 16.04
Pomelo.EntityFrameworkCore.MySql version:
2.0.1

Other details about my project setup:

**Comment by caleblloyd** [comment]
This does not appear to be a problem with this library

It sounds like your queries are taking too long and timing out. You may need to optimize your database by adding indexes.

If you're working in a high concurrency environment also be sure that all of your query methods use `async`

If you find the root cause and it ends up being related to this library please post and we can investigate further
