### ISSUE TITLE
How to connect MySql DB in Amazon EC2 servers using SSL Key

### ISSUE THREAD

**Issue by Ahmed-Raouf** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#489]
Hello,

I develop an asp mvc core 2 application connection on Mariadb on Amazon EC2 server. 
To connect to the database I should provide ssl key file "key-file.pem". I tried the following connection string:

"server=xx.xx.xx ;userid=xxx;pwd=xxxx;database=xxx;sslmode=preferred;certificatefile=LinuxFreeServer.pem"

But I can't connect to the database. Can any one help me?

**Comment by mguinness** [comment]
You'll need to create an issue in the [underlying library](https://github.com/mysql-net/MySqlConnector).  Have you tried converting from PEM to PFX format? See https://dev.mysql.com/doc/connector-net/en/connector-net-tutorials-ssl.html.

**Comment by caleblloyd** [comment]
This is not a bug; it is a usage based question.  Please look on https://mysql-net.github.io/MySqlConnector/connection-options/ for connection string options

If the server supports SSL you can use it simply by setting `SslMode=Required`

If you want to use Mutual Authentication you need to bundle your Certificate and Private Key into a `.pfx` using `openssl pkcs12 -in cert.pem -inkey key.pem -export -out bundle.pfx` and use that as the `CertificateFile=bundle.pfx`

If you want to verify the Server you should use a `ca.pem` and do `SslMode=VerifyCA` and `CACertificateFile=ca.pem`
