### ISSUE TITLE
How to connect MySql DB in Amazon EC2 Ubuntu server over SSH

### ISSUE THREAD

**Issue by Ahmed-Raouf** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#491]
Hi,

I have a MariaDB on EC2 Amazon server. Using Putty, I generated a private key file using the key.pem file and the credentials of the Amazon Linux server.

I connected successfully to the database through the workbench as connection Method: **Standard TCP/IP over SSH** providing the server name, user name, password and the private key file path.

I want to connect the database from an ASP MVC Core 2 application using the same credentials if possible.

How can I create the connection string to provide the previous credential with the private key?

**Comment by Ahmed-Raouf** [comment]
This is the configuration in Startup.cs file:

services.AddDbContext<AppIdentityDbContext>(options =>
                options.UseMySql(Configuration["ApplicationSettings:MyProjectContext"])               
                
                );

I try to provide the follwoing connection string:
"MyProjectContext": "server=........;userid=......;pwd=......;database=myproject;"

I don't know how to provide the private key file. As I did in workbench.

**Comment by mguinness** [comment]
Why are you opening another issue?  I believe the information provided in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/489 has the details you're looking for.

**Comment by Ahmed-Raouf** [comment]
I know that your answer in the previous issue is right according to my question about SSL. But I confused between SSL certificate and SSH. 
In my case I don't have SSL certificate on MySQL. But I connect to the Linux server which contains my database over SSH providing the private key file ".ppk" which I created by Putty application giving the ".pem" server file.
So, I think that there is a difference between SSL and SSH when connecting from the client application to the database. This is the reason that I opened another issue.   

In workbench there are two configuration tabs, one for SSL and another for SSH parameters. I used the tab for SSH, entered my credentials and connected successfully.

**Comment by caleblloyd** [comment]
Please do not ask usage questions here.  This GitHub issue tracker is for bug reports.  StackOverflow is a good site to ask usage questions on.

**Comment by Ahmed-Raouf** [comment]
Sorry, thanks for your support.

**Comment by mguinness** [comment]
@Ahmed-Raouf Sorry I misundersood your issue.  Sounds like you will need to use [PuTTY](http://realprogrammers.com/how_to/set_up_an_ssh_tunnel_with_putty.html) if using Windows.  If you want to do it programatically then you'll need to use [SSH.NET](https://stackoverflow.com/questions/32603982/connection-to-mysql-from-net-using-ssh-net-library).  Good luck and if you get stuck try StackOverflow for further help.

**Comment by Ahmed-Raouf** [comment]
Thanks @mguinness. I solved my problem using the following command to start ssh tunnel:
**ssh -L local_port:database_host:remote_database_port username@database_host** 
Then I written my connection string normally with sslmode=none.

**Comment by nicotp80** [comment]
Hi Ahmed, i've a similar problem, MariaDB with SSH Tunnel, and i have an error when i use scaffold command. How you settings your connection string? This is what i try : dotnet ef dbcontext scaffold "Server=XXXXXX;Database=MyDB;User=xxxxx;Password=xxxxxxx;TreatTinyAsBoolean=true;" "Pomelo.EntityFrameworkCore.MySql", but it's not working, i use the ip address for the server, and correct user and psw for DB (same with workbrench).

**Comment by lauxjpn** [comment]
@nicotp80 It looks like this feature was recently added for Oracle's Connector/NET, but has not been implemented in MySqlConnector yet (the underlying library Pomelo is using).

See [5.3 Connecting With TCP/IP Over SSH](https://dev.mysql.com/doc/connector-net/en/connector-net-ssh-tunneling.html) for further information.

Talk to @bgrainger to see if there are any plans of integrating SSH support in MySqlConnector.

Of course you can always manually open an SSH tunnel and then just connect trough it to the database server as you would normally do (e.g. be forwarding a port).

Google will provide you with many tutorials how to do this. Here are some random ones for Putty:
- https://www.linode.com/docs/databases/mysql/create-an-ssh-tunnel-for-mysql-remote-access/
- https://hostpresto.com/community/tutorials/how-to-connect-to-a-remote-mysql-server-via-an-ssh-tunnel/
- https://blog.devolutions.net/2017/4/how-to-configure-an-ssh-tunnel-on-putty

**Comment by bgrainger** [comment]
The issue for adding SSH tunnels to MySqlConnector is https://github.com/mysql-net/MySqlConnector/issues/671

For now, we recommend following these instructions in our documentation to set up an SSH tunnel for MySQL: https://mysqlconnector.net/tutorials/connect-ssh/
