### ISSUE TITLE
MySQL column type "date" not being mapped

### ISSUE THREAD

**Issue by JaredAtAdevsco** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#499]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

### The issue
Running `Scaffold-DbContext -Connection "[connection string]" -Provider "Pomelo.EntityFrameworkCore.MySql" -OutputDir "Models\Cms" -Context "CmsContext"` causes any mysql column of the `date` type to not get mapped.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: Could not find type mapping for column 'tblname.colname' with data type 'date'. Skipping column.
Stack trace:
```

### Further technical details

MySQL version: 
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

Other details about my project setup:
Could the MySQL date type not be mapped to a C# DateTime object? If you can clue me in to where these mappings are I don't mind trying to help on this issue.

**Comment by mguinness** [comment]
Use datetime or see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/152#issuecomment-304673188.
