### ISSUE TITLE
DropPrimaryKeyOperation Stored Procedure not working

### ISSUE THREAD

**Issue by neville-nazerane** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#504]
### Steps to reproduce
Run a migration that would generated one of the stored procedures and run the scripts on the database. 

### The issue
the generated stored procedures crash when running on the database. I have noticed that resetting the delimiter temporary resolves the issue. Please check the commit there: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/492/commits

### Further technical details

MySQL version: 5.7
Operating system: Ubuntu 17.10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

**Comment by neville-nazerane** [comment]
it isn't just `DropPrimaryKeyOperation`. I had seen one more stored procedure with a similar issue.

**Comment by caleblloyd** [comment]
Please try upgrading to 2.1.1 and open a new issue if the problem persists
