### ISSUE TITLE
OnDelete(DeleteBehavior.Restrict) gives "NO ACTION" in mysql

### ISSUE THREAD

**Issue by LordMike** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#506]
### Steps to reproduce
1 Create a model with a relation between two entities.
2 Set relation to `OnDelete(Restrict)` 

### The issue
Code like this, in OnModelCreating, should create "ON DELETE RESTRICT" in MySQL - but it doesn't.
```csharp
            modelBuilder.Entity<ApplicationUser>()
                .HasOne(s => s.Organization)
                .WithMany(s => s.Users)
                .IsRequired()
                .OnDelete(DeleteBehavior.Restrict);
```

The Migration created from this is:

```csharp
            migrationBuilder.AddForeignKey(
                name: "FK_AspNetUsers_Organizations_OrganizationId",
                table: "AspNetUsers",
                column: "OrganizationId",
                principalTable: "Organizations",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
```

The SQL generated by the above is:
```mysql
ALTER TABLE `AspNetUsers` 
ADD CONSTRAINT `FK_AspNetUsers_Organizations_OrganizationId` 
FOREIGN KEY (`OrganizationId`) 
REFERENCES `Organizations` (`Id`) 
ON DELETE NO ACTION;
```

Shouldn't it be `ON DELETE RESTRICT` ?

I've found this code that seems to be the culprit.
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/fc29dba2a0230a63f3f54116ff1b35a02b42dd56/src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs#L740-L743

### Further technical details

MySQL version: 5.7.20
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

**Comment by mguinness** [comment]
Also noted in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/432.  Can you create a PR?

**Comment by doudouesig** [comment]
Hello,
I used the last version 2.1.1 and I always have this issue :( 
It's the same in another project with the version 2.0.1
