### ISSUE TITLE
MySql doesn't support sequence operation

### ISSUE THREAD

**Issue by kunit1** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#509]
### Steps to reproduce
In Migration Up
```
migrationBuilder.CreateSequence<int>(
                name: "QuoteNumbers",
                schema: "shared",
                startValue: 1000L);

migrationBuilder.AlterColumn<int>(
                name: "QuoteNumber",
                table: "QuoteRequest",
                nullable: false,
                defaultValueSql: "NEXT VALUE FOR shared.QuoteNumbers",
                oldClrType: typeof(string),
                oldNullable: true);
```

In Context OnModelCreating(ModelBuilder modelBuilder)
```
 modelBuilder.HasSequence<int>("QuoteNumbers", schema: "shared")
                .StartsAt(1000)
                .IncrementsBy(1);

            modelBuilder.Entity<QuoteRequest>()
                .Property(q => q.QuoteNumber)
                .HasDefaultValueSql("NEXT VALUE FOR shared.QuoteNumbers");
```

### The issue
After adding the above code to auto increment a column value using sql sequences. When updating the database with the migration it throws an exception in Method CreateSequenceOperation
"MySql doesn't support sequence operation"

Looking at the source code it seems like Pomelo MySql provider doesn't support sql sequences?

### Further technical details

MySQL version: 5.7
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

Other details about my project setup: EF Core 2.0.1

**Comment by mguinness** [comment]
Sequences aren't available in MySQL, although [MariaDB](https://mariadb.com/kb/en/library/create-sequence/) is working to add them.

**Comment by lawrencefej** [comment]
MariaDB has added Sequence, do you plan to add support for this feature anytime soon?

**Comment by mguinness** [comment]
Not at this time, but we welcome user contributions.
