### ISSUE TITLE
Nullable foreign key sometimes is not returned

### ISSUE THREAD

**Issue by dgencheva** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#513]
I am working on an application where I am using  .Net Core 1.1, EF Core and MySQL as database server via Database First approach.
I have a table that has a nullable foreign key. When I query the table although the value of this field is not null for this record, it doesn't get the real value and just returns NULL.
If I stop the project and run it again, the value is returned the first time.

The code is pretty simple:
the property is: `public long? DefaultWorkflowId { get; set; }`
the mapping is:
```
entity.HasOne(d => d.Workflow)
                    .WithMany(p => p.ExternalAccount)
                    .HasForeignKey(d => d.DefaultWorkflowId)
                    .HasConstraintName("FK_ExternalAccount_Workflow")
                    .IsRequired(false);
```
and the query is:
`var account = DbContext.ExternalAccount.FirstOrDefault(o => o.Id == externalAccountId);`

MySQL version: 5.7.17
Operating system: happening on both Windows and Linux
Pomelo.EntityFrameworkCore.MySql version: 1.1.2

**Comment by caleblloyd** [comment]
We don't have a LTS plan and 1.x will not be receiving any updates.

Please upgrade to the latest stable version (2.0.1 at the time of this writing) and see if that fixes your problem.  If the problem persists under the latest stable version, please open a new issue.  Thanks,
