### ISSUE TITLE
semicolon missing in certain alter when scripting database

### ISSUE THREAD

**Issue by neville-nazerane** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#516]
### Steps to reproduce
- Change an int property
- Script migration 

### The issue
Here is the exact line that the semicolon was missing in:

ALTER TABLE `ProjectReview` CHANGE `UserID` `CreatedByID` int(11) NOT NULL

**Comment by caleblloyd** [comment]
PleasPlease try upgrading to 2.1.1 and open a new issue if the problem persists
