### ISSUE TITLE
How do I update to version 2.1.0-preview1

### ISSUE THREAD

**Issue by JanBN** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#517]
Hello,

how do I update to this version 2.1.0-preview1. I can not find any help on this. This is my csproj:
```
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" PrivateAssets="All" />
		<PackageReference Include="NSwag.AspNetCore" Version="11.14.1" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.1.0-preview1-*" />
	</ItemGroup>
```

this is the error:
```
[fail]: OmniSharp.MSBuild.ProjectLoader
        Unable to find package Pomelo.EntityFrameworkCore.MySql with version (>= 2.1.0-preview1)
  - Found 110 version(s) in nuget.org [ Nearest version: 2.0.1 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
```

I have also added NuGet.config file to the root for nightly builds as stated here: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/README.md

Thank you

**Comment by caleblloyd** [comment]
The library is not yet ready.  Track #514 for development progress

**Comment by JanBN** [comment]
Oh thank you. 
I thought its out from yesterday according to schedule https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#schedule-and-roadmap
