### ISSUE TITLE
Unique constraint on combination of multiple columns of a table

### ISSUE THREAD

**Issue by SharmaHarsh7** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#519]
Hi,

I am trying to implement a scenerio using this ORM where I have different tenants of my application using the same mysql database.

In my user table all the tenants have their list of users as following:

```
class User
{
    public int UserID {get; set;}
    public string UserName {get; set;}
    public int TenantID {get; set;}

}
```

> Multiple  tenants can have same UserNames registered to access there system.

I want to know how can I implement the Composit Unique key on columns UserName + TenantID in its mapper class.

I searched it on google and tryied it many times but no luck.

Please help.

Thanks,
Harsh

**Comment by caleblloyd** [comment]
https://docs.microsoft.com/en-us/ef/core/modeling/keys

**Comment by caleblloyd** [comment]
Please use StackOverflow for questions where you are asking for help on how to use EF. GitHub is for bug reports.
