### ISSUE TITLE
Upgrade from 1.1.2 to 2.0.1 clobbering auto_increment columns

### ISSUE THREAD

**Issue by ABCRic** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#520]
### Steps to reproduce

1. Create a migration for an entity with a [Key] property using Pomelo.EntityFrameworkCore.MySql version 1.1.2 and EF Core version 1.1.2
2. Upgrade both EF Core and Pomelo.EntityFrameworkCore.MySql to 2.0.1
3. Create new migration without changing the code

### The issue
Step generation should generate an empty migration but instead generates something like the following:
```
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "idCol",
                table: "t",
                nullable: false,
                oldClrType: typeof(int))
                .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "idCol",
                table: "t",
                nullable: false,
                oldClrType: typeof(int))
                .OldAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
        }
```
Which translates to a script containing the following:
```
ALTER TABLE `t` MODIFY COLUMN `idCol` int NOT NULL;
ALTER TABLE `t` ALTER COLUMN `idCol` DROP DEFAULT;
```
Thus destroying the `AUTO_INCREMENT` that the columns had when they were created.

Note that adding a new entity while still in 2.0.1 with a property marked [Key] does correctly generate a column with AUTO_INCREMENT.

### Further technical details

MySQL version: 5.7.17-log
Operating system: Windows 10 1709
Pomelo.EntityFrameworkCore.MySql version: 1.1.2/2.0.1

Other details about my project setup: not relevant

**Comment by ABCRic** [comment]
As an addendum, this also causes the issue described in #423 when attempting to actually apply the migration, but applying the workaround and letting the migration run leaves the columns with no default value and no auto_increment flag so attempting to add new rows causes errors.
Seems related to #362 but that was closed by a PR from 7 months ago and this is happening in the current NuGet version which is 4 months old.

**Comment by caleblloyd** [comment]
Please try upgrading to 2.1.1 and open a new issue if the problem persists

**Comment by ABCRic** [comment]
It's fixed. Thank you.
