### ISSUE TITLE
EF Core Database First MySQL 

### ISSUE THREAD

**Issue by Ciwan1859** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#521]
Hello

I have a MySQL database, and I want to use EF Core on it, DB First method. I couldn't find any documentation. Is this supported by `Pomelo.EntityFrameworkCore.MySql`?

I followed the [instructions here](https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core-scaffold-example.html#connector-net-entityframework-core-scaffold-packagemgr), but instead of `MySql.Data.EntityFrameworkCore.Design` I used `Pomelo.EntityFrameworkCore.MySql`, and when I ran the command:

`Scaffold-DbContext "mysql-connection-string" Pomelo.EntityFrameworkCore.MySql -OutputDir Models -f`

I got the following:

![screenshot](https://content.screencast.com/users/JKhalaf/folders/Snagit/media/4ab95c7e-3192-469f-88a6-7293f59715f3/2018-03-27_09-19-07.jpg)

And here's a screenshot of my solution showing nuget packages:

![screenshot of solution](https://content.screencast.com/users/JKhalaf/folders/Snagit/media/15f1b5c9-0e47-4863-ad70-7736be47bc39/03.27.2018-09.25.png)

Any help would be greatly appreciated

**Comment by yukozh** [comment]
See #121

**Comment by Ciwan1859** [comment]
Thanks @yukozh, I hadn't noticed #121 , but when I tried running the command, I get:

> No executable found matching command "dotnet-ef"

Not sure why this is happening, I have the following packages:

```<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.0.1" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.2" />
  </ItemGroup>
</Project>
```
And I am in the `.csproj` directory when I run that command, and here is the output of `dotnet --info`:

```.NET Command Line Tools (2.1.200-preview-007474)

Product Information:
 Version:            2.1.200-preview-007474
 Commit SHA-1 hash:  06ce7628d3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200-preview-007474\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d```

**Comment by mguinness** [comment]
Looks like you're missing the following.  If this doesn't work, please direct any further questions to [SO](https://stackoverflow.com/questions/tagged/entity-framework-core).

`<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />`
