### ISSUE TITLE
Inform EntityFrameworkCore Migrations about MySql version?

### ISSUE THREAD

**Issue by bravo-kernel** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#523]
Apologies if this is the wrong repository to ask.

Is it possible to inform EntityFrameworkCore Migrations about my MySQL version being `>=5.6` so it will generate migration files using `"CURRENT_TIMESTAMP(6)"` instead of `"CURRENT_TIMESTAMP"`.

I now manually fix my migration files [using this instruction by @yukozh](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/171#issuecomment-270353088) but it would be nice if this could be automated.

**Comment by mguinness** [comment]
PR's are accepted.  You would need to modify [MySqlMigrationsSqlGenerator](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Migrations/MySqlMigrationsSqlGenerator.cs#L392) class and use [ServerVersion](
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Storage/Internal/ServerVersion.cs#L32) to achieve what you need.

**Comment by bravo-kernel** [comment]
@mguinness thanks, this is my first journey into MS country so a PR might be one step too far right now but I will put this on my list. Much obliged 👍
