### ISSUE TITLE
Code First creates table with lower case letters

### ISSUE THREAD

**Issue by pantonis** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#526]
### The issue
When working with latest version of the Pomelo.MySql and code first, tables are create with lower case letters. eg. instead of ```ClientInvoice``` table is create as ```clientinvoice```

MySQL version:  5.7 
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

Other details about my project setup:

**Comment by yukozh** [comment]
It's related to your my.ini, not a bug in EF layer.

**Comment by pantonis** [comment]
thanks a lot guys
