### ISSUE TITLE
AutoEF: new project to create Code Generation layer for EF Core providers

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#527]
I would like to announce a new project I am starting to and ask the Pomelo community for feedback.

AutoEF is a proposal to improve the provider experience by introducing a Code Generation layer to translate a Microsoft developed provider into a base implementation for third-party providers. The primary goal is for the code generation layer to do the heavy lifting when a provider updates to a new major, minor, or patch version of Entity Framework Core Upstream.

For detailed information please read and comment on the [AutoEF Abstract](https://github.com/AutoEF/CodeGen/issues/1)

cc @yukozh @mguinness @bgrainger please add anyone else in the community that you may think may be interested as well!

_Update 4/21/18: Project renamed from OpenEF to AutoEF_

**Comment by mguinness** [comment]
I think both @roji who manages the Npgsql provider and @ErikEJ the SQLCE provider would be well placed to discuss the merits on the use of code gen.  This could fill a gap where external provider developers are working blind somewhat on core changes.

**Comment by yukozh** [comment]
I agree
