### ISSUE TITLE
1.0.1 can't connect database with no password

### ISSUE THREAD

**Issue by SquallATF** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#53]
My connection string is `server=127.0.0.1;database=mydb;uid=root;pwd=;`
1.0.0 can work, but 1.0.1throw exception `MySqlException: Access denied for user 'root'@'localhost' (using password: YES)`

**Comment by bgrainger** [comment]
Fixed at bgrainger/MySqlConnector#53

This library will need to update to 0.1.0-alpha20.

**Comment by bgrainger** [comment]
@Kagamine Not sure if there's anything else to do here other than rebuild the package with the latest dependencies and republish it?

**Comment by Kagamine** [comment]
Fixed in https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.0.1-prerelease-10003

**Comment by SquallATF** [comment]
I have updated the package to latest version but still have issue

**Comment by bgrainger** [comment]
What version of MySQL Server and OS are you using?

**Comment by SquallATF** [comment]
MariaDB 10.1.17 with Windows 10 Anniversary Update

**Comment by bgrainger** [comment]
I've reopened bgrainger/MySqlConnector#53 for additional investigation with that server.

**Comment by bgrainger** [comment]
There was a bug with reauthentication with MariaDB, which is fixed in [MySqlConnector 0.1.0-alpha22](https://www.nuget.org/packages/MySqlConnector/0.1.0-alpha22).

**Comment by Kagamine** [comment]
Fixed in prerelease 10004
