### ISSUE TITLE
How to set charset my database and all columns to utf8mb4

### ISSUE THREAD

**Issue by majid23** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#530]
I want change **_charset_** of my database and table columns to `utf8mb4`.
How can i set this config when database will be create until my database and all columns in `string` type became `utf8mb4` with collation `utf8mb4_unicode_ci`?

**Comment by mguinness** [comment]
See issue https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/84 for details regarding charset.
