### ISSUE TITLE
PomeloEF is using a setter to set a value, when it should write to a field.

### ISSUE THREAD

**Issue by CheloXL** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#537]
### Steps to reproduce
I'm just notifying you about this issue, as per comment in the thread below, there might be a bug in Pomelo.Ef.

See [In-Memory DB not setting Id property](https://github.com/aspnet/EntityFrameworkCore/issues/11934)

### Further technical details
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

**Comment by mguinness** [comment]
PR's are welcome and appreciated.

**Comment by caleblloyd** [comment]
Please try upgrading to 2.1.1 and open a new issue if the problem persists
