### ISSUE TITLE
Access denied to remote sql server

### ISSUE THREAD

**Issue by DavidTangWei** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#543]
I can use mysql workbench to connect remote mysql server. But it will throw an exception by using **Pomelo.EntityFrameworkCore.Mysql**.

### From workbench 
![image](https://user-images.githubusercontent.com/14040884/40190694-1b3020dc-5a32-11e8-8a0b-830f47fe5203.png)

### From Pomelo
```json
 "ConnectionStrings": {
    "OnTheWayDatabase": "Server=47.98.165.43;Database=ontheway;Uid=king;pwd={other}"
  },
```

And it will throw an exception
![image](https://user-images.githubusercontent.com/14040884/40190898-90bd0efa-5a32-11e8-8600-bb2e6025678f.png)

MySQL version:  5.7.22
Server system: ubuntu16
Operating system:  win10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

My project has been stuck at this step. Hope for your help. Thank you!

**Comment by caleblloyd** [comment]
Probably a firewall or MySQL user configuration problem, not a bug in this library.

**Comment by DavidTangWei** [comment]
Thank you for your reply. It is my mistake. I allow the  'king' user to operate the only database called on_the_way.
But the database in my connectstring is ontheway. so mysql server response Error 1044. I use wireshark to capture the tcp packets. 
![image](https://user-images.githubusercontent.com/14040884/40192834-16108172-5a38-11e8-9d8f-dcee64c38d6e.png)
