### ISSUE TITLE
The object obtained through the foreign key is null

### ISSUE THREAD

**Issue by axel10** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#547]
MySQL version: 5.7.14
Operating system: Win10 17134.48
Pomelo.EntityFrameworkCore.MySql version:2.0.1

I have two tables product and product_standard,the product_standard.product_id column foreign key of Table 1 is associated with the id column of product

![image](https://user-images.githubusercontent.com/25299157/40335794-38cad934-5d98-11e8-8160-82b2baeaed5c.png)

i use the commond
`dotnet ef dbcontext scaffold  "Server=localhost;User Id=root;Password=123;Database=e3mall" "Pomelo.EntityFrameworkCore.MySql" -f`

After running the program, find the object obtained by foreign key is null
![image](https://user-images.githubusercontent.com/25299157/40335931-f461cd38-5d98-11e8-97cd-c652b39b896b.png)

Also found this exception
![image](https://user-images.githubusercontent.com/25299157/40335924-e644cdf4-5d98-11e8-9e47-a57ca6d26d18.png)

**Comment by VictorHaine** [comment]
I think that the problem for the first SS is the laking of ".Include(ps=>ps.Product)"

**Comment by johnfg10** [comment]
I had the same issue and what @VictorHaine suggested fixed it!
