### ISSUE TITLE
Is database scaffolding supported yet? 

### ISSUE THREAD

**Issue by TsengSR** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#55]
I didn't find any information if and how much of the scaffolding (DB to models) is supported or working as of now. 

For a customer I need to scaffold from an existing database, and the official MySQL driver do not seem to support it (neither does it support database updates).

**Comment by Kagamine** [comment]
Entity Framework Core does not support DB First, please open an issue in aspnet/EntityFramework

**Comment by TsengSR** [comment]
Not asking for database first, I am talking about scaffolding Database to models. You usually do this once, to generate the model and the go on with code-first and migrations. 

And EF Code **does** support it, see the docs: https://docs.efproject.net/en/latest/miscellaneous/cli/dotnet.html#dotnet-ef-dbcontext-scaffold.

It doesn't support Model-First (*.edmx files).

**Comment by Kagamine** [comment]
We have supported scaffold, and will ship in 1.1.0-rtm-10003.
