### ISSUE TITLE
Query test/product issues for in 2.1 branch

### ISSUE THREAD

**Issue by maumar** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#552]
Here are the issues in 2.1 branch when running query tests ported from EF Core repo:

- [ ] binding issues (16 tests): can't bind to parent query causing invalid sql. This is actually blocked by https://github.com/aspnet/EntityFrameworkCore/issues/12143. Filed https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/573 to track this more easily.
- [ ] casting issues (94 tests): casting is only supported for handful of types. Currently MySql tries to convert to other types, e.g double -> decimal. The probelm with this approach is that we get cast exception during materialization (expecting double, got decimal). This could potentially be improved by using value converters. Another approach would be to client eval, but that causes a lot of client eval (perf hit) and exposes a lot of bugs in query pipeline. Filed #571 to track this
- [x] query types test issues (9 tests) - Northwind model has hard coded FromSql statement for OrdersQuery: SELECT * FROM "Orders" - need to fix quotes
- [ ] other small issues (15 tests):
Translation of IndexOf
Translation of DateTime.Today
incorrect data returned for some date part functions for DateTimeOffset
DateAdd translation shouldn't use SqlFragment
need to client eval for limit + IN/ALL/ANY in a subquery

**Comment by maumar** [comment]
@AndriySvyryd fyi

**Comment by caleblloyd** [comment]
Closing as this was 2.1 release oriented
