### ISSUE TITLE
MySQL collation issue in EF Core

### ISSUE THREAD

**Issue by viveknuna** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#553]
My database is MySQL. I generate migration and update database, then I see the collation of table which is different on different machines. On my machine its latin1 - default collation and on a different machine, it is utf8 - default collation.

So due to this behavior, I'm getting an exception while inserting Japanese word (日本語) into a table which has a varchar(64) column. It works fine on another machine which has utf8 - default collation on this table.

EF Core Version: 2.0.1
MySql: 5.7.22
Pomelo.EntityFrameworkCore.MySql: 2.0.1

**Comment by viveknuna** [comment]
I'm getting 404 - Page not found on clicking the above links.

**Comment by Giantaxe** [comment]
My apologies, seems I put the links in wrong. Fixed now.

**Comment by viveknuna** [comment]
So When this be fixed completely?

**Comment by ajcvickers** [comment]
@Giantaxe So if the application requests that Unicode strings are saved, but the database is not setup with a collation that allows Unicode characters, what is your expectation of what the behavior should be? Also, is there a typically used default collation on MySQL and if so, does it support Unicode characters?

**Comment by caleblloyd** [comment]
I tend to agree with @Giantaxe.  I think that most MySQL users expect their string columns to be generated using their database default charset.

Our recommendation out of the gate in the [https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#getting-started](README.md) is to use `utf8mb4`.

I don't think we've included charset before, so I'm leaning towards keeping the default behavior the same.  This actually might be a good Provider-level option though - allow the user to specify Unicode and ANSI charsets otherwise use the database default.

There's a pretty long discussion about it in #84.

**Comment by AndriySvyryd** [comment]
Using the default charset could be ok for non-key columns. Though this is the opposite of what @viveknuna asked for.

However key and index columns have a max bound on length: 767 and 3072 byte for pre-5.7.7 and for 5.7.7+ respectively. So if the server default charset is used we would need to assume the worst - that it's utf8mb4 and could use up to 4 bytes per character meaning that the max length for the string column in a key or index would be 191 and 768. And this would only be enough for a single string column, so if the user needs to specify a composite key or index involving a string column they would always have to specify the correct max length explicitly to accommodate the other columns.

**Comment by caleblloyd** [comment]
> the max length for the string column in a key or index would be 191 and 768

This is actually a very real pain point, so there may be value in specifying the charset for Key and Index columns.  Does the current behavior only specify for Key and Index columns or does it specify for all columns?

Also what is your opinion of implementing it by introducing options in `MySqlDbContextOptionsBuilder` for `WithUnicodeCharSet` and `WithAnsiCharSet`?

**Comment by AndriySvyryd** [comment]
@caleblloyd Currently the charset is always specified.

A more flexible set of options would be:
- `WithDefaultCharsetBehavior(DefaultCharsetBehavior)`
  - `None` (default)
  - `NonIndexedColumns`
  - `All`
- `WithUnicodeCharSet` and `WithAnsiCharSet` that would allow to override the defaults of `ucs2` and `latin1` when the server default charset is not used

**Comment by caleblloyd** [comment]
I've got a similar design over in #569 now if you would like to comment on it!  Once we nail down the design there I'll work on some tests.

**Comment by serhioV** [comment]
Is there someone who can explain, how to support accents and like é, à, û, by default when creating a CodeFirst migration and having a property, say "public string Message {get; set; }" for the MySQL database or similar?

**Comment by mguinness** [comment]
@serhioV What is the default collation on your database?  The default is that columns will be unicode unless you use `.IsUnicode(false)` in your DbContext.

**Comment by serhioV** [comment]
> @serhioV What is the default collation on your database? The default is that columns will be unicode unless you use `.IsUnicode(false)` in your DbContext.

linked with the https://github.com/HeidiSQL/HeidiSQL/issues/356, probably that is rather the MySQL client issue, than the EF one... however is interesting to be able to change the desired encoding to support different chars (Russian Cyrillic or Chinese, by eg)
