### ISSUE TITLE
After SaveChanges, there is no self - increasing ID?

### ISSUE THREAD

**Issue by gaoconggit** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#554]
After SaveChanges, there is no self - increasing ID?

**Comment by caleblloyd** [comment]
This GitHub project is for reporting bugs.

Please use the [EF Core Documentation](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties) and ask usage-based questions on StackOverflow.
