### ISSUE TITLE
Error while loading related data in EntityFrameworkCore

### ISSUE THREAD

**Issue by Praveen-Rai** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#562]
**Code** 

**Application DB Context :**
```
        modelBuilder.Entity<Course>(entity =>
        {
            entity.ToTable("courses");

            entity.HasIndex(e => e.Id).HasName("idx_Courses_Id");

            entity.HasIndex(e => e.Url).HasName("uk_Url").IsUnique();

            entity.Property(e => e.Id).HasColumnType("int(11)");
        });

        modelBuilder.Entity<Coursepage>(entity =>
        {
            entity.ToTable("coursepages");

            entity.HasIndex(e => e.CourseId).HasName("idx_CoursePages_CourseId");

            entity.HasIndex(e => e.LessonId).HasName("idx_CoursePages_LessonId");

            entity.HasIndex(e => e.TopicId).HasName("idx_CoursePages_TopicId");

            entity.HasIndex(e => new { e.CourseId, e.LessonId, e.TopicId }).HasName("uk_CourseId_LessonId_TopicId").IsUnique();

            entity.Property(e => e.Id).HasColumnType("int(11)");
            entity.Property(e => e.CourseId).HasColumnType("int(11)");
            entity.Property(e => e.LessonId).HasColumnType("int(11)").HasDefaultValueSql("'0'");
            entity.Property(e => e.TopicId).HasColumnType("int(11)").HasDefaultValueSql("'0'");
            entity.HasOne(d => d.Course)
                .WithMany(p => p.Coursepages)
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CoursePages_Courses_CourseId");
        });
```

**Course Model :**
```
public partial class Course
{
    public Course()
    {
        Coursepages = new List<Coursepage>();
    }
    public ICollection<Coursepage> Coursepages { get; set; }
}
```
**CoursePages Model :**
```
public partial class Coursepage
{
    public int Id { get; set; }
    public int CourseId { get; set; }
    public int LessonId { get; set; }
    public int TopicId { get; set; }
    public Course Course { get; set; }
}
```
**Point of failure :**

```
var course = await _context.Courses.Include(c => c.Coursepages)
                .SingleOrDefaultAsync(m => m.Url == courseUrl);
```

### The issue
When trying to load related data, getting an error that the column name is not found. At the back-end the driver is searching for a column that is named as "<ModelName>Id" which is not the convention being followed.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
MySqlException: Unknown column 'c.CoursepageId' in 'field list'
MySqlConnector.Protocol.PayloadData.ThrowIfError() in PayloadData.cs, line 19

MySqlException: Unknown column 'c.CoursepageId' in 'field list'
MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in MySqlDataReader.cs, line 92
```

### Further technical details

MySQL version: 5.7
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

**Comment by Praveen-Rai** [comment]
I figured that the cause of the problem was a property which is a collection of coursepages. This is sincee the course is hierarchical data ( Course > Lessons > Topics ). So basically my **courpages model** looked like : 
```
public partial class Coursepage
{
    public int Id { get; set; }
    public int CourseId { get; set; }
    public int LessonId { get; set; }
    public int TopicId { get; set; }
    public Course Course { get; set; }

      //  If current page is a Lesson Page
      public List<Coursepage> Topics { get; set; }
}
```

But i really didn't understand the root cause for it. are we supposed to handle this kind of situation if the provider doesn't support it ?

**Comment by caleblloyd** [comment]
This looks usage-based.  You need to ensure you have primary keys and that your constraints are setup properly.  I'd recommend the [EFCore Docs](https://docs.microsoft.com/en-us/ef/core/) and StackOverflow for usage-based questions.

If you're getting a MySQL specific error with a stack trace please open a new issue with a recreate.

**Comment by Praveen-Rai** [comment]
@caleblloyd I also tried adding key using Fluent API, even then it failed. I not the right person to decide if it is a bug or as design. But there's a lot of hierarchical data to be stored in RDBMs, and the method i used seems to be common. I request your wisdom to take a call on this.

**Comment by caleblloyd** [comment]
Check out the models in our Integration Tests for some samples:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/tree/4c099402e3c044fe0cc0d876d8e73630f2eb36c6/test/EFCore.MySql.IntegrationTests/Models

`Blog.cs` and `Crm.cs` both have hierarchical examples

**Comment by caleblloyd** [comment]
The `CrmTest` has some good samples of querying with hierarchical data as well:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/4c099402e3c044fe0cc0d876d8e73630f2eb36c6/test/EFCore.MySql.IntegrationTests/Tests/Models/CrmTest.cs
