### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by a641545621** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#567]
![1](https://user-images.githubusercontent.com/33652128/40698174-63533c00-6400-11e8-80d0-8d96324b1fab.png)
![2](https://user-images.githubusercontent.com/33652128/40698175-63b04ec2-6400-11e8-9768-84f2a43211db.png)
![3](https://user-images.githubusercontent.com/33652128/40698176-640de2e4-6400-11e8-9878-f27dc3c64275.png)
![4](https://user-images.githubusercontent.com/33652128/40698177-646b30de-6400-11e8-8f6d-a22860562b06.png)

How should I set to solve this problem?

Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'RepositoryDbContext'.

**Comment by mguinness** [comment]
Unsure this is a provider issue.  See if you can replicate using [SQLite EF Core Database Provider](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/).

**Comment by antonioortizpola** [comment]
Mmmm, i do not know if that afects, but you are not using async right, you should be using `Tasks`, not `Threads`, and `Task.Delay`, not `Thread.Sleep`.
Your async method should return `Task`, not `void`, and if you could post the code as text and not as image could make easier for us to make some notes!, But like @mguinness i bet the problem is not in the provider

**Comment by caleblloyd** [comment]
@antonioortizpola is right, the `async void` is more than likely the issue, it needs to be `async Task` and must be awaited.
