### ISSUE TITLE
Foreign key object is Null in example

### ISSUE THREAD

**Issue by Herbstein** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#570]
### Steps to reproduce
Uses the example from the README as a baseline.

#### This doesn't work

```csharp
var ret = context.Blogs.Where(x => x.Tags.Object.Contains("Pomelo"));

foreach (Blog blog in ret)
{
    Console.WriteLine(blog.User.Name);
}
```

#### This works
```csharp
foreach (User user in context.Users)
{
    Console.WriteLine(user);
}

var ret = context.Blogs.Where(x => x.Tags.Object.Contains("Pomelo"));

foreach (Blog blog in ret)
{
    Console.WriteLine(blog.User.Name);
}
```

### The issue
I would expect the first example to work without issue, and without having to do work on the set of users first. I get the NullReferenceException when accessing `blog.User`.

```
Exception message: System.NullReferenceException: 'Object reference not set to an instance of an object.'
```

### Further technical details

MySQL version: 5.7.21
Operating system: Windows 10 1709
Pomelo.EntityFrameworkCore.MySql version: v2.0.1

**Comment by mguinness** [comment]
Don't you need to [eager load](https://www.learnentityframeworkcore.com/dbset/querying-data#include-related-data) related data?

**Comment by mguinness** [comment]
I don't know the implementation specifics, but you can look at a [feature comparison](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/features).
