### ISSUE TITLE
Document Funcional Test Failures in issues, then enable in CI

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#581]
Currently functional tests are disabled in CI because of the numbef or failures.

```
dotnet test -c Release test/EFCore.MySql.FunctionalTests

Total tests: 7299. Passed: 7106. Failed: 50. Skipped: 143.
```
Each failure should be investigated then assigned an issue.  Once an issue is assigned, `[Fact(Skip="Issue Number")]` can be applied to the issue.

Once all failures are documented in issues and skipped we can enable them to more easily detect regressions.

**Comment by caleblloyd** [comment]
#583 addressed most of these.

Still get 4 failures on `netcoreapp2.0` and 6 failures on `netcoreapp2.1` and also still need to verify `net461` on windows before enabling functional tests in CI.

**Comment by AndriySvyryd** [comment]
@caleblloyd Which tests are failing for you?

**Comment by caleblloyd** [comment]
@AndriySvyryd just opened #586 so we can see the failing tests in all framework versions.  Looks like a few that the charset PR will fix.

**Comment by AndriySvyryd** [comment]
Interesting, seems like the `SimpleQueryMySqlTest.Where_concat_string_int_comparison` tests depend on the default server charset. The charset configuration PR probably will fix those tests just by having a uniform charset. But in more complex models the user might still have to use different charsets for the columns, so https://github.com/aspnet/EntityFrameworkCore/issues/4978 would be needed for a complete fix.

**Comment by caleblloyd** [comment]
Travis CI Hangs and stops:

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

I think we're going to need a bigger CI Server if we are going to enable this in CI.  We will have to run functional tests with manual verification for the time being.

**Comment by caleblloyd** [comment]
@yukozh the MyGet Build Services are no longer necessary for this repo.  I made it so that we deploy straight to MyGet from TravisCI if it is on the `master` branch or if it is a Git tag:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/4a59ca613ae3fe9e780b1468253b2201550ea65c/.travis.yml#L46-L56

**Comment by AndriySvyryd** [comment]
@caleblloyd Perhaps just increasing the verbosity would help or you can increase the timeout as explained in the travis docs

**Comment by caleblloyd** [comment]
It was hanging for 10 minutes with no output, definitely looked frozen. I don't think increasing the wait timeout on Travis would help.

Is there any way to increase the size of the thread pool that Xunit uses?

**Comment by AndriySvyryd** [comment]
This might also be caused by https://github.com/aspnet/EntityFrameworkCore/issues/5308

**Comment by caleblloyd** [comment]
Closing as this was 2.1 release oriented
