### ISSUE TITLE
Improve Synchronous Performance

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#59]
With the merging of #58, Async Performance is solid.  Threads are not held and Performance tests can run 500+ RPS while keeping response time under 1s.

There is problems with threads getting held during Synchronous performance tests, however.  Synchronous tests have trouble achieving 100 RPS without lockups.

While it is best practice to use Async methods, we can't guarantee that everyone is doing that.  Need to investigate synchronous performance issues and improve so that there are no lockups.

**Comment by caleblloyd** [comment]
Fix will come once https://github.com/bgrainger/MySqlConnector/issues/62 is merged into MySqlConnector and released

**Comment by Kagamine** [comment]
Released 10012

**Comment by caleblloyd** [comment]
Need to change our synchronous methods to call synchronous methods in MySqlConnector.  I will work on this tonight.

**Comment by caleblloyd** [comment]
Quick performance test:

1.0.0: Asynchronous: 30 RPS, Synchronous: 30 RPS
1.0.1: Asynchronous: 300 RPS, Synchronous: still needs fixes

1.0.1 _should_ bring a **10x** performance increase

**Comment by Kagamine** [comment]
What is the official perf test result?

**Comment by caleblloyd** [comment]
> What is the official perf test result?

Hardware Setup: Intel i5-6600K (4 cores), Ubuntu 16.04

Test Methodology: Run the [performance test](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/tree/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests) for 5s with varying RPS rates until 99th percentile request is within 10% of 100ms.  Run at least 3 times.

Results:

	Version   IO Type    Sustained RPS @100ms
	1.0.0     Async      60
	1.0.1     Async      480  => 8x Speedup for Async
	
	1.0.0     Sync       50
	1.0.1     Sync       90   => 1.8x Speedup for Sync

These test results also go to show how important it is for apps to implement Async all the way down.

Great job @bgrainger on the truly async [MySqlConnector](https://github.com/bgrainger/MySqlConnector) and @Kagamine on the solid EF implementation.  We've got the world's first truly async MySql driver for Entity Framework!

**Comment by Kagamine** [comment]
Could you compare our lib to the oracle one?

**Comment by caleblloyd** [comment]
> Could you compare our lib to the oracle one?

I've got an environemnt variable built into the performance test that will run it with Oracle: `export EF_PROVIDER=oracle`

The problem is that [MySql.Data.EntityFrameworkCore/7.0.5-IR21](https://www.nuget.org/packages/MySql.Data.EntityFrameworkCore/7.0.5-IR21) has too many bugs and throws exceptions for all of the methods in the performance test.  I'll try to run it once they release an update.
