### ISSUE TITLE
Old 2.0 Migrations with Foreign Key or Index Identifiers longer than 64 characters does not work properly in 2.1

### ISSUE THREAD

**Issue by TriJetScud** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#590]
### Steps to reproduce
Create a database migration that auto generates foreign key constraints or index identifier that is longer than 64 characters.

### The issue
Prior to commit 1191bc26b740f2514ffced8f3eabb46088b68574, foreign key or index identifiers that is greater than 64 characters is truncated when the migration script is being generated by the database provider. Since the ``LimitLength()`` string extension along with it's use has been removed from the codebase, older migrations generated with the 2.0 EF Core provider that happens to have an auto generated FK or index constraint that is longer than 64 characters are now unusable.

As with EF Core 2.1, the ORM now gives [Database Providers](https://github.com/aspnet/EntityFrameworkCore/commit/05d3442f9a6096680d1575beffeea3cf3f764f48) the ability to pre-emptively limit the length of the generated identifiers at the provider level as opposed to being limited when the migration script is generated. Currently, it seems like Pomelo's EF Core provider now takes advantage of this feature without regard to older migrations generated in the 2.0 branch.

### Workaround
Remove all migrations generated with the old 2.0 database provider and start fresh.

**Comment by WillooWisp** [comment]
That is a "workaround" most existing applications cannot use.

**Comment by caleblloyd** [comment]
Thanks for the report. We'll look at options for fixing this in 2.1.0 RC2.

**Comment by caleblloyd** [comment]
I think we may need to reccomend that a manual migration fix be applied and it can be documented in the release notes. The old behavior led to foreign keys being truncated. The manual migration would need to rename any previously truncated foreign key to the new shortened format.

**Comment by caleblloyd** [comment]
Fixed in [2.1.0-rc2-final](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.1.0-rc2-final)
