### ISSUE TITLE
JsonObject<T> could not be mapped well

### ISSUE THREAD

**Issue by fzrain** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#598]
### Steps to reproduce
Define a JsonObject<T> Type in Entity
Excute Add-Migration and Update-Database

### The issue
In migration file this type mapped "string".The db column type is "longtext" when update to database.However,this type should be "json"

### Further technical details

MySQL version: 5.7.21
Operating system: win10  1803
Pomelo.EntityFrameworkCore.MySql version:2.1.0-rc1-final

Other details about my project setup:

**Comment by caleblloyd** [comment]
`JSON` column type needs to be explicitly defined until https://github.com/aspnet/EntityFrameworkCore/issues/12212 is fixed

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/118df643819609b6986f64db4ece05033df7e8cb/test/EFCore.MySql.IntegrationTests/AppDb.cs#L82-L89
