### ISSUE TITLE
Define Timestamp property

### ISSUE THREAD

**Issue by ehajri** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#605]
I couldn't find anywhere a clear straight to the point answer, but is it possible to define a `Timestamp` property with Pomelo Provider and EF Core 2.1 in a way the generated column is of type `Timestamp`?

**Comment by mguinness** [comment]
What have you tried?  [Data Types](https://docs.microsoft.com/en-us/ef/core/modeling/relational/data-types) shows you how and specifying the string "TIMESTAMP" should work.

**Comment by ehajri** [comment]
Thanks @mguinness. 

I confirm that. Using `[Timestamp]` annotation with/without data types `DateTime`, `DateTimeOffset` or `byte[]` does not work.
```c#
[Column(TypeName = "TIMESTAMP")
public DateTime Timestamp { get; set; }
```
Does the trick.

**Comment by ehajri** [comment]
@mguinness Do I have control on whether to have `on update CURRENT_TIMESTAMP` or not?

I want to create 2 properties:

- `CreatedOn` to have default value as `CURRENT_TIMESTAMP`

- `UpdatedOn` to have default value as `NULL` and extra `on update CURRENT_TIMESTAMP`

**Comment by ehajri** [comment]
For future references, [question is here](https://stackoverflow.com/questions/50823809/how-to-create-createdon-and-updatedon-using-ef-core-2-1-and-pomelo)
