### ISSUE TITLE
Decimal precision - No design-time services were found.

### ISSUE THREAD

**Issue by oscarislas** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#609]
Changed a decimal property precision with the following notation:
```
modelBuilder.Entity<Entity>().Property(o => o.Property).HasColumnType("decimal(12,10)");
```
Which created the following migration: 
```
migrationBuilder.AlterColumn<decimal>(
                name: "Property",
                table: "Entity",
                type: "decimal(12,10)",
                nullable: false,
                oldClrType: typeof(decimal));
```

Running the _Update-Database -Verbose_ command gives the following output:
```
Finding design-time services for provider 'Pomelo.EntityFrameworkCore.MySql'...
Using design-time services from provider 'Pomelo.EntityFrameworkCore.MySql'.
Finding IDesignTimeServices implementations in assembly 'proyect'...
No design-time services were found.
```
Making no changes on the table schema

Is there no implementation for decimal precision, or am I doing something wrong?

**Comment by mguinness** [comment]
What does `Script-Migration` show?

**Comment by oscarislas** [comment]
```
ALTER TABLE `Packages` MODIFY COLUMN `Value` decimal(12,10) NOT NULL;
ALTER TABLE `Packages` ALTER COLUMN `Value` DROP DEFAULT;
```
Seems that it's creating the SQL correctly.
Recreated the table and the schema is now showing correctly

Seems like my problem was elsewhere, didn't knew about ```Script-Migration``` command, helped a lot.

Thankyou.
