### ISSUE TITLE
MyGet ci cannot build our library

### ISSUE THREAD

**Issue by Kagamine** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#61]
Since we have implemented perf tests, myget does not pass the pert test cases.(They don't support mysql service now).

Can we check the environment var "MyGet" in build.ps1, if the value is `True` then remove the folder ./test/Pomelo.EntityFrameworkCore.MySql.PerfTests?

@caleblloyd

**Comment by Kagamine** [comment]
@caleblloyd Still not works, can you provide me your username of MyGet

**Comment by caleblloyd** [comment]
@Kagamine I just signed up for MyGet.org, username is "caleblloyd"

**Comment by Kagamine** [comment]
Done

**Comment by caleblloyd** [comment]
MyGet is running `build.cmd` all the way through, which calls `build.ps1`

Then it runs `build.ps1` again

It should only run one of these.  I'm going to disable the `build.cmd` script if it runs on MyGet

**Comment by caleblloyd** [comment]
Fixed in #65
