### ISSUE TITLE
SET SESSION SQL_MODE When ever Connection made with Server

### ISSUE THREAD

**Issue by Vijaykumarj** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#610]
### Steps to reproduce
I developed one web application by using ASP.Net Core 2.0.7. It was deployed in Shared Hosting server. So How i can  SET SESSION SQL_MODE for every time when ever connection made.  Because we can't change Global SQL_MODE variable info.

### The issue
Describe what is not working as expected.
This is not a bug
If you are seeing an exception, include the full exceptions details (message and stack trace).

This is not a bug

Exception message:
Stack trace:
This is not a bug

### Further technical details
Where we can set SQL_MODE variable & how.

MySQL version: 5.7.21
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

Other details about my project setup:

Thanks in advance.

**Comment by caleblloyd** [comment]
Thanks for the feature request.  This would have to happen in MySqlConnector, so I opened an issue for it there:

https://github.com/mysql-net/MySqlConnector/issues/519

**Comment by mguinness** [comment]
See if [Can I fire an event on connect database in Entity Framework Core?](https://stackoverflow.com/questions/42587984/can-i-fire-an-event-on-connect-database-in-entity-framework-core) might help.

**Comment by caleblloyd** [comment]
Nice find @mguinness!  That would be the best way to get this functionality now @Vijaykumarj

**Comment by Vijaykumarj** [comment]
very interesting solution of my problem.
thanks to @caleblloyd  & @mguinness 
Happy coding
