### ISSUE TITLE
Detecting Changes in table in order to detect when any changes

### ISSUE THREAD

**Issue by Vijaykumarj** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#617]
Receive Notifications when a table record changes between an asp.net web application and an instance of mysql like **SQLDependency in SQL Server**. 

If our library is not support, let me know any other libraries are supported of this feature.

thanks in advance

**Comment by bgrainger** [comment]
Duplicate of mysql-net/MySqlConnector#522.

**Comment by mguinness** [comment]
Closing issue due to cross-posting.
