### ISSUE TITLE
Database level charset and collation support

### ISSUE THREAD

**Issue by gorgi** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#618]
Hi guys, thanks for the great work! 

I noticed that all issues regarding setting collation and character set are closed, but in my opinion I think that explicit options to set these settings on database, table and column level are necessary. Here's what I'm experiencing (My MySQL knowledge is limited):

1. When executing CREATE TABLE, if collate is not specified, the table is created with server's default collation, not the database default collation. 

2. When setting a CHARSET option to a column and not specifying COLLATE, if CHARSET is utf8mb4, then collation to that column is set to utf8mb4_general_ci. I need my columns to be utf8mb4_unicode_ci. 

With the new options in Pomelo 2.1 to set the charset to CharSet.Utf8mb4 is only setting the charset, but collation of the column is defaulting to utf8mb4_general_ci. 

My workaround for this was to set the server default collation to utf8mb4_unicode_ci and set CharSetBehaviour to NeverAppend. This way, my tables and columns are created with my desired collation.

I hope you have understood my issue :)

**Comment by caleblloyd** [comment]
> 1. When executing CREATE TABLE, if collate is not specified, the table is created with server's default collation, not the database default collation.

The latest [MySql Documentation](https://dev.mysql.com/doc/refman/8.0/en/charset-server.html) says "The server character set and collation are used as default values if the database character set and collation are not specified in CREATE DATABASE statements. They have no other purpose."  I read that as  `CREATE TABLE` should inherit from the Database Charset/Collation, and the Database Charset/Collation will be initialized with the server default if one is not specified.

> 2. When setting a CHARSET option to a column and not specifying COLLATE, if CHARSET is utf8mb4, then collation to that column is set to utf8mb4_general_ci. I need my columns to be utf8mb4_unicode_ci.

We should add a `AnsiCollate` and `UnicodeCollate` option to [MySqlDbContextOptionsBuilder](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Infrastructure/MySqlDbContextOptionsBuilder.cs)

---

We could support appending CharSet/Collate to Databases and Tables by adding the following options to [CharSetBehavior](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/7f4f7122d1d42ca178e32303d1e7dc7ddc8fb9e0/src/EFCore.MySql/Infrastructure/CharSetAppendBehavior.cs):

- `AppendUnicodeToCreateDatabase`
- `AppendAnsiToCreateDatabase`
- `AppendUnicodeToCreateTable`
- `AppendAnsiToCreateTable`

**Comment by gorgi** [comment]
I'm actually using MariaDB, but it should behave same as MySQL.

I am not sure why I experience number 1, but the point is that we need control over setting database charset and collation. 

Regarding column charset, according to Maria DB documentation from https://mariadb.com/kb/en/library/setting-character-sets-and-collations/

> If only the character set is provided, the default collation for that character set will be used .


For charset utf8mb4, the default collation is utf8mb4_general_ci. And it doesn't matter what the table default collation is, so that's why I think an option for column collation is needed.

**Comment by Torvin** [comment]
@caleblloyd are those changes ever going to happen? I mean, are they on roadmap?

**Comment by lauxjpn** [comment]
> For charset `utf8mb4`, the default collation is `utf8mb4_general_ci`. And it doesn't matter what the table default collation is, so that's why I think an option for column collation is needed.

> are those changes ever going to happen? I mean, are they on roadmap?

@Torvin We have column level charset and collation support since 3.0.0.

The following issue and PRs might be of interest to you:
* #1001 General question and answer about charset/collation and migrations
* #903 PR that reimplemented the general charset support (including column level support)
* #930 PR that implemented column level collation support
* #931 PR that added scaffolding specific connection string options (regarding charset and collation)

In case your want charset and collation support on a table level, we have #913 tracking this.

**Comment by Torvin** [comment]
@lauxjpn Thank you for such a quick reply! How about database-level charset and collation?

**Comment by lauxjpn** [comment]
No, there is currently no database level charset and collation support. Since we have already a tracking issue about table level support, we can reuse this one for the database level support.

Until then, what is your concrete scenario. There is probably a quick workaround we can find for you.

**Comment by Torvin** [comment]
I'm using a manual sql statement in my first migration as suggested in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/84#issuecomment-450519464:
```c#
migrationBuilder.Sql("alter database character set utf8mb4 collate utf8mb4_unicode_ci");
```

I guess there's no better workaround at the moment?

**Comment by lauxjpn** [comment]
That is probably the quickest way of defining a default charset and collation.
The reason why we have not yet implemented table or database level support, is that there are unresolved issue with how those can be implemented in a consistent and expected way. If you want to join the conversation about it, start with reading https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/913#issuecomment-552099311.

**Comment by Torvin** [comment]
Thanks a lot for your answers and happy new year!
