### ISSUE TITLE
The `Order` property of `Column` attribute applied to base entity is not work.

### ISSUE THREAD

**Issue by liamwang** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#632]
### Steps to reproduce
The `Order` property of `Column` attribute applied to base entity is not work. 

Foo Entity: 
```csharp
public class Foo : Entity
{
    [Column(Order = 1)]
    public int ColumnZ { get; set; }

    [Column(Order = 2)]
    public int ColumnA { get; set; }

    // Other properties
}
```

Base Entity:
```csharp
public abstract class Entity<TKey> : IEntity<TKey>
    where TKey : IEquatable<TKey>
{
    [Key]
    public virtual TKey Id { get; set; }
        
    [Column(Order = 99)]
    public virtual DateTime CreatedAt { get; set; } = DateTime.Now;
}

public abstract class Entity : Entity<int>
{ }
```

### The issue

The order of table column is not correct: 

![image](https://user-images.githubusercontent.com/5000396/42320168-fa7fc1f0-8086-11e8-947a-b91ee6084c76.png)

**The `CreatedAt` column should be at the end.**

### Further technical details

Pomelo.EntityFrameworkCore.MySql version: 2.1.0-rc2-final

**Comment by caleblloyd** [comment]
This isn't implemented upstream: https://github.com/aspnet/EntityFrameworkCore/issues/2272

CLR Property order is preserved, but new columns will get appended to the end:

https://github.com/aspnet/EntityFrameworkCore/issues/2272#issuecomment-379825400
