### ISSUE TITLE
EF Scaffolding no longer converts char(36) to Guid, it converts to string instead.

### ISSUE THREAD

**Issue by DragonDTG** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#639]
### Steps to reproduce
```
dotnet new console
dotnet add package Microsoft.AspNetCore.All --v 2.1.0
dotnet add package Pomelo.EntityFrameworkCore.MySql -v 2.1.0-rc2-final
dotnet ef dbcontext scaffold "Server=..." "Pomelo.EntityFrameworkCore.MySql" --use-data-annotations
```

### The issue

The resulting generated files have a `string` instead of a `Guid` type for char(36):

```
[Table("company")]
public partial class Company
{
    [Required]
    [Column("company_key", TypeName = "char(36)")]
    public string CompanyKey { get; set; }
}
```

Using version 2.0.1 resulted in the expected behavior:

```
[Table("company")]
public partial class Company
{
    [Column("company_key")]
    public Guid CompanyKey { get; set; }
}
```

### Further technical details

MySQL version: Amazon Aurora
Operating system: Windows 10.
Pomelo.EntityFrameworkCore.MySql version: 2.1.0-rc2-final

### SQL
```
CREATE TABLE `company` (
    `company_key` CHAR(36) NOT NULL
);
```

**Comment by lauxjpn** [comment]
It is likely, that this issue has been already fixed. If it hasn't, it is with #904. You can use the connection string option `GuidFormat` to explicitly set the type that is being used to convert a `System.Guid`  to and from (including `MySqlGuidFormat.Char36` which is the default). Reverse engineering scenarios are supported.
