### ISSUE TITLE
version 2.1.1 doesnt work with donet core 2.1

### ISSUE THREAD

**Issue by callmeblessed** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#641]
### Steps to reproduce
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\"/>
  </ItemGroup>
  <ItemGroup>

  <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" PrivateAssets="All" />

    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="4.0.1"/>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.1.1" />
  </ItemGroup>
 
</Project>

### The issue
I run dotnet restore but it produce errors
E:\CRSApp\crsapp.api\CRSApp.API.csproj : error NU1107: Version conflict detected for Microsoft.EntityFrameworkCore. Reference the package directly from the project to resolve this issue.
E:\CRSApp\crsapp.api\CRSApp.API.csproj : error NU1107:  CRSApp.API -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Microsoft.EntityFrameworkCore.Relational 2.1.1 -> Microsoft.EntityFrameworkCore (>= 2.1.1)
E:\CRSApp\crsapp.api\CRSApp.API.csproj : error NU1107:  CRSApp.API -> Microsoft.AspNetCore.App 2.1.0 -> Microsoft.EntityFrameworkCore (= 2.1.0).

```
Exception message:
Stack trace:
```

### Further technical details

MySQL version:  5.7
Operating system: Windows 10 
Pomelo.EntityFrameworkCore.MySql version: 2.1.1

Other details about my project setup:

**Comment by paonath** [comment]
Maybe you have to reference 2.1.1 version for Microsoft.AspNetCore.App

**Comment by mguinness** [comment]
> Maybe you have to reference 2.1.1 version for Microsoft.AspNetCore.App

Correct, the provider is closely tied to the upstream EF Core libraries so using the same version numbers is essential.  Due to limited resources, there was no final 2.1.0 version only a 2.1.1 version published.

**Comment by caleblloyd** [comment]
I went back and published [2.1.0](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.1.0), which will work with those who only have access to 2.1.0 for now, such as AWS Lambda

**Comment by caleblloyd** [comment]
If you can control it though, it is best to go to 2.1.1 since that has fixes from EF Core Upstream.

**Comment by callmeblessed** [comment]
Thanks .  I just upgrade my dotnet core to 2.1.x and write Version="2.1.1" and it work now.

**Comment by bezysoftware** [comment]
Is it possible to use EF Core 2.1.2 & Pomelo 2.1.1? Are you planning a release for v2.1.2?

**Comment by mguinness** [comment]
Pomelo is closely tied to the upstream library versions so a new release will be required (see [dependencies.props](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/build/dependencies.props)).  A new release will likely be made in due course, but due to developer constraints (see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/522) there is no timeline.

**Comment by caleblloyd** [comment]
EF Core is on version [2.1.1](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/2.1.1)

We already have a 2.1.1 published targeting EF Core upstream 2.1.1

If EF Core updates, we will update to match it.  If there are changes that must be made it can take some time to bring our provider up-to-date.  If it is a security update or no changes have been made then we can release quickly.

**Comment by mammadkoma** [comment]
Add "Pomelo.EntityFrameworkCore.MySql" package.
in Stertup.cs & appsettings.json & DbContext :


services.AddDbContext<mvccoreContext>(options =>
         options.UseMySql(Configuration.GetConnectionString("DefaultConnection")
        ));
      

     {
      "ConnectionStrings": {
        "DefaultConnection": "Server=localhost;Database=mvccore;User=root;Password=;"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Warning"
        }
      },
      "AllowedHosts": "*"
    }


protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseMySql("");
        }
    }
