### ISSUE TITLE
How about the future of this project

### ISSUE THREAD

**Issue by rocketRobin** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#647]
Will there be formal assistance from Microsoft engineers?

My project wants to migrate from Mysql.Data.EntityFramework to here.

So, I am very concerned about the future of this project. Thank you.

**Comment by caleblloyd** [comment]
It is a community driven project. Microsoft engineers may choose to help in the future but there is no SLA or guarantee. It would be better if community members with reliance on MySQL and Entity Framework contributed back.

If you use Oracle or DevArt providers, you always have the option to pay those respective companies for support.

If you use this provider, you can always contribute changes back to it and help make it better.

**Comment by rocketRobin** [comment]
Ok，I will try to read the code, and try to make some contributions.
