### ISSUE TITLE
MySqlConnector docs say Synchronous Method (avoid when possible)

### ISSUE THREAD

**Issue by rocketRobin** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#648]
[Best Practices](https://mysql-net.github.io/MySqlConnector/tutorials/best-practices/) say that always use async when possible. I want to know how the practices in Pomelo.EntityFrameworkCore.MySql, when I use the sync method like Select() or context.SaveChanges(), will the provider user async method in MySqlConnector?

**Comment by YandyZaldivar** [comment]
I/O like database access should perform better with async calls, this depends on the project, the number of calls, its size and its concurrency. Internally Pomelo does a great job, you shouldn't worry whether it use async calls or not. The same goes for MySql.Connector.

Regarding the use of Select(), it is part of the query which is not executed until a method like List() or ListAsync() is used, it is up to you which version to use. The same applies for context.SaveChanges(), you can opt to use context.SaveChangesAsync(). In neither case it is Pomelo responsibility. These calls mostly impacts your application code, not Pomelo or MySql.Connector.
