### ISSUE TITLE
MySQL Server is requesting the insecure pre-4.1 auth mechanism

### ISSUE THREAD

**Issue by mkchx** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#649]
I have a dotnet core 2.1 project and I'm trying to query the MySql database, but I'm getting an error
**NotSupportedException: 'MySQL Server is requesting the insecure pre-4.1 auth mechanism (mysql_old_password). The user password must be upgraded; see https://dev.mysql.com/doc/refman/5.7/en/account-upgrades.html.**

The Startup.cs:
...
```
services.AddDbContextPool<MyDbContext>(
                options => options.UseMySql(_appConfiguration.GetConnectionString("Elastix"),
                    mysqlOptions =>
                    {
                        mysqlOptions.ServerVersion(new Version(5, 0, 95), ServerType.MySql);
                    }
            ));
```
It's not up to me to upgrade the database password hashing and the mysql_old_password plugin.
So is there any way to make it work without upgrading?

### Further technical details

MySQL version: 5.0.95
Operating system: Win10
Pomelo.EntityFrameworkCore.MySql version: 2.1.1

Thanks in advance

**Comment by caleblloyd** [comment]
MySQL Version is 5.0.95 is pretty far out of the support window:
https://docs.oracle.com/cd/E17952_01/mysql-5.0-relnotes-en/news-5-0-95.html

I'd recommend upgrading to 5.7 or 8.0.

**Comment by mokkymiah** [comment]
@mkchx Did you find a solution? I am also in the same situation and I have no control over upgrades.

**Comment by mkchx** [comment]
@mokkymiah I think you have to set the old_passwords to ON for your mysql instance..
Checkout this answer https://dba.stackexchange.com/a/155969
![image](https://user-images.githubusercontent.com/13793844/60324643-ffa5b880-998d-11e9-9747-5e8632d16dd6.png)
