### ISSUE TITLE
LINQ Contains is not accent insensitive

### ISSUE THREAD

**Issue by neumartin** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#652]
### Steps to reproduce
Use linq like c.Nombre.Contains(pLow) and prepare one row with nombre 'Nicolás'

I found the query is not "like Nombre '%nicolas%'", the query is like this: LOCATE(@__pLow_1, `p`.`Nombre`)

### The issue
Only find results when use accent in my pLow variable, but if I excecute the query by hand works ok.

### Further technical details

MySQL version: 5.7
Operating system: Devian 9.5
Pomelo.EntityFrameworkCore.MySql version: 2.1.1

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/495 and resolution using [EF.Functions.Like()](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-entity-framework-core-2-0/#like-query-operator) method.

**Comment by neumartin** [comment]
Thanks @mguinness !
But why contains uses locate and not like?

**Comment by juaal12** [comment]
> Thanks @mguinness !
> But why contains uses locate and not like?

Hi @neumartin,

How did you solve your issue with contains? I mean, as far I've read on github and several issues, using EF.Functions.Like() should solve my accent sensitive filter when trying to get data from my DB but it is not being solved.

Let's say I have a customer in my DB with name "Rémy".

My query is like: 

var filter = "Remy";
var customers = customers.Where(c => EF.Functions.Like(c.Firstame, $"%{filter}%"));

Variable customers will be empty.

**Comment by lauxjpn** [comment]
@juaal12  Please post the `CREATE TABLE` statement of your `Customers` table and the version of MySQL/MariaDB and Pomelo you are using, so we can take a look at this.

**Comment by neumartin** [comment]
@juaal12 I never fix this issue, but works fine with this versions:

    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="2.2.*" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="2.2.*" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.2.0" />

To search by many words in a single string I use this code:

```
                    IQueryable<Cliente> query = context.Clientes.Where(p => p.IdEmpresa == idEmpresa && !p.Borrado);

                    if (!string.IsNullOrWhiteSpace(criterio))
                    {
                        string[] palabras = criterio.Split(' ');

                        foreach (string palabra in palabras)
                        {
                            string pLow = palabra.ToLower().Trim();
                            query = query.Where(p =>
                                criterio == "" || EF.Functions.Like(p.Nombre, $"%{pLow}%") ||
                                EF.Functions.Like(p.Apellido, $"%{pLow}%") ||
                                EF.Functions.Like(p.TipoDocumento.Nombre, $"%{pLow}%") ||
                                p.Documento.StartsWith(pLow) || p.Paciente.NroAfiliado.StartsWith(pLow) ||
                                p.Paciente.NroAfiliadoAlternativo.StartsWith(pLow));
                        }
                    }
```
