### ISSUE TITLE
Can I use EF migrations with identity?

### ISSUE THREAD

**Issue by JakubR** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#66]
Hi, 
when I use: 
dotnet ef database update --verbose
I got this error:
Pomelo.Data.MySql.MySqlException: Table 'testdb.__efmigrationshistory' doesn't exist

is ef migrations supported?

**Comment by Kagamine** [comment]
Migrations has been supported  fully. Have you  executed dotnet ef migrations add init？

**Comment by JakubR** [comment]
The problem was because if database exist (but has no tables) ef stops, just delete database and all work fine.

**Comment by Mats391** [comment]
Have same issue.

```
dotnet ef migrations add Init
dotnet ef database update
```
generates same error as using entityframeworkcore/Add-Migration etc.
Deleting the database is not really an option for me. You can add the table yourself.
```
table-name: __efmigrationshistory
Columns:
MigrationId varchar(150) PK
ContextKey varchar(300)
Model longblob
ProductVersion varchar(32)
```
In the end it should work even if database is created and the migration table is missing. So I would say open the issue again

**Comment by Kagamine** [comment]
Does EF Core for sqlserver support migrating with an existed db? I think it does not.

**Comment by Kagamine** [comment]
Without migrate histories, ef cannot decide which migrate script should be apply.

**Comment by Mats391** [comment]
> Does EF Core for sqlserver support migrating with an existed db? I think it does not.

Cant tell for EF core as I only used it with your adapter so far. Normal EF creates the __migrationhistory table if it does not exist even if the DB already exists.
