### ISSUE TITLE
Scaffolded varchars don't have HasMaxLength()

### ISSUE THREAD

**Issue by AccessViolator** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#661]
### Steps to reproduce

Have a table with columns
```
Name varchar(20) DEFAULT NULL,
Data varbinary(20) DEFAULT NULL,
```
Run scaffolding.
2.0.1 produced
```
entity.Property(e => e.Data).HasMaxLength(20);
entity.Property(e => e.Name).HasMaxLength(20);
```
2.1.1 produces
```
entity.Property(e => e.Data).HasMaxLength(20);
entity.Property(e => e.Name).HasColumnType("varchar(20)");
```
### The issue
[According to this](https://docs.microsoft.com/en-us/ef/core/modeling/max-length) EF doesn't validate the lengths, so I suppose it doesn't make any difference at runtime, but I searched issues here for HasMaxLength and didn't find anything that would indicate that this was an intentional change. I think it's better to stick to HasMaxLength as it's more implementation agnostic.
### Further technical details

MySQL version: 8.0.11
Operating system: Win 7 x64
Pomelo.EntityFrameworkCore.MySql version: 2.1.1

**Comment by mguinness** [comment]
AFAIK nothing changed in this provider for scaffolding in [GetColumns()](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs#L108).  Take a look at the logic upstream in [GenerateProperty](https://github.com/aspnet/EntityFrameworkCore/blob/df9d2ccb47614b014c11903ed0eb8c9830da1d2c/src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs#L580) for any changes.

**Comment by AccessViolator** [comment]
I've just tried Microsoft.EntityFrameworkCore.SqlServer 2.1.1 and it produces HasMaxLength() for varchars

**Comment by mguinness** [comment]
@yukozh Do you have any insight, is it related to MySqlTypeMappingSource at all?
