### ISSUE TITLE
Memory leak "More than twenty 'IServiceProvider' instances warning "

### ISSUE THREAD

**Issue by LMing123** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#668]
### Steps to reproduce
I use this code to add a services, when I run .net core app give me a warning .

> "More than twenty 'IServiceProvider' instances have been created for internal use by Entity Framework. This is commonly caused by injection of a new singleton service instance into every DbContext instance. For example, calling UseLoggerFactory passing in a new instance each time--see https://go.microsoft.com/fwlink/?linkid=869049 for more details. Consider reviewing calls on 'DbContextOptionsBuilder' that may require new service providers to be built."

Meanwhile， every request memory will increase.

This is my code
```C#
services.AddDbContext<GuessWhatContext>(options => 
   options.UseLoggerFactory(MyLoggerFactory).UseMySql(Configuration.GetConnectionString("DB"), 
    mysqlOptions =>
            {
                mysqlOptions
                    .CharSetBehavior(CharSetBehavior.AppendToAllColumns)
                    .AnsiCharSet(CharSet.Latin1)
                    .UnicodeCharSet(CharSet.Utf8mb4);
            }));
```
When I commented out these
```C#
                  mysqlOptions
                      .CharSetBehavior(CharSetBehavior.AppendToAllColumns)
                      .AnsiCharSet(CharSet.Latin1)
                      .UnicodeCharSet(CharSet.Utf8mb4);
```C#
The Problem is disappear.


### Further technical details

MySQL version: MariaDB 10.3
Operating system: Windows 10 17735
Pomelo.EntityFrameworkCore.MySql version: 2.1.1

**Comment by LMing123** [comment]
#619   say it fixed in 2.1.0-rc2-final  but I user version 2.1.1, The issue still exit

**Comment by mguinness** [comment]
@AndriySvyryd Any ideas/suggestions?

**Comment by mguinness** [comment]
@AndriySvyryd Thanks for the fix.

@LMing123 Can you try the [latest build](https://www.myget.org/feed/pomelo/package/nuget/Pomelo.EntityFrameworkCore.MySql/2.1.2-preview1-20180816143335) and let us know if the issue has been resolved?

**Comment by LMing123** [comment]
@mguinness  yeah, the issue has been resolved, thanks ~~
