### ISSUE TITLE
Weird Behavior with FirstOrDefault

### ISSUE THREAD

**Issue by matthewjcooper** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#67]
I have a strange issue with using FirstOrDefault. I have the following methods in my generic repository:

```
   public TEntity FirstOrDefault(Expression<Func<TEntity, bool>> predicate)
        {
            return _entities.FirstOrDefault(predicate); // Option 1
            return _entities.Where(predicate).FirstOrDefault(); // Options 2
            return _entities.Where(predicate).ToList().FirstOrDefault(); // Option 3
        }

     public TEntity SingleOrDefault(Expression<Func<TEntity, bool>> predicate)
        {
            return _entities.SingleOrDefault(predicate);
        }
```

If i call the FirstOrDefault method with option 1 or 2  multiple times for different entities, it works the first time, but the second time it just hangs, almost like the first time through never let go of the transaction or something. I don't see any errors, but the system is just stuck and never finishes.

When i use FirstOrDefault with option 3 it works every time just fine. Also, SingleOrDefault does not seem to have this issue.

Here is the code that is calling it:

```
var gender = _unitOfWork.Gender.FirstOrDefault(g => g.Short == viewModel.Gender); 

var organizationPatientDemographic = _unitOfWork.OrganizationPatientDemographics
                .FirstOrDefault(opd => opd.OrganizationPatientId == session.Visit.OrganizationPatientId);

```

The gender call works, but the demographic call will just hang if using option 1 or 2, but is fine with option 3. And if i swap the order of the calls, demographics works, but gender fails.

Further technical details

MySQL version:  5.7
Operating system: OSX El Capitan
Pomelo.EntityFrameworkCore.MySql version: 1.0.0

I've attached my models, and repositories/unitofwork.

[Code.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/499139/Code.zip)

**Comment by Kagamine** [comment]
Does this issue occur with 1.0.1 prerelease？

**Comment by matthewjcooper** [comment]
I haven’t checked. When I tried the 1.0.1 pre-release I was getting all kinds of errors, and didn’t have time to post tickets and review, as I’m in the middle of a release, so I just rolled back.

**Comment by caleblloyd** [comment]
@matthewjcooper it'd be great to see the issues you are getting from 1.0.1.  We are in the process of trying to harden it, a lot has changed.  It should be far more performant than 1.0.0.

**Comment by matthewjcooper** [comment]
This does seem to be functioning properly under 1.0.1
