### ISSUE TITLE
Update Schedule and Roadmap

### ISSUE THREAD

**Issue by antonioortizpola** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#673]
The section _Schedule and Roadmap_ seems to be a little outdated, it would be great if this get updated, since the date (7/8/2018) seems to be a little outdated and can cause come confusion, since it says "2.1.1", when that version is already in nuget.

This makes the project seems a little abandoned, and does not talk about the plans, issues or release date for next versions.

**Comment by caleblloyd** [comment]
It gets updated when we are working on integrating new upstream release, such as 2.2.0.  Since that's not out yet there's nothing to report.
