### ISSUE TITLE
SaaS应用资源有限的情况下如何自动回收内存使用量

### ISSUE THREAD

**Issue by qibunext** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#675]
```c#
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "2.1.2"
    },
    "configProperties": {
      "System.GC.Concurrent": false,
      "System.GC.Server": false
    }
  }
}
```
SaaS应用资源有限的情况下如何自动回收内存使用量
数据访问使用的是 Entity framework + Pomelo.EntityFrameworkCore.MySql 
服务器配置
2核4G内存
当应用程序运行在.net core 2.0上时内存使用量会缓存增加，但使用量最大化时会自动重启应用程序，会停止一会，（目前只能先用.net core 2.0）
应用程序运行在.net core 2.1上时内存使用量也会缓存增加，使用量最大化时不会自动重启，一直停留在最大的使用量。导致静态文件访问不了，mysql数据库访问也会超时

**Comment by yukozh** [comment]
Please use English to open an issue. thx.
