### ISSUE TITLE
Regression: OnDelete(DeleteBehavior.Restrict) gives "NO ACTION" in mysql

### ISSUE THREAD

**Issue by LordMike** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#684]
Hi,

It seems #506 is back. The change I made in commit 6b4d71b3f36128fc1d2c6b503b09d3983b613087 has been negated by a larger change in f5a1e8845b1db3a62829124ea96906e7e9d99f60, two months later. This later commit changed the text back to `NO ACTION`.

**Comment by LordMike** [comment]
Reading up on this, it seems NO ACTION and RESTRICT are interchangeable in MySQL (https://dba.stackexchange.com/a/14159) - I'd go with RESTRICT anyways because that's what the C# enum is, even though it makes no difference in the end.

**Comment by caleblloyd** [comment]
If they are interchangeable, then will the PR fix the issue?  Or is the root issue something else?

**Comment by LordMike** [comment]
It's a while ago now, so I don't remember the original case that well. It's very likely something else was the root cause, and this was just a convenient stopping point for my troubleshooting :P.
