### ISSUE TITLE
Question：ModelBuilder Property HasColumnType("nvarchar(50)") don't work

### ISSUE THREAD

**Issue by IMJacky** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#688]
### Steps to reproduce
this my code：
`          modelBuilder.Entity<ApplicationUser>(m =>
            {
                m.Property(t => t.UserName)
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                m.Property(t => t.Email)
                        .HasColumnType("nvarchar(50)");

                m.Property(t => t.Password)
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");
            });`

### The issue
when i run project and init database，nvarchar(50) can't set in mysql datafield on "UserName"，instead of varchar(50)，what should i do correctly，ths！

### Further technical details

MySQL version: 8.0.12
Operating system: Windows 7
Pomelo.EntityFrameworkCore.MySql version:2.1.2

**Comment by mguinness** [comment]
See [Cannot create NVARCHAR column in MariaDb/Mysql](https://stackoverflow.com/questions/45708349/cannot-create-nvarchar-column-in-mariadb-mysql).

> NVARCHAR is a synonym for VARCHAR in MySQL/MariaDB. But you need to add the CHARACTER SET utf8mb4 to be sure that you get full UTF-8 support.
