### ISSUE TITLE
Always trying to delete the 'Discriminator' column even if it doesn't exist when migration

### ISSUE THREAD

**Issue by funwaywang** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#690]
### Steps to reproduce
thanks for your work. that's great!
I found a strange problem, I think it is probably a bug.

### The issue
I have two entity classes, defined as follows:
``` c#
public class Person
    {
        public int Id { get; set; }
        [StringLength(50), Required]
        public string Name { get; set; }
    }

  public class Staff : Person
    {
        [StringLength(50)]
        public string Job { get; set; }
    }
```
I want them to generate two separate tables, each containing all the columns, such as "Staffs", which requires 3 columns.
According to the ef core documentation, I made the following settings in the OnModelCreating method:

``` c#
modelBuilder.Entity<Staff>().HasBaseType((Type)null);
```

Then execute 'Add-Migration' on the ps command line to generate the migration code.
The code looks good and the table is created very well:
  
``` c#
migrationBuilder.CreateTable(
                name: "People",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_People", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Staffs",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(maxLength: 50, nullable: false),
                    Job = table.Column<string>(maxLength: 50, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Staffs", x => x.Id);
                });
```

BUT!!!!!
When I later perform Add-Migration to do something else, 
It always generates code, try to delete the 'Discriminator' column even if it doesn't exist. 
``` c#
migrationBuilder.DropColumn(
                name: "Discriminator",
                table: "Staffs");
```
There has never been an 'Discriminator' column here.

### Further technical details

MySQL version: MySQL Community Server - 8.0.11
Operating system: Win10 + VS2017(15.8.5)
Pomelo.EntityFrameworkCore.MySql version: 2.1.2

Other details about my project setup:
this is a asp.net core project, normal project.

thanks again

**Comment by mguinness** [comment]
Per [Inheritance in EF Core](https://www.learnentityframeworkcore.com/inheritance) a "discriminator" column is required to implement the TPH pattern.

**Comment by funwaywang** [comment]
I read the article you suggested, I think I want the TPC pattern, but EF Core has not implemented this yet?

Is there any way to prohibit the "DropColumn(name: "Discriminator"...)" in the migration code? It is obviously wrong, can not be work.

**Comment by mguinness** [comment]
That might be an upstream issue and not in this provider.  If you're determined to proceed with something that isn't supported, then commenting out that code in the generated migration would be an option.

**Comment by simader** [comment]
Did you report this to EF Core?

**Comment by dalen** [comment]
I get this in EF Core 8.0.4 if I use `modelBuilder.Entity<Staff>().HasBaseType((Type)null);`.

The fix is to remove that and instead do `modelBuilder.Entity<Staff>().UseTpcMappingStrategy();`
