### ISSUE TITLE
Scaffolding JSON typed column: Could not find type mapping

### ISSUE THREAD

**Issue by Schaussi** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#693]
### Steps to reproduce

`dotnet ef dbcontext scaffold "server=mysqltest;port=3306;user=xx;password=yy;database=zz" Pomelo.EntityFrameworkCore.MySql -o Models -f`

### The issue

If any table contains a column of type JSON, this column will be skipped.

```
Could not find type mapping for column 'xx.yy' with data type 'json'. Skipping column.
```

### Further technical details

MySQL version: 5.7.22
Operating system: Windows 10 Client, Ubuntu 18 Server
Pomelo.EntityFrameworkCore.MySql version: 2.1.2

Other details about my project setup:
Workaround: Setting JSON typed column to VARCHAR works obviously. However, it would be great if the JSON type would be also supported - or if not, is there a way to simply map it to String type?

Thank you,
regards

**Comment by Schaussi** [comment]
After over a year has passed, will there be a solution or workaround in the near future?

Again, I agree there would be some more background work to cast it to JsonObject etc, but for me it would be enough in most cases if the property type would be simply string.

Is it posisble to define such a custom mapping "MysqlJson" <-> "DotNetString" somewhere?
Thank you

**Comment by lauxjpn** [comment]
We have planned to revise the JSON support for on of our EF Core 3.1 releases. It should make it into 3.2.0 or 3.3.0.

**Comment by mguinness** [comment]
There's already [JSON support](https://www.npgsql.org/efcore/mapping/json.html) in the PostgreSQL provider and there's an open issue to [add support](https://github.com/dotnet/efcore/issues/4021) to the SQL Server provider.  Hopefully this provider can leverage the work done in either of those providers.

**Comment by yokkohsan** [comment]
@lauxjpn It works for me :)
