### ISSUE TITLE
Full text index search

### ISSUE THREAD

**Issue by andyfurniss4** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#706]
Does Pomelo EF Core provide a way of utilising a full text index using the `MATCH...AGAINST` syntax?

I can see there's a `ForMySqlIsFullText()` extension on the index builder but I can't find an explanation of how to actually query using this index.

**Comment by mguinness** [comment]
I don't believe there's much work occurring on FTS in this provider, but there's a lot going on [upstream](https://github.com/aspnet/EntityFrameworkCore/issues/1590).  The typical workaround is to use `FromSql` to query the index.

**Comment by AliA74** [comment]
how to specify full text index on the property of them model ?

**Comment by mguinness** [comment]
@AliA74 Not possible ATM, see https://github.com/aspnet/EntityFrameworkCore/issues/11488.  You'll need to use [Custom SQL](https://www.learnentityframeworkcore.com/migrations#executing-custom-sql).

**Comment by frankyjuang** [comment]
Is `MATCH...AGAINST` supported now?

**Comment by frankyjuang** [comment]
Nice! But too bad. I planed to use it on Chinese data. Just realised the support of Chinese fts is pretty poor.

**Comment by lauxjpn** [comment]
@frankyjuang Yeah, I am not proficient in Chinese, but in Japanese, which (naturally) has similar word boundary problems. I suspect that the boolean mode should work, but I haven't given it a try.

**Comment by ahnseunghae** [comment]
@lauxjpn 
Is it possible to create fulltext index with ngram parser using [IsFullText()](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/3c8e65b02faaef135631896ee2c6113a4bc10bb0/src/EFCore.MySql/Extensions/MySqlIndexBuilderExtensions.cs#L26)?

**Comment by lauxjpn** [comment]
@ahnseunghae Do you mean support for the `WITH PARSER ngram` clause? We currently don't but it is easy to implement if it should be needed. So if this is something you need, just open an issue for it.

As a quick workaround, you could use a command interceptor and just modify the statement, or run a manual `ALTER TABLE CHANGE COLUMN` statement in your migrations.

**Comment by zoran-petrovic-87** [comment]
> @frankyjuang Good timing! @neonVoice is just getting PR #1056 ready to be merged. Should be part of `3.2.0`.

Is this now available? I see that is merged and according to integration tests I should be able to use it as 
` _db.Products.Where(p => p.Name.MatchInBooleanMode("Product*"))`
but MatchInBooleanMode method is not found.

**Comment by mguinness** [comment]
Try `_db.Products.Where(p => EF.Functions.Match(p.Name, "Product", MySqlMatchSearchMode.Boolean))` instead.

**Comment by zoran-petrovic-87** [comment]
> Try `_db.Products.Where(p => EF.Functions.Match(p.Name, "Product*", MySqlMatchSearchMode.Boolean))` instead.

Thank you, works great!
