### ISSUE TITLE
LINQ Query runs fine in LinqPad, but not in code

### ISSUE THREAD

**Issue by JwanKhalaf** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#710]
This is the LINQ code:

```
var journeyId = journeyScoreMessage.JourneyId;

var journey = _accountsAndDevicesContext
    .Journey
    .FirstOrDefault(j => j.JourneyId == journeyId);

if (journey == null)
{
    throw new CannotFindTheJourneyException("cannot find the journey", journeyScoreMessage.JourneyId);
}

var journeyEvents = from ad in _accountsAndDevicesContext.AccelerometerData
                    join ae in _accountsAndDevicesContext.AccelerometerEvents on ad.AccelerometerDataId equals ae
                        .AccelerometerData.AccelerometerDataId
                    where ad.Device.DeviceId == journey.Device.DeviceId && ae.Timestamp >= journey.StartDateTime &&
                          ae.Timestamp <= journey.EndDateTime
                    group ae by new
                    {
                        ae.EventType,
                        ae.Level
                    }
                    into g
                    select new JourneyEvents
                    {
                        EventType = new JourneyEventType { JourneyEventTypeId = g.Key.EventType },
                        Level = g.Key.Level,
                        Count = g.ToList().Count
                    };
```

It runs fine in LINQPad, but when I run it in my .NET Core app with Pomelo driver, I get a `NotSupportedException`. Is there a workaround? I really need the `Count = ` here.

The exception message is:

> System.NotSupportedException: 'Could not parse expression 'g.ToList()': This overload of the method 'System.Linq.Enumerable.ToList' is currently not supported.'

**Comment by takerukoushirou** [comment]
You're explicitly creating a `List` to just get the count. This operation doesn't map to SQL. Have you tried using the LINQ `Count()` method instead, i.e. `Count = g.Count()`? That should be easily translatable.

**Comment by JwanKhalaf** [comment]
I have tried that too, when I do, I get an error with the message:

> Operand should contain 1 column(s)

**Comment by wiredbarb** [comment]
Could you share the concerned model classes / database context setup as well as the MySQL and Pomelo.EntityFrameworkCore.MySql versions? I cannot reproduce this and I am actually curious why you don't get an NRE accessing `journey.Device.DeviceId` since you are not calling `.Include(x => x.Device)` on the query fetching journey.

**Comment by JwanKhalaf** [comment]
Sorry guys, that first error was due to me being stupid. I had forgotten to include the devices like this:

```
var journey = _accountsAndDevicesContext
    .Journey
    .Include(j => j.Device)
    .FirstOrDefault(j => j.JourneyId == journeyId);
```

Now though I get a new error, it says:

> "shortException": "Property 'Int32 DeviceId' is not defined for type 'Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[M2M.JBBCloud.Repository.Model.AccelerometerData,System.Collections.Generic.IEnumerable`1[M2M.JBBCloud.Repository.Model.Device]]'\nParameter name: property System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)"
