### ISSUE TITLE
MySql.Data.Types.MySqlDateTime与DateTime 冲突

### ISSUE THREAD

**Issue by xhl592576605** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#713]
我是使用ef去创建了数据库，然后运行项目时，初始化去生成数据库数据，但是在使用linq查询是就报了下面的错。
System.InvalidOperationException:“An exception occurred while reading a database value for property 'Edition.CreationTime'. The expected type was 'System.DateTime' but the actual value was of type 'MySql.Data.Types.MySqlDateTime'.”

**Comment by IAMRogerXi** [comment]
@xhl592576605 请问是否有简单的代码样例？

@xhl592576605 what's the re-produce steps? Thanks.

**Comment by xhl592576605** [comment]
> @xhl592576605 请问是否有简单的代码样例？以及MySQL版本信息和Pomelo.EntityFrameworkCore版本信息？
> 
> @xhl592576605 what's the re-produce steps? Thanks.

MySQL的版本是5.7的，Pomelo.EntityFrameworkCore是最新的2.1.2，代码样例可以在我的[GitHub](https://github.com/xhl592576605/HANSCore)看到，DBContext的文件在[这里 ](https://github.com/xhl592576605/HANSCore/blob/master/aspnet-core/src/HANSCore.EntityFrameworkCore/EntityFrameworkCore/HANSCoreDbContext.cs)
然后我采用的core框架为[ABP](https://github.com/aspnetboilerplate/aspnetboilerplate)

> @xhl592576605 请问是否有简单的代码样例？以及MySQL版本信息和Pomelo.EntityFrameworkCore版本信息？
> 
> @xhl592576605 what's the re-produce steps? Thanks.

**Comment by xhl592576605** [comment]
@IAMRogerXi 
MySQL的版本是5.7的，Pomelo.EntityFrameworkCore是最新的2.1.2，代码样例可以在我的[GitHub](https://github.com/xhl592576605/HANSCore)看到，DBContext的文件在[这里 ](https://github.com/xhl592576605/HANSCore/blob/master/aspnet-core/src/HANSCore.EntityFrameworkCore/EntityFrameworkCore/HANSCoreDbContext.cs)
然后我采用的core框架为[ABP](https://github.com/aspnetboilerplate/aspnetboilerplate)
重现的步骤，在项目开始运行的时候就会了。数据库时网络服务器的，所以可以运行看看，谢谢！Thanks~
