### ISSUE TITLE
Is Pomelo.EntityFrameworkCore.MySql compatible with EFCore 2.2.0?

### ISSUE THREAD

**Issue by lorenh** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#718]
### The issue
Is Pomelo.EntityFrameworkCore.MySql compatible with EFCore 2.2.0 yet?  

When I tried upgrading and running I saw this:

Method not found: System.Reflection.MethodInfo Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.get_SelectAsyncMethod()

**Comment by noumanbhatti** [comment]
When this will be updated to support .net Core 2.2 features??

specifically looking after EntityFrameworkCore DataProtection feature

**Comment by mguinness** [comment]
As noted in [Call for Contributors](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/522) we are looking for help with maintenance and upgrades.  At this time we can't provide any guidance when this will happen as we haven't evaluated what has changed upstream yet.

**Comment by RayLXing** [comment]
yes  compatible.

**Comment by mguinness** [comment]
Closing this issue as now covered by https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/726.
