### ISSUE TITLE
Slow data load with complex key, one of which is Guid

### ISSUE THREAD

**Issue by NaNgets** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#721]
### The issue
When having an entity which has a complex key, with one of the key's type as Guid, and at least another field which is not in the key - data load takes a long time and loads the DB.

The affected load is a wait called "wait/io/socket/sql/client_connection". I see it specifically spike when I run the code on the MySQL server performance schema.

This does NOT happen when I use .AsNoTracking() on the code.

Example code is given below. The threads are just to load the system, in a normal scenario they shouldn't have a major impact, but in this case there is.

If, for example, I change the `.ToArray()` to `AsNoTracking().ToArray()` - it's OK.
If I change the `.ToArray()` to `.Select(tt => new { tt.NumberField, tt.GuidField, tt.AnotherField }).ToArray()` - it's OK.
If I change the `entity.HasKey(e => new { e.NumberField, e.GuidField } );` to `entity.HasKey(e => e.GuidField);` or `entity.HasKey(e => e.NumberField );` - it's OK.
If I remove the `AnotherField` and only leave the key fields - it's OK.

I don't know why this is, but I'd really like to fix it.
If you can point me to the problematic section, I'd be happy to create a PR.

### Further technical details

MySQL version: 5.7
Operating system: Linux
Pomelo.EntityFrameworkCore.MySql version: 2.1.4

Source code:

```
    public class MyDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var connString = "server=localhost;user id=user;password=password;persistsecurityinfo=True;Charset=utf8mb4;old guids=True;";
                optionsBuilder.UseMySql(connString);
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TestTable>(entity =>
            {
                entity.HasKey(e => new { e.NumberField, e.GuidField } );

                entity.ToTable("testTable");

                entity.Property(e => e.NumberField)
                    .HasColumnName("numberField")
                    .HasColumnType("int(11)");

                entity.Property(e => e.GuidField)
                    .HasColumnName("guidField")
                    .HasColumnType("binary(16)");

                entity.Property(e => e.AnotherField)
                    .HasColumnName("anotherField")
                    .HasColumnType("int(11)");
            });
        }
    }

    public class TestTable
    {
        public int NumberField { get; set; }
        public Guid GuidField { get; set; }
        public int AnotherField { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            for (var i = 0; i < 75; i++)
            {
                new Thread(new ThreadStart(DoSomething2)).Start();
                Thread.Sleep(100);
            }

            Thread.Sleep(100000);

            Console.Read();
        }

        static void DoSomething2()
        {
            using (var db = new MyDbContext())
            {
                Console.WriteLine("Created");

                var tt = db.Set<TestTable>().ToArray();

                Console.WriteLine("Got {0}", tt.Length);
            }
        }
    }
```

**Comment by NaNgets** [comment]
After trying with MySQL's official EFCore package, the problem exists over there as well, so I opened an issue in EFCore's package, assuming this is the common denominator.
I will keep this open in case anyone has any input or this might still be related to this package.

https://github.com/aspnet/EntityFrameworkCore/issues/14202

**Comment by caleblloyd** [comment]
Thanks for the report, we'll close this in favor of the upstream bug.
