### ISSUE TITLE
Is Pomelo.EntityFrameworkCore.MySql  DBFirst  can mapping char(36) to GUID  format with EFCore 2.2.0?

### ISSUE THREAD

**Issue by RayLXing** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#722]
Is Pomelo.EntityFrameworkCore.MySql  DBFirst  can convert GUID  with EFCore 2.2.0?

**Comment by RayLXing** [comment]
char(36)  mapping to string  not  Guid......

**Comment by RayLXing** [comment]
work out： version must use v2.01 or low not newest

**Comment by mguinness** [comment]
Take a look at `GuidFormat` setting in [Connection Options](https://mysql-net.github.io/MySqlConnector/connection-options/#other-options).

**Comment by Neustart** [comment]
I have the same problem. Does somebody find any solution?

**Comment by Neustart** [comment]
@mguinness doesn't work

**Comment by Neustart** [comment]
downgrade to 2.0.1 doesn't work for me as well.
So I have char(32) field in my table, then I scaffold DB context based on that table and I see `string `field in my model. Then I try to read the same table and get an error:
`|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request. System.AggregateException: One or more errors occurred. (An exception occurred while reading a database value for property 'EmailTransactions.EmailId'. The expected type was 'System.String' but the actual value was of type 'System.Guid'.) ---> System.InvalidOperationException: An exception occurred while reading a database value for property 'EmailTransactions.EmailId'. The expected type was 'System.String' but the actual value was of type 'System.Guid'. ---> System.InvalidCastException: Unable to cast object of type 'System.Guid' to type 'System.String'.`

**Comment by mguinness** [comment]
Take a look at `GuidToStringConverter` in EF Core [Built-in converters](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#built-in-converters).

**Comment by Neustart** [comment]
@mguinness can I apply this with DB first approach? I mean it's not ok if I will need to add manually to context class converter once I need to scaffold new context. Probably I missed something. Let me know, please

**Comment by mguinness** [comment]
You'll need to manually add `HasConversion()` to the property in the context class, it won't be scaffolded.

**Comment by plittlewood-rpt** [comment]
@Neustart  how did you resolve this in the end? I've just hit the same problem and can't seem to resolve it using any of the above methods.

**Comment by ijason** [comment]
> @Neustart how did you resolve this in the end? I've just hit the same problem and can't seem to resolve it using any of the above methods.

Did you resolve this?  I'm running into the same issue

**Comment by ijason** [comment]
I added .HasConversion<Guid>() to my DB context and updated my scaffolded classes to use Guid instead of string.  This fixed the issue for me in a DB first approach.

**Comment by RayLXing** [comment]
1. Use  version 2.1.0 of  Microsoft.NETCore.App
2. use  version 2.0.1 of Pomelo.EntityFrameworkCore.MySql






At 2019-08-26 05:18:39, "Jason" <notifications@github.com> wrote:


I added .HasConversion() to my DB context and updated my scaffolded classes to use Guid instead of string. This fixed the issue for me in a DB first approach.
