### ISSUE TITLE
code first生成的数据表名问题

### ISSUE THREAD

**Issue by gaoconggit** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#723]
code first生成的数据表名怎么全小写了。
能以下划线分隔么？
如：
MyTable =》 my_table

现在是生成为mytable了。

database first时。表名以下划线分隔时，生成的model是首字母大写的。
如：
my_table=》MyTable

**Comment by wiredbarb** [comment]
Implement a [custom convention](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/conventions/custom#configuring-types) or directly specify table names per class using [`Table` data annotations](https://docs.microsoft.com/en-us/ef/core/modeling/relational/tables).

**Comment by gaoconggit** [comment]
thank you

**Comment by gaoconggit** [comment]
If it is a naming problem for attributes in an entity class?
The code first mode defaults to the field generated in the database named CamelCase. How to generate underscore separation?

**Comment by wiredbarb** [comment]
Something like this should work for you:
EF 6
```
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
    modelBuilder.Types()
       .Configure(c => c.ToTable(YourCamelCaseToUnderscoreImplementation(c.ClrType.Name)));
    modelBuilder.Properties()
       .Configure(c => c.HasColumnName(YourCamelCaseToUnderscoreImplementation(c.ClrPropertyInfo.Name.ToLower())));
}
```

EF Core
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    foreach (var entity in modelBuilder.Model.GetEntityTypes())
    {
        entity.Relational().TableName = YourCamelCaseToUnderscoreImplementation(entity.Name);
        foreach (var property in entity.GetProperties())
        {
             property.Relational().ColumnName = YourCamelCaseToUnderscoreImplementation(property.Name);
        }
    } 
}
```

Unless you are using EF Core, you may also want to look at [model conventions](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/conventions/model).

**Comment by gaoconggit** [comment]
thank you very much
