### ISSUE TITLE
how to use linq with efcore as using where match the Json type?

### ISSUE THREAD

**Issue by gouhan** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#729]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

### The issue
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
SELECT * FROM shh_admin.t_JsonUserUsualLine
where JSON_CONTAINS(UsualLineJson->'$[*].TargetLocation[*].City', '"GuangZhou"', '$')
```
How to write linq expressions in c# with efcore?
`query = query.Where(o => o.UserUsualLineJson.Object.Any(item =>
                            item.FromLocation != null
                            && item.FromLocation.Any(location => location.City == userSo.City))
                        );`
As above written,It can not work，throws exceptions:
Microsoft.EntityFrameworkCore.Query|The LINQ expression 'where {from UserUsualLine item in [o].UserUsualLineJson.Object where (([item].FromLocation != null) AndAlso {from Location location in [item].FromLocation where ([location].City == __userSo_City_0) select [location] => Any()}) select [item] => Any()}' could not be translated and will be evaluated locally

### Further technical details

MySQL version: 
Operating system: 
Pomelo.EntityFrameworkCore.MySql version:
Microsoft.AspNetCore.App version:

Other details about my project setup:

**Comment by yukozh** [comment]
We have not supported this.
