### ISSUE TITLE
Is there a way to add an info comment before the query?

### ISSUE THREAD

**Issue by facundofarias** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#732]
### Steps to reproduce
It's not an issue, but a nice to have.

### The issue
For example, when I run *SHOW PROCESSLIST* on DataGrip, I can see that the actual query is:
`/* ApplicationName=DataGrip 2018.2 */ SHOW PROCESSLIST`, which is easier for debugging purposes. Is there a way to setup that?
Thanks

### Further technical details

MySQL version: 8.0
Operating system: macOS mojave
Pomelo.EntityFrameworkCore.MySql version: 2.1.2
Microsoft.AspNetCore.App version:

**Comment by mguinness** [comment]
See [Query tags](https://docs.microsoft.com/en-us/ef/core/querying/tags), but our provider doesn't support 2.2 at the moment.
