### ISSUE TITLE
Queryable, multiple Where order inconsistence

### ISSUE THREAD

**Issue by TheTrigger** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#733]
### Steps to reproduce

```
var query = context.SalePoints.AsQueryable();

-> CASE SENSITIVE

query = query.Where(w => user.UserRegions.Select(s => s.RegionId).Contains(w.RegionId))
             .Where(u => u.Name.Contains(terms.Term))

REQUEST lower case
{
	"term":"sale"
}

RESPONSE:
[]


REQUEST capitalized
{
	"term":"Sale"
}

RESPONSE:
[
    {
        "id": 1,
        "name": "Sale point test",
        "regionId": 5,
        "tipologyId": 1,
        "createdAt": "2018-12-30T14:20:09",
        "updatedAt": "2018-12-30T14:20:10"
    }
]





-> CASE INSENSITIVE

query = query.Where(u => u.Name.Contains(terms.Term))
	     .Where(w => user.UserRegions.Select(s => s.RegionId).Contains(w.RegionId))
	
REQUEST:
{
	"term":"sale"
}

RESPONSE:
[
    {
        "id": 1,
        "name": "Sale point test",
        "regionId": 5,
        "tipologyId": 1,
        "createdAt": "2018-12-30T14:20:09",
        "updatedAt": "2018-12-30T14:20:10"
    }
]

```

### The issue
Using two Where on Queyable, one to check the Name and one to find an Id into a collection.
**The `Contains` function becomes case-sensitive**
` query.Where(w => user.UserRegions.Select(s => s.RegionId).Contains(w.RegionId)).Where(u => u.Name.Contains(terms.Term))`

**Here the query is case-insensitive**
` query.Where(u => u.Name.Contains(terms.Term)).Where(w => user.UserRegions.Select(s => s.RegionId).Contains(w.RegionId))`

As you can see i just inverted the order.

### Further technical details

MySQL version: 5.7.20
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.1.4
Microsoft.AspNetCore.App version: 2.2.0 (also tried with 2.1)
Database is scaffolded
`​​Scaffold-DbContext "host=localhost;port=3306;database=promoters;username=root;password=" -Provider Pomelo.EntityFrameworkCore.MySql -OutputDir DbModels -Context PromotersContext -verbose -force`

Other details about my project setup:
`CREATE TABLE `sale_points` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(64) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`vat_number` VARCHAR(11) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`region_id` INT(10) UNSIGNED NOT NULL,
	`tipology_id` INT(10) UNSIGNED NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `vat_number` (`vat_number`),
	INDEX `FK_sale_points_regions` (`region_id`),
	INDEX `FK_sale_points_card_tipology` (`tipology_id`),
	CONSTRAINT `FK_sale_points_card_tipology` FOREIGN KEY (`tipology_id`) REFERENCES `service_tipology` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT `FK_sale_points_regions` FOREIGN KEY (`region_id`) REFERENCES `regions` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
`

**Comment by mguinness** [comment]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/495 and resolution using [EF.Functions.Like()](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-entity-framework-core-2-0/#like-query-operator) method.
