### ISSUE TITLE
Lock row Mysql

### ISSUE THREAD

**Issue by aimprogman** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#741]
Lock row in EF CORE  Database Mysql

I can not implement  following query in EF Core

```
SELECT * FROM person WHERE id=1 FOR UPDATE
```

### Steps to reproduce
I want use it as:

```c#
this._context.Person.FirstOrDefault(a => a.id==1).ForUpdate();
```

**Comment by mguinness** [comment]
Entity Framework provides no support for pessimistic concurrency so you will need to use optimistic concurrency.  Closing issue in lieu of question [Entity Framework Core pessimistic locking row table Mysql](https://stackoverflow.com/questions/54408220/entity-framework-core-pessimistic-locking-row-table-mysql) in SO.

**Comment by aimprogman** [comment]
How can i use  FOR UPDATE without FromSql @mguinness

**Comment by mguinness** [comment]
For EF that's your only option, otherwise drop down to ADO.NET as detailed in [Execute Raw SQL in Entity Framework Core](https://elanderson.net/2016/04/execute-raw-sql-in-entity-framework-core/).
