### ISSUE TITLE
Handling currency in Pomelo

### ISSUE THREAD

**Issue by CRCinAU** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#744]
We're using MariaDB to store some currency fields.

The standard practice in accounting is to make currency DECIMAL(19,4) for normal purposes, or DECIMAL(19,6) if you require further accuracy.

When we've looked at the tables generated by this framework, we notice all the currency fields are of type DECIMAL(65,30) - which is bordering on insane :)

Is there any possibility for improvement on either configuration of these fields, or some kind of mapping to resolve these?

**Comment by caleblloyd** [comment]
Define whatever precision you need https://docs.microsoft.com/en-us/ef/core/modeling/relational/data-types

**Comment by CRCinAU** [comment]
Thanks - I'll pass this on to our guys...
