### ISSUE TITLE
Question: how to use datediff in Pomelo.EntityFrameworkCore.MySql?

### ISSUE THREAD

**Issue by WeihanLi** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#747]
In sql server, I can use `EF.Functions.DateDiffDay` to get two date diff days, how can I get diff days in `Pomelo.EntityFrameworkCore.MySql`?

I'm using Pomelo.EntityFrameworkCore.MySql on version 2.1.4 with mysql 8.0

**Comment by mguinness** [comment]
This function hasn't been implemented in this provider.  A translator for [TIMESTAMPDIFF()](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_timestampdiff) would need to be developed.

**Comment by WeihanLi** [comment]
Thanks @mguinness , is there a plan for it?

**Comment by mguinness** [comment]
Not at this time.  However it's a community project and we welcome contributions, so issue marked correspondingly.

You could also look into [Database scalar function mapping](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0#database-scalar-function-mapping) with an example at [Scalar function mapping](http://anthonygiretti.com/2018/01/11/entity-framework-core-2-scalar-function-mapping/).

**Comment by erolkskn** [comment]
Implemented in #750 . I'm looking forward to your review.
