### ISSUE TITLE
EF Core 2.2.2 - Update database failing, MySQL

### ISSUE THREAD

**Issue by TachyonRSA** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#748]
I currently have EF Core 2.2.2 setup and running in my .NET Core Web API project. I am using `Pomelo.EntityFrameworkCore.MySql` as my MySQL provider for EF Core. I am able to successfully create a new migration for my database but as soon as I run `Update-Database` I am getting the following error:

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '2019-02-23 14:44:41.445486', 'Concentrates', '2019-02-23 14:44:41.445486');

Which is strange since I have been using this migration for a couple of weeks now and run `Update-Database` quite frequently as I drop the database during my development and then re-create it. I have the following code to generate my data that is being seeded that is causing the error:
```
//Seed categories
string[] categories = { "Concentrates", "Food", "Specials & combos", "Clones", "Seeds" };
var catCount = 1;

foreach (var category in categories)
{
    modelBuilder.Entity<Category>().HasData(new Category
    {
        Id = catCount,
        Name = category,
        CreatedAt = DateTime.Now,
        UpdatedAt = DateTime.Now
    });

    catCount++;
}
```

The above is being run in the following method:
`protected override void OnModelCreating(ModelBuilder modelBuilder)`

The model for my categories is defined as follows:
```
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Database.Store
{
    public class Category : BaseEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        public string Name { get; set; }
    }
}
```

With the `BaseEntity` defined as the following:
```
using System;

namespace DataAccessLayer.Database
{
    public abstract class BaseEntity
    {
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }
}
```

The strange thing is, that the generated code that I find in the console I am able to execute in my database tool successfully without error. It generates the following SQL code in the console that I am able to see and execute manually without error:

```
Failed executing DbCommand (277ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
INSERT INTO `Categories` (`Id`, `CreatedAt`, `Name`, `UpdatedAt`)
VALUES (1, '2019-02-23 14:44:41.445486', 'Concentrates', '2019-02-23 14:44:41.445486');
INSERT INTO `Categories` (`Id`, `CreatedAt`, `Name`, `UpdatedAt`)
VALUES (2, '2019-02-23 14:44:41.445485', 'Food', '2019-02-23 14:44:41.445485');
INSERT INTO `Categories` (`Id`, `CreatedAt`, `Name`, `UpdatedAt`)
VALUES (3, '2019-02-23 14:44:41.445484', 'Specials & combos', '2019-02-23 14:44:41.445484');
INSERT INTO `Categories` (`Id`, `CreatedAt`, `Name`, `UpdatedAt`)
VALUES (4, '2019-02-23 14:44:41.445483', 'Clones', '2019-02-23 14:44:41.445483');
INSERT INTO `Categories` (`Id`, `CreatedAt`, `Name`, `UpdatedAt`)
VALUES (5, '2019-02-23 14:44:41.445467', 'Seeds', '2019-02-23 14:44:41.445468');
```

Does anyone possibly have an idea why I am getting the error when I try to run `Update-Database` but am able to successfully manually execute the SQL?

EDIT:
[Here is the StackOverflow question as well.](https://stackoverflow.com/questions/54841874/ef-core-2-2-2-update-database-failing-mysql)

**Comment by mguinness** [comment]
What is the output of `dotnet ef migrations script`?  Also please complete the requested from the new issue template:

MySQL version: 
Operating system: 
Pomelo.EntityFrameworkCore.MySql version:
Microsoft.AspNetCore.App version:

**Comment by TachyonRSA** [comment]
@mguinness - thank you for the reply. Here are the requested details:
MySQL version: 8.0.13
Operating system: Windows 10 Professional 1809
Pomelo.EntityFrameworkCore.MySql version: 2.2.0
Microsoft.AspNetCore.App version: 2.2.2

Here is the affected part of the `dotnet ef migrations script`:
```
INSERT INTO `Categories` (`Id`, `CreatedAt`, `Name`, `UpdatedAt`)
VALUES (5, '2019-02-24 11:54:41.157495', 'Concentrates', '2019-02-24 11:54:41.157495');
INSERT INTO `Categories` (`Id`, `CreatedAt`, `Name`, `UpdatedAt`)
VALUES (4, '2019-02-24 11:54:41.157494', 'Food', '2019-02-24 11:54:41.157494');
INSERT INTO `Categories` (`Id`, `CreatedAt`, `Name`, `UpdatedAt`)
VALUES (3, '2019-02-24 11:54:41.157494', 'Specials & combos', '2019-02-24 11:54:41.157494');
INSERT INTO `Categories` (`Id`, `CreatedAt`, `Name`, `UpdatedAt`)
VALUES (2, '2019-02-24 11:54:41.157492', 'Clones', '2019-02-24 11:54:41.157492');
INSERT INTO `Categories` (`Id`, `CreatedAt`, `Name`, `UpdatedAt`)
VALUES (1, '2019-02-24 11:54:41.157477', 'Seeds', '2019-02-24 11:54:41.157477');
```
And the table creation:
```
CREATE TABLE `Categories` (
    `Id` bigint NOT NULL AUTO_INCREMENT,
    `CreatedAt` datetime(6) NULL,
    `UpdatedAt` datetime(6) NULL,
    `Name` longtext NULL,
    CONSTRAINT `PK_Categories` PRIMARY KEY (`Id`)
);
```

**Comment by TachyonRSA** [comment]
I've just spun up a AWS RDS instance to check if it was the server but the same is happening on the AWS RDS instance.

**Comment by mguinness** [comment]
Maybe use [The General Query Log](https://dev.mysql.com/doc/refman/8.0/en/query-log.html) and share the entire migration to help us see the full picture.

**Comment by TachyonRSA** [comment]
It just started working...... I am absolutely lost for words, just booted my machine this morning ran `Drop-Database` then `Update-Database` and now it worked... Weird as hell, thank you though @mguinness
