### ISSUE TITLE
Align CLR and MySQL Data Types

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#75]
Right now we have a few issues where the MySQL Data Type we are using is not the best type for the CLR DataType.

	CLR Type      Current MySQL Type    Desired MySQL Type
	-------------------------------------------------------------------------------
	ushort        int                   smallint unsigned
	uint          bigint                int unsigned
	ulong         real(20, 0)           bigint unsigned
	char          int                   tinyint
	decimal       decimal(18, 2)        decimal(65, 30)

Additionaly, the `DateTimeOffset` CLR Type does not map to a MySQL type.  The closest we can get is storing a `long` using `DateTimeOffset.ToUnixTimeMilliseconds` and `DateTimeOffset.FromUnixTimeMilliseconds`

I will open a PR that implements the desired mappings and their associated tests.

**Comment by Kagamine** [comment]
thx

**Comment by Emtec** [comment]
Thanks ;) Funny, When I started work on this, You've fixed it
(https://github.com/Emtec/Pomelo.EntityFrameworkCore.MySql/commit/7a714ee33d60f92b150e35008922476a2b3d9444)

For char 
https://github.com/Emtec/MySqlConnector/commit/3af04967cb26f7e3ff6cc070b64c9dd7bd9afddf
https://github.com/Emtec/MySqlConnector/commit/e77496c2f857d81403aa4400f43efc1ace742f9c
