### ISSUE TITLE
Reading Invalid Date column as string

### ISSUE THREAD

**Issue by jespersh** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#761]
This is a question issue.

### Steps to reproduce
A date column with cell values of "1111-11-00", "1111-11-99"

### The issue
The way we've been (ab)using the Date column type certain cell values is like this: "1111-11-00","1111-11-01","1111-11-02",.."1111-11-99". So I'd just want the cell value out as a string and feed it back as a string.
Now this is throwing some expected `MySqlConversionException("Cannot convert MySqlDateTime to DateTime when IsValidDateTime is false.")` for "1111-11-00" and above "1111-11-32"
https://github.com/mysql-net/MySqlConnector/blob/4d2e300ecfbbecf3febe7b3e7faa47246a1a62ab/src/MySqlConnector/MySql.Data.Types/MySqlDateTime.cs#L50-L52

So I had a few ideas which all proved to be bust. I have tried to use:
 * Setting the field to string
 * `.HasConversion()` creates a DateTime before conversion
 * `.HasColumnType("char(11)")` seems to have no effect on its own
 * `.HasComputedColumnSql("CAST(statdate AS CHAR)")` thought this would sort of work until realizing statdate is part of my primary key.

I thought that if I could just read out the value as string, then I could do what I needed to do.

The columntype being set on a per resultset: https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/Core/ResultSet.cs#L122
The value being created as a MySqlDateTime object: https://github.com/mysql-net/MySqlConnector/blob/18ef235c10e2d489cfd11e617ad13997ff41724e/src/MySqlConnector/Core/TextRow.cs#L199-L200

Ideally I'd possibly like to be able to call https://github.com/mysql-net/MySqlConnector/blob/4d2e300ecfbbecf3febe7b3e7faa47246a1a62ab/src/MySqlConnector/MySql.Data.Types/MySqlDateTime.cs#L54 and provide them a pull request that would return the value instead of 0000-00-00, but we don't seem to call this method

Ideas?

### Further technical details

MySQL version: 5.5
Operating system: Windows 10 
Pomelo.EntityFrameworkCore.MySql version: 2.2.0 
Microsoft.AspNetCore.App version:Not used

Other details about my project setup:

**Comment by mguinness** [comment]
Assuming you're using something like [ALLOW_INVALID_DATES](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_allow_invalid_dates) I think you're facing a difficult task.  Possible solutions would be to use [Raw SQL Queries](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql) or [Leveraging ADO.NET](https://www.learnentityframeworkcore.com/raw-sql#leveraging-ado.net-via-the-context.database-property#leveraging-ado.net-via-the-context.database-property) to accomplish what you're trying to do.

**Comment by jespersh** [comment]
I ended up using Raw SQL queries combined with HasConversion. Here's an example for others needing a quick fix:
```C#
public class Status1Statdate
{
	public string ToSave => $"{Year}-{Month}-{Day}";
	public string Danish => $"{Day}-{Month}-{Year}";

	public int Year { get; }
	public int Month { get; }
	public int Day { get; }

	public Status1Statdate(string date)
	{
		if (int.TryParse(date.Substring(0, 4), out int year))
		{
			Year = year;
		}
		if (int.TryParse(date.Substring(5, 2), out int month))
		{
			Month = month;
		}
		if (int.TryParse(date.Substring(8, 2), out int day))
		{
			Day = day;
		}
	}

	// Methods to allow comparing against DateTime objects
	public static bool operator ==(Status1Statdate d1, DateTime d2)
	{
		if (d1 == null) return false;
		return d1.Year == d2.Year && d1.Month == d2.Month && d1.Day == d2.Day;
	}

	public static bool operator !=(Status1Statdate d1, DateTime d2)
	{
		if (d1 == null) return false;
		return !(d1.Year == d2.Year && d1.Month == d2.Month && d1.Day == d2.Day);
	}
}

public partial class Status1
{
	public string Cpr { get; set; }
	public Status1Statdate Statdate { get; set; } // Date in mysql
	public string Stat { get; set; }
}
```

and modelbuilder:
```C#
modelBuilder.Entity<Status1>(entity =>
{
	entity.HasKey(e => new { e.Cpr, e.Statdate })
		.HasName("PRIMARY");

	entity.ToTable("status1");

	entity.HasIndex(e => e.Cpr)
		.HasName("cpr");

	entity.HasIndex(e => e.Statdate)
		.HasName("statdate");

	entity.Property(e => e.Cpr)
		.HasColumnName("cpr")
		.HasColumnType("char(11)");

	entity.Property(e => e.Statdate)
		.HasColumnName("statdate")
		.HasColumnType("char(10)")
		.HasConversion(
				property => property.ToSave,
				column => new Status1Statdate(column)
			);

	entity.Property(e => e.Stat)
		.HasColumnName("stat")
		.HasColumnType("mediumtext");
});
```

Using the entity (wrap a model around if you wish):
```C#
// Load Dental graphics and status dates
DentalStatuses = new ObservableCollection<Status1>(await dbContext
	.Status1.FromSql("SELECT `cpr`,CAST(`statdate` AS CHAR(10)) AS `statdate`,`stat` FROM status1")
	.Where(s => s.Cpr == cpr)
	.OrderByDescending(s => s.Statdate)
	.ToListAsync());
```
