### ISSUE TITLE
StartsWith not properly escaping backslashes for LIKE

### ISSUE THREAD

**Issue by dsyalex** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#763]
### Steps to reproduce
`context.OurTable.Where(c => c.TableField.StartsWith("L\-"));`

### The issue
It produced SQL a bit like this:
```
SELECT `c`.`table_field`
FROM `our_table` AS `c`
WHERE ((`c`.`table_field` LIKE CONCAT('L\-','%') AND (POSITION('L\-' IN `c`.`table_field`) = 1))
```

The problem is that's not a correct translation to SQL, and this will not return the results you'd expect. The backslash in the LIKE should be escaped.
From https://dev.mysql.com/doc/refman/5.6/en/string-comparison-functions.html:
> Because MySQL uses C escape syntax in strings (for example, \n to represent a newline character), you must double any \ that you use in LIKE strings. For example, to search for \n, specify it as \\n. To search for \, specify it as \\\\; this is because the backslashes are stripped once by the parser and again when the pattern match is made, leaving a single backslash to be matched against.

We were unable to work around this by doing the escaping ourselves as that would break the POSITION call which cannot have extra escaping. Also, this POSITION call is redundant.

Instead what we had to do to work around this was base the query on raw SQL that we provide ourselves using FromSql (this part handles the StartsWith properly). This results in SQL being generated that uses our provided SQL query as a subquery.

### Further technical details

MySQL version: 5.6
Operating system: Linux
Pomelo.EntityFrameworkCore.MySql version: 1.1.2
Microsoft.AspNetCore.App version: 1.1.2?

**Comment by mguinness** [comment]
You're using an older version of the library.  Your best bet would be to set [NO_BACKSLASH_ESCAPES](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_backslash_escapes)
in MySQL.
