### ISSUE TITLE
在进行数据迁移的时候，迁移失败，但是还是把数据库的表给删除了。

### ISSUE THREAD

**Issue by WangJunZzz** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#769]
![image](https://user-images.githubusercontent.com/25657426/55374032-b209e300-5539-11e9-9ae4-ea30eb28f39b.png)
都抛出了异常。没有做事务吗？

**Comment by yukozh** [comment]
1. Please use English to communicate in Pomelo Foundation.
2. DDL will trigger commit, so there is no way to do a fast rollback. This is by design. If you have enabled MySQL binlog, you can generate a rollback SQL from it.
