### ISSUE TITLE
'HasKey' is not used for every entity when scaffolding

### ISSUE THREAD

**Issue by gtaranti** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#770]
I'm trying to scaffold from an existing MariaDB database of **26** tables.
Everything works OK, but it's strange that in the dbContext file, the  `HasKey` method is added **only in 6** of them :
i.e.  `entity.HasKey(e => e.CityId).HasName("PRIMARY");`

The other entities, even though their respective tables have their PRIMARY keys, don't get correctly scaffolded and you have to manually add it to them (either via modelBuilder or with the attribute [Key] on the model property)

An interesting thing, is that the `HasKey` method is added correctly to all of the entities  that their tables have a **composite** primary key (3 out of 6 entities correctly scaffolded).
The remaining 3 has normal Primary keys.

MySQL version: 5.5.59
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.2.0
Microsoft.AspNetCore.App version: 2.2.0

**Comment by mguinness** [comment]
Without any examples there's no way to determine what is happening.  The code below collects data on PK's for upstream use.  See if you can determine what why the affected tables aren't being included.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/da58f640f6aa7488644c2d292d41e02e0114386f/src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs#L167-L212

**Comment by gtaranti** [comment]
I've tried the SQL query in my database (substituting TABLE_SCHEMA and TABLE_NAME) and brings back correctly the PRIMARY key of each table.

So it must be something else.

I see in the code that there is a log when it can't find a PRIMARY key.
eg : `Error assigning primary key for {table}.`
When scaffolding inside Visual Studio Package Manager Console through ` Scaffold-DbContext`  I use the `-Verbose` option, but I don't see anything like this log. 

Also here is just an example of two simple tables : 

**status_rating**'s PRIMARY key is correctly found:

`CREATE TABLE `status_rating` (
  `rating_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `color` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`rating_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;`

**city**'s PRIMARY key is not found:

`CREATE TABLE `city` (
  `city_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`city_id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;`

**Comment by mguinness** [comment]
I think that this has to do with [Conventions in EF Core](https://www.learnentityframeworkcore.com/conventions#primary-key).

>If a property is named ID or \<entity name>ID (not case-sensitive), it will be configured as the primary key.

If PK can be inferred then no explicit `HasKey()` is required.

**Comment by gtaranti** [comment]
Maybe this is not the case.

Two reasons :
1. The EFCore convention  should have  treated both the above simple tables the same. But the 1st one **gets** the `HasKey()` method.
2. After the MySQL scaffolding, if you try to create a scaffolded Controller-Views for an entity without the `HasKey()` method In the builder(or the[Key] attribute on the model), then the PRIMARY key of the entity is used as another usual property (no hidden and **editable**)

**Comment by mguinness** [comment]
The first one gets `HasKey()` as it's named rating_id rather than status_rating_id.  Change it to the latter and scaffold again to confirm.
