### ISSUE TITLE
SSL Authentication Error

### ISSUE THREAD

**Issue by Tastanium** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#771]
-sometimes i getting this error on production

{"Title":"Exception Middleware - 5XX","ExceptionObject":"{\"Type\":\"MySql.Data.MySqlClient.MySqlException\",\"Path\":\"/mobile/api/message/all\",\"Message\":\"SSL Authentication Error\",\"InnerMessage\":\"Authentication failed, see inner exception.\",\"StackTrace\":\" at MySqlConnector.Core.ServerSession.InitSslAsync(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, SslProtocols sslProtocols, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\\\\projects\\\\mysqlconnector\\\\src\\\\MySqlConnector\\\\Core\\\\ServerSession.cs:line 1105\\r\\n at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\\\\projects\\\\mysqlconnector\\\\src\\\\MySqlConnector\\\\Core\\\\ServerSession.cs:line 329\\r\\n at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\\\\projects\\\\mysqlconnector\\\\src\\\\MySqlConnector\\\\Core\\\\ConnectionPool.cs:line 112\\r\\n at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\\\\projects\\\\mysqlconnector\\\\src\\\\MySqlConnector\\\\Core\\\\ConnectionPool.cs:line 141\\r\\n at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\\\\projects\\\\mysqlconnector\\\\src\\\\MySqlConnector\\\\MySql.Data.MySqlClient\\\\MySqlConnection.cs:line 431\\r\\n at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\\\\projects\\\\mysqlconnector\\\\src\\\\MySqlConnector\\\\MySql.Data.MySqlClient\\\\MySqlConnection.cs:line 175\\r\\n at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\\\\projects\\\\mysqlconnector\\\\src\\\\MySqlConnector\\\\MySql.Data.MySqlClient\\\\MySqlConnection.cs:line 161\\r\\n at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)\\r\\n at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)\\r\\n at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)\\r\\n at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)\\r\\n at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()\\r\\n at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()\\r\\n at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)\\r\\n at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\\r\\n at Internative.DesktopAPI.Controllers.Mobile.MessageController.All(MessageAllRequest request) in D:\\\\Projects\\\\Internative\\\\GIT\\\\prod-holacon-framework\\\\Internative.DesktopAPI\\\\Controllers\\\\Mobile\\\\MessageController.cs:line 68\\r\\n at lambda_method(Closure , Object , Object[] )\\r\\n at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\\r\\n at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\\r\\n at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\\r\\n at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\\r\\n at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\r\\n at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\\r\\n at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()\\r\\n at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\\r\\n at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\r\\n at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()\\r\\n at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()\\r\\n at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\\r\\n at AspNetCoreRateLimit.ClientRateLimitMiddleware.Invoke(HttpContext httpContext)\\r\\n at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)\\r\\n at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\\r\\n at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)\\r\\n at Internative.DesktopAPI.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\\\\Projects\\\\Internative\\\\GIT\\\\prod-holacon-framework\\\\Internative.DesktopAPI\\\\Middleware\\\\ExceptionMiddleware.cs:line 30\",\"RequestBody\":\"{\\\"id\\\":null}\",\"QueryString\":\"\"}","Id":"08d6b8f1-e3ea-679f-c9bf-f738d02880e8","ContentID":null,"CreateDate":"2019-04-04T11:37:16.9931115+00:00","UpdateDate":"2019-04-04T11:37:16.9931122+00:00","LanguageCode":null,"RecordStatus":0}

```

### Further technical details

MySQL version: 8.0.13
Operating system: windows
Pomelo.EntityFrameworkCore.MySql version: 2.1.4
Microsoft.AspNetCore.App version: 2.1.5

**Comment by mguinness** [comment]
Closing since this exception is from an underlying library.  See [Intermittent SSL Authentication error](https://github.com/mysql-net/MySqlConnector/issues/557) and [Random SSL Authentication Error](https://github.com/mysql-net/MySqlConnector/issues/576) for similar issues.
