### ISSUE TITLE
How MySQL handles Concurrency issues?

### ISSUE THREAD

**Issue by SirwanAfifi** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#772]
Is it necessary to add `RowVersion` field on our models?

```csharp
[Timestamp]
public byte[] RowVersion { set; get; }
```

**Comment by mguinness** [comment]
See [Concurrency Management in EF Core](https://www.learnentityframeworkcore.com/concurrency#adding-a-rowversion-property) and [Only Allow RowVersion on byte[] Columns](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/578).
