### ISSUE TITLE
How should we store DateTimeOffset

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#79]
Reference Material:

- [DateTime vs DateTimeOffset](http://stackoverflow.com/a/14268167/1419658)
- [Storing DateTime (UTC) vs. storing DateTimeOffset](http://stackoverflow.com/a/9314893/1419658)

**Option 1: Convert the DateTimeOffset to UTC DateTime and store that**

Pros
- Sorting and comparison will work in the DBMS
- Will only take 8 bytes of storage space in DBMS

Cons
- The original TimeOffset context will be stripped
- The original timezone context will be stripped

**Option 2: Store a String Representation of DateTimeOffset**

Pros
- The original TimeOffset context will be preserved
- The original timezone context will be preserved

Cons
- Sorting and comparison will not work in DBMS
- Will take at least 33 bytes of storage space in DBMS ("2016-10-10T13:49:58.2065722+00:00")

**Comment by garmiter** [comment]
Whether we can in a way compatible with two kinds of situations? Are stored in different areas, for example, decided to use which one according to the environment, or to identify different storage area according to the function.

**Comment by caleblloyd** [comment]
@garmiter I don't think storing two fields is an option.  EF does a 1-to-1 mapping of properties to database fields.

The caller _can_ implement this behavior themselves by defining a DateTime field and a metadata field with a time offset / time zone.  But that is outside the bounds of this library.

**Comment by garmiter** [comment]
Then use the first one(option 1), because can support the DBMS is more important, keep TimeOffset context, I think we should be able to use similar way to solve this problem.

**Comment by caleblloyd** [comment]
That's also my vote.  I think we should use option 1 but flatten to a DateTime(6) in UTC instead of a long representing the timestamp in milliseconds like currently.  @Kagamine what do you think?

**Comment by Kagamine** [comment]
I always avoid use DateTimeOffset in my project but Identity v3 is using type DateTimeOffset. I dont know what issue will occur when changing the store behavior. I suppose DateTime utc is ok, but need test working with Identity v3.

**Comment by caleblloyd** [comment]
Added Identity V3 to the test bench in #82, but haven't written any specific test cases for them yet.

@Kagamine should the CLR `DateTime` type also map to a `DateTime(6)` on the backend?  Right now we map it to a `DateTime(0)` so it only gets granularity to 1 second instead of 1 microsecond by default.  I think it would be odd to be inconsistent on granularity between CLR `DateTime` and `DateTimeOffset`.

**Comment by softlion** [comment]
I just stumbled upon this problem. Offset information of DateTimeOffset is important when you want to know the time of day in the timezone from where the data originates. For example an event starting at 6pm in many countries from different timezones.

So it should be easy to find with a simple query all dates having the time component at "6pm" WITHOUT flattening to UTC+0. If you flatten the date  to UTC+0 you won't be able to understand that your sells are more likely to happen at 6pm in any country.

For a DateTimeOffset 2 fields are required. As this is not supported in netcore, it should generate an exception in mysql provider, mabe depending on a configuration option.

**Comment by caleblloyd** [comment]
@softlion since this is a MySQL limitation, we made the decision to flatten to UTC instead of throw an Exception so that we degrade gracefully.

Users who want the full functionality of `DateTimeOffset` are better off serializing it before save and deserializing it on load, or as you mentioned splitting it out into a `DateTime` and `Offset` field and reassembling the `DateTimeOffset` in C#

**Comment by softlion** [comment]
They are so retarded in mysql world ... At least 6 years behind.
