### ISSUE TITLE
Scaffolding not working - Returns Unable to find provider assembly with name Pomelo.EntityFrameworkCore.MySql Error

### ISSUE THREAD

**Issue by krishan0630** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#790]
### Steps to reproduce
I created an ASP.Net Core API project in VS 2017 and Added .Net Core Class library. Then I installed following nuggets inside the class library. (i need to use this class library as a DAL)

> Pomelo.EntityFrameworkCore.MySql
> 
> Pomelo.EntityFrameworkCore.MySql.Design

I have an existing database. so i need to generate ModelClasses using Database first approach.

So I executed the following command in the package manager console (Web API project name is Test & Class Library name is DAL). I set the DAL as my default project in the package manager console

> `dotnet ef dbcontext scaffold "server=localhost;port=3306;user=root;password=abc123;database=test;" Pomelo.EntityFrameworkCore.MySql -o Models -p DAL -s Test`

after executing this command im getting following error.
`
Unable to find provider assembly with name Pomelo.EntityFrameworkCore.MySql. Ensure the specified name is correct and is referenced by the project.`
I tried to find a solution for this and I was unable to find it. What am I doing wrong?

### Further technical details

MySQL version: 5.7.21
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.2.0
Microsoft.AspNetCore.App version: 2.1.1

**Comment by caleblloyd** [comment]
You need to use .NET Core 2.2 with Poemlo 2.2
