### ISSUE TITLE
Amazon Aurora

### ISSUE THREAD

**Issue by tphillips** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#791]
### Steps to reproduce
Create an EF migration and attempt to run against MySQL Aurora Serverless

### The issue
EF Migration scripts are just hanging, as are other commands:

info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.11-servicing-32099 initialized 'Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (21ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='SalaryAdvanceEmployerInfo' AND TABLE_NAME='__EFMigrationsHistory';

<And it hangs, forever>

### Further technical details

MySQL version: Aurora Serverless
Operating system: Docker containers (FROM dotnet:2.1-sdk) on Ubuntu host talking to Aurora 
Pomelo.EntityFrameworkCore.MySql version:
Microsoft.AspNetCore.App version:

Using the mysql client cli we can connect perfectly.

This has happened overnight and is affecting all our services in dev / prod /test so it's likely an Aurora change...

**Comment by tphillips** [comment]
Turns out we had to disable connection pooling "Pooling=false;". Not sure if this is an Aurora or Pomelo issue...

**Comment by yukozh** [comment]
This is an ADO layer issue, please move to MySqlConnector.

**Comment by chazt3n** [comment]
@yukozh are you saying Pomelo won't work?
Will it ever work? we have some services working, just having issues with migrations.

**Comment by karuakun** [comment]
Same problem.
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1617
