### ISSUE TITLE
Skip logging when catching exception

### ISSUE THREAD

**Issue by corte** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#793]
### Steps to reproduce
When I add an entity which has a Unique key and treat the error in a try-catch block, I still get the error logged, which is polluting the logs with errors that are actually handled.

Example:
```
Material material = null;
try
{
    material = dbContext.Set<Material>().Add(new Material {
        MaterialNumber = 101010,
        Description = "Wood"
    });
    dbContext.SaveChanges();
}
catch (DbUpdateException) // Unique key violated
{
    dbContext.Entry(material).State = EntityState.Detached;
    material = dbContext.Set<Material>()
        .FirstOrDefault(mat => mat.MaterialNumber == 101010);
}
return material;
```

And still get errors in the logs:

> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '101010' for key 'IX_Material_MaterialNumber'

### The issue
Entity framework core don't have any form of validation, leaving it to the database, server or client to handle. My guess is that Pomelo is logging the errors while saving changes even if I am treating it in the server.

I don't know if that's possible, but it would be good to have a way to tell Pomelo that the error is handled and we don't need to pollute the logs with misinformation.

### Further technical details

MySQL version: 5.7
Operating system: Windows 10 and Linux docker image: mcr.microsoft.com/dotnet/core/aspnet:2.2
Pomelo.EntityFrameworkCore.MySql version: 2.2.0
Microsoft.AspNetCore.App version: 2.2

**Comment by lauxjpn** [comment]
There isn't any Pomelo specific logic, that logs exceptions. This is all handled by EF Core itself.
Since the logging facility can be controlled from your `DbContext` derived implementation, you can always add a property for tuning it (or part of it) off or just filter out the irrelevant messages.

See the [official documentation](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging?tabs=v3) for general details.
