### ISSUE TITLE
Ship update in sync with MySqlConnector 0.57.0

### ISSUE THREAD

**Issue by bgrainger** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#794]
In https://github.com/mysql-net/MySqlConnector/issues/642, I am implementing some new "Async" methods that are coming in .NET Core 3.0.

I'd also like to change the method definitions of some existing async methods to be consistent with .NET Core 3; however, **this will be a breaking change**. (It's currently in beta, and hasn't shipped in a stable release.)

I think this can be mitigated if an update to Pomelo.EntityFrameworkCore.MySql that depends on MySqlConnector 0.57.0 is shipped as soon as MySqlConnector 0.57.0 is available.

Is it possible that you would be able to ship 2.2.1 (or 2.3.0?) with this updated dependency and we could synchronise ship dates? There are no source-breaking changes; the code of 2.2.0 just needs to be recompiled against an updated MySqlConnector.

**Comment by bgrainger** [comment]
@caleblloyd If I made a commit based on c58e00c7b3b6bc8f2eeffebd4d10f2e1ff16b790 that updated MySqlConnector and set the version to 2.2.1, would you be OK with shipping that (and be able to)?

**Comment by caleblloyd** [comment]
@bgrainger yes, I could do that!

**Comment by bgrainger** [comment]
@caleblloyd It looks like commits on the `2.2.1` branch https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/commits/2.2.1 are no longer building automatically; possibly due to 7428ab99f65cd183b04e612d8784f51f99020579.

The tip of that branch should be ready to publish as v2.2.1 (mostly just an update to MySqlConnector 0.57.0); what's the best way to get it published?

**Comment by bgrainger** [comment]
@caleblloyd Are we waiting on changes in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/824#issuecomment-536019575 before a 2.2.1 package can be published? (No hurry, just making sure I understand the plan.)

**Comment by caleblloyd** [comment]
Sorry missed these comments. 2.2.6 work superceded 2.2.1 before it was released, and 2.2.6 is now published

**Comment by bgrainger** [comment]
2.2.6 has solved this problem (and no one complained about a binary ABI incompatibility anyway...).
