### ISSUE TITLE
Unable to make use of the .ForMySqlUseSequenceHiLo() method

### ISSUE THREAD

**Issue by bison92** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#798]
### Steps to reproduce
I'm trying to use `.ForMySqlUseSequenceHiLo()` in my modelbuilder.  I'm seeing its defined here 

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/42c335ceac6d93d1c0487ef45fc992810c07fd9d/upstream/EFCore.Upstream/Extensions/MySqlModelBuilderExtensions.cs#L24-L47

and used here:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/ddf8b77e6f58f3915dd170ea1de73755a7b3cae6/upstream/EFCore.Upstream.Tests/Metadata/MySqlBuilderExtensionsTest.cs#L1019-L1037

this is from a commit from May 2018, I was expecting this to be available on July 2019 we're at.

### The issue
I'm unable to access this functionality, Is this working? If so, How I'm supposed to make use of it?

### Further technical details

MySQL version: MariaDB 10.3
Operating system: Windows 10 v1809 x64
Pomelo.EntityFrameworkCore.MySql version: 2.2.0
Microsoft.AspNetCore.App version:2.2.0

Thank you.

**Comment by crozone** [comment]
What exactly isn't working?

Can you please post the generated C# migration code (notably the `migrationBuilder.AddColumn()` method) as well as the generated SQL (using `dotnet ef migrations script`)?

Does the `migrationBuilder.AddColumn()` method have its `defaultValue` parameter set?

**Comment by bison92** [comment]
Well It doesn't compile. I'm unable to _make use of_ **ForMySqlUseSequenceHiLo** on my DBContext. I'm trying to use it on a property as I see it's done in the test.

![imagen](https://user-images.githubusercontent.com/1010516/61458972-03fd3a00-a96c-11e9-8f24-93af187fe78c.png)

**Comment by caleblloyd** [comment]
The `upstream/` folder is a port of SQL Server code with variables renamed for MySQL. It does not build, it is just used as a reference for what changes from release to release.

The real provider code lives in `src/`

HiLo is not supported in this provider, see previous discussion in #477
