### ISSUE TITLE
Generated Id not updating

### ISSUE THREAD

**Issue by Mats391** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#80]
Not sure if this is an EF Core issue or adapter. According to http://ef.readthedocs.io/en/latest/modeling/generated-properties.html#value-generated-on-add EF core should update the Id when adding an entity into the context to a temporary value and get the correct from the database on SaveChanges().

### Steps to reproduce
Create an entity model with auto increment Id. 
Create new object and add it into DB context.
Check Id before adding, before saving and after saving.
In my case:
Before adding: Id=0
After adding: Id=-2147482645
After saving: Id=-2147482645
In DB: Id=1

### The issue
The object gets temporary Id assigned -2147482645 after getting added to the context. Once SaveChanges is called it should be updated to the correct Id it got assigned by the DB. This is not happening. 

### Further technical details
Using ASP Web API with injected DB context/Repository. Not sure if relevant.

Pomelo.EntityFrameworkCore.MySql version: "1.0.1-prerelease-10013"

**Comment by caleblloyd** [comment]
Are you using a `uint` for your ID? If so, can you try using an `int`?

If this is the issue, the bug resides in the MySql Driver, and is something that is also present in Oracle's MySql Driver.

**Comment by Mats391** [comment]
I am using `int`. Thats why it turns to `-2147482645`. 
I tried it in a small console app now and it updated correctly. Will let you know if I screwed up or injected DB are the problem.

**Comment by Mats391** [comment]
I am an idiot. Sorry for bothering you.

**Comment by caleblloyd** [comment]
What did the issue end up being, just a misconfiguration?  No problem, keep opening bugs when you think you find issues.  We're trying to harden 1.0.1 and it really helps when people submit issues!

**Comment by Kagamine** [comment]
A generated ID must be another model FK, in other fiels which is not FK will be -2147xxx

**Comment by Mats391** [comment]
In the repository I had a call by value instead of reference. Starring at code too long can make you blind.
