### ISSUE TITLE
AWS Lambda connection count issue

### ISSUE THREAD

**Issue by sarkarstanmoy** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#804]
### Steps to reproduce
In Startup file:
services.AddDbContext<TeamDbContext>((optionsBuilder) =>
            {
                optionsBuilder.UseMySql(Configuration["ConnectionString:db-app"]);
            });

public class LambdaFunction : Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
    {
        protected override void Init(IWebHostBuilder builder)
        {
            builder
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseStartup<Startup>()
                .UseLambdaServer();
        }
    }
### The issue
We are using Lambda's which are deployed in VPC to connect RDS instance which is again hosted in private subnet. We are using .Net Core 2.1, Pomelo.EntityFrameworkCore.MySql 2.2.4 version for Entity framework and MySql database. Currently, for one environment we are using 14 Lambda functions. The issue we are facing is RDS connection keeps on increasing and it went upto 70 connections for one user. If we stopped using lambda's then the connection count slowly coming down. Need your suggestions on how to minimize the database connection count and improve performance.
```
Exception message:
Stack trace:
```

### Further technical details

MySQL version: 5.6.41
Operating system: Lambda container
Pomelo.EntityFrameworkCore.MySql version: 2.2.4
Microsoft.AspNetCore.App version: 2.1

Other details about my project setup:

**Comment by liguobao** [comment]
use  AddDbContextPool?
```csharp
services.AddDbContextPool<EventDataContext>(options =>
          {
              options.UseMySql(Configuration["MySQLString"].ToString());
          });
```

but your app if AWS func, the state not in pool.

**Comment by sarkarstanmoy** [comment]
I have used AddDbContextPool with no success. The default count for DbContextPool is 128. But every time API get's called from API Gateway new container is getting created and new connection pool got initialized. How can I share connection object within lambda containers?

**Comment by bgrainger** [comment]
Would it help to specify `Pooling=false` in your connection string to completely bypass connection pooling? That way, connections won't stay alive (in the pool) once they're closed.

**Comment by caleblloyd** [comment]
Lambda will spin multiple containers up but will also re-use the same container for multiple requests.

You'll have to tune connection pooling settings.  You can try disabling pooling as @bgrainger recommends or you could use pooling with a lower `Max Pool Size` and `Connection Idle Timeout`

https://mysqlconnector.net/connection-options/
