### ISSUE TITLE
How to configure ON UPDATE on Foreign Key constraint using Fluent API

### ISSUE THREAD

**Issue by coultonluke** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#807]
### Steps to reproduce
I have the following configuration for a foreign key relationship for one of my tables, I have configured the ON DELETE value:

```
builder.HasOne(t => t.Quiz)
    .WithMany(t => t.MostActiveQuizzes)
    .HasForeignKey(d => d.QuizId)
    .HasConstraintName("FK_MostActiveQuiz_Quiz_QuizId")
    .OnDelete(DeleteBehavior.Cascade);
```

However, I can't configure the ON UPDATE property in the same way, for illustration purposes:

```
builder.HasOne(t => t.Quiz)
    .WithMany(t => t.MostActiveQuizzes)
    .HasForeignKey(d => d.QuizId)
    .HasConstraintName("FK_MostActiveQuiz_Quiz_QuizId")
    .OnDelete(DeleteBehavior.Cascade)
    .OnUpdate(UpdateBehavior.Cascade); // ???
```

### The issue
It is possible to configure the ON DELETE value for a foreign key using the Fluent API, but it doesn't appear to be possible to configure the ON UPDATE value.

Is there a way to do this, or is there a reason that this isn't possible?

I could always add these in to the migration code that has been created, but I'm not sure whether that's a good thing to do...

### Further technical details

MySQL version: 5.7.24
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.2.0
Microsoft.AspNetCore.App version: 

Other details about my project setup:

**Comment by lauxjpn** [comment]
There is no support for `ON UPDATE` in EF Core at the moment. There is however support for `ON UPDATE` for migrations according to this [question on StackOverflow](https://stackoverflow.com/a/53327574/2618319).

(Most of the time `ON UPDATE CASCADE` can be considered a design smell and could be an indication to redesign the model, as primary keys should generally not be changed after they have been set.)

**Comment by ivanmem** [comment]
Can you add support for at least configuration in the model? I don’t want to change it manually through phpmyadmin.
![image](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/assets/33786293/53a5d040-0829-467a-9254-00ce88b4edb0)
My project does not require good architecture.

**Comment by roji** [comment]
@ivanmem that requires EF-side support (tracked by https://github.com/dotnet/efcore/issues/21563). You should be able to edit your migration and integrated the necessary DDL to add the ON UPDATE behavior ([migration docs](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#adding-raw-sql)).
