### ISSUE TITLE
How to generated the auto increatement column in mysql

### ISSUE THREAD

**Issue by pointch** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#808]
How to generated the auto increatement column in mysql database,  it seem that [DatabaseGenerated(DatabaseGeneratedOption.Identity)] is  not useful

**Comment by coultonluke** [comment]
Mine works by just specifying a primary key of type `int`:

**Fluent Configuration:**
```
// Primary Key
builder.HasKey(t => t.Id);
```

**Object:**
```
public class MyClass {
    public int Id { get; set; }
}
```

**Comment by pointch** [comment]
I find the reason, deleted the older migration files by sql server and add new migration, then update database, finally it works.  thanks.

**Comment by SpringHgui** [comment]
![image](https://github.com/user-attachments/assets/3685efb1-d7e3-413b-bb15-457a8f9a1ab1)
![image](https://github.com/user-attachments/assets/90f14883-2208-4d25-95ef-c6260608400b)
not work ！！！

mysql 8.0.28
Pomelo.EntityFrameworkCore.MySql 8.0.2

**Comment by lauxjpn** [comment]
@SpringHgui Feel free to create a new issue. Also, please don't post screenshots. Post the source code instead, so it can easily be copy and pasted by us to reproduce the issue you are having. Thanks!
