### ISSUE TITLE
Migration Transaction not used

### ISSUE THREAD

**Issue by WangJunZzz** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#812]
I'm moving Database.Migration data failed.But No part of failure succeeds.Shouldn't it be business together?

```c#
Duplicate key name 'IX_SocialOrderInfoCategoryDetail_ApplyDetailId1'
# The last migration was unsuccessful and did change the index name of the database.
```
### Further technical details
EF Core version: 2.2.0"
Database Provider: Mysql5.7
Operating system: 
IDE: (e.g. Visual Studio 2019)

**Comment by lauxjpn** [comment]
I am not sure I fully understand the exact issue.

If you are using idempotent migrations, the following discussion about this issue exists for EF Core: https://github.com/aspnet/EntityFrameworkCore/issues/7681

If you are using normal (non-idempotent) migrations, they should be wrapped in a transaction automatically.

If you are using normal (non-idempotent) migrations and explicitly start a transaction, the following discussion about this issue exists for EF Core:
https://github.com/aspnet/EntityFrameworkCore/issues/12325

If this does not resolve your issue, please describe it in more detail.

**Comment by kanadaj** [comment]
@lauxjpn I'm wondering about this issue. MySQL doesn't support transactions for DDL commands and they automatically trigger COMMIT internally, so a failed migration leaves the database in a half-failed state. See https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html.

It feels like Pomelo's migration system should either automatically roll back the failed changes by generating inverse statements to all successful statements, or run the Down() method with try-catch

**Comment by lauxjpn** [comment]
>MySQL and MariaDB doesn't support transactions for DDL commands and they automatically trigger COMMIT internally, so a failed migration leaves the database in a half-failed state.

That's correct. I usually advocate to backup the database before applying migrations and to restore it if something goes wrong.

>[...] or run the Down() method with try-catch

This won't work, because calling `Down()` would run _all_ reverse actions, which would be incorrect, because not all `Up()` operations were executed. So this would throw and/or result in a database left in an unpredictable state.
