### ISSUE TITLE
Support for GSSAPI

### ISSUE THREAD

**Issue by alexrait** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#813]
On windows server/client I am trying to use the gssapi_auth (Kerberos,NTLM)

Looks like it is not supported, I get this message:
Authentication method 'auth_gssapi_client' is not supported

The new versions of MySqlConnector do support this type of authentication.

**Comment by bgrainger** [comment]
Pomelo.EntityFrameworkCore.MySql 2.2.0 depends on MySqlConnector 0.49.2, which should support `auth_gssapi_client`.

What versions are you running? What's the OS of your client and .NET Framework version? What's the full call stack from the exception?

**Comment by lauxjpn** [comment]
Closed due to lack of information.
@alexrait We reopen this, when you provide the additional details.
