### ISSUE TITLE
Connection string does not support "allowloadlocalinfile"

### ISSUE THREAD

**Issue by billsking** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#816]
When implementing batch import function,LOAD DATA was used, but an error occurred。[This is the official recommended way to use it](https://dev.mysql.com/doc/refman/5.7/en/load-data.html#load-data-input-file)，But you need to add "allowloadlocalinfile" to the connection string，Using mysql.data is correct.With Pomelo.EntityFrameworkCore.MySql, however, allowloadlocalinfile is not supported for a newspaper。

ArgumentException: Option allowloadlocalinfile not supported.

**Comment by bgrainger** [comment]
`AllowLoadLocalInfile` was added in the underlying MySQL library in MySqlConnector 0.55.0: https://github.com/mysql-net/MySqlConnector/issues/643

(Before that, it wasn't necessary to specify it.)

Make sure you're using MySqlConnector 0.55.0 or later, installing it manually in your top-level project if necessary.

See https://mysqlconnector.net/troubleshooting/load-data-local-infile/ for more information.
