### ISSUE TITLE
How to use DELIMITER in raw sql statements 

### ISSUE THREAD

**Issue by findmoon** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#817]
I want create a trigger use raw sql，this sql as：

```sql
DELIMITER $$   
CREATE OR REPLACE TRIGGER platformdb.trig_updatevehiclekilometer
    AFTER UPDATE ON platformdb.VehicleTravels FOR EACH ROW 
    BEGIN
        UPDATE Vehicles SET TotalKilometers=new.Kilometers WHERE ID=new.VehicleId;
    END$$
DELIMITER ;
```
Executed in mariadb is no problem, but the raw sql query using EF core will report a DELIMITER  error, as follows

```
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELIMITER $$ CREATE OR REPLACE TRIGGER platformdb.trig_updatevehiclekilometer  A' at line 1 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELIMITER $$ CREATE OR REPLACE TRIGGER platformdb.trig_updatevehiclekilometer  A' at line 1
```
use `DELIMITER $$;` as same error 

So,how to Execut raw sql with `DELIMITER `，or what alternatives? 

Please，thanks！

**Comment by bgrainger** [comment]
`DELIMITER $$` is for MySQL Workbench. In C# code, just create a `MySqlCommand` with the full command text and execute it:

```csharp
using (var command = new MySqlCommand(@"CREATE OR REPLACE TRIGGER platformdb.trig_updatevehiclekilometer
    AFTER UPDATE ON platformdb.VehicleTravels FOR EACH ROW 
    BEGIN
        UPDATE Vehicles SET TotalKilometers=new.Kilometers WHERE ID=new.VehicleId;
    END", connection))
{
    command.ExecuteNonQuery();
}
```

**Comment by bgrainger** [comment]
See https://github.com/mysql-net/MySqlConnector/issues/645.

**Comment by findmoon** [comment]
> `DELIMITER $$` is for MySQL Workbench. In C# code, just create a `MySqlCommand` with the full command text and execute it:
> 
> ```cs
> using (var command = new MySqlCommand(@"CREATE OR REPLACE TRIGGER platformdb.trig_updatevehiclekilometer
>     AFTER UPDATE ON platformdb.VehicleTravels FOR EACH ROW 
>     BEGIN
>         UPDATE Vehicles SET TotalKilometers=new.Kilometers WHERE ID=new.VehicleId;
>     END", connection))
> {
>     command.ExecuteNonQuery();
> }
> ```

Thank you, this's very useful for me。非常感谢！

**Comment by rhaynes123** [comment]
Just wanted to leave a comment here as this helped address an issue I add with a MySQL migration and hope it adds value to anyone in the future. I had a migration script that looked like this 

protected override void Up(MigrationBuilder migrationBuilder)
        {

            string sql = @" USE TimePunch;
                        DROP procedure IF EXISTS GetAllTimePunches;

                        DELIMITER //
                        
                        CREATE PROCEDURE GetAllPunches ()
                        BEGIN
	                        SELECT * FROM TimeClock.TimePunches;
                        END//

                        DELIMITER ;
                        
                        ";

            migrationBuilder.Sql(sql);
        }

After reading this I adjust the Migration to the below and it was successful 

protected override void Up(MigrationBuilder migrationBuilder)
        {
           
            string sql = @"CREATE PROCEDURE GetAllTimePunches ()
                        BEGIN

                            SELECT * FROM TimeClock.TimePunches; END";

            migrationBuilder.Sql(sql);
           
        }
