### ISSUE TITLE
Use Azure DevOps for CI

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#824]
Currently Travis CI is only able to run a subset of tests because it was hanging when running the full test suite

It also looks like the AppVeyor configuration needs some work as it will show passing even with failing tests

Azure DevOps is now free for open source and has the capability to run both Linux and Windows builds

Explore moving CI and Release functionality to AZDO

- [x] Move Windows/Linux builds from AppVeyor/TravisCI to AZDO
- [x] Move nightly builds from MyGet to AZDO Feed

**Comment by caleblloyd** [comment]
I created an AZDO org and public project:  https://dev.azure.com/pomelo-efcore/Pomelo.EntityFrameworkCore.MySql/

Also created a service account that only has access to this repository that links to AZDO: @pomelo-efcore-sa 

Will work on `feature_azdo` branch and integrate in #823

**Comment by bgrainger** [comment]
ICYMI MySqlConnector has a fair amount of Azure Pipelines YAML that might contain useful snippets: https://github.com/mysql-net/MySqlConnector/blob/master/azure-pipelines.yml

**Comment by caleblloyd** [comment]
CI has been lifted from AppVeyor/Travis to AZDO

Still need to add automatic releases from `master` and `*-wip` branches.  AZDO feed will replace MyGet feed.

**Comment by caleblloyd** [comment]
Packages moved to nightly feed in #828

- Packages for branches ending in `-wip` will be published to nightly feed if they pass or fail CI
- Packages for `master` will be published to nightly feed ONLY if they pass CI
- Packages for tagged releases will be published to the nightly feed.  Will add an integration to push them to NuGet shortly

**Comment by lauxjpn** [comment]
At the moment, merging a PR with a `-wip` branch is still blocked, when tests in CI fail.
This should probably be handled, so there is no need to comment out not yet working tests anymore.
See #838

**Comment by caleblloyd** [comment]
`master` should not have failing tests, they should be fixed or skipped. otherwise there is no easy way to tell if there are regressions.

**Comment by lauxjpn** [comment]
I agree, but any `-wip` branch should be allowed to. After all, it's still work in progress.

**Comment by caleblloyd** [comment]
Yes wip branches can have failing CI. Are you saying GitHub is blocking merges into the wip branch? I merged the arcade PR without any problem... Maybe a permission thing?

**Comment by lauxjpn** [comment]
Actually, i can merge it now. Maybe I just thought I couldn't?
