### ISSUE TITLE
Expected MySqlOptions.ServerVersion behavior

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#832]
What is the expected behavior, if `MySqlOptions.ServerVersion` does not get set at all?
Should we assume a default version and database type or should we throw an exception, with a clear message to set it up first before creating a `DbContext` or so?

There might also be the need for a convenient `AutoDetectServerVersion` method (or specially from `ServerVersion` derived class), that queries `@@version` or `VERSION()`, before the first query gets translated (or maybe just when a database connection gets opened).

**Comment by bgrainger** [comment]
The server sends its version to the client during the initial handshake, so it's available in the `MySqlConnection.ServerVersion` property after `Open` (or `OpenAsync`); no need to `SELECT @@version`.

**Comment by caleblloyd** [comment]
I think behavior should be default to latest GA MySQL.  Most of the features we differentiate before are MySQL 5.6 pre-json support, MySQL 5.7 post-json support, and MariaDB.

We use the server version mainly to create migrations.  In the past we did detect server version from the server.  But usually migrations are being created on a developer machine and should not depend on a DB Connection (or the developer DB may not be the same version as the prod DB).

Original issue was #272 and change was #576

**Comment by lauxjpn** [comment]
>I think behavior should be default to latest GA MySQL.

It's a reasonable approach.

The only counterpoint I can possibly see is, that for someone who missed to set the `ServerVersion` explicitly, a Pomelo update could suddenly change application behavior.
Throwing when neither a `ServerVersion` nor some autodetection has been set, would prevent this scenario.

>We use the server version mainly to create migrations.

Because of client eval being disabled by default as of 3.0, a couple of features, that previously depended on that, will suddenly not work by default.

Because of that, I leveraged some functionality like `LATERAL` etc., that is only available in newer versions.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/7b2c81b04308134f795ec1de93fdc033cbbaf032/src/EFCore.MySql/Query/Internal/MySqlQuerySqlGenerator.cs#L219-L231

Also, we check against the `ServerVersion` for actual `CONVERT` to `double` and `float` conversion support in MySQL with 3.0.0.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/7b2c81b04308134f795ec1de93fdc033cbbaf032/src/EFCore.MySql/Query/Internal/MySqlQueryableMethodTranslatingExpressionVisitor.cs#L30-L41

**Comment by lauxjpn** [comment]
@bgrainger Great insight! That would make an auto-detect feature trivial to implement.

**Comment by lauxjpn** [comment]
I think we should then use auto detection as the default for 3.0.
