### ISSUE TITLE
DatabaseGenerated Identity

### ISSUE THREAD

**Issue by EliasDerHai** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#835]
### Steps to reproduce
Generate Uuid for pk via

````
[Key]
[StringLength(40)]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
public Guid Uuid { get; set; }
````
### The issue
No Uuid generated when Inserting new Db-Entry on DB-manually

### Further technical details
MySQL version: 8.0.13
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.20
Microsoft.AspNetCore.App version: 2.2.0

**Comment by lauxjpn** [comment]
This seems to be related: https://github.com/aspnet/EntityFrameworkCore/issues/14518

As far as I can see, at this point in time, you have two options:

1. Create the Guid in your code, before calling `SaveChanges`:
```c#
myObject.Uuid = Guid.NewGuid();
```
2. Use a default value on the column for generating the `Guid`:
```c#
modelBuilder.Entity<MyEntity>()
    .Property(e => e.Uuid)
    .HasDefaultValueSql("uuid()"); // or maybe "(uuid())"?
```

**Comment by jotatoledo** [comment]
Had a similar issue using:

<TargetFramework>netcoreapp3.1</TargetFramework>
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.1.1" />
MySQL 8.0

UUID was not being generated for a alternative-key column, the value was always `Guid.Empty`

I solved it by using:

```
builder.Property(t => t.Id) // type of Id is Guid
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("(uuid())");
```
