### ISSUE TITLE
OnDelete Behaviour not Set as Specified

### ISSUE THREAD

**Issue by EliasDerHai** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#837]
### Steps to reproduce
Set OnDeleteBehaviour of my Table like this:

````
            modelBuilder.Entity<VisuPageLayerEntity>()
                        .HasMany(x => x.ControlInstances)
                        .WithOne(x => x.PageLayer)
                        .HasForeignKey(x => x.PageLayerUuid)
                        .OnDelete(DeleteBehavior.Cascade);
````

### The issue
DeleteBehaviour is set to Restrict (it does work for most other tables though)

Migration Script:
````
migrationBuilder.CreateTable(
                name: "VisuControlInstance",
                columns: table => new
                {
                    Uuid = table.Column<Guid>(maxLength: 40, nullable: false),
                    ControlTypeUuid = table.Column<Guid>(nullable: false),
                    Order = table.Column<int>(nullable: false),
                    PageGroupUuid = table.Column<Guid>(nullable: true),
                    PageLayerUuid = table.Column<Guid>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_VisuControlInstance", x => x.Uuid);
                    table.ForeignKey(
                        name: "FK_VisuControlInstance_VisuControlType_ControlTypeUuid",
                        column: x => x.ControlTypeUuid,
                        principalTable: "VisuControlType",
                        principalColumn: "Uuid",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_VisuControlInstance_VisuPageGroup_PageGroupUuid",
                        column: x => x.PageGroupUuid,
                        principalTable: "VisuPageGroup",
                        principalColumn: "Uuid",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_VisuControlInstance_VisuPageLayer_PageLayerUuid",
                        column: x => x.PageLayerUuid,
                        principalTable: "VisuPageLayer",
                        principalColumn: "Uuid",
                        onDelete: ReferentialAction.Restrict);
                });
````
(edited migration snippet)

![pomelo](https://user-images.githubusercontent.com/19493409/65687613-f0f09f80-e069-11e9-9329-8507e6a2be7f.PNG)

### Further technical details
MySQL version: 8.0.13
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.20
Microsoft.AspNetCore.App version: 2.2.0

**Comment by lauxjpn** [comment]
@EliasDerHai Please provide us with a small, self-contained console project, that we can use to generate the migration from and replicate this issue.

**Comment by EliasDerHai** [comment]
@lauxjpn Hi sorry for late response just comming back from vacation...

Here is my testproject
https://github.com/EliasDerHai/VisuPageTest

Thanks in advance for any help.

**Comment by lauxjpn** [comment]
> Hi sorry for late response just comming back from vacation...

No worries. (Herbstferien sind was Feines.)
Thanks for the test project, I'll check it out later today.

**Comment by lauxjpn** [comment]
It seems that `OnDelete` is being set to `Cascade` when your FK is `Guid` (non-nullable) while it is being set to `Restrict` (the default) when your FK is `Guid?` (nullable).

I'll check, what the expected behavior is for nullable foreign keys and `ON DELETE CASCADE` constraints. Issues related to nullable behaviors are more likely to be bugs than others.
