### ISSUE TITLE
Releasing 3.0.0-rc1.final

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#839]
Let's use this issue to track the progress for a first ~~3.0.0 preview~~ final 3.0.0 rc1 release.

#797 is in use for general updates on the 3.0.0 GA progress so far.

**Comment by lauxjpn** [comment]
Current test metrics:

MySQL | Total | Passed | Failed | Skipped
------|-------|--------|--------|--------
8.0.17 | 14104 | 13518 | 98 | 488
5.7.27 |  |  |  | 

(And yes, I did quickly fix a test before posting the stats, just to get under 100 for MySQL 8.)

**Comment by CaddyDz** [comment]
Microsoft should seriously keep v2 of asp.net core in the homepage instead of v3 which every package I try to install now doesn't support yet

**Comment by caleblloyd** [comment]
3.0.0 nightly builds are now available.  Feed instructions are updated on [README](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/README.md) and nightly builds are available on [Azure DevOps Feed](https://dev.azure.com/pomelo-efcore/Pomelo.EntityFrameworkCore.MySql/_packaging?_a=package&feed=pomelo-efcore-public&package=Pomelo.EntityFrameworkCore.MySql&version=3.0.0-rc1.19480.1&protocolType=NuGet&view=versions)

**Comment by lauxjpn** [comment]
As far as I can see, the only serious issue blocking a preview release is #844.

**Comment by lauxjpn** [comment]
I would like to (pre)release the `3.0.0-preview1` tomorrow, after the remaining open PRs have been merged.

Am I assuming correctly, that I just need to change the `PreReleaseVersionLabel` tag of the project's `Versions.prop` file and tag the merged commit accordingly to make the prerelease be published automatically to nuget?

**Comment by caleblloyd** [comment]
I need to add the Nuget step for tags, working on that right now.

I think `3.0.0-rc1-final` is appropriate.  `-previewX` usually denotes it's tracking that version of EF Core Preview and that the API is still subject to change.  Since it's tracking EF Core RTM `rc` seems appropriate as we are trying to vet out bugs and find a stable release.

> Am I assuming correctly, that I would just need to change the PreReleaseVersionLabel tag of the project's Versions.prop file and tag the merged commit accordingly

Correct, for final preview/rc releases draft a release just like `3.0.0-<PreReleaseVersionLabel>-final` on GitHub.  For RTM releases use the semver like `3.0.0`

**Comment by lauxjpn** [comment]
@caleblloyd I created a release. What is the procedure to get it published on NuGet? While the CI for the last PR that I merged ran, it skipped the `Nuget` job (as expected).
And creating the release on GitHub did not trigger anything.

Do I have to directly push a commit to the `3.0.0-wip` branch, together with the `3.0.0-rc1-final` tag, to trigger the NuGet publication and then complete the release information in GitHub afterwards?

Or do we need to add a release pipeline in AZDO?

**Comment by caleblloyd** [comment]
Looks like AZDO didn't build the tag, let me did for an option to enable that

**Comment by lauxjpn** [comment]
Unrelated to the tag triggering issue:
Should I drop the `-final` from the release title (not the release tag)?

**Comment by lauxjpn** [comment]
It looks like the PR did pass CI successfully, while the actual merge did not. Seems non-deterministic then, because they are the same. Though I am not sure, if this would affect the tag trigger issue.

**Comment by caleblloyd** [comment]
Tag triggering issue was that [tag trigggers need to be specified](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#tags)

> If you don't specify any tag triggers, then by default, tags will not trigger pipelines.

Validating the Nuget push logic with 2.2.6 now and I'll port the `azure-pipelines.yml` logic over to `3.0.0-wip` once it's working

Dropping `-final` from release name is fine, those can be edited after the fact too.  It does need to be in the tag name for prereleases, however, as their is logic to ensure the tag name matches the package version/suffix to prevent erroneously pushing misversioned packages due to overlooking `<VersionPrefix>` or `<PreReleaseVersionLabel>` in `Versions.props`

**Comment by caleblloyd** [comment]
Nuget tagging should be fixed on `3.0.0-wip`

I added a `Pack.BuildFailedOverride` variable that you can set to `true` to override failures

You'll need the new `azure-pipelines.yml` in the release.  To re-trigger the release delete the existing release/tag from GitHub and add it back

![image](https://user-images.githubusercontent.com/2414837/66265579-43525e80-e7d6-11e9-8852-8edd50443de1.png)

**Comment by caleblloyd** [comment]
Is it just Windows tests that are non-deterministic?

**Comment by lauxjpn** [comment]
>Nuget tagging should be fixed on 3.0.0-wip

Nice work!

> Is it just Windows tests that are non-deterministic?

Yes, I think this might be because the Chocolatey installed MySQL does not use a full `my.ini`, but generates a 4-liner on the fly.

**Comment by lauxjpn** [comment]
I am starting to be able to reproduce these issues locally.

**Comment by olfek** [comment]
@lauxjpn :wave: How do I get this release working on my local ASP.NET Core 3.0.0 project?

**Comment by lauxjpn** [comment]
Wow, this took a while. So the underlying issue is, that some test classes, e.g. `MappingQueryMySqlTest`, rely on tables outside of their own defined model.
Because we still don't load a SQL dump for Northwind to bootstrap the database (which is officially required as I recently inquired), test might fail if they are not executed in an order, where the needed tables have not been created yet (as a side effect of other previously run tests).

**Comment by lauxjpn** [comment]
@olfek 3.0.0-rc1-final will definitely be published to NuGet today. Stay tuned.

**Comment by olfek** [comment]
Wooo! :man_dancing:

**Comment by olfek** [comment]
@lauxjpn Thank you so much, I appreciate the effort you and others put in. :heart:

**Comment by NahroTo** [comment]
@lauxjpn Thanks for the update Laurents! Any idea what timespan we are talking about with 'today; ? Different timezones play a role here, haha.

**Comment by lauxjpn** [comment]
@caleblloyd I will deactivate test parallelism for now and force the dependent tests to run after some general test classes as a quick and dirty workaround for now, until we get around to migrate the Northwind database from SQL Server to a MySQL dump.

**Comment by lauxjpn** [comment]
@NahroTo I think < 4 hours is a safe bet.

**Comment by caleblloyd** [comment]
Looks like Arcade actually generates the package as `3.0.0.rc1.final` with a dot instead of a dash, so the tag needs to match that

**Comment by caleblloyd** [comment]
Looks like Arcade actually generates the package as `3.0.0-rc1.final` with a dot between "rc1" and "final" instead of a dash, so the tag needs to match that

**Comment by lauxjpn** [comment]
Release [3.0.0-rc1](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/3.0.0-rc1.final) is now available via [NuGet](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/3.0.0-rc1.final).

**Comment by lauxjpn** [comment]
@caleblloyd Here is the corresponding part of the [arcade versioning documentation](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md#package-version), that confirms the new versioning schema:

Build kind | Pre-release labels | Package Version example
-- | -- | --
Local developer build default | "dev" | "1.2.3-dev"
PR validation build | "ci" | "1.2.3-ci"
Daily official build | PreReleaseVersionLabel.SHORT_DATE.REVISION | "1.2.3-preview1.12345.1"
**Final pre-release official build** | **PreReleaseVersionLabel."final"** | **"1.2.3-beta.final"**
Release official build | "" | "1.2.3"

It is in line with [SemVer2](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions) and its [pre-release specs](https://semver.org/#spec-item-9):

```
<valid semver> ::= <version core>
        | <version core> "-" <pre-release>
        | <version core> "+" <build>
        | <version core> "-" <pre-release> "+" <build>

<pre-release> ::= <dot-separated pre-release identifiers>

<dot-separated pre-release identifiers> ::= <pre-release identifier>
        | <pre-release identifier> "." <dot-separated pre-release identifiers>
```
It should be noted, that it is possible to fallback on [SemVer1](https://semver.org/spec/v1.0.0.html) according to the [arcade docs](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md#semver1-fallback):

>The repository opts into SemVer1 fallback by setting SemanticVersioningV1 property to true.
>
>Examples of SemVer1 package versions:
>
>"1.2.3-dev", "1.2.3-ci", "1.2.3-beta-12345-01", "**1.2.3-beta-final**", "1.2.3".

But moving forward, using SemVer2 seems the way to go here.

**Comment by lauxjpn** [comment]
Special thanks to

- @bgrainger for a couple of quick fixes and obscure underlying MySQL bug discoveries and workarounds for MySqlConnector
- @caleblloyd for upgrading the whole CI process to AZDO pipelines and arcade

**Comment by LeandroCarneiro** [comment]
Was migration meant to be working for this release?
I am getting this:

Add-Migration : The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Am I missing something?

**Comment by neumartin** [comment]
Hi @LeandroCarneiro, try this:
Install tools for EF 3: dotnet tool install --global dotnet-ef
Use command: dotnet ef migrations add MIGRATION_NAME
Be sure that dotnet SDK 3 was installed in you system.

**Comment by LeandroCarneiro** [comment]
Hi @neumartin I installed the EF 3, but when I am trying to run:
**dotnet ef migrations add CreateAgain**(my_migration_name)
Then I am getting this as result:

No project was found. Change the current working directory or use the --project option.

Any idea?

**Comment by neumartin** [comment]
Try to use the command in the same folder where dbcontext or migrations exists.

**Comment by LeandroCarneiro** [comment]
Worked when I run the cmd through prompt cmd.
**dotnet ef migrations add CreateAgain -c MySqlContext**

Thanks @neumartin

**Comment by killerfrienddk** [comment]
It is having a few problems with foreign keys
I was trying to use microsoft's identity system.

Cannot change column 'RoleId': used in a foreign key constraint 'fk_aspnetroleclaims_aspnetroles_roleid'

**Comment by lauxjpn** [comment]
@killerfrienddk Please open a new issue for each problem you encountered, if you think these are bugs or issues that need to be addressed.

Related to the ASP.NET Identity System, we currently had the following reported issues so far:
#869, #865 , #863
