### ISSUE TITLE
Number of rows fetched grows exponentially on multiple .include/joins

### ISSUE THREAD

**Issue by sitepodmatt** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#841]
Using Pomelo 3.0.0-rc1 / EF 3.0

If we have an Animal (id auto, name) and four Attribute containers as follows: 

```
TextAttribute (id : auto , animal_Id : int (fk), value : string)
NumberAttribute (id : auto , animal_Id : int (fk), value : Decimal)
BooleanAttribute (id : auto , animal_Id : int (fk), value : bool)
DateTimeAttribute (id : auto , animal_Id : int (fk), value : DateTime)
```

if we .Include all four the amount of rows fetched is n1 x n2 x n3 x n4 (where n1 is number of related rows in text attribute, n2 number of related rows in number attribute and so on..) In our scenarios where each attribute container has over a 100 we've seen this balloon too nearly 100million rows - and thus timeouts.

Running the exact same setup on EF2.2 with Mysql.Data.EntityFrameworkCore/8.0.17 we see the preferred behavior of running 5 separate queries join on one attribute table each time and thus  millisecond query performance.

Is there a way to influence the behavior of Pomelo when joining on multiple tables? 

We currently work around this by doing 4 queries ourselves each with only 1 .include(x => x.coll) and merging but it would be nice if it was handled as seamless as the mysql-net entityframeworkcore driver

**Comment by lauxjpn** [comment]
This should be a direct result of the new EF Core 3.0 query pipeline and unrelated to Pomelo.MySql specifically:
https://devblogs.microsoft.com/dotnet/announcing-ef-core-3-0-and-ef-6-3-general-availability/

> Single SQL statement per LINQ query
Another aspect of the design that changed significantly in 3.0 is that we now always generate a single SQL statement per LINQ query. In previous versions, we used to generate multiple SQL statements in certain cases, like to translate Include() calls on collection navigation properties and to translate queries that followed certain patterns with subqueries. Although this was in some cases convenient, and for Include() it even helped avoid sending redundant data over the wire, the implementation was complex, it resulted in some extremely inefficient behaviors (N+1 queries), and there was situations in which the data returned across multiple queries could be inconsistent.

So mimicking the default 2.2 behavior by executing separate queries manually is the simplest way for you to ensure the same performance as before.

That said, normal `Include()` operations should be translated to `LEFT JOIN` or  `INNER JOIN` clauses, that should not return more rows than the amount of rows in your `Animal` table.

If you are getting `100^4` rows returned, your query was translated to an (implicit or explicit) `CROSS JOIN`, which is only supposed to happen with your 5 tables, if the majority of the rows of your 4 attribute tables don't share a foreign key with the primary key of the `Animal` table and you manually force a `CROSS JOIN` to execute.

If you think this is a bug, please provide as either with a small test project (including a database dump) or with the following, so we can reproduce the issue:

- The model definition (either in fluent style or with data annotations)
- A SQL dump containing the `CREATE TABLE` statements for the 5 tables in question and their related `INSERT` statements (about 10 per Table should be enough)
- The LINQ query that is being translated (containing the `Include()` calls, C#)
- The actual SQL query that is being executed (use MySQL's general query log or EF Core's logging functionality)

**Comment by sitepodmatt** [comment]
Hi Lauxjpn.

Thanks for the detail insight. 

Sure, let me mock it up, as the example I trivialized for the report.

**Comment by sitepodmatt** [comment]
I'm not sure I follow you explanation of "that should not return more rows than the amount of rows in your Animal table" as that would depend if there was more attributes than animals? 

https://github.com/sitepodmatt/joinrowsexample

You can see the read basically pulls back 125,000,000 rows and times out, bring the 500 down to 10 or 5...

**Comment by sitepodmatt** [comment]
I think this can be closed as there is an active discussion at https://github.com/aspnet/EntityFrameworkCore/issues/18022 and this isn't directly Pomelo issue (I hadnt considered the single sql statement change between 2.2 and 3.0 when opening the bug initially). 

Thanks

**Comment by lauxjpn** [comment]
> If you are getting 100^4 rows returned, your query was translated to an (implicit or explicit) CROSS JOIN, which is only supposed to happen with your 5 tables, if the majority of the rows of your 4 attribute tables don't share a foreign key with the primary key of the Animal table and you manually force a CROSS JOIN to execute.

That was definitely a wrong statement from me. If you join multiple tables, the maximum rows returned will be the number of rows of each table multiplied with each other.

The generated SQL statement is correct:

```sql
SELECT `a`.`Id`, `t`.`Id`, `t`.`AnimalId`, `t`.`Name`, `t`.`Value`, `i`.`Id`, `i`.`AnimalId`,
       `i`.`Name`, `i`.`Value`, `d`.`Id`, `d`.`AnimalId`, `d`.`Name`, `d`.`Value`
FROM `Animals` AS `a`
LEFT JOIN `text_attributes` AS `t` ON `a`.`Id` = `t`.`AnimalId`
LEFT JOIN `int_attributes` AS `i` ON `a`.`Id` = `i`.`AnimalId`
LEFT JOIN `datetime_attributes` AS `d` ON `a`.`Id` = `d`.`AnimalId`
ORDER BY `a`.`Id`, `t`.`Id`, `i`.`Id`, `d`.`Id`
```
So querying the related entities manually is the way to go here.
