### ISSUE TITLE
Dotnet Core 3 Identity MARS error

### ISSUE THREAD

**Issue by thepaleone** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#863]
### Steps to reproduce
1.  Set up Identity in an AspNet 3.0.0 project.
2.  Get a list of ApplicationUsers via the UserManager<ApplicationUser> instance
3.  Attempt to get the roles a user is in from the same instance.

```
var users = _userManager.Users.ToArray()
var roles = await _userManager.GetRolesAsync(users.First());
```

### The issue
An exception is thrown on the call to GetRolesAsync(). This was working in net core 2 with the latest stable version.

```
Exception message: System.InvalidOperationException: Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.

Stack trace:
   at MySql.Data.MySqlClient.MySqlCommand.set_CommandText(String value) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 151
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.GetRolesAsync(TUser user, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.GetRolesAsync(TUser user)

```

### Further technical details

MariaDB: 10.3.18
Operating system: Windows 10 & CentOS 7 (fails on both))
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc1-final
Microsoft.AspNetCore.App version: 3.0.0

**Comment by bgrainger** [comment]
The underlying exception is coming from https://github.com/mysql-net/MySqlConnector/commit/8debdef13af09498ebf900588f36bb8f56765044, which was introduced in 0.31.3. 

So this isn't a result of updating MySqlConnector (from 0.49.2 to 0.59.2) in 3.0.0-rc1.final.

**Comment by lauxjpn** [comment]
I cannot reproduce this issue.

I am using the following connection string:

```json
  "ConnectionStrings": {
    "DefaultConnection": "Server=localhost;port=3306;Database=aspnet-Issue863;User=root;Password="
  },
```
https://github.com/lauxjpn/Issue863/blob/29594436d28a05d335a1fdd01473296dabb42ae3/appsettings.json#L2-L4

I added a user, some roles and claims, assigned them to the user and called the following code:

```c#
private async Task TestIssue863()
{
    var users = _userManager.Users.ToArray();
    var roles = await _userManager.GetRolesAsync(users.First());

    foreach (var role in roles)
    {
        Debug.WriteLine(role);
    }
}
```
https://github.com/lauxjpn/Issue863/blob/29594436d28a05d335a1fdd01473296dabb42ae3/Pages/Index.cshtml.cs#L29-L38

The roles are being read as expected and being output to the debug console.

---

Generally you should make sure, that there is only one data reader opened for the same connection at the same time. If you need a second one, open another connection (e.g. by creating another `DbContext`).

The full project I used to (unsuccessfully) reproduce this issue can be found here:
https://github.com/lauxjpn/Issue863

Please provide us with a self-contained working sample project (e.g. could be on the basis of my project), that reproduces this issue.

Otherwise, please close this one.

**Comment by thepaleone** [comment]
It turns out the code I copied I'd been fiddling with. Removing the ToArray() on the first line was the problem. I think it may have something to do with changes to dotnet core 3. It seems like the lazy loading behavior has changed. If I make sure that the LINQ expression is  executed with the .ToArray() (or something similar) the error goes away.

**Comment by lauxjpn** [comment]
@thepaleone Even after removing the `ToArray()` call, my referenced [test project](https://github.com/lauxjpn/Issue863) cannot reproduce this issue:

```c#
private async Task TestIssue863()
{
    var users = _userManager.Users;
    var roles = await _userManager.GetRolesAsync(users.First());
    foreach (var role in roles)
    {
        Debug.WriteLine(role);
    }
}
```

If you publish some code, that can be used to reproduce this issue, I *will* take a deeper look into this, which might be worth it. But as long as this cannot be reproduced on our end, I have to assume that this issues is not related to Pomelo or the 3.0 update.

**Comment by clarity99** [comment]
I've been getting the same issue all over my code. 
example: 
`var mpusers = db.User.Where(x => x.mojpUsername != null).ToList();
                        foreach (var u in mpusers)
                        {`

works, but before (2.2) it worked without .ToList as well. I've had to add ToList in a few other places as well. I'll see if I can make a simple repro project.

**Comment by lauxjpn** [comment]
@clarity99 Please do. If this is reproducible, we might report this one to the EF Core team, as this would most likely be a bug upstream, because we set `RelationalConnection.IsMultipleActiveResultSetsEnabled=false` and therefore shouldn't get any MARS related errors.
