### ISSUE TITLE
EF Core 3 With Pomelo MySQL Provider Does Not Scaffold Views

### ISSUE THREAD

**Issue by hakankurcenlivivense** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#867]
According to the following link, EF Core 3 supports reverse engineering views:
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/

And according to these links, there isn't yet a MySQL provider for EF Core 3:
https://github.com/aspnet/EntityFrameworkCore/issues/17556
https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core.html

So, I used the Pomelo provider version 3.0.0-rc1.final to scaffold:

    Scaffold-DbContext "server=server;user=user;password=password;database=database" "Pomelo.EntityFrameworkCore.MySql" -OutputDir EF -f

But scaffolding did not create the views. Are you also experiencing this issue or is this something related to my configuration?

**Comment by baronics** [comment]
My test project:
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.0.0-rc1.final" />
  </ItemGroup>
</Project>`

**Comment by bgrainger** [comment]
> seem like my project is using mysql.data client even if i dont have reference to it anymore
> 
> at System.Data.Common.DbDataReader.GetFieldValue[T](Int32 ordinal) at MySql.Data.MySqlClient.MySqlDataReader.GetFieldValue[T](Int32 ordinal) in C:\projects\ **mysqlconnector** \src\ **MySqlConnector** \MySql.Data.MySqlClient\MySqlDataReader.cs:line 303 at

No, you are using the underlying MySqlConnector library.

**Comment by MKI-Miro** [comment]
> Just tried Pomelo provider version 3.0.0-rc1.final to scaffold my simple MySQL 8.0.17 database with 9 tables using .NET Core 3.0, VS2019 16.3.3 and it worked without any issues. I used the same Scaffold-DbContext command from the above comment.

do you have tinyint(1) bolumn? (in phpmyadmin it is alias for boolean)

**Comment by baronics** [comment]
I have several columns that I create with:
TINYINT UNSIGNED NOT NULL DEFAULT 0
but I see that using MySQL Workbench, it shows them as:
tinyint(3) unsigned NOT NULL DEFAULT '0'

**Comment by yukozh** [comment]
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs#L167-L174

Pomelo is using the information_schema to get the tables info, so the view is not working currently.

**Comment by MKI-Miro** [comment]
I dont have any view, I only have tables

**Comment by MKI-Miro** [comment]
I can confirm that tiny int(4) works....  but tiny int(1) not

**Comment by yukozh** [comment]
@MKI-Miro See the typemapper which implemented in Pomelo:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs

tinyint is mapping to sbyte, not bool.

**Comment by MKI-Miro** [comment]
@yukozh yes correct but I think you didnt read carefully...

I db I have tinyInt(1) ->  this is scaffolded to sbyte (dotnet type) -> on select query it throws error

When I change it tinyInt(4) -> it scaffold also to sybte -> select query works

Difference is in context file 
.HasColumnType("tinyint(1)");
.HasColumnType("tinyint(4)");

**Comment by lauxjpn** [comment]
@hakankurcenlivivense Pomelo does support views in general. If seems though, that this has not yet been implemented for scaffolding an existing database, as the following SQL is used to query the tables but not the views:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/49cac2e6dd08e60e2cb91c8127f087af8a9f594e/src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs#L81

I will implement this for `3.0.0-rc2`.

**Comment by lauxjpn** [comment]
@MKI-Miro, @baronics 
Is your your discussion actually related to the topic? If you are discussing a separate issue, please open a new one. Or are you discussing #866?

**Comment by MKI-Miro** [comment]
I am sory I thought I reply to #866

**Comment by lauxjpn** [comment]
@MKI-Miro No worries. I copied your discussion over to #866 as best as I could and will hide them in this issues here.

**Comment by lauxjpn** [comment]
Scaffolding views from existing databases has been added now with #896.
