### ISSUE TITLE
3.0.0-rc1.final / BINARY(16) not mapped to Guid with OldGuids=true

### ISSUE THREAD

**Issue by henrypiassek** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#884]
### Steps to reproduce

**SQL**
```
CREATE DATABASE GuidDataTypeTest;
USE GuidDataTypeTest;

CREATE TABLE GuidTestTable (
	GuidTestTableID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	GuidTest1 BINARY(16) NOT NULL,
	GuidTest2 BINARY(16),
	GuidTest3 CHAR(36) NOT NULL,
	GuidTest4 CHAR(36)
);
```
**CLI**
`dotnet ef dbcontext scaffold "Server=localhost;Database=GuidDataTypeTest;User=user;Password=pw;TreatTinyAsBoolean=true;OldGuids=true" "Pomelo.EntityFrameworkCore.MySql"`

### The issue
Hi,

it seems that data type mapping for binary(16) (as well as CHAR(36)) is not working properly when scaffolding from database. BINARY(16) columns are mapped to byte[] and CHAR(36) to string when "OldGuids=true" is specified in connection string (but also when its omitted or set to false explicitly).

Generated entity code looks like this:
```
public partial class GuidTestTable
{
    public long GuidTestTableId { get; set; }
    public byte[] GuidTest1 { get; set; }
    public byte[] GuidTest2 { get; set; }
    public string GuidTest3 { get; set; }
    public string GuidTest4 { get; set; }
}
```

Additionally TINYINT(1) is not mapped to bool. I found that this has been explained / resolved in #866 and #875 - now I'm wondering if the mechanics described in there could also be responsible for this data type mapping issue. Did anyone else experience the same problem and already found a solution?

### Further technical details

MySQL version: 8.0.17
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc1.final
Microsoft.AspNetCore.App version: 3.0.0

[EDIT]
Just wanted to add that TINYINT(1) columns are mapped to bool correctly on nightly builds - BINARY916)/CHAR(36) still aren't.

**Comment by lauxjpn** [comment]
I will check this later today. Maybe the following line is the culprit, as `clrType` is likely to be `null` in the described case, because the scaffolder doesn't know what the CLR type is supposed to be (which is the reason it is applying the mapping in the first place):

https://github.com/lauxjpn/Pomelo.EntityFrameworkCore.MySql/blob/41ef218ab27f8451de751ced6c0fc783272d624d/src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs#L291

**Comment by bgrainger** [comment]
Note that MySqlConnector can variously treat `BINARY(16)`, `CHAR(32)`, or `CHAR(36)` columns as `System.Guid` depending on the `GuidFormat` connection string option (which supersedes the `OldGuids` option inherited from Connector/NET). https://mysqlconnector.net/connection-options/

**Comment by henrypiassek** [comment]
@lauxjpn Yes, it appears that clrType is null. I cloned the repo and locally modified that condition as follows:

```
                if (_options.ConnectionSettings.OldGuids)
                {
                    if (storeTypeName.Equals(_oldGuid.StoreType, StringComparison.OrdinalIgnoreCase)
                        && (clrType == typeof(Guid) || clrType == null))
                    {
                        return _oldGuid;
                    }
                }
                else
                {
                    if (storeTypeName.Equals(_uniqueidentifier.StoreType, StringComparison.OrdinalIgnoreCase)
                        && (clrType == typeof(Guid) || clrType == null))
                    {
                        return _uniqueidentifier;
                    }
                }
```
I don't know if this may have any side effects so I don't feel comfortable submitting a pull request for this change.

@bgrainger I should have mentioned that I tried using GuidFormat=Binary16 as well and it didn't work either.

**Comment by lauxjpn** [comment]
@bgrainger Thanks for the heads-up! In that case we should implement the `GuidFormat` option as well, while we are at it.

**Comment by lauxjpn** [comment]
@henrypiassek Your proposed code change should work.
I can either implement it together with the `GuidFormat` support, or you can open a PR. If the CI tests are running again (they suddenly didn't yesterday), they should take care of providing the necessary feedback. Generally, the `null` check should not have any unexpected side effects, as we are just correcting for the expected behavior.

**Comment by lauxjpn** [comment]
Let's keep this issue open until `GuidFormat` has been implemented as well.
