### ISSUE TITLE
Multi-schema drop

### ISSUE THREAD

**Issue by Donistivanov** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#897]
### Steps to reproduce
I have a MySQL conn string: `server=localhost;User Id=groot;password=password;database=schema1`

I put a Table attribute on some model like: `[Table("cool_table", Schema="schema2")]`

Scaffolding and db update makes both schemas.

`dotnet ef database drop` only drops schema1

### The issue
I would like to be able to drop all the schemas related to my project

### Further technical details

MySQL version: 6.3
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: `<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.2.0-preview1-final" />`
Microsoft.AspNetCore.App version: `<TargetFramework>netcoreapp2.2</TargetFramework>`

Other details about my project setup: If I have to have references between schemas, I think I had to put the line `modelBuilder.HasDefaultSchema("schema1");`

**Comment by mguinness** [comment]
Similar to https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/892#issuecomment-546073417 you'll have to create a `DbContext` for that database (if you haven't already) and specify that in the [CLI](https://www.entityframeworktutorial.net/efcore/cli-commands-for-ef-core-migration.aspx#database-drop).
