### ISSUE TITLE
Mysql 8.0 RENAME COLUMN

### ISSUE THREAD

**Issue by eduardoxvii** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#898]
It: ALTER TABLE `TurmaAluno` RENAME COLUMN `AlunoId` `PessoaId`
Shoud be: ALTER TABLE `TurmaAluno` RENAME COLUMN `AlunoId` TO `PessoaId`

 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`PessoaId`' at line 1

Pomelo: 3.0.0-rc1

**Comment by lauxjpn** [comment]
Thank you for reporting this. It is fixed with #899.
