### ISSUE TITLE
authorize attribute causing 500 server error, possible issue with identity in asp.net core 3.0

### ISSUE THREAD

**Issue by yohsii** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#902]
### Steps to reproduce
trying to run [this](https://github.com/yohsii/puck-core) project with pomelo mysql provider.
delete existing migrations (which are based on SQL Server) and use valid mysql connection string in appSettings.json.
initial migrations should scaffold database with no errors

### The issue
when you visit /puck (the backoffice for the cms) which uses authorize attributes, you get a 500 error with no stack trace (not great, i know)

when you do the same thing using SQL Server, it works

### Further technical details

MySQL version: 8.0.18
Operating system: w10
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc1.final
Microsoft.AspNetCore.App version: 3.0

Other details about my project setup:
thanks

**Comment by lauxjpn** [comment]
Take a look at https://github.com/MiniProfiler/dotnet/issues/433#issuecomment-547077949 and try-out if it resolves this issue for you.

https://github.com/aspnet/EntityFrameworkCore/issues/12157 should generally be resolved in `3.0.0`.

**Comment by yohsii** [comment]
@lauxjpn thank you! that did the trick :]
