### ISSUE TITLE
conflict

### ISSUE THREAD

**Issue by Dau-Duc-Hai** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#907]
### Steps to reproduce
When using EF & MySql.Data
  internal IDbConnection DbConnection
        {
            get
            {
                return new MySqlConnection(_config.GetConnectionString("DefaultConnection"));
            }
        }

### The issue
The type 'MySqlConnection' exists in both 'MySql.Data, Version=8.0.18.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' and 'MySqlConnector, Version=0.59.2.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92'
```
Exception message:
Stack trace:
```

### Further technical details

MySQL version:  5.7
Operating system: windows
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc1.final
Microsoft.AspNetCore.App version: 3.0

Other details about my project setup:

**Comment by yukozh** [comment]
You should not install the client which published by Oracle

**Comment by lauxjpn** [comment]
As @yukozh points out, you are mixing Oracle's `MySql.Data` with `MySqlConnector` and possibly `Pomelo.EntityFramework.Core` (as you are seeking help here about the error).

That is not going to work. If you want to use `Pomelo.EntityFramworkCore.MySql` (which uses `MySqlConnector` for its database access), please remove all your Oracle MySQL references from your project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.0.0-rc1.final" />
  </ItemGroup>

</Project>
```

**Comment by Dau-Duc-Hai** [comment]
Thank you Yuko Zheng for reply.
in my case I want to use mix EF for IdentityServer4 and also using dapper,
which I need MySqlconnection. Can you tell me how to do?

Thank you for support.
Best regard.

HD

**Comment by lauxjpn** [comment]
@Dau-Duc-Hai Have you tried using different projects/assemblies (each with its own needed references) for the EF Core and for the Dapper related stuff?

**Comment by bgrainger** [comment]
See comments at https://github.com/mysql-net/MySqlConnector/issues/189#issuecomment-543583735 for how to use aliases in SDK projects.

**Comment by Dau-Duc-Hai** [comment]
In fact, I have no problem with MS SQL server. I have project started with
MS sql server but my customer wants to change from MS SQL  to MySql then I
need to migrate ...

**Comment by mguinness** [comment]
You can also use Dapper with [MySqlConnector](https://mysqlconnector.net/overview/use-with-orms/), so you can probably do away with MySql.Data altogether.
