### ISSUE TITLE
Error applying migrations: uniqueidentifier, datetime2

### ISSUE THREAD

**Issue by alejo345** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#919]
### Steps to reproduce
```
/***   Guid   ***/
modelBuilder.Entity("EntityFrameworkDataAccess.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

/***   datetime2   ***/
 modelBuilder.Entity("EntityFrameworkDataAccess.Entities.Credit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Credit");
                });
```

### The issue
When I try to apply a migration create from SQL Server to MySQL, it fails when it is changing the column type from **uniqueidentifier** (GUID) to **char(36)**

```
Exception message:
Stack trace:
MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'uniqueidentifier(36) NOT NULL,

another

MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'datetime2(6) NOT NULL....
```

### Further technical details

MySQL 5.7.3: 
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc2.final
Microsoft.AspNetCore.App version: 3.0.0

**Comment by lauxjpn** [comment]
#### Guid

Your code:
```c#
b.Property<Guid>("AccountId")
    .HasColumnType("uniqueidentifier");
```
MySQL does not support a type named `uniqueidentifier`. But Pomelo *does* supports multiple options to save a `Guid` in a MySQL table.

See `GuidFormat` on the [MySQL ConnectionString Options](https://mysqlconnector.net/connection-options/) page.

The default mapping for `System.Guid` is `char(36)`, which will work out-of-the box without explicitly specifying the `GuidFormat`:

Working code:
```c#
b.Property<Guid>("AccountId")
    .HasColumnType("char(36)");
```

#### DateTime

Your code:
```c#
b.Property<DateTime>("TransactionDate")
    .HasColumnType("datetime2");
```

MySQL does not support a type named `datetime2`. It supports the follow date/time related data types:
- `time`
- `date`
- `datetime`
- `timestamp`

The closest data type MySQL >= 5.6 supports to a MSSQL `datetime2` is `datetime(6)`, which will automatically be chosen, if your MySQL version supports it.
So the following code will work:

Working code:
```c#
b.Property<DateTime>("TransactionDate")
    .HasColumnType("datetime");
```

#### General

See the [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/data-types.html) for all supported data types.

**Comment by alejo345** [comment]
We need support both database engines (SQL Server and MySQL).
I reviewed GuidFormat on the MySQL ConnectionString Options, and it still failed.

After compare Pomelo v2.2.6 with the latest 3.0.0-rc, we have to remove `.HasColumnType("uniqueidentifier")` and `.HasColumnType("datetime2")` from Migrations.cs and Migrations.Designer.cs, also the `ContextModelSnapshot.cs` and it works, but the idea is prevent the customization of **Up** and **Down** methods by migration

**Comment by lauxjpn** [comment]
Take a look at the following two MSDN articles:
- [Migrations with Multiple Providers](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli) and 
- [Alternating between multiple models with the same DbContext type](https://docs.microsoft.com/en-us/ef/core/modeling/dynamic-model)

Also, as you figured out yourself, you can fall back on the default type mapping implementation by just removing the `HasColumnType()` call all together.

---

> I reviewed GuidFormat on the MySQL ConnectionString Options, and it still failed.

You need to use `GuidFormat` in conjunction with your model definition. My previous samples should work without issues. If it does not, please post the exact model definition code you tried and the corresponding `GuidFormat` connection string option you used.
