### ISSUE TITLE
Updating entity without changes

### ISSUE THREAD

**Issue by Mats391** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#92]
Not sure if this is EF Core or adapter problem. I tested it with EF6 and MySql adapter and it worked as expected there.

### The issue
I am creating an asp app and clients are allowed to update existing entries in the database. For that I accept the data, create an untracked entity model and then set its status to modified. Looks something like this then:
```
using (var db = MyDbContextFactory.Create(connectionstring))
{
    Course course = new Course()
    {
        Name = "Name"
    };
    db.Courses.Add(course);
    db.SaveChanges();
} // Works fine. Adds new Course

using (var db = MyDbContextFactory.Create(connectionstring))
{
	Course course = new Course()
	{
		Id = 1,
		Name = "New Name"
	};
	db.Entry(course).State = EntityState.Modified;
	db.SaveChanges();
}
```
This works fine if Name really is a new name. In the following scenario it wont work:
```
using (var db = MyDbContextFactory.Create(connectionstring))
{
	Course course = new Course()
	{
		Name = "Name"
	};
	db.Courses.Add(course);
	db.SaveChanges();
} // Works fine. Adds new Course

using (var db = MyDbContextFactory.Create(connectionstring))
{
	Course course = new Course()
	{
		Id = 1,
		Name = "New Name"
	};
	db.Entry(course).State = EntityState.Modified;
	db.SaveChanges();
} // Works fine. Changes Name of Course with Id 1 to New Name

using (var db = MyDbContextFactory.Create(connectionstring))
{
	Course course = new Course()
	{
		Id = 1,
		Name = "New Name"
	};
	db.Entry(course).State = EntityState.Modified;
	db.SaveChanges();
} // Concurrency error
```
Hope this is easy to fix. I really do not want to manually check if entity changed. :)

### Exception
```
{Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagation(Int32 commandIndex, DbDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(DbDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.MySqlBatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at EFCoreAddDeleteTest.Program.Main(String[] args)}
```

### Further technical details

Pomelo.EntityFrameworkCore.MySql version: "1.0.1-prerelease-10018"

**Comment by Kagamine** [comment]
Why you change the entity state manually?

**Comment by caleblloyd** [comment]
There is a quick fix: set `UseAffectedRows=false` in your MySqlConnection string.  This option was added yesterday in https://github.com/mysql-net/MySqlConnector/issues/104 and requires 1.0.1-prerelease-10019

On another note, we need to research using Found Rows instead of Affected Rows for throwing `DbUpdateConcurrencyException`, because of this very reason.  I'll open a separate issue.

**Comment by Kagamine** [comment]
@Mats391 You should use DbContext.Attach() before changing the entity state.

**Comment by Mats391** [comment]
Using DbContext.Attach() or DbSet.Attach() before changing the entity state still causes same error. Those two just set the entity state to Unchanged, dont they?
I wanted to give the `UseAffectedRows=false` a try, but for some reason nuget does not recognize 10019 as a valid version. 10018 is highest I can get.

**Comment by caleblloyd** [comment]
Just updated the NuGet feed to include 10019, can you try now?

**Comment by Kagamine** [comment]
10019 is still using MySqlConnector 0.5.0. Due to its bad version rule, we have to modify our project.json manually.

**Comment by caleblloyd** [comment]
Should be fine, `UseAffectedRows` was introduced in MySqlConnector 0.5.0

**Comment by Mats391** [comment]
10019 works now and UseAffectedRows fixed the issue, thanks. Is there any downside from using it?

**Comment by caleblloyd** [comment]
No downside for general use EF purposes. #93 is open to discuss changing this to the default behavior.
