### ISSUE TITLE
Issue - Package reference should not specify a version

### ISSUE THREAD

**Issue by whreed** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#921]
### Steps to reproduce
I am trying to update Clean Architecture with Pomelo to use MySql instead of SQL or SQL Lite.  I added the pomelo to a .NET Core 3.0 class library.

### The issue
When adding the pomelo v3 rc3 I receive the error 
Severity	Code	Description	Project	File	Line	Suppression State
Error		The package reference 'Pomelo.EntityFrameworkCore.MySql' should not specify a version.  Please specify the version in 'C:\Users\xxxx\Source\Repos\CleanArchitecture-master\Packages.props' or set VersionOverride to override the centrally defined version.	CleanArchitecture.Infrastructure	C:\Users\xxxx\Source\Repos\CleanArchitecture-master\src\CleanArchitecture.Infrastructure\CleanArchitecture.Infrastructure.csproj	1	

### Further technical details

MySQL version: MariaDB 10.4.6
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc3.final
Microsoft.AspNetCore.App version: 3.0

Other details about my project setup:

**Comment by mguinness** [comment]
It appears you have an issue with MSBuild, you probably should create an issue at [CleanArchitecture ](https://github.com/ardalis/CleanArchitecture).

**Comment by lauxjpn** [comment]
Many projects/solutions explicitly specify the versions of their packages to ensure, that they do not get changed by accident to a version, that has not been tested with the project in question.

In your case, the error message of your `CleanArchitecture` project does tell you exactly what to do:

> The package reference 'Pomelo.EntityFrameworkCore.MySql' should not specify a version. Please specify the version in 'C:\Users\xxxx\Source\Repos\CleanArchitecture-master\Packages.props' or set VersionOverride to override the centrally defined version.

So put it in https://github.com/ardalis/CleanArchitecture/blob/master/Packages.props and you should be fine.

This is unrelated to Pomelo.

**Comment by whreed** [comment]
Thank you @lauxjpn I feel pretty stupid the error kept referring me to the project file and I was just focused on that instead of modifying the props file like the error said.  Thank you so much for pointing me in the right direction.
