### ISSUE TITLE
Internally inconsistent `MySql:CharSet` annotation behavior

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#926]
Currently, the newly introduced `MySql:CharSet` annotation has a value of type `string` when scaffolding, but of type `CharSet` everywhere else.

We should make it a `string` for everything, because the `CharSet` class does only add the max. bytes per char functionality, which is not being used for the purpose of this annotation.
This would also make the very long generated lines by the scaffolder shrink down.

**Comment by mguinness** [comment]
Maybe omit the `MySql:CharSet` annotation in scaffolding for now and reassess in 3.1?  Thinking that a `MySql:Collation` annotation might be a better solution (from which charset can be inferred).

**Comment by lauxjpn** [comment]
We can add a collation annotation at any point without breaking the already existing charset annotation.

Inferring a charset from a collation would require some up-to-date mapping tables between charsets and collations, which I would not like to maintain, because these annotations don't have any impact on Pomelo, but are just for scenarios where other apps depend on a specific column charset or collation.

Just adding another extension method like `.HasCollation()` or overloading the `.HasCharSet()` extension method with an additional parameter for the collation seems easier for us. The user is then responsible and in full control of his charsets and collations.

**Comment by mguinness** [comment]
I don't think you'd need mapping tables as there are [Collation Naming Conventions](https://dev.mysql.com/doc/refman/8.0/en/charset-collation-names.html) with each collation tied to a charset, but your other points are valid.

**Comment by lauxjpn** [comment]
I wasn't are of that. That actually seems pretty straight forward to implement. We can at least use this as a fallback feature, if a collation but no charset has been specified.
