### ISSUE TITLE
Use Found Rows instead of Affected Rows for DB Concurrency Updates

### ISSUE THREAD

**Issue by caleblloyd** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#93]
Research using Found Rows instead of Affected Rows for detecting concurrency errors

#91 and #92 show that upserts can be submitted that are legitimate (1 Found Row), but don't actually change anything (0 Affected Rows).  This should not throw a `DbUpdateConcurrencyException`.

**Comment by Kagamine** [comment]
found_rows() only works with `SELECT`. It does not return a correct value while you are using `UPDATE`, `INSERT` or `DELETE`

**Comment by Kagamine** [comment]
@caleblloyd  Can we set false as the UseAffectedRows default value in our lib?

**Comment by caleblloyd** [comment]
Yes, I think that we should.  It will cut down on Concurrency Exceptions.  EF does not need Affected Rows anywhere.  We can do it on all connections that configure Pomelo with a connection string.

I'll work up a PR within the next couple days.

**Comment by Kagamine** [comment]
It is really a bad design of MySQL. I hope they divide the ROW_COUNT() into AFFECTED_ROW_COUNT() and FOUND_ROW_COUNT().

**Comment by Kagamine** [comment]
After fixing this, we will release `1.0.1`, and bump up our library to 1.1.0-preview1
