### ISSUE TITLE
Error when getting a model with a guid

### ISSUE THREAD

**Issue by jdaless** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#938]
I'm struggling trying to get my models to work with `Guid` type properties. If I add a new value to the `DbSet`, when I try to retrieve it I get a `FormatException: Guid should contain 32 digits with 4 dashes`. If I manually enter the Guid in that format, when I try to retrieve the object I get an `InvalidCastException : Unable to cast object of type 'System.Guid' to type 'System.Byte[]'`. I am using the default Guid storage, my db is storing them as a char(36). 

Is there some step I'm missing? 

###Further technical details
MySQL version: MySQL 8.0
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.2.6
Microsoft.AspNetCore.App version: 3.0.0

**Comment by mguinness** [comment]
You haven't mentioned what version of the library your using...

Do you have either `GuidFormat` or `OldGuids` specified in your [connection string](https://mysqlconnector.net/connection-options/)?

**Comment by jdaless** [comment]
Edited above. 

I do not.

**Comment by mguinness** [comment]
You should be using [3.0.0-rc3.final](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/3.0.0-rc3.final) then.

**Comment by lauxjpn** [comment]
We recently improved the general support for `Syste.Guid` with #904.

You can also take a look at https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/919#issuecomment-550514909 for a quick example.

If you still have trouble getting your code to work (with the latest prerelease), you can post us your model definition.

**Comment by jdaless** [comment]
Upgrading got it working, thanks for the example @lauxjpn!
