### ISSUE TITLE
Scaffold-DbContext tool BIT -> ulong

### ISSUE THREAD

**Issue by jpuebla** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#946]
I Tried new final release 3.0.0.0
When I use Scaffold-DbContext tool wirh MariaDb 10.3 all fileds BIT(1) are converted to ulong

It should be converted to bool

MariaDb 10.4: 
Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.0.0.0
Microsoft.AspNetCore.App version: 3.0

**Comment by lauxjpn** [comment]
This is a duplicate of #917.
