### ISSUE TITLE
version 3.0.0 not support netstandard 2.0 

### ISSUE THREAD

**Issue by bidianqing** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#947]
I can't install it in TargetFramework `netstandard2.0`

**Comment by mguinness** [comment]
See [EF Core 3.0 targets .NET Standard 2.1 rather than .NET Standard 2.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#netstandard21) for more information.

**Comment by lauxjpn** [comment]
The `3.0.0` release is compatible with EF Core 3.0 which uses .NET Standard 2.1.
We released Pomelo `3.0.0` currently as .Net Core 3.0 compatible and not .NET Standard 2.1 compatible, though we should probably recompile it as .NET Standard 2.1.
