### ISSUE TITLE
Invalid cast to double in generated SQL

### ISSUE THREAD

**Issue by hrattls** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#952]
The following code
`.FirstOrDefault(s => factuur.Datum.AddDays(s.Dagen) <= _dateTimeProvider.Today).Id`  

Generates the following where clause:
`    WHERE DATE_ADD(`f2`.`Datum`, INTERVAL CAST(CAST(`h0`.`Dagen` AS double) AS signed) day) <= @___dateTimeProvider_Today_8
`

s.Dagen is type int.
I get a syntax error because double is invalid.
The query runs if I manually test the generated sql and change it to (replaced double by signed)

`    WHERE DATE_ADD(`f2`.`Datum`, INTERVAL CAST(CAST(`h0`.`Dagen` AS signed) AS signed) day) <= curdate()
`

MySQL version: 8.0.16
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.0.0
Microsoft.AspNetCore.App version: 3

**Comment by lauxjpn** [comment]
It is likely that you are not specifying the `ServerVersion` you are using when you are setting up the context:

```
options.UseMySql(myConnectionString, builder =>
    builder.ServerVersion(new ServerVersion(new Version(8, 0, 16), ServerType.MySql)));
```

If no `ServerVersion` is configured, it is assumed you are using the latest Version of MySQL.
Support for `double` casts was introduced in MySQL 8.0.17.

**Comment by hrattls** [comment]
Thank you.
After setting the ServerVersion, the following SQL is generated:

`    WHERE DATE_ADD(`f2`.`Datum`, INTERVAL CAST((CAST(`h0`.`Dagen` AS decimal(65,30)) + 0e0) AS signed) day) <= @___dateTimeProvider_Today_8`

and the syntax error does not occur anymore.
