### ISSUE TITLE
PMC command "dotnet ef database update" issue

### ISSUE THREAD

**Issue by raime910** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#96]
### Steps to reproduce

Created a new .NET Core project and added the code on the GitHub main page.
Ran it once - it worked.
Added a new table called Role which has a many-to-many relationship with the User table.
Ran `dotnet ef database update`
Then I got this 

`C:\users\user\documents\visual studio 2015\Projects\WebApplication2\src\webapplication2\Migrations\MyContextModelSnapshot.cs(25,43): error CS0246: The type or namespace name 'ICollection<>' could not be found 
(are you missing a using directive or a
n assembly reference?)`

I added the namespace to get rid of the build issue
I ran `dotnet ef database update` and the error is back.

Is there another way to update my schema?

MySQL version: 5.6
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 1.0.0

**Comment by Mats391** [comment]
How did you configure your many-to-many relationship? Could you post your entities?
