### ISSUE TITLE
Scaffold ServerVersion() call

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#960]
We currently do not scaffold the `ServerVersion` that is being used by the database server.

With the different implementations of MySQL compatible database servers out there and still heavy development on the feature side of MySQL, we are making use of server version specific statements in many parts of the Pomelo provider.

Though users should always specify the expected (or minimal supported) server version when setting up a `DbContext`, many user are not aware of that and therefore use the default server version, which is the latest one.

As we discussed on Wednesday, scaffolding the actual `ServerVersion` will help prevent this issue at least in those cases, where users assume that the scaffolded code is complete and does not need to be altered, which could lead to bugs later on, when Pomelo makes use of newly introduced MySQL features that are not yet supported by the older version of the underlying database used by the user.

This will be the first step towards making it mandatory to explicitly set the server version when setting up a `DbContext` for Pomelo.

It should be functional equivalent to the scrapped #932 PR.

/cc @ajcvickers, @roji

**Comment by roji** [comment]
Note that if you want singleton services to be affected by the version (e.g. TypeMappingSource, QuerySqlGenerator), then unless I'm mistaken a model annotation will not be sufficient - you're going to need something inheriting ISingletonOptions. This will cause a new service provider to be built for different, and a different instance of each singleton service to get instantiated. You can take a look at how Npgsql does this in [NpgsqlOptions](https://github.com/npgsql/efcore.pg/blob/778a78579bb982a3086270b3587f7f14ba894f25/src/EFCore.PG/Internal/NpgsqlOptions.cs#L12), which extends ISingletonOptions (or CosmosSingletonOptions in EF Core). @ajcvickers can confirm that I haven't said anything silly.

IIRC unfortunately we don't yet have a mechanism to scaffold db context options, which is how the version would be implemented. No time to find the tracking issue at the moment, but @bricelam can confirm.

**Comment by lauxjpn** [comment]
I think we implemented it in a similar way in #961, where we read the server version from the connection right before scaffolding, and then save it as an IMySqlOptions property (via the official `DbContextBuilder` extension method) as long as it has not already been set for some reason.

We then use `ProviderCodeGenerator.GenerateProviderOptions()` to generate the code for the `ServerVersion()` extension method.

**Comment by bricelam** [comment]
We need to flow the model (or just its annotations) into the provider scaffolding method. Tracked by https://github.com/aspnet/EntityFrameworkCore/issues/10487
