### ISSUE TITLE
Lazy loading not working

### ISSUE THREAD

**Issue by claunia** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#965]
### Steps to reproduce
Enable LazyLoading proxies in https://github.com/discimagechef/DiscImageChef.Server

### The issue
Lazy loading is not working. While previously said it was not supported by EFCore, it is from long ago, it appear in Microsoft documentation, and it works with MySQL Connector for .NET.

### Further technical details

MariaDB version: 10.3.1
Operating system: ArchLinux
Pomelo.EntityFrameworkCore.MySql version: 3.0.0
Microsoft.AspNetCore.App version: 3.0.0

**Comment by lauxjpn** [comment]
Lazy Loading is working fine in my tests. Here is a complete example I used to verify the correct behavior:

```c#
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int WaffleId { get; set; }

        // Needs to be virtual for Lazy Loading to work out-of-the box.
        public virtual Waffle Waffle { get; set; }
    }

    public class Waffle
    {
        public int Id { get; set; }
        public string Name { get; set; }

        // Needs to be virtual for Lazy Loading to work out-of-the box.
        public virtual ICollection<IceCream> IceCreams { get; set; } = new HashSet<IceCream>();
    }

    public class Context : DbContext
    {
        public DbSet<IceCream> IceCreams { get; set; }
        public DbSet<IceCream> Waffles { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql("server=127.0.0.1;port=3306;user=root;password=;database=Issue965")
                .UseLazyLoadingProxies() // <-- enable Lazy Loading
                .UseLoggerFactory(LoggerFactory.Create(b => b
                    .AddConsole()
                    .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IceCream>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.HasOne(e => e.Waffle)
                    .WithMany(e => e.IceCreams)
                    .HasForeignKey(e => e.WaffleId);
            });

            modelBuilder.Entity<Waffle>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.HasMany(e => e.IceCreams)
                    .WithOne(e => e.Waffle)
                    .HasForeignKey(e => e.WaffleId);
            });
        }
    }

    internal class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.IceCreams.AddRange(
                new IceCream()
                {
                    Name = "Vanilla",
                    Waffle = new Waffle {Name = "Natural Waffle"}
                },
                new IceCream()
                {
                    Name = "Vanilla Special",
                    Waffle = new Waffle {Name = "Chocolate Waffle"}
                });

            context.SaveChanges();

            var iceCreams = context.IceCreams.ToList();
            var chocolateWaffle = iceCreams.Last().Waffle;
            var chocolateWafflesIceCreams = chocolateWaffle.IceCreams.ToList();

            Debug.Assert(iceCreams.Count == 2);
            Debug.Assert(chocolateWaffle != null);
            Debug.Assert(chocolateWaffle.Name == "Chocolate Waffle");
            Debug.Assert(chocolateWafflesIceCreams.Count == 1);
            Debug.Assert(chocolateWafflesIceCreams[0].Name == "Vanilla Special");
        }
    }
}
```
You can find general information about [Lazy Loading](https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading) in the official docs.

If you encounter a specific area, where Lazy Loading does not appear to work, please provide us with a simple example project that reproduces the issue (just alter the code above if you want).

**Comment by claunia** [comment]
I can't believe I forgot to add `.UseLazyLoadingProxies()` to the TWO places where it had to be.

I sincerely apologize, I shall not do bug reports under fever, you are absolutely right it works now.

**Comment by lauxjpn** [comment]
Not a problem. I hope you feel better soon!

**Comment by alessandroparma** [comment]
Sorry to come back to a so old post. @claunia : shy did you say "to the TWO places where is had to be"?
LaxyLoading enabling shall reside only in the OnConfiguring method of the constext. SHere the second place shall be?

**Comment by mguinness** [comment]
Based on the referenced project, it was in Startup and DbContext.

https://github.com/aaru-dps/Aaru.Server/search?q=UseLazyLoadingProxies

**Comment by ragabmoh2ooo** [comment]
I use Efcor 5 , So in the Console Application I need to use Lazy Loading ..When I was Installing
 - "Microsoft.EntityFrameworkCore.Proxies" Version 5.0.7
And Created in OnConfiguring  method in Context Class 
 - optionbuilder. UseLazyLoadingProxies().SqlServer("your Connectionstring")
And Made every Navigation Properties Virtual 
 After All these ... gave me Exception 
  "Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object."
Any One Can help me Please ....

**Comment by lauxjpn** [comment]
@RagabMohamedRagab Is this still an issue for you?

**Comment by RagabMohamedRagab** [comment]
Totally right 🔥

**Comment by RagabMohamedRagab** [comment]
> @RagabMohamedRagab Is this still an issue for you?

Totally right 🔥

**Comment by RagabMohamedRagab** [comment]
> @RagabMohamedRagab Is this still an issue for you?

Actually sir , I have solved it by adding it also in DbContext of domain entities

**Comment by lauxjpn** [comment]
@RagabMohamedRagab Awesome, glad you were able to solve it!

**Comment by RagabMohamedRagab** [comment]
> @RagabMohamedRagab Awesome, glad you were able to solve it!

Thanks 🔥
