### ISSUE TITLE
Deleting related entites without FK

### ISSUE THREAD

**Issue by Mats391** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#97]
I am currently working on a MyIsam database and found some unexpected behavior when cascade deleting. I could switch to InnoDb or another engine that supports FK for dealing with this natively on the database, but I actually do not want to care about the database too much while working with EF.
### The issue

On a database engine that does not support FK (e.g. MyIsam) related entities that should cascade on delete only get deleted if you eager load them before.
Example:

```
// This will delete related Students
db.Remove(course.Include(x=>x.Students);

// This will not delete related Students
db.Remove(course);
```

This could be an issue with EF core and 1.1 might actually fix this as they say 1.1 will deal with more queries on the database instead of memory. With 1.1 it also looks like we will be able to easily load related entities without having to do a lot of includes.
All in all would be nice if this could be done on the database without explicitly having to eager load everything.

**Comment by caleblloyd** [comment]
Explicit Loading ([commit](https://github.com/aspnet/EntityFramework/issues/625), [docs](https://docs.efproject.net/en/staging/querying/related-data.html#explicit-loading)) is supported in EF 1.1.0-preview1.

@Kagamine  I think we should up our build to support 1.1.0-preview1, since we will end up shipping Pomelo 1.1 once EF 1.1 is RTM.

Lazy loading is still not supported.

@Mats391 you should always use InnoDB unless you have a very good reason to be using MyISAM.  There's plenty of articles out there that explain the differences, but InnoDB will be far more stable for you.

**Comment by Kagamine** [comment]
Where is VS Tooling for .NET Core 1.1.0-prev1?

**Comment by caleblloyd** [comment]
Not sure about VS Tooling, I use JetBrains Project Rider.  The 1.1.0-preview1 `dontet` install instructions are here though: https://blogs.msdn.microsoft.com/dotnet/2016/10/25/announcing-net-core-1-1-preview-1/

**Comment by caleblloyd** [comment]
I can't get command line tooing to work (same as VS tooling I think).  Looks like there's an open issue:

https://github.com/aspnet/EntityFramework/issues/6897

I've got the upgrade to 1.1.0-preview1 WIP here: https://github.com/caleblloyd/Pomelo.EntityFrameworkCore.MySql/commit/0b5d1a6d1f8b58fbb8b494eb427a6e3f39278cba, once Microsoft fixes the tooling I will test it and open a PR

**Comment by caleblloyd** [comment]
@Mats391 explicit loading is working in our `1.1.0-preview1` builds.  For an example of how it works, checkout the [Test Case](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/104/files) . It doesn't cover bulk update/delete scenarios though.

https://github.com/aspnet/EntityFramework/issues/795 will bring bulk Update / Delete whenever it is implemented.

It looks like https://github.com/zzzprojects/EntityFramework-Plus may provide the extension methods that you need for Bulk Update / Delete, but I haven't tried it.
