### ISSUE TITLE
Support for EF Core 3.1

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#978]
It might take us until mid-January for an official EF Core 3.1 compatible release, but we will make a prerelease (based on `3.0.1`) available within approximately 48 hours, that I expect to be as stable as `3.0.1` itself.

**Comment by lauxjpn** [comment]
Release [3.1.0-rc1](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/3.1.0-rc1.final) is now available via [NuGet](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/3.1.0-rc1.final).

**Comment by lauxjpn** [comment]
I talked to @roji yesterday about future releases planed for EF Core and it looks like EF Core will move from 3.1 directly to .NET 5.0.

Originally we planed to put in a couple of new features for Pomelo (e.g. spatial support) in our 3.1 release, because we try to be SemVer2 compliant but also correlate our version numbers with those of EF Core.

This would have lead us to wait until we would have implemented and stabilized these features, before we could make the 3.1 support public as a non-prerelease.

But now with EF Core not doing another minor version release until .NET 5.0, we are free to just release an official version for 3.1 right away, that people can hop on for .NET Standard 2.0 support and also to be able to switch to the new LTS release, and then release a 3.2.0 version with new features later in January when we have had enough time for testing them out in the field.

**Comment by ajcvickers** [comment]
@lauxjpn Sounds like a good plan.

**Comment by lauxjpn** [comment]
Release [3.1.0](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/3.1.0) is now available via [NuGet](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/3.1.0).

**Comment by sebamed** [comment]
@lauxjpn Do you have any info on the `spatial support`?

**Comment by lauxjpn** [comment]
@sebamed We will add JSON and Spatial support next. Probably in this order. Each feature could take as long as two weeks to implement, depending on how much time I will have available.

**Comment by tinchoel10** [comment]
There's any news on spatial support?

**Comment by lauxjpn** [comment]
> There's any news on spatial support?

I want to get Pomelo 3.x feature complete this month, so we can focus on EF Core/.NET 5. So hopefully we can get stable spatial support out this month.
