### ISSUE TITLE
How to retain time zone information of DateTimeOffset?

### ISSUE THREAD

**Issue by newpost** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#995]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

### The issue
I get  {2019/12/19 22:58:12 +08:00} using ado.net, but {2019/12/19 22:58:12 +00:00} using ef linq to SQL

### Further technical details

MySQL version: 
Operating system: 
Pomelo.EntityFrameworkCore.MySql version:
Microsoft.AspNetCore.App version:

Other details about my project setup:

**Comment by mguinness** [comment]
Not enough information provided.  At a bare minimum we need version numbers requested in template that you left blank and also of the ADO.NET provider (Connector/NET or MySqlConnector).

Also please provide data model, context and connection string, see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/900#issuecomment-546710275 for an example.

**Comment by newpost** [comment]
Pomelo.EntityFrameworkCore.MySql Version is 3.1.0 With NET Core 3.1
`    public class TestDbContext : DbContext
    {
        public TestDbContext()
        {
        }

        public TestDbContext(DbContextOptions<TestDbContext> options)
            : base(options)
        {
        }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseMySql("Server=localhost;User ID=root;Password=xxxx;Database=testdb");
            }
        }

        public virtual DbSet<Student> Student { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Student>(entity =>
            {
                entity.ToTable("student");
                entity.HasKey(e => new { e.Id })
                    .HasName("PRIMARY");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("bigint");
                entity.Property(e => e.Name)
                    .HasColumnName("name")
                    .HasColumnType("varchar(255)");

                entity.Property(e => e.Birthday)
                    .HasColumnName("birthday")
                    .HasColumnType("datetime");
            });
        }
    }


    public class Student
    {
        public long Id { set; get; }
        public string Name { set; get; }

        public DateTimeOffset Birthday { set; get; }
    }`

**Comment by newpost** [comment]
Dapper:
```
using (var connection = new MySqlConnection("Server=localhost;User ID=zhangshi;Password=1234.com;Database=testdb"))
            {
                var stu = connection.Query<Student>("select *from student where name like @Name", new { Name = "\"zs" }).FirstOrDefault();
                Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(stu));
//{"Id":3,"Name":"\"zs","Birthday":"2019-12-26T04:00:00+08:00"}
            }
```
EFCore:
 ```
using (TestDbContext dbContext = new TestDbContext())
            {
                var student = dbContext.Student.Where(x => x.Name == "\"zs").FirstOrDefault();
                Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(student));
            }
//{"Id":3,"Name":"\"zs","Birthday":"2019-12-26T04:00:00+00:00"}
```
The result returned using dapper is correct

**Comment by mguinness** [comment]
Your `Birthday` field should be changed as follows and rerun migration to set database type to `date`.

`[Column(TypeName = "date")]`
`public DateTime Birthday { set; get; }`

Since there is no date type in MySQL that stores timezone, `DateTimeOffset` will flatten to `DateTime(6)` and values will be converted to/from UTC under the hood which which is not what you want.

**Comment by lauxjpn** [comment]
> Since there is no date type in MySQL that stores timezone, DateTimeOffset will flatten to DateTime(6) and values will be converted to ~~/from~~ UTC under the hood [...]

Natively, MySQL does not support datetime values with offsets or time zones. We therefore use the `DateTimeOffset.UtcDateTime` property before sending that value to the database by default and thus saving the UTC value in the table without offset.

This will still result in the same point in time as the original value, but will not retain the offset, which can be seen in the following example. So the UTC value is not converted back to a `System.DateTimeOffset` with an offset, but to one without an offset that still represents UTC time:

```c#
using System;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class Student
    {
        public long Id { set; get; }
        public string Name { set; get; }
        public DateTimeOffset Birthday { set; get; }
    }

    public class Context : DbContext
    {
        public DbSet<Student> Students { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql("server=127.0.0.1;port=3308;user=root;password=;database=Issue995")
                .UseLoggerFactory(LoggerFactory.Create(b => b.AddConsole()))
                .EnableDetailedErrors()
                .EnableSensitiveDataLogging();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Student>(entity =>
            {
                entity.ToTable("student");

                entity.HasKey(e => new { e.Id })
                    .HasName("PRIMARY");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .HasColumnType("bigint");

                entity.Property(e => e.Name)
                    .HasColumnName("name")
                    .HasColumnType("varchar(255)");

                entity.Property(e => e.Birthday)
                    .HasColumnName("birthday")
                    .HasColumnType("datetime");
            });
        }
    }

    internal class Program
    {
        private static void Main()
        {
            var newStudent = new Student
            {
                Name = "zs",
                Birthday = new DateTimeOffset(
                    new DateTime(2000, 1, 1, 0, 0, 0),
                    TimeSpan.FromHours(8))
            };
            
            using (var context = new Context())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.Students.Add(newStudent);
                context.SaveChanges();
            }

            using (var context = new Context())
            {
                var queriedStudent = context.Students.Single();
                
                // has no offset
                Debug.Assert(queriedStudent.Birthday.Offset == TimeSpan.Zero);

                // UTC time without offset = local time + offset
                Debug.Assert(queriedStudent.Birthday == newStudent.Birthday);

                // is correct UTC time
                Debug.Assert(queriedStudent.Birthday == newStudent.Birthday.ToUniversalTime());
                Debug.Assert(queriedStudent.Birthday == new DateTimeOffset(
                    new DateTime(1999, 12, 31, 16, 0, 0),
                    TimeSpan.Zero));
            }
        }
    }
}
```

Whether you want to save birthdays in UTC or local time is up to you. But @mguinness is right, that it usually makes more sense to save birthdays in local time (and as a `date` store type instead of a `datetime`). 

In case you need to congratulate the student at a certain point in his local time or you need the actual time of the birthday (including hour/minutes), you will need to save his local timezone somehow and stick with `System.DateTimeOffset`. In this case, there are multiple options:
* Save the timezone manually in a dedicated column
* Use one of many predefined value converters, that *will* retain the offset for you:
    * https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/819#issuecomment-531132122
    * [Value Conversions](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#built-in-converters)
